### ISSUE TITLE
Record without ipdb

### ISSUE THREAD

**Issue by elsheikh21** [seleniumbase/SeleniumBase#1075]
I would like to record user web actions using `sbase mkrec recording.py --url=http://google.com` . I want some help with the following

1. when the user closes the browser, the recording is saved.
2. I want to remove `import ipdb; ipdb.set_trace()` or automatically enter `c` in terminal and remove 

my script is as follows:

```{python}
def user_prompt_title(filename, url_str):
    url_valid = validate_url(url_str)
    if url_valid:
        if os.path.exists(filename):
            os.remove(filename)
        os.system(f"sbase mkrec {file_name} --url={string_}")
```

desired behavior: 
when the above script is run by user input (irrelevant how to this question) when the user closes the browser. The recording is saved as a pytest file normally

**Comment by mdmintz** [comment]
Hi @elsheikh21 There's a section of https://seleniumbase.io/help_docs/recorder_mode/ that tells you about splitting the main recorder command into 4 separate commands:

```bash
sbase mkfile TEST_NAME.py --rec

pytest TEST_NAME.py --rec -q -s

sbase print ./recordings/TEST_NAME_rec.py -n

cp ./recordings/TEST_NAME_rec.py ./TEST_NAME.py
```

This should give you the flexibility that you need to reach the behavior that you're looking for.
The ``ipdb`` is needed to pause the script for adding manual actions, but if you just run the recorder without the pause (``pytest --rec`` on any script) then it will record the actions already specified by the test, even without an ``ipdb``.

For single-URL recordings, you can call ``self.activate_recorder()`` from your test to activate the recorder for that page alone.

**Comment by elsheikh21** [comment]
Okay perfect, so can I make the recording stop and save to TEST_NAME.py file when user closes browser?

**Comment by mdmintz** [comment]
@elsheikh21 Yes, however ``pytest`` must close the browser (Recorder Mode processing is part of the tearDown phase).

**Comment by elsheikh21** [comment]
@mdmintz Okay perfect, I am sorry but can you please guide me on how to do that? 
Thanks for taking the time to answer my questions :)

**Comment by mdmintz** [comment]
@elsheikh21 Does it work if you just add ``self.activate_recorder()`` inside your test when you want to record?

**Comment by elsheikh21** [comment]
sorry for the naivete of what I am going to ask, but where can I add that line of code?

**Comment by mdmintz** [comment]
@elsheikh21  Anywhere in your test when you want to record.

**Comment by elsheikh21** [comment]
so shall I do `os.system(f"sbase mkfile {file_name} --rec && pytest {file_name} --rec -q -s && sbase print ./recordings/{file_name} -n && cp ./recordings/{file_name} ./{file_name}")` or shall I ignore that and start my script by ?

**Comment by mdmintz** [comment]
@elsheikh21 Just try with ``self.activate_recorder()`` inside your test first.
Add the ``import ipdb; ipdb.set_trace()`` if you need to pause the test.

**Comment by elsheikh21** [comment]
@mdmintz 
okay so I did the following 

```{python}
import validators
from tkinter import messagebox


def start_recording(file_name, string_url):
    string_url = string_url.strip()
    bool_ = validators.url(string_url)
    if not bool_:
        messagebox.askretrycancel(
            "Retry?", 'Please enter a valid URL e.g. "https://google.com"'
        )
    else:
        if os.path.exists(file_name):
            os.remove(file_name)
        os.system(f"sbase mkrec {file_name} --url={string_url}")
```

When I convert the file to `.exe` the output in the command line -when I try to run the exe- is that sbase is not a known command, is there a solution for that?


I have as well tried to implement a class of mine that inherits seleniumBase.BaseClass as follows:

```{python}
from seleniumbase import BaseCase


class MyRecorderTests(BaseCase):
    def __init__(self, *args, **kwargs):
        super(BaseCase, self).__init__(*args, **kwargs)

    def test_recording(self):
        self.activate_recorder()
        # if self.recorder_ext and not self.xvfb:
        # import ipdb; ipdb.set_trace()
```

and I try to invoke `MyRecorderTests.test_recording()`  it outputs the following

```seleniumbase.common.exceptions.OutOfScopeException:
 It looks like you are trying to call a SeleniumBase method
 from outside the scope of your test class's `self` object,
 which is initialized by calling BaseCase's setUp() method.```

**Comment by mdmintz** [comment]
@elsheikh21 For the first part, I'm not sure what tool you're using to covert Python to EXE, but it looks like that tool isn't doing something correctly. (Maybe a bug with that tool?)
For the second part, you can't invoke ``MyRecorderTests.test_recording()`` from within a Python file because you have to run ``test_recording()`` via ``pytest`` from the command-line in order to parse command-line arguments that get processed in the setUp() method before each test. There is a way to perform initialization without using pytest, and here's an example of that: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py
(You can call that with ``python`` instead of using ``pytest``.)

**Comment by elsheikh21** [comment]
@mdmintz For the first part, I am using `pyinstaller` do you recommend something else?

so the convert to exe command is just as follows `pyinstaller main.py` and when it runs, this happens

![image](https://user-images.githubusercontent.com/26064109/142444953-cae628f7-515a-4a77-a7e4-e7cf6fef1d67.png)

**Comment by elsheikh21** [comment]
and that is the full script 

```
import tkinter as tk
import os
import validators
from tkinter import TclError, messagebox
from RecorderTests import MyRecorderTests


def validate_url(url_):
    return validators.url(url_)


def start_recording(file_name, string_url):
    string_url = string_url.strip()
    bool_ = validate_url(string_url)
    if not bool_:
        messagebox.askretrycancel(
            "Retry?", 'Please enter a valid URL e.g. "https://google.com"'
        )
    else:
        if os.path.exists(file_name):
            os.remove(file_name)
            
        # mrt = MyRecorderTests(url=string_url)
        # mrt.test_recording()
        os.system(f"sbase mkrec {file_name} --url={string_url}")



def execute_playback(file_name):
    os.system(f"pytest {file_name} --verbose --capture=no")


def create_tkinter_gui(file_name):
    window = tk.Tk()
    window.title("WEB MKA-E | SCREEVO")
    window.geometry("360x175")
    try:
        window.iconbitmap("logo.ico")
    except TclError:
        pass

    frame = tk.Frame(window)
    frame.pack()

    a = tk.StringVar()
    tk.Label(window, text="Enter URL you would like to automate your process").pack()
    entry = tk.Entry(window, textvariable=a)
    entry.pack()
    entry.focus()
    entry.bind("<Return>", (lambda _: start_recording(file_name, a.get())))
    tk.Button(
        window, text="Record", command=lambda: start_recording(file_name, a.get())
    ).pack()

    tk.Label(window, text="playback your latest recorded actions on the web").pack()
    tk.Button(
        window, text="Playback", command=lambda: execute_playback(file_name)
    ).pack()

    # Bring form to topfront
    window.lift()
    window.attributes("-topmost", True)
    window.after_idle(window.attributes, "-topmost", False)

    window.mainloop()


if __name__ == "__main__":
    file_name = "recording.py"
    create_tkinter_gui(file_name)
```


Pyinstaller v4.7
Python 3.7.11 x64
sbase v2.1.9

**Comment by mdmintz** [comment]
@elsheikh21 I made a small change and it works now:

```python
os.system(f"python -m sbase mkrec {file_name} --url={string_url}")
```

Use ``python -m sbase``

**Comment by elsheikh21** [comment]
![image](https://user-images.githubusercontent.com/26064109/142451383-371aecb8-9b94-4c66-9943-fedc26d81e08.png)
And sbase is installed in Conda env

**Comment by mdmintz** [comment]
@elsheikh21 
Here's a recording I made using the EXE file created with pyinstaller after switching to ``python -m sbase``:
(It works! This is amazing!)

https://user-images.githubusercontent.com/6788579/142454125-1b4a82e7-13be-4842-99bd-aedc79f3ddc6.mov

**Comment by elsheikh21** [comment]
THAT'S AMAZINGGGGGG
I would love to have it working on mine hahahahah
can u let me know what is your pyinstaller command and env vars?

**Comment by mdmintz** [comment]
@elsheikh21 
``pyinstaller main.py`` was all I ran, and it created the ``main`` executable in the ``./dist/main/`` folder. To make it work, I also had to install the latest version of ``seleniumbase`` from outside the virtual environment, which meant 2 installs: (I already had it in my virtual environment, but when the EXE runs, it looks for it on the global environment.) Basically, I had to make sure that ``python -m sbase`` worked right after opening a new command prompt. Once that was working, running from the EXE also worked.

**Comment by mdmintz** [comment]
In case anything else was different, here's the script:

```python
import tkinter as tk
import os
import validators
from tkinter import TclError, messagebox
# from RecorderTests import MyRecorderTests


def validate_url(url_):
    return validators.url(url_)


def start_recording(file_name, string_url):
    string_url = string_url.strip()
    bool_ = validate_url(string_url)
    if not bool_:
        messagebox.askretrycancel(
            "Retry?", 'Please enter a valid URL e.g. "https://google.com"'
        )
    else:
        if os.path.exists(file_name):
            os.remove(file_name)
            
        # mrt = MyRecorderTests(url=string_url)
        # mrt.test_recording()
        os.system(f"python -m sbase mkrec {file_name} --url={string_url}")



def execute_playback(file_name):
    os.system(f"pytest {file_name} --verbose --capture=no")


def create_tkinter_gui(file_name):
    window = tk.Tk()
    window.title("WEB MKA-E | SCREEVO")
    window.geometry("360x175")
    try:
        window.iconbitmap("logo.ico")
    except TclError:
        pass

    frame = tk.Frame(window)
    frame.pack()

    a = tk.StringVar()
    tk.Label(window, text="Enter URL you would like to automate your process").pack()
    entry = tk.Entry(window, textvariable=a)
    entry.pack()
    entry.focus()
    entry.bind("<Return>", (lambda _: start_recording(file_name, a.get())))
    tk.Button(
        window, text="Record", command=lambda: start_recording(file_name, a.get())
    ).pack()

    tk.Label(window, text="playback your latest recorded actions on the web").pack()
    tk.Button(
        window, text="Playback", command=lambda: execute_playback(file_name)
    ).pack()

    # Bring form to topfront
    window.lift()
    window.attributes("-topmost", True)
    window.after_idle(window.attributes, "-topmost", False)

    window.mainloop()


if __name__ == "__main__":
    file_name = "recording.py"
    create_tkinter_gui(file_name)
```

**Comment by elsheikh21** [comment]
Thanks a lot!

**Comment by elsheikh21** [comment]
@mdmintz I have another question, can I make the script run without installing SeleniumBase in the global env?

**Comment by mdmintz** [comment]
Hi @elsheikh21, SeleniumBase can run in both virtual and global environments, but if you're using ``pyinstaller`` to create the EXE file, then it'll run from the global environment (but maybe that's only by default). Perhaps ``pyinstaller`` has docs to show you how to change that, but I only discovered that tool when you mentioned it, so you'd likely know more about ``pyinstaller`` than I do at this moment.

**Comment by elsheikh21** [comment]
@mdmintz Can I run the recorder via python without using `os.system` or `subprocess.Popen` i.e. without executing it as if it is a bash/terminal command?

**Comment by mdmintz** [comment]
@elsheikh21
You can add ``--rec`` to a ``pytest`` run command to run the recorder. Example:

```bash
pytest TEST_NAME.py --rec -q -s
```

You can also call ``self.activate_recorder()`` from within a test, but if you leave the page, the recorder stops unless you reactivate it with ``self.activate_recorder()``.

**Comment by elsheikh21** [comment]
@mdmintz I am trying to activate it from python itself and not using any terminal commands, so when the user presses on Record, it can start recording automatically

**Comment by mdmintz** [comment]
@elsheikh21 Are you trying to avoid using ``pytest`` from the terminal? That can't be avoided unless you use ``nosetests``, which brings you back to the same issue.

**Comment by elsheikh21** [comment]
I am trying not to use anything on command line, as I want this product to be shipped without installing anything -not even python- on the customer side. :/

**Comment by mdmintz** [comment]
@elsheikh21 I'm not sure how you'd be able to avoid using Python to run a Python framework. Perhaps that's something that ``pyinstaller`` provides.

**Comment by elsheikh21** [comment]
@mdmintz avoiding python is easy, the problem now is avoiding using terminal commands such as `sbase`

**Comment by mdmintz** [comment]
@elsheikh21 That may be tricky because ``pytest`` is a terminal command once installed, and therefore it's not simple to avoid using that, especially for a framework that can be considered a pytest plugin.

**Comment by elsheikh21** [comment]
@mdmintz ohh yes this I am making peace with :D 
Is there a way to avoid using command `sbase` in terminal

**Comment by mdmintz** [comment]
@elsheikh21 Yes, just use the following to activate the recorder for a test:

```bash
pytest TEST_NAME.py --rec -q -s
```

**Comment by elsheikh21** [comment]
Okay, thank you
will give it a try. and maybe change my approach to the problem

Thanks again for your help and time

**Comment by elsheikh21** [comment]
@mdmintz I noticed the code in the `examples/desktop_app/`  and I am genuinely happy to be able to contribute 😍

**Comment by mdmintz** [comment]
@elsheikh21 Yes, thank you! I liked it so much that I added that in as a real example, and created a new folder for it with the possibility of adding other useful desktop apps!

**Comment by elsheikh21** [comment]
@mdmintz I will brainstorm a little about some ideas, but if you have an idea of what to do please let me know 
Actually, I did the feature `stop recording upon user prompt via popup message box`
here is my email if needed aelsheikh13[at]gmail[dot]com

**Comment by mdmintz** [comment]
@elsheikh21 Gitter chat is probably the most convenient. It can handle both group and private messaging: https://gitter.im/seleniumbase/SeleniumBase

**Comment by Ashish3080** [comment]
is there a way where i can skip pressing 'c' and hitting 'enter' like run a keyboard listener, where when I press 'end', it sends c in the terminal and hits enter. Because the recording, that was provided by @mdmintz , still had to be stopped by entering c into the terminal to stop the debugging mode.
