### ISSUE TITLE
Improvement: catch the traces gracefully if css collector failed

### ISSUE THREAD

**Issue by miaodahua** [seleniumbase/SeleniumBase#109]
Hi @mdmintz ,

Its me again, as I mentioned in last issue(which is user error actually), the self.assert_text() works, but if it can not recognize the selector from the page, the trace in console is a mess, as you can see from the attached file.

I understand they are debug info from WebDriver which is trying to select the element specified, just wondering if SeleniumBase can handle those info, allow user to close the debug option, or catch them inner of the framework?

It is not a functional issue, but just a improvement request.
[traces.txt](https://github.com/seleniumbase/SeleniumBase/files/1154805/traces.txt)

**Comment by mdmintz** [comment]
Hi @miaodahua. Use "--logging-level=INFO" on the command line where you run the tests. Or make sure you include https://github.com/seleniumbase/SeleniumBase/blob/master/examples/setup.cfg (The setup.cfg file) in the folder where you kick off your test runs. This will keep the test output clean. Did that help?

**Comment by miaodahua** [comment]
@mdmintz  it works. Thank you .
