### ISSUE TITLE
(Windows) OSError when creating basic_test_info.txt for logs when an "sb" fixture test fails.

### ISSUE THREAD

**Issue by radhakrishnanakireddy** [seleniumbase/SeleniumBase#1101]
Hi 
I am getting below error after upgrading seleniumbase to 2.2.4
**E       OSError: [Errno 22] Invalid argument: 'latest_logs//tests/ui/test_loginto_app.py::TestLoginApplication::test_login_1/basic_test_info.txt'** with the below log while running a test

C:\Program Files\Python39\lib\codecs.py:905: OSError

I am facing this issue with every file while creating on windows10 machine, I think we should have fix for every path :-(

Could you please help me to figure it out

**Comment by mdmintz** [comment]
@radhakrishnanakireddy I would need to see the full stack trace to know what SeleniumBase is doing. What run command are you using, and what is your directory structure? The ``./latest_logs/`` folder is where test logs get saved for the latest test run.

**Comment by radhakrishnanakireddy** [comment]
Hi Thanks for the reply, please find the rquired info 
_______________________________________________________________________________________ ERROR at teardown of TestLoginApplication.test_login_1 ________________________________________________________________________________________

request = <SubRequest 'sb' for <Function test_login_1>>

    @pytest.fixture()                                                        
    def sb(request):
        """SeleniumBase as a pytest fixture.
        Usage example: "def test_one(sb):"
        You may need to use this for tests that use other pytest fixtures."""
        from seleniumbase import BaseCase
    
        class BaseClass(BaseCase):
            def setUp(self):
                super(BaseClass, self).setUp()

            def tearDown(self):
                self.save_teardown_screenshot()
                super(BaseClass, self).tearDown()

            def base_method(self):
                pass

        if request.cls:
            request.cls.sb = BaseClass("base_method")
            request.cls.sb.setUp()
            request.cls.sb._needs_tearDown = True
            request.cls.sb._using_sb_fixture = True
            request.cls.sb._using_sb_fixture_class = True
            sb_config._sb_node[request.node.nodeid] = request.cls.sb
            yield request.cls.sb
            if request.cls.sb._needs_tearDown:
>               request.cls.sb.tearDown()

venv\lib\site-packages\seleniumbase\plugins\pytest_plugin.py:1561:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv\lib\site-packages\seleniumbase\plugins\pytest_plugin.py:1547: in tearDown
    super(BaseClass, self).tearDown()
venv\lib\site-packages\seleniumbase\fixtures\base_case.py:11751: in tearDown
    log_helper.log_test_failure_data(
venv\lib\site-packages\seleniumbase\core\log_helper.py:138: in log_test_failure_data
    log_file = codecs.open(basic_file_path, "w+", "utf-8")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = 'latest_logs//tests/ui/test_loginto_app.py::TestLoginApplication::test_login_1/basic_test_info.txt', mode = 'w+b', encoding = 'utf-8', errors = 'strict', buffering = -1

    def open(filename, mode='r', encoding=None, errors='strict', buffering=-1):

        """ Open an encoded file using the given mode and return
            a wrapped version providing transparent encoding/decoding.

            Note: The wrapped version will only accept the object format
            defined by the codecs, i.e. Unicode objects for most builtin
            codecs. Output is also codec dependent and will usually be
            Unicode as well.

            Underlying encoded files are always opened in binary mode.
            The default file mode is 'r', meaning to open the file in read mode.

            encoding specifies the encoding which is to be used for the
            file.

            errors may be given to define the error handling. It defaults
            to 'strict' which causes ValueErrors to be raised in case an
            encoding error occurs.

            buffering has the same meaning as for the builtin open() API.
            It defaults to -1 which means that the default buffer size will
            be used.

            The returned wrapped file object provides an extra attribute
            .encoding which allows querying the used encoding. This
            attribute is only available if an encoding was specified as
            parameter.

        """
        if encoding is not None and \
           'b' not in mode:
            # Force opening of the file in binary mode
            mode = mode + 'b'
>       file = builtins.open(filename, mode, buffering)
E       OSError: [Errno 22] Invalid argument: 'latest_logs//tests/ui/test_loginto_app.py::TestLoginApplication::test_login_1/basic_test_info.txt'

C:\Program Files\Python39\lib\codecs.py:905: OSError

**Folder structure Screenshot :** 
![image](https://user-images.githubusercontent.com/47018449/144478032-4d2772bf-dd0f-4266-84c0-45139d9acf14.png)

used cmd to execute it 
**pytest .\tests\ui\test_loginto_app.py --dashboard --html=report.html --rs**

**Comment by radhakrishnanakireddy** [comment]
> Hi Thanks for the reply, please find the rquired info _______________________________________________________________________________________ ERROR at teardown of TestLoginApplication.test_login_1 ________________________________________________________________________________________
> 
> request = <SubRequest 'sb' for >
> 
> ```
> @pytest.fixture()                                                        
> def sb(request):
>     """SeleniumBase as a pytest fixture.
>     Usage example: "def test_one(sb):"
>     You may need to use this for tests that use other pytest fixtures."""
>     from seleniumbase import BaseCase
> 
>     class BaseClass(BaseCase):
>         def setUp(self):
>             super(BaseClass, self).setUp()
> 
>         def tearDown(self):
>             self.save_teardown_screenshot()
>             super(BaseClass, self).tearDown()
> 
>         def base_method(self):
>             pass
> 
>     if request.cls:
>         request.cls.sb = BaseClass("base_method")
>         request.cls.sb.setUp()
>         request.cls.sb._needs_tearDown = True
>         request.cls.sb._using_sb_fixture = True
>         request.cls.sb._using_sb_fixture_class = True
>         sb_config._sb_node[request.node.nodeid] = request.cls.sb
>         yield request.cls.sb
>         if request.cls.sb._needs_tearDown:
> ```
> 
> > ```
> >           request.cls.sb.tearDown()
> > ```
> 
> venv\lib\site-packages\seleniumbase\plugins\pytest_plugin.py:1561:
> 
> venv\lib\site-packages\seleniumbase\plugins\pytest_plugin.py:1547: in tearDown super(BaseClass, self).tearDown() venv\lib\site-packages\seleniumbase\fixtures\base_case.py:11751: in tearDown log_helper.log_test_failure_data( venv\lib\site-packages\seleniumbase\core\log_helper.py:138: in log_test_failure_data log_file = codecs.open(basic_file_path, "w+", "utf-8")
> 
> filename = 'latest_logs//tests/ui/test_loginto_app.py::TestLoginApplication::test_login_1/basic_test_info.txt', mode = 'w+b', encoding = 'utf-8', errors = 'strict', buffering = -1
> 
> ```
> def open(filename, mode='r', encoding=None, errors='strict', buffering=-1):
> 
>     """ Open an encoded file using the given mode and return
>         a wrapped version providing transparent encoding/decoding.
> 
>         Note: The wrapped version will only accept the object format
>         defined by the codecs, i.e. Unicode objects for most builtin
>         codecs. Output is also codec dependent and will usually be
>         Unicode as well.
> 
>         Underlying encoded files are always opened in binary mode.
>         The default file mode is 'r', meaning to open the file in read mode.
> 
>         encoding specifies the encoding which is to be used for the
>         file.
> 
>         errors may be given to define the error handling. It defaults
>         to 'strict' which causes ValueErrors to be raised in case an
>         encoding error occurs.
> 
>         buffering has the same meaning as for the builtin open() API.
>         It defaults to -1 which means that the default buffer size will
>         be used.
> 
>         The returned wrapped file object provides an extra attribute
>         .encoding which allows querying the used encoding. This
>         attribute is only available if an encoding was specified as
>         parameter.
> 
>     """
>     if encoding is not None and \
>        'b' not in mode:
>         # Force opening of the file in binary mode
>         mode = mode + 'b'
> ```
> 
> > ```
> >   file = builtins.open(filename, mode, buffering)
> > ```
> 
> E OSError: [Errno 22] Invalid argument: 'latest_logs//tests/ui/test_loginto_app.py::TestLoginApplication::test_login_1/basic_test_info.txt'
> 
> C:\Program Files\Python39\lib\codecs.py:905: OSError
> 
> **Folder structure Screenshot :** ![image](https://user-images.githubusercontent.com/47018449/144478032-4d2772bf-dd0f-4266-84c0-45139d9acf14.png)
> 
> used cmd to execute it **pytest .\tests\ui\test_loginto_app.py --dashboard --html=report.html --rs**

**Comment by mdmintz** [comment]
@radhakrishnanakireddy Thank you, I was able to reproduce the issue on Windows (It does not occur on Mac or Linux). I'll work on a fix for this.

**Comment by mdmintz** [comment]
@radhakrishnanakireddy This issue has been resolved in https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.2.5
Let me know if you have any other issues. Thanks for finding this!

**Comment by radhakrishnanakireddy** [comment]
@mdmintz  : Thank you for your fix, but still I see issue with visual report and please find the log below 

=============================================================================================================== ERRORS ================================================================================================================
____________________________________________________________________________________ ERROR at teardown of TestLoginApplication.test_visual_testing ____________________________________________________________________________________

request = <SubRequest 'sb' for <Function test_visual_testing>>

    @pytest.fixture()
    def sb(request):
        """SeleniumBase as a pytest fixture.
        Usage example: "def test_one(sb):"
        You may need to use this for tests that use other pytest fixtures."""
        from seleniumbase import BaseCase

        class BaseClass(BaseCase):
            def setUp(self):
                super(BaseClass, self).setUp()

            def tearDown(self):
                self.save_teardown_screenshot()
                super(BaseClass, self).tearDown()

            def base_method(self):
                pass

        if request.cls:
            request.cls.sb = BaseClass("base_method")
            request.cls.sb.setUp()
            request.cls.sb._needs_tearDown = True
            request.cls.sb._using_sb_fixture = True
            request.cls.sb._using_sb_fixture_class = True
            sb_config._sb_node[request.node.nodeid] = request.cls.sb
            yield request.cls.sb
            if request.cls.sb._needs_tearDown:
>               request.cls.sb.tearDown()

venv\lib\site-packages\seleniumbase\plugins\pytest_plugin.py:1561:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv\lib\site-packages\seleniumbase\plugins\pytest_plugin.py:1547: in tearDown
    super(BaseClass, self).tearDown()
venv\lib\site-packages\seleniumbase\fixtures\base_case.py:11906: in tearDown
    self.__process_visual_baseline_logs()
venv\lib\site-packages\seleniumbase\fixtures\base_case.py:9572: in __process_visual_baseline_logs
    shutil.copy(baseline_path, baseline_copy_path)
C:\Program Files\Python39\lib\shutil.py:427: in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

src = 'visual_baseline/test_visual_testing/test_visual_testing_dashboard_page\\baseline.png', dst = 'latest_logs/seleniumbase.plugins.pytest_plugin.BaseClass.base_method\\baseline.png'

    def copyfile(src, dst, *, follow_symlinks=True):
        """Copy data from src to dst in the most efficient way possible.

        If follow_symlinks is not set and src is a symbolic link, a new
        symlink will be created instead of copying the file it points to.

        """
        sys.audit("shutil.copyfile", src, dst)

        if _samefile(src, dst):
            raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

        file_size = 0
        for i, fn in enumerate([src, dst]):
            try:
                st = _stat(fn)
            except OSError:
                # File most likely does not exist
                pass
            else:
                # XXX What about other special files? (sockets, devices...)
                if stat.S_ISFIFO(st.st_mode):
                    fn = fn.path if isinstance(fn, os.DirEntry) else fn
                    raise SpecialFileError("`%s` is a named pipe" % fn)
                if _WINDOWS and i == 0:
                    file_size = st.st_size

        if not follow_symlinks and _islink(src):
            os.symlink(os.readlink(src), dst)
        else:
            with open(src, 'rb') as fsrc:
                try:
>                   with open(dst, 'wb') as fdst:
E                   FileNotFoundError: [Errno 2] No such file or directory: 'latest_logs/seleniumbase.plugins.pytest_plugin.BaseClass.base_method\\baseline.png'

C:\Program Files\Python39\lib\shutil.py:266: FileNotFoundError

**Comment by mdmintz** [comment]
@radhakrishnanakireddy Thank you for finding that new issue. I created a separate ticket for it: https://github.com/seleniumbase/SeleniumBase/issues/1103
