### ISSUE TITLE
The save_screenshot_to_logs failed when the window was closed

### ISSUE THREAD

**Issue by sensall** [seleniumbase/SeleniumBase#1118]
**当打开一个新窗口时，由于窗口出错而关闭，使用save_screenshot_to_logs就会出错！**
```
def save_screenshot_to_logs(
        self, name=None, selector=None, by=By.CSS_SELECTOR
    ):
        self.wait_for_ready_state_complete()
        test_logpath = os.path.join(self.log_path, self.__get_test_id())
        self.__create_log_path_as_needed(test_logpath)
```

```
    def wait_for_ready_state_complete(self, timeout=None):
        """ Waits for the "readyState" of the page to be "complete".
            Returns True when the method completes. """
        self.__check_scope()
        self.__check_browser()
```

```
    def __check_browser(self):
        """This method raises an exception if the window was already closed."""
        active_window = None
        try:
            active_window = self.driver.current_window_handle  # Fails if None
        except Exception:
            pass
        if not active_window:
            raise NoSuchWindowException("Active window was already closed!")
```

**由于这个原因导致截图失败！
tips: WARNING: Unable to get screenshot!**

**Comment by mdmintz** [comment]
Hello @sensall, the ``self.save_screenshot_to_logs()`` method is expected to fail if the window is closed because there's no longer a window to take a screenshot from. Your tests should not be closing the window on their own because that part is supposed to happen automatically in the ``tearDown()`` step.

**Comment by mdmintz** [comment]
If a test fails, it will automatically save a screenshot of the last page to the ``latest_logs/`` folder, assuming that the window is still open to take the screenshot.

**Comment by sensall** [comment]
> Hello @sensall, the `self.save_screenshot_to_logs()` method is expected to fail if the window is closed because there's no longer a window to take a screenshot from. Your tests should not be closing the window on their own because that part is supposed to happen automatically in the `tearDown()` step.

HI @mdmintz, I did not close the window, but the browser closed the window automatically when executing the use case, so I did not take the screenshot of the error

**Comment by sensall** [comment]
> If a test fails, it will automatically save a screenshot of the last page to the `latest_logs/` folder, assuming that the window is still open to take the screenshot.

 it not automatically save a screenshot of the last page to the `latest_logs/` folder, page_source.html is "<h3>Warning: Unable to get page source!</h3>
<h4>The browser window was either unreachable, unresponsive, or closed prematurely!</h4>"
