### ISSUE TITLE
convert_xpath_to_css(xpath) issue 

### ISSUE THREAD

**Issue by webmoskal** [seleniumbase/SeleniumBase#1126]
Have following xpath 
`//tr[@class='MuiTableRow-root MuiTableRow-hover'][1]//td[@class='MuiTableCell-root MuiTableCell-body MuiTableCell-alignCenter'][2]//span[@class='MJX_Assistive_MathML']`

Believe expected:
`tr.MuiTableRow-root.MuiTableRow-hover:nth-of-type(1) td.MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignCenter:nth-of-type(2) span.MJX_Assistive_MathML`

Actual: 2.2.10
`tr.MuiTableRow-root.MuiTableRow-hover"][1] td[class="MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignCenter"][2] span[class="MJX_Assistive_MathML`

**Comment by mdmintz** [comment]
I see the issue. I'll have it fixed in the next release.
