### ISSUE TITLE
Dockerfile has minor error.

### ISSUE THREAD

**Issue by benjamin-kirkbride** [seleniumbase/SeleniumBase#1147]
https://github.com/seleniumbase/SeleniumBase/blob/master/Dockerfile#L97-L98

Chromedriver is moved to `/usr/local/bin`, but is then attempted to be accessed at `/usr/bin`. Build fails due to file not found by `chmod`

**Comment by mdmintz** [comment]
Thanks for the catch! I'm putting together the next release with a fix for this!

**Comment by mdmintz** [comment]
@benjamin-kirkbride This was fixed in https://github.com/seleniumbase/SeleniumBase/pull/1149 and released as part of https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.3.4

**Comment by mdmintz** [comment]
And thank you @benjamin-kirkbride for helping with this! Let me know if you find any more issues!
