### ISSUE TITLE
Dockerfile didn't successfully install SeleniumBase

### ISSUE THREAD

**Issue by benjamin-kirkbride** [seleniumbase/SeleniumBase#1148]
https://seleniumbase.io/integrations/docker/ReadMe/#2-create-your-seleniumbase-docker-environment

`docker-machine` is not supported/archived.

`docker run seleniumbase ./run_docker_test_in_chrome.sh` and `docker run seleniumbase ./run_docker_test_in_firefox.sh` do not work anymore with the following error (both have basically the same error):

```
***** SeleniumBase Docker Machine *****
Running example SeleniumBase test from Docker with headless Firefox...
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --browser=firefox --headless
  inifile: /SeleniumBase/examples/pytest.ini
  rootdir: /SeleniumBase/examples
```

**Comment by benjamin-kirkbride** [comment]
The issue appears to be that `seleniumbase` does not actually get installed. `exec`'ing into the container and `pip install seleniumbase` causes the test scripts to actually run.

**Comment by benjamin-kirkbride** [comment]
Changing https://github.com/seleniumbase/SeleniumBase/blob/master/Dockerfile#L86 to `RUN cd /SeleniumBase && pip install .` fixed it.

**Comment by mdmintz** [comment]
Thanks for the catch! I'm putting together the next release with a fix for this!

**Comment by benjamin-kirkbride** [comment]
Thanks for the prompt response, have to say I am extremely impressed with SeleniumBase so far. 

I think that line 85 of the Dockerfile could probably go too? I think that the pip install also gets all the dependencies. Also, would it make sense to just have sbase install the drivers itself, instead of doing so manually as part of the Dockerfile?

**Comment by mdmintz** [comment]
@benjamin-kirkbride Yes, technically the newer ``sbase install chromedriver`` and ``sbase install geckodriver`` do install the drivers, and ``--path`` also copies to the PATH, but to avoid any Docker surprises, and to make sure I still have an alternative way for downloading drivers, it might be alright (just for Docker) to have the detailed steps that would automatically get performed when using the newer driver install way. And the ``requirements.txt`` file does have a few additional dependencies such as ``flake8``, which isn't required, but can be useful for writing clean code. I'll have the pull request ready in 20 minutes.

**Comment by mdmintz** [comment]
@benjamin-kirkbride This was fixed in https://github.com/seleniumbase/SeleniumBase/pull/1149 and released as part of https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.3.4

**Comment by mdmintz** [comment]
And thank you @benjamin-kirkbride for helping with this! Let me know if you find any more issues!
