### ISSUE TITLE
Excuse me, how to make “value” get 3 different types of values?

### ISSUE THREAD

**Issue by tengfei-jiao** [seleniumbase/SeleniumBase#1165]
@parameterized.expand(
        [
            ["99"],
            ["99.09"],
            ["101"],
        ]
    )
    # @pytest.mark.parametrize("value", ["101", "98", "100"])
    @pytest.mark.smoke
    @allure.title("分润方式按照固定金额，编辑成功")
    def test_012(self, value):
        self.login()
        self.type(专家管理.分润_输入金额_输入框, value)

**Comment by mdmintz** [comment]
Hi @tengfei-jiao, Here is how:

```python
from parameterized import parameterized
from seleniumbase import BaseCase

class Tests(BaseCase):
    @parameterized.expand(
        [
            ["A"],
            ["B"],
            ["C"],
        ]
    )
    def test_parameterized(self, value):
        self.open(URL)
        self.type(SELECTOR, value)
```

**Comment by tengfei-jiao** [comment]
When I click the green triangle symbol on the left of def, an error is reported


collecting ... ERROR: not found: F:\auto-test-seleniumbase-withvenv\auto-test-seleniumbase\project_demo_001\远程专家服务\test_专家管理.py::ExpertManage::test_012
collected 0 items                                                              (no name 'F:\\auto-test-seleniumbase-withvenv\\auto-test-seleniumbase\\project_demo_001\\远程专家服务\\test_专家管理.py::ExpertManage::test_012' in any of [<UnitTestCase ExpertManage>])
============================ no tests ran in 0.03s ============================

Process finished with exit code 4

Empty suite

**Comment by mdmintz** [comment]
@tengfei-jiao I'm not sure what you are referring to, because I don't have access to your app, but here is a working example of test parameterization:

https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py

**Comment by tengfei-jiao** [comment]
![企业微信截图_16415623783574](https://user-images.githubusercontent.com/77912533/148623404-c7c7b729-43df-40ba-bb29-3533b66c7a81.png)
when i click green ，have a error

**Comment by tengfei-jiao** [comment]
![企业微信截图_16416017052073](https://user-images.githubusercontent.com/77912533/148623735-df0765dc-b8cd-4d40-99f3-8291a9c3d011.png)

I spent a month talking about the product documentation. After learning it, you wrote it very well. I've never seen such an example of the source code. I think I must save it for you

**Comment by tengfei-jiao** [comment]
I ran pytest on the command line with the same error

**Comment by mdmintz** [comment]
@tengfei-jiao  Try removing this line: ``@allure.title(...)`` and see if the error still occurs.

**Comment by tengfei-jiao** [comment]
i removed  @allure.title(...)  of  class and def test_012，but  i have a same error

**Comment by mdmintz** [comment]
@tengfei-jiao The test needs to be run using "pytest". Maybe you have to run that test from the command-line because the green triangle might only be running the test with "python" instead of "pytest". I cannot determine the issue from what I see because I'm not sure how your IDE is configured. Here's a working example:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py
See if you have any trouble running that, as a start.

**Comment by tengfei-jiao** [comment]
Thank you very much for your support. Next, I will debug it myself. There is one more question:
     @pytest.mark.smoke
     @allure.title("Enter the application time, click search, and search for the specified data")
     def test_004(self):
         self.enter_expert_review()
         self.type(Expert review. Application time_start time, "2021-11-01")
         self.type(Expert review. Application time_end date, "2021-11-30")
         self.click(expert review.search)
         self.assert_in("2021-11", self.get_text(Expert review. Form_application time))
         **print(self.get_text(expert review. form_application time))** 


I can't print the content of print on the console. I read all your issues, and vaguely remember which configuration file to change here?

**Comment by mdmintz** [comment]
@tengfei-jiao Put a https://github.com/seleniumbase/SeleniumBase/blob/master/pytest.ini file in the folder where you run your tests. Or, if running from the command-line with ``pytest``, add ``-s`` as a command-line option.
