### ISSUE TITLE
The window will close when I use yield to run teardown

### ISSUE THREAD

**Issue by hipeyeking** [seleniumbase/SeleniumBase#1169]
I have a fixture in conftest like this:
@pytest.fixture()
def open(sb):
    sb.open("https://www.google.com")
    yield 
    sb.open("https://www.youtube.com")

and i have a test case like this :
@pytest.mark.positive
def test_google(sb ,open):
    pass

The window will close when the setup step finish,so the teardown will fail
![image](https://user-images.githubusercontent.com/42728057/148879067-6abd5cc9-2e78-44a9-9715-d7318fb4d1b3.png)

**Comment by mdmintz** [comment]
@hipeyeking Your syntax looks incorrect. You shouldn't need to use ``yield`` at all. Here's an example of using the ``sb`` fixture correctly:

```python
def test_sb_fixture_with_no_class(sb):
    sb.open("https://google.com/ncr")
    sb.type('input[title="Search"]', 'SeleniumBase\n')
    sb.click('a[href*="github.com/seleniumbase/SeleniumBase"]')
    sb.click('a[title="seleniumbase"]')
```

--------

Here's a more complex example using the ``sb`` fixture and page objects:

```python
class LoginPage:
    def login_to_swag_labs(self, sb, username):
        sb.open("https://www.saucedemo.com")
        sb.type("#user-name", username)
        sb.type("#password", "secret_sauce")
        sb.click('input[type="submit"]')

class MyTests:
    def test_swag_labs_login(self, sb):
        LoginPage().login_to_swag_labs(sb, "standard_user")
        sb.assert_element("#inventory_container")
        sb.assert_element('div:contains("Sauce Labs Backpack")')
```

--------

For more info, see https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md

**Comment by hipeyeking** [comment]
> @hipeyeking Your syntax looks incorrect. You shouldn't need to use `yield` at all. Here's an example of using the `sb` fixture correctly:
> 
> ```python
> def test_sb_fixture_with_no_class(sb):
>     sb.open("https://google.com/ncr")
>     sb.type('input[title="Search"]', 'SeleniumBase\n')
>     sb.click('a[href*="github.com/seleniumbase/SeleniumBase"]')
>     sb.click('a[title="seleniumbase"]')
> ```
> 
> Here's a more complex example using the `sb` fixture and page objects:
> 
> ```python
> class LoginPage:
>     def login_to_swag_labs(self, sb, username):
>         sb.open("https://www.saucedemo.com")
>         sb.type("#user-name", username)
>         sb.type("#password", "secret_sauce")
>         sb.click('input[type="submit"]')
> 
> class MyTests:
>     def test_swag_labs_login(self, sb):
>         LoginPage().login_to_swag_labs(sb, "standard_user")
>         sb.assert_element("#inventory_container")
>         sb.assert_element('div:contains("Sauce Labs Backpack")')
> ```
> 
> For more info, see https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md

Thank you for your answer
Maybe my expression is not complete enough

 fixture in conftest like this:
@pytest.fixture()
def add_group_then_delete(sb):
    sb.open("https://www.xxxx.com")
    sb.click(ADD_BUTTON)
    sb.update_text("XPATH","XXXX")
    sb.click(CONFIRM_BUTTON)
    yeild 
    sb.click(DELETE_BUTTON)
    sb.click(CONFIRM_BUTTON)


test case like this :

@pytest.mark.positive
def test_add(sb ,add_group_then_delete):
   sb.assert_title('XXXX')

My goal is to verify the elements after the group is created, and then delete the group。
However, now after I create the group, the window will close directly, and I can't delete the teardown of the group

**Comment by mdmintz** [comment]
You'll have to use Syntax Format 2 if you want to customize the setUp() and tearDown() methods. (See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md for more info)

```python
from seleniumbase import BaseCase

class BaseTestCase(BaseCase):
    def setUp(self):
        super(BaseTestCase, self).setUp()
        sb.open(URL)
        sb.click(ADD_BUTTON)
        sb.type(SELECTOR, "XXXX")
        sb.click(CONFIRM_BUTTON)

    def tearDown(self):
        self.save_teardown_screenshot()
        sb.click(DELETE_BUTTON)
        sb.click(CONFIRM_BUTTON)
        super(BaseTestCase, self).tearDown()

class MyTests(BaseTestCase):
    @pytest.mark.positive
    def test_add(self):
        sb.assert_title('XXXX')
```

**Comment by hipeyeking** [comment]
> You'll have to use Syntax Format 2 if you want to customize the setUp() and tearDown() methods. (See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md for more info)
> 
> ```python
> from seleniumbase import BaseCase
> 
> class BaseTestCase(BaseCase):
>     def setUp(self):
>         super(BaseTestCase, self).setUp()
>         sb.open(URL)
>         sb.click(ADD_BUTTON)
>         sb.type(SELECTOR, "XXXX")
>         sb.click(CONFIRM_BUTTON)
> 
>     def tearDown(self):
>         self.save_teardown_screenshot()
>         sb.click(DELETE_BUTTON)
>         sb.click(CONFIRM_BUTTON)
>         super(BaseTestCase, self).tearDown()
> 
> class MyTests(BaseTestCase):
>     @pytest.mark.positive
>     def test_add(self):
>         sb.assert_title('XXXX')
> ```

Great! It works! thanks!
About selemiumbase, so I can not use yeild with pytest in conftest.py to run teardown ?

**Comment by mdmintz** [comment]
Correct. Don’t use `yield`. Instead, use one of the existing syntax formats for structuring tests.
