### ISSUE TITLE
Seeing errors when trying to validate text from PDF files

### ISSUE THREAD

**Issue by praveenraj123** [seleniumbase/SeleniumBase#1180]
Hi team 

My scenario is to verify the pdf file data. we tried pdf file validation selenium base function but it was not working it is throwing some  authorization error so we focus to add the chrome browser capability  **"plugins.always_open_pdf_externally": True**  but we unable to add capabilities .

we tired below ways: 
1 Add command line argument  --cap-string = 'plugins.always_open_pdf_externally: True'
2 Add command line argument  --cap_file = capabilities/CAP_FILE.py
3  Add capability inside of the selenium base core folder venv/Lib/site-packages/seleniumbase/core/browser_launcher.py
its working fine. 

Caps file 
from seleniumbase.core.download_helper import downloads_path

desired_cap = {
    "download.default_directory": downloads_path,
    "local_discovery.notifications_enabled": False,
    "credentials_enable_service": False,
    "download.prompt_for_download": False,
    "download.directory_upgrade": True,
    "safebrowsing.enabled": False,
    "safebrowsing.disable_download_protection": True,
    "default_content_setting_values.notifications": 0,
    "default_content_settings.popups": 0,
    "managed_default_content_settings.popups": 0,
    "content_settings.exceptions.automatic_downloads.*.setting": 1,
    "profile.password_manager_enabled": False,
    "profile.default_content_setting_values.notifications": 0,
    "profile.default_content_settings.popups": 0,
    "profile.managed_default_content_settings.popups": 0,
    "profile.default_content_setting_values.automatic_downloads": 1,
    "plugins.always_open_pdf_externally": True
}

Kindly provide your  valuable suggestion to fix this issue.

**Comment by mdmintz** [comment]
Desired capabilities are specific to connecting to remote Selenium Grids that use the capabilities set there. There's a ReadMe about that here: https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities

However, that's unrelated to what you're trying to accomplish, which is parsing/verifying text from PDF files that may be password-protected. For that, here are the relevant method calls with all the available args:

```python
self.get_pdf_text(
    pdf, page=None, maxpages=None, password=None,
    codec='utf-8', wrap=False, nav=False, override=False)

self.assert_pdf_text(
    pdf, text, page=None, maxpages=None, password=None,
    codec='utf-8', wrap=True, nav=False, override=False)
```

There's a password argument, which lets you open PDF files that set a password. The PDF can't be opened externally if you want Selenium to be able to access it.

**Comment by praveenraj123** [comment]
Hi @mdmintz ,

Thanks for your response 

we are trying to download simple PDF file without password and trying to access the content 
but I'm facing issue downloading the file to my local disk in run time 

kindly provide your valuable suggestion.

Thanks 
Praveen raj

**Comment by mdmintz** [comment]
Is there a stack trace you can provide, or any code that you may have used? Did you try using: ``self.get_pdf_text()``?

**Comment by praveenraj123** [comment]
hi @mdmintz 

please have look at error trace 

self = <test_file_download.FileDownload testMethod=test_tc03_read_pdf>
pdf = 'mywebsite/pdfprint.do?hdn_button=ViewDocument&id=653263&documentFileType=4'
page = None, maxpages = 0, password = '', codec = 'utf-8', wrap = False
nav = False, override = False

    def get_pdf_text(self, pdf, page=None, maxpages=None,
                     password=None, codec='utf-8', wrap=False, nav=False,
                     override=False):
        """ Gets text from a PDF file.
            PDF can be either a URL or a file path on the local file system.
            @Params
            pdf - The URL or file path of the PDF file.
            page - The page number (or a list of page numbers) of the PDF.
                    If a page number is provided, looks only at that page.
                        (1 is the first page, 2 is the second page, etc.)
                    If no page number is provided, returns all PDF text.
            maxpages - Instead of providing a page number, you can provide
                       the number of pages to use from the beginning.
            password - If the PDF is password-protected, enter it here.
            codec - The compression format for character encoding.
                    (The default codec used by this method is 'utf-8'.)
            wrap - Replaces ' \n' with ' ' so that individual sentences
                   from a PDF don't get broken up into separate lines when
                   getting converted into text format.
            nav - If PDF is a URL, navigates to the URL in the browser first.
                  (Not needed because the PDF will be downloaded anyway.)
            override - If the PDF file to be downloaded already exists in the
                       downloaded_files/ folder, that PDF will be used
                       instead of downloading it again. """
        import warnings
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=UserWarning)
            from pdfminer.high_level import extract_text
        if not password:
            password = ''
        if not maxpages:
            maxpages = 0
        if not pdf.lower().endswith('.pdf'):
>           raise Exception("%s is not a PDF file! (Expecting a .pdf)" % pdf)
E           Exception: https:mywebsite/cf/pdfprint.do?hdn_button=ViewDocument&id=653263&documentFileType=4 is not a PDF file! (Expecting a .pdf)

venv\lib\site-packages\seleniumbase\fixtures\base_case.py:3026: Exception

**Comment by mdmintz** [comment]
Your PDF file URL must end in ``.pdf``.
You should try the examples:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_pdf_asserts.py
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_chinese_pdf.py

**Comment by praveenraj123** [comment]
hi @mdmintz  

Thanks for your updates . no use its not working 
  
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_pdf_asserts.py
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_chinese_pdf.py

**Comment by praveenraj123** [comment]
Hi  @mdmintz  

Thanks  for your response but  i tried above mentioned function but our application we are not download file through web service because they used some security  purpose. this PDF file URL https://nostarch.com/download/Automate_the_Boring_Stuff_dTOC.pdf
 its working for us .
 but we try to download pdf url as
  **https:mywebsite/cf/pdfprint.do?hdn_button=ViewDocument&id=653263&documentFileType=4**    its not normal PDF URL 

So we tried to add  chrome browser capability  to selenium base Framework but  we unable to add fallowing capability **"plugins.always_open_pdf_externally", true**   

This same capability we used existing java framework its working and now migrate to seleniumbase frame work  now we faced this issue 
**Once i add that capability once i click that link the PDF file automatically download in default download location** 

Note : we manually add this capability in selenium base launch browser py file in our Frame work its working fine with out any issue  

kindly provide your valuable solution

**Comment by mdmintz** [comment]
That looks like a malformed URL. Your ``https:`` is missing the ``//`` directly after it. You'll need a valid URL that ends with ``.pdf``.

There are a few other methods you can use for downloading files:

```python
self.download_file(file_url, destination_folder=None)

self.save_file_as(file_url, new_file_name, destination_folder=None)
```

You'll still need a valid URL for those to work.

For the meantime, if you need that capability set, you can spin up a basic webdriver browser (non-SeleniumBase) from within a SeleniumBase test. Then if you set ``self.driver`` to that new driver, you'll be able to use SeleniumBase methods with it.

```python
from seleniumbase import BaseCase

class lTests(BaseCase):
    def test_something(self):
        self.driver.quit()
        
        from selenium import webdriver
        from selenium.webdriver.chrome.service import Service as ChromeService
        options = webdriver.ChromeOptions()
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option("useAutomationExtension", False)
        # Set any other options you need
        service = ChromeService()

        self.driver = webdriver.Chrome(service=service, options=options)
        
        # Now use SeleniumBase methods as needed with "self.*"

```

**Comment by praveenraj123** [comment]
HI @mdmintz 

Thanks for your response . we tried your code but we faced bellow mentioned error trace  **service = ChromeService()
E       TypeError: __init__() missing 1 required positional argument: 'executable_path'**  

Than we passed  chrome driver  location path but we faced --init-- error in remote driver class

**Comment by mdmintz** [comment]
I've updated the code. And this time I had time to test it: 🙂

```python
from seleniumbase import BaseCase

class Tests(BaseCase):
    def test_something(self):
        self.driver.quit()
        
        from selenium import webdriver
        chrome_options = webdriver.ChromeOptions()
        prefs = {
            "download.prompt_for_download": False,
            "content_settings.exceptions.automatic_downloads.*.setting": 1,
            "plugins.always_open_pdf_externally": True,
            "profile.default_content_setting_values.automatic_downloads": 1,
        }
        self.driver = webdriver.Chrome(options=chrome_options)

        # Now use SeleniumBase methods as needed with "self.*"
```

**Comment by mdmintz** [comment]
Additionally, SeleniumBase ``2.4.1`` adds the option to open PDF files externally with ``--external-pdf``: https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.4.1
