### ISSUE TITLE
run multi testcases but only open browser once

### ISSUE THREAD

**Issue by cjydayang** [seleniumbase/SeleniumBase#119]
Hi @mdmintz, a quetion may ask for your help when using SeleiumBase:

Such as the example “my_test_suite.py”,this suite contains 4 testcases，everytime run a testcase，browser will open once，so is there any method that run the testsuite only open browser once？

I come up with a method that use “setUpClass” and “tearDownClass” method instead of “setUP” and “tearDown”，but i don‘t know how to modify base_case.py in SeleniumBase(Only modify that two method may influence other method).
Hope you can give me some advice.
Thanks!

**Comment by mdmintz** [comment]
Hi @cjydayang , To make sure that every test has a fresh environment and cache, each one will spin up and spin down a new window each time. This is the expected behavior. If you want 4 tests to use the same window, then you can combine all of them into a single test. That's probably your best bet.

**Comment by cjydayang** [comment]
@mdmintz Thanks for your reply, I understand now.

**Comment by mdmintz** [comment]
@cjydayang  There's a ``pytest`` command-line option (``--rs``) in SeleniumBase that makes tests reuse the browser session between all tests.

```python
pytest --rs
```

It was added a few years ago. I forgot to update this ticket then.
