### ISSUE TITLE
click link read PDF in memory

### ISSUE THREAD

**Issue by sridharaiyer** [seleniumbase/SeleniumBase#1191]
When we perform the `click` action, we know that if the link opens a PDF file then Seleniumbase downloads the PDF file under the `{current_directory}/downloaded_files` directory. What can be done to read the file (in this case it is PDF but it could be any format) in memory and not download it locally?

**Comment by mdmintz** [comment]
Hello @sridharaiyer, You should check out https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_get_pdf_text.py
You can read the PDF without downloading it.

**Comment by sridharaiyer** [comment]
Thank you sir.
I think in my application, it is a Javascript embedded in the link that is making it to download when clicking. I don't get a direct URL to the PDF. So I was able to do something like this which is working fine. Let me know what you think.

```
        self.click('Link to the PDF Doc')        
        downloaded_files_path = Path.joinpath(Path.cwd(), 'downloaded_files')
        pdf_path = str(max(downloaded_files_path.glob('*.pdf'), key=lambda f: f.stat().st_ctime))
        pdf_text = self.get_pdf_text(pdf_path)
        # Using this pdf_text to find a substrings using simple Python string based logics
        self.assert_pdf_text(pdf_path, '609.19')
```

**Comment by mdmintz** [comment]
If it works, then great. More examples here if you need them: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_pdf_asserts.py
