### ISSUE TITLE
Browser not running in maximized window

### ISSUE THREAD

**Issue by spsch** [seleniumbase/SeleniumBase#121]
Hello @mdmintz , I have a small question about browser_launcher module; as I understood, this one is taking care about set up of chosen browser - now I want to start Chrome in maximized window, so I added
`chrome_options.add_experimental_option("prefs", prefs)
            chrome_options.add_argument("--allow-file-access-from-files")
            chrome_options.add_argument("--allow-running-insecure-content")
            chrome_options.add_argument("--start-maximized")
            return webdriver.Chrome(chrome_options=chrome_options)`
but when running the test (nosetests), Chrome will not respect it. What I am missing? Thank you in advance.

**Comment by mdmintz** [comment]
Hi @spsch ,
Try using: `chrome_options.add_argument("--kiosk")` instead, assuming you're using a MAC or Linux machine. Or use both `--kiosk` AND `--start-maximized` to include both MAC/Linux and Windows users for that. And rerun `python setup.py install` after you make changes to browser_launcher.py for your changes to take effect. Let me know if you're having any issues with that.

**Comment by spsch** [comment]
Thank you @mdmintz for help, it is actually on Windows, when trying on linux box everything is working as expected including adding the option in mentioned file. Unfortunately on Win10 this issue still remains, but it seems it has something common to virtualenv and 2.7/3 python aside installation. Anyway thank you for great tool and good work.

**Comment by mdmintz** [comment]
Let me know if you encounter any more issues. There have been many improvements over the past few years.
