### ISSUE TITLE
Selenium Undetectable autobot

### ISSUE THREAD

**Issue by LeaDer-E** [seleniumbase/SeleniumBase#1211]
Hello, i'm need to know how can i make the browser didn't detected that it's auto-bot with selenium..
sorry for bad English <3

**Comment by mdmintz** [comment]
SeleniumBase lets you change the User Agent from the command-line using ``--agent=STRING``. That can make your browser appear as different as you want it to be. There are also some default options that it sets, which may help.

If that's not enough, here are some resources on evading Selenium-detection:

https://github.com/ultrafunkamsterdam/undetected-chromedriver

https://github.com/diprajpatra/selenium-stealth

https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver?rq=1

https://stackoverflow.com/a/52108199/7058266

**Comment by LeaDer-E** [comment]
> SeleniumBase lets you change the User Agent from the command-line using ``--agent=STRING``. That can make your browser appear as different as you want it to be. There are also some default options that it sets, which may help.
> 
> If that's not enough, here are some resources on evading Selenium-detection:
> 
> https://github.com/ultrafunkamsterdam/undetected-chromedriver
> 
> https://github.com/diprajpatra/selenium-stealth
> 
> https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver?rq=1
> 
> https://stackoverflow.com/a/52108199/7058266
> 

Thanks for helping 🌹

**Comment by LeaDer-E** [comment]
for sorry all method didn't work
