### ISSUE TITLE
How to add options

### ISSUE THREAD

**Issue by c350147221** [seleniumbase/SeleniumBase#1219]
How to add options？

as follows

    opt = Options()
    opt.add_experimental_option("prefs", {"profile.default_content_setting_values.media_stream_mic": 1,
                                          "profile.default_content_setting_values.media_stream_camera": 1,
                                          "profile.default_content_setting_values.geolocation": 1,
                                          "profile.default_content_setting_values.notifications": 1})
    driver = webdriver.Chrome("chromedriver", options=opt)

**Comment by mdmintz** [comment]
@c350147221 There's ``--chromium-arg=ARG`` for a comma-separated list of Chromium args, but that's for ``chrome_options.add_argument()``. For changing the profile, you'll need to override ``get_new_driver()`` from BaseCase. 
Here's an example of that:

```python
from selenium import webdriver
from seleniumbase import BaseCase


class OverrideDriverTest(BaseCase):

    def get_new_driver(self, *args, **kwargs):
        """ This method overrides get_new_driver() from BaseCase. """
        options = webdriver.ChromeOptions()
        options.add_experimental_option(
            "excludeSwitches", ["enable-automation"]
        )
        options.add_experimental_option("useAutomationExtension", False)
        if self.headless:
            options.add_argument("--headless")
        return webdriver.Chrome(options=options)

    def test_simple(self):
        self.open("https://seleniumbase.io/demo_page")
        self.assert_text("Demo Page", "h1")
```
