### ISSUE TITLE
 loop, selenium open in new tab

### ISSUE THREAD

**Issue by LeaDer-E** [seleniumbase/SeleniumBase#1227]
### 1. **First:** How can I open a link in a new tab page using Selenium, if I have my xpath and let's say this is:

`
 ('//*[@id="app"]/div[1]/div[1]/div[1]/a')
`

### 2. **The second:** I have three lines of selector and xpath,, How can I increment any one of them to make them 100 lines without typing them manually, please look at this picture to know what i mean :smile: 

sorry for bad English :rose: 
![Screenshot at 2022-02-18 01-39-35](https://user-images.githubusercontent.com/99460904/154591455-a4922a07-cd44-428b-ab9e-db8aaa5b9ae4.png)

**Comment by mdmintz** [comment]
self.get_attribute(selector, “href”) gets the link of an element.
self.open_new_window() opens a new window.
Now you can open that url in a new window with self.open(url)

Use a for-range loop to increment a variable.
for i in range(1, num):
    ...
Now you can change a selector:
“div:nth-child(%s)” % i

**Comment by LeaDer-E** [comment]
> self.get_attribute(selector, “href”) gets the link of an element. self.open_new_window() opens a new window. Now you can open that url in a new window with self.open(url)
> 
> Use a for-range loop to increment a variable. for i in range(1, num): ... Now you can change a selector: “div:nth-child(%s)” % i



> for i in range(1, num):

Sorry can u give me the right code to put in in my idle pls :rose:

**Comment by mdmintz** [comment]
I’m on vacation now with phone only, and I can’t verify code at this time. https://github.com/seleniumbase/SeleniumBase/issues/1224

**Comment by LeaDer-E** [comment]
> I’m on vacation now with phone only, and I can’t verify code at this time. #1224

Thanks for Helping :heart:
