### ISSUE TITLE
Reopening #1229 - Headless not maximizing window in local or Docker headless

### ISSUE THREAD

**Issue by sridharaiyer** [seleniumbase/SeleniumBase#1230]

**Comment by sridharaiyer** [comment]
Hi Dev team,
You may refer to my earlier issue #1229 for details.
In addition, I also tried `self.maximize_window()` inside my script. It is still not maximizing the window in headless local.

**Comment by mdmintz** [comment]
I reopened #1229, so I’m closing this as a duplicate.
