### ISSUE TITLE
How do I use fixture to encapsulate some of the predecessor methods as necessary.

### ISSUE THREAD

**Issue by HellShuro** [seleniumbase/SeleniumBase#1246]
How can I use fixture in pytest, fixture decorators are used on functions, but seleniumbase has to be used by using class inheritance. When writing code, it is necessary to use fixture to encapsulate some of the predecessor steps. So, what should I do.
![image](https://user-images.githubusercontent.com/32864369/157812604-1516d8d2-cd73-4873-807a-4c094db98b67.png)

**Comment by mdmintz** [comment]
If you're just trying to open that URL, you could have a script like this:

```python
from seleniumbase import BaseCase


class MyTestClass(BaseCase):
    def test_basics(self):
        self.open("https://www.baidu.com")
```

If you want that setup to be included before each test, you can subclass BaseCase and add a special setUp() step:

```python
from seleniumbase import BaseCase


class BaseTestCase(BaseCase):
    def setUp(self):
        super(BaseTestCase, self).setUp()
        self.open("https://www.baidu.com")

class MyTestClass(BaseTestCase):
    def test_abc(self):
        pass  # Write your test here
```

You can also use the ``sb`` fixture to avoid using classes:

```python
def test_sb_fixture_with_no_class(sb):
    sb.open("https://google.com/ncr")
    sb.type('input[title="Search"]', "SeleniumBase GitHub\n")
    sb.click('a[href*="github.com/seleniumbase/SeleniumBase"]')
    sb.click('a[title="seleniumbase"]')
```

You'll find a lot of that information here: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md

**Comment by HellShuro** [comment]
The last one is what I want, thank you very much
