### ISSUE TITLE
pytest --rs Runtime issues

### ISSUE THREAD

**Issue by shmily-cwt** [seleniumbase/SeleniumBase#1247]
There are three test methods in a test class

In the first test method, two tab pages will be generated after starting the browser

When the second test method is started, the tab page in the browser started by the first method closes

It is hoped that when the later test methods under a class are started again, the browser started earlier will not be affected

**Comment by mdmintz** [comment]
When running tests in ``--rs`` / ``--reuse-session`` mode, only the first window/tab is carried over to the other tests. This prevents a lot of complexity, and allows additional browser windows to be cleaned up that might not be needed in other tests.
