### ISSUE TITLE
firefox_pref is not correctly set by code

### ISSUE THREAD

**Issue by anvayatechnocrats** [seleniumbase/SeleniumBase#1268]
I have given "--firefox_pref='devtools.jsonview.enabled:False'" and file is not interpreting it correctly.

https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/browser_launcher.py#L622-L624
`f_pref = firefox_pref_item.strip()
 if needs_conversion:
    f_pref_value = firefox_pref_item.strip()
`

Above lines should be replaced with
`f_pref = f_pref.strip()
 if needs_conversion:
    f_pref_value = f_pref_value.strip()
`

Please suggest If I can contribute in development :)

**Comment by mdmintz** [comment]
Fixed by https://github.com/seleniumbase/SeleniumBase/commit/fd1ff0e491d9dd94e29d685addab9833dd9bfbdc in https://github.com/seleniumbase/SeleniumBase/pull/1269 and released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.4.30
Upgrade to SeleniumBase ``2.4.30`` to receive the fix.

**Comment by mdmintz** [comment]
@anvayatechnocrats Thanks for finding the issue. Fixed in version ``2.4.30`` (already released).
