### ISSUE TITLE
HEAD instead of GET for checking status codes

### ISSUE THREAD

**Issue by frafra** [seleniumbase/SeleniumBase#1280]
Using an HTTP HEAD requests instead of an HTTP GET requests for checking if a link is valid or not, could save time and space, since the link could also be a large page or file.

https://github.com/seleniumbase/SeleniumBase/blob/7191a8c8b6006f8691bb698e83c0b80d25260b1a/seleniumbase/fixtures/page_utils.py#L232

**Comment by mdmintz** [comment]
This was completed and released as part of https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.5.0
(Version ``2.5.0``)
