### ISSUE TITLE
Unable to install drivers on Windows10

### ISSUE THREAD

**Issue by cigol1** [seleniumbase/SeleniumBase#1286]
When trying to install chromedrivers in Windows 10 using `python -m sbase install chromedriver` I get a `invalid_run_command`.

After a little digging it looks like the argv[0] check is a little too stringent.  I made the following changes to get the install to work.  

The `argv` looks like the following:
```
['C:\\Users\\name\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sbase\\__main__.py', 'install', 'chromedriver']
```

The following change might make a bit more robust:

**Original code**:

```
    if (
        sys.argv[0].split("/")[-1].lower() == "seleniumbase"
        or (sys.argv[0].split("\\")[-1].lower() == "seleniumbase")
        or (sys.argv[0].split("/")[-1].lower() == "sbase")
        or (sys.argv[0].split("\\")[-1].lower() == "sbase")
    ):
```

**New code**:

```
    if (
        "sbase" in sys.argv[0].lower()
        or ("seleniumbase" in sys.argv[0].lower())
    ):
```

**Comment by mdmintz** [comment]
@cigol1 Thank you for reporting this! I'll have a fix shipped before the end of this weekend.

**Comment by mdmintz** [comment]
Released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v2.5.3
