### ISSUE TITLE
Xpath selector in BaseCase.functions

### ISSUE THREAD

**Issue by dickcarlee** [seleniumbase/SeleniumBase#129]
Hi @mdmintz , it's a perfect package!
I have met a question about BaseCase.functions, in most of functions, you check if the way of 'By'  is 'page_utils.is_xpath_selector()' and that convenient, but this step isn't cover all of the functions, e.g: 'BaseCase.get_text()',
` def get_text(self, selector, by=By.CSS_SELECTOR,
                 timeout=settings.SMALL_TIMEOUT):`
        `if self.timeout_multiplier and timeout == settings.SMALL_TIMEOUT:`
            `timeout = self._get_new_timeout(timeout)`
       `self.wait_for_ready_state_complete()`
        `time.sleep(0.01)`
        `element = page_actions.wait_for_element_visible(  self.driver, selector, by, timeout)` 
that's a little bit annoying.

**Comment by mdmintz** [comment]
Hi @dickcarlee , Thanks for your request. I've just merged https://github.com/seleniumbase/SeleniumBase/pull/130 to take care of that. Let me know if you have any more comments or questions!

**Comment by mdmintz** [comment]
This issue is resolved. Closing the ticket. Let me know if you have any questions!
