### ISSUE TITLE
Issue with Docker Image

### ISSUE THREAD

**Issue by benjamin-kirkbride** [seleniumbase/SeleniumBase#1296]
The docker image is currently built on Ubuntu 18.04 and it seems to be causing some issues.

In addition, the image on dockerhub has not been updated in a very long time.

**Comment by mdmintz** [comment]
Hi @benjamin-kirkbride,
I've gotten some experiments to work on Ubuntu 20.04 when using GitHub Actions: https://github.com/mdmintz/seleniumbase-examples/actions/runs/2164653440

I no longer deal with DockerHub, but I do maintain the Dockerfile in the SeleniumBase repo. What issues were you having? A stacktrace would be helpful if you have it.

**Comment by mdmintz** [comment]
@benjamin-kirkbride I updated the Dockerfile and pushed a new image to DockerHub with a fix:
https://hub.docker.com/layers/seleniumbase/seleniumbase/seleniumbase/latest/images/sha256-d0ac1b627a7c9414f21a0dc8426a81a93ec43e67e4e23f1da6eeae3f41c1500a?context=repo
