### ISSUE TITLE
What is the default --env parameter when sbase gui starts a test?

### ISSUE THREAD

**Issue by tcw010** [seleniumbase/SeleniumBase#1367]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/3793852/174264479-349872e4-53f7-46ad-99a1-b2172785abbf.png">
![Uploading image.png…]()

**Comment by tcw010** [comment]
![image](https://user-images.githubusercontent.com/3793852/174264596-8e169ebe-76b7-4ce1-a2cb-204d44148e46.png)

**Comment by tcw010** [comment]
At present, the default --env parameter is test?

**Comment by mdmintz** [comment]
@tcw010 Yes, that's correct. All default values for pytest are defined in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/pytest_plugin.py
