### ISSUE TITLE
Send a nice email report when all tests are done, can you support this feature?

### ISSUE THREAD

**Issue by tcw010** [seleniumbase/SeleniumBase#1368]
Send a nice email report when all tests are done, can you support this feature?

**Comment by mdmintz** [comment]
@tcw010 This feature is supported via the build tool you are using. For examples, GitHub Actions can send an email notification such as the one seen the screenshot below. If you use Jenkins for building, you can also configure email notifications through that.

<img width="502" alt="Screen Shot 2022-06-17 at 8 17 35 AM" src="https://user-images.githubusercontent.com/6788579/174296624-5586e873-8f46-4827-9734-3497dbf9a146.png">

**Comment by tcw010** [comment]
It wasn't what I wanted. I want to send to more team members。

**Comment by mdmintz** [comment]
Jenkins supports configurable emails to those you'd like to email your reports to. You may want to add ``--junitxml=results.xml`` for a better report to email out.

You can also use ``pytest_session_finish()`` in a ``conftest.py`` file to send out your own emails after all tests complete: https://stackoverflow.com/a/60648714/7058266

For sending out reports/attachments, see https://stackoverflow.com/questions/3362600/how-to-send-email-attachments

SeleniumBase doesn't have its own email sender, as that would require a server, but the above options let you get around that.
