### ISSUE TITLE
--env=production and --with-db_reporting conflict

### ISSUE THREAD

**Issue by tcw010** [seleniumbase/SeleniumBase#1369]
--env=production is specified in cli, and after using the --with-db_reporting to save the test results into mysql, the env field is incorrectly recorded as test.

**Comment by tcw010** [comment]
![image](https://user-images.githubusercontent.com/3793852/174515299-b4a4c8b1-5652-48b3-81f6-a13784087000.png)
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/3793852/174515356-eac4a130-c09b-4d88-8b72-0d99a011619a.png">

**Comment by tcw010** [comment]
The command I use
`pytest -s auto_tests/test_demo_site.py --env=production --settings=custom_settings.py --with-db_reporting
`

**Comment by mdmintz** [comment]
Fixed in https://github.com/seleniumbase/SeleniumBase/pull/1370
Released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v3.2.11
