### ISSUE TITLE
switch_to_frame_of_element() This method takes too long to execute

### ISSUE THREAD

**Issue by chenqinggang001** [seleniumbase/SeleniumBase#1394]
start = time.time()
self.switch_to_frame_of_element("//body[@class='mce-content-body ']/p")
end = time.time()
print(f"switch_to_frame_of_element: {end - start}")

log:

============================= test session starts =============================
platform win32 -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: C:\Users\13040\PyCharm 2022.1.3\jbr\bin
plugins: forked-1.4.0, html-2.0.1, metadata-2.0.1, ordering-0.6, rerunfailures-10.2, xdist-2.5.0, seleniumbase-3.3.2
collected 1 item                                                               

. switch_to_frame_of_element: 21.092121124267578
.

**Comment by chenqinggang001** [comment]
start = time.time()
self.switch_to_frame(//div[@role='application']//div[@class='tox-edit-area']/iframe)
end = time.time()
print(f"switch_to_frame_of_element: {end - start}")

It also takes a long time

**Comment by chenqinggang001** [comment]
I'm not sure if this has anything to do with the page element being tested

**Comment by mdmintz** [comment]
Hi @chenqinggang001 I'm not seeing a slowdown when running this example:

```python
def test_switch_to_frame_of_element_and_double_click(self):
        self.open("https://seleniumbase.io/w3schools/double_click")
        self.switch_to_frame_of_element('[ondblclick="myFunction()"]')
        self.double_click('[ondblclick="myFunction()"]')
        self.assert_text("Hello World", "#demo")
```

But it could be that if you're on a page that has hundreds of iframes, then finding the correct element inside of one could take time, but I'm not sure without more information.

If you already know the frame, the fastest way would be to switch to the known frame first, and then interact with the element you need.

**Comment by chenqinggang001** [comment]
I use the translation software to communicate with you. Please ignore my grammatical mistakes. I'm sorry

**Comment by chenqinggang001** [comment]
This is the speed of the local browser :

switch_to_frame_of_element: 0.23825597763061523

**Comment by mdmintz** [comment]
@chenqinggang001  I think I see the problem. You have ``driver.implicitly_wait(10)`` in your code. SeleniumBase already has automatic waiting. If you use ``driver.implicitly_wait(10)``, then it adds a lot of extra waiting. If you remove that, it might solve your problem.

**Comment by chenqinggang001** [comment]
Thank you very much. Solved my problem @mdmintz
