### ISSUE TITLE
Can this recorder support the recording of desktop electron applications?

### ISSUE THREAD

**Issue by anlanone** [seleniumbase/SeleniumBase#1443]
I want to open electron app using provided seleniumbase and start recording. How should I modify the recorder App interface to enter a local url address, like "C:/Program Files/Postman.exe", click the record button to achieve.

**Comment by mdmintz** [comment]
Hi @anlanone If there's an actual URL, you can use the Selenium Recorder to record actions in an Election App. I was just asked this same question recently in https://github.com/seleniumbase/SeleniumBase/issues/1441
