### ISSUE TITLE
Compatibility of save_cookies and load_cookies on Windows   

### ISSUE THREAD

**Issue by chenqinggang001** [seleniumbase/SeleniumBase#1450]
Using this method on Windows the path is "/", This is probably not done for Windows compatibility

![image](https://user-images.githubusercontent.com/74290987/183929103-bdb1fbfd-576e-4e9c-bce5-bb12aa79d59f.png)

**Comment by mdmintz** [comment]
@chenqinggang001 Nice catch. I'll update path-joining to use ``os.path.join()``.
