### ISSUE TITLE
update documentation for installing drivers through homebrew on Mac

### ISSUE THREAD

**Issue by RomanPszonka** [seleniumbase/SeleniumBase#1456]
URL: https://seleniumbase.io/help_docs/webdriver_installation/#seleniumbase-installation

current instruction:
`brew cask install chromedriver`

this results in an error:
`Error: 'brew cask' is no longer a 'brew' command. Use 'brew <command> --cask' instead.`

correct instruction:
`brew install --cask chromedriver`

**Comment by RomanPszonka** [comment]
also, the next section might need to be updated, but I haven't tried it
`brew cask upgrade chromedriver`

**Comment by mdmintz** [comment]
Done: https://github.com/seleniumbase/SeleniumBase/commit/36801dfdab352967844e630e18e9b9b821f2a02b
