### ISSUE TITLE
is there a way to specify the driver's location in seleniumbase?

### ISSUE THREAD

**Issue by anilreddy** [seleniumbase/SeleniumBase#1462]
In our organization we will maintain drivers location in separate path and there will be no permissions to us to download it and use it via `sbase get chromedriver` or other command. So if there is no way to specify it can you add one like `driver_location=` or something else as we are implementing this framework across our projects.

**Comment by chenqinggang001** [comment]
@anilreddy You can inherit BaseCase and override the `get_new_driver` method
```python
class NewBaseCase(BaseCase):
    def get_new_driver(self, *args, **kwargs):
        
        driver = webdriver.Chrome(...)
        return driver

class TestCase(BaseCase):
	def testcase(self):
		self.open(www.google.com)
```

reference:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_override_driver.py

**Comment by anilreddy** [comment]
@chenqinggang001 Got it thanks

**Comment by tpduarte** [comment]
Hi, all.

I'm new to the library and having a difficulty in understanding how we can pass this parameter in the Driver class. 

When I,  for example, schedule a job in databricks he can't actually detect the path that I have installed in Chrome in the code below:

`driver = Driver(uc=True, headless=True)`

**Comment by mdmintz** [comment]
@tpduarte Browser location is separate from the driver location. You can specify the browser location with `binary_location`:

https://github.com/seleniumbase/SeleniumBase/blob/570910c6f6e079cddd00c23e826e202c6489f39e/seleniumbase/plugins/driver_manager.py#L111
