### ISSUE TITLE
HOOK ERROR when Xvfb not installed in docker image

### ISSUE THREAD

**Issue by jlamaille** [seleniumbase/SeleniumBase#1467]
https://github.com/seleniumbase/SeleniumBase/blob/f1a3e6f3f5b7abb0066a2e78b8b70b611fdef812/seleniumbase/fixtures/base_case.py#L12304

If we use behave command and Docker image of the python type with Chrome but without Xvfb : 
Actual : 
We have the following error in after_scenario.
`[chromedriver] is now ready for use!
   ❌ Scenario Failed!  (Skipping remaining steps:)
HOOK-ERROR in after_scenario: AttributeError: 'BaseCase' object has no attribute 'headless_active'`

Expected : 
No error (set the value of the headless_active variable before the instantiation of the Display class)
And display an information log about the error encountered (in my case, it was the unknown command Xvfb)

**Comment by mdmintz** [comment]
@jlamaille Thanks for reporting this. I'll get a fix shipped out today.

**Comment by mdmintz** [comment]
@jlamaille Released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.0.1
