### ISSUE TITLE
Feature request: add screenshot which return byte like object

### ISSUE THREAD

**Issue by anilreddy** [seleniumbase/SeleniumBase#1485]
Add a screenshot method like `self.save_screenshot_as_byte()` to get screenshot in bytes like object as when am trying to attach screenshot in allure am getting following error when am using `self.save_screenshot()` or `self.save_screenshot_to_logs()` in allure.attach method

I have alternate solution but it would be better to have in-house method instead of using `self.driver.`
```python
allure.attach(self.save_screenshot('screenshot'), 'Screenshot', AttachmentType.PNG)

**a bytes-like object is required, not 'NoneType'**

# There is alternative solution
allure.attach(self.driver.get_screenshot_as_png(), 'Screenshot', AttachmentType.PNG)
```

**Comment by mdmintz** [comment]
@anilreddy If you can already do ``self.driver.get_screenshot_as_png()``, then I would use that. The ``save_`` methods that you're trying to use in ``allure.attach()`` don't return anything... they just save the screenshot directly to the correct folder.
