### ISSUE TITLE
How to automatically activate recorder recording when cross domain？

### ISSUE THREAD

**Issue by anlanone** [seleniumbase/SeleniumBase#1486]
Hi @mdmintz ,
I have two questions I would like your help,

First, the web **URL** entered by the user in the recorder app, I see that the _create_tkinter_gui()_ function in _sb_recorder.py_ captures it. Sorry I'm not familiar with python syntax, I don't know if this **URL** can be obtained in other files? For example _browser_launch.py_?

Second, after activating the recording, when the current page clicks a button to jump to another cross-domain page, it cannot jump to another page for recording, what should I do?

**Comment by mdmintz** [comment]
Hi @anlanone,

The Recorder makes a call to https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/console_scripts/sb_mkrec.py , which adds the url as a pytest command-line option via ``--url=URL``. Inside a test, that URL is found in ``self.start_page``. The completed recording will have that in a ``self.open(URL)`` command.

The Recorder should automatically record on cross-domain sites when jumping via click. Did the red border (indicating a recording is in progress) not appear on the new page for you after the jump?

**Comment by mdmintz** [comment]
Assuming the question has been answered / resolved.
