### ISSUE TITLE
hover_on_element() method doesn't work with id as selector

### ISSUE THREAD

**Issue by josh213564** [seleniumbase/SeleniumBase#1501]
self.assert_element('login','id')
        self.hover_on_element('login','id')

[undefined]Exception: Message: no such element: Unable to locate element: {"method":"css selector","selector":"login"}

**Comment by mdmintz** [comment]
Thanks for reporting this. I'll ship a fix shortly.

**Comment by mdmintz** [comment]
@josh213564 Released in ``4.3.6`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.3.6

**Comment by josh213564** [comment]
@mdmintz Thanks for quick reaction!
