### ISSUE TITLE
Screenshot of error 

### ISSUE THREAD

**Issue by BK-Go-Python** [seleniumbase/SeleniumBase#1516]
chrome version: 105.0.5195.127
selenium.common.exceptions.WebDriverException: Message: GET /session/d8e1cae8-cd75-4fa8-ab58-d9fb35dbfb00/element/3/screenshot
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'WIN-K323MBGQ590', ip: '*', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_341'
Driver info: driver.version: unknown

**Comment by mdmintz** [comment]
This is not a SeleniumBase issue. SeleniumBase is Python, and you have a Java error. Also, you appear to be using a very old version of Selenium from 7 years ago.
