### ISSUE TITLE
When I use the recording tool to record the electron application, I cannot jump to the page after clicking login.

### ISSUE THREAD

**Issue by GuiStarF** [seleniumbase/SeleniumBase#1517]
When I use the recording tool to record the electron application, I cannot jump to the page after clicking login. I suspect that the recording tool prevents the page jumping. Is there any function or method to stop the monitoring of the recording tool? I tried "ESC", the js script is still working, I would like to know the way to turn off the recording tool script completely, Thanks!

**Comment by GuiStarF** [comment]
I found the problem, in _seleniumbase/js_code/recorder_js.py_

```
document.body.addEventListener('mouseover', function (event) {
     reset_if_recorder_undefined();
     if (sessionStorage.getItem('pause_recorder') === 'yes') return;
     const el = event.target;
     const selector = getBestSelector(el);
     if (!selector.startsWith('body') && !selector.includes('div')) {
         document.title = selector;
     }
});
```
**This if statement affects the page jump.**
```
 if (!selector.startsWith('body') && !selector.includes('div')) {
         document.title = selector;
     }
```
 **What is the function of this if statement?**

**Comment by mdmintz** [comment]
When hovering over elements with the mouse, the title shown at the top of the web browser becomes the selector of the element being hovered over (assuming the selector is clean and not too long).
