### ISSUE TITLE
Stuck on get() method

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1572]
My code stuck on get() method and give timeout error 300s, sometimes

```
self.driver.get("https://whatismyip.com/")
```

I want to add Options class to driver object (Driver())
`options.page_load_strategy = 'none'`

**Comment by mdmintz** [comment]
You can easily change the ``page_load_strategy`` with the SeleniumBase Driver Manager:

```python
from seleniumbase import Driver

driver = Driver(page_load_strategy="none")
driver.get("https://whatismyip.com/")
```

Options for ``page_load_strategy`` are "normal", "eager", or "none".
