### ISSUE TITLE
JQUERY_CLICK_ALL with contains('...')

### ISSUE THREAD

**Issue by KolyStudio** [seleniumbase/SeleniumBase#1573]
Hi, I'm trying to do a `self.js_click_all,` with a specific text inside, but nothing happens.

`self.jquery_click_all('span.FiLwP:contains("BOOSTKOJAK")')`

Maybe it's not compatible?

Thanks!

**Comment by mdmintz** [comment]
The format for the last part should be:

``TAG:contains("TEXT")``, eg: ``body div span:contains("Hello")``

In your example, you used ``TAG.class:contains("TEXT")`` - NOT a valid format!

You could try: ``self.jquery_click_all('span:contains("BOOSTKOJAK")')``

The ``:contains()`` selector comes from jQuery (I didn't invent it, but I use their rules for SeleniumBase CSS Selectors to make it work). That selector type does not exist in pure JS, which means that it can't be used in ``js_click_all()``.
