### ISSUE TITLE
Unable to --disable-csp

### ISSUE THREAD

**Issue by KolyStudio** [seleniumbase/SeleniumBase#1588]
Hello, when I try to use self.activate_jquery(), I get the error for blocking csp, even if I switch to test --disable-csp

Exception: Unable to load jQuery on "https://web.snapchat.com/" due to a violation of the website's Content Security Policy directive. To override this policy, add "--disable-csp" on the command-line when running your tests.

I tried pytest xx.py --disable-csp

**Comment by mdmintz** [comment]
The fix will be available in ``seleniumbase`` ``4.7.1``. I'm working on completing that.
Here's how it will look once it's ready:

<img width="500" alt="Screenshot 2022-11-01 at 9 28 07 PM" src="https://user-images.githubusercontent.com/6788579/199373494-418fadb0-ceb4-4c53-95ac-cb3cfab218a7.png">

Here's the script that I ran:

```python
from seleniumbase import BaseCase

class MyTestClass(BaseCase):
    def test_base(self):
        self.open("https://web.snapchat.com/")
        self.activate_jquery()
        self.post_message("SeleniumBase is Here!", duration=30)
```

And this was the command I used:

```bash
pytest new_file.py --uc --disable-csp
```

**Comment by mdmintz** [comment]
Released in ``4.7.1`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.7.1

**Comment by mdmintz** [comment]
@azizainunnajib Set `disable_csp` to `True` when using `SB()`:

https://github.com/seleniumbase/SeleniumBase/blob/77ee5149a34a0bbca17c27a7e745d0754e3ad9e3/seleniumbase/plugins/sb_manager.py#L50

Example:

```python
from seleniumbase import SB

with SB(uc=True, disable_csp=True) as sb:
    # ...
```

**Comment by azizainunnajib** [comment]
thanks @mdmintz, great working well.

many thanks for support..
