### ISSUE TITLE
How to screenshot an element using SeleniumBase

### ISSUE THREAD

**Issue by mybdye** [seleniumbase/SeleniumBase#1598]
when img src is not a real path
```
<img id="captcha" src="xxxxx.php" alt="CAPTCHA Image">
```
thank you.

**Comment by mdmintz** [comment]
Hi @mybdye, there is:

 ```python
self.save_screenshot(name, folder=None, selector=None, by="css selector")
```

If a selector is provided, then it will get a screenshot of a specific element.

When there is a valid src, you can download it directly:

```python
self.download_file(src)  # Goes to the "downloaded_files/" folder.
```

Here's an example of the long way when there is no src:

```python
import os
image = self.find_element("img")  # (Use the selector you need)
filename = "my_image.png"
folder = "downloaded_files"
file_path = os.path.join(folder, filename)
image.screenshot(file_path)
```

Here are some examples you can try:

https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_download_images.py
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_image_saving.py
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_save_screenshots.py

**Comment by mybdye** [comment]
Thanks a lot for the reply, I will try it.

**Comment by mybdye** [comment]
> Here's an example of the long way when there is no src:
> 
> ```python
> import os
> image = self.find_element("img")  # (Use the selector you need)
> filename = "my_image.png"
> folder = "downloaded_files"
> file_path = os.path.join(folder, filename)
> image.screenshot(file_path)
> ```
This worked for me , thanks. :)
