### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1608]
File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\mytools\templates\selenium_.py", line 159, in get
    self.driver.get(url)
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\seleniumbase\undetected\__init__.py", line 412, in get
    return super().get(url)
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HP\PycharmProjects\Selenium-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.585
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
	Ordinal0 [0x0063ACD3+2075859]
	Ordinal0 [0x005CEE61+1633889]
	Ordinal0 [0x004CB7BD+571325]
	Ordinal0 [0x004BE410+517136]
	Ordinal0 [0x004BE231+516657]
	Ordinal0 [0x004BD0A3+512163]
	Ordinal0 [0x004BD6D8+513752]
	Ordinal0 [0x004C6662+550498]
	Ordinal0 [0x004D1BD5+596949]
	Ordinal0 [0x004D4FC0+610240]
	Ordinal0 [0x004BDA81+514689]
	Ordinal0 [0x004D1A0F+596495]
	Ordinal0 [0x0052B93B+964923]
	Ordinal0 [0x00517136+880950]
	Ordinal0 [0x004EFEFD+720637]
	Ordinal0 [0x004F0F3F+724799]
	GetHandleVerifier [0x008EEED2+2769538]
	GetHandleVerifier [0x008E0D95+2711877]
	GetHandleVerifier [0x006CA03A+521194]
	GetHandleVerifier [0x006C8DA0+516432]
	Ordinal0 [0x005D682C+1665068]
	Ordinal0 [0x005DB128+1683752]
	Ordinal0 [0x005DB215+1683989]
	Ordinal0 [0x005E6484+1729668]
	BaseThreadInitThunk [0x760AFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77687BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77687B8E+238]

Getting timeout exception in loading url, no such issue in selenium or undetected_chrome module

Code snippet:
while True:
    driver = Driver(uc=True)
    driver.get(url)
    time.sleep(120)

Stop after about 4 or 5 iterations

**Comment by mdmintz** [comment]
That means the page itself was unable to load at least one of its resources. Sometimes a person's firewall can affect it. It's usually a problem with the page, but you can change the page load strategy to "none" to get around that so that not all resources are loaded.

```
driver = Driver(uc=True, pls="none")
driver.get(url)
```

**Comment by M-Zubair10** [comment]
Thanks it worked!
