### ISSUE TITLE
Chrome crash

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1609]
Driver function crash after sometimes when used in linux while it works in headless windows 10

**Comment by mdmintz** [comment]
That's not a helpful report. A helpful report would include the version of SeleniumBase used, the version of Linux used, the command-line options passed into SeleniumBase (or the SeleniumBase Driver manager), a stack trace (with line numbers), etc.

SeleniumBase is being tested every hour on all environments: https://github.com/mdmintz/seleniumbase-examples/actions
I have not seen your issue on the latest version of SeleniumBase. Maybe you need to upgrade.

**Comment by M-Zubair10** [comment]
Its latest seleniumbase selenium version 4.3.0, linux version 18 ubuntu

Options: user_data_dir, headless2=True,
uc=true, debug=false, pls=none

But, it works perfect on windows

**Comment by mdmintz** [comment]
In ```seleniumbase`` ``4.8.3``, the https://github.com/seleniumbase/SeleniumBase/blob/master/setup.py file has ``selenium==4.6.0`` listed as a dependency. But somehow you have ``4.3.0``, which includes bugs that were fixed in newer versions.
