### ISSUE TITLE
Cannot open the same profile second time

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1656]
When I use --user-data-dir flag to save content, next time chrome crashes and the exception is `chromedriver assumes chrome has been crashed`

**Comment by mdmintz** [comment]
I need more information, as I cannot reproduce this. Did you add anything else to your run command besides ``--user-data-dir=my_user_data_dir``? Are you using the latest version of SeleniumBase? Which Python version? A stack trace would be helpful.
