### ISSUE TITLE
Undetected-Driver

### ISSUE THREAD

**Issue by pedrots00** [seleniumbase/SeleniumBase#1658]
Hi! First of all, I would like to congratulate you on the project. I'm loving working with Selenium Base.
I was facing problems with Headless from Undetected Chrome, and one of the solutions was to use 'import Driver'.

My question is, can I use the same SB() tools together with the Driver? like css selectors, automatically wait for elements, and other amazing features.
I'm new to programming, and the project is helping me a lot.

**Comment by mdmintz** [comment]
Hello! Check out the existing SeleniumBase solution I posted in https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/847 (I’m currently on vacation, so I’m limited in posting ability)

**Comment by pedrots00** [comment]
Hi!! I'm already using it, I just followed this tutorial. My doubt is When using the "import driver", I have the same benefits of using the SB(), for example, the "automatic sleep", the wait_for_element, etc. By the way, enjoy your vacation!

**Comment by mdmintz** [comment]
SB() has all the options as the Driver(), and more. With SB(), you also get access to all the SeleniumBase methods. If using BaseCase inheritance, you can pass the options via the command line for pytest runs, (eg. --uc). For the BaseCase version, see https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py

**Comment by mdmintz** [comment]
Let me know if you have any more questions!
