### ISSUE TITLE
Hiding the chromedriver console window in UC mode on Windows when using pyinstaller

### ISSUE THREAD

**Issue by anovob** [seleniumbase/SeleniumBase#1659]
I'm using chrome driver in SeleniumBase to open chrome

I compiled my script using pyinstaller as one exe file. When I fire up my app, I get a chromedriver.exe console (a black window) followed by a chrome window opened and all my requests are done.

I used bellow code when using undetected_chromedriver 

`driver = uc.Chrome(service_creationflags=subprocess.CREATE_NO_WINDOW)`

My question: Is there a way in SeleniumBase to hide the console window ?

**Comment by mdmintz** [comment]
I can probably implement a simple solution for this based on https://github.com/SeleniumHQ/selenium/pull/8647 by adding a command-line option for it. Are using SeleniumBase via BaseCase inheritance (for “pytest”), or via the SB() context manager? If you’re using the context manager format (which is called directly with “python”) I’ll also need to add a method arg for it.

**Comment by anovob** [comment]
```
from seleniumbase import Driver

driver = Driver(uc=True)

driver.get('Url')
```
I used this

**Comment by mdmintz** [comment]
Sounds good. I’ll add an option. I’ll get to this in a few days when I return from vacation. See https://github.com/seleniumbase/SeleniumBase/issues/1657

**Comment by mdmintz** [comment]
In the next version of SeleniumBase (coming soon), I'll make that the default option when running scripts in ``uc`` Mode on Windows.

**Comment by mdmintz** [comment]
Released in ``4.11.3`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.11.3

**Comment by anovob** [comment]
Thanks for your update. 

Here is one error. When I add chromium_arg browser auto closed.


```
  chromium_arg = {
        '--profile-directory=Default'
        }
  user_data_path = 'path'
  return Driver(user_data_dir=user_data_path, uc=True, chromium_arg=chromium_arg)
```

**Comment by mdmintz** [comment]
@anovob There are over 30 issues with setting a user_data_dir when using undetected chromedriver: https://github.com/ultrafunkamsterdam/undetected-chromedriver/search?p=2&q=user_data_dir&type=issues

Not sure how to fix it. Your best option is to not use both options at the same time.

**Comment by anovob** [comment]
Still open chromedriver console window

**Comment by mdmintz** [comment]
Option was set for Windows UC users.

https://github.com/seleniumbase/SeleniumBase/blob/94e80e460259e6a406c3685eadb4203fe3abc959/seleniumbase/undetected/__init__.py#L270

If that option isn't enough, I wouldn't know. I'm not a ``pyinstaller`` expert.

**Comment by anovob** [comment]
I just see undetected_chromedriver updated and add creationflags. Can you update this?

**Comment by mdmintz** [comment]
It's already being set as shown below (for Windows users), with ``creationflags=subprocess.CREATE_NO_WINDOW``

<img width="720" alt="Screenshot 2023-01-14 at 1 33 17 PM" src="https://user-images.githubusercontent.com/6788579/212490340-aa2eed1d-adf0-4200-8b9d-336aaeef7515.png">

**Comment by anovob** [comment]
Chromedriver console always open.

They Updated in other place. Please check attached file
![flags](https://user-images.githubusercontent.com/5115489/213324553-7267d4b8-5699-4a06-be99-a5270ee53335.png)

**Comment by mdmintz** [comment]
I made an update in ``4.11.6`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.11.6
