### ISSUE TITLE
Wrong screenshots destination when using sb fixture

### ISSUE THREAD

**Issue by casatir** [seleniumbase/SeleniumBase#1660]
Hi there!
Thanks for this amazing project : I discovered it few weeks ago and after converting our test base we get highly reproducible and stable tests! Great!

Just to report what looks like a bug: when you call `sb.save_screenshot_to_logs()` with the `sb` fixture, picture always goes to `latest_logs/seleniumbase.plugins.pytest_plugin.BaseClass.base_method/`.

When using the `--screenshot` option (even with the `sb`fixture) picture correctly goes to `latest_logs/<test-specific-path>/`.

I just investigate a bit and it seems the `__get_test_id()` method in `BaseCase` does not return the correct id in this case...

Thanks

**Comment by mdmintz** [comment]
Hello! Thanks for reporting this. Which version of Python are you using? I can take a look soon. I’m currently on vacation for a few more days and have been responding to all messages via phone. See https://github.com/seleniumbase/SeleniumBase/issues/1657

**Comment by casatir** [comment]
Thanks for answering. I see this on 3.9.2 (locally) and 3.10.9 (CI docker image).

**Comment by mdmintz** [comment]
Released in ``4.11.3`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.11.3
