### ISSUE TITLE
SeleniumBase Driver options are different from standard Chrome options

### ISSUE THREAD

**Issue by mrmi6** [seleniumbase/SeleniumBase#1677]
hi i use uc before like this : 
options.add_argument('--ignore-ssl-errors=yes')
options.add_argument('--ignore-certificate-errors')
options.add_argument('--proxy-server='+proxy)
driver = uc.Chrome(options=options)

but
i cant use options know 
driver = Driver(uc=True,options=options)

error: Driver() got an unexpected keyword argument 'options'

how can i use it like before?

**Comment by mdmintz** [comment]
The options are different from standard undetected-chromedriver use. See: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/driver_manager.py

For ``proxy``, there's ``SERVER:PORT`` and ``USER:PASS@SERVER:PORT`` formats.
Eg. ``driver = Driver(uc=True, proxy="USER:PASS@SERVER:PORT")``

All the important args already get set if using ``uc=True`` mode.

If you want to add other args, there's ``chromium_arg``, which takes a comma-separated list.
Eg. ``driver = Driver(uc=True, chromium_arg="ARG=N,ARG2")``

**Comment by anovob** [comment]
You can use:

crome_options = '--ignore-ssl-errors=yes, --ignore-certificate-errors'
driver = Driver(uc=True, chromium_arg=crome_options)

**Comment by mdmintz** [comment]
For a complete example of seleniumbase ``Driver`` usage, see: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_browser_launcher.py

Eg:

```python
from seleniumbase import Driver
from seleniumbase import js_utils
from seleniumbase import page_actions

driver = Driver(browser="chrome", headless=False)
try:
    driver.get("https://seleniumbase.io/apps/calculator")
    page_actions.wait_for_element(driver, "4", by="id").click()
    page_actions.wait_for_element(driver, "2", by="id").click()
    page_actions.wait_for_text(driver, "42", "output", by="id")
    js_utils.highlight_with_js(driver, "#output", loops=6)
finally:
    driver.quit()
```
