### ISSUE TITLE
Incompatibility with tuspy=1.0.0

### ISSUE THREAD

**Issue by jirikralik** [seleniumbase/SeleniumBase#1683]
Hi Michael, 

currently we have a compatibility issue when using SeleniumBase together with [tuspy](https://github.com/tus/tus-py-client/). The problem is that the it requires the latest [aiohttp](https://github.com/aio-libs/aiohttp). In this package there is "depends on charset-normalizer<3.0 and >=2.0". The latest code already fixed it, but dont know when they are going to release. Do we need to use charset-normalizer==3.0.1 ? Thank you!

**Comment by jirikralik** [comment]
actually, they also created a [ticket](https://github.com/aio-libs/aiohttp/discussions/7171) for aiohttp. Let's see when can they publish...

**Comment by mdmintz** [comment]
Hi,

As you mentioned, they already have an open ticket for that, and here's their PR: https://github.com/aio-libs/aiohttp/pull/7089

It would seem that this is an issue with ``aiohttp``, and not a ``seleniumbase`` one, as ``seleniumbase`` already supports the latest version of ``charset-normalizer`` (currently ``3.0.1``).
