### ISSUE TITLE
How to run SB scripts in UC Mode on Ubuntu 20.04?

### ISSUE THREAD

**Issue by BlondinkaQ** [seleniumbase/SeleniumBase#1685]
`from seleniumbase import Driver
from seleniumbase import page_actions
from selenium.webdriver.common.by import By
chrome_options = f"--incognito,--no-sandbox"
driver = Driver(headless=True, uc=True, chromium_arg=chrome_options)
driver.get("https://nowsecure.nl")

screenshot_name = "now_secure_image.png"
driver.save_screenshot(screenshot_name)
print("\nScreenshot saved to: %s" % screenshot_name)
driver.quit()`

`    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60555
from chrome not reachable
Stacktrace:
#0 0x5616281d6303 <unknown>
#1 0x561627faabbd <unknown>
#2 0x561627f995ab <unknown>
#3 0x561627fd73c3 <unknown>
#4 0x561627fceae9 <unknown>
#5 0x5616280104a6 <unknown>
#6 0x561628007753 <unknown>
#7 0x561627fdaa14 <unknown>
#8 0x561627fdbb7e <unknown>
#9 0x56162822532e <unknown>
#10 0x561628228c0e <unknown>
#11 0x56162820b610 <unknown>
#12 0x561628229c23 <unknown>
#13 0x5616281fd545 <unknown>
#14 0x56162824a6a8 <unknown>
#15 0x56162824a836 <unknown>
#16 0x561628265d13 <unknown>
#17 0x7fa848825609 start_thread
`

**Comment by mdmintz** [comment]
It's working for me: https://github.com/mdmintz/undetected-testing/actions/runs/15980637420/job/45073991857

Tested from https://github.com/mdmintz/undetected-testing

Here's one of the scripts that worked: (https://github.com/mdmintz/undetected-testing/blob/master/verify_undetected.py)

```python
import time
from seleniumbase import page_actions
from seleniumbase import DriverContext

with DriverContext(uc=True, incognito=True) as driver:
    driver.get("https://nowsecure.nl/#relax")
    page_actions.wait_for_text(
        driver, "OH YEAH, you passed!", "h1", by="css selector"
    )
    print("\n Success! Website did not detect Selenium!")
    time.sleep(2)
    screenshot_name = "now_secure_image.png"
    driver.save_screenshot(screenshot_name)
    print("\nScreenshot saved to: %s" % screenshot_name)

```

```bash
> python verify_undetected.py

 Success! Website did not detect Selenium!

Screenshot saved to: now_secure_image.png
```

If you can't see the details from GitHub Actions, fork https://github.com/mdmintz/undetected-testing , and then it will run automatically in your GitHub Actions.

**Comment by BlondinkaQ** [comment]
from seleniumbase import page_actions
from seleniumbase import DriverContext


with DriverContext(headless=True, uc=True, incognito=True) as driver:
    driver.get("https://nowsecure.nl/#relax")
    page_actions.wait_for_text(
        driver, "OH YEAH, you passed!", "h1", by="css selector"
    )
    print("\n Success! Website did not detect Selenium!")
    time.sleep(2)
    screenshot_name = "now_secure_image.png"
    driver.save_screenshot(screenshot_name)
    print("\nScreenshot saved to: %s" % screenshot_name)

this code open real browser, don't work in headless mode. I tested this in rdp linux ubuntu 20, if i use ssh linux server i get same err "raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60555 from chrome not reachable
"

**Comment by mdmintz** [comment]
That's specific to ``undetected-chromedriver`` mode, and there's a workaround here: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/743#issuecomment-1366847803

You'll have to use ``Xvfb``.

Regular SeleniumBase scripts that run on Linux use ``Xvfb`` so that you can avoid using headless mode on Linux.

```python
from seleniumbase import BaseCase

if __name__ == "__main__":
    from pytest import main
    main([__file__, "--uc", "--incognito", "-s"])

class UndetectedTest(BaseCase):
    def test_browser_is_undetected(self):
        if not self.undetectable or not self.incognito:
            self.get_new_driver(undetectable=True, incognito=True)
        self.open("https://nowsecure.nl/#relax")
        try:
            self.assert_text("OH YEAH, you passed!", "h1", timeout=6.75)
            self.post_message("Selenium wasn't detected!", duration=2.8)
            self._print("\n Success! Website did not detect Selenium! ")
            self.save_screenshot_to_logs()
        except Exception:
            self.fail('Selenium was detected! Try using: "pytest --uc"')
```
