### ISSUE TITLE
SeleniumBase Detected On Discord

### ISSUE THREAD

**Issue by IamZiroToxic** [seleniumbase/SeleniumBase#1700]
This module is great but it can't bypass number verification on unclaimed account I tried many possible way to bypass it can someone help me ?

**Comment by mdmintz** [comment]
Are you using SeleniumBase in undetected mode? If not, you need to set ``--uc`` as a command-line option, or from within the test when launching a new driver. Eg:

```python
from seleniumbase import BaseCase

if __name__ == "__main__":
    from pytest import main
    main([__file__, "--uc", "--incognito", "-s"])


class UndetectedTest(BaseCase):
    def test_browser_is_undetected(self):
        if not self.undetectable or not self.incognito:
            self.get_new_driver(undetectable=True, incognito=True)
        self.open("https://nowsecure.nl/#relax")
        try:
            self.assert_text("OH YEAH, you passed!", "h1", timeout=7.75)
            self.post_message("Selenium wasn't detected!", duration=2.8)
            self._print("\n Success! Website did not detect Selenium! ")
            self.save_screenshot_to_logs()
        except Exception:
            self.fail('Selenium was detected! Try using: "pytest --uc"')
```

**Comment by IamZiroToxic** [comment]
Yes i tried that I used undetected selenium before and past nowsecure but discord ask me for phone number even i tried pixelscan and everything is green but still discord detect uc

**Comment by mdmintz** [comment]
If your clicks are being detected, then you'll have to combine SeleniumBase page loads in UC Mode with https://github.com/asweigart/pyautogui so that your clicks are no longer detected. (That's what the experts are using.)

**Comment by IamZiroToxic** [comment]
I even tried that with my click like I clicked the mouse keyboard and everything connected by me but it still detected I think it detects selenium even I open regular chrome and selenium chrome and try to register I can register in regular chrome and I don't have any problem but I changed my IP and register by my self but It asks me again for the number I recognize its for the driver. get it because I open a new tab in opened selenium chrome and tried to register and it's successful but when I use the driver. get when the driver controls the tab it detects me

**Comment by IamZiroToxic** [comment]
If you can't answer me please open issue

**Comment by mdmintz** [comment]
The new https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.12.2 release from yesterday had several updates to UC Mode. Hopefully that resolves your issue. If that still doesn't resolve it, than you'll probably need to either use https://github.com/asweigart/pyautogui for more of your script, or open an issue with https://github.com/ultrafunkamsterdam/undetected-chromedriver, where much of the SeleniumBase UC Mode code comes from.

SeleniumBase UC Mode does make some improvements to undetected-chromedriver on its own, such as:

* driver-management (SeleniumBase automatically detects your browser version and current driver version, so it knows which version of chromedriver to download as needed, and how to patch it. In undetected-chromedriver, you have to use ``version_main`` with an exact version if you don't have the latest browser.)

* headless mode (SeleniumBase's headless UC Mode gets the exact same results as regular headed mode. With undetected-chromedriver, the results can be different, and you could get detected in headless mode even if you weren't detected in regular mode on the same web page.)

* Chrome 109+ support (SeleniumBase's UC Mode has updates to support Chrome 109+. The last update to undetected-chromedriver was in 2022, which is before the latest stable Chrome 109 was released in 2023, and so it's missing the necessary updates for maximum un-detection.)

I'm actively following a thread on undetected-chromedriver's Pull Request page: https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/993#issuecomment-1403508965, which may have updates soon with improvements that will help. I've already implemented the current updates, which helped, but it looks like they will have more updates soon, so I'll be waiting on more info from that.

**Comment by IamZiroToxic** [comment]
No it did't work
