### ISSUE TITLE
Add an option to specify the Chromium browser binary used

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1709]
## Add an option to specify the Chromium browser binary used

(For the browser executable, NOT the driver)

Supports the two main Chromium browsers: Chrome and Edge.

Example:

```bash
pytest test_demo_site.py --binary-location="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

Also as an option for other [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md):

```python
from seleniumbase import Driver
from seleniumbase import js_utils
from seleniumbase import page_actions

driver = Driver(browser="chrome", binary_location="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")
try:
    driver.get("https://seleniumbase.io/apps/calculator")
    page_actions.wait_for_element(driver, "4", by="id").click()
    page_actions.wait_for_element(driver, "2", by="id").click()
    page_actions.wait_for_text(driver, "42", "output", by="id")
    js_utils.highlight_with_js(driver, "#output", loops=6)
finally:
    driver.quit()
```

**Comment by mdmintz** [comment]
Released in ``4.12.3`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.12.3

**Comment by mdmintz** [comment]
Hello @mingatupturndotorg, you mentioned that you're running on `Ubuntu-22.04`, yet you're trying to use a `.exe` file.

`.exe` files aren't supported on Ubuntu. You should use one from the list provided: `['google-chrome', 'google-chrome-stable', 'chrome', 'chromium', 'chromium-browser', 'google-chrome-beta', 'google-chrome-dev', 'google-chrome-unstable', 'brave-browser', 'brave-browser-stable', 'opera', 'opera-stable']` (Those files don't have a file extension.)

For a Linux system, those are the supported binaries to choose from. Using a different one would lead to errors, so that is prevented during binary selection.

**Comment by mingatupturndotorg** [comment]
Thanks @mdmintz, that's a fair response. To clarify my use case or expected behavior - when using undetected-chromedriver, I could run the following script in Ubuntu with WSL:

```
CHROME_PATH = '/mnt/c/Program Files/Google/Chrome Beta/Application/chrome.exe'

options = uc.ChromeOptions()
options.binary_location = CHROME_PATH
driver = uc.Chrome(options=options)
```

and a headful Chrome installed in Windows would appear. Is that behavior possible with sbase?

**Comment by mdmintz** [comment]
@mingatupturndotorg I had not considered WSL (Windows Subsystem for Linux) - (https://ubuntu.com/wsl).
I'll add `chrome.exe` as a valid option for `binary_location` on Linux. That may resolve your issue.
(Will be in the next release.)

**Comment by mingatupturndotorg** [comment]
Thanks! Would a temporary fix be to add `chrome.exe` to `valid_chrome_binaries_on_linux` in `constants.py`?

**Comment by mdmintz** [comment]
@mingatupturndotorg Yes, try that.
