### ISSUE TITLE
Seleniumbase + Multiprocessing not working

### ISSUE THREAD

**Issue by sunny9495-dev** [seleniumbase/SeleniumBase#1717]
Selenium + Multiprocessing not working, I have recorded video showing the issue.

[https://www.dropbox.com/s/da372oadvp6pjo6/NVIDIA_Share_L7g4PMXM38.mp4?dl=0](https://www.dropbox.com/s/da372oadvp6pjo6/NVIDIA_Share_L7g4PMXM38.mp4?dl=0)

When i select two campaigns and run it, it should opened 2 browser, but one browser is open up and another is just crashing or else am i doing wrong, I am using Seleniumbase 4.12.3

Any help would be appreciated

**Comment by mdmintz** [comment]
Multi-threaded SeleniumBase tests must be called via ``pytest -n=4``, (substitute 4 for the number of threads you want if different).

You appear to be using an external app, which might not be doing things correctly.

SeleniumBase also comes with its own GUI app if you want to run tests via GUI. (See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/commander.md)

If you have an issue to report, include the run command that was used to call the tests, and the stack trace that resulted if something didn't work.
