### ISSUE TITLE
Level-up UC Mode algorithms to counter advancements in anti-Selenium technology

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1725]
At approximately 10AM EST on Feb 1st, 2023, anti-Selenium services deployed a new algorithm for bot-detection, which has rendered existing stealth tech inadequate/obsolete for properly masking browser fingerprints.

This screenshot was taken yesterday a few hours after the update was deployed by the anti-Selenium services:

<img width="600" alt="Detected" src="https://user-images.githubusercontent.com/6788579/216339050-da109d5c-40bf-4dbe-b033-0b42f709b73e.png">

I was too preoccupied with standard paid-work duties to address the situation immediately. This morning, I was able to make a few key assessments, which I believe will prove to be invaluable for uncovering a possible solution to level-up the current stealth tech successfully.

(Note: SeleniumBase UC Mode is activated by adding ``--uc`` as a ``pytest`` command-line option.)

**Comment by mdonova33** [comment]
Eager to get an update, l noticed this. I get stuck on CAPTCHA Turnstile a ton

**Comment by mdmintz** [comment]
This was released in ``4.12.4`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.12.4 - (https://github.com/seleniumbase/SeleniumBase/pull/1731)

**Comment by mdmintz** [comment]
Half-way there. Ubuntu failed. macOS succeeded.

<img width="500" alt="Screenshot 2023-02-03 at 2 26 02 AM" src="https://user-images.githubusercontent.com/6788579/216538301-77290b02-958e-45ad-8399-02aae32fac65.png">

**Comment by mdmintz** [comment]
Didn't work. It's going to need another update.

**Comment by mdonova33** [comment]
Still not working while using proxy on windows (I'm sure you're aware, just trying to provide updates). Let me know if there's any way I can help

**Comment by mdmintz** [comment]
There may be some improvements in https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1010 for improving things. Currently, as you've seen, UC Mode is working for some conditions, but not for others. Some of that is OS-dependent, so what works on a Mac might not work on Linux / Windows, and vice versa. I'll be looking into it.

**Comment by mdonova33** [comment]
> 

Looks like using that fork of undected_chromedriver, and using the "chrome_options" arguement of --proxyserver, allows for it to pass the turnstile Cloudflare on windows. Is there a way to add chrome options to SeleniumBase? If not, I can look at merging the two somehow

**Comment by mdmintz** [comment]
The chrome_options ``--proxyserver`` option wouldn't work if the proxy server requires authentication, unless there's something I missed.

**Comment by mdonova33** [comment]
This was after switching to using authentication via IP, not via credentials. It’s what I usually do with SeleniumBase as wellSent from my iPhoneOn Feb 3, 2023, at 5:48 PM, Michael Mintz ***@***.***> wrote:﻿
The chrome_options --proxyserver option wouldn't work if the proxy server requires authentication, unless there's something I missed.

**Comment by mdmintz** [comment]
The work continued in ``4.12.5`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.12.5

**Comment by mdmintz** [comment]
Victory with ``4.12.5`` - https://github.com/mdmintz/undetected-testing/actions/runs/4090027422/jobs/7053156773

<img width="800" alt="Screenshot 2023-02-03 at 11 53 30 PM" src="https://user-images.githubusercontent.com/6788579/216749389-a30b6846-e6fc-4ff6-b4ed-98566eac2214.png">

**Comment by mdonova33** [comment]
> Victory with `4.12.5` - https://github.com/mdmintz/undetected-testing/actions/runs/4090027422/jobs/7053156773
> 
> <img alt="Screenshot 2023-02-03 at 11 53 30 PM" width="800" src="https://user-images.githubusercontent.com/6788579/216749389-a30b6846-e6fc-4ff6-b4ed-98566eac2214.png">

Unfortunately, still not working with a proxy on Windows

**Comment by mdmintz** [comment]
@mdonova33 For the ``Driver`` Manager format, (see https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_23), this is the syntax to use for setting a proxy in UC Mode:

```python
from seleniumbase import Driver
driver = Driver(uc=True, proxy="USER:PASS@IP:PORT")
```

That's working for me on all operating systems.

For UC Mode without a proxy:

```python
from seleniumbase import Driver
driver = Driver(uc=True)
```

**Comment by mdonova33** [comment]
> @mdonova33 For the ``Driver`` Manager format, (see https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_23), this is the syntax to use for setting a proxy in UC Mode:
> 
> 
> 
> ```python
> 
> from seleniumbase import Driver
> 
> driver = Driver(uc=True, proxy="USER:PASS@IP:PORT")
> 
> ```
> 
> 
> 
> That's working for me on all operating systems.
> 
> 
> 
> For UC Mode without a proxy:
> 
> 
> 
> ```python
> 
> from seleniumbase import Driver
> 
> driver = Driver(uc=True)
> 
> ```

That's exactly how I have it. 
"driver = Driver(uc=True, proxy="USER:PASS@IP:PORT")"

Currently, webmail100.com initiates a turnstile Cloudflare page on Windows 11, one that is not able to be passed. 

However, using the undetected_chrome package, it is able to be passed. But that module is far slower than SeleniumBase, so I'd like to see if we can figure out how to get it working.

**Comment by ultrafunkamsterdam** [comment]
@mdmintz  I just updated UC. Good to go again

**Comment by mdmintz** [comment]
@ultrafunkamsterdam Thank you! I'll go through your changes and put those to use.

**Comment by mdonova33** [comment]
> @ultrafunkamsterdam Thank you! I'll go through your changes and put those to use.

FYI thank you both for the work you do. Open source can be a thankless job sometimes
