### ISSUE TITLE
undetected by https://www.hermes.cn/

### ISSUE THREAD

**Issue by WZQ1993** [seleniumbase/SeleniumBase#1734]
Hi, mdmintz
I need to help
I tried it on hermes, it work  successful the first time, but soon I was blocked when I opened the other page for the second time
This  is my code

env
Python 3.9.6
selenium                 4.8.0
seleniumbase             4.12.5

````
def get_cookie(proxyStr):
    with SB(undetectable=True, proxy=proxyStr, incognito=True) as sb:
        sb.open("https://www.hermes.cn/cn/zh/")
        sb.sleep(3)
        sb.driver.save_screenshot('index.png')
        print("\nScreenshot saved to: %s" % 'index.png')

        sb.open("https://www.hermes.cn/cn/zh/category/%E5%A5%B3%E5%A3%AB/%E6%88%90%E8%A1%A3%E7%B3%BB%E5%88%97/%E6%98%A5%E5%A4%8F%E7%B3%BB%E5%88%97/#|")
        sb.sleep(3)
        sb.driver.save_screenshot('category.png')
        print("\nScreenshot saved to: %s" % 'category.png')
        sb.driver.quit()
````

I got two screenshots like this, it doesn't work when i trying another ip 

index.png
![index](https://user-images.githubusercontent.com/11957047/216802115-b3e1703f-d2dd-4f4e-8203-471497924e1d.png)
category.png
![category](https://user-images.githubusercontent.com/11957047/216802108-01f9dba3-cb41-4c0a-a655-3dfd93900790.png)

Thanks a lot.

**Comment by mdmintz** [comment]
Try the following on SeleniumBase ``4.12.6`` with a unique ip address that hasn't visited that page before with Selenium:

```python
from seleniumbase import SB

with SB(undetectable=True) as sb:
    sb.open("https://www.hermes.cn/cn/zh/")
    sb.sleep(6)
    hermes_img_1 = "hermes_img_1.png"
    sb.driver.save_screenshot(hermes_img_1)
    print("\nScreenshot saved to: %s" % hermes_img_1)

with SB(undetectable=True, uc_cdp_events=True) as sb:
    sb.open("https://www.hermes.cn/cn/zh/category/女士/#|")
    sb.sleep(6)
    hermes_img_2 = "hermes_img_2.png"
    sb.driver.save_screenshot(hermes_img_2)
    print("\nScreenshot saved to: %s" % hermes_img_2)
```

That website uses more than standard detection. If you hit pages too quickly, you'll still be asked to verify, even if using a regular browser window without Selenium. The current UC Mode is as good as can be with undetected-chromedriver protections. If you still get detected, you may need to slow down actions, or file a separate ticket with undetected-chromedriver directly.
