### ISSUE TITLE
What is the difference between SeleniumBase architecture design and implementation principles compared with selenium?

### ISSUE THREAD

**Issue by anlanone** [seleniumbase/SeleniumBase#1737]
@mdmintz，
Hi, I want to know if seleniumbase has an overall architecture and scheme design diagram to look at? Does Seleniumbase support multiple scripting languages such as Java, python, C#, etc. like selenium? Whether to support different operating platforms such as Mac, Linux, WINDOWS?Looking forward to your answer.

**Comment by mdmintz** [comment]
Hello! Great question.

SeleniumBase is a Python framework for end-to-end testing and web automation for all major platforms (Windows / macOS / Linux) and supports all major browsers (Chrome, Edge, Firefox, Safari).

SeleniumBase supports multiple Design Patterns for structuring tests. See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md
Most of these formats are designed to be run with ``pytest``, however some of them can be run with pure ``python``.

SeleniumBase includes multiple command-line options for ``pytest``. See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/customizing_test_runs.md

SeleniumBase includes lots of examples to help people get started. See https://github.com/seleniumbase/SeleniumBase/tree/master/examples

### Here's the ReadMe description of how SeleniumBase is different from raw Selenium:

<p>💡 SeleniumBase is a Python framework for browser automation and testing. SeleniumBase uses <a href="https://www.w3.org/TR/webdriver2/#endpoints" target="_blank">Selenium/WebDriver</a> APIs, and incorporates test-runners such as <code>pytest</code>, <code>nosetests</code>, and <code>behave</code> to provide organized structure, test discovery, test execution, test state (<i>eg. passed, failed, or skipped</i>), and command-line options for changing default settings (<i>such as choosing the browser to use</i>). With raw Selenium, you would need to set up your own options-parser for configuring tests from the command-line.</p>

<p>💡 With raw Selenium, commands that use selectors need to specify the type of selector (eg. <code>"css selector", "button#myButton"</code>). With SeleniumBase, there's auto-detection between CSS Selectors and XPath, which means you don't need to specify the type of selector in your commands (<i>but optionally you could</i>).</p>

<p>💡 SeleniumBase methods often perform multiple actions in a single method call. For example, <code>self.type(selector,text)</code> does the following:<br />1. Waits for the element to be visible.<br />2. Waits for the element to be interactive.<br />3. Clears the text field.<br />4. Types in the new text.<br />5. Presses Enter/Submit if the text ends in "\n".<br />With raw Selenium, those actions require multiple method calls.</p>

<p>💡 SeleniumBase uses default timeout values when not set:<br />
✅<code>self.click("button")</code><br />
With raw Selenium, methods would fail instantly (<i>by default</i>) if an element needed more time to load:<br />
❌<code>self.driver.find_element(by="css selector", value="button").click()</code><br />
(Reliable code is better than unreliable code.)</p>

<p>💡 SeleniumBase lets you change the explicit timeout values of methods:<br />
✅<code>self.click("button",timeout=10)</code><br />
With raw Selenium, that requires more code:<br />
❌<code>WebDriverWait(driver,10).until(EC.element_to_be_clickable("css selector", "button")).click()</code><br />
(Simple code is better than complex code.)</p>

<p>💡 SeleniumBase gives you clean error output when a test fails. With raw Selenium, error messages can get very messy.</p>

<p>💡 SeleniumBase gives you the option to generate a dashboard and reports for tests. It also saves screenshots from failing tests to the <code>./latest_logs/</code> folder. Raw <a href="https://www.selenium.dev/documentation/webdriver/" target="_blank">Selenium</a> does not have these options out-of-the-box.</p>

<p>💡 SeleniumBase includes desktop GUI apps for running tests, such as <b>SeleniumBase Commander</b> for <code>pytest</code>, and <b>SeleniumBase Behave GUI.</b></p>

<p>💡 SeleniumBase has its own Recorder & Test Generator that can create tests from manual browser actions. SeleniumBase also has many other useful tools and console scripts for getting things done quickly. (<i>See the documentation for more details!</i>)</p>
