### ISSUE TITLE
Need to manually combine the recorded individual test case into a test suite before running the test suite?

### ISSUE THREAD

**Issue by anlanone** [seleniumbase/SeleniumBase#1744]
Hi,@mdmintz,
  Recently, I am learning your SleniumBase automated testing framework. There are three questions I would like to ask.

 First, I see that you have provided two pytest commands to generate automated test reports, which are **_pytest test_suite.py --html=report.html_**  and _**pytest test_suite.py --dashboard**_.I see that the recording script is saved in one test case method at a time, and the test suite contains multiple use case methods. Does _this test_suite.py_ require the user to integrate multiple recording scripts into one suite? Or is there any other way to run multiple test cases sequentially to generate test reports?

Second, are the implementation principles of the report-html and dashboard test reports both built-in functions of pytest?

Third, when playing back the script, what is the speed delay of _**--slow**_ slow playback and _**--demo**_ demo mode playback? Where in the code can I see this?

Looking forward to your answer.

**Comment by mdmintz** [comment]
Hello @anlanone,
1. If you run ``pytest`` without specifying a file, it'll run all tests that it finds based on pytest discovery rules. All test files that start with ``test_`` or end with ``_test.py`` will get picked up. Test methods that start with ``test_`` will get picked up. The class name doesn't matter as long as tests inherit ``BaseCase``. Then you can add additional args for advanced features such as reports and dashboards (``--html=report.html`` / ``--dashboard``). You can also group tests together using [pytest markers](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_markers.py). The [SeleniumBase Recorder](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/recorder_mode.md) can help you generate tests.

2. ``pytest-html`` is a separate dependency that includes html reports. (It is included with SeleniumBase dependencies.) The Dashboard comes built-in with SeleniumBase.

3. ``--slow`` adds 0.5s between actions. With ``--demo``, there is an animation that highlights actions, which lasts close to 1s. Many timeout values [can be found here](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/config/settings.py).
