### ISSUE TITLE
Can we add custom variables in env?

### ISSUE THREAD

**Issue by anilreddy** [seleniumbase/SeleniumBase#1745]
Currently we are using env to determine env url like test has different we have custom envs like t2 and dev but am getting an error that those 2 are not in env list.

Can you make possible to add custom env for —env=custom_env

**Comment by mdmintz** [comment]
There's a hardcoded list for preventing spelling issues and commonly mixed-up terms for the ``--env=ENV`` option (accessed with ``self.env``):

(choose from 'qa', 'rc', 'staging', 'develop', 'production', 'offline', 'online', 'master', 'remote', 'local', 'alpha', 'beta', 'main', 'test', 'uat')

People would often mix up "production" / "prod", or "develop" / "dev", so there is a "production" option (but not "prod"), and there is a "develop" option (but not "dev"). That way, things go smoothly inside tests where you have an ``if`` statement for ``self.env`` to do things differently based on the environment set.

People can also use a custom option for passing in an env:

```python
--account=STR  # (Set account. Access with "self.account" in tests.)
--data=STRING  # (Extra test data. Access with "self.data" in tests.)
--var1=STRING  # (Extra test data. Access with "self.var1" in tests.)
--var2=STRING  # (Extra test data. Access with "self.var2" in tests.)
--var3=STRING  # (Extra test data. Access with "self.var3" in tests.)
--variables=DICT  # (Extra test data. Access with "self.variables".)
```
