### ISSUE TITLE
UserAgent is not hovering over the browser with UC mod

### ISSUE THREAD

**Issue by Shpakoff** [seleniumbase/SeleniumBase#1771]
Hello again, I hope I'm not distracting you too much. How do I solve the problem that in the UC mod I have no UserAgent hovering over the browser. Also my is_mobile doesn't work, but it's not that important. As soon as I turn off the UC mod, everything works. 
My code:
self.browser = Driver(undetectable=True,agent=userAgent,incognito=True,block_images=True,is_mobile=True,d_p_r=True)

**Comment by mdmintz** [comment]
**One**: ``d_p_r`` is short for Device Pixel Ratio, which is generally a small integer less than 10. You set it to a boolean (True).

**Two**: Mobile Mode cannot be used in conjunction with UC Mode. (The two modes can be used separately, but not together at the same time.)

**Three**: What do you mean by the User Agent hovering over the browser? The User Agent is a string based on the browser settings, which can be changed.

**Comment by Shpakoff** [comment]
> **One**: `d_p_r` is short for Device Pixel Ratio, which is generally a small integer less than 10. You set it to a boolean (True).
> 
> **Two**: Mobile Mode cannot be used in conjunction with UC Mode. (The two modes can be used separately, but not together at the same time.)
> 
> **Three**: What do you mean by the User Agent hovering over the browser? The User Agent is a string based on the browser settings, which can be changed.

Yes thanks, apparently it was because is_mobile = True. didn't notice that d_p_r is a small integer)
