### ISSUE TITLE
Xhr requests 

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#1776]
Hi,
Is there a way to do xhr requests in API within the browser on this awesome package?  if they are done through the requests package they fail through cloudfare, but if they are done inside the browser it may work correctly in the same way when you press reply xhr inside the networks section in chrome.
Thanks

**Comment by mdmintz** [comment]
For that, you'll need a custom built initialization with selenium-wire. Here's a boilerplate to start with:

```python
from seleniumbase import BaseCase
from seleniumwire import webdriver  # Requires "pip install selenium-wire"

class WireTestCase(BaseCase):
    def get_new_driver(self, *args, **kwargs):
        options = webdriver.ChromeOptions()
        options.add_experimental_option(
            "excludeSwitches", ["enable-automation"]
        )
        options.add_experimental_option("useAutomationExtension", False)
        return webdriver.Chrome(options=options)

    def test_simple(self):
        self.open("https://seleniumbase.io/demo_page")
        for request in self.driver.requests:
            print(request.url)
```

Then, you'll need to combine that with ``selenium-wire``'s own ``undetected-chromedriver`` initialization discussed here:

https://github.com/wkeeling/selenium-wire#bot-detection

```python
import seleniumwire.undetected_chromedriver as uc

chrome_options = uc.ChromeOptions()

driver = uc.Chrome(
    options=chrome_options,
    seleniumwire_options={}
)
```

Which gets you something like this after you've combined everything:

```python
from seleniumbase import BaseCase
from seleniumwire import undetected_chromedriver as uc

class WireTestCase(BaseCase):
    def get_new_driver(self, *args, **kwargs):
        options = uc.ChromeOptions()
        return uc.Chrome(options=options, seleniumwire_options={})

    def test_simple(self):
        self.open("https://seleniumbase.io/demo_page")
        for request in self.driver.requests:
            print(request.url)
```

That uses an unmodified ``undetected-chromedriver``, with all of the deprecation warnings still present. Might be enough for what you need, but at least there you have a complete ``selenium-wire`` integration with an ``undetected-chromedriver`` backend and access to ``seleniumbase`` APIs. Modify as needed.

**Comment by FranciscoPalomares** [comment]
Hi, Thanks
How to send with headers? 
Thanks again

**Comment by mdmintz** [comment]
Use ``self.driver`` to access the raw driver directly, then follow the instructions from https://github.com/wkeeling/selenium-wire#example-add-a-request-header
