### ISSUE TITLE
How can I use pyinstaller to build a test.py to an executable file?

### ISSUE THREAD

**Issue by jeffreyouni** [seleniumbase/SeleniumBase#1788]
I have written some scripts and I want to build them as an executable file using pyinstaller, and then send these executable files to other people who haven't installed python or any SeleniumBase environment. This means I want to build a test.py script to an executable file including all relatives.

How can I do that?

Thank you so much for your help

**Comment by mdmintz** [comment]
There's an existing thread about turning SeleniumBase desktop apps such as the Recorder/Playback tool (https://github.com/seleniumbase/SeleniumBase/tree/master/examples/desktop_apps) into pure executables, which can be found here: https://github.com/seleniumbase/SeleniumBase/issues/1075#issuecomment-973021116

https://user-images.githubusercontent.com/6788579/142454125-1b4a82e7-13be-4842-99bd-aedc79f3ddc6.mov

--------

But for using ``pyinstaller``, you should read their documentation here: https://github.com/pyinstaller/pyinstaller
