### ISSUE TITLE
proxy detection on selenium base 

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#1795]
```
from seleniumbase import SB
import time
from time import sleep
import random
import string



def random_char1(y):
    return ''.join(random.choice(string.ascii_lowercase) for x in range(y))
m = (random_char1(7) + '-' + random_char1(7))

with SB(uc=True, user_data_dir=f"F:\\{m}",proxy = "eqmhgmmg:oh75ju0coss2@45.72.53.102:6138") as sb:
    cdc_props = sb.driver.execute_script('const j=[];for(const p in window){'
                                         'if(/^[a-z]{3}_[a-zA-Z0-9]{22}_.*/i.test(p)){'
                                         'j.push(p);delete window[p];}}return j;')
    if len(cdc_props) > 0:
        cdc_props_js_array = '[' + ','.join('"' + p + '"' for p in cdc_props) + ']'
        sb.driver.execute_cdp_cmd('Page.addScriptToEvaluateOnNewDocument',
                                  {'source': cdc_props_js_array + '.forEach(k=>delete window[k]);'})
        
    sleep(5000)
```

hello please in the code above i connected seleniumbase with proxy but proxy was detected as extension on chrome browser i want to know how to do the following :

1- how can i prevent chrome from detection that i use proxy through extensions 
2-in `[(chrome://version/)` how can disappear that i am using proxy 

i want to make proxy undetectable as many anti detection software for example : multi login , go login , incogniton , morelogin, 

if possible can you tell me these softwares built by which programming language , 

are there an online source how can i built like these softwares please ?

i have upload 3 pictuers to clarify the problems 

[[](url)](https://ibb.co/NYqFbnL)

[[](url)](https://ibb.co/FbyCsn1)

[[](url)](https://ibb.co/C2McNzc)

**Comment by mdmintz** [comment]
There are a few different things it could be.

1. You're using an old version of Windows (Windows 8.1), which may be a problem, given your screenshot:

<img width="712" alt="Screenshot 2023-03-09 at 9 28 21 AM" src="https://user-images.githubusercontent.com/6788579/224056176-11d5e4d3-ce75-4dfd-915c-7e15cb16228f.png">

2. It could be an issue with your proxy, which sites might be able to detect.

3. You've modified settings with your ``execute_cdp_cmd()`` method, which may have broken undetection.

--------

Default settings have already been shown to work. See: https://github.com/mdmintz/undetected-testing

You can also try running the example test: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py

Those work for me and on CI. If that doesn't work for you with default settings, then it could be your Windows version, or the website you're testing on.

**Comment by ahmedabdelhamedz** [comment]
> There are a few different things it could be.
> 
> 1. You're using an old version of Windows (Windows 8.1), which may be a problem, given your screenshot:
> 
> <img alt="Screenshot 2023-03-09 at 9 28 21 AM" width="712" src="https://user-images.githubusercontent.com/6788579/224056176-11d5e4d3-ce75-4dfd-915c-7e15cb16228f.png">
> 
> 2. It could be an issue with your proxy, which sites might be able to detect.
> 3. You've modified settings with your `execute_cdp_cmd()` method, which may have broken undetection.
> 
> Default settings have already been shown to work. See: https://github.com/mdmintz/undetected-testing
> 
> You can also try running the example test: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
> 
> Those work for me and on CI. If that doesn't work for you with default settings, then it could be your Windows version, or the website you're testing on.

i dont tell that it detected as bot no i donnt mean that 

i mean that extension appear on chrome browser but when i use application like incogniton software chrome browser dont detect any extension for proxy

 do you understood what i mean?

**Comment by mdmintz** [comment]
The content that appears on chrome://version/ is based on the settings that are set when Chrome launches. I don't think it can be changed afterward by selenium, unless you open a new Chrome browser with new settings. I'm not sure what effect other applications would have on changing that page.
