### ISSUE TITLE
uc_driver don't support chromedriver V111

### ISSUE THREAD

**Issue by BishoLv** [seleniumbase/SeleniumBase#1797]

**Comment by mdmintz** [comment]
It's working for me on the latest version of seleniumbase (currently ``4.13.10``):

--------

```bash
> sbase install uc_driver

*** chromedriver version for download = 111.0.5563.64 (Latest)

Downloading chromedriver_mac64.zip from:
https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_mac64.zip ...
Download Complete!

Extracting ['chromedriver', 'LICENSE.chromedriver'] from chromedriver_mac64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/uc_driver

Making [uc_driver 111.0.5563.64] executable ...
[uc_driver 111.0.5563.64] is now ready for use!
The file [uc_driver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/uc_driver

Making [uc_driver 111.0.5563.64] executable ...
[uc_driver 111.0.5563.64] is now ready for use!

> pytest verify_undetected.py --uc
========================================= test session starts =========================================
platform darwin -- Python 3.11.2, pytest-7.2.2, pluggy-1.0.0
rootdir: /Users/michael/github/SeleniumBase/examples, configfile: pytest.ini
plugins: html-2.0.1, xdist-3.2.0, rerunfailures-11.1.2, ordering-0.6, cov-4.0.0, metadata-2.0.4, forked-1.6.0, seleniumbase-4.13.10
collected 1 item                                                                                      

verify_undetected.py 
 Success! Website did not detect Selenium! 
.

========================================== 1 passed in 8.65s ==========================================
```

--------

Please upgrade to the latest version of SeleniumBase, and please include more details in your bug reports, such as version, OS, and run commands / command-line options.

Note that ``uc_driver`` is only patched AFTER the first test that uses it runs. (When it is first downloaded, it is identical to chromedriver.)

**Comment by faustus-eth** [comment]
I had the same issue when using seleniumbase like so:  

`from seleniumbase import Driver`
`driver = Driver(undetected=True)`

Attempting to solve by updating with `pip3 install --no-cache-dir --force-reinstall -U seleniumbase` collects/installs the latest version 
> Collecting seleniumbase
> Downloading seleniumbase-4.13.14-py3-none-any.whl (519 kB)

and then using `sbase` displays an older version:
> C:\Users\[UserName]\AppData\Local\Programs\Python\Python310\Lib\site-packages\
> seleniumbase 4.13.0

using `pytest` also displays an older version:
>seleniumbase-4.13.0

I later SOLVED the problem when i figured out `uc_driver.exe` was not automatically updated in `C:\Users\[UserName]\AppData\Local\Programs\Python\Python310\Lib\site-packages\seleniumbase\drivers`. Manualy removing `uc_driver.exe` then caused a chromedriver download which solved the problem.
