### ISSUE TITLE
How to add a new fixture

### ISSUE THREAD

**Issue by chenhaijun02** [seleniumbase/SeleniumBase#1803]
I want to add a new fixture, which file should I put it in? For example, conftest.py in pytest

**Comment by mdmintz** [comment]
You can put fixtures in a ``conftest.py`` file. See https://docs.pytest.org/en/latest/reference/fixtures.html for reference.

Also read up on existing discussions:
* https://github.com/seleniumbase/SeleniumBase/discussions/1631
* https://github.com/seleniumbase/SeleniumBase/discussions/1383#discussioncomment-3056420

Note that if you want to use custom fixtures in your tests, you'll need to use one of SeleniumBase syntax formats that uses the ``sb`` fixture. (``BaseCase`` inheritance is **not** supported.)

See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md for a list of all syntax formats. (Look for ones that use the **``sb``** fixture.)

**Comment by chenhaijun02** [comment]
Thank you!
