### ISSUE TITLE
Proxy with wire option

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#1807]
Hi, comment in https://github.com/seleniumbase/SeleniumBase/issues/1574

Hi, how to set proxy ? if code is:

```
from seleniumbase import Driver

driver = Driver(wire=True)
driver.get("https://seleniumbase.io/demo_page")

```
set_wire_proxy function not exists. If set with proxy argument, not catch requests
Thanks

**Comment by mdmintz** [comment]
Use one of the [SeleniumBase Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that has ``base_case.py`` methods.

Then make sure you run tests in wire mode (eg. ``--wire``).

Then you can change your proxy with one of the following methods:

```python
self.set_wire_proxy("SERVER:PORT")
self.set_wire_proxy("socks5://SERVER:PORT")
self.set_wire_proxy("USERNAME:PASSWORD@SERVER:PORT")
```

Or if using the ``Driver`` Manager in ``wire`` mode (as you have), then just use this method for changing the proxy:

```python
    def set_wire_proxy(self, string):
        """Set a proxy server for selenium-wire mode ("--wire")
        NOTE: This method ONLY works while using "--wire" mode!
        Examples:
            self.set_wire_proxy("SERVER:PORT")
            self.set_wire_proxy("socks5://SERVER:PORT")
            self.set_wire_proxy("USERNAME:PASSWORD@SERVER:PORT") """
        if not string:
            self.driver.proxy = {}
            return
        the_http = "http"
        the_https = "https"
        if string.startswith("socks4://"):
            the_http = "socks4"
            the_https = "socks4"
        elif string.startswith("socks5://"):
            the_http = "socks5"
            the_https = "socks5"
        string = string.split("//")[-1]
        self.driver.proxy = {
            "http": "%s://%s" % (the_http, string),
            "https": "%s://%s" % (the_https, string),
            "no_proxy": "localhost,127.0.0.1",
        }
```

**Comment by gouravkumar99** [comment]
Thanks @mdmintz for the support, but I am not using wire. I am using the Driver() option as follows:
`driver = Driver(uc=True,user_data_dir=user_data_dir, multi_proxy=True, proxy=proxy_d)`

i want to change new proxy in running browser.

**Comment by mdmintz** [comment]
@gouravkumar99 The only way to change the proxy of an active browser in the middle of a test is with Wire Mode enabled and using the `set_wire_proxy()` method:

```python
self.set_wire_proxy("SERVER:PORT")
self.set_wire_proxy("socks5://SERVER:PORT")
self.set_wire_proxy("USERNAME:PASSWORD@SERVER:PORT")
```

(Note that Wire Mode cannot be used together with UC Mode.)
