### ISSUE TITLE
Linux headed behavior broken since v4.13.6

### ISSUE THREAD

**Issue by AchilleAsh** [seleniumbase/SeleniumBase#1808]
Hi,

Since version 4.13.6 and still currently on master, --headed feature on Linux is broken: the browser is never shown but the tests run fine:

```bash
➜ git checkout master
➜ pytest examples/test_demo_site.py --headed
# [...] 
# = 1 passed in 14.71s = 
# Passes but the browser is not visible
➜ git checkout v4.13.5                      
➜ pytest examples/test_demo_site.py --headed
# [...]
# = 1 passed in 13.50s =
# Passes and browser is visible, expected behavior of --headed
```

This is happening using both Chrome (111.0.5563.64) and Firefox (110.0.1), on Opensuse Tumbleweed with KDE Plasma (5.17.2).

Based on the code this is due to https://github.com/seleniumbase/SeleniumBase/pull/1780 in [seleniumbase/plugins/selenium_plugin.py:1178](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/selenium_plugin.py#L1178) : the xvfb display is initialized and used regardless of headless/headed mode.

The fix doesn't seem complex, do you want me to open a PR? 

Thanks for this great framework!

**Comment by mdmintz** [comment]
Thanks for reporting this. I'll ship a fix / new release in the next few hours.

**Comment by mdmintz** [comment]
This was released in ``4.13.15`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.13.15

**Comment by cengizili** [comment]
I think this issue is still ongoing, Chrome appears in taskbar but has no screen on headed mode.

**Comment by mdmintz** [comment]
@cengizili Are you sure you're on the latest version? Check with ``seleniumbase --version``
If still an issue, use a debugger to find out where Xvfb is getting enabled, and show some code or a screenshot of the location. Note that ``--headless`` mode is the default on Linux, unless using ``--headed``.

**Comment by cengizili** [comment]
> @cengizili Are you sure you're on the latest version? Check with `seleniumbase --version` If still an issue, use a debugger to find out where Xvfb is getting enabled, and show some code or a screenshot of the location. Note that `--headless` mode is the default on Linux, unless using `--headed`.

Yeah I am using the latest version. I just figured out it is happening since I am trying to run pytest as root user like "sudo pytest random_test.py --headed", instead  "pytest random_test.py --headed" works fine. I have to use the former because I am also running it with the option --user-data-dir=data, and not to have sudo in the beginning leads to permission denied error.

**Comment by cengizili** [comment]
> > @cengizili Are you sure you're on the latest version? Check with `seleniumbase --version` If still an issue, use a debugger to find out where Xvfb is getting enabled, and show some code or a screenshot of the location. Note that `--headless` mode is the default on Linux, unless using `--headed`.
> 
> Yeah I am using the latest version. I just figured out it is happening since I am trying to run pytest as root user like "sudo pytest random_test.py --headed", instead "pytest random_test.py --headed" works fine. I have to use the former because I am also running it with the option --user-data-dir=data, and not to have sudo in the beginning leads to permission denied error.

Any advice on how can I run pytest command as sudo without enabling xvfb?

**Comment by AchilleAsh** [comment]
The latest version works fine on my side.

I think your system isn't properly set up: using sudo clears your path, so depending on your environment you might still have the old version installed and available in the path used for root.

On my machine, root thus cannot find seleniumbase: 
```shell 
➜ which seleniumbase                                                                                                                       
/home/achille/.cache/pypoetry/virtualenvs/xxx/bin/seleniumbase
➜ sudo which seleniumbase                                                                                                                       
which: no seleniumbase in (/usr/sbin:/usr/bin:/sbin:/bin)
```

So I would suggest to check your path first to make sure you're using the correct package version

**Comment by cengizili** [comment]
Both gives the same path for me. All I need is giving permissions to my script in order to save and load cookies, and I couldn't find a solution except running the pytest command as sudo, which brokes headed mode and I couldn't figure why. Can you try `sudo pytest <EXAMPLE>.py --headed` on your machine to check headed behaviour is fine, I need to be sure that the issue is related to my setup before doing destructive changes.

**Comment by mdmintz** [comment]
@cengizili Does ``sudo seleniumbase --version`` give you the same output as ``seleniumbase --version``?
Have you tried putting ``--headed`` in a ``pytest.ini`` file in the ``addopts =`` section? The latest SeleniumBase fixed the issue, but it looks like the ``sudo`` is still giving you old behavior somehow. Speaking of permissions issues, the latest version of seleniumbase, ``4.13.18`` just bumped the minimum version of ``filelock``, fixing a permissions issue that it had there. Probably unrelated, but have you tried ``4.13.18``?

**Comment by mdmintz** [comment]
@cengizili,  a quick way to know for sure if you have the correct version is to drop in a breakpoint in the middle of the test and see if the code is correct.
You can use ``pytest --trace`` to start with a breakpoint.
Call ``self._BaseCase__activate_virtual_display_as_needed()`` and inspect that code.

Expected in there:

```python
if "linux" in sys.platform and (not self.headed or self.xvfb):
```

If ``self.headed`` is True and ``self.xvfb`` is False, then ``Xvfb`` won't be activated.
(``--xvfb`` overrides ``--headed``)
Check your ``pytest.ini`` to make sure you're not using an arg that you don't want.
