### ISSUE TITLE
Driver auto submit when I just fill password field

### ISSUE THREAD

**Issue by phamxuanphongson** [seleniumbase/SeleniumBase#1816]
Hello, I have been using SeleniumBase for a while now, but recently, after I used a proxy to log in to TikTok, an error occurred.

I declared the driver using: from seleniumbase import Driver.
After entering the username using send_keys, when I entered the password, the submit button was immediately submitted, even though I only allowed to fill in the password and sleep for 100, because I wasn't ready to submit yet!
Now that I have removed the proxy, things are not the same as they used to be. The driver still automatically submits even though I don't allow it.

**Comment by phamxuanphongson** [comment]
I have checked a lot and there is no error thrown, I have tried to use sleep but it just skips the sleep, I am using the original selenium and there is no issue

**Comment by phamxuanphongson** [comment]
I have checked a lot and there is no error thrown, I have tried to use sleep but it just skips the sleep, I am using the original selenium and there is no issue

**Comment by phamxuanphongson** [comment]
#Click on the username element and continue to send keys
    browser.forceClick(usernameBtn)
    usernameBtn.send_keys(username)
    sleep(2)

    # Click on the password element and continue to send keys
    browser.forceClick(passwordBtn)
    passwordBtn.send_keys(password)
    sleep(2000)

    it even skips my sleep(2000)

**Comment by mdmintz** [comment]
Those are not SeleniumBase APIs, so this isn't a SeleniumBase issue.

But I can help you debug it: Use ``import pdb; pdb.set_trace()`` to drop in a breakpoint.
Then walk through the code to see what's going on. ``s`` + ``Enter``. Etc.

```bash
Debug Mode Commands:
n: Next line of method.
s: Step through.
c: Continue.
h: List all commands.
```
