### ISSUE TITLE
Load extensions in UC Mode

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#1817]
Hi, when I load extensions with uc not works, normal works:

```
driver = Driver(uc=True, extension_zip='./extensiones/dont_with_paste.crx')
driver = Driver(extension_zip='./extensiones/dont_with_paste.crx')
```

**Comment by mdmintz** [comment]
As mentioned in https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/867#issuecomment-1298946593, you need to convert your ``.crx`` file to a ``.zip`` file, and then unzip the file to a folder. Then use ``extension_dir=DIR`` as an option. UC Mode uses undetected-chromedriver, which doesn't support zipped/CRX extensions.

**Comment by FranciscoPalomares** [comment]
driver = Driver(uc=True,extension_dir='extensiones/dont_with_paste') #works
driver = Driver(uc=True,extension_dir='extensiones/multilogin') #works
driver = Driver(uc=True,extension_dir='extensiones/dont_with_paste,extensiones/multilogin') #not works

**Comment by mdmintz** [comment]
Worked for me after unzipping ``ad_block.zip`` and ``disable_csp.zip`` from https://github.com/seleniumbase/SeleniumBase/tree/master/seleniumbase/extensions, putting those folders into a ``temp`` folder, and then running a script:

```python
from seleniumbase import Driver

driver = Driver(uc=True, extension_dir="temp/disable_csp,temp/ad_block")
try:
    driver.get("https://nowsecure.nl/#relax")
    import pdb; pdb.set_trace()
finally:
    driver.quit()
```

<img width="1230" alt="Screenshot 2023-03-22 at 3 12 17 PM" src="https://user-images.githubusercontent.com/6788579/227012280-0a00ca1e-04c6-4234-b777-cc7079ba79c4.png">

**Comment by dexforint** [comment]
> Worked for me after unzipping `ad_block.zip` and `disable_csp.zip` from https://github.com/seleniumbase/SeleniumBase/tree/master/seleniumbase/extensions, putting those folders into a `temp` folder, and then running a script:
> 
> from seleniumbase import Driver
> 
> driver = Driver(uc=True, extension_dir="temp/disable_csp,temp/ad_block")
> try:
>     driver.get("https://nowsecure.nl/#relax")
>     import pdb; pdb.set_trace()
> finally:
>     driver.quit()
> <img alt="Screenshot 2023-03-22 at 3 12 17 PM" width="1230" src="https://user-images.githubusercontent.com/6788579/227012280-0a00ca1e-04c6-4234-b777-cc7079ba79c4.png">

This method doesn't work!

**Comment by mdmintz** [comment]
For custom extensions in UC Mode / CDP Mode after Chrome 142+, you'll need to use a custom chromium browser, such as Opera, Brave, or raw chromium. (Edge works too in the sb_cdp format.)

This is due to Chrome removing the `--load-extension` option in branded Chrome 142+ (for "security" reasons):

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/cf840b31-de0f-42a0-a543-1cead31e869d" />
