### ISSUE TITLE
set unhandledPromptBehavior capability using local browser

### ISSUE THREAD

**Issue by bt-ctsmith** [seleniumbase/SeleniumBase#1825]
I have the need to set the `unhandledPromptBehavior` capability to ignored when using a local browser instance. This appears to have been a change in how the weddrivers handle this specific capability in the past year, but I am not sure when. Before, I was able to do the below, and the alert would stay open between the click (which, in my case, presents a confirm alert) and `self.wait_for_and_accept_alert()`. See snippet below:

```
        self.update_text('#field', 'text')
        self.click('#save_button')
        self.wait_for_and_accept_alert()
```

I have tried using the `--cap_file` option, but looking at `browser_launcher.py` that only applies to remote instances, not local. I was able to force it by adding the capability in `_set_chrome_options` and `_set_firefox_options`.

seleniumbase: 4.13.18
selenium: 4.8.2

Fedora Linux 37
chromedriver: 111.0.5563.64
Chrome: 111.0.5563.146
geckodriver: 0.32.2
Firefox: 111.0.1 (602aa16c20d4 2023-02-08 00:09 +0000)

**Comment by bt-ctsmith** [comment]
Thank you for the work around, that did allow me to interact with the alert.

**Comment by Id1n** [comment]
hi
This method is great  `self.wait_for_ready_state_complete()`   , but it has one issue. When the alert has two or more buttons, it always selects Cancel. Is there any way to choose which button to select?

**Comment by mdmintz** [comment]
@Id1n Use self.accept_alert() for that.

**Comment by Id1n** [comment]
I have tried both methods `self.wait_for_and_accept_alert()`  and `self.accept_alert()`. They are not efficient when it's unclear whether an alert is present or not because they have unlimited wait times, and if an alert doesn't occur, it can disrupt the program. Method `self.wait_for_ready_state_complete()`, however, continues the process if the alert doesn't appear. The only issue is that it lacks the capability to change the button.

**Comment by Id1n** [comment]
I've tested almost all scenarios, but this alert won't dismiss, and it throws this error.

An error occurred: Alert Text: Are you sure you want to submit?
Message: unexpected alert open: {Alert text : Are you sure you want to submit?}
  (Session info: chrome=114.0.5735.134)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0088A813+48355]
	(No symbol) [0x0081C4B1]
	(No symbol) [0x00725358]
	(No symbol) [0x0077CDAD]
	(No symbol) [0x0076A536]
	(No symbol) [0x007482DC]
	(No symbol) [0x007493DD]
	GetHandleVerifier [0x00AEAABD+2539405]
	GetHandleVerifier [0x00B2A78F+2800735]
	GetHandleVerifier [0x00B2456C+2775612]
	GetHandleVerifier [0x009151E0+616112]
	(No symbol) [0x00825F8C]
	(No symbol) [0x00822328]
	(No symbol) [0x0082240B]
	(No symbol) [0x00814FF7]
	BaseThreadInitThunk [0x75907BA9+25]
	RtlInitializeExceptionChain [0x7755BD3B+107]
	RtlClearBits [0x7755BCBF+191]
<img width="337" alt="Screenshot 2023-11-12 145754" src="https://github.com/seleniumbase/SeleniumBase/assets/150162204/0cf4a613-bf1b-4dc4-a805-7b5ca48efefb">




 Do you think there's a way to handle it?

**Comment by mdmintz** [comment]
@Id1n Do a regular `element.click()` or `default_get(url)` action to get to that pop-up, then do `accept_alert()`.
