### ISSUE TITLE
"remote_debug" mode isn't working while in "uc" mode

### ISSUE THREAD

**Issue by bfgngfnfgmnggn** [seleniumbase/SeleniumBase#1827]
remote_debug mode
I have opened a google chrome locally, how to take over it with remote_debug,
Code below:
     driver = Driver(uc=True, remote_debug="http://127.0.0.1:52312")
it opens another browser and doesn't take over the original browser

**Comment by bfgngfnfgmnggn** [comment]
In undetected-chromedriver, although it will open another browser, it can normally take over the old browser and perform web page operations

**Comment by mdmintz** [comment]
I see the issue. I'll have it fixed in the next release. Note the the URL to access the remote debugger is chrome://inspect/#devices (And for Chrome windows to appear in that list, I think the remote debugging port will need to be hard-coded to 9222.)

**Comment by bfgngfnfgmnggn** [comment]
> I see the issue. I'll have it fixed in the next release. Note the the URL to access the remote debugger is chrome://inspect/#devices (And for Chrome windows to appear in that list, I think the remote debugging port will need to be hard-coded to 9222.)

Thank you, the port is provided by another software, it cannot be hardcoded

**Comment by mdmintz** [comment]
Released in ``4.13.22`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.13.22 (See link for details)
