### ISSUE TITLE
Is there a way to get the language of the website? Thanks

### ISSUE THREAD

**Issue by chenhaijun02** [seleniumbase/SeleniumBase#1835]
Is there a way to get the language of the website? I want to get the lang attribute value in the source code, is there a method in seleniumbase。Thanks
![1681184895838](https://user-images.githubusercontent.com/69953502/231051212-4af8f06b-3c83-42fb-90bc-19dd62a4a16e.jpg)

**Comment by mdmintz** [comment]
There is:
* ``self.get_locale_code()``

See example usage: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/locale_code_test.py

**Comment by mdmintz** [comment]
You can also do:

* ``self.get_attribute("html", "lang")``

**Comment by chenhaijun02** [comment]
@mdmintz  Thank you so much!
