### ISSUE TITLE
Specific chromedriver.exe

### ISSUE THREAD

**Issue by VeryFunnyXD** [seleniumbase/SeleniumBase#1841]
how can i do that, it downloads a new chromedriver everytime i run the program

**Comment by mdmintz** [comment]
SeleniumBase only downloads chromedriver if it can't find it. First it checks the ``seleniumbase/drivers`` folder, then it checks the rest of the PATH for the system you're running on.

To download chromedriver to your path on **macOS/Linux**, use:

``sbase get chromedriver --path``

On **Windows**, you can do ``sbase get chromedriver``, and then copy that directly to your PATH from ``seleniumbase/drivers``. (You may need to edit your System Environmental Variables from your Windows Settings.)

But the drivers need to be either in ``seleniumbase/drivers`` (based on where ``seleniumbase`` is installed) or on the System PATH.
