### ISSUE TITLE
Proxy for driver download

### ISSUE THREAD

**Issue by exelanz** [seleniumbase/SeleniumBase#1844]
Hi,

When I run "pytest myapp.py --proxy=server:port" the browser is using the proxy as expected. Only in the case of "missing driver" and "upgrade driver" myapp.py "hangs", the download of the driver does not work. I have seen this before with other driver managers, where a custom download manager was used.

Is there a way around this?

I am using Python 3.11.3, SeleniumBase 4.13.25.

Thanks

**Comment by mdmintz** [comment]
Hello, the ``--proxy=server:port`` is for the browser proxy settings, but when downloading a driver, that uses the ``requests`` library without a proxy. To avoid downloading the driver without a proxy, you may want to consider using a separate script to download the driver you need to the local ``seleniumbase/drivers`` folder, or to anywhere on your System PATH. Then run your tests with the proxy as needed after you have obtained a compatible driver.

**Comment by exelanz** [comment]
Hi Michael, thanks for your reply. Ok, this was my line of thinking as well. Might this be a feature request? To have selenium use a proxy for driver download?

**Comment by mdmintz** [comment]
Specifically, what is the error message that you get when you try downloading a driver without a proxy? Does it fail right away, or does it hang for a bit before failing. If I were to add such a feature, it would be part of the error-handling for driver downloads when the tests are also set to use a proxy. Eg. If the driver download failed with the default ``requests`` proxy settings, then try with the same proxy as the browser tests if a new proxy is specified for them.

**Comment by exelanz** [comment]
There is no error. It just hangs. I did not wait for some kind of time-out message if any. Longest run was 5 minutes. Yes I believe your description of the "feature" is correct.Thanks.

**Comment by mdmintz** [comment]
This was resolved by ``4.14.0`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.14.0

If you want to download a driver via proxy directly, use:
* ``sbase get DRIVER --proxy=server:port`` or ``sbase get DRIVER --proxy=user:pass@server:port``
--> Eg. ``sbase get chromedriver --proxy=user:pass@1.2.3.4:1234``

If you want tests that already use a proxy to also download the driver via the same proxy:
* ``pytest TEST.py --proxy=server:port --proxy-driver``
* ``pytest TEST.py --proxy=user:pass@server:port --proxy-driver``
(If you don't add the ``--proxy-driver`` option, the tests will still use proxy settings from ``--proxy=PROXY``, but the driver will be downloaded without using a proxy.)
