### ISSUE TITLE
Extra chrome options

### ISSUE THREAD

**Issue by M-Zubair10** [seleniumbase/SeleniumBase#1849]
I request to add feature to Driver function of seleniumbase to add extra_args parameter set to empty tuple by default so that in case if anyone want to use new option, he can add it using `extra_args=("--host-rules=...")

**Comment by mdmintz** [comment]
Duplicate. See https://github.com/seleniumbase/SeleniumBase/issues/1219#issuecomment-1040751512

There's ``--chromium-arg=ARG`` for a comma-separated list of Chromium args, but that's for ``chrome_options.add_argument()``. For changing the profile, (or for using ``add_experimental_option``), you'll need to override ``get_new_driver()`` from BaseCase. 
Here's an example of that:

```python
from selenium import webdriver
from seleniumbase import BaseCase


class OverrideDriverTest(BaseCase):

    def get_new_driver(self, *args, **kwargs):
        """ This method overrides get_new_driver() from BaseCase. """
        options = webdriver.ChromeOptions()
        options.add_experimental_option(
            "excludeSwitches", ["enable-automation"]
        )
        options.add_experimental_option("useAutomationExtension", False)
        if self.headless:
            options.add_argument("--headless")
        return webdriver.Chrome(options=options)

    def test_simple(self):
        self.open("https://seleniumbase.io/demo_page")
        self.assert_text("Demo Page", "h1")
```
