### ISSUE TITLE
Issue with uc cdp events

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#1872]
Ucdp events not works in version 13 chromedriver. i need to change in:
driver = Driver(uc=True, proxy='...', headless=headless,  uc_cdp_events= True)

in 13 version not works ucdp events, in version 12 it works

**Comment by mdmintz** [comment]
This is working fine for me on ``chromedriver`` 113:

```python
import time
from pprint import pformat
from seleniumbase import Driver

driver = Driver(uc=True, headless=True, uc_cdp_events=True)
driver.add_cdp_listener(
    "Network.requestWillBeSentExtraInfo",
    lambda data: print(pformat(data))
)
driver.get("https://nowsecure.nl/#relax")
time.sleep(8)
driver.quit()
```

Your issue may be with your personal proxy. The driver has to match your version of Chrome, as mentioned in https://github.com/seleniumbase/SeleniumBase/issues/1871, and ``driver.add_cdp_listener()`` is working correctly, as mentioned in https://github.com/seleniumbase/SeleniumBase/issues/1870

**Comment by FranciscoPalomares** [comment]
Hello,
Is there a way to change the version to 12 from Python itself?

**Comment by mdmintz** [comment]
I'm assuming you mean 112 and 113, as there isn't a 12 or 13 for chromedriver. And no, the version of chromedriver needs to match the chrome version, so if you need chromedriver 112, downgrade to Chrome 112 and then your chromedriver will also be 112.
