### ISSUE TITLE
Maintainer on vacation from May 12 to May 24, 2023

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1878]
Hey, this is the maintainer of SeleniumBase. I'll be on vacation May 12 to May 24. Responses will be very delayed. I might be able to respond to simple questions via smartphone, but I plan on keeping the laptop lid closed during the trip, so I probably won't answer any questions until I'm back.

**Comment by alimp5** [comment]
I would thank you dear 🥇@mdmintz🥇  and  🥇 all contributors🥇.
have the best times ;XXXX

**Comment by mdmintz** [comment]
I'm back from vacation and shipped version ``4.14.10`` last night.
