### ISSUE TITLE
Better handle cases where pytest nodeIds cause linux file lengths to exceed 255 bytes

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#1882]
If you have long nodeIds, seleniumbase is trying to write some files to disk and isn't handling them gracefully due to no exception handling when performing `codecs.open`. 

[Here](https://github.com/seleniumbase/SeleniumBase/blob/fda7a286c4a0b2cb9015baa19d825b89834c8c1b/seleniumbase/core/log_helper.py#L292)

This can cause OSErrors as part of test execution:

```shell
 log_file = codecs.open(basic_file_path, "w+", "utf-8")
OSError: [Errno 5] Input/output error: 'latest_logs/<very long node id from a test item>/basic_test_info.txt'
```

**Comment by mdmintz** [comment]
This was resolved in ``4.14.10`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.14.10
