### ISSUE TITLE
How Can I open multiple browser via driver manager (via direct import) with deferent user_data_dir 

### ISSUE THREAD

**Issue by anovob** [seleniumbase/SeleniumBase#1887]
How Can I open multiple browser via driver manager (via direct import) with deferent `user_data_dir`

I am using Tkinter to open browser. When I open first browser by clicking in tkinter button its open and running. But when I click to open second browser its not open. I also want to use deferent `user_data_dir` for all browser.

Note: I am using UC mode.

**Comment by mdmintz** [comment]
See get_new_driver() in https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md
There are args to set the user_data_dir, etc. UC mode might not fully support changing the default user_data_dir. It’s an external issue with Undetected Chromedriver. If you want parallel runs, you’ll need to use pytest multithreading, which comes with the pytest-xdist plugin.

**Comment by anovob** [comment]
But I used that option with seleniumbase. But it's stop working when chromedriver updated version to 113.

**Comment by anovob** [comment]
And also its working with undetected-chromedriver. But they can not bypass Cloudflare in headless mode

**Comment by anovob** [comment]
If I use `Driver(user_data_dir=user_data_dir, chromium_arg=chromium_arg)` It's working fine.
If I use `Driver(user_data_dir=user_data_dir, uc=True)` It's not working

**Comment by anovob** [comment]
Here Is my Code:

`project_dir = pathlib.Path().absolute()

def start_open_browser():
    num = default_browser.get()
    num = int(num)
    event = threading.Event()
    thrSet = threading.Thread(target=start_application, args=(None, num))
    thrSet.daemon = True
    thrSet.start()
    event.set()


def start_driver(arg=None, i=0):
    user_data_dir = str(project_dir / 'userdatas' / f"userdata{i}")
    driver = Driver(user_data_dir=user_data_dir, uc=True)
    driver.maximize_window()
    return driver


def start_application(arg=None, browser=0):
    driver = start_driver(arg, browser)
    while True:
        try:
            time.sleep(10)
            driver.get('https://www.youtube.com/watch?v=3xYXUeSmb-Y')
        except NoSuchWindowException:
            break
        except:
            continue
    driver.quit()
    return




if __name__ == "__main__":
    multiprocessing.freeze_support()

    root = Tk()

    # display section
    frame = LabelFrame(root, text="Start Application", font=('Helvetica bold', 12))
    frame.pack(fill="both", expand=False, padx=20, pady=5)
    browser_number = ['1', '2', '3', '4', '5', '6', '7']
    default_browser = StringVar()
    default_browser.set(browser_number[0])
    ent_browser = OptionMenu(frame, default_browser, *browser_number)
    ent_browser.pack(fill='both', expand=False, padx=10, pady=10, side=LEFT)
    btn_browser = Button(frame, text='Start Application', command=start_open_browser, height=1,
                         font=('Helvetica bold', 15))
    btn_browser.pack(fill='both', expand=True, padx=10, pady=11, side=LEFT)

    root.title(f"Testing")
    root.mainloop()`


When I open first browser this is working fine. When I open other browser Chrome opens with "Data;" with selenium


I also print driver first time open uc_driver. second time open cromedriver
Here is the driver print value
1st: `<seleniumbase.undetected.Chrome (session="818e958ca40f0e419c3681f57b163957")>`
2nd: `<selenium.webdriver.chrome.webdriver.WebDriver (session="eb419ef2a305c5fbc7f337e42f99f379")>`
