### ISSUE TITLE
Running tests in parallel on multiple browsers through remote Selenium Grid (but not a test farm)

### ISSUE THREAD

**Issue by gg-synamedia** [seleniumbase/SeleniumBase#1888]
On a remote machine called _my_grid_, I started a grid like this:
`docker run -d -p 4442-4444:4442-4444 -e SE_OPTS="--log-level FINE" --name selenium-hub selenium/hub:4.9.1-20230508`

I registered to the grid chrome, edge and safari selenium test nodes, running on Windows and Macs, like this:
`java -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.9.1.jar --ext selenium-http-jdk-client.jar node --host "$my_ip" --port "$my_port" --hub "my_grid"`  

Now using seleniumBase I can trigger a test through the grid against each browser separately, by specifying --edge, --safari etc.    

However I cannot benefit from the grid and run the tests on all three browsers in parallel.   
I tried the following but it runs only chrome:
`pytest test_mfa_login.py --browser="remote" --cap-file='caps.py' -n=3 --server="my_grid"`   

Where caps.py is:  
```
capabilities = [
    {"browserName": "chrome"},
    {"browserName": "safari"},
    {"browserName": "MicrosoftEdge"},
]
```
Is there a way to run on all browsers in parallel?

**Comment by mdmintz** [comment]
Use get_new_driver() from https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md to open the browser you want from within a test. There can only be one default browser, but you can always open another if the one you want isn’t the default. Works well with parameterized tests (see examples in the examples/ folder).
