### ISSUE TITLE
Prevent testing the default Chrome when running tests in parallel on multiple browsers in remote

### ISSUE THREAD

**Issue by gg-synamedia** [seleniumbase/SeleniumBase#1896]
I have a remote Selenium grid (but not a farm!) with chrome, edge and safari test nodes registered permanently.   
Sometimes I want to run tests only on Edge and Safari, but it always runs also on Chrome. 
How can I prevent the Chrome testing?

I ran the command:
```
pytest test_multi_direct.py -sv --server 
```
With the this [simplified] code:
```
import pytest
class Test_MultiBrowser:

    @pytest.fixture(autouse=True)
    def get_driver(self, sb, browser):
        if browser != "":
            browserNames = {'chrome': 'chrome', 'safari': 'safari', 'edge': 'MicrosoftEdge'}
            name = browserNames[browser]
            cap_string='{"browserName":"' + name + '"}'
            sb.get_new_driver(browser="remote", cap_string=cap_string)

    @pytest.mark.parametrize(
        "browser", ["edge","safari"]
    )
    def test1(self, sb, browser):
        print("browser=" + browser)
        print("sb.browser=" + sb.browser)
        sb.open("https://seleniumbase.io/realworld/login")
```

In fact I tried also adding a --two_browsers parameter to control that from command line, by adding this conftest.py (and removing parameterize mark over the test), but Chrome gets tested anyway:
```
import pytest

def pytest_addoption(parser):
    parser.addoption("--two_browsers", action="store_true", help="run on two browsers")

def pytest_generate_tests(metafunc):
    if "browser" in metafunc.fixturenames:
        if metafunc.config.getoption("browsers"):
            metafunc.parametrize("browser", ["edge","safari"])
        else:
            metafunc.parametrize("browser", [""])
```

**Comment by mdmintz** [comment]
As listed in detail in the capabilities ReadMe here: https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities, if using "remote" as the browser, the capabilities file determines the browser, and different selenium grids will process the capabilities files differently. It’s up to the grid that you use to parse the capabilities correctly. Alternatively, you could set the browser directly and avoid using the capabilities file if you don’t need the specific configuration that your capabilities file sets. Eg. browser="safari", etc.

**Comment by gg-synamedia** [comment]
I would like to run the same test simultaneously on several browsers in the same run, 
i.e. not running pytest with --edge then with --safari etc.   
Following your proposal ([here](https://github.com/seleniumbase/SeleniumBase/issues/1888#issuecomment-1566355487)) I tried with sb.get_new_driver and @pytest.mark.parametrize for browsers.   
The problem is that while get_new_driver adds a browser, Chrome was already created in the base class setUp, 
and so Chrome is always sent.   

I could use the capabilities file if it would be possible to specify several browsers like:
```
capabilities = [
  {
    "browserName": "safari"
  },
  {
    "browserName": "MicrosoftEdge"
  }
]
```
but it seems SB does not accept that. 

BTW I am using the standard [Selenium 4 Grid](https://www.selenium.dev/documentation/grid/)

**Comment by mdmintz** [comment]
There’s going to be one default browser per run, but then you can use parameterization to switch to a different one from there. With get_new_driver(), you can do that. If you need to close a browser early, you can use self.driver.quit()

**Comment by gg-synamedia** [comment]
Thanks!  self.driver.quit() does it.
For anyone interested, the working solutions looks like:
```
import pytest
class Test_MultiBrowser:
    @pytest.fixture(autouse=True)
    def get_driver(self, sb, browser):
        if browser != "":
            sb.driver.quit()  # <---  added this line
            browserNames = {'chrome': 'chrome', 'safari': 'safari', 'edge': 'MicrosoftEdge'}
            name = browserNames[browser]
            cap_string='{"browserName":"' + name + '"}'
            sb.get_new_driver(browser="remote", cap_string=cap_string)

    @pytest.mark.parametrize(
        "browser", ["edge","safari"]
    )
    def test1(self, sb, browser):
        print("browser=" + browser)
        print("sb.browser=" + sb.browser)
        sb.open("https://seleniumbase.io/realworld/login")
        # etc..
```
