### ISSUE TITLE
"Personalize your web experience" notification appears when running on Edge

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1897]
## "Personalize your web experience" notification appears when running on Edge

This notification is intrusive, and should be disabled somehow:

--------

<img width="360" alt="Screenshot 2023-06-06 at 2 35 46 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/b6fc79cb-3cfa-4c29-89ff-97fd0954247c">

--------

The easiest way to remove this is by running in ``--guest`` mode. If that has to become the default setting on Edge to remove the notification, then that should be done. Guest mode was already the default setting for Windows users ever since the "Sync your profile" notification appeared. Since Chromium extensions don't work in Guest Mode, we'll keep the default settings for that, even if that means keeping the notifications. Perhaps there's another way to remove the notifications and still allow extensions?

**Comment by mdmintz** [comment]
In ``4.14.13``, ``--guest`` mode becomes the default mode on Edge unless using the SeleniumBase Recorder or disabling the CSP, which requires extensions (extensions don't work in Guest Mode).

**Comment by mdmintz** [comment]
Reopening because the issue still happens if using extensions.

**Comment by cprimis** [comment]
This is still not fixed for me without changing anything around in my code. Any idea how to access the prefs dict in python?

**Comment by mdmintz** [comment]
@cprimis  The `prefs` dict is not directly accessible. It can be changed via command-line options where available.

Were you using the latest version of `seleniumbase`? The "Personalize your web experience" notification did not appear for me. I would need more info to debug your particular situation. Was there something that you were able to change to prevent that pop-up for you?
