### ISSUE TITLE
Sorry,i am detected by 'https://antoinevastel.com/bots/'

### ISSUE THREAD

**Issue by ngantsung** [seleniumbase/SeleniumBase#1912]
Hilo , I use the uc mode and undetectable  in SeleniumBase driver , and which is so powerful ,less website can detect my programming .However , I am detected by 'https://antoinevastel.com/bots/' .Therefore , please help me to solve this problem !
<img width="1046" alt="Screenshot 2023-06-13 at 11 52 23 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/111569568/654c4799-2467-46b6-9c12-7ee55d6ae8a3">
<img width="1392" alt="Screenshot 2023-06-13 at 11 52 48 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/111569568/3da37139-23a2-46d0-b92e-01c4d6cb67b3">

**Comment by mdmintz** [comment]
I got the same result when using a regular Chrome browser, so the ``Inconsistent`` value there isn't accurate.

But the following script works, so it means anti-detection is working:

```python
from seleniumbase import Driver
import time

driver = Driver(uc_cdp=True, incognito=True)
driver.get("https://antoinevastel.com/bots/datadome")
time.sleep(5)
driver.quit()
```

<img width="1267" alt="Screenshot 2023-06-13 at 12 05 11 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/ec2b532c-8024-441e-9846-ac6506240f91">
