### ISSUE TITLE
The best option choose of click() in anti-detected 

### ISSUE THREAD

**Issue by ngantsung** [seleniumbase/SeleniumBase#1913]
Yes , I know there are  js().click(),   page_action.click(),  find_element_click()  ,jQuery().click(),   pyauto.click(). However, what is the best option for me to not be detected in using click() function as my program has to work in high security environment ,many thanks.

**Comment by mdmintz** [comment]
If a regular ``click()`` isn't enough to avoid bot-detection, you can try https://pyautogui.readthedocs.io/en/latest/ to avoid direct browser clicks.
