### ISSUE TITLE
Remote execution on browserstack, how to set the window to maximize

### ISSUE THREAD

**Issue by chenhaijun02** [seleniumbase/SeleniumBase#1915]
I execute on browserstack remotely using **--browser=remote --maximize --server=aloneblood_YjhrWv:5V4xVAFNb45fSaZV5Xax@hub.browserstack.com --port=80 --cap_file=config/cap_file_BS.py** but the window is not maximized. What else do I need to do?
Thank you so much!
![image](https://github.com/seleniumbase/SeleniumBase/assets/69953502/2cd7cf1d-3cda-40d7-8d76-741c18b5b854)

**Comment by mdmintz** [comment]
Try calling ``self.maximize_window()`` from your tests at the beginning.

**Comment by chenhaijun02** [comment]
@mdmintz Work fine. Thanks!
