### ISSUE TITLE
How can I add cookies as it's done in Selenium?

### ISSUE THREAD

**Issue by magicpigomg** [seleniumbase/SeleniumBase#1919]
How can I add cookies as it's done in Selenium?

**Comment by mdmintz** [comment]
SeleniumBase has access to all selenium driver commands via ``self.driver``. Which means you can do anything that you could do via regular selenium.

SeleniumBase also has special APIs for cookies. These methods let you save and load cookies to/from files:

```python
self.save_cookies(name="cookies.txt")

self.load_cookies(name="cookies.txt")
```

For working with cookies, see https://www.selenium.dev/documentation/webdriver/interactions/cookies/
