### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: /usr/lib/python3.11/site-packages/seleniumbase/drivers/chromedriver_linux64.zip

### ISSUE THREAD

**Issue by carlosal1015** [seleniumbase/SeleniumBase#1926]
Hi, I would like to use [`chromedriver`](https://aur.archlinux.org/packages/chromedriver) over `/usr/bin/chromedriver`, but if this is not found, we use the command

```
$ sbase get chromedriver latest

*** chromedriver version for download = 114.0.5735.90 (Latest)

Downloading chromedriver_linux64.zip from:
https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip ...

* Unable to download driver! Retrying in 3s...


*** chromedriver version for download = 114.0.5735.90 (Latest)

Downloading chromedriver_linux64.zip from:
https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip ...
** Unable to download driver! Retrying in 5s...


*** chromedriver version for download = 114.0.5735.90 (Latest)

Downloading chromedriver_linux64.zip from:
https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip ...
Traceback (most recent call last):
  File "/usr/sbin/sbase", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/seleniumbase/console_scripts/run.py", line 1006, in main
    sb_install.main()
  File "/usr/lib/python3.11/site-packages/seleniumbase/console_scripts/sb_install.py", line 720, in main
    with open(file_path, "wb") as file:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/seleniumbase/drivers/chromedriver_linux64.zip'
```
I am packaging [`python-seleniumbase`](https://aur.archlinux.org/packages/python-seleniumbase) in order to test [`trame-client`](https://pypi.org/project/trame-client).

**Comment by mdmintz** [comment]
This looks like your Linux user doesn't have the permissions necessary to access that folder.

There are a few ideas, such as https://stackoverflow.com/a/23871224/7058266

Try with ``chmod`` or ``chown``. Or use a user that has access to that folder. (`root` or other).

Alternatively, you can try manually getting the file, (eg. with `wget`), and then placing the `chromedriver` file on your `PATH` (eg. in `/usr/local/bin`).

Also, it's possible that the download will succeed if you let the test get it automatically (because the permissions may be different).

**Comment by boludoz** [comment]
I think it is a bug and should be solved, I am using Windows and it didn't happen before.

**Comment by boludoz** [comment]
He requested that it be reopened to try to find a solution.

**Comment by boludoz** [comment]
This does not happen with the normal driver.

**Comment by mdmintz** [comment]
@boludoz The base algorithm of the SeleniumBase Chromedriver Patcher is unchanged from the `undetected-chromedriver` version:

https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/0aa5fbe252370b4cb2b95526add445392cad27ba/undetected_chromedriver/patcher.py#L347

If you have an issue with the Patcher, mention that in the `undetected-chromedriver` repo.

**Comment by boludoz** [comment]
> @boludoz The base algorithm of the SeleniumBase Chromedriver Patcher is unchanged from the `undetected-chromedriver` version:
> 
> https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/0aa5fbe252370b4cb2b95526add445392cad27ba/undetected_chromedriver/patcher.py#L347
> 
> If you have an issue with the Patcher, mention that in the `undetected-chromedriver` repo.

The problem seems to be that a uc_driver.exe remains open.

**Comment by boludoz** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1655

In fact I made some proposals for changes.

**Comment by boludoz** [comment]
I would really like to investigate if it is possible to do this multi-instance but I don't have time.

**Comment by mdmintz** [comment]
Multithreaded UC Mode **without** using `pytest -n NUM` is going to be officially announced in the second UC Mode video tutorial that I'm currently trying to prepare the presentation for. The fewer GitHub notifications I see until then, the faster it gets done.
