### ISSUE TITLE
headless2

### ISSUE THREAD

**Issue by xiaocf-git** [seleniumbase/SeleniumBase#1935]
why some time , in headless2 mode, seleniumbase cannot find the element, but can find the element in no headless2 mode, i use the method wait_for_ready_state_complete(), it didn't work

**Comment by mdmintz** [comment]
There are two different headless modes, which can be activated by ``--headless`` or ``--headless2`` on the command-line when running tests. The first one, ``--headless`` is Chrome's original headless mode (``options.add_argument("--headless")``), which has different behavior from regular mode. It can be faster, but it also might not render the page exactly like a regular browser would. There's also ``--headless2``, which is Chrome's new headless mode (``options.add_argument("--headless=new")``). It renders the page exactly like regular headed mode would. More info: https://stackoverflow.com/a/73840130/7058266
