### ISSUE TITLE
Screenshot of an element is not saved in full size

### ISSUE THREAD

**Issue by qomhmd** [seleniumbase/SeleniumBase#1947]
The problem is that an element is saved in a shorter height e.g., 89 pixels sized in the browser's DevTool became 57 pixels in the resultant PNG image.

**Comment by mdmintz** [comment]
These are the commands for saving screenshots:

```python
self.save_element_as_image_file(selector, file_name, folder=None, overlay_text="")

self.save_screenshot(name, folder=None, selector=None, by="css selector")
```

The first one uses ``element.screenshot_as_png``, (which is Selenium's internal method for saving an image, which is used after finding the element).

The second one uses ``driver.get_screenshot_as_file(screenshot_path)``, (where ``screenshot_path`` is where the image gets saved).

Screenshots will be based on the current size of the browser. If you want them bigger or smaller, changing the window size may change that. SeleniumBase methods call Selenium's methods indirectly for saving screenshots.
