### ISSUE TITLE
Getting detected by cloudflare 

### ISSUE THREAD

**Issue by bfgngfnfgmnggn** [seleniumbase/SeleniumBase#1949]
uc=True

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1388

**Comment by mdmintz** [comment]
Looks like something changed on CloudFlare's side. Based on observations, this should be an easy fix. I created a new ticket for it: https://github.com/seleniumbase/SeleniumBase/issues/1953

**Comment by bfgngfnfgmnggn** [comment]
> 这是通过`4.15.14`- [https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.15.14解决的](https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.15.14)

Thanks
