### ISSUE TITLE
dir latest_logs and  archived_logs move to another dir

### ISSUE THREAD

**Issue by xianyo** [seleniumbase/SeleniumBase#1950]
i do not want to latest_logs and  archived_logs in  ./
dir latest_logs and archived_logs move to another dir?

i just install SeleniumBase and not used now, and then run pytest, my test failed, it will have empty dir  latest_logs and  archived_logs

**Comment by mdmintz** [comment]
See https://github.com/seleniumbase/SeleniumBase/discussions/1413#discussioncomment-3148458 and https://github.com/seleniumbase/SeleniumBase/issues/486

The ``latest_logs/`` folder is created from the location where ``pytest`` is called. Not configurable, for reasons outlined in https://github.com/seleniumbase/SeleniumBase/issues/486

You can always run ``pytest`` from a different folder to have the logs created there.
