### ISSUE TITLE
how to add 2 extension ?

### ISSUE THREAD

**Issue by ngantsung** [seleniumbase/SeleniumBase#1960]
how to add 2 extension ? Thanks for response

**Comment by mdmintz** [comment]
Use the ``pytest --extension-zip=ZIP1.zip,ZIP2.zip`` /  ``pytest --extension-dir=DIR1,DIR2`` to load multiple extensions.

It should be comma-separated with no spaces in between.

From the documentation:

```bash
pytest --extension-zip=ZIP  # (Load a Chrome Extension .zip|.crx, comma-separated.)
pytest --extension-dir=DIR  # (Load a Chrome Extension directory, comma-separated.)
```

Eg.

```bash
pytest --extension-zip=ZIP1.zip,ZIP2.zip
pytest --extension-dir=DIR1,DIR2
```
