### ISSUE TITLE
The Chromium Team changed how they package drivers!

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1968]
## The Chromium Team changed how they package drivers!

If you go to https://chromedriver.chromium.org/downloads you'll see that available chromedrivers stop at version 114. That's because they said this:

> "If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading."

Here's what that means for SeleniumBase users: You'll need to upgrade to the latest version of SeleniumBase (at least ``4.16.1``) so that you get the update that keeps the gears turning. There was a fix for https://github.com/seleniumbase/SeleniumBase/issues/1966 in the release: https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.16.1

If you continue to use an earlier version of SeleniumBase, you'll see this warning message with Chrome 115: ``Warning: chromedriver update needed. Getting it now:`` at the start of every test because it keeps trying to download chromedriver 115 from the wrong location, so it gets chromedriver 114 instead, and uses that, which works. Once Chrome reaches version 116, you'll likely start seeing errors if you don't upgrade.

SeleniumBase ``4.16.1`` made a change so that chromedriver 114 continues to work with Chrome 115 (and above). Given the major changes to chromedriver starting in 115, such as requiring a special [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) binary to work (see https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30), it seems that keeping the 114 chromedriver functional is a better plan for now. Will reevaluate after Chrome 116 comes out.

**Comment by mathiasbynens** [comment]
> Given the major changes to chromedriver starting in 115, such as requiring a special [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) binary to work (see https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30) […]

As part of the release process changes, we didn’t make any changes to the ChromeDriver binary itself. ChromeDriver certainly doesn’t _require_ a CfT binary. What makes you say otherwise?

**Comment by mathiasbynens** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1466427

**Comment by mdmintz** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1466427#c27

> `"The patches have been backmerged, but no release containing them has been made yet. We hope to get a release out by the end of next week. Thank you for your patience."`

Once those patches have been backmerged, it may be safe to upgrade SeleniumBase's driver manager. (In the current state, SeleniumBase is forcing ``chromedriver`` ``114`` via ``service_args=["--disable-build-check"]``. Even if the browser version is ``115`` or higher, this configuration has been set to work properly.

**Comment by mdmintz** [comment]
Chromedriver 115.0.5790.170 was just released, fixing the issue mentioned above. The next SeleniumBase release will start using Chromedriver 115 for Chrome 115, instead of patching Chromedriver 114 for that.

**Comment by mdmintz** [comment]
Work completed in https://github.com/seleniumbase/SeleniumBase/issues/1983 and released in ``4.17.1`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.17.1
