### ISSUE TITLE
Using headless in code

### ISSUE THREAD

**Issue by reeexpert** [seleniumbase/SeleniumBase#1986]
Hey I want to use Flask with a function the uses SB. The documentation shows that I can use the headless mode only from outside when using it as a script "--headless" but I want to include that in the function is there any way?

I use "with SB(uc=True) as sb:"

**Comment by mdmintz** [comment]
You can do this:

``with SB(uc=True, headless=True) as sb:``

Eg:

```python
from seleniumbase import SB

with SB(uc=True, headless=True) as sb:
    sb.open("data:text/html,<div>Hello<br><input></div>")
    sb.type("input", "Goodbye")
    sb.click("html body > div")
    sb.assert_element("input")
    sb.assert_text("Hello", "div")
    sb.highlight("div")
    sb.sleep(0.5)
```

Or:

```python
from seleniumbase import SB

with SB(uc=True, headless=True) as sb:
    sb.open("https://nowsecure.nl/#relax")
    sb.assert_text("OH YEAH, you passed!", "h1")
    sb.sleep(1)
    sb._print("\n*Selenium was not detected*\n")
```

See https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/sb_manager.py for all options.
