### ISSUE TITLE
Changing proxy settings can cause "ConnectionError" in UC Mode

### ISSUE THREAD

**Issue by bfgngfnfgmnggn** [seleniumbase/SeleniumBase#1995]
In UC mode, an error is being reported as follows: {ConnectionError}HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with URL: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000218E9445400>: Failed to establish a new connection: [WinError 10060].

It appears that before opening the URL, SeleniumBase performs an internal check, but it doesn't use the browser's IP proxy. When I manually enter google.com in the browser, it opens successfully.

The driver successfully opens a website that does not require a proxy,The driver failed to open the website that requires a proxy

**Comment by mdmintz** [comment]
I see the issue. It will be fixed in the next release.

**Comment by mdmintz** [comment]
This was resolved in `4.17.3` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.17.3
