### ISSUE TITLE
SeleniumBase UC Mode needs a video tutorial

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2000]
## SeleniumBase UC Mode needs a video tutorial

There should first be a prelude on how sites detect Selenium in general.

Then there should be an explanation on how automation frameworks can avoid being detected by websites with anti-bot services.

--------

### Key things that Selenium frameworks need to do in order to avoid getting detected:

* Modify chromedriver to rename chromedriver-specific variables that appear in the Chrome DevTools console.
* Launch Chrome before attaching chromedriver to it. (Don't use chromedriver to launch Chrome directly.)
* Don't use Chrome options that are specific to Selenium (or ones that are generally only used with Selenium).
* If using headless Chrome, make sure that you change `HeadlessChrome` to `Chrome` in the User Agent String.
* If specifying a custom `user_data_dir`, make sure that the folder is never used with non-UC-Mode Chrome.
* Disconnect chromedriver temporarily from Chrome before loading websites that try to detect chromedriver.

--------

When all preventative measures are done correctly, Selenium should be able to enter websites appearing human:

<img width="568" alt="Undetected SeleniumBase" src="https://user-images.githubusercontent.com/6788579/213031519-0220d19f-e210-4858-b6b5-9253b112efe4.png">

--------

### Here are some existing examples that use ``--uc`` mode:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py

### Here's a raw driver example:

```python
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(6)
driver.quit()
```

**Comment by aavvaavvaa** [comment]
Hello, thank you for your work. 
Is it possible to change/hide screen resolution, videocard information?

**Comment by mdmintz** [comment]
Here's a multithreaded example that can be run with `pytest --uc -n4 `

```python
import pytest
from random import randint
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__, "--uc", "-n4")


@pytest.mark.parametrize("", [[]] * 4)
def test_multi_threaded(sb):
    sb.driver.get("https://nowsecure.nl/#relax")
    sb.set_window_rect(randint(0, 750), randint(0, 400), 700, 500)
    try:
        sb.assert_text("OH YEAH, you passed!", "h1", timeout=5.25)
        sb.post_message("Selenium wasn't detected!", duration=2.8)
        sb._print("\n Success! Website did not detect Selenium! ")
    except Exception:
        sb.driver.get("https://nowsecure.nl/#relax")
        try:
            sb.assert_text("OH YEAH, you passed!", "h1", timeout=5.25)
            sb.post_message("Selenium wasn't detected!", duration=2.8)
            sb._print("\n Success! Website did not detect Selenium! ")
        except Exception:
            sb.fail('Selenium was detected! Try using: "pytest --uc"')
```

**Comment by mdmintz** [comment]
The video is ready. Enjoy! https://www.youtube.com/watch?v=5dMFI3e85ig

<a href="https://www.youtube.com/watch?v=5dMFI3e85ig"><img src="http://img.youtube.com/vi/5dMFI3e85ig/0.jpg" title="SeleniumBase on YouTube" width="285" /></a>

**Comment by mdmintz** [comment]
See https://www.youtube.com/@MichaelMintz/videos for my YouTube channel.

See https://www.youtube.com/playlist?list=PLp9uKicxkBc5UIlGi2BuE3aWC7JyXpD3m for the SeleniumBase playlist.

**Comment by mdmintz** [comment]
Closing this ticket in favor of the newer https://github.com/seleniumbase/SeleniumBase/issues/2213
