### ISSUE TITLE
find_text raising exception

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2021]
is there a way to call find_text, than if not exist, dont raise exception just return False ?

```
with SB(...) as sb:
   ...
   if sb.find_text("welcome", timeout=3):
      print("true")
   else:
      print("false")
```

**Comment by mdmintz** [comment]
Use `sb.is_text_visible(text)` for a text method that returns True or False.

See [help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) for a list of all methods.

**Comment by YOTYTeaM** [comment]
> Use `sb.is_text_visible(text)` for a text method that returns `True` or `False`.
> 
> `sb.find_text(text)` is supposed to raise an exception if the text doesn't appear within the timeout.
> 
> Those methods with full args:
> 
> ```python
> self.is_text_visible(text, selector="html", by="css selector")
> 
> self.find_text(text, selector="html", by="css selector", timeout=None)
> ```
> 
> See [help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) for a list of all methods.

thanks


this code working:
```
with SB(...) as sb:
      def text_exists(text, timeout=None):
            try:
                sb.find_text(text, timeout=timeout)
                return True
            except:
                return False
       ...
```
