### ISSUE TITLE
everytime i running the codes, it downloading chromedriver again

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2022]
everytime i running the codes, it downloading chromedriver again

everytime i running the codes, it shows:
```
Warning: chromedriver update needed. Getting it now:

*** chromedriver version for download = 116.0.5845.96 (Latest)

Downloading chromedriver-win64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip ...
```

the arguments i used:
`with SB(uc=True, agent=user_agent, slow=True) as sb:`

**Comment by mdmintz** [comment]
I'm running this script and I can't reproduce your issue:

```python
from seleniumbase import SB

with SB(uc=True, agent="Mozilla/5.0", slow=True) as sb:
    sb.open("seleniumbase.io")
with SB(uc=True, agent="Mozilla/5.0", slow=True) as sb:
    sb.open("seleniumbase.github.io")
with SB(uc=True, agent="Mozilla/5.0", slow=True) as sb:
    sb.open("seleniumbase.github.io/demo_page")
```

What version of SeleniumBase are you using? What OS? Are you adding any additional command-line options?

SeleniumBase downloads drivers into the `seleniumbase/drivers` folder. If that folder is deleted between tests, then you'll need to download the driver again

**Comment by YOTYTeaM** [comment]
> I'm running this script and I can't reproduce your issue:
> 
> ```python
> from seleniumbase import SB
> 
> with SB(uc=True, agent="Mozilla/5.0", slow=True) as sb:
>     sb.open("seleniumbase.io")
> with SB(uc=True, agent="Mozilla/5.0", slow=True) as sb:
>     sb.open("seleniumbase.github.io")
> with SB(uc=True, agent="Mozilla/5.0", slow=True) as sb:
>     sb.open("seleniumbase.github.io/demo_page")
> ```
> 
> What version of SeleniumBase are you using? What OS? Are you adding any additional command-line options?
> 
> SeleniumBase downloads drivers into the `seleniumbase/drivers` folder. If that folder is deleted between tests, then you'll need to download the driver again

i deleted `...\venv\Lib\site-packages\seleniumbase\drivers\chromedriver.exe`  and it fixed
