### ISSUE TITLE
google can detect me

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2024]
google detect me

i made app that login in google account and doing something..

i change my ip but it still detecting me

i think google using fonts and gpu to find me
is SeleniumBase saving cookies?
how can i disable gpu?

**Comment by mdmintz** [comment]
This login script works:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.open("https://www.google.com/gmail/about/")
    sb.click('a[data-action="sign in"]')
    sb.type('input[type="email"]', "test123@gmail.com")
    sb.click('button:contains("Next")')
    import pdb; pdb.set_trace()
    # sb.type('input[type="password"]', PASSWORD)
    # sb.click('button:contains("Next")')
```

Google and others can block you if they detect unusual traffic coming from your IP address. You can pass in additional Chrome options via `chromium_arg` with a comma-separated list. Some options make you more-easily detectable.
