### ISSUE TITLE
how does this bypass cloudflare

### ISSUE THREAD

**Issue by NCLnclNCL** [seleniumbase/SeleniumBase#2026]
Disconnect and connect, right??

**Comment by mdmintz** [comment]
SeleniumBase **UC Mode** is used for bypassing bot-detection services. It's not the default mode, but it can be activated via `pytest` command-line options, eg: `pytest --uc`, or by passing `uc=True` as an arg for the [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that are called directly with `python`.

### Here are some existing examples that use ``--uc`` mode:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py

### Here's a raw driver example:

```python
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(6)
driver.quit()
```

--------

While using **UC Mode**, a SeleniumBase script can browse websites appearing as human:

<img width="568" alt="Undetected SeleniumBase" src="https://user-images.githubusercontent.com/6788579/213031519-0220d19f-e210-4858-b6b5-9253b112efe4.png">

**Comment by NCLnclNCL** [comment]
> SeleniumBase **UC Mode** is used for bypassing bot-detection services. It's not the default mode, but it can be activated via `pytest` command-line options, eg: `pytest --uc`, or by passing `uc=True` as an arg for the [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that are called directly with `python`.
> 
> ### Here are some existing examples that use `--uc` mode:
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py
> 
> ### Here's a raw driver example:
> ```python
> from seleniumbase import Driver
> import time
> 
> driver = Driver(uc=True)
> driver.get("https://nowsecure.nl/#relax")
> time.sleep(6)
> driver.quit()
> ```
> 
> While using **UC Mode**, a SeleniumBase script can browse websites appearing as human:
> 
> <img alt="Undetected SeleniumBase" width="568" src="https://user-images.githubusercontent.com/6788579/213031519-0220d19f-e210-4858-b6b5-9253b112efe4.png">

But uc use connect and disconnect, right??

**Comment by mdmintz** [comment]
### Key things that Selenium frameworks need to do in order to avoid getting detected:

* Modify chromedriver to rename chromedriver-specific variables that appear in the Chrome DevTools console.
* Launch Chrome before attaching chromedriver to it. (Don't use chromedriver to launch Chrome directly.)
* Don't use Chrome options that are specific to Selenium (or ones that are generally only used with Selenium).
* Disconnect chromedriver temporarily from Chrome before loading websites that try to detect chromedriver.

#### (SeleniumBase UC Mode uses all these things.)
