### ISSUE TITLE
CF dont passed in this url : https://nowsecure.nl/#relax and http://fenom.com

### ISSUE THREAD

**Issue by reactiver001** [seleniumbase/SeleniumBase#2027]
Hello 
I test all example but dont work , only work if click manual in captcha , 

Example : 

from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
page_source = driver.page_source

# Print the page source
print(page_source)
time.sleep(6)
driver.quit()

Its possible automatic and dont click manual  ?
Thanks

**Comment by mdmintz** [comment]
This worked for me:

```python
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(3)
page_source = driver.page_source
print(page_source)
driver.quit()
```

Perhaps you didn't wait long enough before getting the page source. Any type of driver command, (such as `driver.page_source`), can be detected.

**Comment by reactiver001** [comment]
Hello , i try now and dont work , have this : 

If try manual work good. thanks 

<html lang="en-US" class="lang-en"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><script src="/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=7fbf9744fb3506d2"></script><script src="https://challenges.cloudflare.com/turnstile/v0/g/313d8a27/api.js?onload=URXdVe4&amp;render=explicit" async="" defer="" crossorigin="anonymous"></script></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><h1 class="zone-name-title h1">nowsecure.nl</h1><h2 id="challenge-running" class="h2">Checking if the site connection is secure</h2><div id="challenge-stage" style="display: block;"><div id="turnstile-wrapper" class="captcha-prompt spacer"><div><iframe src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/if/ov2/av0/rcv0/0/n8g5j/0x4AAAAAAADnPIDROrmt1Wwj/light/normal" allow="cross-origin-isolated; fullscreen" sandbox="allow-same-origin allow-scripts allow-popups" id="cf-chl-widget-n8g5j" tabindex="0" title="Widget containing a Cloudflare security challenge" style="border: none; overflow: hidden; width: 300px; height: 65px;"></iframe><input type="hidden" name="cf-turnstile-response" id="cf-chl-widget-n8g5j_response"></div></div></div><div id="challenge-spinner" class="spacer loading-spinner" style="display: none; visibility: hidden;"><div class="lds-ring"><div></div><div></div><div></div><div></div></div></div><div id="challenge-body-text" class="core-msg spacer">nowsecure.nl needs to review the security of your connection before proceeding.</div><div id="challenge-success" style="display: none;"><div class="h2"><span class="icon-wrapper"><img class="heading-icon" alt="Success icon" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAMAAADypuvZAAAANlBMVEUAAAAxMTEwMDAxMTExMTEwMDAwMDAwMDAxMTExMTExMTEwMDAwMDAxMTExMTEwMDAwMDAxMTHB9N+uAAAAEXRSTlMA3zDvfyBAEJC/n3BQz69gX7VMkcMAAAGySURBVEjHnZZbFoMgDEQJiDzVuv/NtgbtFGuQ4/zUKpeMIQbUhXSKE5l1XSn4pFWHRm/WShT1HRLWC01LGxFEVkCc30eYkLJ1Sjk9pvkw690VY6k8DWP9OM9yMG0Koi+mi8XA36NXmW0UXra4eJ3iwHfrfXVlgL0NqqGBHdqfeQhMmyJ48WDuKP81h3+SMPeRKkJcSXiLUK4XTHCjESOnz1VUXQoc6lgi2x4cI5aTQ201Mt8wHysI5fc05M5c81uZEtHcMKhxZ7iYEty1GfhLvGKpm+EYkdGxm1F5axmcB93DoORIbXfdN7f+hlFuyxtDP+sxtBnF43cIYwaZAWRgzxIoiXEMESoPlMhwLRDXeK772CAzXEdBRV7cmnoVBp0OSlyGidEzJTFq5hhcsA5388oSGM6b5p+qjpZrBlMS9xj4AwXmz108ukU1IomM3ceiW0CDwHCqp1NjAqXlFrbga+xuloQJ+tuyfbIBPNpqnmxqT7dPaOnZqBfhSBCteJAxWj58zLk2xgg+SPGYM6dRO6WczSnIxxwEExRaO+UyCUhbOp7CGQ+kxSUfNtLQFC+Po29vvy7jj4y0yAAAAABJRU5ErkJggg=="></span>Connection is secure</div><div class="core-msg spacer">Proceeding...</div></div><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'nowsecure.nl',cType: 'managed',cNounce: '2722',cRay: '7fbf9744fb3506d2',cHash: '4e8b0878597ffbc',cUPMDTk: "\/?__cf_chl_tk=I4Zl.ovt6NXEBKRSrdaXb.iG_21dPnme0QZdoYKgyGQ-1692922005-0-gaNycGzNC5A",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "",fa: "/?__cf_chl_f_tk=I4Zl.ovt6NXEBKRSrdaXb.iG_21dPnme0QZdoYKgyGQ-1692922005-0-gaNycGzNC5A",md: "9UGk4tUbGOIVhkweYTFVbvyApmEnbLhYvS_lHJN3Tt0-1692922005-0-AZcMtOZ41v0HX086fwLq5RQCgX33uyop6cdrUKPQ1HzzJ84WebrCwlAgDdongV_Nn6q2lAd--YzKn1SHnNY3yaUhjKVzk4dyuKT4SUG08uib4BTiao8gh5cHxoP4_BSP9S3nkzfR1kveNf2_dje0pi11HLqtg-iIb_vsPcTXq72swMFq9HGWhZmPH7FDmr94qA1HR2DYptsF3931GCaeZbPRAABoll7AX3pOYyZluO1pYFH5NlrWIHlDMGZmxnySxEIDAsk7kOVyEMJ8ll0trZGX8AQVJqhILj0mk8zhrJwiF_hT1i7-v7ReXgDzbeE4JwLSOokKR55I9FP5xzBTSws3SUM-z0Qsvr261C2mhgKcktX85M0YJRkpRqBbN2Chs3Zif5ooULqhgNTK7Zb11HJvzgtE8iy02rsetb2YOJNrn_dM8FbIoMm0KDByecRmb3Wi061r6QkUkxYNrJ9HOH34tiGIVH6bGPbO25g87A382Syu7XDciXYJjAW5CUKM0HLzvFft_W-hDeHGVEOpg99ZeLRTJQ5bxkbr3q1y2fKjrXUAX10KJXJrnBTnJxu3KRVIQuSXHSt6XqerY8Q2P8J3am5-ulULVhLWLHV0smTdENVwJh_wmc3HwamyykO6y2YRspbYkPz3C_tT2_ZVwPcK8yQuu3DFaiLopgd9eHPQ_-tcFhF_X05xS5Ms0-HoP8erzRdlI-Xirztp73A4RcXhRCNtxNubKNtSDt2mvySjTcLBJ8ieJOpbLXRjtdxhqJjJOWT3mGiTtCwFSA1qss5KuEbxac9LLEN3dE7qEZ2rrnGE9G-qizR5xYdkvrvSs4jUVQm-Ng3moRjyq9eAM8gOEiszNi7Ukqcobd4Kl3QmhFyV81vpuOyLdUDyAvtT8Y5Zb304NZJhsl0g0Dclc9dQfOi4p0H8pwCWZPZsLwhTrI17eEiBzkwfLEywQBPEwPKnEwdu4ucPXjrvOBYzSp6szxnG6ZGlufH7T4TGjUmy2T763GMrtBY0ZF6lHktqQOwKpsXpkIaj8WUsDcJa61xcwBpnGSTyVFxkkfa6kDl7c6wy8eDXIFwBny2zcHAzIUapvwQvkNVoFoxu6_bvBh9dsxzUaBayvGLUiwfqPbHgGrrAPpttDjBAcx_i4azQc70jrED3-rKctCszSYIIh4cmByqzkzXCIY5az9cZ2p8dDwRWH1X8bAyZ3GlMq-G_TSoQ4asYQbk75ZEwGTwQ6Hn55um9Fqj9em1PVERS_8aQ2-5nxqPWpJ7Jh6zkifi65ImP6Y7bzRrwOxMLYYBDSmkf2Mep-LsTL9bSlS7lMn7QYv82S7l_vIhq-eS_mP3ku-9qVx8RYvQPuYAwYpokflP8mCFPyJYVptyrL-dHuQavnZVDlmXUaI5S1Ry1z-vceuWxnuZGa_oLNDZkdjKsYKJ4YJTAekVuv3a5sBq9RSJslTHWbdzDSmSy-jqGfy5oF-2MsXN5Na_VENhIRyRYEVmQLWdx1H_CJVspZKnl-_-SnRZiq_TxbuDp_3H7-78rrefPKNxgk1P_9IJjRT6tH70_Kt5KoEEvug_VxHeSFowKbH8zY8MfjuRk-sD-mO5odKW0-PA_KenEPB8VkBfnghwRXdQWJMq_4NmP8zDE4chqoyhwh8CMRqblMhJWLvoUb17jLS7UU_cwn9fwe8ih5UYQWw9j6gk5_teedvz8SVx_uQAXezWXN8uFhUTfWVBxVnMfz0TQC1aC7SPRQBXZtzFKwjK_FFVspwsXY6xTwCrOqtY64AG6tb1hn0yiswWM34LfEto5duIMfAHjTnFtYwSDv1SDyPrMeZ-agskX--cwDQMmQfZOBkxM6eRWPKLjLlFy1IPB0GtEMZIXp0cX-PIkC3M5AdCkPlBDL0s4w1XncxdH7VatqpPek2BcjYp6tMfhHwj-lCme-TkcS16Uapm70ygCMbcP5aLlJkYYsf3AVso2DQSS2dLSQEECUwXeh4ct4tbXE_iSTcFvraCelFQxHShvIjIoZbqfCrjVCF6cs-36uYyJ0YCKkr5eEWAXK1xEtODPhrcIdOW1i0BECQyvIz_4hKSyIqljl-mPysmr6MgEGe78HLGqesdx01L46SMj6YvwQToHSTpI-1w4aICN0Cz17HN5pzQxIC0ItURfDYTDeWby1JwiR8-lKH1zN6YtOSsB0qPQzEYbLGa99EgulZ61qBUTunMnlSSB1yDE_IFWVK0EeMhzApWLYMzriAhDFKXKFqyzegt0EIbnrmEHdX5a_s0dzAQyUg6NwBZkKLx3XHMXisUXFhMorStyHdGwfONPI3CeGF-0SpdkgE-EGyjmSDfHv2ekJIhOffzcgbl_Kp0QnrSANCCUX1YKIfYUKq381yH6jobgFrHE1hPU1k0ql0o0fDDNwcqJbiWJG2maRM46fKYiZEhD2jZTo0sV6l0p4MU6vdsdWOQf8pxhWXRBURBschIhZ_KcPU5PShHLb7gPNuKMh47myGY5guPdj5fmIw4Lfj1wnnRua-zd5CLdVvGQRFzxWdcFwmABN9fTD7qWJxSYoJ2oOVeciR5P1R7r5h90fHTg2yF4HUx1uiyEAkXEgVByXWRTQl6ej6joaD7nhZkjziaeDGLiXN_Jt50x7yA-BBkqJtZH4NMvfAaPnYCCpx8aodrA05tIcRs-pYdYc0-IhrOvRjHJs8VSru3KOuhLZSBjBPxwZxGrNoPUam9_zglvqDdqYOJ1O_261VI1mOVXO0qOErNkX9IswYbKpC3AQOqArE81mXGOX9eLImaLcgfW89Ohf8WGK7LEH0p5Wj4F09e8OX0s1YvNAaWUKpqCBixNO99xsT6hft1fAaHx2x8u698-7wl2khxsK6YnRmvskqCmIWtcNepT7G6XC4p9kxVKg1L29YY",cRq: {ru: 'aHR0cHM6Ly9ub3dzZWN1cmUubmwv',ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzExNi4wLjAuMCBTYWZhcmkvNTM3LjM2',rm: 'R0VU',d: 'oVBqoPSpIQbq5+D+JAEmnTtEeZ5bIgnoFPxled7xGAdwE/iZNpebGJ7nj6Z0NiGKLx8ZB4N4fs0BaUAiaWh4nu1klz4IYZpBNum7pscsQ4AMbEramUiGYgfgMoo81lzehW7cyYLSLDAlyjdcWeIPtbUZPIGHBUNzD5aA1JA5vUi3EyofNaoCPavvcsfMj4l+X9/u5+in09IIeK4FjZTMnJuPQD6JcOuJvGDVzQ6MmeGvy0Sc0xXFrlYdj4Fh124wrxwRN65+Pvj4zc4DBnU4kOwgpGOO8OD4wx+vn0UBD9TjWrLII5oHph5VzjLIwT2emuGYLew2WB+d+whlh/ElZGGbSseHCH/QOM+8HY2howHxjtpCkWnDwMCHaSGRxBNEOsJ9Q3fm4q9aYl0VBaOlMQCq7SVuus31of4DJvTgP14OJ//2VwrR4T7o8rt7P4yjhHPBr+yGMAu4kIiw6nIvbQ==',t: 'MTY5MjkyMjAwNS4yNzcwMDA=',cT: Math.floor(Date.now() / 1000),m: 'C7hKybaxS6Fu1IINChj3SjMoJc31N+oi++KEZvDB5Gc=',i1: 'IidpuhSEaVXaJXEUyIlneA==',i2: 'a3bZ+QF4cH9SLTd6q9Y+2Q==',zh: '9o6sDYLEg3t9KrPhDrxQpLX3EFuiRPt8/vBjYeXXjhM=',uh: '9mPvDFNZ0y8VGO4IML6ngXc1m8uVnDSvugn0Dixn1yo=',hh: 'ZWKc/9OeKWBypS27gOf1uCLya4SW2C0xp63VDfZjYWk=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=7fbf9744fb3506d2';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/?__cf_chl_rt_tk=I4Zl.ovt6NXEBKRSrdaXb.iG_21dPnme0QZdoYKgyGQ-1692922005-0-gaNycGzNC5A" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);};}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script><div class="footer" role="contentinfo"><div class="footer-inner"><div class="clearfix diagnostic-wrapper"><div class="ray-id">Ray ID: <code>7fbf9744fb3506d2</code></div></div><div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&amp;utm_campaign=m" target="_blank">Cloudflare</a></div></div></div></body></html>
