### ISSUE TITLE
pyinstaller is undetected and won't run extensions

### ISSUE THREAD

**Issue by Romhast** [seleniumbase/SeleniumBase#2028]
Before compiling my codes, I can use all its features without any problems. But after compiling it opens like normal Selenium browser and extensions don't work. I think the problem is in pyinstaller, do I also need to add something?

`pyinstaller --onefile main.py  -i "NONE"`

**an image from the browser before compiling**
![image](https://github.com/seleniumbase/SeleniumBase/assets/109461554/90ca63d1-cfb3-42e2-9855-e4fd168b5218)

**after compiling bot check comes**
![image](https://github.com/seleniumbase/SeleniumBase/assets/109461554/e6faf3bb-f2d6-41d0-b2d2-41fe4b297e6c)

**Comment by mdmintz** [comment]
For compatibility with **UC Mode**, you need to convert your ``.crx`` files into ``.zip`` files, and then unzip the files to folders. Then use ``extension_dir=DIR`` as an option. UC Mode uses `undetected-chromedriver`, which doesn't support zipped/CRX extensions.

The following worked for me after unzipping ``ad_block.zip`` and ``disable_csp.zip`` from https://github.com/seleniumbase/SeleniumBase/tree/master/seleniumbase/extensions, putting those folders into a ``temp`` folder, and then running a script:

```python
from seleniumbase import Driver

driver = Driver(uc=True, extension_dir="temp/disable_csp,temp/ad_block")
try:
    driver.get("https://nowsecure.nl/#relax")
    import pdb; pdb.set_trace()
finally:
    driver.quit()
```

<img width="1230" alt="Screenshot 2023-03-22 at 3 12 17 PM" src="https://user-images.githubusercontent.com/6788579/227012280-0a00ca1e-04c6-4234-b777-cc7079ba79c4.png">

--------

For issues specific to `pyinstaller`, see https://github.com/pyinstaller/pyinstaller, as that is a separate repo.

**Comment by Romhast** [comment]
> For compatibility with **UC Mode**, you need to convert your `.crx` files into `.zip` files, and then unzip the files to folders. Then use `extension_dir=DIR` as an option. UC Mode uses `undetected-chromedriver`, which doesn't support zipped/CRX extensions.
> 
> The following worked for me after unzipping `ad_block.zip` and `disable_csp.zip` from https://github.com/seleniumbase/SeleniumBase/tree/master/seleniumbase/extensions, putting those folders into a `temp` folder, and then running a script:
> 
> ```python
> from seleniumbase import Driver
> 
> driver = Driver(uc=True, extension_dir="temp/disable_csp,temp/ad_block")
> try:
>     driver.get("https://nowsecure.nl/#relax")
>     import pdb; pdb.set_trace()
> finally:
>     driver.quit()
> ```
> 
> <img alt="Screenshot 2023-03-22 at 3 12 17 PM" width="1230" src="https://user-images.githubusercontent.com/6788579/227012280-0a00ca1e-04c6-4234-b777-cc7079ba79c4.png">
> 
> For issues specific to `pyinstaller`, see https://github.com/pyinstaller/pyinstaller, as that is a separate repo.

i found the source of the problem **ad_block_on=True** this parameter causes a system corruption after compiling.
