### ISSUE TITLE
Everytime i run the code it downloads undetected_chrome driver

### ISSUE THREAD

**Issue by TurgutHarunArslan** [seleniumbase/SeleniumBase#2046]
![image](https://github.com/seleniumbase/SeleniumBase/assets/83730616/25cf0b97-1965-48af-8228-67f88d5e86f0)
And when it downloads it downloads to somewhere in tempfiles not /drivers inside seleniumbase how can i fix this?

**Comment by TurgutHarunArslan** [comment]
Uh i forgot to write my seleniumbase driver folder is here
C:\Users\nazan_cqb5k5e\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\drivers

**Comment by mdmintz** [comment]
Are you installing seleniumbase to an autogenerated temp folder that is being recreated every time you run tests? How are you running tests? (With pytest?) How did you install seleniumbase?

The seleniumbase folder from your message is different from the one in your screenshot. The screenshot has ``..\AppData\Local\Temp\SOME_AUTOGENERATED_TEXT\seleniumbase\drivers\uc_driver.exe``

If the driver doesn't exist at that location, it should be getting downloaded. Is it downloading to the same location each time?

**Comment by TurgutHarunArslan** [comment]
B

> Are you installing seleniumbase to an autogenerated temp folder that is being recreated every time you run tests? How are you running tests? (With pytest?) How did you install seleniumbase?
> 
> The seleniumbase folder from your message is different from the one in your screenshot. The screenshot has `..\AppData\Local\Temp\SOME_AUTOGENERATED_TEXT\seleniumbase\drivers\uc_driver.exe`
> 
> If the driver doesn't exist at that location, it should be getting downloaded. Is it downloading to the same location each time?

No everytime i run in it finds a random number and downloads it there, im running the code as an exe generated from pyinstaller

**Comment by mdmintz** [comment]
`pyinstaller` is generating a new folder every time, so `seleniumbase` doesn't have control over that.

But what you can do is hide those install messages by using this:

```python
from seleniumbase.config import settings
settings.HIDE_DRIVER_DOWNLOADS = True
```

**Comment by TurgutHarunArslan** [comment]
> `pyinstaller` is generating a new folder every time, so `seleniumbase` doesn't have control over that.
> 
> But what you can do is hide those install messages by using this:
> 
> ```python
> from seleniumbase.config import settings
> settings.HIDE_DRIVER_DOWNLOADS = True
> ```

I see , thank you alot!

**Comment by taytanqbpass** [comment]
sorry to bump this, but is there a way for it to only download once and reuse that when opening the exe app again?

**Comment by mdmintz** [comment]
@taytanqbpass SeleniumBase doesn't have control over how `pyinstaller` works. But there are command-line options such as `--driver-version="keep"` / `driver_version="keep"` to keep using any driver that is found, even if the version of it doesn't match the browser version.

**Comment by taytanqbpass** [comment]
@mdmintz got it, but how are we supposed to release executables that use seleniumbase?

**Comment by mdmintz** [comment]
@taytanqbpass People that use `pyinstaller` with `seleniumbase` have found ways to do it, but perhaps they didn't share their findings after they figured it out. There are ways to configure `pyinstaller` to set a folder structure with existing files, such as the driver, but that falls outside the regular scope of SeleniumBase.
