### ISSUE TITLE
is there any method to modify WebGL?

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2048]
hello, is there any method to modify WebGL?

change WebGL renderer and vendor, and canvas, audio,..

a way to make new fingerprint..

Im using `SB`

**Comment by mdmintz** [comment]
If there was a way to modify WebGL or other Chrome internals, it would be through ``driver.execute_cdp_cmd()``.

Here's an example of using that to change the Geo Location: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_geolocation.py

```python
self.execute_cdp_cmd(
            "Browser.grantPermissions",
            {
                "origin": "https://www.openstreetmap.org/",
                "permissions": ["geolocation"],
            },
        )
        self.execute_cdp_cmd(
            "Emulation.setGeolocationOverride",
            {
                "latitude": 48.87645,
                "longitude": 2.26340,
                "accuracy": 100,
            },
        )
```

For more info on `driver.execute_cdp_cmd()`, you may have to search the web.

**Comment by YOTYTeaM** [comment]
thank you,
https://github.com/diprajpatra/selenium-stealth it works but made driver detectable
also i made extension to change it, it works but again made it detectable. 

js extension code:
```
function modifyWebGLParameters() {
  const getParameter = WebGLRenderingContext.prototype.getParameter;
  WebGLRenderingContext.prototype.getParameter = function(parameter) {
    if (parameter === 37445) {
      return "Google Inc.";
    }
    if (parameter === 37446) {
      return "ANGLE (Intel HD Graphics 620 Direct3D11 vs50 ps50) ";
    }
    return getParameter.apply(this, arguments);
  };
}

function injectScript(fn) {
  const script = document.createElement('script');
  script.text = `(${fn.toString()})();`;
  document.documentElement.appendChild(script);
  script.parentNode.removeChild(script);
}

injectScript(modifyWebGLParameters);
```

https://pixelscan.net/ says that you are masking your fingerprint
