### ISSUE TITLE
Opening browser with SeleniumBase in remote debugging mode, possible?

### ISSUE THREAD

**Issue by iWeeDev** [seleniumbase/SeleniumBase#2049]
Hi there,

Is there any way of opening Chrome in remote debugging mode using SeleniumBase?

In Chrome browser I use this command in the console and then I can connect through the port 9222. 

`start "Chrome" "C:\Program Files\Google\Chrome\Application\chrome.exe" -remote-debugging-port=9222 -user-data-dir=C:\chromeData`

My aim is once the browser is open by SeleniumBase, I would like to give access to other modules or scripts.

Regards,

**Comment by mdmintz** [comment]
Hi @iWeeDev There's a pytest command-line option for it: ``--remote-debug``

```bash
pytest --remote-debug
```

It's in the ReadMe:

https://github.com/seleniumbase/SeleniumBase/blob/f2b9448686c4c821226dd51c1c35d4584237f2b7/README.md?plain=1#L656

If using one of the pure Python syntax formats, use: ``remote_debug=True``.

**Comment by iWeeDev** [comment]
Thanks for the quick answer!

Do I need to add a port in order to access other modules through it?

**Comment by mdmintz** [comment]
Port `9222` is the default. You'll see it here: ``chrome://inspect/#devices``
Not sure if there's anything else you need to do. It should just work.

**Comment by ahmedabdelhamedz** [comment]
> Hi @iWeeDev There's a pytest command-line option for it: `--remote-debug`
> 
> ```shell
> pytest --remote-debug
> ```
> 
> It's in the ReadMe:
> 
> https://github.com/seleniumbase/SeleniumBase/blob/f2b9448686c4c821226dd51c1c35d4584237f2b7/README.md?plain=1#L656
> 
> If using one of the pure Python syntax formats, use: `remote_debug=True`:
> 
> ```python
> from seleniumbase import SB
> 
> with SB(remote_debug=True) as sb:
>     sb.open("data:text/html,<div>Hello<br><input></div>")
>     sb.type("input", "Goodbye")  # selector, text
>     sb.click("html body > div")  # selector
>     sb.assert_element("input")  # selector
>     sb.assert_text("Hello", "div")  # text, selector
>     sb.highlight("div")  # selector
>     sb.sleep(4)
> ```

i tried code but selenium based it is not connected to existing chrome browser can you send me code how can i connect selenium base by existing ip:port as we did it on selenium ?
