### ISSUE TITLE
Avoid closing the browser window after test execution completes

### ISSUE THREAD

**Issue by Davidd-u** [seleniumbase/SeleniumBase#2060]
Hello,

I am currently working on a project where users can send requests to a server via FastAPI. The server uses web scraping to retrieve data requested by the user in their request. The first time a user sends a request, the server logs into the specified website and performs its tasks.

The issue I'm encountering is related to using "**with SB() as sb.**" It creates a problem where, after exiting the "with" block, the program automatically closes. This behavior is problematic because, for a client to send another request, the server must log in again. This results in an unreasonably long delay, especially when multiple requests are needed in quick succession.

Is there a way to prevent the SeleniumBase browser window from closing automatically at the end of a test? It would greatly improve the efficiency of my project by eliminating the need to log in repeatedly.

Thank you for your assistance.

**Comment by mdmintz** [comment]
For tests that use one of the ``pytest`` syntax formats, you can reuse the browser session by adding ``--reuse-session`` or ``--rs`` to your pytest run command. That will keep the same session open for all tests. If you want to close the session between different classes of tests, use ``--reuse-class-session`` or ``--rcs``.

See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md for a description of all 23 syntax formats. If you can't use one of the ``pytest`` formats, there are other ways of keeping the browser open after tests.
