### ISSUE TITLE
How to use uc=True with mobile=True?

### ISSUE THREAD

**Issue by MacMarde** [seleniumbase/SeleniumBase#2062]
Is it possible to use mobile=True and still be undetectable?

I also need extensions, and user_data_dir and some chromium_arguments, resulting in:

`chrome_obj = Driver(uc=True, uc_subprocess=True, user_data_dir=user_data_dir, chromium_arg=chromium_arguments, extension_dir=loadExtensionString, mobile=True)`

Adding the last statement 'mobile=True' will not work. The browser even doesn't open at all. Any solution?

Is it maybe possible with pytest?

**Comment by mdmintz** [comment]
UC Mode doesn't support mobile emulation. (Don't mix ``--uc`` with ``--mobile``)

Mixing would lead to: ``invalid argument: unrecognized chrome option: mobileEmulation``.

If you try mixing the two with `pytest`, there's already a message that's displayed:
``SeleniumBase doesn't support mixing --uc with --mobile``.

**Comment by MacMarde** [comment]
@mdmintz 
Why is it not possible to use --uc with --mobile?
Any chance you can implement that feature?

**Comment by mdmintz** [comment]
Mobile Mode is fake by it's very nature: It uses a mobile emulator that's easily detectable. Regular UC Mode just needs to convince a website that a regular Chrome browser is being used, rather than one controlled by chromedriver.

**Comment by MacMarde** [comment]
@mdmintz 
That is true but there are solutions working so far.
For example Multilogin and GoLogin browsers.
Unfortunately these are not working when using Selenium to automate it.

So are you sure it is not possible or do you think it might be worth a try?

**Comment by mdmintz** [comment]
I think I finally figured out how to make Mobile Mode work with UC Mode...

<img width="1170" alt="Screenshot 2023-10-08 at 8 58 42 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/e3e33a42-c27c-403a-92bc-e7b7620eafbc">

I'll try to ship this update in the next release. I think you owe me a GitHub Star for this one...

New ticket for that: https://github.com/seleniumbase/SeleniumBase/issues/2169

**Comment by MacMarde** [comment]
> I think I finally figured out how to make Mobile Mode work with UC Mode...
> <img alt="Screenshot 2023-10-08 at 11 15 31 PM" width="1175" src="https://user-images.githubusercontent.com/6788579/273491979-4f82ab56-ca6a-45ab-a8a8-81ce9a4d7b88.png">
> 
> I'll try to ship this update in the next release. I think you owe me a GitHub Star for this one...
> 
> New ticket for that: #2169

You are genious. This is awesome.

Can't wait to try it.

As soon as you tell me how I can give you a Github star I will do it.

What about an extra donation of 50$ for you? Maybe it helps you to keep up the good work?

**Comment by mdmintz** [comment]
SeleniumBase is already well-funded / has paying customers. The framework doesn't need or take donations at this time.

Video of the upcoming UC Mode + Mobile Mode for a future release:

https://github.com/seleniumbase/SeleniumBase/assets/6788579/a97131a1-82ea-433f-b740-d6833aec9ba4

It'll be released when it's ready. There are some other priorities to attend to first.

**Comment by MacMarde** [comment]
ok thank you so much.

Will it also work in this way. I do not want to use pytest:

`chrome_obj = Driver(uc=True, uc_subprocess=True, user_data_dir=user_data_dir, chromium_arg=chromium_arguments, extension_dir=loadExtensionString, mobile=True)`

**Comment by mdmintz** [comment]
It will work that way, but mobile browsers don't use desktop Chrome extensions, so you might get detected if you try setting a custom extension while in mobile mode.

**Comment by MacMarde** [comment]
> It will work that way, but mobile browsers don't use desktop Chrome extensions, so you might get detected if you try setting a custom extension while in mobile mode.

Yes true. Anyway I am excited about it.

I think I have managed to nominate you now for a Github star.

**Comment by MacMarde** [comment]
@mdmintz 
Thank you so much. I will test it soon.

**Comment by MacMarde** [comment]
@mdmintz 
It seems to be messed up now. 
I am starting chrome this way:

`chrome_obj = Driver(uc=True, uc_subprocess=True, user_data_dir=user_data_dir, chromium_arg=chromium_arguments, extension_dir=loadExtensionString)`

I am not using mobile mode, but my first tab in chrome is a mobile version.

![SeleniumBase](https://github.com/seleniumbase/SeleniumBase/assets/50266741/08fa99f3-86d1-4d20-a34a-f32263f8c5a1)

**Comment by MacMarde** [comment]
Also true for:

`chrome_obj = Driver(uc=True)`

**Comment by mdmintz** [comment]
@MacMarde It is working for me... and you did promise a GitHub Star.

**Comment by MacMarde** [comment]
> @MacMarde It is working for me... and you did promise a GitHub Star.

Yeah I found a website where I could nominate you for a github star and I did.
I do not really know anything about github stars, that is why I asked you for assistence to give you a github star.
You did never answer me, so I started my own search with Google. Maybe it was not what you expected
So again I ask you for letting me know how I can give you a github star?

**Comment by MacMarde** [comment]
> As soon as you tell me how I can give you a Github star I will do it.

This was my question to you.

**Comment by mdmintz** [comment]
@MacMarde  A GitHub Star is what appears when clicking this button:

<img width="551" alt="Screenshot 2023-10-13 at 3 12 34 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/1a5c0fca-2ddc-4a53-969e-be837e74763c">

**Comment by MacMarde** [comment]
@mdmintz 
Ok thanks. I am sorry for the misunderstanding. 
Of course I gave you now a github star. I would have done much more for it, I just did not know what you mean.
:-)

Will you help me know again?

**Comment by mdmintz** [comment]
I'm about to ship a new release in the next hour. It will probably solve your remaining issues.

**Comment by MacMarde** [comment]
@mdmintz 
This is great. Looking forward to it.
