### ISSUE TITLE
get and save and load cookies by SeleniumBase

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2064]
how can i get browser cookies and save it then load to any chrome driver 

for save cookies 
cookies = driver.get_cookies()
pickle.dump(cookies, open("xmcookies.pkl", "wb"))

for load cookies
cookies = pickle.load(open("cookies.pkl", "rb"))

    for cookie in cookies:
        cookie['domain'] = ".google.com"
how can i do that with selenium base

**Comment by mdmintz** [comment]
SeleniumBase has special methods for cookies. These let you save and load cookies to/from files:

```python
self.save_cookies(name="cookies.txt")

self.load_cookies(name="cookies.txt")
```

For working with cookies, see https://www.selenium.dev/documentation/webdriver/interactions/cookies/

Here are the other SeleniumBase cookie methods:

```python
self.delete_all_cookies()
# Duplicates: self.clear_all_cookies()

self.delete_saved_cookies(name="cookies.txt")
```

**Comment by ahmedabdelhamedz** [comment]
> SeleniumBase has special methods for cookies. These let you save and load cookies to/from files:
> 
> ```python
> self.save_cookies(name="cookies.txt")
> 
> self.load_cookies(name="cookies.txt")
> ```
> 
> For working with cookies, see https://www.selenium.dev/documentation/webdriver/interactions/cookies/
> 
> Here are the other SeleniumBase cookie methods:
> 
> ```python
> self.delete_all_cookies()
> # Duplicates: self.clear_all_cookies()
> 
> self.delete_saved_cookies(name="cookies.txt")
> ```

i already tried it  but i must visit domain cookie to can be added how can i added any cookies without visit domain  ?

**Comment by mdmintz** [comment]
See https://stackoverflow.com/a/63220249/7058266 if you want to add cookies before reaching a domain.

**Comment by EnkhAmar** [comment]
Hello @mdmintz , How I save my cookies and load them in the below code? thanks in advance

```python3
from seleniumbase import SB, Driver

driver = Driver(uc=True, headed=True, user_data_dir="/user_data_dir")
cookies = driver.get_cookies()
```

**Comment by mdmintz** [comment]
Use the `SB()` format or a `BaseCase` format to access the methods listed in [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md)
