### ISSUE TITLE
pyinstaller: Chromedriver does not get saved to seleniumbase/drivers during production

### ISSUE THREAD

**Issue by iammarco11** [seleniumbase/SeleniumBase#2065]
Hi,

I have an exe which is made using pyinstaller has all the site-packages required including seleniumbase and sbase. When the exe runs the chromedriver gets installed to C://USERNAME/.cache/selenium instead of file location of exe which is in C://Program Files/project/*

But during testing it works fine with the output below. Is there anyway the exe could download chromedriver convert it to uc_driver and install it in the exe file location instead of .cache. Although I am not sure if it is actually designed that way.

```
*** chromedriver to download = 116.0.5845.96 (Latest Stable) 

Downloading chromedriver-win64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip ...        
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Unzip Complete!

The file [uc_driver.exe] was saved to:
C:\Users\aksha\projects\project\env\Lib\site-packages\seleniumbase\drivers\uc_driver.exe

Making [uc_driver.exe 116.0.5845.96] executable ...      
[uc_driver.exe 116.0.5845.96] is now ready for use!
```
Thanks in advance!

**Comment by mdmintz** [comment]
``pyinstaller`` in an external program with its own rules and bugs. If using it changes default SeleniumBase behavior, then there's little that I can do about it.

But what you can do is hide those install messages by using this:

```python
from seleniumbase.config import settings
settings.HIDE_DRIVER_DOWNLOADS = True
```
