### ISSUE TITLE
how to scroll down to specific element on webpage 

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2067]
hello please i want to know how can i scroll down to specific element on webpage 

i use a code in selenium 

```
m9 = driver.find_element('xpath','//a[contains(@href,"domain.com/index.php?page=item&id=487")]')
driver.execute_script("arguments[0].scrollIntoView();", m9)
```
how can i do that by seleniumbase please?

is seleniumbase can control on mouse to move mouse to specific element or not ?

thanks for your help

**Comment by mdmintz** [comment]
With the SeleniumBase APIs, you can use the following to scroll to an element:

```python
self.scroll_to(selector)
```

There's also a pure JS way:

```python
self.scroll_into_view(selector)
```

(Requires a syntax format that uses BaseCase or SB or sb.)

**Comment by ahmedabdelhamedz** [comment]
> With the SeleniumBase APIs, you can use the following to scroll to an element:
> 
> ```python
> self.scroll_to(selector)
> ```
> 
> There's also a pure JS way:
> 
> ```python
> self.scroll_into_view(selector)
> ```
> 
> (Requires a syntax format that uses BaseCase or SB or sb.)

i used this sb.scroll_into_view() to scroll into specific element but it scroll in one second  how can i make it scroll till element as a human behaviour slowly ?

**Comment by mdmintz** [comment]
You can use ``self.slow_scroll_to(selector)`` to slow to an element slowly.

See [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) for a list of all methods.

**Comment by ahmedabdelhamedz** [comment]
> self.slow_scroll_to(selector)

i already tried it but not suitable with me i mean more slowly as some one click on down arrow on keyboard one by one till go to selector

**Comment by mdmintz** [comment]
You can press arrow keys if you need to:

``self.press_down_arrow(selector="html", times=4)``
