### ISSUE TITLE
How can i ignore certificate errors in seleniumbase 

### ISSUE THREAD

**Issue by Sytehel-1337** [seleniumbase/SeleniumBase#2068]
as i mentioned on head, how can i ignore certificate errors in seleniumbase. Im using webdriver 

heres my code

```
from seleniumbase import Driver
from seleniumbase.config import settings

settings.HIDE_DRIVER_DOWNLOADS = True
proxy = "localhost:8080"
driver = Driver(uc=True,guest_mode=True,proxy=f"http://{proxy}")
driver.maximize_window()
driver.get("https://www.whatismybrowser.com/detect/what-is-my-user-agent/")
```

**Comment by mdmintz** [comment]
``--ignore-certificate-errors`` is already set by default when changing proxy settings.

You can see the warning message that pops up:

<img width="697" alt="Screenshot 2023-09-06 at 1 29 52 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/9a67bb22-d84d-4e2a-a1d1-d693f830fa68">

<br />However, if you try to use a selenium option to hide that message, then you'll get detected.

(Having that message there won't make you detectable.)
