### ISSUE TITLE
alert exception and quit driver

### ISSUE THREAD

**Issue by mahsa2017** [seleniumbase/SeleniumBase#2070]
Hi I have issue with testing a website which starts with an alert which user is supposed to click on Ok button
I get the error below: 
```
test_initial_popup - selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Componente...
  raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
E           selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Componente...
E           undefined
E           Message: unexpected alert open: {Alert text : Componente...
E           undefined}
E             (Session info: chrome=116.0.5845.179)
E           Stacktrace:
```

my test looks like below:
```
def test_initial_popup(self):
        try:
            self.wait_for_and_accept_alert(timeout=None)
        except UnexpectedAlertPresentException:
            pass
```
            
 I also have another question which is how can I ensure the driver gets closed after this test I added a teardown as below but its not working (maybe because my test is failing)

```
 def tearDown(self):
        super().tearDown()
        self.driver.quit() 
```
     

Thanks in advance

**Comment by mdmintz** [comment]
First, calling `super().tearDown()` from your custom `tearDown()` method will automatically quit the driver, so you shouldn't be trying to quit it there.

Second, here's better code for your alert block:

```python
try:
    self.wait_for_and_accept_alert()
except Exception:
    pass
```

If there's no alert, then the block with continue without throwing an exception. If there is an alert, `self.wait_for_and_accept_alert()` will close the alert.

**Comment by mahsa2017** [comment]
Thank you Mike, but I have tried with your code and still get the same error for the alert and still the driver is not closed
