### ISSUE TITLE
proxy_bypass_list not working when using an authenticated proxy

### ISSUE THREAD

**Issue by gouravkumar99** [seleniumbase/SeleniumBase#2073]
I am using your Seleniumbase Driver with proxy. But proxy_bypass_list is not working in that.

`proxy_d = f"{proxy_user}:{proxy_password}@{proxy_host}:{proxy_port}"
driver = Driver(uc=True,user_data_dir=user_data_dir, multi_proxy=True, proxy=proxy_d,proxy_bypass_list="*ipinfo.io")` 

Can you tell me whether i am using the correct method?

**Comment by mdmintz** [comment]
Looks like a new bug specific to authenticated proxies. Thanks for finding this. If using a non-authenticated proxy, then using `proxy_bypass_list="*ipinfo.io*"` with a `*` on both ends works (https://github.com/seleniumbase/SeleniumBase/issues/1684#issuecomment-1385564771), but not currently for an authenticated one. I'll have a fix in the next release.

**Comment by gouravkumar99** [comment]
> Looks like a new bug specific to authenticated proxies. Thanks for finding this. If using a non-authenticated proxy, then using `proxy_bypass_list="*ipinfo.io*"` with a `*` on both ends works ([#1684 (comment)](https://github.com/seleniumbase/SeleniumBase/issues/1684#issuecomment-1385564771)), but not currently for an authenticated one. I'll have a fix in the next release.

**Comment by mdmintz** [comment]
This was resolved in `4.18.2` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.18.2
