### ISSUE TITLE
about iframe elements

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2074]
hello please i made the same code in seleniumbase work perfectly but when write same code with selenium it didnt click on link can i know the reason for that 

`with SB(uc=True) as sb:
    sb.maximize_window()
    sb.open("https://www.prceg.com/search/label/%D8%AF%D9%8A%D8%AC%D8%AA%D9%8A%D8%A7%D9%84%20%D9%85%D8%A7%D8%B1%D9%83%D8%AA%D9%8A%D9%86%D8%AC")
    try:
         m = sb.switch_to_frame('aswift_1')
         print('switched')
    except:
        print('no switch')
    try:
        sb.click('//a[contains(@href,".g.doubleclick.net")]',timeout=60)
        print('clicked')
    except:
        print(' no click')`

**Comment by mdmintz** [comment]
SeleniumBase is not the same as raw Selenium. SeleniumBase does use several raw Selenium APIs, but it also has its own APIs. What may work in SeleniumBase might not work in Selenium. If you have an issue with raw Selenium, (but not SeleniumBase), then this isn't the place to ask.
