### ISSUE TITLE
google gmail login detect it in remote debug 

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2075]
`from seleniumbase import SB

with SB(remote_debug=True,chromium_arg="127.0.0.1:9222") as sb:
    sb.maximize_window()
    sb.open("https://accounts.google.com/")
    sb.type("//input[@name='identifier']", "email@gmail.com")
    sb.click("//div[@id='identifierNext']")
    sb.type('input[type="password"]', "password")
    sb.click('button:contains("Next")')
    input()`

hello please why when i use SeleniumBase as uc=True it can login to my gmail account eaisly but when i use remote_debug it appear to me gmail error in the below can i know how to solve this problem on remote debug 

Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by mdmintz** [comment]
If using certain options such as ``remote_debug=True`` breaks UC Mode, then don't use those options with UC Mode. :)
