### ISSUE TITLE
can i change on browser fingerprint with selenium base 

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2077]
please can i change on browser fingerprint 

Fonts ,Canvas, WebGL Image , WebGL metadata , AudioContext , Media device , ClientRects , SpeechVoices , Hardware concurrency , Device memory , MAC Address , Device name , Do Not Track , Flash , Port scan protection , Hardware acceleration

can i change them by SeleniumBase as multilogin and adspower or i should to use java language ?

**Comment by mdmintz** [comment]
There's UC Mode (`--uc` / `uc=True`), which lets you load a website with pure Chrome before chromedriver connects to it. This gives your browser a temporary appearance that you're not using chromedriver at all. But once chromedriver is connected to it, then your browser's fingerprint (signature) may change to reflect that it's being controlled by automation.

**Comment by ahmedabdelhamedz** [comment]
> There's UC Mode (`--uc` / `uc=True`), which lets you load a website with pure Chrome before chromedriver connects to it. This gives your browser a temporary appearance that you're not using chromedriver at all. But once chromedriver is connected to it, then your browser's fingerprint (signature) may change to reflect that it's being controlled by automation.

https://github.com/diprajpatra/selenium-stealth
can i use this package with Seleniumbase to can change browser fingerprint ?

**Comment by nemesis7331** [comment]
sorry for replying in a closed issue, but I think I may have a solution to the fingerprint issue that works from the start: you can load a custom extension to change those value, bypassing the connection problem, ex. https://mybrowseraddon.com/audiocontext-defender.html
