### ISSUE TITLE
how can i use SeleniumBase with firefox driver

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2078]
how can i use SeleniumBase with firefox driver?

**Comment by mdmintz** [comment]
To run scripts with Firefox, add ``--firefox`` on the command-line as a pytest arg, or add ``browser="firefox"`` with the direct Python syntax formats.

**Comment by ahmedabdelhamedz** [comment]
> To run scripts with Firefox, add `--firefox` on the command-line as a pytest arg, or add `browser="firefox"` with the direct Python syntax formats.

i tried it but appear to me this message  how can i solve it please 

uc is work only for chrome or can work also for safari , firefox,edge?

**Comment by mdmintz** [comment]
UC Mode is only for Chrome right now.

**Comment by PankajSavaliya** [comment]
@mdmintz Is Support added for Firefox for UC mode?
