### ISSUE TITLE
how to close previous driver when use that self.get_new_driver()

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2082]
how can i close first driver when i use a code self.get_new_driver() with Seleniumbase SB

**Comment by mdmintz** [comment]
Drivers will be closed automatically at the end of tests. But if you need to quit the first driver early, you can do `self._default_driver.quit()`, or save drivers with `driver = self.driver` before calling `driver2 = self.get_new_driver()`, which resets `self.driver` to be the new driver.
