### ISSUE TITLE
How to click the Tab key with SeleniumBase?

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2086]
How to click the Tab key with SeleniumBase?

**Comment by mdmintz** [comment]
Use ``\t`` with ``self.send_keys(selector, text)`` or ``self.type(selector, text)`` to click the tab key.

See the example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_cycle_elements.py
