### ISSUE TITLE
how can i add bookmark to chrome with SeleniumBase

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [seleniumbase/SeleniumBase#2088]
how can i add bookmark to chrome with SeleniumBase?

**Comment by mdmintz** [comment]
You would need to use the external Chrome bookmarks API: https://developer.chrome.com/docs/extensions/reference/bookmarks/

SeleniumBase / Selenium lets you interact with web pages, but bookmarks exist outside of web pages (and directly part of the browser itself).
