### ISSUE TITLE
Proxy with auth not working on latest version

### ISSUE THREAD

**Issue by gouravkumar99** [seleniumbase/SeleniumBase#2093]
![image](https://github.com/seleniumbase/SeleniumBase/assets/88101323/8b64c180-d6a7-498b-866f-8a2c2dbd7f18)
after updated lates version proxy not working showing popup requires username and passoword

`proxy_d = f"{proxy_user}:{proxy_password}@{proxy_host}:{proxy_port}"
driver = Driver(uc=True,user_data_dir=user_data_dir, multi_proxy=True, proxy=proxy_d)`

**Comment by mdmintz** [comment]
This was resolved in `4.18.5` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.18.5
