### ISSUE TITLE
Options with undetected driver

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#2098]
Hi,
How to add options chrome in undetected driver?
I dont see any example
Thanks

**Comment by mdmintz** [comment]
There's a description of pytest command-line options here: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/customizing_test_runs.md

You can see the args for the `SB()` manager here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/sb_manager.py

You can see the args for the `Driver()` and `DriverContext()` managers here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/driver_manager.py

Some options aren't supported by UC Mode.

**Comment by FranciscoPalomares** [comment]
from selenium.webdriver.chrome.options import Options ?
What is the example?

**Comment by mdmintz** [comment]
Using the `Options` object directly is only supported with these Syntax Formats:
* https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_09
* https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_10

When using these formats, the browser management is fully under your responsibility. That means you get access to SeleniumBase methods, but you have to create your own browser launcher and undetected mode.
