### ISSUE TITLE
Using uc option with proxy in multiprocessing repeats same ip

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#2101]
![image](https://github.com/seleniumbase/SeleniumBase/assets/39648210/0df98f15-82d4-4e73-b1d3-384c5a2c692f)

Hi, using this code in multiprocessing and different proxy, repeats ip:
driver = Driver(uc=True, proxy=proxy_dict['http'], headless=headless, uc_cdp_events=api,incognito=True) 

Thanks

**Comment by punkerpunker** [comment]
This does seem to still be an issue, I can take a look into if you haven't started yourself yet @mdmintz, thanks!

**Comment by mdmintz** [comment]
You have to enable that option for multiple proxies. See the documentation: https://github.com/seleniumbase/SeleniumBase/issues/1832

* ``--multi-proxy`` (Command-line option for ``pytest``)
* ``multi_proxy=True`` (``SB`` manager, ``Driver`` manager, ``DriverContext`` manager)

**Comment by punkerpunker** [comment]
@mdmintz Is this something needed to be enabled even when I use single authenticated proxy single-threaded? Thanks!

**Comment by mdmintz** [comment]
@punkerpunker If using a single proxy (either single-threaded or multi-threaded), you won't need the option.

Using `--multi-proxy` / `multi_proxy=True` will create a custom proxy config for every test that uses a proxy.

**Comment by punkerpunker** [comment]
Thanks @mdmintz!

What I am trying to communicate, is that after the upgrade to version 117, extension that's wrapping a user authenticated proxy doesn't work in headless2 mode.

**Comment by mdmintz** [comment]
@punkerpunker Are you using SeleniumBase `4.18.6`? https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.18.6
Chrome 117 made changes to headless mode, and SeleniumBase was already patched for it.

**Comment by punkerpunker** [comment]
> 
@punkerpunker Are you using SeleniumBase 4.18.6? https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.18.6
Chrome 117 made changes to headless mode, and SeleniumBase was already patched for it.

I just double checked it - yes, that's the case with the latest version of seleniumbase

**Comment by mdmintz** [comment]
@punkerpunker Can you be more specific on your issue? You mentioned several topics, but that you only had one issue.

Which of these most-closely resembles the issue you're experiencing?
1. Proxy settings aren't being applied at all.
2. Only one proxy is being used for all tests.
3. An error message appears somewhere.
4. Multi-threading isn't working.
5. UC Mode is getting detected in headless mode.

If it's the last one, (5), check your user-agent, and see if `HeadlessChrome` is there. You can change your user-agent with an arg: `agent`.

**Comment by mdmintz** [comment]
I found the issue, it's most-certainly number 5. The workaround right now is to specify the `agent` if using an authenticated proxy in headless mode. I'll probably create another ticket for this.

**Comment by mdmintz** [comment]
I opened another ticket for it: https://github.com/seleniumbase/SeleniumBase/issues/2114
(It's off-topic from this original ticket.)

**Comment by mdmintz** [comment]
@punkerpunker - resolved in ``4.18.7`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.18.7
