### ISSUE TITLE
Chrome v117 Headless is Detected in UC Mode

### ISSUE THREAD

**Issue by jdholtz** [seleniumbase/SeleniumBase#2106]
This relates to https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1559. I'm attempting to log in to https://mobile.southwest.com in headless mode. While it works in Chrome 116 flawlessly, it isn't working in Chrome 117 (it works in headed mode though). I'm not sure what changed in Chrome 117, but something must be very different because many people are reporting this same issue on UC.

**Comment by mdmintz** [comment]
Something *has* changed. If my calculations are correct, I'll have a new release with the fix ready in less than 3 hours.

**Comment by jdholtz** [comment]
Awesome! Let me know if you need me to test at all

**Comment by mdmintz** [comment]
This was resolved in `4.18.6` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.18.6

### Here are some existing examples that use ``--uc`` mode:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py

Let me know if any of those have issues after upgrading to `seleniumbase` `4.18.6`.

**Comment by jdholtz** [comment]
4.18.6 works. Thank you very much for the quick fix!

Looking at the code, was the user agent giving headless mode away? Was the fix just to remove the headless part from the user agent?

**Comment by mdmintz** [comment]
That was it. Change `HeadlessChrome` to `Chrome` in the user-agent, and things work.

For the record, the "in less than 3 hours" time estimate was accurate:

<img width="864" alt="Screenshot 2023-09-13 at 5 25 52 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/d450d902-18ca-4b58-b2b0-20da0cdbeb58">

<img width="255" alt="Screenshot 2023-09-13 at 5 23 50 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/c7fa2f90-af47-4b68-a1c0-3fe65ffd81db">

**Comment by jdholtz** [comment]
Wow. Do you accept any donations for your work on SeleniumBase?

**Comment by mdmintz** [comment]
> Wow. Do you accept any donations for your work on SeleniumBase?

Just tell people to Star the repo on GitHub, and that's enough reward. **⭐**
