### ISSUE TITLE
uc mode detected by captchaturnstile

### ISSUE THREAD

**Issue by mdonova33** [seleniumbase/SeleniumBase#2129]
Captcha turnstiles made a comeback, I'm not passing them with uc mode any longer.

Let me know how I can help, if theres any additional info anyone needs.

**Comment by mdmintz** [comment]
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py is still working for me:

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__, "--uc", "-s")


class UndetectedTest(BaseCase):
    def verify_success(self):
        self.assert_text("OH YEAH, you passed!", "h1", timeout=6.25)
        self.post_message("Selenium wasn't detected!", duration=2.8)
        self._print("\n Success! Website did not detect Selenium! ")

    def fail_me(self):
        self.fail('Selenium was detected! Try using: "pytest --uc"')

    def test_browser_is_undetected(self):
        if not (self.undetectable):
            self.get_new_driver(undetectable=True)
        self.driver.get("https://nowsecure.nl/#relax")
        try:
            self.verify_success()
        except Exception:
            self.clear_all_cookies()
            self.get_new_driver(undetectable=True)
            self.driver.get("https://nowsecure.nl/#relax")
            try:
                self.verify_success()
            except Exception:
                if self.is_element_visible('iframe[src*="challenge"]'):
                    with self.frame_switch('iframe[src*="challenge"]'):
                        self.click("area")
                else:
                    self.fail_me()
                try:
                    self.verify_success()
                except Exception:
                    self.fail_me()
```

**Comment by mdonova33** [comment]
> https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py is still working for me:
> 
> ```python
> from seleniumbase import BaseCase
> BaseCase.main(__name__, __file__, "--uc", "-s")
> 
> 
> class UndetectedTest(BaseCase):
>     def verify_success(self):
>         self.assert_text("OH YEAH, you passed!", "h1", timeout=6.25)
>         self.post_message("Selenium wasn't detected!", duration=2.8)
>         self._print("\n Success! Website did not detect Selenium! ")
> 
>     def fail_me(self):
>         self.fail('Selenium was detected! Try using: "pytest --uc"')
> 
>     def test_browser_is_undetected(self):
>         if not (self.undetectable):
>             self.get_new_driver(undetectable=True)
>         self.driver.get("https://nowsecure.nl/#relax")
>         try:
>             self.verify_success()
>         except Exception:
>             self.clear_all_cookies()
>             self.get_new_driver(undetectable=True)
>             self.driver.get("https://nowsecure.nl/#relax")
>             try:
>                 self.verify_success()
>             except Exception:
>                 if self.is_element_visible('iframe[src*="challenge"]'):
>                     with self.frame_switch('iframe[src*="challenge"]'):
>                         self.click("area")
>                 else:
>                     self.fail_me()
>                 try:
>                     self.verify_success()
>                 except Exception:
>                     self.fail_me()
> ```

works for me as well, but there's another website that doesn't pass

**Comment by mdmintz** [comment]
I would need URLs of those other sites to test.

**Comment by mdonova33** [comment]
Looks like it might be a problem with the actual undetected chromedriver, not the integration with seleniumbase On Sep 21, 2023, at 8:08 PM, Michael Mintz ***@***.***> wrote:﻿
I would need URLs of those other sites to test.

**Comment by mdmintz** [comment]
> Looks like it might be a problem with the actual undetected chromedriver, not the integration with seleniumbase

SeleniumBase UC Mode works differently from regular undetected-chromedriver.

Since it works fine with SeleniumBase, I'll close this ticket.
