### ISSUE TITLE
how to close Turn on an ad privacy feature popup

### ISSUE THREAD

**Issue by gouravkumar99** [seleniumbase/SeleniumBase#2141]
![image](https://github.com/seleniumbase/SeleniumBase/assets/88101323/f64b6b3b-7e3e-4789-ade9-ef5ca1197735)

I have showing Turn on an ad privacy feature popup, how to close this popup?

**Comment by mdmintz** [comment]
I'm not seeing this pop-up on the latest version of SeleniumBase with default settings. Tested on Mac / Windows. If you've upgraded to the latest and still see it, I'll need to know more info, such as OS, SeleniumBase settings used (if not using default settings), the run command used, and which of the [23 Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) that you used.
