### ISSUE TITLE
[QUESTION] How to pass parameters from pytest cli to inherited class ?

### ISSUE THREAD

**Issue by DRVR1** [seleniumbase/SeleniumBase#2144]
I need to pass parameters from pytest's command line interface, and those parameters to be taken by the TestClass(BaseCase). The issue comes when TestClass inherits BaseCase, it stops interpreting the mproxy parameter from pytest.

testing.py
```
import pytest
from seleniumbase import BaseCase

class TestClass(BaseCase):
    def test_something1(self,mproxy):
          self.get_new_driver(undetectable=True,proxy=mproxy)
```
conftest.py:
```
parameters = ['--mproxy']

def pytest_addoption(parser):
    for p in parameters:
        parser.addoption(p, action="store", default="default name")

def pytest_generate_tests(metafunc):
    option_value = metafunc.config.option.mproxy

    for p in parameters:
        if p[2:] in metafunc.fixturenames and option_value is not None:
            metafunc.parametrize(p[2:], [option_value])
```

Cli:
`pytest -s testing.py --mproxy user:pass@ip:port`

Currently working testing.py (conftest.py didn't change):
```
class TestClass:
    def test_something1(self,mproxy):
        print(mproxy)
```
Cli (same as before):
`pytest -s testing.py --mproxy user:pass@ip:port`

this works beacuse BaseCase is not inherited. How do i fix it?

**Comment by mdmintz** [comment]
`self.get_new_driver()` will reuse the same parameters that spun up the original browser if you don't specify any. Eg. If I called `pytest --edge`, then `self.get_new_driver()` will spin up another Edge browser. Same for `proxy` and any other parameter.

`def test_something1(self,mproxy):` is invalid. Unless you are using parameterization (Eg. https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py), you should not have any parameters other than `self` in your method definition.

You can also pass args into your tests with `--data=DATA`, `--var1=DATA`, `--var2=DATA`, and `--var3=DATA`. Then, inside your tests, you can access those values with: `self.data`, `self.var1`, `self.var2`, and `self.var3`.

Also, if you set a proxy via `pytest --proxy=USER:PASS@HOST:PORT`, then you can access the value of that in your test using: `self.proxy_string`.
