### ISSUE TITLE
`Driver(uc=True)` "cannot connect to chrome"

### ISSUE THREAD

**Issue by 2-X** [seleniumbase/SeleniumBase#2154]
the normal driver works fine but as soon as i add the `uc=` or `uc_cdp=` kwarg it fails to initialize.
i am using chrome version `117.0.5938.132` on WSL2.
anyone else experiencing this issue?

**Comment by mdmintz** [comment]
I'm running the following without issue:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
driver.quit()
```

I would need more info to debug, as I can't reproduce it. Add more code and a stack trace.
