### ISSUE TITLE
Using recorder in a website with cloudflare challenge does not work

### ISSUE THREAD

**Issue by steinpigs** [seleniumbase/SeleniumBase#2158]
`sbase mkrec recorder_cf.py --url=https://www.nowsecure.nl --undetected --gui`

The cloudflare checkbox can't be clicked. Instead it opens a new tab of cloudflare url "https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/if/ov2/av0/rcv0/0/gtfu5/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal"

**Comment by mdmintz** [comment]
To record on cloudflare-protected websites, you must active Recorder Mode **after** SeleniumBase has already bypassed the captcha screen. Here's an example that uses `self.activate_recorder()` to activate the Recorder after it is safe to do so:

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__, "--uc", "-s")

class RecordUndetectedTest(BaseCase):
    def test_record_undetected(self):
        if not (self.undetectable):
            self.get_new_driver(undetectable=True)
        self.driver.get("https://nowsecure.nl/#relax")
        if not self.is_text_visible("you passed", "h1"):
            self.driver.get("https://nowsecure.nl/#relax")
        self.activate_recorder()
        import pdb; pdb.set_trace()
```
