### ISSUE TITLE
seleniumbase 4.19.1 not support pytest-html 4.0.2?

### ISSUE THREAD

**Issue by tianlichunhong** [seleniumbase/SeleniumBase#2159]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seleniumbase 4.19.1 requires pytest-html==2.0.1, but you have pytest-html 4.0.2 which is incompatible.

I think pytest-html==2.0.1 is too old.

**Comment by mdmintz** [comment]
`pytest-html` `2.0.1` is still the best version. Every version after that has had at least one major bug that wasn't acceptable.

One of bugs of the current latest `pytest-html` `4.0.2` is inconsistent time units.

Compare the left image (`2.0.1`) with the right image (`4.0.2`):

<img width="585" alt="Screenshot 2023-09-01 at 4 19 03 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/47c8e3a0-4b6e-4d0c-bdeb-14ac50340b20">

Mixing time units in the newer version on the right is completely unacceptable. There are other issues too, such as misaligned images, unused whitespace in rows pushing back useful info, and counterintuitive sorting.

For these reasons, `pytest-html` `2.0.1` is still used, even though it's not the latest version. It's the only dependency that's being held back. The other dependencies currently support the latest version.

**Comment by tianlichunhong** [comment]
it makes sense. Thank you!
