### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'get_page_source'

### ISSUE THREAD

**Issue by maxi-am** [seleniumbase/SeleniumBase#2160]
Hi! Thanks for [SeleniumBase](https://github.com/seleniumbase/SeleniumBase)!
After opening the website with
`driver.get("https://www.linkedin.com/home")`
then authorized and loaded the additinal content with 
`driver.click('#top-card-text-details-contact-info')`

All these actions worked properly. But then

when I tryed to save page code with 
`html = driver.get_page_source()`
I got such stange error  

> AttributeError                            Traceback (most recent call last)
> C:\Users\7272~1\AppData\Local\Temp/ipykernel_18088/2899172806.py in <module>
> ----> 1 html = driver.get_page_source()
>       2 
>       3 # title = driver.get_element("html")
> 
> ~\AppData\Roaming\Python\Python39\site-packages\seleniumbase\undetected\__init__.py in __getattribute__(self, item)
>     319     def __getattribute__(self, item):
>     320         if not super().__getattribute__("debug"):
> --> 321             return super().__getattribute__(item)
>     322         else:
>     323             import inspect
> 
> AttributeError: 'Chrome' object has no attribute 'get_page_source'

Could you help me, what I`m doing wrong? :(

**Comment by mdmintz** [comment]
You're looking for `driver.page_source` (a built-in `driver` variable). `self.get_page_source()` is a `seleniumbase` method for syntax formats that use the methods of [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) directly.

I have added some of the seleniumbase methods directly into the driver. I could add this one as well.

**Comment by maxi-am** [comment]
> You're looking for `driver.page_source` (a built-in `driver` variable). `self.get_page_source()` is a `seleniumbase` method for syntax formats that use the methods of [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) directly.
> 
> I have added some of the seleniumbase methods directly into the driver. I could add this one as well.

I`m just a novice in Python. So please excuse me for dumb questions 🙈

I tried to use methods from [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) with `driver`. I thought it`s possible.

How is it possible to use this methods line by line in Jupiter Notebook with keeping option **uc=True**? Is it possible without using classes? 
Thank you

**Comment by mdmintz** [comment]
Use the `SB()` manager: (https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py)

```python
"""SB Manager using UC Mode for evading bot-detection."""
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.get("https://nowsecure.nl/#relax")
    sb.sleep(2)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        sb.get_new_driver(undetectable=True)
        sb.driver.get("https://nowsecure.nl/#relax")
        sb.sleep(2)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        if sb.is_element_visible('iframe[src*="challenge"]'):
            with sb.frame_switch('iframe[src*="challenge"]'):
                sb.click("span.mark")
                sb.sleep(4)
    sb.activate_demo_mode()
    sb.assert_text("OH YEAH, you passed!", "h1", timeout=3)
```

(`sb` has all the methods from [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md))

**Comment by maxi-am** [comment]
> Use the `SB()` manager: (https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py)
> 
> ```python
> """SB Manager using UC Mode for evading bot-detection."""
> from seleniumbase import SB
> 
> with SB(uc=True) as sb:
>     sb.driver.get("https://nowsecure.nl/#relax")
>     sb.sleep(2)
>     if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
>         sb.get_new_driver(undetectable=True)
>         sb.driver.get("https://nowsecure.nl/#relax")
>         sb.sleep(2)
>     if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
>         if sb.is_element_visible('iframe[src*="challenge"]'):
>             with sb.frame_switch('iframe[src*="challenge"]'):
>                 sb.click("span.mark")
>                 sb.sleep(4)
>     sb.activate_demo_mode()
>     sb.assert_text("OH YEAH, you passed!", "h1", timeout=3)
> ```
> 
> (`sb` has all the methods from [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md))

Sorry for one more dumb question 

I saw the method you mentioned. Even tried it. The problem is that it`s close the browser window after finishing all commands.  1. How can I keep browser window opened?
2. Is it possible to add and execute new lines of commands on Jupiter Notebook after? New line, new comand. It`s very usefull to test how new commands ( interaction with some elements of the page) works

Thanks for this tool one more time!

**Comment by mdmintz** [comment]
Use a `breakpoint()` or `import pdb; pdb.set_trace()` to pause the test at the breakpoint until continuing with `c` + `Enter`. With the exception of the `driver = Driver()` format, the other syntax formats will close the browser at the end of the test. Not sure about your "Jupiter Notebook" question: I don't use that.
