### ISSUE TITLE
change vendor and renderer of webgl

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2168]
how can i change vendor and renderer of webgl
i tried so much to do that but i failed
can you help me?

**Comment by mdmintz** [comment]
There are two different `pytest` command-line options that you can use for changing WebGL rendering:

```python
--enable-3d-apis  # (Enables WebGL and 3D APIs.)
--swiftshader  # (Chrome "--use-gl=angle" / "--use-angle=swiftshader-webgl")
```

If using the `Driver()`, `DriverContext()` or `SB()` managers, then you can set a method arg to activate those. Here are those args with the default settings: (Set one or both to `True` to activate.)

```python
enable_3d_apis=None,  # Enable WebGL and 3D APIs.
swiftshader=None,  # Chrome: --use-gl=angle / --use-angle=swiftshader-webgl
```

**Comment by YOTYTeaM** [comment]
its true.
i mean that changing vendor and renderer to custom variables, how can i?

**Comment by mdmintz** [comment]
Those are the available options. There's no option for faking the graphics/vendor/renderer settings.
