### ISSUE TITLE
UC mode was detected by Cloudflare after clicking with selenium

### ISSUE THREAD

**Issue by CatalinaCharlotte** [seleniumbase/SeleniumBase#2185]
[Basic Information]
System: win10
Language: python 3.9
seleniumbase version: 4.20.1
chrome version: 118.0.5993.71

[Details]
When testing with the following code, https://nowsecure.nl/#relax passes the test most of the time. In situations where the test does not pass, the test can also be passed by manually clicking on the checkbox:

```
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(6)
driver.quit()
```

But https://mjai.ekyu.moe/ still fails to pass the cloudflare test. Manually clicking the checkbox will give a failed result
```
from seleniumbase import Driver
import time

driver = Driver(uc=True)
driver.get("https://mjai.ekyu.moe/")
time.sleep(6)
driver.quit()
```

**Comment by mdmintz** [comment]
Starting with `seleniumbase` `4.20.2`, you can increase the default reconnect time when opening a page in UC Mode:

(See https://github.com/seleniumbase/SeleniumBase/issues/2186#issue-1942075366)

```
from seleniumbase import Driver

driver = Driver(uc=True)
driver.uc_open_with_reconnect("https://mjai.ekyu.moe/", reconnect_time=5)
# ...
driver.quit()
```

Then you no longer need to click that checkbox. (The second page you used needed more than the default wait time.)

### Video:

https://github.com/seleniumbase/SeleniumBase/assets/6788579/9bfd1a5c-0773-44c4-86c8-f45c4e31d4a4

You'll need to update your scripts to use the new method that opens the page with a longer reconnect time. (After upgrading to `seleniumbase` `4.20.2`)

**Comment by CatalinaCharlotte** [comment]
Thanks for your prompt reply and update. It works.

**Comment by OpsecGuy** [comment]
@mdmintz Would you have any solution for that? Surprisingly without the usage of proxies, everything is working just fine!
The main problem is that the website auto-refreshes after submitting the captcha on proxified connections.


1st try is WITHOUT proxy
2nd try is WITH proxy

![Code_TwdeMxmxHM](https://github.com/seleniumbase/SeleniumBase/assets/30886720/344b8fff-f4f8-431b-81ca-343e66442d21)

**Comment by mdmintz** [comment]
@OpsecGuy Your proxy had a slow connection. I used a stopwatch to time how long it took for your captcha to appear: 10 seconds! Yet, you used `reconnect_time=5` in your `uc_open_with_reconnect()` call, which means that you could be detected after your 5 seconds was up. It's also possible that your proxy's IP Address was already blocked.

**Comment by OpsecGuy** [comment]
> @OpsecGuy Your proxy had a slow connection. I used a stopwatch to time how long it took for your captcha to appear: 10 seconds! Yet, you used `reconnect_time=5` in your `uc_open_with_reconnect()` call, which means that you could be detected after your 5 seconds was up. It's also possible that your proxy's IP Address was already blocked.

Thank you, bro!
I appreciate your engagement! Now I know what to do :)
