### ISSUE TITLE
ModuleNotFoundError: No module named 'seleniumbase'

### ISSUE THREAD

**Issue by mrghubba** [seleniumbase/SeleniumBase#2188]
Hi there,
I've been getting the error message: "No module named undetected_chromedirver".
So I followed the instructions on this page to use Selenium Base instead from Michael Mintz: https://stackoverflow.com/questions/76863168/latest-undetected-chromedriver-version-3-5-1-problem

But I got this error:
![image](https://github.com/seleniumbase/SeleniumBase/assets/52516277/6ce0947a-275f-4be3-831e-0e3f4ec2f2ad)

I've tried Python 3.9, 3.10, 3.11 and 3.12. I have chromedriver 117, selenium 4.14 and I'm using the operating system Ubuntu 22.04 ARM64.
Please help. Thanks.

**Comment by mdmintz** [comment]
It looks like you have multiple Python environments on your system. Make sure you've installed `seleniumbase` into the one you're using. You can try several different commands to do that:

```bash
pip install -U seleniumbase
python -m pip install -U seleniumbase
python3 -m pip install -U seleniumbase
```

When you run your script, make sure you call it with the correct version of Python (for the direct-Python syntax formats).

Eg. If your program is called `test_abc`, then try the following ways:

```bash
python test_abc.py
python3 test_abc.py
```

If using `pytest`, it may be one of the following:

```
pytest
python -m pytest
python3 -m pytest
```

**Comment by mrghubba** [comment]
Hi mdmintz. Thanks for the quick reply. I did as you said. I also did a pip list of 3 different Python virtual environments and I got the same files: 
![image](https://github.com/seleniumbase/SeleniumBase/assets/52516277/c716aa68-1daf-42c6-aa59-16a23744ac79)

Then I did python instead python3 as you instructed but I got the same error:
![image](https://github.com/seleniumbase/SeleniumBase/assets/52516277/d691a65e-8e6c-415c-82d8-5c710a011eda)

**Comment by mdmintz** [comment]
From inside a Python script, you can use the following to install a package directly into that environment:

```python
import sys
import subprocess

subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", "seleniumbase"])
```

**Comment by mrghubba** [comment]
Great! It all works now. Thanks very much.
