### ISSUE TITLE
The XPath-to-CSS converter fails if an HTML tag contains a dash (`-`)

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2193]
## The XPath-to-CSS converter fails if an HTML tag contains a dash (`-`)

Eg. `self.js_click("//downloads-manager")`, where `seleniumbase` first converts the selector to CSS.

(The `downloads-manager` HTML tag can be found on the `chrome://downloads/` page.)

**Comment by mdmintz** [comment]
This was resolved in `4.20.3` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.20.3

**Comment by stanislaw** [comment]
Thank you very much for your quick turnaround!
