### ISSUE TITLE
"Enhanced ad privacy in Chrome" pop-up when setting a custom `user_data_dir`

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2201]
## "Enhanced ad privacy in Chrome" pop-up when setting a custom `user_data_dir`

This pop-up gets in the way of tests:

<img width="1200" alt="Screenshot 2023-10-20 at 12 18 39 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/a8764add-f320-4287-a24d-9d537c55f429">

**Comment by steinpigs** [comment]
Try setting this flag '--disable-features=PrivacySandboxSettings4'

**Comment by mdmintz** [comment]
@steinpigs Thanks, that worked. I'll ship a new release with the fix shortly.

**Comment by mdmintz** [comment]
This was resolved in `4.20.5` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.20.5 and already released to PyPI (https://pypi.org/project/seleniumbase/).
Hashtag: "Same-Hour-Delivery" (even Amazon would be jealous of that speed)
