### ISSUE TITLE
"Customize Chrome to give your browser a new look" pop-up is now appearing

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2203]
## "Customize Chrome to give your browser a new look" pop-up is now appearing

It must be raining pop-ups today, because earlier I encountered https://github.com/seleniumbase/SeleniumBase/issues/2201, and now I'm encountering this:

<img width="500" alt="Screenshot 2023-10-20 at 2 29 05 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/f356b2b5-79c6-4030-8335-f85862563f30">

Thanks to the info in https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md, I can remove this pop-up by using: `--ash-no-nudges` in Chromium options.

It appears that the latest Chromium release has added multiple pop-ups that haven't been seen before.

**Comment by mdmintz** [comment]
This was resolved in `4.20.6` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.20.6

**Comment by euroshopofcode** [comment]
This is not resolved with flag `--ash-no-nudges` yet, i am afraid, it randomly keep showing up still. 

<img width="381" alt="Image" src="https://github.com/user-attachments/assets/1cb9862f-2132-4f4b-9827-ddfcbe402d19" />

I tried all flag , but that blue pop-ups keep coming  `--disable-infobars --disable-notifications --disable-component-update --disable-background-networking --disable-default-apps --no-first-run --disable-popup-blocking --disable-pinch --disable-ipc-flooding-protection --disable-component-extensions-with-background-pages --disable-features=InterestFeedContentSuggestions,ChromeTips,ExtensionsToolbarMenu,PrivacySandboxSettings4,Translate --ash-no-nudges --no-default-browser-check --noerrdialogs`


Can you please check if there is any other flag for this? Thank you
