### ISSUE TITLE
How to set options with the `driver` format inside the code? (Eg. --undetected)

### ISSUE THREAD

**Issue by Takundanashe** [seleniumbase/SeleniumBase#2215]
can you tell how to set options eg --headed, --undetected inside code ,,i tried i couldn't solve this

**Comment by MovingW** [comment]
No options setting by far. But you could add params when creating new instance.

`driver = Driver(undetected=True, headless=True)`

Any other params, you could refer to below.

<img width="718" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/148598755/ba1e3469-a99c-49ed-a5b6-c1ca6a16f21f">

**Comment by mdmintz** [comment]
```python
from seleniumbase import Driver

driver = Driver(uc=True, headed=True)
driver.get("https://nowsecure.nl/#relax")
driver.sleep(4)
driver.quit()
```
