### ISSUE TITLE
Setting a `user_data_dir` while using Chrome extensions

### ISSUE THREAD

**Issue by SiTu-JIanying** [seleniumbase/SeleniumBase#2216]
First time,I use SeleniumBase open chrome without add extensions,like editcookies, and I really add "user-data-dir",generate special folder,at the end I use driver.quit() ,second time,i just use SeleniumBase open by "user-data-dir=special folder path", I can't find the installed extensions  in chrome.Did I do something wrong? or How can I see the extensions installed for the first time after the second startup?
wait u r,thx

**Comment by mdmintz** [comment]
If setting a `user_data_dir` (`--user-data-dir=DIR`) while setting a Chromium extension (`--extension-dir="dir1,dir2"`), make sure you run subsequent tests with the same command-line options for it to work. (Or with the same args if using one of the driver manager formats.)

Also, be sure that your user-data-dir for SeleniumBase is not used with regular non-Selenium Chrome. If using UC Mode, you can only reuse that user-data-dir for other UC Mode tests.
