### ISSUE TITLE
Add `--log-cdp` / `log_cdp=True` options for capturing CDP logs

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2220]
## Add `--log-cdp` / `log_cdp=True` options for capturing CDP logs

If enabled, this happens:

```python
chrome_options.set_capability(
    "goog:loggingPrefs", {"performance": "ALL", "browser": "ALL"}
)
```

Then you can do something like this to display those logs: (Eg. `driver.get_log("performance")`)

```python
from seleniumbase import Driver

driver = Driver(uc=True, log_cdp=True)
try:
    driver.get("https://seleniumbase.io")
    driver.sleep(3)
    print(driver.get_log("performance"))
finally:
    driver.quit()
```

Note that UC Mode also has separate `--uc-cdp` / `uc_cdp=True` options. That works differently. (See [SeleniumBase/examples/uc_cdp_events.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py) for an example of that.)

**Comment by mdmintz** [comment]
This was resolved in `4.20.8` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.20.8

**Comment by MovingW** [comment]
That's GREAT!!
Thanks for your quick response Michael.

**Comment by mdmintz** [comment]
https://github.com/seleniumbase/SeleniumBase/issues/2050#issuecomment-1718083788 - To get the response body of a request, first get the `requestId`. Then, you'll want to execute the following: `driver.execute_cdp_cmd("Network.getResponseBody", { "requestId": "<request id>" })`

**Comment by mdmintz** [comment]
See https://stackoverflow.com/a/52636871/7058266 for details.
