### ISSUE TITLE
Using uc option with proxy in multiprocessing repeats same ip

### ISSUE THREAD

**Issue by FranciscoPalomares** [seleniumbase/SeleniumBase#2223]
Related to https://github.com/seleniumbase/SeleniumBase/issues/2101

With multi_proxy=True, uc_subprocess=True

Same ip in 2 different drivers with uc
Thanks

**Comment by mdmintz** [comment]
This is working for me with valid proxies:

```python
from parameterized import parameterized
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__, "-n3")

class ProxyTests(BaseCase):
    @parameterized.expand(
        [
            ["host1:port1"],
            ["host2:port2"],
            ["host3:port3"],
        ]
    )
    def test_multiple_proxies(self, proxy_string):
        self.get_new_driver(
            undetectable=True, proxy=proxy_string, multi_proxy=True
        )
        self.driver.get("https://browserleaks.com/webrtc")
        self.sleep(30)
```

![multi_webrtc_checks](https://github.com/seleniumbase/SeleniumBase/assets/6788579/9292cd57-f364-49a5-9cd3-3e81235a68ef)

**Comment by FranciscoPalomares** [comment]
Script failed for me: argparse.ArgumentError: argument --browser: conflicting option string: --browser

Have you tried proxies with authentication? for me not works
Thanks

**Comment by mdmintz** [comment]
`argparse.ArgumentError: argument --browser: conflicting option string: --browser` means you installed another `pytest` plugin that is conflicting with `seleniumbase`. You'll need to uninstall the other plugin for `seleniumbase` to work. (Likely you have `pytest-playwright` installed, which has the same option.)

Authenticated proxies are working normally for me.

**Comment by FranciscoPalomares** [comment]
For me with undetectable=False,
with undetectable=True not works

**Comment by mdmintz** [comment]
What part isn't working? The full script is working for me.

**Comment by FranciscoPalomares** [comment]
Solved with pip install selenium base --upgrade --force

Sorry

**Comment by mdmintz** [comment]
@FranciscoPalomares It looks like you didn't add in the `proxy=PROXY_STRING` option, such as in this example: https://github.com/seleniumbase/SeleniumBase/issues/2223#issuecomment-1784140559
It's working for me, so perhaps there's an issue with your code. I can't debug unless you show me some code and your `pytest` run command.

**Comment by FranciscoPalomares** [comment]
Error with pyinstaller, generates dir with proxy_ext_dir_* . What is the purpose of this folder? How to delete ?

**Comment by mdmintz** [comment]
That's how authenticated proxy in Chrome works: https://stackoverflow.com/a/35293284/7058266 (If you don't want the temporary folder, don't use authenticated proxy.) More info about that and `pyinstaller` issues: https://github.com/seleniumbase/SeleniumBase/issues/2028#issuecomment-1692451570

**Comment by mdmintz** [comment]
That temporary proxy folder is deleted automatically at the end of a `pytest` run with SeleniumBase. Multiple tests and drivers could use it.

**Comment by FranciscoPalomares** [comment]
With this code, without pytest not delete the proxy folder:

`
import concurrent
from multiprocessing import freeze_support

from seleniumbase import Driver


proxies =  [
            "proxy:....",
            "proxy:....",
            "proxy:....",
        ]


def logic(proxy):
    driver = Driver(multi_proxy = True,  undetected=True, proxy = proxy,  uc_subprocess=True, ad_block_on=False)

    driver.get("https://browserleaks.com/webrtc")
    driver.sleep(30)

    driver.quit()

if __name__ == '__main__':
    freeze_support()
    with concurrent.futures.ProcessPoolExecutor(max_workers =2) as executor:
        future_proc = {executor.submit(logic, proxy): proxy for proxy in proxies}
        for future in concurrent.futures.as_completed(future_proc):
            pass
`

**Comment by mdmintz** [comment]
That's why you have to use multithreading with pytest. There could be multiple threads using the same proxy config folder. The threads can't talk to each other, so neither one knows when it's safe to delete the folder. However, with pytest managing the threads, pytest knows when all threads have completed, and can safely delete the temporary proxy config folder at the end of the tests. That's one of many reasons why multithreading is only supported via pytest (using `pytest-xdist`).
