### ISSUE TITLE
Does it support script recording for Shadow-DOM

### ISSUE THREAD

**Issue by wuwen5** [seleniumbase/SeleniumBase#2237]
When I am in a scene with `Shadow DOM`, the recorded script seems to not work properly.

**Comment by mdmintz** [comment]
To work with Shadow DOM, see [SeleniumBase/help_docs/shadow_dom.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/shadow_dom.md).

The [SeleniumBase Recorder](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/recorder_mode.md) cannot record those selectors on its own.
