### ISSUE TITLE
UC Mode Fails on Cloudflare Turnstile

### ISSUE THREAD

**Issue by Pugio** [seleniumbase/SeleniumBase#2250]
While `https://nowsecure.nl/#relax` works, the following site does not:

```python
from seleniumbase import Driver

d = Driver(uc=True)
d.get("https://myaccounts.secumd.org/Authentication")
d.save_screenshot("turnstile_fail.png")
```

I'm not sure how to debug this failure, but I'm happy to try things out...

**Comment by mdmintz** [comment]
Um, that's a real bank / financial institution. It would be totally illegal to help you get past their captcha security like that.

With great automation software comes great responsibility... and you can't come in here asking for something illegal.

Getting past captchas is all fun & games until you use it on a place where there are consequences for those actions.

From what you just heard, it should come as no surprise that you're getting blocked for opening an issue like that.
