### ISSUE TITLE
Can I change WebGL information

### ISSUE THREAD

**Issue by gupta723** [seleniumbase/SeleniumBase#2252]
Is there a way to enter random information? When we tested on https://pixelscan.net/  

Exemple:
languages=["en-US", "en"],
vendor="Google Inc.",
platform="Win32",
webgl_vendor="Intel Inc.",
renderer="Intel Iris OpenGL Engine",
fix_hairline=True,

more using in the SB model

```
with SB(uc=True, mobile=False) as sb: 
    ua = UserAgent()
    user_agent = ua.random

    sb.execute_cdp_cmd( "Network.setUserAgentOverride", {"userAgent": user_agent})
    sb.get("https://nowsecure.nl")
    sb.sleep(150.75)
```

**Comment by mdmintz** [comment]
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2248#discussioncomment-7501491
