### ISSUE TITLE
Is there any method of using two extensions simultaneously?

### ISSUE THREAD

**Issue by gupta723** [seleniumbase/SeleniumBase#2253]
I currently have two extensions that should be applied to the execution, what should I do?

An error always occurs stating that one of the manifests is incorrect, but only one goes normally

unsuccessful test

```
with SB(uc=True, mobile=False,extension_dir="extension/pyd,extension/dax") as sb:

    sb.get("https://nowsecure.nl")
    sb.sleep(150.75)
```

**Comment by mdmintz** [comment]
Extensions in UC Mode get added via `extension_dir`, which takes a comma-separated string as you have done. If a manifest is incorrect, then that would indicate a problem with the extension itself.

**Comment by gupta723** [comment]
Yes, but both run alone work, but when we try both, a manifest always gives an error, but they are completely correct
