### ISSUE TITLE
Looks like Cloudflare found out about SeleniumBase UC Mode

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2255]
The makers of the **Turnstile** have found out about **SeleniumBase UC Mode**:

<img width="480" alt="Screenshot 2023-11-08 at 5 47 30 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/08fa67af-262e-48e4-8699-33e04c15ab54">

**To quote Dr. Emmett Brown from Back to the Future:**
> **"They found me. I don't how, but they found me."**

![dr-emmett-brown-doc](https://github.com/seleniumbase/SeleniumBase/assets/6788579/0268c030-96b5-4e22-a0f1-d648a6375f68)

I guess that means they watched the **SeleniumBase UC Mode** video: https://www.youtube.com/watch?v=5dMFI3e85ig

--------

In other news, I'm working on more updates and demo pages for running tests.

Once the next release is shipped, I'll start going through the notification queue.

**Comment by mdmintz** [comment]
Version `4.21.0` is now available: https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.21.0

**Comment by Rhaniel0** [comment]
Hello, excuse me for my lack of knowledge and possible English errors, so does this mean Cloudflare is being able to detect seleniumbase UC mode? I ask because I have an automation running using this repository and it started to be detected yesterday, so I would like to understand if it was the protection of the website in question that added another layer of security or if it was Cloudflare that improved detection. Again, I'm not an experienced developer, so I might be off topic. And thank you for all your fantastic work

**Comment by mdmintz** [comment]
@Rhaniel0 I tested all the UC Mode examples successfully on version `4.21.0`:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py

UC Mode is also working on these new examples where clicking is required:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py

Upgrade to the latest version of SeleniumBase, and things should be working.

**Comment by Rhaniel0** [comment]
> @Rhaniel0Testei todos os exemplos do modo UC com sucesso na versão `4.21.0`:
> 
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py
> 
> O Modo UC também está trabalhando nestes novos exemplos onde é necessário clicar:
> 
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py
> 
> Atualize para a versão mais recente do SeleniumBase e tudo deverá funcionar.

Thank you!

**Comment by Rhaniel0** [comment]
Hi @mdmintz , I updated to the latest version, but I keep getting undetected. I can access the website and carry out the process, but I receive a message in my email saying that the process carried out has been cancelled. This happens when there is detection. Can you guide me if I should make a specific configuration? I'm using `seleniumbase` with `context-manager` and `uc=True`.

**Comment by Id1n** [comment]
thank you for seleniumbase updates ,  works well

**Comment by Id1n** [comment]
> @Rhaniel0 I tested all the UC Mode examples successfully on version `4.21.0`:
> 
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py
> 
> UC Mode is also working on these new examples where clicking is required:
> 
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py
> * https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py
> 
> Upgrade to the latest version of SeleniumBase, and things should be working.


thank you for seleniumbase updates , works well

**Comment by STARKILLER-1** [comment]
Please go away Cloudflare

**Comment by STARKILLER-1** [comment]
4.21.1
![image](https://github.com/seleniumbase/SeleniumBase/assets/102546596/c04aa046-fbef-4538-b2b8-35e34c1ed960)
![image](https://github.com/seleniumbase/SeleniumBase/assets/102546596/4fbbd8e3-dd05-455b-8f60-696cde0107d4)

**Comment by mdmintz** [comment]
@STARKILLER-1 Suspicious behavior can get your IP blacklisted, as mentioned in https://www.youtube.com/watch?v=5dMFI3e85ig at 22:37 and 29:41.

**Comment by STARKILLER-1** [comment]
> @STARKILLER-1 Suspicious behavior can get your IP blacklisted, as mentioned in https://www.youtube.com/watch?v=5dMFI3e85ig at 22:37 and 29:41.

Yep, I remembered it while was testing, thank you!

**Comment by mdmintz** [comment]
The latest UC Mode updates can be found in `4.21.2` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.21.2

Also closing out this ticket.
