### ISSUE TITLE
Would it be possible for MAC Address Changer to always do a random

### ISSUE THREAD

**Issue by gupta723** [seleniumbase/SeleniumBase#2256]
Is it possible to somehow change the MAC Address Changer
Like https://technitium.com/tmac/ it is a Windows version but it is based on the change generating a random message?

MAC Address Chang?

**Comment by mdmintz** [comment]
That appears to be a totally separate tool that is unaffiliated with Selenium, etc. I would seek answers elsewhere. A quick Google search turned up this, which may be of interest: https://thepythoncode.com/article/make-a-mac-address-changer-in-python
