### ISSUE TITLE
Find element and Get attribute in UC=TRUE

### ISSUE THREAD

**Issue by Id1n** [seleniumbase/SeleniumBase#2263]
Hi 

It might be funny, but I've been struggling to find an Attribute for more than a day, and I haven't succeeded. 
In this situation it can be easily found

driver = uc.Driver()
driver.get(web)
driver.find_element(by='class', value='g-recaptcha').get_attribute('data-sitekey')

 but in situation

SB(uc=True) as sb:
sb.driver.get(web)

I've checked numerous methods, but none of them gave me the correct answer with this mode. I apologize if my question is too beginner-level. I would appreciate it if you could guide me.

**Comment by mdmintz** [comment]
To find the `data-sitekey` on https://seleniumbase.io/apps/recaptcha, you can do:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
try:
    driver.get("https://seleniumbase.io/apps/recaptcha")
    sitekey = driver.locator("div.g-recaptcha").get_attribute("data-sitekey")
    print(sitekey)
finally:
    driver.quit()
```
