### ISSUE TITLE
Seleniumbase not working with Chrome 119.*

### ISSUE THREAD

**Issue by Id1n** [seleniumbase/SeleniumBase#2265]
hello

Until Chrome version was 114, the SeleniumBase was working very well. After updating Chrome, SeleniumBase detects that Chrome has been updated and displays the following message:

Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 119.0.6045.105 (Latest Stable) 

Downloading chromedriver-win64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/win64/chromedriver-win64.zip ...
Download Complete!

each time the code is executed, the same message appears. After downloading the driver, the browser briefly appears and disappears, and the code remains in the same state. When I downgrade Chrome to version 114, it works again. I want to know if there is a version limitation for running Chrome and if there is anything specific I need to do."

**Comment by STARKILLER-1** [comment]
Hi, I had same issue, fixed by downloading driver myself from https://googlechromelabs.github.io/chrome-for-testing/ and deploying in project directory

**Comment by mdmintz** [comment]
SeleniumBase UC Mode is working properly for me with default settings on Windows:

![11B5CF5B-EDA6-40DA-A60B-26A68CFB1D31](https://github.com/seleniumbase/SeleniumBase/assets/6788579/0a24a9ca-6cd7-44ee-8806-b5ef5068e18d)

It updated the driver the first time as needed, and then it reused the existing driver.
