### ISSUE TITLE
mouse founction in Seleniumbase

### ISSUE THREAD

**Issue by Mo0LY** [seleniumbase/SeleniumBase#2267]
hi 
are there any method in seleniumbase for mouse founction ?!
i need to hover_element_and_click and drag and drop .
could you tell me how can i access to them

**Comment by mdmintz** [comment]
There's `self.hover_and_click(hover_selector, click_selector)`.
There's also `self.drag_and_drop(drag_selector, drop_selector)`.

Examples of those:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_demo_site.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_drag_and_drop.py

All methods:
https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md
