### ISSUE TITLE
Verbose mode - Driver details

### ISSUE THREAD

**Issue by pablorq** [seleniumbase/SeleniumBase#2271]
Is there any way to get a verbose mode or get more details about the driver version, or uc version?

It will good to have it with SB and Driver class, at least.

**Comment by mdmintz** [comment]
A way of getting the driver version already exists. Try running [SeleniumBase/examples/test_chromedriver.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_chromedriver.py)

Or get the details via `driver.capabilities`:

```python
driver_version = driver.capabilities["chrome"]["chromedriverVersion"].split(" ")[0]
print(driver_version)
```

Works for both regular `chromedriver` and `uc_driver`.
