### ISSUE TITLE
Prevent `self._get_browser_version()` from erroring for Appium users

### ISSUE THREAD

**Issue by adityai** [seleniumbase/SeleniumBase#2287]
In my capabilities.py file I have 'appium:platformVersion', but I didn't have a 'version' or 'browserVersion' in it, and I see an error message in the console log (as shown below). To get around this problem, I had to add 'browserVersion': '' to the capabilities. 

==================================================================================== FAILURES =====================================================================================
___________________________________________________________________________ MyTestClass.testLoginButton ___________________________________________________________________________
venv\lib\site-packages\seleniumbase\fixtures\base_case.py:15731: in tearDown
    sb_config._browser_version = self._get_browser_version()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <iosSafariTests.MyTestClass testMethod=testLoginButton>

    def _get_browser_version(self):
        driver_capabilities = None
        if hasattr(self, "driver") and hasattr(self.driver, "capabilities"):
            driver_capabilities = self.driver.capabilities
        elif hasattr(sb_config, "_browser_version"):
            return sb_config._browser_version
        else:
            return "(Unknown Version)"
        if "version" in driver_capabilities:
            browser_version = driver_capabilities["version"]
        else:
>           browser_version = driver_capabilities["browserVersion"]
E           KeyError: 'browserVersion'

venv\lib\site-packages\seleniumbase\fixtures\base_case.py:15567: KeyError
============================================================================= short test summary info ============================================================================= 
FAILED iosSafariTests.py::MyTestClass::testLoginButton - KeyError: 'browserVersion'
=============================================================================== 1 failed in 22.23s ================================================================================

**Comment by mdmintz** [comment]
Resolved in `4.21.3` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.21.3
