### ISSUE TITLE
driver.reconnect() messes up window handles

### ISSUE THREAD

**Issue by MacMarde** [seleniumbase/SeleniumBase#2305]
I have one Chrome browser tab opened. I click a link inside this tab, which open a new tab.
I instantly make a reconnect, to be undetected on the new opened tab.
After the reconnect timeout I want to switch to the latest window (tab) opened.

Here is my code:

```
element1.click()                
browser.reconnect(random.uniform(15, 20))
browser.switch_to.window(browser.window_handles[-1])
```
Before I open a new tab, I have one open window A with windows handle index '0'.
After executing the code above I have two windows A and B, but windows A has now the window handle index '1', though it should have index '0'.
Without browser.reconnect Windows A is keping its handle '0', also after open a new window. 
So when switching to the last opened window with `browser.switch_to.window(browser.window_handles[-1])` I get two different behaviours.

Of course I can easily change my code, but the question is if this behaviour is correct, becuase it can confuse existing code.

**Comment by mdmintz** [comment]
Don't use regular clicks when you want to remain undetected. There's a special `driver.uc_click(selector)` method for that: (Change the `reconnect_time` when you need a longer disconnect, mainly for slower internet connections.)

```python
driver.uc_click(
    selector, by="css selector",
    timeout=settings.SMALL_TIMEOUT, reconnect_time=None)
```

If you can keep everything down to one tab, that is preferable, as reconnecting chromedriver to Chrome may change the order of multiple tabs.

Here are some example tests that use `driver.uc_click(selector)`:

* [SeleniumBase/examples/raw_turnstile.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py)
* [SeleniumBase/examples/raw_form_turnstile.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py)

**Comment by MacMarde** [comment]
> Don't use regular clicks when you want to remain undetected. There's a special `driver.uc_click(selector)` method for that: (Change the `reconnect_time` when you need a longer disconnect, mainly for slower internet connections.)
> 
> ```python
> driver.uc_click(
>     selector, by="css selector",
>     timeout=settings.SMALL_TIMEOUT, reconnect_time=None)
> ```
> 
> If you can keep everything down to one tab, that is preferable, as reconnecting chromedriver to Chrome may change the order of multiple tabs.
> 
> Here are some example tests that use `driver.uc_click(selector)`:
> 
>     * [SeleniumBase/examples/raw_turnstile.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py)
> 
>     * [SeleniumBase/examples/raw_form_turnstile.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py)

I think it will maybe not be possible to use uc_click() for me.
In my example above I click on an element which opens a new tab but does not wait for the website to load within the new tab.
So I think it will still be undetectable because I can instantly make a manual reconnect. 
I believe this should also work as long as the webdriver is not waiting for the new website to load.
May I be wrong? What do you think?
