### ISSUE TITLE
Recorder fails if the System `python` PATH contains spaces

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2320]
## Recorder fails if the System `python` PATH contains spaces

Eg, if the System Python PATH is `C:\Program Files\Python312\python.exe`, then you may see this error message:

`'C:\Program' is not recognized as an internal or external command`

This happened because the space caused a break in the path, which was interpreted in the system as a separate command.

**Comment by mdmintz** [comment]
Resolved in `4.21.5` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.21.5

**Comment by anthonyg45157** [comment]
Confirmed!! I'm the guy from YouTube! 👍 Great work
