### ISSUE TITLE
Incognito mode not working when Proxy set

### ISSUE THREAD

**Issue by antooro** [seleniumbase/SeleniumBase#2336]
Incognito mode not enabled when proxy is set (Proxy with auth)

`driver = Driver(uc=True, incognito=True, proxy=user:pwd@ip:port)`
`driver = Driver(uc=True, incognito=True)`

![image](https://github.com/seleniumbase/SeleniumBase/assets/34341810/3f07d240-4bb9-4852-a25a-376540057f23)

**Comment by mdmintz** [comment]
As mentioned in https://support.google.com/chrome_webstore/answer/2664769?hl=en -->

“Important: You can't add extensions when you browse in Incognito mode or as a guest.”

Proxy with auth requires the use of a Chrome extension to configure proxy settings. When you set SeleniumBase to use both an extension and incognito mode, it prioritizes the extension.

**Comment by ale-romeo** [comment]
Is there any alternatives to use both incognito mode and proxies? Is it possible to simulate incognito mode just deleting all cookies after a session?

**Comment by mdmintz** [comment]
There’s delete_all_cookies() if you just want to delete cookies during a session.
