### ISSUE TITLE
How can I use wait_for_element() for some elements at the same time?

### ISSUE THREAD

**Issue by Id1n** [seleniumbase/SeleniumBase#2342]
Hello,

I want to use the "wait_for_element" feature in a way that, after the page is loaded, there might be three different elements presented, and based on those elements, different processes need to be executed. For example, if I use `self.wait_for_element('#button', timeout=10)` and the element is not on the page, I'll get an error.

I tried using a try-except block to check the second element, but the problem is that it takes a considerable amount of time if I force checking for three conditions separately. I want to utilize this option to minimize the time spent finding the elements and make the process more efficient.

Is there a solution to check multiple elements simultaneously?

**Comment by mdmintz** [comment]
You may want to utilize `self.is_element_visible(selector):` so that you have better flow of control than just `try/except` for this.

Or be creative and try something like this:

```python
import time

found_1 = False
found_2 = False
found_3 = False
max_wait = time.time() + 10
while True:
    if time.time() >= max_wait:
        raise Exception("Waited too long!")
    if self.is_element_visible("selector_1"):
        found_1 = True
        # Do something for 1
    if self.is_element_visible("selector_2"):
        found_2 = True
        # Do something for 2
    if self.is_element_visible("selector_3"):
        found_3 = True
        # Do something for 3
    if found_1 and found_2 and found_3:
        break
    time.sleep(0.1)
```

**Comment by Id1n** [comment]
thank you for your solution.
