### ISSUE TITLE
UC Mode Ineffective on Streamlit Cloud

### ISSUE THREAD

**Issue by LiPingYen** [seleniumbase/SeleniumBase#2350]
I have deployed a web automation script on Streamlit Cloud, utilizing the `uc` mode to bypass the web scraping detection system. During local device testing, the script consistently successfully circumvents the web scraping detection system. However, when executing on Streamlit Cloud, the `uc` mode appears to be ineffective, leading to the detection of the script. Could someone please provide guidance on how to address this issue?

I have reviewed #2063. Is there a method available to make the `uc` mode effective without using a proxy?

**Comment by mdmintz** [comment]
Using a proxy lets you mask the IP Address in UC Mode. Masking the IP address may be necessary to avoid detection because services such as Cloudflare will blacklist IP ranges for known bot traffic, such as Streamlit Cloud in your case.
