### ISSUE TITLE
Strange behavior in headless mode on chrome version 120.0.6099.62 (arm64)

### ISSUE THREAD

**Issue by LiPingYen** [seleniumbase/SeleniumBase#2354]
When the local Chrome version is 119.x, the headless mode combined with UC mode and utilizing the SB syntax with the context manager can be executed successfully. However, upon upgrading the local Chrome version to 120.0.6099.62 (Official Build) (arm64), the headless mode executes continuously without producing results, and no error messages are displayed. If the same configuration is used with headless set to False, the execution proceeds smoothly.

- seleniumbase version: 4.22.0

**Comment by mdmintz** [comment]
> `If the same configuration is used with headless set to False, the execution proceeds smoothly.`

I would just set `headless` to False then if that is not an issue. Not sure what exactly changed in Chrome 120, but if you can change a simple setting to make it work, then just do that.
