### ISSUE TITLE
Not able to capture Network trafic Responses 

### ISSUE THREAD

**Issue by slvamegestic** [seleniumbase/SeleniumBase#2359]
`from seleniumbase import SB

def callback(data):
url = data['params']['response']['body']
print(url)

with SB(uc=True, headed=True, uc_cdp_events=True) as sb:
sb.driver.add_cdp_listener("Network.responseReceived", callback)
sb.driver.get("https://checkout.stripe.dev/preview")
sb.sleep(3)
sb.set_content_to_frame('iframe[title="Checkout Demo"]')
sb.sleep(3)
`
if I try to get the body of the response, it gets null, how to capture network responses in Seleniumbase?

**Comment by mdmintz** [comment]
This will capture and print the data:

```python
from pprint import pformat
from seleniumbase import SB

with SB(uc=True, headed=True, uc_cdp_events=True) as sb:
    sb.driver.get("https://checkout.stripe.dev/preview")
    sb.sleep(3)
    url = sb.get_attribute('iframe[title="Checkout Demo"]', "src")
    sb.driver.get(url)
    sb.sleep(3)
    sb.driver.add_cdp_listener("Network.responseReceived", lambda data: print(pformat(data)))
    sb.driver.refresh()
    sb.sleep(3)
```

**Comment by slvamegestic** [comment]
Hi @mdmintz 
Thanks for your response.
But Unfortunately still i not able to get the response body

Please see my below code for your understanding.

This needs to by return my IP, but i am getting headers /params.

`from pprint import pformat
from seleniumbase import SB

with SB(uc=True, headed=True, uc_cdp_events=True) as sb:
    sb.driver.get("http://httpbin.org/ip")
    sb.sleep(3)
    sb.driver.add_cdp_listener("Network.responseReceived", lambda data: print(pformat(data)))
    sb.driver.refresh()
    sb.sleep(3)`
    
    This would be appreciatable if you help me with this
