### ISSUE TITLE
Cannot pass cloudfare. Only PC restart helps

### ISSUE THREAD

**Issue by mdaliyot** [seleniumbase/SeleniumBase#2361]
Hi, I'm using SB version 4.21.1, chrome version 120.0.6099.71.
I could use SB quite a while, but from time to time it gets detected and being blocked by cloudfare.
Only when I restart my PC (Windows 11), it can pass it again.
Any help is greatly appreciated, thanks!

**Comment by mdmintz** [comment]
Hi, you're on an old version of SeleniumBase that's missing several key updates. You should upgrade to the latest.

Also, since you haven't shown any code or stack traces, I'm not sure what you're doing.
(The [23 Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) are very different.)

Here's a script that works on the latest version: (It uses the `SB()` manager.)

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    sb.driver.uc_open_with_tab("https://nowsecure.nl/#relax")
    sb.sleep(1.2)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        sb.get_new_driver(undetectable=True)
        sb.driver.uc_open_with_reconnect(
            "https://nowsecure.nl/#relax", reconnect_time=3
        )
        sb.sleep(1.2)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        if sb.is_element_visible('iframe[src*="challenge"]'):
            with sb.frame_switch('iframe[src*="challenge"]'):
                sb.click("span.mark")
                sb.sleep(2)
    sb.activate_demo_mode()
    sb.assert_text("OH YEAH, you passed!", "h1", timeout=3)
```

**Comment by mdaliyot** [comment]
Hi Michael,
First I've upgraded to latest version 4.22.0.

Now, This is my code:

`from seleniumbase import Driver
`...
`drv = Driver(undetectable=True, headless=False, browser="chrome")`
**==> At that point, I'm getting "Access is denied" in console**
```
drv.maximize_window()
drv.get(f"https://www.forexfactory.com/calendar?day=today")
```
**==> Up until that point, page is loaded correctly**

**==>When trying to reload page at 'today' date or any other date, it gets blocked.**
`drv.get(f"https://www.forexfactory.com/calendar?day={date_str}")`

As stated above, The only solution I have currently is PC restart

**Comment by mdmintz** [comment]
Try with the `SB()` manager format, especially if you're using Linux. (It automatically sets up the Xvfb virtual display.)

For slower connections (or longer page loads), you'll need to use `uc_open_with_reconnect()` with a longer time to make sure the page finishes loading before reconnecting.

Here's a simple example:

```python
from seleniumbase import SB

with SB(uc=True, headed=True):
    sb.driver.uc_open_with_reconnect("https://nowsecure.nl/#relax", reconnect_time=4)
```

There are lots of UC Mode examples to help you:

* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py

Here are some newer UC Mode examples where clicking is required:

* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py

And if that isn't enough, there's a UC Mode video showing how it works:
<b>https://www.youtube.com/watch?v=5dMFI3e85ig</b>

<a href="https://www.youtube.com/watch?v=5dMFI3e85ig"><img src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/4c9a112a-25c6-458f-83c6-c4b910b8b636" title="undetected automation" width="330" /></a>

**Comment by mdmintz** [comment]
Hi @mdaliyot, Great! I'm not sure if `pyinstaller` made any changes recently, or if you made changes to your `pyinstaller` setup. If you can, just use `python` directly. That's what I do.

**Comment by Tongcheng** [comment]
Hi @mdmintz , I wonder if you know the pass of Cloudflare tests (e.g. nowsecure.nl) is dependent on IP address. Specifically, I am testing on Colab (which I think uses Data Center IP), and it doesn't seem to pass. Any thoughts on if it's dependent on proxying with residential IP?

**Comment by mdmintz** [comment]
@Tongcheng It's definitely dependent on IP Address. Cloudflare blocks datacenter IPs.
