### ISSUE TITLE
Unsuccessful attempt to bypass datadome detection using uc mode in seleniumbase

### ISSUE THREAD

**Issue by LiPingYen** [seleniumbase/SeleniumBase#2365]
I attempted to bypass DataDome's detection using the `uc` mode in SeleniumBase, but unfortunately, I was not successful. I'm wondering if anyone else has encountered a similar situation. Below is the test code I used for reference.

```python
datadome_test_url = 'https://antoinevastel.com/bots/datadome’
with SB(uc = True, slow = True) as sb:
    sb.driver.uc_open_with_reconnect(datadome_test_url, reconnect_time = 10)
    sb.save_screenshot(name = './datadome_test_outcome.png')
```

![Unknown](https://github.com/seleniumbase/SeleniumBase/assets/47491041/08fef31d-cae3-430d-a5ff-f46b3ea55893)

**Comment by mdmintz** [comment]
```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.uc_open_with_reconnect(
        "https://antoinevastel.com/bots/datadome",
        reconnect_time=6
    )
    breakpoint()
```

<img width="1270" alt="Screenshot 2023-12-15 at 10 27 12 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/cdd1c9c1-38dd-4641-88fd-d760fdb4b72b">

**Comment by ivanovevgeny** [comment]
To reproduce, on the first open [https://www.sonono.de/](https://www.sonono.de/) (or after clear cookies)

<img width="340" height="387" alt="Image" src="https://github.com/user-attachments/assets/b968c32d-265e-44e0-9315-e1dfb2573c14" />

**Comment by mdmintz** [comment]
People should be using the newer [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md), which has been available since October 2024.

**Comment by ivanovevgeny** [comment]
> People should be using the newer [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md), which has been available since October 2024.

I tried, but got the picture above (DataDom puzzle captcha)
```
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://www.sonono.de/kueche.html"
    sb.activate_cdp_mode(url)
    sb.sleep(1)
    sb.uc_gui_click_captcha()
    sb.sleep(20)
```


I will try some repos based on computer vision (OpenCV) later, like [Puzzle-Captcha-Solver](https://github.com/vsmutok/Puzzle-Captcha-Solver) or [Slider-Captcha-Automation](https://github.com/prashant-italiya/Slider-Captcha-Automation).
