### ISSUE TITLE
user_data_dir & proxy

### ISSUE THREAD

**Issue by Allmight3** [seleniumbase/SeleniumBase#2368]
Hello.

This code works well for me. It creates a local directory profile, uses the proxy and adds my extensions.

`driver = Driver(uc=True, headed=True, proxy=PROXY, user_data_dir=absolute_profile_directory, page_load_strategy="eager", extension_dir=extensions_dir)`

My issue is when I want to come back to this profile later, it requires authentication from the proxy I used when I created it. The problem is, I rotate proxies and the authentication changes.

I tried regular Selenium:
```
options = webdriver.ChromeOptions()
options.add_argument(f'--user-data-dir={folder_path}')
```

As well as SB:
`driver = Driver(uc=True, headed=True, user_data_dir=folder_path)`

I just want to load that profile back up without a proxy requirement. I also snooped around in the profile folder looking to see where the proxy information was being stored, so I could delete it programmatically before launching. However I couldn't find that information. It wasn't in Preferences or anywhere else that I had noticed.

Am I trying to do something that's unsupported? If so, is there a work-around -- such as deleting where the proxy data is stored before relaunching the profile?

Thank you

**Comment by mdmintz** [comment]
To disable proxy settings for regular Selenium, use https://stackoverflow.com/a/49033706/7058266:

```python
chrome_options.add_argument("--no-proxy-server")
```

With SeleniumBase, those options get passed via `chromium_arg`:

```python
chromium_arg="--no-proxy-server"
```

With the `Driver()`, that would be this:

```python
driver = Driver(chromium_arg="--no-proxy-server")
```

**Comment by epictroller64** [comment]
Hi, I am still having same issue with `driver = Driver(chromium_arg="--no-proxy-server", browser="chrome", user_data_dir=session_dir, headless=False, undetected=True)`, keeps asking to reauthenticate. I even deleted the proxy file from downloaded_files directory.

**Comment by mdmintz** [comment]
@epictroller64 You probably mixed your UC Mode `user_data_dir` with a non UC Mode Chrome. (You can't "cross the streams".) Try from a brand new `user_data_dir`, or don't specify one at all when you run your script.

**Comment by epictroller64** [comment]
Seems the only solution is to delete `user_data_dir` but I really need to carry the session data over after changing proxy. Creating new profile worked only once, after I removed the proxy and used `chromium_arg="--no-proxy-server"`, it still showed old details.

**Comment by mdmintz** [comment]
@epictroller64 You probably need to disable extensions:
`chromium_arg="--no-proxy-server,--disable-extensions"`

(Proxy details are configured via Chrome extension in SeleniumBase.)

Also, make sure you're not mixing a non UC Mode Chrome `user_data_dir` with a UC Mode Chrome `user_data_dir`.
If you "cross the streams", you'll need to start with a fresh `user_data_dir` for things to work.

**Comment by Allmight3** [comment]
> Seems the only solution is to delete `user_data_dir` but I really need to carry the session data over after changing proxy. Creating new profile worked only once, after I removed the proxy and used `chromium_arg="--no-proxy-server"`, it still showed old details.

I found that creating the profile using UC mode and a proxy with username:pass authentication will cause the profile to always require that same proxy.

If you create a profile using UC mode and a proxy without username:pass, then it will work normally as expected. So that's what I did. If you only have proxies with username authentication then you could use proxy.py perhaps to forward the proxy, then use the downstream proxy to create the profiles.
