### ISSUE TITLE
Multithreading using SeleniumBase

### ISSUE THREAD

**Issue by fashionprivate** [seleniumbase/SeleniumBase#2371]
Hello,

I'm using pytest in order to manage a multithreading bot and everything works fine.

```python
import pytest

@pytest.mark.parametrize("", [[]] * 4)
def test_multi_threaded(sb):
    sb.open("https://nowsecure.nl/#relax")
    try:
        sb.assert_text("OH YEAH, you passed!", "h1", timeout=5.25)
        sb.post_message("Selenium wasn't detected!", duration=2.8)
        sb._print("\n Success! Website did not detect Selenium! ")
    except Exception:
        sb.fail('Selenium was detected! Try using: "pytest --uc"')
```

Now, how I can get the CTRL-C key command in order to shutdown all the tests that run in parallel?

Thanks

**Comment by mdmintz** [comment]
Hello, pytest multithreading is purely coded on the pytest side of things: I would check out their repo if you're having trouble shutting down all parallel tests at once: https://github.com/pytest-dev/pytest
