### ISSUE TITLE
Can we use headless and undetectable both while creating a driver?

### ISSUE THREAD

**Issue by faisalriazgoraya** [seleniumbase/SeleniumBase#2372]
from seleniumbase import Driver
driver = Driver(undetectable=True, headless=True)
driver.open("https://www.ibm.com/topics/natural-language-processing")
driver.quit()

i am trying to use both headless and undetectable while creating a driver and it's not working. it's got stuck and does not return "Process finished with exit code 0" while using both undetectable and headless and it's working fine when i use one of them.
Can you please confirm, wheather can i use both or not?

**Comment by mdmintz** [comment]
Are you using macOS? If so, I just created https://github.com/seleniumbase/SeleniumBase/issues/2375 for this issue. I'll ship a fix sometime today.

**Comment by Kakhi74** [comment]
> Are you using macOS? If so, I just created #2375 for this issue. (`On macOS, Chrome 120 (or newer), UC Mode, and Headless Mode, the browser gets stuck after script.`)
> 
> I'll ship a fix sometime today.

Thank you. We have the same issue, looking forward for the result. Similar to Mac users with Silicon chips, I encountered problems with Mac drivers. I resolved the issue by installing Rosetta2, so it would translate the drivers instruction to be compatible with the x86 installation. Would it be possible to include native Chrome drivers for apple sillicon chips, as this would enhance performance?

**Comment by mdmintz** [comment]
The issue with **((macOS, Chrome 120+, UC Mode, and Headless Mode))** was resolved by `4.22.1` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.22.1

UC Mode on macOS needs the x86 chromedrivers to avoid detection. If you're not using UC Mode, the ARM drivers will be used instead.
