### ISSUE TITLE
get_text not work with path

### ISSUE THREAD

**Issue by Gantaronee** [seleniumbase/SeleniumBase#2379]
Hi ,
this is my html,I would like to take the " + " sign, but it doesn't work with Full xpath
I need to know what position it is in, whether after the first image or the second or third:

![Screenshot 135](https://github.com/seleniumbase/SeleniumBase/assets/133801447/986a5d73-492f-4449-97cd-8941f66d4826)

sb.get_text('/html/body/div[3]/div[1]/div[1]/div[2]/div[2]/h3/text()[2]')

Evaluating: sb.get_text('/html/body/div[3]/div[1]/div[1]/div[2]/div[2]/h3/text()[2]') did not finish after 3.00 seconds.

**Comment by Gantaronee** [comment]
to work around the problem I tried using :
sb.get_text('/html/body/div[3]/div[1]/div[1]/div[2]/div[2]/h3/img[2]/following-sibling::p')

but it does not work

**Comment by mdmintz** [comment]
If you have specific questions related to finding the correct selector (CSS or XPath) for your scripts, try [StackOverflow](https://stackoverflow.com/questions/tagged/selenium).

The message `did not finish after 3.00 seconds` isn't coming from SeleniumBase, so there must be something else you're running into.

**Comment by Gantaronee** [comment]
This is the complete message error:  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 1817, in get_text
    element = page_actions.wait_for_element_visible(
  File "/usr/local/lib/python3.10/site-packages/seleniumbase/fixtures/page_actions.py", line 508, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "/usr/local/lib/python3.10/site-packages/seleniumbase/fixtures/page_actions.py", line 266, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.NoSuchElementException: Message: 
 Element {/html/body/div[3]/div[1]/div[1]/div[2]/div[2]/h3/text()[2]} was not present after 10 seconds!
