### ISSUE TITLE
How to restart the browser with pytest?

### ISSUE THREAD

**Issue by mIgLLL** [seleniumbase/SeleniumBase#2382]
1. I have millons of urls and need to crawl the data from the website.
2. The anti-crawling technologies restrict that one broswer can only crawl ten pages, then you must close the browser and restart it again.
3. I find that pytest is designed for web testing, not crawling website, it's hard to restart the browser.
4. When starting a broswer, I need to load four chrome extensions, which makes it more complicated.
5. multi-thread is necessary

Any tips will help. Thank you!

**Comment by mdmintz** [comment]
You can always open a fresh, new browser for your tests in the middle of a test:

```python
self.get_new_driver(undetectable=True)
```

And you can close your existing browser window with:
`self.driver.quit()`.

For loading multiple Chrome extensions in the `pytest` format that uses `BaseCase`, use:
`pytest --extension-dir=DIR1,DIR2,DIR3,DIR4`
(Comma-separated format)

For multi-threading with `pytest`, see https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785

Note that even if you use UC Mode to bypass detection, if you send too many requests (too much traffic), they may still block your IP Address.
