### ISSUE TITLE
Chrome crashes using "--proxy=user:pw@ip:port" in amazon linux 2023

### ISSUE THREAD

**Issue by ytk223344** [seleniumbase/SeleniumBase#2389]
Hi, i am unable to run seleniumbase with default chrome browser in the following environment with authenticated proxy option:

NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
PYTHON VERSION = "3.9.16"

Please check the following screenshots:
![crashes with proxy](https://github.com/seleniumbase/SeleniumBase/assets/50663386/5414e5db-8b54-47da-996b-f21053273dec)

I had run pytest and it had thrown the following error:
pytest proxy_test.py --proxy=login:password@brd.superproxy.io:2222

`../.local/lib/python3.9/site-packages/seleniumbase/core/browser_launcher.py:3466:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__
    super().__init__(
../.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:61: in __init__
    super().__init__(command_executor=executor, options=options)
../.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:209: in __init__
    self.start_session(capabilities)
../.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:293: in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
../.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:348: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7effb87ea6d0>
response = {'status': 500, 'value': '{"value":{"error":"session not created","message":"session not created: Chrome failed to sta...wn>\\n#14 0x557d43bee1d7 \\u003Cunknown>\\n#15 0x557d43c00124 \\u003Cunknown>\\n#16 0x7fdcc0c9f7f2 start_thread\\n"}}'`

Please also see attached for the error:
![running pytest with authenticated proxy and chrome](https://github.com/seleniumbase/SeleniumBase/assets/50663386/a0752710-f3d7-477a-89c7-db16d040c14b)

**Comment by mdmintz** [comment]
There are a few things you can try:

* Add `headless2=True` as an arg to `SB()`. (Or use `pytest --headless2`)

* Add `xvfb=True` as an arg to `SB()`. (Or use `pytest --xvfb`)

* Try using Wire Mode: `wire=True` as an arg to `SB()`. (Or use `pytest --wire`)
**Then use `sb.driver.set_wire_proxy(proxy_string)` for setting the proxy:**

```python
from seleniumbase import SB

with SB(wire=True) as sb:
    sb.driver.set_wire_proxy("user:pass@SERVER:PORT")
    # ....
```

At least one of these options should work and resolve the issue for you.

**Comment by ytk223344** [comment]
Using the below solved the issue. Thanks

with SB(browser="chrome", headless2=True, uc=True, proxy=proxy) as sb

**Comment by ytk223344** [comment]
Hi, even thought i can execute in the terminal, i am unable to setup the script as a start service using systemctl. It throws error when i start the service:

Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

My startup service script as follows:
![Uploading ResultBot service.png…]()

**Comment by mdmintz** [comment]
Is your `systemctl` script the same as your previous script and running with the same user as https://github.com/seleniumbase/SeleniumBase/issues/2389#issuecomment-1869011587?
It looks like the permissions changed between your scripts. Make sure you ran with the same user.

**Comment by ytk223344** [comment]
Hi, i had played around with different SB options running in terminal and startup service with brightdata rotating IP. I don't think It's permission changed that caused the issue.

Run in terminal, all 5 options were successful:
<img width="900" alt="Terminal" src="https://github.com/seleniumbase/SeleniumBase/assets/50663386/c0758c62-e347-43e6-ac64-66821ed4a510">

<img width="546" alt="TL 5 responses" src="https://github.com/seleniumbase/SeleniumBase/assets/50663386/c06b4cc8-4b7b-4909-9b37-5652dfec4904">

Run as startup service, option (proxy=proxy) did not response:
<img width="804" alt="Startup service" src="https://github.com/seleniumbase/SeleniumBase/assets/50663386/66e54b01-0de2-434e-b8d7-2486c20702ab">

<img width="546" alt="TL 4 responses" src="https://github.com/seleniumbase/SeleniumBase/assets/50663386/0ba6c632-1666-480f-9e50-f139b32229c8">

Please kindly advise what could be wrong.

**Comment by ytk223344** [comment]
The issue was caused when SB creates folder "download_files", create folder manually and change folder user's owner permission at root solved the issue.
