### ISSUE TITLE
Access denied error(403 forbidden) when when using seleniumbase. 

### ISSUE THREAD

**Issue by pauljohnySN** [seleniumbase/SeleniumBase#2398]
I am trying to do a data scraping from the website capterra.com. But after several hits to the website it shows access denied. 

```
from seleniumbase import Driver
driver = Driver(uc=True,headless=False,incognito=True)
driver.get("https://www.capterra.com/categories/")
```

I get the following error
<img width="1178" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/154502911/9e656f93-6939-42c0-a04c-7803705f9608">

When it loads I traverse the page and then grab the data and when I click on the pagination using selenium `.click()` it again pops the access denied when loading the next page.

**Comment by mdmintz** [comment]
Automation can load that page just fine in UC Mode.
This script loads it and drops in a Python `breakpoint()`.

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.uc_open_with_reconnect(
        "https://www.capterra.com/categories/",
        reconnect_time="breakpoint",
    )
```

But you can't do regular selenium clicks, as that gets you detected.
Use `sb.driver.uc_click(selector)` instead.

Also, if too much traffic gets generated from an IP Address, then that IP Address gets blacklisted. UC Mode does not hide your IP Address. That can only be done by changing proxy settings with the `proxy` arg.

**Comment by pauljohnySN** [comment]
How to change the proxy settings?

**Comment by mdmintz** [comment]
There's an arg, `proxy`, that you can set with `SB()`:

https://github.com/seleniumbase/SeleniumBase/blob/2036a7b9b4218daffb8a7106481134c6529ae3cc/seleniumbase/plugins/sb_manager.py#L41

Eg:

```python
from seleniumbase import SB

with SB(uc=True, proxy="server:port") as sb:
    sb.driver.uc_open_with_reconnect(URL)
```

or an authenticated proxy:

```python
from seleniumbase import SB

with SB(uc=True, proxy="user:password@server:port") as sb:
    sb.driver.uc_open_with_reconnect(URL)
```

(You'll need to provide your own proxy settings.)
