### ISSUE TITLE
Could not connect to the CAPTCHA service. Please try again.

### ISSUE THREAD

**Issue by JakobReal-rgb** [seleniumbase/SeleniumBase#2402]
Hello, Im using seleniumbase with uc=True.
The Problem is that I still get detected on a site where i want  a bot to checkout. The message "Could not connect to the CAPTCHA service. Please try again." pops up and im not redirected to the checkout page. Is there a workaround? or some settings I have to add?

**Comment by mdmintz** [comment]
If you need clicks to go undetected, try the UC Mode examples that click undetected:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py
