### ISSUE TITLE
Using multi-proxy on pyinstaller gives an error

### ISSUE THREAD

**Issue by AlexPaiva** [seleniumbase/SeleniumBase#2408]
Without pyinstaller multi-proxy flag on a raw driver works fine, with pyinstaller it gives this error on any chrome opened except the first one:

```
File "selenium\webdriver\common\selenium_manager.py", line 137, in run
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "selenium\webdriver\common\driver_finder.py", line 38, in get_path
  File "selenium\webdriver\common\selenium_manager.py", line 103, in driver_location
  File "selenium\webdriver\common\selenium_manager.py", line 140, in run
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI56922\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI72082\test.py", line 12, in test
    driver = Driver(uc=True, multi_proxy=True, proxy=proxy_lista, external_pdf=True, do_not_track=False, ad_block_on=True, enable_3d_apis=False,
  File "seleniumbase\plugins\driver_manager.py", line 463, in Driver
  File "seleniumbase\core\browser_launcher.py", line 1565, in get_driver
  File "seleniumbase\core\browser_launcher.py", line 3776, in get_local_driver
  File "selenium\webdriver\chrome\webdriver.py", line 45, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 49, in __init__
  File "selenium\webdriver\common\driver_finder.py", line 41, in get_path
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

Basically if I delete the `downloaded_files` folder and run pytest xdist with 1 thread with pyinstaller works fine, as soon as I open a thread with pytest xdist `-n 2` or more than 2 it opens 1 browser fine and the rest give this error. If I don't delete the `downloaded_files` folder after it's creation it won't start any more browsers and give this error. If I delete it, it can open 1 browser fine the rest give the above error. I assume it's a simple path related issue?

**Comment by AlexPaiva** [comment]
Update: it's actually do to the ad_block_on=True flag not multi-proxy, my mistake. Threads with ad_block_on=True on pyinstaller don't start properly and give that error.

**Comment by mdmintz** [comment]
The `ad_block_on=True` is the old way of ad-blocking.
It's been made obsolete by the new CDP system: [SeleniumBase/examples/test_cdp_ad_blocking.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_cdp_ad_blocking.py)

The old way has been kept for backwards-compatibility, but there won't be any more updates to it.
It isn't even configured for Manifest-V3 Chromium extensions, which are replacing Manifest-V2.

If using the old way gives you `pyinstaller` issues, then there's a simple solution: Don't use it.

Also, ``pyinstaller`` is an external program with its own rules and bugs. If using it changes default SeleniumBase behavior, then there's little that I can do about it.

**Comment by AlexPaiva** [comment]
> The `ad_block_on=True` is the old way of ad-blocking. It's been made obsolete by the new CDP system: [SeleniumBase/examples/test_cdp_ad_blocking.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_cdp_ad_blocking.py)
> 
> The old way has been kept for backwards-compatibility, but there won't be any more updates to it. It isn't even configured for Manifest-V3 Chromium extensions, which are replacing Manifest-V2.
> 
> If using the old way gives you `pyinstaller` issues, then there's a simple solution: Don't use it.
> 
> Also, `pyinstaller` is an external program with its own rules and bugs. If using it changes default SeleniumBase behavior, then there's little that I can do about it.

Got it, was using it to test aswell. Pyinstaller is for frozen envs, compatibility for them usually is just a matter of path issues.
