### ISSUE TITLE
Unfortunately, when we open more than one thread of undetected chromedriver, if we quit one, the others will be closed.

### ISSUE THREAD

**Issue by boludoz** [seleniumbase/SeleniumBase#2410]
Unfortunately, when we open more than one thread of undetected chromedriver, if we use  driver.quit(), the others will be closed.

**Comment by boludoz** [comment]
In theory the problem should be in the way it closes, possibly the taskill.

**Comment by mdmintz** [comment]
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785

Only `pytest` multithreading is supported via `pytest-xdist`.

In the `pytest` [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md), the driver is automatically quit at the end of each test. Therefore, if you were calling `driver.quit()` manually, then you probably weren't using UC Mode with `pytest`.

**Comment by boludoz** [comment]
> Duplicate of [#2006 (comment)](https://github.com/seleniumbase/SeleniumBase/issues/2006#issuecomment-1679789785)
> 
> Only `pytest` multithreading is supported via `pytest-xdist`.
> 
> In the `pytest` [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md), the driver is automatically quit at the end of each test. Therefore, if you were calling `driver.quit()` manually, then you probably weren't using UC Mode with `pytest`.

I only need to take data from a protected web and write them down on one without any protection. When using without UC it works correctly. I don’t think it’s a bug, but rather a lack of support for this feature.

**Comment by boludoz** [comment]
Disabling:

```
    "uc_subprocess": False,
    "uc_cdp_events": False
```
Works in UC mode, I guess it will be the same as nothing.
