### ISSUE TITLE
can use chrome profile

### ISSUE THREAD

**Issue by raymomo** [seleniumbase/SeleniumBase#2432]
can i use chrome profile path

**Comment by mdmintz** [comment]
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2331#discussioncomment-7730581

If you need multiple profiles, set a different `user_data_dir` for each one that you want. Only the `Default` profile is supported.

If you're setting the `user_data_dir` while using UC Mode, then make sure you read https://github.com/seleniumbase/SeleniumBase/discussions/2118#discussioncomment-7029201 first. (Don't mix a regular `user_data_dir` with one that is used by UC Mode Chrome, as the two formats are not compatible.)
