### ISSUE TITLE
Improve support for BrowserStack allowing browserName, device, realMobile and os_version to be specified

### ISSUE THREAD

**Issue by dowenb** [seleniumbase/SeleniumBase#244]
Presently desired capabilities are tightly controlled and linked to selected Browser. While this works well for using local WebDrivers, this isn't suitable for BrowserStack, that doesn't support extended Chrome Options, and does require additional desired capabilities not used locally.

In order to make better use of the hosted Selenium Grid provider, BrowserStack, access needs to be given to pass options to desired capabilities.

An example of a basic BrowserStack desired capabilities, where tests would run against a real iPhone 8 plus, running iOS 11 is as follows:

desired_cap = {
 'browserName': 'iPhone',
 'device': 'iPhone 8 Plus',
 'realMobile': 'true',
 'os_version': '11.0'
}

Another example, for running IE8, on Windows 7 with a given resolution:

desired_cap = {
 'browser': 'IE',
 'browser_version': '8.0',
 'os': 'Windows',
 'os_version': '7',
 'resolution': '1024x768'
}

A more comprehensive example - using all the possible options:
desired_cap = {
'os_version' : '7.0',
'device' : 'Samsung Galaxy S8',
'real_mobile' : 'true',
'project' : 'MyProject',
'build' : 'MyBuild1',
'name' : 'TestName',
'browserstack.local' : 'true',
'browserstack.debug' : 'true',
'browserstack.console' : 'warnings',
'browserstack.networkLogs' : 'true',
'browserstack.networkProfile' : '3.5g-hspa-good',
'browserstack.appium_version' : '1.7.1',
'deviceOrientation' : 'landscape'
}
 
More details on how BrowserStack desired capabilities work with Selenium and Python can be found here: https://www.browserstack.com/automate/python

The full "Capabilities generator" https://www.browserstack.com/automate/capabilities

**Comment by mdmintz** [comment]
I'm working on getting all this working for both BrowserStack and Sauce Labs at the same time, so it's taking slightly longer than usual, but will be ready soon.

**Comment by mdmintz** [comment]
https://github.com/seleniumbase/SeleniumBase/pull/247 Merged
https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.17.5

**Comment by dowenb** [comment]
Using --browser=firefox alongside a capabilities file where 'browser' : 'IE' is specified - currently the value from the capabilities takes priority, is this by choice?

**Comment by dowenb** [comment]
Thank you - it appears to desired capabilities are all being passed as expected (when using --browser=remote). This will be very useful.

**Comment by mdmintz** [comment]
I'll probably keep it at the current setting, as people shouldn't be setting the browser to one thing and the capabilities browser to another. It doesn't make sense, and could lead to strange behavior. In most cases, people should just use ``--browser=remote`` and do all their settings in the desired capabilities file when using the feature. But in the case that the need SeleniumBase capabilities, such as when using a proxy server with authentication on Chrome, they should be aware and make sure both browsers match up.

**Comment by mdmintz** [comment]
I'm closing this issue as resolved. All details are in the following ReadMe: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/capabilities/ReadMe.md
