### ISSUE TITLE
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)

### ISSUE THREAD

**Issue by subh-sk** [seleniumbase/SeleniumBase#2443]
> # Prerequisites
> * Similar issues [('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))](https://github.com/robotframework/SeleniumLibrary/issues/1802). But the solution is not helpful.
> 
> # Steps to reproduce issue:
> * This issue is reproducible when the new pop-up window is opened and it closes with a click of a button.
> * Go to the URL and click on a button that opens a new pop-up. This pop-up has a save and cancel button.
> * Click on cancel button which closes that pop-up.
> * Try to do any action on the base page it will throw a protocol issue.
> 
> ## Expected behavior and actual behavior
> Expected behavior: Automation should continue to execute when the pop-up is closed using the cancel button. Actual result: The selenium library hangs on clicking on the cancel button and we cannot perform any other action after that.
> 
> When I follow those steps, I see...
> 
> ## Environment
> Browser: Google Chrome and version 120 Browser driver: Chrome-driver version 120.0.6099.225 (Official Build) (64-bit) (cohort: Stable)  Operating System: Windows 11
> 
> Libraries
> 
> * Selenioumbase
> * Interpreter: Python 3.11

![image](https://github.com/seleniumbase/SeleniumBase/assets/69626287/9682b111-b5dc-479a-a966-6be6459fb2ae)

**Comment by mdmintz** [comment]
Looks like you're trying to call an `ActionChains` method directly, but that method is part of raw Selenium (and not part of SeleniumBase). For the SeleniumBase API, see: [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md).

The `chrome://settings` pages have a lot of Shadow root elements, so you need SeleniumBase `::shadow` selectors to access them, such as in this example:

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class LocaleCodeTests(BaseCase):
    def test_locale_code(self):
        self.open("about:blank")
        locale_code = self.get_locale_code()  # navigator.language
        print("\nYour Browser's Locale Code: %s" % locale_code)
        if self.browser == "chrome" and not self.headless:
            self.open("chrome://settings/languages")
            language_info = self.get_text(
                "settings-ui::shadow "
                "settings-main::shadow "
                "settings-basic-page::shadow "
                "settings-languages-page::shadow "
                "#languagesSection div.start div"
            )
            print("Language info (chrome://settings/languages):")
            print(language_info)
            self.sleep(1)
```

There's a full ReadMe for interacting with Shadow root elements here: [SeleniumBase/help_docs/shadow_dom.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/shadow_dom.md).

If you're not using the latest version of SeleniumBase, you may need to upgrade. For better debugging, I would need to know which version of SeleniumBase you have.

Also, if you're going to paste a stack trace, make sure it includes a SeleniumBase line of code that leads to it. For raw Selenium issues, see https://github.com/SeleniumHQ/selenium/issues
