### ISSUE TITLE
Seleniumbase v4.22.6 Stops wire integration from capturing request responses

### ISSUE THREAD

**Issue by bokicks283** [seleniumbase/SeleniumBase#2446]
I am using SB to create an automated tester for my company. I've noted using v4.22.6 the requests on the selenium wire driver all don't have a response even though the browser shows they do get responses from the server. Reverting to v4.22.5 seems to resolve the issue.

**Comment by mdmintz** [comment]
I'm running this on the latest:

```python
from seleniumbase import Driver

driver = Driver(wire=True, headless=True)
try:
    driver.get("https://wikipedia.org")
    for request in driver.requests:
        print(request.url)
finally:
    driver.quit()
```

Output:

```
https://wikipedia.org/
https://www.wikipedia.org/
https://www.wikipedia.org/portal/wikipedia.org/assets/js/index-9a76191102.js
https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png
https://www.wikipedia.org/portal/wikipedia.org/assets/js/gt-ie9-ce3fe8e88d.js
https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikinews-logo_sister@2x.png
https://www.wikipedia.org/portal/wikipedia.org/assets/img/sprite-8bb90067.svg
```

What do you see?

**Comment by bokicks283** [comment]
I think failing to use wait_for_request form the selenium webdriver was the cause. I used that function and the request returned now has a response. My apllogies.

**Comment by bokicks283** [comment]
Will mention your sample looks at the url of the request and not the response of the request which is the original issue.
Attempt to capture a request response and see if it doesn't equal None. Not sure the requried use of wait_for_request is expected behavior or not.
