### ISSUE TITLE
Could not use "click_and_hold()" and "Release()" as Action_Chain to bypass "Press And Hold" Captcha

### ISSUE THREAD

**Issue by mynguyen95dn** [seleniumbase/SeleniumBase#2463]
I trired to bypass the captcha of walmart but i coudn't find the method to use it!

I really appreciate it if this problem is solved!

Thank you Mdmintz for building this Seleniumbase! 

![capthca walmart](https://github.com/seleniumbase/SeleniumBase/assets/64193337/fd44a6bd-fd6f-4497-9d38-6716512869da)

**Comment by mdmintz** [comment]
Use UC Mode to bypass the CAPTCHA:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.uc_open_with_reconnect("https://walmart.com", "breakpoint")
```

Type `c` and press ENTER in the console to continue from the breakpoint.

Swap `"breakpoint"` with `3` (or more) seconds when you're done experimenting.
