### ISSUE TITLE
Ubuntu 22.04 Desktop always thrown RemoteDisconnected Exception 

### ISSUE THREAD

**Issue by harleyLuke** [seleniumbase/SeleniumBase#2467]
system:Ubuntu 22.04 Desktop
seleniumbase 4.23.2
chrome version：108 and 121
Run example command: pytest test_demo_site.py
FAILED test_demo_site.py::DemoSiteTests::test_demo_site - http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by mdmintz** [comment]
That may be a problem with your network connection or firewall: https://github.com/SeleniumHQ/selenium/issues/8612
(It's not specific to SeleniumBase.)
There's a lot of StackOverflow posts about `Remote end closed connection without response`.
