### ISSUE TITLE
Selenium Base doesn't open Chrome tab in a Ubuntu VM (VMware)

### ISSUE THREAD

**Issue by S2001B** [seleniumbase/SeleniumBase#2477]
I have a problem when i run a script in Ubuntu VM to open a Chrome tab with Selenium Base. I am not sure if the problem is that it defaults to a headless state or it actually doesn't run Chrome properly. This is the script I ran : 

from seleniumbase import Driver

with Driver(uc=True) as driver:
    driver.get("https://www.example.com") 
    driver.sleep(5)

When I run the script and open my System Monitor in Ubuntu in my VM, I can see that Chrome starts running in the background, and it indeed stops working after the script is finished. 

When I run the same script in Windows, it works perfectly and the Chrome tab is visible. Could anyone please tell my why is that.  

My Ubuntu is the newest LTS version and I use the latest Chrome version. I am also using the latest VMware version.

**Comment by mdmintz** [comment]
If you're using the `Driver()` format on a machine with no display, then use https://github.com/mdmintz/sbVirtualDisplay for `Xvfb` activation (to have a virtual display).

Example:

```python
from sbvirtualdisplay import Display
from seleniumbase import Driver

display = Display(visible=0, size=(1440, 1880))
display.start()

driver = Driver(uc=True)
driver.get("https://www.example.com/")
# ...
driver.quit()

display.stop()
```

`headless` mode is also the default mode on Linux. Use `--headed`/`headed=True` to override.

Most [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) activate `Xvfb` by default on Linux systems, but not the `Driver()` format since it doesn't have all the `BaseCase` methods that most formats have.

With the following code, `Xvfb` is automatically activated on Linux systems when the driver is launched:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.get("https://www.example.com/")
```

**Comment by amitbidlan** [comment]
Hi @mdmintz  Thankyou very much for your continued support. 
Issue 1:

I'm facing an issue with my SeleniumBase code. I have around 50,000 test cases, and I'm using multithreading with semaphore to lower the queue and put less stress on the Google Cloud VM. It works fine for 10-12 cases but throws the following error:

`selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: DevToolsActivePort file doesn't exist 
Host info: host: '9b59bfec7391', ip: '172.18.0.3'
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-28-cloud-amd64', java.version: '17.0.11'
Driver info: driver.version: unknown
...
`

I have concurrency of 5 chromes in selenium-grid.

Is there any way to handle a larger number of test cases without crashing?

Issue 2:

Is there a way to keep the browser open using SeleniumBase as a Python Context Manager (with detach=True option) without overriding Selenium drivers? I want to avoid overriding drivers of Selenium.

Please help me out: Here is my code, 

from seleniumbase import BaseCase
from seleniumbase import config as sb_config
import mysql.connector
import time
from save_error_to_file import save_error_to_file
from save_deleted_logs import save_deletedlogs_to_file
import datetime
from english_translate import scrape_jobs
import logging
import asyncio
import threading
from concurrent.futures import ThreadPoolExecutor
limiter = threading.BoundedSemaphore(20)
# Maximum number of connection attempts
MAX_CONNECTION_ATTEMPTS = 3

async def establish_connection():
    attempts = 0
    while attempts < MAX_CONNECTION_ATTEMPTS:
        try:
            # Establish MySQL connection
            connection = mysql.connector.connect(
                host="",
                user="root",
                password="",
                database="" 
            )
            return connection
        except mysql.connector.Error as err:
            print(f"Error occurred while connecting to MySQL: {err}")
            print("Connection attempt failed. Retrying in 5 seconds...")
            await asyncio.sleep(5)
            attempts += 1
    print("Maximum connection attempts reached. Unable to establish connection.")
    return None

async def main():
    # Establish the MySQL connection asynchronously
    connection = await establish_connection()

    if connection and connection.is_connected():
        cursor = connection.cursor()
        query = "SELECT * FROM listed_jobs LIMIT 600"
        cursor.execute(query)
        results = cursor.fetchall()
        loop = asyncio.get_running_loop()
        with ThreadPoolExecutor(max_workers=10) as executor:
            
            i = 0
            for row in results:
                limiter.acquire()
                i+=1
                select_query = """
                    SELECT COUNT(*)
                    FROM english_translated_jobs
                    WHERE end_point = %s
                """
                cursor.execute(select_query, (row[5],))
                result = cursor.fetchone()[0]
                url = "https://townwork-net.translate.goog" + row[5] + "?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp"
                print(f"url processing: {i}")
                if result == 0:
                    # Execute scraping task and await it
                    **loop.run_in_executor(executor, scrape_jobs, url, row[5],i)** **Here is scraping being done**
                    limiter.release()
                else:
                    print(f"Skipping {url} alread exists.....")
                    limiter.release()
    else:
        print("Error: Unable to establish connection to MySQL.")

# Run the main function asynchronously
asyncio.run(main())


**My scraping class**

from seleniumbase import BaseCase
from seleniumbase import SB
import asyncio
import logging
from time import sleep
import sys
import threading
from flask import Flask, jsonify
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import NoSuchElementException
from remove_unwanted_lines import remove_unwanted_newlines
import datetime
import mysql.connector
from mysql.connector import Error
import re
#limiter = threading.BoundedSemaphore(10)
log_lock = threading.Lock()
sys.argv.append("-n")




def scrape_jobs(url,end_point,i):
    #limiter.acquire()
    with SB(undetectable=True,locale_code="en",servername="http://192.168.151.73:4444/wd/hub", enable_3d_apis=False, headless=True,demo=True,do_not_track=True) as sb:
        sb.open(url)
        isError = sb.find_elements(By.CSS_SELECTOR,".error-contents-wrap")
        
        if len(isError)==0:
            try:
                
                blue_button = sb.find_elements(By.CSS_SELECTOR, ".detail-ft-btn-lst-box-wrap .jsc-btn-active-simple")
                different_blue_button = sb.find_elements(By.CSS_SELECTOR,".detail-ft-btn-lst-box-wrap .grd-blue-new")
                #print("diffb",len(different_blue_button))
                #print("normalb",len(blue_button))
                #expired_button = sb.find_elements(By.CSS_SELECTOR,".detail-ft-btn-lst-box-wrap .btn-wrap")
                if len(blue_button)==0 and len(different_blue_button)==0:
                    print("Application period expired")
                    save_deletedlogs_to_file(url, end_point)
                    print("Logs entered in log file")
                    deleted_log_file = "deleted_log.txt"
                    line_count = count_lines_in_file(deleted_log_file,log_lock)
                    print(f"Number of deleted lines from table in '{deleted_log_file}': {line_count}")

                    #delete_endpoint_from_table(end_point)
                else:
                    job_details_map = []
                    html_dom = sb.get_page_source()
                    #soup = BeautifulSoup(html_dom,'html.parser')
                    phone_number = extract_phone_number(html_dom)
                    if phone_number:
                        job_details_map.append({"phone_number":phone_number})
                    sb.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            
                    element_scroll = sb.find_element(".job-detail-ttl-wrap")
                    time.sleep(1)
                    sb.execute_script("arguments[0].scrollIntoView({ behavior: 'auto', block: 'center', inline: 'center' });", element_scroll)
                    sb.execute_script("window.scrollTo(0, document.body.scrollHeight);")
                    element_scroll = sb.find_element(".contents-main-wrap")
                    sb.execute_script("arguments[0].scrollIntoView({ behavior: 'auto', block: 'center', inline: 'center' });", element_scroll)
                    
                    time.sleep(1)
                    sb.execute_script("window.scrollTo(0, 0);")
                    time.sleep(1)
                    company_name = sb.find_element(By.CSS_SELECTOR,".job-detail-box-wrap .job-detail-ttl-wrap").text
                    job_detail_caption = sb.find_elements(By.CSS_SELECTOR,".job-detail-box-wrap .job-detail-caption-c")
                    job_detail_text =  sb.find_elements(By.CSS_SELECTOR,".job-detail-box-wrap .job-detail-txt")
                    if company_name:
                        job_details_map.append({"company_name":company_name})
                    if job_detail_caption:
                        job_details_map.append({"job_detail_caption":job_detail_caption[0].text})
                    if job_detail_text:
                        job_details_map.append({"job_detail_text":job_detail_text[0].text})
                    
                    job_detail_elements = sb.find_elements(By.CSS_SELECTOR, ".job-detail-tbl-wrap .job-ditail-tbl-inner")
                    
                    for detail_element in job_detail_elements:
                        # Extract the text of the dt and dd elements
                        dt_text = detail_element.find_element(By.TAG_NAME, "dt").text.strip()
                        dt_text = remove_unwanted_newlines(dt_text)
                        dd_text = detail_element.find_element(By.TAG_NAME, "dd").text.strip()
                        dd_text = remove_unwanted_newlines(dd_text)
                        # Store the extracted data in the dictionary
                        #job_details_map[dt_text] = dd_text
                        job_details_map.append({dt_text:dd_text})
                        #print(dt_text)
                    #print()
                    merit_elements = sb.find_elements(By.CSS_SELECTOR, ".job-detail-merit-inner li")
                    merit_texts = []
                    if merit_elements:
                        for merit_element in merit_elements:
                            if merit_element.text.strip()!="":
                                merit_texts.append(merit_element.text.strip())
                                #print(merit_texts)
                        merit_text = ", ".join(merit_texts)
                        job_details_map.append({"merit_text":merit_text})

                    detail_elements = sb.find_elements(By.CSS_SELECTOR, ".job-detail-box-data dl")
                    for detail_element in detail_elements:
                        dt_text = detail_element.find_element(By.TAG_NAME, "dt").text.strip()
                        dd_text = detail_element.find_element(By.TAG_NAME, "dd").text.strip()
                        dd_text = remove_unwanted_newlines(dd_text)
                        #print(dt_text)
                        job_details_map.append({dt_text:dd_text})

                    map_link = sb.find_elements(By.CLASS_NAME, "ico-flag")
                    
                    if map_link:
                        lat = map_link[0].get_attribute("data-lat")
                        long = map_link[0].get_attribute("data-lon")
                        if lat:
                            job_details_map.append({"lat":lat})
                        if long:
                            job_details_map.append({"long":long})

                    #phone_element = sb.find_elements(By.CLASS_NAME, "detail-tel-num")
                    
                    #if phone_element:
                    #    button = sb.find_element(By.CSS_SELECTOR, ".btn-wrap.jsc-phone-popup-wrapper")
                    #    button.click()
                    #    time.sleep(2)
                    #    phone_number_element = sb.find_element(By.CSS_SELECTOR, ".detail-tel-num")
                    #    phone_number = phone_number_element.text.strip()
                    #    job_details_map.append({"phone_number":phone_number})
                    #    #print(phone_number)

                    image_element = sb.find_elements(By.CSS_SELECTOR, ".job-detail-img img")
                    if image_element:
                        image_url = image_element[0].get_attribute("src")
                        job_details_map.append({"image_url":image_url})
                        print("Image URL:", image_url)

                    slideshow_thumbs = sb.find_elements(By.CSS_SELECTOR,".slideshow-thumb")
                    if slideshow_thumbs:
                        # Get the first slideshow-thumb element
                        slideshow_thumb = slideshow_thumbs[0]
                        extra_image_links = []
                        # Find all elements with class "jsc-thumb-link" within the slideshow-thumb element
                        image_ele1 = slideshow_thumb.find_elements(By.XPATH,"/html/body/div[1]/div[3]/div/div[1]/div[2]/div[2]/div[1]/div[2]/ul/li[1]/a/img")
                        if image_ele1:
                            image_link1 = image_ele1[0].get_attribute("src")
                            if image_link1:
                                extra_image_links.append(image_link1)
                        image_ele2 = slideshow_thumb.find_elements(By.XPATH,"/html/body/div[1]/div[3]/div/div[1]/div[2]/div[2]/div[1]/div[2]/ul/li[2]/a/img")
                        if image_ele2:
                            image_link2 = image_ele2[0].get_attribute("src")
                            if image_link2:
                                extra_image_links.append(image_link2)
                        image_ele3 = slideshow_thumb.find_elements(By.XPATH,"/html/body/div[1]/div[3]/div/div[1]/div[2]/div[2]/div[1]/div[2]/ul/li[3]/a/img")
                        if image_ele3:
                            image_link3 = image_ele3[0].get_attribute("src")
                            if image_link3:
                                extra_image_links.append(image_link3)

                        if len(extra_image_links)!=0:
                            job_details_map.append({"extra_images":extra_image_links})
                            
                    print(f"Printing job no: {i}   ----------->   ",job_details_map)
                    post_data_if_not_exists(end_point,str(job_details_map))
                    print("Job Posted successfully")
                    #limiter.release()
                
            except NoSuchElementException as e:
                print("Element do not exists error")
                save_error_to_file(str(e),url)
                deleted_log_file = "error_log.txt"
                line_count = count_lines_in_file(deleted_log_file,log_lock)
                print(f"Number of error lines in '{deleted_log_file}': {line_count}")
                #limiter.release()
                sleep(5)
                #scrape_jobs(url,end_point)
                


        else:
            print("delete the data from table:",url)
            delete_endpoint_from_table(end_point)
            save_deletedlogs_to_file(end_point,url)

Please Help me out. Thank you.

**Comment by mdmintz** [comment]
@amitbidlan The `DevToolsActivePort` issue is resolved by using proper Linux configuration: https://stackoverflow.com/a/50642913/7058266 (It's not specific to SeleniumBase).

Not sure what you're using for the multithreading, but only `pytest` can properly handle all that.
Eg. `pytest -n8` (assuming your system has at least 8 cores).

For the `detach` alternative, see this thread: https://github.com/seleniumbase/SeleniumBase/issues/1814

**Comment by amitbidlan** [comment]
@mdmintz Hi , Thank you for reply and time. I have gone through the StackOverflow post. The problem I am facing is how to add chrome options in 
`with SB(undetectable=True,locale_code="en", enable_3d_apis=False, headless=True,demo=True,do_not_track=True,) as sb:` to disbale sandbox, I am calling this class using Flask app. If I try to structure the code according to this one: 
`class OverrideDriverTest(BaseCase):

    def get_new_driver(self, *args, **kwargs):
        """ This method overrides get_new_driver() from BaseCase. """
        options = webdriver.ChromeOptions()
        options.add_experimental_option(
            "excludeSwitches", ["enable-automation"]
        )
        options.add_experimental_option("useAutomationExtension", False)
        
        return webdriver.Chrome(options=options)

    def test_simple(self):
        self.open("https://seleniumbase.io/demo_page")
        self.assert_text("Demo Page", "h1")`

I get the error: It looks like you are trying to call a SeleniumBase method
 from outside the scope of your test class's `self` object. 

Please suggest how to provide options/arguments with SB(uc=True) format. Thank you.

**Comment by mdmintz** [comment]
Options like that are already included. Eg.

https://github.com/seleniumbase/SeleniumBase/blob/6ae5ee38643ea6eeb9efa95f56a718a9a121f788/seleniumbase/undetected/options.py#L72

https://github.com/seleniumbase/SeleniumBase/blob/6ae5ee38643ea6eeb9efa95f56a718a9a121f788/seleniumbase/core/browser_launcher.py#L866

https://github.com/seleniumbase/SeleniumBase/blob/6ae5ee38643ea6eeb9efa95f56a718a9a121f788/seleniumbase/core/browser_launcher.py#L872

There are lots of default options already set. Search for them first.

For the not-already-included default options, there are args that you can pass into `SB()` on initialization:

https://github.com/seleniumbase/SeleniumBase/blob/6ae5ee38643ea6eeb9efa95f56a718a9a121f788/seleniumbase/plugins/sb_manager.py#L30

Follow the [23 Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) for structuring your tests properly.
