### ISSUE TITLE
struggle with posting a request in uc mode

### ISSUE THREAD

**Issue by dh12306** [seleniumbase/SeleniumBase#2480]
how to send a post request in uc mode?
is there any demo ? @mdmintz 
I had bypassed  the cloudflare,but cant post a request in js
here is my code ,though I send success ,but the result is failed 
meaning I losed something in header I think 
can you give some guides?
```
jsrequest = '''var xhr = new XMLHttpRequest();
                  var data = {'timestamp': %s, 'address': "%s", 'signature': "%s"};
                  var json_str = JSON.stringify(data);
                  xhr.open("POST", "https://blasterswap.com/api/v1/send-wallet", false);
                  xhr.setRequestHeader("Content-type", "application/json, text/plain, */*");
                  xhr.setRequestHeader("Cookie","%s");
                  xhr.setRequestHeader("User-Agent","%s");
                  xhr.send(json_str);
                  return xhr.response;'''% (stamp,addr,siga,new_cook, ua)

  print(" js : ", jsrequest)
  time.sleep(3)
  result = sb.driver.execute_script(jsrequest)
```

**Comment by mdmintz** [comment]
For that, you may want to check out:
* https://stackoverflow.com/a/62142792
* https://stackoverflow.com/a/66448627
* https://stackoverflow.com/a/31303228

With UC Mode, you can make external browser actions undetectable (eg. opening a URL, clicking a button/checkbox, etc).
However, running any kind of script via `sb.driver.execute_script(script)` may reveal Selenium to the website.
