### ISSUE TITLE
Getting "selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer" in Driver(uc=True)

### ISSUE THREAD

**Issue by iamumairayub** [seleniumbase/SeleniumBase#2481]
I am getting `"selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer"` in `Driver(uc=True)`

google search suggests adding `--no-sandbox` and `--disable-dev-shm-usage` but I can see they are already added in [line](https://github.com/seleniumbase/SeleniumBase/blob/77ee5149a34a0bbca17c27a7e745d0754e3ad9e3/seleniumbase/core/browser_launcher.py#L1042)

I am using Python 3.10 with latest SeleniumBase and here is snippet from my code

```
from seleniumbase import Driver
from sbvirtualdisplay import Display
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()

prefs = {"profile.managed_default_content_settings.images": 2}
chrome_options.add_experimental_option("prefs", prefs)

with Display(visible=0, size=(1440, 1880)):

    driver = Driver(
        uc=True, 
        browser='chrome',
        cap_string=chrome_options.to_capabilities()
    )
    driver.get('https://www.website.com/')

```

**Comment by mdmintz** [comment]
`cap_string` can only be used when connecting to Selenium Grids that support it:
(And UC Mode won't work on a Selenium Grid)

https://github.com/seleniumbase/SeleniumBase/blob/77ee5149a34a0bbca17c27a7e745d0754e3ad9e3/seleniumbase/plugins/sb_manager.py#L47

There's already an option to block images: `block_images`:

https://github.com/seleniumbase/SeleniumBase/blob/77ee5149a34a0bbca17c27a7e745d0754e3ad9e3/seleniumbase/core/browser_launcher.py#L814

The `SB()` format might help solve your issue: (https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_21)
It has extra code for handling those situations.

----

Duplicate info here: https://github.com/seleniumbase/SeleniumBase/issues/2334#issuecomment-1837498871

**Comment by iamumairayub** [comment]
@mdmintz sorry for confusing you.

My basic was not to disable images, it was actually to get your suggestion why the `selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer` error is happening?

**Comment by mdmintz** [comment]
That's usually related to Chrome trying to display something in a headless environment such as Linux. Maybe try something from https://github.com/seleniumbase/SeleniumBase/discussions/2426#discussioncomment-8112765 - The `SB(uc=True)` format may be more useful that the `Driver(uc=True)` format in this case.

**Comment by mdmintz** [comment]
Try upgrading the version of Chrome on your machine. Looks like it was something that appeared for uses on Chromium 119 and Chromium 120 (Chrome and Edge), but not on newer versions: https://github.com/MicrosoftEdge/EdgeWebDriver/issues/126
(This issue is not specific to SeleniumBase.)

**Comment by iamumairayub** [comment]
@mdmintz just did, but issue still persists.

**Comment by iamumairayub** [comment]
@mdmintz how do set xvfb window size?

```
with SB( uc=True, xvfb=True, browser='chrome', ) as sb:
    pass
```

I used to do it with `Driver` like this

`with Display(visible=0, size=(1600, 900))`

**Comment by mdmintz** [comment]
With `SB()` and `BaseCase`, Xvfb is automatically used as needed. Default width: 1440 Default height: 1880

**Comment by iamumairayub** [comment]
@mdmintz I understand its not a Python or SB issue. But you have any suggestions for me to fix this?
I am running Google Chrome 120.0.6099.224
I saw your above linked [github issue](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/126) but that guy says upgrading chrome didnt solve issue https://github.com/MicrosoftEdge/EdgeWebDriver/issues/126#issuecomment-1960869033

**Comment by iamumairayub** [comment]
One hint is that I have more instances of this script running on server, could that cause some issue with xvfb or something?

**Comment by AngeloParra** [comment]
any solution to the problem? @iamumairayub
