### ISSUE TITLE
chromedriver downloads started failing: `"zipfile.BadZipFile: File is not a zip file"`

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2495]
### chromedriver downloads started failing: `"zipfile.BadZipFile: File is not a zip file"`

----

The Chromedriver team changed how `chromedriver` is packaged. Now `chromedriver` downloads are failing. Not yet sure if this is a mistake they made somewhere, or if this new packaging system is here to stay. I'm investigating. I'll ship a new release today to make things work.

Here's the error output that people may be seeing:

```
sbase get chromedriver

*** chromedriver to download = 121.0.6167.184 (Latest Stable) 

Downloading chromedriver-mac-arm64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip ...
Download Complete!


* Unable to download driver! Retrying in 3s...


*** chromedriver to download = 121.0.6167.184 (Latest Stable) 

Downloading chromedriver-mac-arm64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip ...
Download Complete!

** Unable to download driver! Retrying in 5s...


*** chromedriver to download = 121.0.6167.184 (Latest Stable) 

Downloading chromedriver-mac-arm64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/mac-arm64/chromedriver-mac-arm64.zip ...
Download Complete!

Traceback (most recent call last):
  File "/Users/michael/.virtualenvs/sbase12/bin/sbase", line 33, in <module>
    sys.exit(load_entry_point('seleniumbase', 'console_scripts', 'sbase')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/run.py", line 1019, in main
    sb_install.main()
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/sb_install.py", line 848, in main
    zip_ref = zipfile.ZipFile(zip_file_path, "r")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Failed CI:
* https://github.com/mdmintz/seleniumbase-examples/actions/runs/7915904996
* https://github.com/mdmintz/coffee-cart-testing/actions/runs/7916632023
* https://github.com/mdmintz/sails-demo-app/actions/runs/7916729126

**Comment by mdmintz** [comment]
I haven't done anything yet, but it looks like things are getting resolved on their own:

* https://github.com/mdmintz/seleniumbase-examples/actions/runs/7917434991
* https://github.com/mdmintz/coffee-cart-testing/actions/runs/7917447465
* https://github.com/mdmintz/sails-demo-app/actions/runs/7917540227

I guess the Chromedriver team found the issue and fixed it themselves.

No changes are needed here at this time.

Canceling Red Alert status.

**Comment by mdmintz** [comment]
After reading https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1743#issuecomment-1945971109, it appears that `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/` may be changing to `https://storage.googleapis.com/chrome-for-testing-public/` for Chrome 121 and newer versions.

The likely story here is that the Chromedriver team wanted to change the link, but didn't realize that a lot of people's downloads would be affected by it, so they changed it back quickly to work on both of the storage URLs for Chrome 121.

**Comment by Alexei17** [comment]
Fried my brains out on this one, it's still giving the same error for me. Installed manually

**Comment by mdmintz** [comment]
It's been fixed in the latest version of SeleniumBase because the Chromedriver team is probably going to make the switch to the new format permanently: https://github.com/seleniumbase/SeleniumBase/issues/2497

**Comment by mdmintz** [comment]
I found the origin of this issue: https://github.com/GoogleChromeLabs/chrome-for-testing/pull/108

It looks like: `"Until all existing assets are migrated to the new storage bucket, we have to keep using the legacy URL format for older assets."` I think that means that the download locations of chromedriver 115 through 120 will also be switching to the new format soon, and then removed from the older format. I'll need to make another update for that, because the update in https://github.com/seleniumbase/SeleniumBase/issues/2497 only changes the location to the newer format for chromedriver 121 and newer. (People may still need to download the older drivers.)

**Comment by mdmintz** [comment]
All chromedriver downloads now use the updated format, as completed in https://github.com/seleniumbase/SeleniumBase/issues/2519.

It's safe to cancel Red Alert status again...

![cancel_red_alert2](https://github.com/seleniumbase/SeleniumBase/assets/6788579/af3396f7-a019-43bf-a137-4fdcb51a4d85)

https://github.com/seleniumbase/SeleniumBase/assets/6788579/d7cecf2a-be55-49e5-9f2e-1e826a984a11
