### ISSUE TITLE
Automation Script is triggering "slider" captcha using uc mode and proxy

### ISSUE THREAD

**Issue by cohnhead66** [seleniumbase/SeleniumBase#2502]
I had a working automation script using standard selenium that was working for some time until the target web site was upgraded causing my automation to trigger a slider Captcha.  
![image](https://github.com/seleniumbase/SeleniumBase/assets/60977702/aed4eb96-1762-4fa4-abeb-ffe1f967d5d7)
even if I solve it manually, it still throws a block.
![image](https://github.com/seleniumbase/SeleniumBase/assets/60977702/f88579e9-8e88-4e14-9d90-b9a2ff5a30a1)

I transitioned script to seleniumbase, using uc mode and proxy with authorization with the same results as I was getting with standard selenium. I am able to login and navigate as necessary until i get to the page where the captcha kicks in.  Proxy is definitely working because every time i run script it reports a different ip.

Here is code:

from seleniumbase import Driver
driver = Driver(uc=True, proxy=proxy, undetectable=True, )
driver.uc_open_with_reconnect(webSite, reconnect_time=10)
driver.sleep(10)
driver.type("#lgUserName", memberNumber)
driver.type("#lgPassword", password+"\n")
driver.click("#hovDiv")
driver.sleep(5)
driver.click('a:contains('+memberName+')')
driver.sleep(5)
timer = driver.get_text('#tt1_left > p > span.serverClock > span > b',by="css selector")
print(timer)
**driver.click('a:contains("21")')  ### this triggers Captcha**
driver.sleep(5)
input()
driver.quit()

Any help is appreciated.  I think i am going to love using Seleniumbase if I can get a solution
I can share web site and log in credentials as needed to help solve.

**Comment by mdmintz** [comment]
If you need clicks to go undetected, try the UC Mode examples that click undetected:
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_turnstile.py
* https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_form_turnstile.py

That means you'll **definitely** need to use:

```python
driver.uc_click(selector)
```

And **maybe** you'll need to use:

```python
driver.reconnect(timeout)
```

Full UC Mode special method list:

```python
driver.uc_open_with_tab(url)
driver.uc_open_with_reconnect(url, reconnect_time=None)
driver.reconnect(timeout)
driver.uc_click(selector)
driver.uc_switch_to_frame(frame)
```

UC Mode docs: [SeleniumBase/help_docs/uc_mode.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md)

Make sure you're not using a proxy address that has already been blacklisted.
(Most of the ones found online on random sites have been.)

For combining UC Mode with manual actions, use "breakpoint" for the value of `reconnect_time`.
(More on that here: https://github.com/seleniumbase/SeleniumBase/issues/2383#issuecomment-1868216485 and https://github.com/seleniumbase/SeleniumBase/issues/2384)

**Comment by mdmintz** [comment]
Use `driver.reconnect(timeout)` when you need to hide any trace of Selenium in the browser, usually after you perform actions if you haven't yet been detected.

A simple test would be:

```python
driver.uc_open_with_reconnect(URL, "breakpoint")
```

Then perform manual actions while in the breakpoint and see if you were detected. If you weren't, then you know there's a way if you set the timings correctly and use `uc_click()` as needed. Type `c` and press `ENTER` to continue from the breakpoint.

**Comment by jkoestner** [comment]
@cohnhead66 did you ver figure this out?

**Comment by cohnhead66** [comment]
Not really.  I believe the Captcha is triggered by using Chromium browser as opposed to Chrome.  I found a Chrome extension for automation that didn't trigger the captcha and i am using that for now.  Not nearly as flexible as a selenium solution, but it is working.

**Comment by vermaisrahul** [comment]
@cohnhead66 Please tell the solution and name the extension and your approach. I a facing same problem with datadome

**Comment by mdmintz** [comment]
See the examples for bypassing Datadome-protected sites with [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md):
* [examples/cdp_mode/raw_bestwestern.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/raw_bestwestern.py)
* [examples/cdp_mode/raw_priceline.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/raw_priceline.py)

**Comment by cohnhead66** [comment]
CDP Mode is working for me and not triggering the captcha using a Windows machine without proxy.  I have yet to try using linux as that is my preferred environment, but never was able to get past captcha in linux with UC Mode.

**Comment by mdmintz** [comment]
On Linux, **don't** use headless mode. **Use `xvfb=True` instead.**
Also, GitHub Actions runs on residential IPs, so use that if you're blocked via IP Address.

**Comment by vermaisrahul** [comment]
@mdmintz Great Fan of yours, you have saved me a lot in last few days. Can we implement cdp in normal driver mode 
like 
driver = Driver(uc=True)

**Comment by mdmintz** [comment]
`Driver()` is for WebDriver. CDP Mode doesn't use WebDriver at all.

**Comment by Matloob-20** [comment]
@mdmintz Great man, Can you please provide guidance for me? Our Selenium-based web scraping script encounters login, email verification, and a slide captcha on the target website. Even after manually solving the captcha and capturing the resulting session, it expires quickly, requiring repeated manual intervention.

**Comment by prashant-italiya** [comment]
Try this dude it has 100% accuracy. 
https://github.com/prashant-italiya/Slider-Captcha-Automation
