### ISSUE TITLE
How to run a sb driver with a proxy without proxy_user and proxy_password ？

### ISSUE THREAD

**Issue by dh12306** [seleniumbase/SeleniumBase#2504]
hello,I have a problem with proxy:
my proxy solver gave me just the ip:port, and add my ip in their server whitelist;
so I want to run a driver in using the arg "proxy-bypass-list "
,first I set 
```
chrome_options.add_argument("--proxy-server=http://%s" % proxy_string)
the real is : --proxy-server=http://43.152.113.72:15362
```
second , I add the bypass, for example,this website:https://ipinfo.io/
,but it failed in the end 
```

proxy_bypass_list = 'https://ipinfo.io/'
if proxy_bypass_list:
    chrome_options.add_argument(
        "--proxy-bypass-list=%s" % proxy_bypass_list
    )
```
it still need to authorize in user and password like this ,can you give some advices ? @mdmintz ,thanks:
![image](https://github.com/seleniumbase/SeleniumBase/assets/20471681/79b894ba-3149-4d97-8d96-513cbb6838f6)

**Comment by mdmintz** [comment]
Hello. Use the built-in args for that. Example:

```python
from seleniumbase import Driver

driver = Driver(
    proxy="43.152.113.72:15362",
    proxy_bypass_list="*ipinfo.io*",
)
try:
    driver.open("https://ipinfo.io")
    driver.sleep(5)
finally:
    driver.quit()
```
