### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by Roboxkin** [seleniumbase/SeleniumBase#2513]
I still don’t understand how the elementary conditions are met (if this is even possible)

if (element){
    we are doing something
} else {
   Close browser
}

Is it realistic to make working conditions at all?

**Comment by mdmintz** [comment]
SeleniumBase has a large number of flow-of-control methods, such as:

```python
self.is_element_present(selector)
self.is_element_visible(selector)
self.is_element_clickable(selector)
self.is_element_enabled(selector)
self.is_text_visible(text, selector="html")
self.is_exact_text_visible(text, selector="html")
self.is_non_empty_text_visible(selector="html")
self.is_attribute_present(selector, attribute, value=None)
self.is_link_text_visible(link_text)
self.is_partial_link_text_visible(partial_link_text)
self.is_link_text_present(link_text)
self.is_partial_link_text_present(link_text)
```

In a test, that could look like this:

```python
if self.is_element_visible("button.primary"):
    pass  # Do Something Useful
else:
    pass  # Do Something Else
```

There are also special combo methods that include both flow-of-control and an action:

```python
self.click_if_visible(selector)
self.check_if_unchecked(selector)
self.uncheck_if_checked(selector)
self.open_if_not_url(url)
self.js_click_if_present(selector)
self.js_click_if_visible(selector)
```

The browser is closed automatically at the end of tests, so you don't need to think about that.

See [help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) for all methods.

**Comment by Roboxkin** [comment]
Thank you very much for such a detailed example.
