### ISSUE TITLE
It doesnt work with websites with nested elements and no id on the tags...

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2515]
Hello

I am trying to do an example with iryo, but as far as I see i cannot get any element... what am i doing wrong?

```
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

 class MyTestClass(BaseCase):
     def test_swag_labs(self):
         self.open("https://iryo.eu/es/home")
         self.click('span:contains(" Aceptar todas ")')
         # self.click('#ilsa-cookies-cta > div.ilsa-cookies-cta__buttons > ilsa-button:nth-child(1) > div > button > span:contains(" Aceptar todas ")')
         self.click('span:contains("Solo ida")')
```

Thank you!

**Comment by mdmintz** [comment]
Your selectors are incorrect. Use this script to get through the first screen:

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class TrainRideTests(BaseCase):
    def test_train_ride(self):
        self.open("https://iryo.eu/es/home")
        self.click('button span:contains("Aceptar todas")')
        self.sleep(1)
        self.click('[data-qa="ilsa-main-search-radio-outbound-container"]')
        self.click('[data-qa="ilsa-main-search-radio-forLeisure-container"]')
        self.sleep(1)
        self.click('[data-qa="ilsa-main-search-select-route-dropdown-origin-button"]')
        self.sleep(1)
        self.click('span:contains("Barcelona")')
        self.sleep(1)
        self.click('[data-qa="ilsa-main-search-select-route-dropdown-destination-button"]')
        self.sleep(1)
        self.click('span:contains("Madrid")')
        self.sleep(1)
        self.click('[data-qa="ilsa-main-search-datepicker__button"]')
        self.sleep(2)
        self.click('.ilsa-datepicker__monthdays-item--todayHighlighted')
        self.sleep(1)
        self.click('.ilsa-datepicker__monthdays-item span:contains("31")')
        self.sleep(1)
        self.click('button span:contains("BUSCAR")')

        breakpoint()
```

**Comment by manel00** [comment]
Hello!

Excuse me sir, but it is detecting me Cloudflare...

![image](https://github.com/seleniumbase/SeleniumBase/assets/8410687/ae1615bd-3f47-4485-877f-46b183549fda)

How could you bypass it?

I've tried with uc-chromedriver as well and no luck...

**Comment by manel00** [comment]
Sorry It gives me an error this command, can you be more explicit please?

**Comment by mdmintz** [comment]
Make sure you have correctly copy/pasted the code above. If you see an error, you need to be more specific. (Eg. Line numbers / stack traces.)

**Comment by manel00** [comment]
I am executing "pytest --uc" on a Dockerfile and then a docker-compose executes it, the result is:

![image](https://github.com/seleniumbase/SeleniumBase/assets/8410687/d7e4c0a1-9114-479a-b223-494b8469848b)

Im not sure i got your idea... I am a little bit lost to see if it works

**Comment by mdmintz** [comment]
I see a few things:
* Your version of `seleniumbase` in that Dockerfile is from May 2023. Upgrade to the latest version.
* It doesn't look like you correctly ran a test (`pytest` collection shows `no tests ran`)

Be sure to properly format your tests based on [help_docs/syntax_formats.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md).

**Comment by manel00** [comment]
aaah ok! now i see... thank you first time I see this... anyway... i am having an error here

![image](https://github.com/seleniumbase/SeleniumBase/assets/8410687/dfa70f59-ffef-400a-a067-b34a6d5baf8b)

Did you achieve it? because i tried multiple things and still it is not going on...

**Comment by mdmintz** [comment]
Maybe adjust timing. Do you have a screenshot of that page when the error occurs? My script at the top worked for me.

**Comment by manel00** [comment]
Thank you so much! i could make it! (I just change it for the input and insert a date for the example)

You are a master on it! i appreciate it

Have a nice day! you won a follower!

**Comment by mdmintz** [comment]
GitHub Stars are good too. ⭐
