### ISSUE TITLE
Is it possible to use Seleniumbase, not as a test way?

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2526]
Hello!

Basically I am curious how to use it as a normal code instead of doing tests, thank you!

Regards

**Comment by mdmintz** [comment]
Hello! Expanding on https://github.com/seleniumbase/SeleniumBase/issues/581#issuecomment-1694519229, there are [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) such as [Syntax Format 21](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_21) where you can use SeleniumBase without `pytest`. (Non-test scripts that run with pure `python`)

Eg:

```python
from seleniumbase import SB

with SB() as sb:
    sb.open("seleniumbase.io/simple/login")
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.click('a:contains("Sign in")')
    sb.assert_exact_text("Welcome!", "h1")
    sb.assert_element("img#image1")
    sb.highlight("#image1")
    sb.click_link("Sign out")
    sb.assert_text("signed out", "#top_message")
```

or

```python
from seleniumbase import Driver

driver = Driver()
try:
    driver.open("seleniumbase.io/simple/login")
    driver.type("#username", "demo_user")
    driver.type("#password", "secret_pass")
    driver.click('a:contains("Sign in")')
    driver.assert_exact_text("Welcome!", "h1")
    driver.assert_element("img#image1")
    driver.highlight("#image1")
    driver.click_link("Sign out")
    driver.assert_text("signed out", "#top_message")
finally:
    driver.quit()
```

For more, look into the [SeleniumBase/examples](https://github.com/seleniumbase/SeleniumBase/tree/master/examples) folder and find files that start with `raw_`.

**Comment by manel00** [comment]
Omg, thank you sir, very kind! i was checking and couldnt find nothing...

**Comment by manel00** [comment]
Excuse me sir, what is the problem with this? Cannot find it

`if not driver.undetectable:
        driver.get_new_driver(undetectable=True)`

`Traceback (most recent call last):
  File "app/mtest.py", line 99, in <module>
    if not driver.undetectable:
AttributeError: 'WebDriver' object has no attribute 'undetectable'`

**Comment by mdmintz** [comment]
For UC Mode: (example)

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.driver.get("https://nowsecure.nl/#relax")
```

**Comment by manel00** [comment]
I am curious... can happen that after some retries... the website already catch you and you cannot bypass the Cloudflare

**Comment by mdmintz** [comment]
Websites can blacklist/block IP Addresses that hit a website too many times. Same thing could happen if a regular user hits a website that many times. Don't overdo the automation to avoid getting blocked by websites.

Or, you might be getting detected because you're not waiting long enough to pass the Turnstile page. Use:

```python
driver.uc_open_with_reconnect(url, reconnect_time=5)
```

Increase the `reconnect_time` as needed.
