### ISSUE TITLE
select_option_by_text equivalent for SB?

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2527]
Hello,

I am struggling to find documentation for SB instead of for testing, would you mind please to give any hint where to find it? thank you

(For example 'select_option_by_text' it doesnt work for SB :( )

Thank you!

**Comment by mdmintz** [comment]
All methods in [help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md) are supported with the `SB()`/`sb` syntax format:

```python
from seleniumbase import SB

with SB() as sb:
    sb.open("https://seleniumbase.io/demo_page")
    sb.activate_demo_mode()

    # Verify that a "select" option updates a meter bar
    sb.assert_element('meter[value="0.25"]')
    sb.select_option_by_text("#mySelect", "Set to 75%")
    sb.assert_element('meter[value="0.75"]')
```

**Comment by manel00** [comment]
I am curious... how can you use sb.open... and I have to use sb.driver.open(XXX) with the same code as yours... thank you!

**Comment by mdmintz** [comment]
`uc_open_with_reconnect()` is part of the `driver`, and only if `uc=True`.

**Comment by MartinCura** [comment]
Hi! Any ideas why i could be getting that erorr when running in docker but not locally?

Error (only in docker container):
```
chatbot-1  | Traceback (most recent call last):
chatbot-1  |   File "/opt/app/quieromudarm/chatbot/bot.py", line 307, in create_search
chatbot-1  |     total_results, posts = provider.get_search_results(search_url, parsed_payload)
chatbot-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatbot-1  |   File "/opt/app/quieromudarm/providers/zonaprop.py", line 186, in get_search_results
chatbot-1  |     sb.driver.uc_open_with_reconnect(url, 3)
chatbot-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatbot-1  | AttributeError: 'WebDriver' object has no attribute 'uc_open_with_reconnect'
```

```python
    with SB(
        uc=True,
        headless2=True,
        disable_js=True,
        servername=cfg.selenium_servername,
        port=cfg.selenium_port,
    ) as sb:
        sb.driver.uc_open_with_reconnect(url, 3)
```

On the host it runs flawlessly 🤔 In both cases i'm connecting to a docker container with image `selenium/standalone-chrome`.

**Comment by mdmintz** [comment]
@MartinCura UC Mode isn’t compatible with Grid use. You set a “servername”, which tells SeleniumBase to use a Selenium Grid.

**Comment by MartinCura** [comment]
> @MartinCura UC Mode isn’t compatible with Grid use. You set a “servername”, which tells SeleniumBase to use a Selenium Grid.

Oh. Any other way you recommend to keep a Selenium "server" is kept running so that it runs faster?

Though weird thing that it did seem to work locally (and fast, so it wasn't doing all the upfront work).

**Comment by mdmintz** [comment]
@MartinCura It’s easy to use a Selenium Grid as long as it’s used separately from UC Mode. Lots of documentation: [Selenium Grid Docs](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/utilities/selenium_grid/ReadMe.md).

**Comment by MartinCura** [comment]
Sorry if i wasn't clear, i meant that using UC mode while connecting to a `selenium/standalone-chrome` docker container seems to work without any problem.

![image](https://github.com/seleniumbase/SeleniumBase/assets/14017665/eef25379-1138-4776-aa12-462ea5afa507)

In any case all i want is to have a running instance of Selenium so that each time i have to request a URL it's snappy, but if i don't use UC i get blocked :( So is there a way to have both of these things together? Really doesn't have to Selenium Grid if there's something like it, a simpler alternative.

In any case, thanks for the help! Learned of this project through your video intro 😄 I'll give the docs another attempt.
