### ISSUE TITLE
Cannot find any information about how to get <ul><li>

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2528]
Hello!

I would like to know please how to get info from dropdowns by text, tried to use this option but it is not working `select_option_by_text` and didnt find any other information... because of doing it not by testing... (would be nice to see where to get like a cheatsheet for the normal code)

e.g:

`<ul role="listbox" id="awesomplete_list_2" hidden=""><li role="option" aria-selected="false" id="awesomplete_list_2_item_0"><mark>XX</li><li role="option" aria-selected="false" id="awesomplete_list_2_item_1"><mark>XXX</li></ul>`

Thank you

**Comment by mdmintz** [comment]
`select_option_by_text()` only works on `<select>` elements.

Example: [SeleniumBase/examples/test_select_options.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_select_options.py)
