### ISSUE TITLE
Verify `selenium` `4.18.1`, and upgrade `seleniumbase` to it

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2530]
## Verify `selenium` `4.18.1`, and upgrade `seleniumbase` to it

https://pypi.org/project/selenium/4.18.1/ is here. Hopefully it's good...

If everything still works with it, upgrade `seleniumbase` to use it.

**Comment by oculunto** [comment]
Hello, 
So installing seleniumbase after selenium 4.18.1 throws the ERROR: 
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seleniumbase 4.23.7 requires selenium==4.17.2; python_version >= "3.8", but you have selenium 4.18.1 which is incompatible.`

And installing seleniumbase after, downgrades selenium to 4.15.2

Am I doing something wrong ?

**Comment by mdmintz** [comment]
@oculunto SeleniumBase pins several dependencies. The current version of seleniumbase (`4.23.7`) currently pins selenium `4.17.2`. `selenium` frequently makes changes that would break `seleniumbase` if the version wasn't pinned.

There's a new version coming very soon, so please be patient.

**Comment by oculunto** [comment]
Ah okay I thought it was already in the latest version I am sorry.
Thank you for your assistance and for your great work, it is very much appreciated !

**Comment by mdmintz** [comment]
This was resolved in `4.24.0` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.24.0
