### ISSUE TITLE
What do I need to do to make the screenshot a screenshot of the assertion failure?

### ISSUE THREAD

**Issue by chenhaijun02** [seleniumbase/SeleniumBase#2540]
Hello,Michael：
Driver2's assertion will fail, and Driver1's assertion will succeed. Why the use case execution fails is not a screenshot of Driver2's assertion failure, but a screenshot of Driver1's assertion success.
What do I need to do to make the screenshot a screenshot of the assertion failure?

`class TestA():
    def test_news(self, login):
   
        BackHomePage().hover(login, BackHomePage.content).hover_click(login, BackHomePage().add_content,
                                                                      BackHomePage().important_news)
        (ImportantNewsPage().create_news(login, news_title="test_news", summary=True, summary_text="test_summary",
                                         news_content="test_body"))
        login.click(BackHomePage.content)

        try:
            driver = login.get_new_driver()

            driver.get("XXXXXXXX")
            driver.maximize_window()

            login.js_click_if_present(HcpConfirmPage.choice_yes)
            login.js_click_if_present(HcpConfirmPage.cookie_accept)
            driver.assert_in("test_bofy", HomePage().get_news(login))
        finally:
            login.switch_to_default_driver()

            ContentList().click_delete_button(login, "test_news").click_delete_dialog(login)
            login.assert_equal("The Important news test_news has been deleted.", CommonPage().get_status_message(login))`
![1709023655128](https://github.com/seleniumbase/SeleniumBase/assets/69953502/048565cd-5a77-4851-ae08-151f0d41b8e0)

**Comment by mdmintz** [comment]
You called `switch_to_default_driver()`, which switches back to the original driver. Before you called that, you never took a screenshot of your "Driver2", which means there wouldn't be a screenshot.

----

Also, with the `BaseCase` format, screenshots for failing tests are automatic:

```python
""" This test fails on purpose to demonstrate
    the logging capabilities of SeleniumBase.
    >>> pytest test_fail.py --html=report.html
    This creates ``report.html`` with details.
    (Also find log files in ``latest_logs/``) """

from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class FailingTests(BaseCase):
    def test_find_army_of_robots_on_xkcd_desert_island(self):
        self.open("https://xkcd.com/731/")
        self.assert_element("div#ARMY_OF_ROBOTS", timeout=1)
```

----

If you want a test to keep going after an assertion fails, there's a Deferred Assert System for that: [examples/test_deferred_asserts.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_deferred_asserts.py)

To save screenshots after each deferred assertion failure, add `fs=True`. Here are the methods for that:

```python
self.deferred_assert_element(selector, by="css selector", timeout=None, fs=False)
self.deferred_assert_element_present(selector, by="css selector", timeout=None, fs=False)
self.deferred_assert_text(text, selector="html", by="css selector", timeout=None, fs=False)
self.deferred_assert_exact_text(text, selector="html", by="css selector", timeout=None, fs=False)
self.deferred_assert_non_empty_text(selector="html", by="css selector", timeout=None, fs=False)
self.deferred_check_window(name="default", level=0, baseline=False, check_domain=True, full_diff=False, fs=False)
self.process_deferred_asserts(print_only=False)
```
