### ISSUE TITLE
How to take a screenshot before it crashes?

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2542]
Hello,

I am trying to get a screenshot when it crashes but i am getting the following error, is there a way to do it?

`Message: Active window was already closed!`

Thank you sir! Great job!

Regards

**Comment by mdmintz** [comment]
With the `BaseCase` format, screenshots for failing tests are automatic:

```python
""" This test fails on purpose to demonstrate
    the logging capabilities of SeleniumBase.
    >>> pytest test_fail.py --html=report.html
    This creates ``report.html`` with details.
    (Also find log files in ``latest_logs/``) """

from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class FailingTests(BaseCase):
    def test_find_army_of_robots_on_xkcd_desert_island(self):
        self.open("https://xkcd.com/731/")
        self.assert_element("div#ARMY_OF_ROBOTS", timeout=1)
```

**Comment by manel00** [comment]
is there a way to reconnect or something like that to get a screenshot?

**Comment by mdmintz** [comment]
You can also use the `SB()` format to get screenshots when a test fails:

```python
from seleniumbase import SB

with SB(test=True) as sb:
    sb.open("seleniumbase.io/simple/login")
    sb.fail("Fail!")
```

(Screenshots will appear in the `./latest_logs/` folder for failing tests.)

**Comment by manel00** [comment]
Thank you as always!
