### ISSUE TITLE
Error 'invalid argument: invalid locator' when get_attribute()

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2549]
Hello,

```
list_rows_elements = sb.find_elements(list_new_format_data)
for item in list_rows_elements:
    train_img_string = item.find_element(".//img").get_attribute("src")
```
                        
I am getting `invalid argument: invalid locator` because of the get_attribute, sometimes i dont understand the code... how can I differ it?

Thank you

**Comment by mdmintz** [comment]
Your `list_rows_elements` is a list of `selenium` `WebElement` items. When working on a `WebElement`, those don't have the `seleniumbase` simplifications, such as the ability to use a selector without specifying the `by`. For a `WebElement` item, you would have to use `item.find_element("xpath", ".//img")` in your case.
