### ISSUE TITLE
how to close or quit uc_driver ?

### ISSUE THREAD

**Issue by zxczxcdev** [seleniumbase/SeleniumBase#2562]
I couldn't find any documentation about closing uc_driver after it's finished running. sb.quit() does not exist
![image](https://github.com/seleniumbase/SeleniumBase/assets/72661673/c0f9846f-d53d-42dd-b40d-006ff8b6989b)

**Comment by mdmintz** [comment]
To access `driver`-specific commands from the `SB()` format, use `sb.driver`.

To quit the `driver` at any point: `sb.driver.quit()`

The driver is also quit automatically at the end of the `with` block:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    # ...
```
