### ISSUE TITLE
Possibility integrating SeleniumBase in dotnet ?

### ISSUE THREAD

**Issue by graysuit** [seleniumbase/SeleniumBase#2563]
Normally been using normal selenium library. But when needed google automation, or somewhere cloudflare, only SB worked for me. 

But I mainly write for .Net Framework and Visual Basic as programming language.
Wrapping in to pyinstaller looks workaround at a moment. But harder to control.

Are there any SB bindings for dotnet ?
or any similar project that have UC mode ?

I also tried uc_driver.exe which patched by SB. But on url navigation cloudflare detects my dotnet app.
So I'm sure on navigation SB does some additional work too ?

Any advice or suggestion would be highly appreciated.
Thanks a ton

**Comment by mdmintz** [comment]
Using a patched `chromedriver` (`uc_driver`) isn't enough to remain undetected. There are other tasks that must be performed as well.

SeleniumBase is only for Python right now, but there's another thread about C# support in `undetected-chromedriver` here: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/540, which has a link to https://github.com/fysh711426/UndetectedChromeDriver (C# implementation of `undetected-chromedriver`).

**Comment by ilgrank** [comment]
> Any advice or suggestion would be highly appreciated. Thanks a ton
Could this project be of interest?

**Comment by JvB94** [comment]
@ilgrank are you using that project? Can

**Comment by ilgrank** [comment]
> [@ilgrank](https://github.com/ilgrank) are you using that project? Can you maybe show an example? the github repo seems to be down.

No, I'm not using it, but I found it while searching for a similar solution.
Alas, as you say the github repo of the project is down (and no archived page seems to be avaliable on web archive) BUT a sample page exists here https://github.com/waynewa/SampleProjects
Let me know if you are able to get something out of it :)
