### ISSUE TITLE
Darwin Arm WebDriver download link broken?

### ISSUE THREAD

**Issue by sarkrui** [seleniumbase/SeleniumBase#2565]
It seems the link for darwin arm latest WebDriver ([ver.122](https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.94/mac-arm64/chromedriver-mac-arm64.zip)) is broken, and sbase isn't aware of that.  
![Xnip2024-03-05_16-45-15](https://github.com/seleniumbase/SeleniumBase/assets/14228455/4dd2d84a-706f-4692-ab84-70396981b082)
<img width="568" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/14228455/6f3c338d-92b3-4384-9d5d-b5dbdf4c4e8c">

Both commands for upgrading the WebDriver did show downlod failed.
```
sbase get chromedriver mlatest
seleniumbase get chromedriver
```
<img width="723" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/14228455/bb0b7a4c-142a-41e1-9ff0-eedaf789192c">

**Comment by mdmintz** [comment]
The Chromium Team changed the download location of drivers, and SeleniumBase was updated to use the newer location 2 weeks ago in https://github.com/seleniumbase/SeleniumBase/issues/2519

You need to upgrade to a newer version of SeleniumBase.

Also, the `"mlatest"` option is only for `--driver-version=VER` / `driver_version=VER` when running the tests. (It's not for the `seleniumbase get chromedriver VER` command.)
