### ISSUE TITLE
UC mode Selenoid In Chance?

### ISSUE THREAD

**Issue by hnnoye04** [seleniumbase/SeleniumBase#2572]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1600#discussioncomment-7253842
I hv got uc driver patched docker work already but i want to work my code with SB mode any chance on this?

**Comment by mdmintz** [comment]
Duplicate of https://github.com/seleniumbase/SeleniumBase/discussions/2285

SeleniumBase in basic mode supports Selenoid. (https://github.com/seleniumbase/SeleniumBase/discussions/1087#discussioncomment-1714005)
(But not in UC Mode, which doesn't work with Selenium Grids.)
