### ISSUE TITLE
Simple site detetected undetected_chrome

### ISSUE THREAD

**Issue by FreeM1ne** [seleniumbase/SeleniumBase#2573]
i think detected driver.find
https://www.kleinanzeigen.de/m-passwort-vergessen.html

**Comment by mdmintz** [comment]
You have to provide sample code for me to be able to debug your issue.

**Comment by FreeM1ne** [comment]
site detect func click send keys and driver.find 
you can see for yourself there's 10 lines of code.

**Comment by mdmintz** [comment]
Sounds like you're using regular Selenium commands. The SeleniumBase API is different. There are methods such as `sb.driver.uc_click(selector)` (for example) that don't exist with regular Selenium. You need to show me a sample SeleniumBase script if you want me to reproduce and debug your issue.

**Comment by FreeM1ne** [comment]
pytest .\new_recording.py --uc --mobile --proxy=127.0.0.1:49441
```
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)


class RecorderTest(BaseCase):
    def test_recording(self):
        self.open("https://www.kleinanzeigen.de/m-passwort-vergessen.html")
        self.click("div#gdpr-banner div:nth-of-type(2)")
        self.click("button#gdpr-banner-accept")
        self.click("div#site-content")
        self.type("input#resetpwd-email", "keksshoppss123@gmx.de")
        self.click("button#resetpwd-submit")
        self.open_if_not_url("https://www.kleinanzeigen.de/m-passwort-vergessen.html")
        import time
        time.sleep(10000)
```

**Comment by mdmintz** [comment]
Using the mobile emulator in UC Mode will get you detected. Also, you have to use `self.driver.uc_click(selector)` to remain undetected in UC Mode when clicking.

See the example: [examples/raw_nopecha.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_nopecha.py)

**Comment by FreeM1ne** [comment]
undetected write text?

**Comment by FreeM1ne** [comment]
detected
```
from time import sleep
from seleniumbase import SB

with SB(uc=True, test=True, proxy="127.0.0.1:51128") as sb:
    sb.driver.uc_open_with_reconnect("https://www.kleinanzeigen.de/m-passwort-vergessen.html", 5)

    sb.driver.uc_click("div#gdpr-banner div:nth-of-type(2)")
    sb.driver.uc_click("button#gdpr-banner-accept")
    sb.driver.uc_click("div#site-content")

    sb.driver.uc_click("#resetpwd-email")
    sb.driver.send_keys("#resetpwd-email", "jdisadijajaiwd@gmx.de")
    sb.driver.uc_click("#resetpwd-submit")
    sleep(100000)
```

**Comment by mdmintz** [comment]
You can try using `sb.driver.reconnect(2)` after typing text if you were detected from that.

**Comment by FreeM1ne** [comment]
where do I add this?

**Comment by mdmintz** [comment]
Right after any line where you type text.

**Comment by FreeM1ne** [comment]
detected

**Comment by mdmintz** [comment]
Try manually from the `breakpoint()` in this script:

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    url = "https://www.kleinanzeigen.de/m-passwort-vergessen.html"
    sb.driver.uc_open_with_reconnect(url, "breakpoint")
```

**Comment by FreeM1ne** [comment]
Manually, everything works

**Comment by mdmintz** [comment]
If it works from that selenium window, then you can either figure out the correct timing to make it work from there, or mix `pyautogui` into your script to perform the actions on that selenium window without getting detected.

**Comment by FreeM1ne** [comment]
pyautogui это худшее решение я думаю проблема в вводе текста

**Comment by FreeM1ne** [comment]
Ignore?

**Comment by mdmintz** [comment]
You said that https://github.com/seleniumbase/SeleniumBase/issues/2573#issuecomment-1984230018 solved your issue. Which means either adjust timing for the `reconnect_time`, or combine `seleniumbase` with `pyautogui`. There's not much else that can be done at this point.

**Comment by FreeM1ne** [comment]
how get pid browser

**Comment by mdmintz** [comment]
Use https://stackoverflow.com/ for non-SeleniumBase questions.

**Comment by FreeM1ne** [comment]
Why? I start this process in the code, so there should be a variable with pid how do I search for the window via pyautogui.

**Comment by mdmintz** [comment]
`pyautogui` is a different repo: https://github.com/asweigart/pyautogui
