### ISSUE TITLE
Using a proxy with authorization and seleniumbase

### ISSUE THREAD

**Issue by Pidoffka** [seleniumbase/SeleniumBase#2591]
Hello
I would like to share my problem with working with a proxy with authorization
I pass the proxy parameter to the driver and when I start throwing different profiles, I get an authorization dialog, but sometimes it works fine

I searched the entire Internet, found that you can use the display, but as I understand it, it only works with Ubuntu and there should be no problems with Windows

I also looked that Seleniumbase uses the method of throwing up proxies with authorization through Java script files and read somewhere that they are used as extensions for Chrome and work stably only in headless mode

Can you confirm or refute these theses and suggest how you can work stably with Seleniumbase through a proxy with authorization and whether this is achievable at all, since I cannot somehow process this dialog box, and I have not found a stable working solution on the Internet, it worked stably before via seleniumwire, but it is not secure enough now, how can I solve my problem?

My issue may be similar to https://github.com/seleniumbase/SeleniumBase/issues/2368
Where do I need to use different proxies with authentication for one profile? I didn’t understand the solution in the post, can you tell me what I need for this?

**Comment by mdmintz** [comment]
Rotating proxies is a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2450#issuecomment-1910500931.
Proxies with Chrome extensions is a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2397#issuecomment-1872564511.

(If you're not using UC Mode, then you don't need the `--uc` / `uc=True` part.)

**Comment by Pidoffka** [comment]
> Ротация прокси — это дубликат [#2450 (комментарий)](https://github.com/seleniumbase/SeleniumBase/issues/2450#issuecomment-1910500931) . Прокси с расширениями Chrome — это дубликат [#2397 (комментарий)](https://github.com/seleniumbase/SeleniumBase/issues/2397#issuecomment-1872564511) .
> 
> (Если вы не используете режим UC, вам не нужна часть `--uc`/ `uc=True`.)

Thanks
Using the parameter helped:  `multi-proxy=True` and `chromium_agg='--no-server-proxy'`
It’s strange that the second command still forwards the proxy server, and does not disable its use, because Google says that it disables the use of proxies, but on the sites, by definition of IP, I had a proxy IP and not my own

**Comment by TruongDinhDTri** [comment]
@Pidoffka  Hey I'm facing the same problem as you, so all I need is just add 2 more parameter is multi-proxy=True and chromium_agg='--no-server-proxy' right ?

**Comment by Derrick-Mulwa** [comment]
Any update on this? I am unable to use a proxy that requires authentication (username, password) without getting the chrome popup to sign in.

I am using the seleniumbase Driver(). Here's the code snippet:

proxy = "myusername:mypassword@host:port"

driver = Driver(
                    uc=True,
                    headless=headless_mode,
                    proxy=proxy,
                    chromium_arg="--no-server-proxy",
                    multi_proxy=False
                    locale_code="en",
                    )

Proxy does not work

**Comment by mdmintz** [comment]
You must `activate_cdp_mode()` in order for proxy auth to take effect (unless you set `use_chromium=True`).
Otherwise, there's no auth with UC Mode alone. (You have to do at least one of the two things above.)

**Comment by maximunya** [comment]
> You must `activate_cdp_mode()` in order for proxy auth to take effect (unless you set `use_chromium=True`). Otherwise, there's no auth with UC Mode alone. (You have to do at least one of the two things above.)

Here's my code, where I'm trying to use UC + CDP mode to use proxy with auth:
```
  with SB(
      browser="chrome",
      uc=True,
      xvfb=True,
      incognito=True,
      proxy=self._get_proxy(),
      chromium_arg=[
          "--no-sandbox",
          "--disable-dev-shm-usage",
      ],
  ) as sb:
      sb.activate_cdp_mode("https://api.ipify.org")
      logger.info("Full IP from ipify:")
      logger.info(sb.get_page_source())

```
And I get traceback:
Traceback (most recent call last): File "/opt/src/.venv/lib/python3.10/site-packages/seleniumbase/undetected/cdp_driver/connection.py", line 621, in listener_loop event = cdp.util.parse_json_event(message) File "/opt/src/.venv/lib/python3.10/site-packages/mycdp/util.py", line 19, in parse_json_event return _event_parsers[json["method"]].from_json(json["params"]) File "/opt/src/.venv/lib/python3.10/site-packages/mycdp/network.py", line 3833, in from_json response=Response.from_json(json["response"]), File "/opt/src/.venv/lib/python3.10/site-packages/mycdp/network.py", line 1084, in from_json charset=str(json["charset"]), KeyError: 'charset'

**Comment by mdmintz** [comment]
This worked fine for me:
```python
from seleniumbase import SB

with SB(uc=True, test=True, proxy="user:pass@ip:port") as sb:
    sb.activate_cdp_mode("https://api.ipify.org")
    print(sb.get_page_source())
```

**Comment by maximunya** [comment]
I updated the proxy format to `user:pass@ip:port` (instead of `http://user:pass@ip:port`), but I’m still unable to reach the target site when using an authenticated proxy. Without a proxy, everything works as expected.

Current working example without proxy:

```python
from seleniumbase import SB

with SB(uc=True, xvfb=True, incognito=True) as sb:
    sb.uc_open_with_reconnect("https://vx-underground.org", 5)
    sb.uc_gui_click_captcha()
    sb.sleep(5)
    sb.save_screenshot("/tmp/main_page.png")
```

When I try to use an auth proxy, either with or without `activate_cdp_mode`, the browser just shows a blank screen:

```python
from seleniumbase import SB

with SB(
    uc=True,
    xvfb=True,
    incognito=True,
    proxy="user:pass@ip:port",
) as sb:
    sb.activate_cdp_mode("https://vx-underground.org")
    sb.sleep(2)
    sb.uc_gui_click_captcha() # tried sb.solve_captcha() also
    sb.sleep(5)
    sb.save_screenshot("/tmp/main_page.png")
```

I think I might be using the combination of UC and CDP mode incorrectly. Could you clarify the correct way to use auth proxies here, or if there’s a known limitation?

**UPD:** Tried another proxy with the same code. Now shows Cloudflare "Verification successful" followed by endless "Waiting for vx-underground.org to respond..." instead of blank screen.

**Comment by cipherpodliq1** [comment]
@mdmintz is there a solution to this?

**Comment by mdmintz** [comment]
Set `use_chromium=True` for the proxy extension to work. That'll use Chromium, which still allows command-line extensions, unlike branded Google Chrome, which removed the `--load-extension` command-line switch.

```python
from seleniumbase import SB

with SB(uc=True, test=True, use_chromium=True, proxy="user:pass@ip:port") as sb:
    sb.activate_cdp_mode("https://api.ipify.org")
    print(sb.get_page_source())
```
