### ISSUE TITLE
tuple index out of range - python

### ISSUE THREAD

**Issue by own3mall** [seleniumbase/SeleniumBase#2598]
```
from seleniumbase import Driver
browser = Driver(uc=True, headless=True)
browser.get(url)
```
Above code fails with:

```
Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 122.0.6261.128 (Latest Stable) 

Downloading chromedriver-linux64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.128/linux64/chromedriver-linux64.zip ...

*** chromedriver to download = 122.0.6261.128 (Latest Stable) 

Downloading chromedriver-linux64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.128/linux64/chromedriver-linux64.zip ...
tuple index out of range
```

But I already have installed the undetected-chromedriver package.  When I use undetected-chromedriver by itself, it works, but not in headless mode which is why I decided to try this package, but it doesn't appear to work?

**Comment by mdmintz** [comment]
Looks like your Linux user might have missing permissions to download the driver. It never showed "Download complete!"

Here it is on mine:

https://github.com/seleniumbase/SeleniumBase/actions/runs/8269106351/job/22623569626

<img width="1244" alt="Screenshot 2024-03-13 at 3 02 21 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/784d7d09-5645-4090-9e53-d56c06e11047">

And here it is on my Mac:

```
sbase get uc_driver

*** chromedriver to download = 122.0.6261.128 (Latest Stable) 

Downloading chromedriver-mac-x64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.128/mac-x64/chromedriver-mac-x64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-mac-x64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/uc_driver

Making [uc_driver 122.0.6261.128] executable ...
[uc_driver 122.0.6261.128] is now ready for use!
```

That's as much as I can determine from the info you provided.

**Comment by own3mall** [comment]
Well, if I run the script as root using `sudo`, it works.  Why wouldn't it work with a normal user?  I haven't limited or changed the permissions of my normal user :(

**Comment by mdmintz** [comment]
@own3mall By the looks of it, a regular user on your specially-configured Linux box doesn't have the permissions needed to download a file into your `seleniumbase/drivers` folder from within your Python environment. Since it works when you use `sudo`, that should hopefully indicate the situation.

**Comment by own3mall** [comment]
@mdmintz 

So, I tried doing this:

cd /usr/local/lib/python3.8/dist-packages
sudo chmod 775 -R seleniumbase
sudo usermod -a -G staff {MY_USER_LOGIN}

But now when I run my python script, I get the following.

Mar 13 23:42:05 {MY_USER_LOGIN}-{MY_COMPUTER_HOSTNAME} kernel: [65909.164364] audit: type=1400 audit(1710394925.830:1138): apparmor="DENIED" operation="open" profile="snap.chromium.chromium" name="/etc/vulkan/icd.d/" pid=341096 comm="chrome" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Mar 13 23:42:05 {MY_USER_LOGIN}-{MY_COMPUTER_HOSTNAME} kernel: [65909.164546] audit: type=1400 audit(1710394925.830:1139): apparmor="DENIED" operation="open" profile="snap.chromium.chromium" name="/etc/vulkan/implicit_layer.d/" pid=341096 comm="chrome" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Mar 13 23:42:05 {MY_USER_LOGIN}-{MY_COMPUTER_HOSTNAME} kernel: [65909.164760] audit: type=1400 audit(1710394925.830:1140): apparmor="DENIED" operation="open" profile="snap.chromium.chromium" name="/etc/vulkan/implicit_layer.d/" pid=341096 comm="chrome" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Mar 13 23:42:05 {MY_USER_LOGIN}-{MY_COMPUTER_HOSTNAME} kernel: [65909.164939] audit: type=1400 audit(1710394925.830:1141): apparmor="DENIED" operation="open" profile="snap.chromium.chromium" name="/etc/vulkan/icd.d/" pid=341096 comm="chrome" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

I'm running Ubuntu 20.04 with no special changes.  Running the script with sudo works fine, but that's not ideal for security purposes.  Any idea how I can fix this issue?

**Comment by mdmintz** [comment]
@own3mall You can try using a Python virtual environment when you run scripts.

**Comment by own3mall** [comment]
@mdmintz , I don't want to do it that way.  Evidently, no one has a working answer how to disable specifically the snap chromium profiles:

https://askubuntu.com/questions/1267980/how-to-disable-apparmor-for-chromium-snap-ubuntu-20-04
https://ubuntuforums.org/showthread.php?t=2410550
https://ubuntuforums.org/showthread.php?t=2449022
https://answers.launchpad.net/ubuntu/+source/apparmor/+question/701036

So, might as well get rid of the Ubuntu garbage altogether:

```
sudo systemctl stop apparmor 
sudo systemctl disable apparmor
```

Working for my user account now.  Snap sucks.

**Comment by own3mall** [comment]
And filed a bug with Ubuntu:  https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2057943

Anyways, selenium base works great.  Thank you!
