### ISSUE TITLE
Error Message: element not interactable random appears...

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2606]
Hello

I am getting the following error: 

`Message: element not interactable`

I don't understand how to avoid it, in few words, i am trying to do click on a tab element and get some information from what is within (table with data), before i check the table data, I sleep 2 seconds to try to avoid it (sb.sleep(2)) and nothing is blocking it, the scroll is perfect and I see the element... I don't know how to be sure to click on it... any tips please?

Thank you so much

**Comment by mdmintz** [comment]
That means another element overlay is appearing over the element you want to click.
If that overlay isn't going away on its own, you can use `sb.js_click(selector)` to click the element directly.
