### ISSUE TITLE
Headless Not Passing Captchas in Some Cases

### ISSUE THREAD

**Issue by own3mall** [seleniumbase/SeleniumBase#2608]
For example, with seleniumbase https://www.marketwatch.com/investing/stock/GOOG headless uc mode doesn't get past I'm thinking this recaptcha script:  `<script data-cfasync="false" src="https://interstitial.captcha-delivery.com/i.js">`

It was working yesterday though.  Weird.   Any ideas?

```
                display = Display(visible=0, size=(1920, 1200))
                display.start()

                browser = Driver(uc=True, headless=True)
                browser.get(url)
```

**Comment by mdmintz** [comment]
The whole point of the virtual display is for avoiding the use of headless mode, which can get you detected. The virtual display lets you spin up a headed browser in a headless environment.

**Comment by own3mall** [comment]
@mdmintz Actually, I can't get that link to work with any mode.  

```
display = Display(visible=0, size=(1920, 1200))
                display.start()

                browser = Driver()
                browser.get(url)

```

With / without uc=True makes no difference and I am using the virtual display without headless mode

**Comment by mdmintz** [comment]
As long as this test is passing: [examples/raw_pixelscan.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_pixelscan.py) then I know that the anti-detection for page loads is working at maximum capacity. If that's working, then it's good enough for me. People have to solve their own edge cases.
