### ISSUE TITLE
Setting locale in UC Mode

### ISSUE THREAD

**Issue by rafafranco2203** [seleniumbase/SeleniumBase#2624]
Hello, I have a bot that follows a profile on Tiktok, but a while ago it stopped working, every time it tries to follow it, it doesn't work, it's like the profile has a blocker
when f5 comes back, the account is not blocked because I just tested it manually in the normal browser, it seems that something is being detected by tiktok

browser_arg = "--lang=en"  # Locale for traditional English
browser = Driver(uc=True, browser='chrome', locale_code=browser_arg)

**Comment by rafafranco2203** [comment]
this worked here but I want to use seleniumbase

from auto_download_undetected_chromedriver import download_undetected_chromedriver

folder_path = "c:\\download2thisfolder20"
chromedriver_path = download_undetected_chromedriver(
    folder_path, undetected=True, arm=False, force_update=True
)
import undetected_chromedriver as uc

driver = uc.Chrome(
    driver_executable_path=chromedriver_path, headless=False, use_subprocess=True
)

**Comment by mdmintz** [comment]
You have to use one of the locale codes in https://seleniumbase.io/help_docs/locale_codes/ when setting a locale code.
Eg: `locale_code="en_us"`.

For customizing the `reconnect_time` in UC Mode, use `driver.uc_open_with_reconnect(url, reconnect_time)`.
Eg: [examples/raw_pixelscan.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_pixelscan.py), where there's a longer page load, so the default reconnect_time isn't enough. Use `driver.uc_click(selector)` when you need to click something and remain undetected.
