### ISSUE TITLE
How to connect to a local chrome already opend?

### ISSUE THREAD

**Issue by peaceyourself** [seleniumbase/SeleniumBase#2633]
I uses code like this to connect to my local chrome by `selenium`, How can i do this with `seleniumbase`
Have read the doc and api, did not figure it out ,need help

```python
from selenium import webdriver
    chrome_options = Options()
    chrome_options.add_experimental_option("debuggerAddress", '127.0.0.1:' + str(hub_port))
    chrome_service = webdriver.ChromeService(executable_path=driver_path)
    driver = webdriver.Chrome(options=chrome_options, service=chrome_service)
```

**Comment by mdmintz** [comment]
That's what UC Mode does. It spins up a Chrome browser, and then attaches Selenium WebDriver to it. The browser that it attaches to must be one that it opened itself.

This is a duplicate of these two tickets:

* https://github.com/seleniumbase/SeleniumBase/issues/2369#issuecomment-1858989224

* https://github.com/seleniumbase/SeleniumBase/issues/2225#issuecomment-1785326861

**Comment by peaceyourself** [comment]
I have read the two issue , but still not understood. 
I want to connect to chrome window opend by AdsPower.
Does this means  there is noway to connect to the AdsPower?

**Comment by mdmintz** [comment]
That falls outside the scope of this repo.

**Comment by mdmintz** [comment]
The code for taking control of existing Chrome browsers via the `remote-debugging-port` is here:

**https://github.com/seleniumbase/SeleniumBase/issues/3354#issuecomment-2557709036**
