### ISSUE TITLE
Ability to provide custom timeout without specifying 'by' locator strategy

### ISSUE THREAD

**Issue by StareNew01** [seleniumbase/SeleniumBase#2634]
Assuming a project uses 'css selector' as the locator strategy most of the time, to support custom timeout on a case by case basis (i.e. without touching the default timeout), a user should be able to use:

self.find_element('#somecssid', timeout=8) instead of self.find_element(('#somecssid', by="css selector", timeout=8)

Is this already possible in seleniumbase OR an enhancement needed?

**Comment by mdmintz** [comment]
It's already possible. There's a `timeout` argument for most methods.

Eg. `self.click("button", timeout=5)`
