### ISSUE TITLE
Selenium4 used by seleniumbase cannot be set to name through options. set_capability, it is suspected that selenium4 is incompatible with the latest version of zalenium

### ISSUE THREAD

**Issue by WaterLoran** [seleniumbase/SeleniumBase#2638]
![image](https://github.com/seleniumbase/SeleniumBase/assets/52927459/d29aa5d6-a853-4d8d-b7fa-644281dd781b)

![image](https://github.com/seleniumbase/SeleniumBase/assets/52927459/67ca6e41-201e-4dc0-a387-a3ea5c4ab8ab)

![image](https://github.com/seleniumbase/SeleniumBase/assets/52927459/8def5de3-e280-4e0e-99d0-0c0f5af6769f)

I still need a tool similar to zalenium to help me solve compatibility issues when running in a Linux environment, but it seems that zalenium has been out of maintenance for 2 years, so I'm not sure if Selenium4 and zalenium are incompatible. If there is a better alternative to zalenium, please let me know. Here, I mainly like zalenium's video recording function

**Comment by WaterLoran** [comment]
The key code is this line of options. set_capability ("name", "cur_exec_name")

As long as it is added, the driver application will fail

**Comment by mdmintz** [comment]
For setting capabilities, see [examples/capabilities](https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities)

See https://github.com/seleniumbase/SeleniumBase/issues/499#issuecomment-585799338 for connecting to a Zalenium Selenium Grid:

**Comment by WaterLoran** [comment]
I think we should first submit an issue to Selenium. If Selenium 4 is not possible, then Selenium base should also not be supported. Therefore, I will temporarily close this issue
