### ISSUE TITLE
recorder is not working 

### ISSUE THREAD

**Issue by manojs1978** [seleniumbase/SeleniumBase#2643]
when we run below command recorder is not launching

command : sbase mkrec new_test.py or sbase recorder or seleniumbase recorder

Error:

(seleniumbase) manoj@manoj:~/**/**/SeleniumBase$ sbase recorder
Traceback (most recent call last):
  File "/home/manoj/.local/bin/sbase", line 33, in <module>
    sys.exit(load_entry_point('seleniumbase', 'console_scripts', 'sbase')())
  File "/home/manoj/**/**/SeleniumBase/seleniumbase/console_scripts/run.py", line 1043, in main
    from seleniumbase.console_scripts import sb_recorder
  File "/home/manoj/**/**/SeleniumBase/seleniumbase/console_scripts/sb_recorder.py", line 36, in <module>
    import tkinter as tk  # noqa: E402
ModuleNotFoundError: No module named 'tkinter'

seleniumbase version: latest
OS: ubuntu23

**Comment by mdmintz** [comment]
On Ubuntu, `tkinter` needs to be installed separately: https://stackoverflow.com/a/25905642/7058266

```bash
sudo apt-get install python3-tk
```

**Comment by manojs1978** [comment]
thank you for your reply.

but still facing issue

i followed steps to install as below

created virtual env
python3 -m venv sbase_env
source sbase_env/bin/activate
sudo apt-get install python3-tk
pip uninstall seleniumbase

then i was trying for recorder
seleniumbase recorder

but getting below error
![image](https://github.com/seleniumbase/SeleniumBase/assets/5729240/4904f7fa-d3a9-4df6-bcba-ad133dc1f29c)

**Comment by mdmintz** [comment]
You've got three options:
1. Find another StackOverflow article on fixing tkinter installation on Linux.
2. Use macOS or Windows instead.
3. Start recording without the GUI: `sbase mkrec TEST_NAME.py --url=URL`
