### ISSUE TITLE
Selenium base can not get data from network

### ISSUE THREAD

**Issue by TranTienVan** [seleniumbase/SeleniumBase#2650]
I am trying to use the function driver.get_log in seleniumbase in it does not work.
Any helps?
Thank you!

**Comment by mdmintz** [comment]
Network log capture must be enabled to take effect (``log_cdp=True``):

See the example: [SeleniumBase/examples/raw_cdp_logging.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_cdp_logging.py)

```python
from rich.pretty import pprint
from seleniumbase import Driver

driver = Driver(uc=True, log_cdp=True)
try:
    driver.uc_open_with_reconnect("https://seleniumbase.io/apps/turnstile")
    driver.switch_to_frame("iframe")
    driver.uc_click("span.mark")
    driver.sleep(3)
    pprint(driver.get_log("performance"))
finally:
    driver.quit()
```
