### ISSUE TITLE
how to run with interactive interpreter?

### ISSUE THREAD

**Issue by emin63** [seleniumbase/SeleniumBase#266]
Thanks for SeleniumBase. It's a neat package.

Can you provide some hints on how to run in an interactive interpreter?

I saved your [my_first_test.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/my_first_test.py) in a file and succesfully ran via `py.test my_first_test.py`. Then I tried to run in an interactive interpreter via
```python
import my_first_test
import unittest
result = unittest.main('my_first_test', exit=False*)
```
but got the following error:

```
======================================================================
ERROR: test_basic (my_first_test.MyTestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\Anaconda3\lib\site-packages\seleniumbase\fixtures\base_case.py", line 2770, in setUp
    raise Exception("""SeleniumBase plugins did not load! """
Exception: SeleniumBase plugins did not load! Please reinstall using:
 >>> "python setup.py install" <<< 

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
>>> 
```

Again, it seems installed correctly since I can run tests from the command line. I would like to be able to experiment with SeleniumBase from inside the interpreter in the same way I can with Selenium webdriver but haven't figured out how.

Thanks.

**Comment by emin63** [comment]
Thanks for the quick response.

That sounds like a pretty big limitation as compared to regular selenium. Isn't there a way I can call the `setUp` method or something to do the prep work that `pytest` does? I tried just calling `setUp` of course and then manually calling methods from the test but that didn't work either.

Do you know what kinds of things pytest is doing and how I might do those manually in the interpreter?

Thanks.

**Comment by emin63** [comment]
I hacked at this some more and was able to execute the stuff in `my_first_test`  in the interpreter using the code below.

Basically, it seems like all that was required was to set some things that `BaseCase` normally sets based on the pytest config. If you could provide some docs on how the pytest config works or what those requierd variables are I think that would resolve this nicely and extend the things you can do with `SeleniumBase`.

If not, well I guess we can just use hacks like what we have below. :)

Thanks.

```python
import my_first_test
b = my_first_test.MyTestClass()
b.browser='chrome'
b.headless=False
b.servername='localhost'
b.port=6363
b.proxy_string=None
b.cap_file=None
b.timeout_multiplier=1.0
b.js_checking_on=False
b.ad_block_on=False
b.setUp()
b.demo_mode=True
b.demo_sleep=2
b.message_duration=2
b.highlights=False
b.test_basic()
b.tearDown()
del b
```

**Comment by mdmintz** [comment]
@emin63 The pytest config options are defined in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/pytest_plugin.py  As you've discovered, those options are used the the BaseCase setUp() method defined in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/fixtures/base_case.py (as well as in other methods).  The advantage to using pytest is that you can specify all those options on the command line. With the code you just wrote, you can now define all those variables in the Python interactive interpreter without using pytest to set the values of the parameters. I didn't think much about the usefulness of that, but perhaps there's more than I thought. What are some of the ways you see this for expanding SeleniumBase? The one thing I see is the ability to perform SeleniumBase actions as a pure Python script without the need of using Pytest.

**Comment by mdmintz** [comment]
Also, thanks to the tearDown() method of pytest runs, the browser window will automatically get closed at the end of the test, even if there are errors in the middle. I'd say the advantages of running scripts in unittest format with pytest outweight the advantages of running scripts as a pure python script.

**Comment by emin63** [comment]
Wow! You're fast. Thanks for that `raw_parameter_script.py`. That solves my problem.

I agree with you that running scripts in unittest has a lot of advantages relative to pure python. That is how I generally do testing. Sometimes for demos, debugging, or developing things however I prefer the python or ipython interpreter and its nice to be able to use SeleniumBase in those situations.

I'm closing this ticket since my use case is now solved. Thanks.

**Comment by mdmintz** [comment]
@emin63 Also see:

```python
"""Context Manager Test. Runs with "python". (pytest not needed)."""
from seleniumbase import SB

with SB() as sb:  # By default, browser="chrome" if not set.
    sb.open("https://seleniumbase.io/realworld/login")
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.enter_mfa_code("#totpcode", "GAXG2MTEOR3DMMDG")  # 6-digit
    sb.assert_text("Welcome!", "h1")
    sb.highlight("img#image1")  # A fancier assert_element() call
    sb.click('a:contains("This Page")')  # Use :contains() on any tag
    sb.click_link("Sign out")  # Link must be "a" tag. Not "button".
    sb.assert_element('a:contains("Sign in")')
    sb.assert_exact_text("You have been signed out!", "#top_message")
```
