### ISSUE TITLE
Emojis and return lines not being processed properly by self.type

### ISSUE THREAD

**Issue by st7xxx** [seleniumbase/SeleniumBase#2663]
Hello, i am using self.type to type a message like this Testing emojis: ⭐❤️
                                                                                  Testing return: 
                                                                                  Return test 
and instead of returning the exact text it returns, every row being typed separately  and no emojis being sent. 
I couldn't find anyone else having this issue

**Comment by mdmintz** [comment]
I'm not sure I really understand your issue without actual code.

This code types emojis successfully for me:

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class DemoSiteTests(BaseCase):
    def test_demo_site(self):
        self.open("https://seleniumbase.io/demo_page")
        self.type("#myTextInput", "⭐❤️")
        self.type("textarea.area1", "⭐❤️\n")
        self.type('[name="preText2"]', "⭐❤️!")
        self.sleep(3)
```
