### ISSUE TITLE
Unable to pass cloudflare using UC Mode

### ISSUE THREAD

**Issue by flairekq** [seleniumbase/SeleniumBase#2668]
Hi, I tried the codes from [raw_form_turnstile.py.py](https://github.com/seleniumbase/SeleniumBase/tree/master/examples/raw_form_turnstile.py.py) it passes the Cloudflare however when I modify the URL to [https://thaiticketmajor.com/concert/](https://www.thaiticketmajor.com/concert/ ) and tries to sign in, it keeps failing Cloudflare with error code of 600010.

**Comment by flairekq** [comment]
The code I'm using:
```
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    sb.driver.uc_open_with_reconnect("https://www.thaiticketmajor.com/concert/", 3)
    sb.highlight_click("button.btn-signin")
    sb.switch_to_frame('iframe[src*="challenge"]')
    sb.driver.uc_click("span.mark")
```

**Comment by mdmintz** [comment]
You have to use `driver.uc_click(selector)` whenever going to a screen that has a CAPTCHA waiting for you. (You used `highlight_click(selector)` instead, which would get you detected.)

This worked:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    sb.driver.uc_open_with_reconnect("https://www.thaiticketmajor.com/concert/", 4)
    sb.driver.uc_click("button.btn-signin", 4)

    breakpoint()
```
