### ISSUE TITLE
Integrate Type Checks, to improve development experience.

### ISSUE THREAD

**Issue by Saur-av** [seleniumbase/SeleniumBase#2669]
While working with the module it seems that there are no "methods" suggestions being popped up onto the code editor. I went onto the code and found that there were no Type Checks beings implemented and I think it is the main issue for this project. Do correct me if I'm wrong. Thanks!

**Comment by mdmintz** [comment]
Based on this project's structure, which allows for multiple [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md), the best way to see method suggestions is to use a Python `breakpoint()`. (It'll open a [pdbp](https://github.com/mdmintz/pdbp) debugger, which is quite advanced.)

See https://github.com/mdmintz/pdbp for more info on the `pdbp` realtime debugger.
