### ISSUE TITLE
Some elements cannot be inputted using the input method

### ISSUE THREAD

**Issue by WaterLoran** [seleniumbase/SeleniumBase#2687]
Some elements cannot be inputted using the input method and require the use of action_chain to simulate real keyboard input.

For example, the following element requires input of a verification code, but if it navigates to the first input box and calls input, it will fail. 
![e4831413aeda7a3bdd102b55cf1899f](https://github.com/seleniumbase/SeleniumBase/assets/52927459/f7f7a5fb-7e9c-4209-adf3-239f89fb40fa)

However, using the following code will succeed,
![image](https://github.com/seleniumbase/SeleniumBase/assets/52927459/30d82d76-09e7-4af5-802e-1e452a45b99a)

May I ask if there are any relevant packaged methods available.

Perhaps you need to modify the type method,
![image](https://github.com/seleniumbase/SeleniumBase/assets/52927459/31a9e68b-a341-4d1c-804c-7743bcae7cea)

The URL of the relevant tested website is as follows. Just enter your email and click to see the verification code page
https://app.zeitro.com/services/preapp/emailverification?customerid=zeitro&loid=2fbec8de-8f6a-4fd9-8be3-c9743622e2b7

**Comment by mdmintz** [comment]
There are different input methods in SeleniumBase. `self.type(selector, text)` is specifically for regular input fields.

Use one of these for the section on that page:

```python
self.send_keys('input[inputmode="decimal"]', " 1234")

self.press_keys('input[inputmode="decimal"]', " 1234")
```
