### ISSUE TITLE
Timezone problem on pixelscan test

### ISSUE THREAD

**Issue by Juanfra24** [seleniumbase/SeleniumBase#2689]
First of all I would like to thank you @mdmintz for this excellent library.
I have only been working with it a couple of days and i can see all the features that you have already implemented, is just awesome

Now, I would like to comment about an issue im having with the  pixelscan test, which I believe is the reason behind my script is also not passing a turnstile captcha. Im Actually using an authenticated proxy to connect to chrome, wich is working fine with the ip spoofing but is not hidding the timezone correctly on my Chromium.

![image](https://github.com/seleniumbase/SeleniumBase/assets/30813101/9fdc2d69-99fd-46af-94dc-ffdb3a383dc4)

![image](https://github.com/seleniumbase/SeleniumBase/assets/30813101/7a22a7fa-12b1-418f-bc32-c5059175b7da)

These images can tell you what im talking about, i were looking for some solutions on stack and i found this thread.
https://stackoverflow.com/questions/44688079/how-do-i-set-a-timezone-in-selenium-chromedriver

Tried some of the solutions proposed there but without results. As I understand it, the change must be made at the time of instantiating the drive. Tried to pass the Timezone args trough the chromium arg but also failed.
`
    with SB( uc=True, proxy=proxy_url, incognito=True, chromium_arg="TZ=America/New_York") as sb:
    ....
`

So, my question is, do you have any approach to make this work?
maybe is about my chromium driver version or my js version? 

EDIT: my proxy ip is located on US
```
IP address
72.46.136.154 (United States)
ISP: Comcast Cable
User Type by IP: hosting
```

**Comment by mdmintz** [comment]
Timezone spoofing: https://github.com/seleniumbase/SeleniumBase/issues/918#issuecomment-864054769

```python
tz_params = {'timezoneId': 'America/New_York'}
self.driver.execute_cdp_cmd('Emulation.setTimezoneOverride', tz_params)
```
(From https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setTimezoneOverride)

Also more info in this discussion already: https://github.com/seleniumbase/SeleniumBase/discussions/2464

**Comment by Juanfra24** [comment]
strange, I could swear I tried that, thanks i will follow the discussion 😃
