### ISSUE TITLE
How to open a file *.html?

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2701]
Hello,

I am trying to access to a file but it is giving me an error:

`ERROR - Invalid URL: "/output/html/my_html.html"!`

How could I do that? Thank you

**Comment by mdmintz** [comment]
Pass the file path to the load_html_file() method. See the example: https://github.com/seleniumbase/SeleniumBase/blob/e2c3a5e44285dd5b2bbc90c635d2517e72427ba3/examples/offline_examples/test_demo_page.py#L13
