### ISSUE TITLE
Excessive CPU and RAM usage

### ISSUE THREAD

**Issue by Ashish3080** [seleniumbase/SeleniumBase#2744]
While trying to record and playback browser actions, the recorder after 2-3 trials starts to occupy the entire RAM which inevitably makes the entire system slow. I tried it on different systems, but the issue still persists. Any solution for that?
For recording I am using :- sbase mkrec my_test.py --url=imdb.com
For playback I am using :- pytest my_test.py

**Comment by mdmintz** [comment]
I'm unable to reproduce that. Be sure to finish your recordings by typing `c` in the console and pressing `Enter` to continue from the Python `breakpoint()`.

**Comment by Ashish3080** [comment]
is there any other way to stop the recording other than entering c?

**Comment by mdmintz** [comment]
You can use the Recorder without manual intervention. For example:

```bash
pytest --rec
```

That runs the Recorder on scripts, which optimizes the selectors that were used.

To print the results / output immediately, use:

```bash
pytest --rec-print
```
