### ISSUE TITLE
Not able to Login on ticketmaster

### ISSUE THREAD

**Issue by waysiPire0** [seleniumbase/SeleniumBase#2750]
i am trying with syntax "SeleniumBase SB (Python context manager)". I am trying to login on ticketmaster website. but everytime i filled the login form, the px-captcha appear. i tried both methods (manual and automated) to solve this "press and hold"  captcha. but it reppear again and again.

My code:
<img width="907" alt="Screenshot 2024-05-05 at 3 56 04 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/63053679/dec131e0-427a-41ca-af24-33da42310e06">

captcha:
<img width="941" alt="Screenshot 2024-05-05 at 4 01 04 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/63053679/b2672e56-5d53-47a3-aeaf-08f23c14382c">

**Comment by mdmintz** [comment]
How to press and hold in Selenium Python:
[https://stackoverflow.com/questions/68636955/how-to-long-press-press-and-hold-mouse-left-key-using-only-selenium-in-python](https://stackoverflow.com/a/68848948/7058266)

How to press and hold in JavaScript: (Use `sb.driver.execute_script()` to call JS from Python.)
[https://stackoverflow.com/questions/64068697/how-to-simulate-a-hold-click-on-a-button-class](https://stackoverflow.com/a/64068910/7058266)

**Comment by waysiPire0** [comment]
@mdmintz 
is it not possible that the website not mark the browser as bot and this captcha not be shown ?

**Comment by mdmintz** [comment]
Make sure you optimized the launch command.
(See [examples/raw_pixelscan.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_pixelscan.py), which needed both `uc=True` and `incognito=True` to maximize stealth on that website.)
