### ISSUE TITLE
--use-file-for-fake-audio-capture doesn't working

### ISSUE THREAD

**Issue by pyleo-1998** [seleniumbase/SeleniumBase#2777]
I wantes to get all the sounds packets that were received and send from the google chrome and for that i have found one solution that listed over here 

https://groups.google.com/g/discuss-webrtc/c/T4n2kwYKm9Y

its says to use the `--use-file-for-fake-audio-capture` flag in selenium
so i have passed  `chromium_arg = "--use-file-for-fake-audio-capture=/home/chrome_audio/audio.wav"` with `uc=True`
its just not working even i have tried passing `chromium_arg = "use-file-for-fake-audio-capture=/home/chrome_audio/audio.wav"`
still no luck.
For more information you can refere

chrome://webrtc-internals/
https://stackoverflow.com/questions/50759376/use-file-for-fake-audio-capture-doesnt-play-on-google-com

**Comment by mdmintz** [comment]
This may be due to a Chromium issue: https://issues.chromium.org/issues/40662946

Also, see the StackOverflow question: https://stackoverflow.com/q/50774560/7058266

This is not a SeleniumBase-specific issue.
