### ISSUE TITLE
seleniumbase uc with proxy on ubuntu (linux) problem

### ISSUE THREAD

**Issue by AmirHosseinJ** [seleniumbase/SeleniumBase#2779]
Without a proxy things are nice but as soon as I add a proxy on Ubuntu there is a text on Chrome. Moreover, I used headless and virtual displays but the same result is always there. I have attached a screenshot taken by selenium from chrome in headless mode since there is no "headed" mode available in get_new_driver method.
here is my driver setup
`driver = self.sb.get_new_driver(undetectable=True,
                                            # uc_subprocess=True,
                                            user_data_dir=self.user_chrome_data_dir,
                                            # headless2=True,
                                            incognito=True,
                                            proxy=proxy_combo)`
![ACCEPT TEST](https://github.com/seleniumbase/SeleniumBase/assets/47473216/82fed960-b54e-44bc-999b-38984588b217)

**Comment by mdmintz** [comment]
Can't reproduce this. Could be an issue with your `proxy` or your `user_data_dir`. (Note that you can't use a `user_data_dir` from a regular Chrome instance because it's not compatible with UC Mode `user_data_dir`.)

Also, for Linux, you may want to use `xvfb=True`.
