### ISSUE TITLE
Asking for the implementation of a method that gets the response status code 

### ISSUE THREAD

**Issue by Eliobosdet** [seleniumbase/SeleniumBase#2781]
Hello, since i'm using SeleniumBase with the undetected chromedriver mode (UC mode) and my goal is to get the content of the sites that are protected with a captcha, i have some problems to understand whenever the request failed and more specifically why it failed. For this i can't just check the HTML content by doing: "sb.driver.get_page_source()". 
I know that selenium was born to be used as an web automator but if it would be possible to add this feature i would be super grateful.
Thabk you in advance!

**Comment by mdmintz** [comment]
It sounds like you're looking for https://pypi.org/project/requests/.

(SeleniumBase does everything through a web browser.)
