### ISSUE TITLE
Wire Mode: `No module named 'blinker._saferef'` if installing `selenium-wire` alone

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2782]
### Wire Mode: `No module named 'blinker._saferef'` if installing `selenium-wire` alone.

----

Wire Mode (`--wire` / `wire=True`) uses the `selenium-wire` library. The `selenium-wire` library has a dependency on `blinker`. The latest version of `blinker` no longer has `blinker._saferef`, which `selenium-wire` needs. This leads to `ModuleNotFoundError: No module named 'blinker._saferef'`.

Since https://github.com/wkeeling/selenium-wire is no longer maintained (and therefore won't make changes or pin dependencies) it's up to `SeleniumBase` to make the necessary changes. One way is by forcing `blinker==1.7.0`, which does not have the issue.

Because Wire Mode is optional, I don't want to create a dependency on `blinker==1.7.0` in the standard SeleniumBase dependencies. Instead, this issue can be fixed by automatically installing `blinker==1.7.0` in Wire Mode if that is not the current version of `blinker`.

**Comment by mdmintz** [comment]
This was resolved in `4.27.0` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.27.0

**Comment by doscode-kr** [comment]
Thank you for the detailed explanation.

**Comment by rkiddy** [comment]
Thank you for adding the note about the work-around for selenium-wire. It is pretty amazing that I was able to search for a fix, easily find this and, you know, it just worked. I am a bit shocked. Wonderful job. :--)
