### ISSUE TITLE
CloudFlare verification not working under VPN

### ISSUE THREAD

**Issue by bjornkarlsson** [seleniumbase/SeleniumBase#2793]
The following code works on a direct connection (no verification asked), however when using VPN (or an http proxy, NordVPN in my case) clicking on the verification box doesn't let the verification go through:

```python   
    
    URL = 'https://rateyourmusic.com/artist/pink-floyd/'
    with SB(uc=True) as sb:
        sb.driver.uc_open(URL)
        if sb.is_element_visible('iframe[src*="challenge"]'):
            iframe = sb.find_element('iframe[src*="challenge"]')
            sb.driver.switch_to.frame(iframe)
            confirm_input = sb.driver.find_element(By.CSS_SELECTOR, 'input')
            confirm_input.click()
            sb.sleep(2)
```

I have tried other libraries with undected capabilities through VPN, and while most didn't go through I was able to go past the verification box with https://github.com/kaliiiiiiiiii/Selenium-Driverless.

Anyone else experienced a similar behaviour?

**Comment by mdmintz** [comment]
I used the script below and didn't encounter any CAPTCHAs:

```python
from seleniumbase import SB

with SB(uc=True, ad_block_on=True) as sb:
    url = "https://rateyourmusic.com/artist/pink-floyd/"
    sb.driver.uc_open_with_reconnect(url, 8)
```

Also, whenever you need to click in UC Mode, use `sb.driver.uc_click(selector)` to remain undetected.
(That'll work unless they already detected you in a previous step.)

**Comment by bjornkarlsson** [comment]
Unfortunately, this does not solve the issue, the problem occurs only when using a VPN connection or an https Proxy. So it needs to be tested under a VPN (my provider is NordVPN) otherwise there is no issue on a direct connection.

On a VPN:

The verification box excepts a click from the user.
After the checkbox input is being clicked from the driver it attempts a verification for a few seconds (spinning wheel), however it ends up on the input box being unchecked expecting for a retry of this process

**Comment by mdmintz** [comment]
NordVPN isn't supported. That can prevent regular browsers from failing to bypass CAPTCHAs too.

Even the original `undetected-chromedriver` had that issue. (See https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1441#issuecomment-1671905938 and https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1387#discussioncomment-6552952)

**Comment by dipstef** [comment]
Thanks for your reply, at the moment i haven't experienced being blocked both on regular browser when regular navigating the site and on bot using Selenium-driverless.

The examples verification website validate fines under VPN:
https://nowsecure.nl/

Are CloudFlare verification configurable per site basis or have they implemented stronger verification policies for certain sites?

**Comment by bjornkarlsson** [comment]
Thanks for looking into this! Only wanted to see if there was a change with seleniumbase as otherwise I would need to rewrite everything in an async mode :D by using selenium-driverless which seems to work

**Comment by mdmintz** [comment]
Possibly it was related to the part where the VPN hides your IP:

<img width="590" alt="Screenshot 2024-05-21 at 3 54 22 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/61dda986-483e-4fd3-9dc6-a4be123df78e">

--

If the VPN replaces your IP with another IP that was already flagged as a bot, then a site may flag you as a bot.

**Comment by bjornkarlsson** [comment]
The things that confuses me is that gitlab login verification passes under VPN after clicking captcha using seleniumbase, nowsecure.nl does not even ask for captcha.

Not sure wether Cloudflare bot detection can be configured per site or there are different levels of detection.

**Comment by mdmintz** [comment]
I'm not sure about Cloudflare configuration on a site-by-site basis, but I am familiar with how to bypass it. 🙂

**Comment by bjornkarlsson** [comment]
Are you aware of any resource/documentation that explains how to bypass Cloudflare verification, or better dig in the source code?

As both the regular browser and driverless chrome escape the checks (NordVPN has also HTTPS proxies that could be used as chrome plugin which work fine as well in that site) and being a stubborn engineer which would probably prefer dig in dirt than rewrite my bots with async selenium-driverless I want to give it a chance 😄 

Greetings!

**Comment by mdmintz** [comment]
To figure out why you were detected, run this script: [SeleniumBase/examples/raw_pixelscan.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_pixelscan.py)

----

To learn more about how UC Mode works for bypassing Cloudflare, check out these videos:

<a href="https://www.youtube.com/watch?v=5dMFI3e85ig"><img src="http://img.youtube.com/vi/5dMFI3e85ig/0.jpg" title="SeleniumBase on YouTube" width="250" /></a>
<p>(<b><a href="https://www.youtube.com/watch?v=5dMFI3e85ig">Watch the 1st UC Mode tutorial on YouTube! ▶️</a></b>)</p>

--

<a href="https://www.youtube.com/watch?v=2pTpBtaE7SQ"><img src="http://img.youtube.com/vi/2pTpBtaE7SQ/0.jpg" title="SeleniumBase on YouTube" width="250" /></a>
<p>(<b><a href="https://www.youtube.com/watch?v=2pTpBtaE7SQ">Watch the 2nd UC Mode tutorial on YouTube! ▶️</a></b>)</p>

**Comment by bjornkarlsson** [comment]
watched both vids, very helpful, even have enjoyed the videos ;)
