### ISSUE TITLE
Best practice open new tab (multiple tab)

### ISSUE THREAD

**Issue by adarmawan117** [seleniumbase/SeleniumBase#2796]
Is there any best way to open multiple tab.?
For example:
I have a page that contain links. And then i want to extract all link, and open it in new tab, without close first page.

This is my code
```
elements = self.sb.find_elements('//a[contains(text(), "members")]')
for elem in elements:
    group_link = elem.find_element('xpath', './/parent::div//parent::div//parent::span//parent::div//parent::div/div[1]/a').get_attribute('href')
    self.sb.driver.uc_open_with_tab(group_link) # here i want to open the new tab
```

Thanks

**Comment by mdmintz** [comment]
For UC Mode, don't use multiple tabs. That'll either get you detected, or break tab order.
Instead, use multiple drivers. Example:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "seleniumbase.io/demo_page"
    sb.driver.uc_open_with_reconnect(url)
    links = sb.get_unique_links()
    for link in links:
        driver2 = sb.get_new_driver(undetectable=True)
        driver2.uc_open_with_reconnect(link)
        print(driver2.title)
        sb.quit_extra_driver()
```

**Comment by pankajkalania** [comment]
I don't want to use multiple tabs, but want to refresh existing tab with a new one. Can i do that without creating a new driver?

**Comment by mdmintz** [comment]
There's a CDP Mode example that deals with multiple tabs:
* [SeleniumBase/examples/cdp_mode/raw_tab_switching.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/raw_tab_switching.py)

**Comment by pankajkalania** [comment]
Okay. Also, you mentioned that opening multiple tabs can get me detected. Will below scenario get detected as well?
1. Start a crawling process in a tab
2. Close and open a new one after process is complete
3. start a new crawling process in the new tab
In short, does refreshing tab help in better success rate?

**Comment by mdmintz** [comment]
> Okay. Also, you mentioned that opening multiple tabs can get me detected. Will below scenario get detected as well?
> 
> 1. Start a crawling process in a tab
> 2. Close and open a new one after process is complete
> 3. start a new crawling process in the new tab
>    In short, does refreshing tab help in better success rate?

@pankajkalania It all may depend on the website itself. You'll have to experiment.
