### ISSUE TITLE
nodriver in seleniumbase

### ISSUE THREAD

**Issue by FRIKIdelTO** [seleniumbase/SeleniumBase#2798]
I love seleniumbase and since I discovered it, as far as selenium goes, I haven't used anything else since, but I have recently discovered [nodriver](https://github.com/ultrafunkamsterdam/nodriver) and I am amazed at the speed with which the results come...
Would it be possible to implement nodriver in seleniumbase?

**Comment by mdmintz** [comment]
You can use Syntax Format 9 for that: [SeleniumBase/help_docs/syntax_formats.md#sb_sf_09](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_09)
