### ISSUE TITLE
page_actions.wait_for_text_visible does not work with tags

### ISSUE THREAD

**Issue by frafra** [seleniumbase/SeleniumBase#280]
This code should fail, but it does not.

```python3
page_actions.wait_for_text_visible(self.driver, "bad-string", "title")
```

Same behavior when using other tags, like `p`.
That happens when ` if element.is_displayed():` is false. There is an `else` missing there.

**Comment by mdmintz** [comment]
PR merged! Thanks! (Will be added to the release tonight)
