### ISSUE TITLE
Is it possible to use seleniumbase with selenium-requests?

### ISSUE THREAD

**Issue by mvx20** [seleniumbase/SeleniumBase#2807]
Can I use selenium-request's RequestsSessionMixin module with seleniumbase?

<img width="786" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/88004617/9d27a1ee-671b-4c3e-8c94-b41db2b4c75b">

or does Seleniumbase have its own functions that we can request ?  
I want to enter the site with seleniumbase and do the rest of the operations with request via driver.

**Comment by mdmintz** [comment]
It might support it, but there's also a `selenium-wire` integration for that: https://github.com/seleniumbase/SeleniumBase/issues/2145.

Also see: https://github.com/seleniumbase/SeleniumBase/issues/2774#issuecomment-2110911078.
