### ISSUE TITLE
Website detected - uc mode

### ISSUE THREAD

**Issue by jkoestner** [seleniumbase/SeleniumBase#2815]
I've recently had my bot detected on a website. It was working for a few months, but has recently seemed to be flagged. I'm not sure if this is just a product of tighter security. I've done a few tests. Any direction would be appreciated. Thanks!

**packages**
- seleniumbase: 4.27.0
- Chromium 125.0.6422.112 built on Debian 12.5, running on Debian 12.5

First I checked pixelscan.net to see what may be causing the website to flag. This seems ok to me because it states "no automation framework detected"

```python
with SB(
        uc=True,
        headless2=True,
        proxy=proxy,
    ) as sb:
        url = "https://pixelscan.net/"
        sb.driver.uc_open_with_reconnect(url, 20)
        sb.sleep(10)
        sb.driver.save_screenshot('folioflex/configs/pixel.png') 
```

![pixel](https://github.com/seleniumbase/SeleniumBase/assets/50647092/4ca1da1d-53f9-4226-bcc8-aeb47b0837cb)

I then saved a screenshot of how the website is flagging the bot. The code below does work on a laptop using chrome, but does not work on a linux server running docker using chromium.

```python
with SB(
        uc=True,
        headless2=True,
        proxy=proxy,
    ) as sb:
        url = "https://www.wsj.com/livecoverage/stock-market-today-dow-jones-earnings-05-30-2024?mod=lctimeline_finance_viewall"
        sb.driver.uc_open_with_reconnect(url, 20)
        sb.sleep(15)
        sb.driver.save_screenshot('folioflex/configs/bot.png')
```
![bot](https://github.com/seleniumbase/SeleniumBase/assets/50647092/10bdba73-07d1-460c-941b-c1bd98f82c48)

**Comment by mdmintz** [comment]
Same answer as https://github.com/seleniumbase/SeleniumBase/discussions/2802#discussioncomment-9555175:

For UC Mode, you have to use regular chrome, not chromium. The binary would be called `google-chrome` or `google-chrome-stable` on Linux.
