### ISSUE TITLE
Proxy and wire

### ISSUE THREAD

**Issue by kitsune0n** [seleniumbase/SeleniumBase#2819]
[By this manual](https://seleniumbase.io/help_docs/method_summary/#seleniumbase-methods-api-reference) when trying add flag user_wire=True in my python code and sb.set_wire_proxy(proxy_string) ip don't changed.
And as alternative trying use proxy= . tha's works and ip changed but after few minutes have popup with auth required for proxy

**Comment by mdmintz** [comment]
These are the docs you're looking for: https://github.com/seleniumbase/SeleniumBase/issues/2145

For changing the proxy in Wire Mode (`wire=True` / `--wire`):

```python
driver.set_wire_proxy(string)
```

Where the proxy string formats are: `host:port` or `user:pass@host:port`.

You can also change the proxy without Wire Mode by using `proxy="string"` / `--proxy="string"`.

**Comment by kitsune0n** [comment]
can i use UC mode with wire proxy ?
or selenium-stealth with wire proxy ?
when i try use uc and proxy= . tha's works and ip changed but after few minutes have popup with auth required for proxy

> These are the docs you're looking for: #2145
> 
> For changing the proxy in Wire Mode (`wire=True` / `--wire`):
> 
> ```python
> driver.set_wire_proxy(string)
> ```
> 
> Where the proxy string formats are: `host:port` or `user:pass@host:port`.
> 
> You can also change the proxy without Wire Mode by using `proxy="string"` / `--proxy="string"`.
> 
> Also, duplicate of [#1807 (comment)](https://github.com/seleniumbase/SeleniumBase/issues/1807#issuecomment-1472800048)

**Comment by kitsune0n** [comment]
when using uc=True, proxy=proxy_string
proxy in format username:password@ip:port 
have this popup
![Screenshot 2024-06-02 021258](https://github.com/seleniumbase/SeleniumBase/assets/48809760/5e443200-28d9-451f-965a-010a65b7bdb0)
butt if i check proxy in this session by google, it works

**Comment by mdmintz** [comment]
You can't combine Wire Mode with UC Mode: https://github.com/seleniumbase/SeleniumBase/issues/2145#issuecomment-1788890241.

As for UC Mode and Proxy Mode, it works for me. Not sure what you're doing. Maybe you gave it a bad proxy or the username/password was invalid.
