### ISSUE TITLE
UC mode and proxy

### ISSUE THREAD

**Issue by kitsune0n** [seleniumbase/SeleniumBase#2820]
when using uc=True, proxy=proxy_string
proxy in format username:password@ip:port
have this popup
![Screenshot 2024-06-02 021258](https://github.com/seleniumbase/SeleniumBase/assets/48809760/4627e1a9-a611-4a61-b6de-4919fb14b1b9)
butt if i check proxy in this session by google, it works

**Comment by mdmintz** [comment]
UC Mode and Proxy Mode together is working for me. By the looks of it, you're trying to use it on a Chrome Extension page (`chrome-extension://`). UC Mode must be used on a URL that starts with either `http` or `https`. The proxy settings are set via a standalone Chrome extension. There's already a lot of info in the SeleniumBase docs regarding UC Mode and proxies.
