### ISSUE TITLE
Don't bypass cloudware

### ISSUE THREAD

**Issue by steve140298** [seleniumbase/SeleniumBase#2826]
Hi! I have a problem with bypassing cloudware.
 `import time
from seleniumbase import SB
from selenium_stealth import stealth
from seleniumbase import page_actions

proxy = 'CFKaEA:4fQF98@217.29.63.91:10931'
with SB(uc=True,  proxy=proxy, user_data_dir=r"C:\Users\Степан\AppData\Local\Google\Chrome\User Data\4") as sb:
    stealth(sb.driver,
            languages=["en-US", "en"],
            vendor="Google Inc.",
            platform="Win32",
            webgl_vendor="Intel Inc.",
            renderer="Intel Iris OpenGL Engine",
            fix_hairline=True,
            )
url = 'https://aviso.bz/work-youtube'
    sb.driver.uc_open_with_reconnect(url, 3)
    cl = sb.find_element('//*[starts-with(@id, "link_ads")]')
cl.uc_click()
`time.sleep(5000)`
I click on url , then open 2nd window with cloudware captcha, and it think , that i am bot.

**Comment by mdmintz** [comment]
Your link, https://aviso.bz/work-youtube, redirects to https://aviso.bz/login, so I can't help.
For a more stealthy click, use `sb.driver.uc_click(selector)` with a CSS Selector.
