### ISSUE TITLE
Element is not clickable at point (916, 785)

### ISSUE THREAD

**Issue by marconimedeiros2** [seleniumbase/SeleniumBase#2827]
How to solve it?

Normally I would solve resizing the window, clicking by xpath, etc, but I cant found how to do it with SB.

Anyone can help me?

The element:
`
driver.click("//*[@id='sendButton']")`

**Comment by mdmintz** [comment]
Use `driver.js_click(selector)` with a CSS Selector when that happens.

In your case, it would be:
`driver.js_click("#sendButton")`
