### ISSUE TITLE
"You can open bookmarks..." pop-up is now appearing since Chrome 125.

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2836]
## "You can open bookmarks..." pop-up is now appearing since Chrome 125.

Full text: `You can open bookmarks, reading mode, and more from the Chrome menu`.

<img width="373" alt="Screenshot 2024-05-24 at 12 11 53 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/df6f4202-be74-4477-9373-e9e066facc92">

It must be purged from Chrome browsers during tests, as it is quite annoying to users.

There's likely a Chrome option to prevent the side panel from getting pinned like that.

**Comment by mdmintz** [comment]
This was resolved in `4.27.4` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.27.4

**Comment by luckman212** [comment]
Can anyone tell me what option(s) I need to supply to disable this? It pops up seemingly randomly, about 20-30% of the time...

I'm using chromedriver 126.0.6478.126

```py
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument(...) <== what goes here
```

**Comment by mdmintz** [comment]
@luckman212 Which version of SeleniumBase are you using? It's fixed in the latest.

**Comment by luckman212** [comment]
Thanks @mdmintz — 4.22.0 I think? I'm using Python venv and installed via `pip install selenium`. This could be an ID 10T/PEBKAC problem for sure, as I'm just getting started.

```
$ pip list --local --format=json | jq 'map(select(.name|test("selenium")))[]'
{
  "name": "selenium",
  "version": "4.22.0"
}
```

**Comment by mdmintz** [comment]
@luckman212 I think you're looking for: https://github.com/SeleniumHQ/selenium.
This is the SeleniumBase repo - (https://github.com/seleniumbase/SeleniumBase).

That popup won't appear in the latest version of SeleniumBase, (which is`4.28.0`).

**Comment by luckman212** [comment]
Oh dear. How embarrassing (for me). I apologize, but glad I accidentally stumbled in here. SeleniumBase looks awesome!

**Comment by Devatron777** [comment]
Ok
But we do not have the answer how to avoid this popup.
Any idea please ?

**Comment by murtu-stack** [comment]
> Oh dear. How embarrassing (for me). I apologize, but glad I accidentally stumbled in here. SeleniumBase looks awesome!

have u been able to fix that pop using selenium and not selenium base that pop up of bookmarks is coming in chrom version 126

**Comment by pimterry** [comment]
For everybody else landing here looking for the option to disable this, it's hidden in the PR above - the Chromium feature is called 'SidePanelPinning' and you can disable it with `--disable-features=SidePanelPinning`
