### ISSUE TITLE
"Choose your search engine" google chrome popup

### ISSUE THREAD

**Issue by MiMaPr** [seleniumbase/SeleniumBase#2839]
Since this week this popup appears, which seems to be very similar to the popup about privacy which could be solved with this argument: --add_argument('--disable-features=PrivacySandboxSettings4').

Maybe someone has a clue how to get past this one. The html tag is "search-engine-choice-app".

Thanks in advance

![image](https://github.com/seleniumbase/SeleniumBase/assets/103506985/99f6cd38-328f-4775-b5ac-3b2593b8156c)

![image](https://github.com/seleniumbase/SeleniumBase/assets/103506985/031de0bc-a3d9-4162-9055-3e740c39815b)

**Comment by mdmintz** [comment]
It may happen for regular Selenium users (https://support.google.com/chrome/thread/278310235/choose-your-search-engine-pop-up-shown-while-default-engine-is-already-chosen?hl=en) but I'm not seeing it with SeleniumBase. I think the existing options take care of it.

If you're seeing it in SeleniumBase, I'll need a minimal script to reproduce it, and the run command you used.

You can also probably use `--guest` mode to hide it. (`--incognito` probably works too)

**Comment by mdmintz** [comment]
@Kylian-Project   I'm not seeing the issue.
Which version of SeleniumBase are you using? Have you tried on the latest version?

**Comment by Kylian-Project** [comment]
> @Kylian-Project I'm not seeing the issue. Which version of SeleniumBase are you using? Have you tried on the latest version?

I'm sorry, I've deleted my message, because I didn't have the right version of seleniumbase. Sorry for the inconvenience :)
