### ISSUE TITLE
New Chrome break the remote_debug?

### ISSUE THREAD

**Issue by guocity** [seleniumbase/SeleniumBase#2853]
After update to chrome Version 126.0.6478.62, remote_debug in seleniumbase is broken, 
with WARNING: Unable to get screenshot!
<img width="348" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/1127820/36f5fe04-7c3e-478b-83c5-4f60d626244a">

**Comment by mdmintz** [comment]
I didn't encounter any issues when I used it. Make sure port `9222` is free.

<img width="600" alt="Screenshot 2024-06-14 at 4 27 15 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/50de61c6-4718-4a60-a047-198d5709b102">

**Comment by guocity** [comment]
interesting, the new chrome driver sometimes work, sometimes not, that's really weird, not sure where the issue is

**Comment by guocity** [comment]
before it will always use existing chrome process with port 9222, with new chrome update, it will start a new chrome process, instead of using existing chrome process

**Comment by mdmintz** [comment]
Make sure there isn't an existing process using port 9222. `remote_debug` is for debugging a browser that is spun up with remote_debug enabled at launch.

**Comment by guocity** [comment]
yea it work perfectly well, not a single issue, until chrome v126, 
I have remote session started at
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
with version 126, chrome driver sometimes use this session, but most of the time it will launch a new chrome process,

**Comment by mdmintz** [comment]
Maybe an issue with Chrome 126. Nothing changed there on the SeleniumBase side.

**Comment by guocity** [comment]
Yea, I can see change history, just really hate this annoying chrome driver bug, 
<img width="1113" alt="image" src="https://github.com/seleniumbase/SeleniumBase/assets/1127820/f38ce622-26c3-4c65-96b9-68a4acbd0a6c">

**Comment by guocity** [comment]
is there anyway to downgrade chromedriver?

sbase get chromedriver 125.0.6422.141

but when I run the sb it will automatically upgrade

Warning: chromedriver update needed. Getting it now:
*** chromedriver to download = 126.0.6478.63 (Latest Stable)

**Comment by mdmintz** [comment]
https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/customizing_test_runs.md#-changing-the-default-driver-version

https://github.com/seleniumbase/SeleniumBase/blob/3bb813fe039448b0c6bb2ff043266295cb40220a/seleniumbase/plugins/sb_manager.py#L77

**Comment by guocity** [comment]
I reset the chrome setting, seems like problem solved
