### ISSUE TITLE
HTTP Request Interception

### ISSUE THREAD

**Issue by namename-123** [seleniumbase/SeleniumBase#2871]
I'm trying the code below and it keeps giving me the following error: `No module named 'blinker._saferef'`
How can I fix it? Also it would be great if I could change the request's parameters/headers, like changing a certain header before continuing the request like in playwright/puppeteer.

```from seleniumbase import Driver

def intercept_response(request, response):
    print(request.headers)

driver = Driver(wire=True)
try:
    driver.response_interceptor = intercept_response
    driver.get("https://wikipedia.org")
finally:
    driver.quit()```

**Comment by mdmintz** [comment]
Run `pip install blinker==1.7.0` to downgrade blinker for `selenium-wire`, or upgrade to a newer version of `seleniumbase`, which will automatically install the correct version of `blinker` at runtime when using Wire Mode.

(`selenium-wire` is an external library used by `seleniumbase` in Wire Mode)
