### ISSUE TITLE
--window-size Does Not Work for Driver initialization.

### ISSUE THREAD

**Issue by oniononion36** [seleniumbase/SeleniumBase#2872]
When I pass chromium_arg='--window-size=1000,1000' into Driver, the argument gets split up into `--window-size=1000` and `--1000`, and is subsequently ignored at browser start up.

**Comment by mdmintz** [comment]
Window size can be set ***after* the browser has been launched**:

```python
driver.set_window_size(700, 700)
```

**Comment by PankajSavaliya** [comment]
```
  driver = Driver(uc=True, agent=generate_random_mobile_user_agent(False),
                    chromium_arg="--window-size:280,653")
 ```
 
 @mdmintz 
 I have set like above snippet even not set size, if I used 
 
 `driver.set_window_size(1000, 1000)`
 
 then it's work but I want to set in chromium_arg, can you please give me a sample of how to set .
