### ISSUE TITLE
seleniumbase with proxy 

### ISSUE THREAD

**Issue by Akshay-Shingala** [seleniumbase/SeleniumBase#2874]
I write a seleniumbase script using a proxy from some proxy provider.
if I don't use a proxy, UC mode can easily bypass it, but if I use a proxy, it blocks my proxy. but sometimes it allows me to bypass it.
Cloudflare may detect me as a bot because I use a proxy provider.
what can I do?
can you suggest any good proxy provider names?

**Comment by mdmintz** [comment]
There may be a problem with your proxy provider. This is not a proxy-provider-suggestion-service. You'll have to find your own valid proxies to use.

Supported `proxy` formats:

* `proxy="user:pass@ip:port"`
* `proxy="ip:port"`

(`ip` can be an IP Address or a domain)

You also mentioned that you're able to bypass Cloudflare without a proxy... that's great! Then maybe you don't need to use a proxy if things work for you without one.
