### ISSUE TITLE
'Chrome' object has no attribute 'scroll_to'

### ISSUE THREAD

**Issue by PankajSavaliya** [seleniumbase/SeleniumBase#2897]
I'm using a Mac with seleniumbase==4.28.3, and this script for multi-threading that's why unable to use SB object directly, can you please how to scroll_to method use instead of using execute_script for scrolling?

```
def random_scroll(driver):
    # Get the dimensions of the web page
    page_width = driver.execute_script("return document.body.scrollWidth")
    page_height = driver.execute_script("return document.body.scrollHeight")

    # Generate random coordinates within the page dimensions
    random_x = random.randint(0, page_width)
    random_y = random.randint(0, page_height)

    # Scroll to the random coordinates
    driver.scroll_to(random_x, random_y)

    # Optionally, wait to see the result
    driver.sleep(5)  # Wait for 5 seconds to see the scroll effect


def launch_driver(url):
    width, height = get_device_size()
    arg = [f'--window-size:{width},{height}', ]

    driver = Driver(uc=True,)
   
    try:

        driver.uc_open(url)
        driver.uc_gui_handle_cf()

        random_scroll(driver)

        driver.sleep(50)
        print("done")

    except Exception as e:
        print(e)
    finally:
        driver.quit()
```

**Comment by mdmintz** [comment]
Using `execute_script` is the standard way for scrolling via the `driver`:

Scrolling to coordinates: https://stackoverflow.com/a/27760083/7058266

``driver.execute_script("window.scrollTo(0, Y)")``  (Where `Y` is the height)

``driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")``

Or to scroll to a specific element via the SeleniumBase `driver`:

```python
element = driver.find_element(selector)
element.location_once_scrolled_into_view
```

**Comment by PankajSavaliya** [comment]
@mdmintz I show **selector**, can you please explain what is it? I'm very new and using this lib and I'm enjoying so I want to clarify everything. 

```
random_elems = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.XPATH, random_elem_xpath))
        )
        random.shuffle(random_elems)
        an_elem = random.choice(random_elems)
        try:
            scroll_to_element(driver, an_elem)
            driver.sleep(1)
            print(an_elem)
            sb.uc_click(an_elem)
```

error

```
Not Clickable random Element: Invalid selector type: "<class 'seleniumbase.undetected.webelement.WebElement'>"
```

not working that uc_click that's why I need to understand what is selector.

**Comment by mdmintz** [comment]
It looks like you're mixing formats. See [SeleniumBase/help_docs/syntax_formats.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md)

The raw `driver` comes from Selenium (https://github.com/SeleniumHQ/selenium) not SeleniumBase (https://github.com/seleniumbase/SeleniumBase). Also, any `WebElement` object only has the raw Selenium / `driver` methods.

SeleniumBase formats (`SB`, `BaseCase`) have their own API: [SeleniumBase/help_docs/method_summary.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md).

Some SeleniumBase methods have been back-ported into the `driver` (most have not, and won't be).

With SeleniumBase, you **don't** need to use `WebDriverWait`, `presence_of_all_elements_located`, etc, because of the automatic waiting. See [the examples](https://github.com/seleniumbase/SeleniumBase/tree/master/examples), and learn the correct way to structure your tests. The non-pytest formats will start with `raw_` in the filename.

**Comment by PankajSavaliya** [comment]
Oh, thank you so much! I'm just moving my code to SB, which is why it's mixing up. While I understand everything, I'll make sure all things will be used in SB.

can you please update my above raw Selenium code to SB? I'm very appreciate of that. @mdmintz

**Comment by mdmintz** [comment]
This isn't https://stackoverflow.com/.
People can learn from the SeleniumBase Docs (and the [many examples](https://github.com/seleniumbase/SeleniumBase/tree/master/examples)) and write their own scripts.

**Comment by PankajSavaliya** [comment]
> @mdmintz I have checked and searched there is no demo on the scroll function, kindly share that specific link, even no document on the selector, how to use it, and all. please share the document instead of the video. document will be easy to save and reuse. it's very difficult for me because I'm moving from Selinum to [SeleniumBase](https://github.com/seleniumbase/SeleniumBase). please help.
> 
> I'm using for UC mode, so is there any different method for scrolling for undetected bots? right now I'm exploring scroll_to,scroll_to_element,scroll_into_view, so is there do I need to connect and reconnect method use? as I don't know much about these methods that's why asking you. look at this [question](https://github.com/seleniumbase/SeleniumBase/issues/2896#issuecomment-2203136451).
> 
> ```
> elements = sb.driver.find_elements(value=random_elem_xpath, by='xpath')
> random.shuffle(elements)
> elements[0].uc_click()
> ```
> 
> `scroll=True` is missed in `uc_click()`
> 
> then I want to scroll in UC mode, with this I can get the list of elements in, and one of the elements will pick and scroll to the element that I want if a click is required then I want to click also (UC mode).

could you please explain how to scroll to `elements[0]`?

**Comment by mdmintz** [comment]
Once you find a `WebElement` and want to perform actions on it, you are dealing with the Selenium (https://github.com/SeleniumHQ/selenium) API, not the SeleniumBase (https://github.com/seleniumbase/SeleniumBase) one. This repo is for SeleniumBase questions only.

**Comment by PankajSavaliya** [comment]
```
 random_elems = sb.find_elements(value=random_elem_xpath, by='xpath')
 random.shuffle(random_elems)
 an_elem = random.choice(random_elems)
```

now it's SB base element, so is there possibility how to scroll with UC? @mdmintz

**Comment by mdmintz** [comment]
I'm saying that once you call `sb.find_elements`, the result is a list of regular `WebElement` objects, where each one uses the Selenium API. For scrolling, it would be a Selenium API action. Eg. `element.location_once_scrolled_into_view`.

**Comment by mdmintz** [comment]
`sb.disconnect()` disconnects the driver from Chrome. A website cannot detect Selenium while disconnected. While disconnected, you can only perform `pyautogui` actions, as no Selenium actions will work.

`sb.connect()` lets you perform Selenium actions again. You can also get detected when connected.

`sb.reconnect()` is just `sb.disconnect()` + `sb.sleep()` + `sb.connect()`.

**Comment by PankajSavaliya** [comment]
perfect!

so while I interact with scroll, click etc, I need to use each method for connect, disconnect, and reconnect for undetection. 

for scrolling
```
sb.connect() //is this required only for finding the element and finding the location instead of click, scroll and etc?
element = driver.find_element(selector)
location=element.location_once_scrolled_into_view
sb.disconnect()
```
is there any method to scroll as `sb.scroll_to(x,y)` or do I need to modify and add new same as `scroll_to_bottom()`? @mdmintz

**Comment by mdmintz** [comment]
That is done via `execute_script` with `"window.scrollTo(0, Y);"`

**Comment by PankajSavaliya** [comment]
@mdmintz This is a normal script, as I want to move fully to SB with UC. Can we connect on Google Meet for just 10 minutes? I have a few more questions. I would really appreciate it.

**Comment by mdmintz** [comment]
Use spacebar or arrow keys with `pyautogui` to scroll while disconnected. That's the only "stealth" scrolling, if that's what you're looking for.

**Comment by mdmintz** [comment]
It depends what the website is looking for. Maybe it's not looking for scroll actions.
