### ISSUE TITLE
How to handle and dismiss Interstitials Overlay Ads in website?

### ISSUE THREAD

**Issue by PankajSavaliya** [seleniumbase/SeleniumBase#2899]
Hi, I'm new to [SeleniumBase](https://github.com/seleniumbase/SeleniumBase). How can I find an iframe and dismiss overlay ads after clicking on any element on the web, which then triggers an interstitial overlay ad? I want to dismiss this ad by clicking a button.

<img width="1788" alt="Screenshot 2024-07-03 at 5 28 07 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/13134958/f64a2c8f-13d7-4914-abf3-d63c0c3ada22">

**Comment by mdmintz** [comment]
Determine the CSS Selector of the `X` and then click that after switching into the iframe with `sb.switch_to_frame()`

You can also try the `--ad-block` / `ad_block=True` option.

**Comment by PankajSavaliya** [comment]
> Determine the CSS Selector of the `X` and then click that after switching into the iframe with `sb.switch_to_frame()`
> 
> You can also try the `--ad-block` / `ad_block=True` option.

I don't want to block the ads, that's why.
