### ISSUE TITLE
Can SeleniumBase bypass Cloudflare inside Google Form?

### ISSUE THREAD

**Issue by bao1311** [seleniumbase/SeleniumBase#2909]
I am automating myself to fill in a Google Form. However, when I click the submit button, I must solve the recaptcha. Attaching my user profile with normal Selenium will not make me do the recaptcha. I wonder if there is any way that I do not need to include my profile with Seleniumbase but can still bypass that Recaptcha. However, When I test the raw_form_turnstile.py inside examples, it does not work.

**Comment by bao1311** [comment]
Oh, sorry, I just checked again and figured out that Recaptcha is different from Cloudflare. I wonder if we can bypass Recaptcha with SeleniumBase?

**Comment by mdmintz** [comment]
reCAPTCHA is different from other anti-bot services because it throws CAPTCHAs even if not detecting Selenium.

Instead of bypassing reCAPTCHA, solve the audio challenge with an external repo:
https://github.com/search?q=pydub.AudioSegment.from_mp3+recaptcha+solver+language%3APython&type=code
