### ISSUE TITLE
how to import keys to press enter button on keyboard 

### ISSUE THREAD

**Issue by pythondeveloperz** [seleniumbase/SeleniumBase#2924]
how to import keys to press enter button on keyboard 

> element1 = driver.find_element("name","q")
> element1.send_keys(Keys.Enter)

**Comment by mdmintz** [comment]
Add `\n` to press Enter after typing text.

https://github.com/seleniumbase/SeleniumBase/blob/f65a302a0c657de1c7944004f09efabafb51c4dc/examples/raw_test_scripts.py#L6
