### ISSUE TITLE
I would like to use a certificate, but I am not sure how to do so.

### ISSUE THREAD

**Issue by ShogoDev0212** [seleniumbase/SeleniumBase#2934]
# Environment
Python: 3.10.11
SeleniumBase: 4.24.12

# Description
I would like to use a certificate, but I am not sure how to do so.

Below is the sample source code. In this example, I am unable to access "https://geo.brdtest.com/mygeo.json".

```
from seleniumbase import Driver as MySBDriver
import ssl
import certifi

ssl_context = ssl.create_default_context(cafile=certifi.where())
ssl_context.load_verify_locations(str(Path(f"{os.path.sep.join(sys.argv[0].split(os.path.sep)[:-1])}/ca.crt")))

driver = MySBDriver(uc=True, proxy="http://brd-customer-hl_e43c514b-zone-residential_proxy3:1234@brd.superproxy.io:22225")
driver.get("https://geo.brdtest.com/mygeo.json")
```

Please let me know if there are any possible remedies or ideas that may help solve this issue. Thank you.

**Comment by mdmintz** [comment]
For the certificate things, you will need to use https://github.com/wkeeling/selenium-wire (which is activated with `--wire` / `wire=True` in SeleniumBase). But note that Wire Mode is not compatible with UC Mode, so you may pick one, but not both.

And it might also be a good idea to upgrade to the latest version of SeleniumBase. (Your version is missing a lot of important updates.)
