### ISSUE TITLE
How to Modify Response Body in SeleniumBase Similar to Playwright's `page.route`?

### ISSUE THREAD

**Issue by TisuHitam** [seleniumbase/SeleniumBase#2935]
Hi,

I have a question regarding SeleniumBase. Is it possible to modify the response body in SeleniumBase similar to how it can be done in Playwright using page.route? If this feature is not directly available, is there an alternative method or solution for achieving this?

Thank you!

**Comment by mdmintz** [comment]
If that's possible with SeleniumBase, it would be via the `selenium-wire` integration.
See https://github.com/seleniumbase/SeleniumBase/issues/2145 for details.

**Comment by TisuHitam** [comment]
I understand that selenium-wire integration is the way to go. However, I need to use uc mode, and as far as I know, wire mode doesn't work with uc mode. Is there any other workaround or solution that allows modifying the response body while still using uc mode?

**Comment by mdmintz** [comment]
Maybe https://github.com/seleniumbase/SeleniumBase/issues/2316#issuecomment-1827067375

**Comment by TisuHitam** [comment]
Thanks for the suggestion, but `driver.execute_cdp_cmd` didn’t work. If there’s no other solution, I guess I’ll have to go without it.

**Comment by odell0111** [comment]
You could set up a proxy, such as mitmproxy, to intercept and modify the relevant requests
