### ISSUE TITLE
Strategies for blocked ips 

### ISSUE THREAD

**Issue by moadennagi** [seleniumbase/SeleniumBase#2940]
This is not an issue, more of a general question, I own a website, I have a system for blocking ips with a certain number of requests in a minute.
Is it possible to work around this system ?

**Comment by mdmintz** [comment]
To get past an IP-block, you must change your IP Address.
Use the `proxy` arg to route traffic through a proxy server.

Supported `proxy` formats:

* `proxy="user:pass@ip:port"`
* `proxy="ip:port"`

(`ip` can be an IP Address or a domain)

You can also rotate proxy servers by using `pytest` parameterization: https://github.com/seleniumbase/SeleniumBase/issues/2450#issuecomment-1910500931

(Naturally, you'll need to provide your own proxy server connection details for this.)
