### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by moadennagi** [seleniumbase/SeleniumBase#2950]
I apologize for submitting this as an issue, this project is awesome, @mdmintz is this open to contribution, is there a roadmap ?

**Comment by mdmintz** [comment]
There's a roadmap: It's top secret of course, given that CAPTCHA providers are seeking desperately to figure out how SeleniumBase is able to bypass CAPTCHAs so quickly & easily.

The project is not generally open to outside contribution, for reasons outlined in https://github.com/readme/featured/how-open-is-open-source. The code is open source, but SeleniumBase is not seeking outside contributors.
