### ISSUE TITLE
Driver causing persistent increase in memory

### ISSUE THREAD

**Issue by brnlee** [seleniumbase/SeleniumBase#2953]
First of all, thank you for your work on this project!

I have a python program (running in a Docker container with `google-chrome-stable` installed FWIW) that consistently spawns threads in which a `Driver` is created. I am hoping that this program could run "forever" but I've observed that the memory usage of the container steadily increases over time and I'm worried about memory issues down the line.

I've narrowed the issue down to the creating of the `Driver`. To simulate my issue, I ran the code below in a container and observed the increase in memory usage in the image attached. I've checked that the only process during `sleep` is the python program itself, so it seems like all instances of Chrome were shutdown and reaped.

My questions are:
1. Am I missing some sort of cleanup? 
2. Is there anything I can do to prevent the increase in memory usage over time?

Additional information:
* Google Chrome 126.0.6478.182
* Driver installed via `seleniumbase get chromedriver --path`
* selenium==4.22.0
* seleniumbase==4.28.7
* Python 3.12

```python
while True:
    for _ in range(50):
        with DriverContext(uc=True, incognito=True):
            pass
    time.sleep(30)
```
![image](https://github.com/user-attachments/assets/d05a89e7-aefc-4cbf-9b80-42213c070e5d)

**Comment by mdmintz** [comment]
It's probably something from here: https://github.com/search?q=repo%3Aultrafunkamsterdam%2Fundetected-chromedriver+memory&type=discussions

The best way to resolve this might be to terminate all Chrome processes after every 1000 runs with UC Mode.
The `psutil` library may be helpful for this: https://pypi.org/project/psutil/.
If you find a better way, let me know. This appears to be what people are using for UC Mode at scale.
