### ISSUE TITLE
SeleniumBase A.I. detected a CF Turnstile change (update needed)

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2962]
### SeleniumBase A.I. detected a CF Turnstile change (update needed)

<img width="610" alt="Screenshot" src="https://github.com/user-attachments/assets/b761801e-78fb-4b4e-b7ae-4f607f379837">

That change is preventing UC Mode from bypassing the CAPTCHAs.

The proposed update will be shipped in the next release to fix UC Mode.

**Comment by mdmintz** [comment]
This was resolved in `4.29.2` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.29.2

**Comment by subradrad** [comment]
That was blazingly fast; thank you!

**Comment by mdmintz** [comment]
I also mentioned the update here: https://github.com/seleniumbase/SeleniumBase/issues/2865#issuecomment-2251365704
