### ISSUE TITLE
Unable to Click Turnstile Using `uc_gui_click_cf` on Specific URL

### ISSUE THREAD

**Issue by TisuHitam** [seleniumbase/SeleniumBase#2972]
Hello,

I am facing an issue with SeleniumBase where I am unable to click a turnstile using the `uc_gui_click_cf` method on the following URL: https://gateway.platoboost.com/a/2569?id=82829192.

**Comment by mdmintz** [comment]
Make sure you're using `seleniumbase` `4.29.3` (or newer if available).

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    url = "https://gateway.platoboost.com/a/1?id=1"
    sb.uc_open_with_reconnect(url, 4)
    sb.uc_gui_click_captcha()
```

See the UC Mode documentation: [SeleniumBase/help_docs/uc_mode.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md)

**Comment by TisuHitam** [comment]
Yes I have updated SeleniumBase to version 4.29.3, but `uc_gui_click_cf` only works in Cloudflare Challenge not in normal turnstile

https://gateway.platoboost.com/a/2569?id=82829192
![Screenshot_20240728-133455](https://github.com/user-attachments/assets/df6d40b8-7500-4457-ac4d-a39afa81ccc3)

**Comment by mdmintz** [comment]
On that page, use `sb.uc_gui_click_captcha("#captchaContainer")`.
