### ISSUE TITLE
uc_gui_handle_cf() started behaving strangely

### ISSUE THREAD

**Issue by vmolostvov** [seleniumbase/SeleniumBase#2973]
Hey seems like `uc_gui_handle_cf()` stop working correctly (watch the video), maybe some changes in DOM, can u check please? Using last sb upgrade, macOS, python 3.11. Testing on this url: https://dexscreener.com/
Other functions `uc_gui_click_captcha(), uc_gui_click_cf()` working well, but I need to use that one.

https://github.com/user-attachments/assets/010faa12-a059-439b-b041-bb7281656f3e

**Comment by mdmintz** [comment]
Looks like CF made another change to Turnstiles again.
I'll ship a new release later today to address the changes.

**Comment by mdmintz** [comment]
This was resolved in `4.29.4` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.29.4

**Comment by vmolostvov** [comment]
That was fast enough, thank you!
