### ISSUE TITLE
Stuck on with 'SB(uc=True) as sb'

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2979]
Hello!

I am using it for a while and it worked perfect, but since yesterday or before yesterday, it started to be stuck on:

`with SB(uc=True) as sb:`

And after a while it retrieves the following error:

`timeout: Timed out receiving message from renderer: 600.000  (Session info: chrome=127.0.6533.72)`

and it doesn't go further, what can see? I've already updated the libraries but no luck, still the same

Thank you

p.s: I just started to do it updating all the libraries and it retrieves the same as old versions

p.s: also another question... how can i deploy Seleniumbase on a service and do some kind of 'remote_url' in 'with SB(uc.....)'?

p.s: I just found an error, doing git clone of your project and doing a 'docker run', it retrieves 

```
 => [44/44] RUN chmod +x *.sh                                                                                                                                                                           0.4s
 => exporting to image                                                                                                                                                                                 15.3s
 => => exporting layers                                                                                                                                                                                15.3s
 => => writing image sha256:6ff83de84875b1ef89490738920f423cccb1c6be74df8222842f09e1e1e86667                                                                                                            0.0s
 => => naming to docker.io/library/seleniumbase                                                                                                                                                         0.0s

 3 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 13)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 11)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 12)
```

**Comment by mdmintz** [comment]
I'm not able to reproduce your issue when running from the latest `Dockerfile`, updated today: [SeleniumBase/blob/master/Dockerfile](https://github.com/seleniumbase/SeleniumBase/Dockerfile).

Also note that UC Mode isn't fully compatible with Docker, as Docker leaves a unique fingerprint that can make UC Mode detectable by CAPTCHAs. (No issues with regular Linux.)

**Comment by manel00** [comment]
I am not using Selenium Grid, the code was working till 2 days ago and I wonder what happened...
