### ISSUE TITLE
How to get your repo as an image for Docker?

### ISSUE THREAD

**Issue by manel00** [seleniumbase/SeleniumBase#2980]
Hello,

I've tried within your repo to reproduce my code and it works but I wonder how to use your repo as an image for Docker and use your repo, thank you

Regards

**Comment by mdmintz** [comment]
We provide a `Dockerfile`: [SeleniumBase/Dockerfile](https://github.com/seleniumbase/SeleniumBase/blob/master/Dockerfile).
It's up to you to do more with it (such as building an image).
