### ISSUE TITLE
How to Connect to wsendpoint

### ISSUE THREAD

**Issue by GJayLG** [seleniumbase/SeleniumBase#2983]
How is it possible to connect to wsendpoint? I looked through all the issues and did not find the answer. Could you tell me how this can be done with SB

with SB(uc=True) as sb:

ws://127.0.0.1:6338/devtools/browser/aa87c815-f980-406a-be69-19308bd607e8

**Comment by mdmintz** [comment]
It looks like you're trying to connect to an existing browser. That's already how UC Mode works: It spins up a regular Chrome browser, then attaches Selenium to it via the `remote-debugging-port`. For setting options that aren't already included, you can pass those into `chromium_arg`, which takes a comma-separated list, no spaces.

https://github.com/seleniumbase/SeleniumBase/blob/50e865851473da8044fb5fbe1d0bf65a4b99e921/seleniumbase/plugins/sb_manager.py#L69
