### ISSUE TITLE
DeviceMetrics wrong required type

### ISSUE THREAD

**Issue by tkozybski** [seleniumbase/SeleniumBase#2985]
Currently, device metrics require int for pixelRatio, but any number is actually correct (int or float). If you try to pass float to seleniumbase, it will use default settings instead. Many mobile devices use fractional scaling, also any high resolution PC uses a scaling factor.

See: https://developer.chrome.com/docs/chromedriver/mobile-emulation and https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride

**Comment by mdmintz** [comment]
Thanks for reporting this. It'll be fixed in the next release.

**Comment by mdmintz** [comment]
This was resolved in `4.29.5` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.29.5

**Comment by tkozybski** [comment]
I'm not sure if width and height can use floats. According to the [documentation](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride), only pixel ratio uses number type.

**Comment by mdmintz** [comment]
This was resolved fully in `4.29.6` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.29.6
