### ISSUE TITLE
seleniumbase with proxy error

### ISSUE THREAD

**Issue by BEST1AV** [seleniumbase/SeleniumBase#2988]
i write script using seleniumbase and its working fine without proxy ,
but when i use proxy i got this error : selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:41027

code:
  from seleniumbase import SB
  
  username = '*****'
  password = '****'
  prox = f"{username}:{password}@gate.dc.smartproxy.com:20000"
  
  with SB(uc=True,headless=True,test=True,proxy=prox) as sb:
          
              #sb.maximize_window()
              sb.driver.uc_open_with_reconnect("https://whoer.net/", reconnect_time=3,)
              ip=sb.get_text("//strong[@class='your-ip']")
              
              country=sb.get_text("//h2[@class='city-or-country']")
              print(country ,":", ip)

**Comment by mdmintz** [comment]
Might be an issue with your proxy provider. I was unable to reproduce your issue.

**Comment by BEST1AV** [comment]
thanks for your reply to my issue but i changed the os from (ubuntu to fedora its working fine maybe i make something wrong when install it ) 
anyway i fixed this issue thank you sir
