### ISSUE TITLE
error 'Chrome' object has no attribute 'uc_gui_click_captcha'

### ISSUE THREAD

**Issue by alish511** [seleniumbase/SeleniumBase#2990]
why I get this error 'Chrome' object has no attribute 'uc_gui_click_captcha' on driver 
how can use this method on wich object ?
please help

**Comment by mdmintz** [comment]
See the docs: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md
You need to set uc=True or --uc.
