### ISSUE TITLE
uc mode doesn't pass the CF in Ubuntu system

### ISSUE THREAD

**Issue by yingrulinn** [seleniumbase/SeleniumBase#2993]
I attempted to bypass CF Turnstile with the following code. It works without any issues on the Windows system, but it always fails on the Linux system. My SeleniumBase version is 4.29.6.

```python
with SB(uc=True, incognito=True, test=True, rtf=True, agent=ua, disable_features="UserAgentClientHint", proxy=proxy, headed=True, xvfb=True) as sb:
    try:
        url = "https://fr.tlscontact.com/oauth2/authorization/oidc" 
        sb.uc_open_with_reconnect(url, 4)
        sb.uc_gui_click_captcha()  # Ready if needed!
        sb.uc_gui_click_cf()

        sb.wait_for_element('div[class="tls-form"]', timeout=30)

    except Exception as e:
        sb.save_screenshot("log.png", folder="./downloaded_files")
        sb.assert_downloaded_file("log.png")
        print('\n"%s/%s" was saved!' % ("downloaded_files", "log.png"))
        sb.save_page_source('./downloaded_files/log.html')
        print('\n"%s/%s" was saved!' % ("downloaded_files", "log.html"))
```
I also tried the following code:
```
with SB(uc=True, test=True, incognito=True, proxy=proxy, agent=agent) as sb:
    sb.driver.uc_open_with_reconnect("https://fr.tlscontact.com/oauth2/authorization/oidc", 15) 
    sb.switch_to_frame("iframe")
    sb.execute_script('document.querySelector("input").focus()')

    save_log(sb, '1')
    
    sb.send_keys("html", "\t")

    sb.driver.disconnect()
    pyautogui.press(" ")
    sb.sleep(10)
    sb.driver.reconnect(4)
    sb.sleep(10)
    #sb.assert_element("img#captcha-success", timeout=3)
    print(sb.get_current_url())
    sb.set_messenger_theme(location="top_left")
    sb.post_message("SeleniumBase wasn't detected", duration=3)
    save_log(sb, '2')
```
However, it resulted in the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/t3.py", line 134, in <module>
    sb.switch_to_frame("iframe")
  File "/home/ubuntu/tlss/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 3496, in switch_to_frame
    if isinstance(frame, str) and self.is_element_visible(frame):
  File "/home/ubuntu/tlss/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 1434, in is_element_visible
    self.wait_for_ready_state_complete()
  File "/home/ubuntu/tlss/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 4540, in wait_for_ready_state_complete
    self._check_browser()
  File "/home/ubuntu/tlss/lib/python3.10/site-packages/seleniumbase/fixtures/base_case.py", line 8985, in _check_browser
    raise NoSuchWindowException("Active window was already closed!")
selenium.common.exceptions.NoSuchWindowException:` Message: Active window was already closed!
```
this is my sistem environment:
(tlss) ubuntu@ip-172-31-42-185:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

please kindly help :(

**Comment by yingrulinn** [comment]
![image](https://github.com/user-attachments/assets/6907ff59-c055-43ae-9c5e-3e21f0d0d892)

**Comment by yingrulinn** [comment]
it always stucks here :

**Comment by mdmintz** [comment]
UC Mode is working for me on Linux (Ubuntu), as per the UC Mode docs: ([SeleniumBase/help_docs/uc_mode.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md))

<img width="610" alt="Screenshot 2024-08-04 at 3 27 39 PM" src="https://github.com/user-attachments/assets/61e4f6dc-a96b-4494-a9cc-6c6f4f42ce71">

There are several things you should note:
* Don't look for `iframe` elements directly anymore (they are hidden in Shadow-DOM).
* Don't try changing the default UserAgent on Linux (SeleniumBase gives you a good one).
* Don't look for `"img#captcha-success"`outside of SeleniumBase website pages.
* Don't use Docker (not supported)
