### ISSUE TITLE
How to change headers  before request

### ISSUE THREAD

**Issue by Mracobes9** [seleniumbase/SeleniumBase#2997]
Hi. How can i change headers before request sending using wire ?

**Comment by mdmintz** [comment]
See https://github.com/seleniumbase/SeleniumBase/issues/1906#issuecomment-1584516315.

Also see https://github.com/seleniumbase/SeleniumBase/discussions/1179.

You can try `driver.execute_cdp_cmd()` as mentioned in https://github.com/seleniumbase/SeleniumBase/issues/2050#issuecomment-1718083788.

Or try ideas from https://stackoverflow.com/q/77494543/7058266.

For `selenium-wire` specific questions, see https://github.com/wkeeling/selenium-wire.
