### ISSUE TITLE
The browser crashes.

### ISSUE THREAD

**Issue by radovs3245** [seleniumbase/SeleniumBase#3001]
After entering, and sometimes before entering text into the field, the browser closes, what could be the problem? 
Closes on the last line.

with SB(headless=False, uc=True) as sb:

url = "https://site.com"
sb.uc_open_with_reconnect(url, 10)

sb.sleep(random.randint(1, 5))
sb.click("//input[@id='lastNameInput']", 'xpatch', 90, random.randint(1, 5))
 sb.send_keys(selector="//input[@id='lastNameInput']", text=str(akk_surname), by='xpatch', timeout=30)
sb.click("//input[@id='firstNameInput']", 'xpatch', 90, random.randint(1, 5))
sb.send_keys(selector="//input[@id='firstNameInput']", text=str(akk_name), by='xpatch', timeout=30)

**Comment by mdmintz** [comment]
It would never make it to the last line. You misspelled `xpath` when selecting the `by`, so it would fail on the first click.

Please use proper indentation and code-formatting when pasting code, (use Markdown), and include relevant information such as stack traces.
