### ISSUE TITLE
Repeat UC Browser

### ISSUE THREAD

**Issue by radovs3245** [seleniumbase/SeleniumBase#3013]
Hello.
Please tell me how can I set the repeat?
Perform an action 5 times in the browser.
Browser uc.
driver = Driver(uc=True, headless=True, chromium_arg=f'remote-debugging-port={port}')
url = 'https://google.com'
driver.uc_open_with_reconnect(url, 10)
driver.click("//input[@id='usernameInput']", 'xpath', 90)
driver.send_keys("//input[@id='usernameInput']", login)

**Comment by mdmintz** [comment]
Use a `for` loop for code repetition:
* https://wiki.python.org/moin/ForLoop
* https://docs.python.org/3/tutorial/controlflow.html#for-statements
