### ISSUE TITLE
Prevent intermittent `SessionNotCreatedException` during UC Mode

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#3018]
## Prevent intermittent `SessionNotCreatedException` during UC Mode

Here's where it happened: https://github.com/mdmintz/undetected-testing/actions/runs/10306599780/job/28530036367

<img width="1360" alt="Screenshot 2024-08-12 at 10 10 09 PM" src="https://github.com/user-attachments/assets/af87e558-17cf-4a2c-a022-27bdcde83458">

I'm not sure what caused it, but I can add a retry when launching the browser during UC Mode.
Also, it's possible that it was caused by a GitHub Actions issue, since it hasn't happened in 4 days.

**Comment by oniononion36** [comment]
This is the same issue I am seeing on my Mac, only it never succeeds. My code looks like this:

with SB(uc=True, test=True) as sb:
    sb.driver.uc_open_with_reconnect('https://www.cnn.com/', 3)

**Comment by mdmintz** [comment]
It was only intermittent for me, and very rare.

**Comment by mdmintz** [comment]
This was resolved in `4.29.9` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.29.9

**Comment by oniononion36** [comment]
Weird, I tried it on my desktop (Windows) and seems like it's working fine there, any way to get detailed logging?

**Comment by mdmintz** [comment]
Review the stack trace, if available. Also try `breakpoint()` for manual debugging.
