### ISSUE TITLE
Exception: Frame {iframe} was not visible after 10 seconds!

### ISSUE THREAD

**Issue by CLIRD** [seleniumbase/SeleniumBase#3023]
Hello, 
I'm getting this error using this code, I've tried different ways (undetected_chromedriver, selenium ect) but I can't manage to bypass the cloudflare on this site:
with SB(uc=True, test=True,headless=True, disable_features="UserAgentClientHint", agent=ua) as sb:
    sb.driver.uc_open_with_reconnect(
        "https://www.upstart.com",
        10
    )
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")

![Screenshot 2024-08-13 at 16-02-32 Error - Upstart](https://github.com/user-attachments/assets/a7973695-0603-4dbd-84f4-29b094448237)

**Comment by mdmintz** [comment]
Assuming that site throws a CAPTCHA, the code would look something like this:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://www.upstart.com"
    sb.uc_open_with_reconnect(url, 4)
    sb.uc_gui_click_captcha()
```

See the updated UC Mode documentation: [SeleniumBase/help_docs/uc_mode.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md)

**Comment by CLIRD** [comment]
Thank you, it works perfectly. I had another question, is there a way to make this code work in headless mode?

**Comment by mdmintz** [comment]
UC Mode uses `PyAutoGUI` to click CAPTCHAs, and `PyAutoGUI` requires a headed browser.
Thankfully, you no longer need to use headless mode because UC Mode comes with a special Xvfb virtual display on Linux machines, which makes it possible to run on Linux without headless mode.

**Comment by CLIRD** [comment]
Ok thanks I understand better, I was looking for something that doesn't need a headed browser to run it on a remote server.
