### ISSUE TITLE
fingerprint.com detected uc mode in version 4.29.9

### ISSUE THREAD

**Issue by fw-real** [seleniumbase/SeleniumBase#3028]
Pretty sure in previous versions it was working fine but now even seleniumbase's uc mode got detected by fingerprint.com am i doing something wrong? i am just using a basic example of uc mode and it worked before i dont see why it shouldn't now as well.

![image](https://github.com/user-attachments/assets/78b9264c-957a-4fff-80cf-d063842c0c5e)

heres the code i used:
```py
from seleniumbase import SB


with SB(uc=True, test=True, rtf=True) as sb:
    url = "https://fingerprint.com/products/bot-detection/"
    sb.uc_open_with_reconnect(url, 4)
    while True:
        pass
```

**Comment by mdmintz** [comment]
For some anti-bot systems, you need to set `incognito=True`.

```python
from seleniumbase import SB

with SB(uc=True, incognito=True) as sb:
    url = "https://fingerprint.com/products/bot-detection/"
    sb.uc_open_with_reconnect(url, 8)
```

<img width="1392" alt="Screenshot 2024-08-15 at 6 05 09 PM" src="https://github.com/user-attachments/assets/19d15e92-e953-43b7-b4fe-9ad91fefd061">
