### ISSUE TITLE
Can't change the user agent 

### ISSUE THREAD

**Issue by Damji7** [seleniumbase/SeleniumBase#3035]
hello, 
i want to change the user agent of the browser using the sb form and uc mode but it didn't work for me i've tried several times without results, here is the code snippet

user_agents = [config.get('AGENTS', f'AGENT{i}') for i in range(1, 5)]
random.shuffle(user_agents)
chosen_user_agent = random.choice(user_agents)

with SB(uc=True, incognito=True) as sb:

    sb.execute_cdp_cmd(
        "Network.setUserAgentOverride",
        {
            "userAgent": chosen_user_agent
        },
    )
    url = config.get('URLS', 'SITE')
    sb.uc_open_with_reconnect(url, 2)
    sb.sleep(3)
    sb.uc_gui_handle_captcha()

when i check the netwrok tab and look at the user agent i find the original one, is there any good solution to change it ?

**Comment by mdmintz** [comment]
Use the `agent` arg during initialization to change the user agent:

https://github.com/seleniumbase/SeleniumBase/blob/af3d9545473e55b2a25cdbab8be0b1ed5e1f6afa/seleniumbase/plugins/sb_manager.py#L45

Example:

```python
from seleniumbase import SB

with SB(uc=True, agent="SPECIAL USER AGENT STRING") as sb:
    sb.uc_open_with_reconnect("https://my-user-agent.com/")
    user_agent_detected = sb.find_element("#ua_string").text
    print("\n\nUser-Agent: %s" % user_agent_detected)
```

(Note that UC Mode gives you a good user-agent by default, so if you change it, you could be detected.)
