### ISSUE TITLE
Is possible to block urls permanently and not just for the first load (on open) in UC mode?

### ISSUE THREAD

**Issue by ProtocolNebula** [seleniumbase/SeleniumBase#3037]
Hi,
I'm using UC mode (to skip Cloudflare).

I have the following rule to block some URLs:

```python
    sb.execute_cdp_cmd(
        'Network.setBlockedURLs',
        {
            "urls": [
                "https://domain.com/style/*",
                "https://domain.com/images/*",
                "https://domain.com/*.gif",
                "https://domain.com/*.png",
                "https://domain.com/*.svg",
                "https://domain.com/*.jpg",
            ]
        }
    )
    sb.execute_cdp_cmd('Network.enable', {})
```

I read everywhere that these URLs will just be blocked when the `open`  command is called explicitly, but I need to block these resources ALWAYS, I want to load the text content but it is horribly slow at the website I'm trying to scrape.

Any hack or trick?

**Comment by akumathedyn123** [comment]
@ProtocolNebula block some url???? like what? like block the sites to load or block the scrapper to visit that site??

**Comment by ProtocolNebula** [comment]
@akumathedyn123, as shown in the example, I want to block some resources (css, images...).

Everything I need to scrape works with these filter applied (but it does not maintain over the time and I scrape using forms 
+ POST).

**Comment by mdmintz** [comment]
When using UC Mode for that, the trick is to put the `Network.setBlockedURLs` part in a Chrome extension. That's kind of how `ad_block=True` works. You'll need to create your own custom Chrome extension for `Network.setBlockedURLs` specifics. Then load the directory using the `extension_dir` arg:

https://github.com/seleniumbase/SeleniumBase/blob/af3d9545473e55b2a25cdbab8be0b1ed5e1f6afa/seleniumbase/plugins/sb_manager.py#L74

----

But if you need to do that without using UC Mode, then then solution is much simpler:

[SeleniumBase/examples/test_cdp_ad_blocking.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_cdp_ad_blocking.py)

```python
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)


class CDPNetworkBlockingTests(BaseCase):
    def test_cdp_network_blocking(self):
        self.open("about:blank")
        if not self.is_chromium():
            message = "This test is only for Chromium browsers!"
            print(message)
            self.skip(message)
        self.execute_cdp_cmd(
            'Network.setBlockedURLs', {"urls": [
                "*googlesyndication.com*",
                "*doubleclick.net*",
                "*adsafeprotected.com*",
                "*2mdn.net*",
                "*googletagmanager.com*",
                "*adsafeprotected.com*",
                "*snigelweb.com*",
                "*fastclick.net*",
                "*amazon-adsystem.com*",
                "*google-analytics.com*",
            ]})
        self.execute_cdp_cmd('Network.enable', {})
        self.open('https://www.w3schools.com/jquery/default.asp')
        source = self.get_page_source()
        self.assert_true("doubleclick.net" not in source)
        self.assert_true("google-analytics.com" not in source)
        self.post_message("Blocking was successful!")
```
