### ISSUE TITLE
raw_uc_mode detected

### ISSUE THREAD

**Issue by farisyusry** [seleniumbase/SeleniumBase#3043]
any ideas i testing using example also not working
examples/raw_uc_mode.py

is it my python seleniumbase not using latest version?

`from seleniumbase import SB

with SB(test=True) as sb:
    sb.open("https://seleniumbase.io/antibot/login")
    sb.highlight("h4", loops=6)
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.click_if_visible("button span")
    sb.highlight("label#pText")
    sb.highlight("table#detections")
    sb.sleep(4.4)  # Add time to read the table`

**Comment by mdmintz** [comment]
For the `https://seleniumbase.io/antibot/login` page, see [SeleniumBase/examples/raw_antibot_login.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_antibot_login.py):

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://seleniumbase.io/antibot/login"
    sb.uc_open_with_disconnect(url, 2.15)
    sb.uc_gui_write("\t" + "demo_user")
    sb.uc_gui_write("\t" + "secret_pass")
    sb.uc_gui_press_keys("\t" + " ")  # For Single-char keys
    sb.sleep(1.5)
    sb.uc_gui_press_keys(["\t", "ENTER"])  # Multi-char keys
    sb.reconnect(1.8)
    sb.assert_text("Welcome!", "h1")
    sb.set_messenger_theme(location="bottom_center")
    sb.post_message("SeleniumBase wasn't detected!")
```

(That website uses realtime bot-scanning, so you can connect chromedriver to Chrome at all when on a Brotector-protected site. Once you've bypasses the CAPTCHA, it's safe to reconnect.)

----

For the `https://gitlab.com/users/sign_in` page, see: [seleniumbase/examples/raw_uc_mode.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py):

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://gitlab.com/users/sign_in"
    sb.uc_open_with_reconnect(url, 4)
    sb.uc_gui_click_captcha()
    sb.assert_text("Username", '[for="user_login"]', timeout=3)
    sb.assert_element('label[for="user_login"]')
    sb.highlight('button:contains("Sign in")')
    sb.highlight('h1:contains("GitLab.com")')
    sb.post_message("SeleniumBase wasn't detected", duration=4)
```
