### ISSUE TITLE
Please add "tel:" to def assert_no_404_errors(self, multithreaded=True, timeout=None):

### ISSUE THREAD

**Issue by Th0mas89** [seleniumbase/SeleniumBase#3051]
Hello,

You have a great exception handler for "data:" "mailto:" etc. links.
Please add also "tel:" to the list, so that tests don't fail in this case.

Best,

Thomas

**Comment by mdmintz** [comment]
Sounds good. I'll add that into the next release.

**Comment by mdmintz** [comment]
This was resolved in SeleniumBase `4.30.0` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.0
