### ISSUE TITLE
I wanted to pass the ChromeOptions of selenium into get_new_driver() method, but there is no parameter which accepts Chromeoptions.

### ISSUE THREAD

**Issue by christinajoice** [seleniumbase/SeleniumBase#3052]
I actually wanted to enable notification of chrome browser and I passed it as an argument to the Chromeoptions. This Chromeoptions I wanted to pass it to get_new_driver() method of Seleniumbase. But the get_new_driver() method doesn't have the parameter "options" which allow me to pass Chromeoptions. 

Below are few approaches I tried:

1. Tried to override the method still not working.

    `
def get_new_driver(self, *args, **kwargs):
            options = ChromeOptions()
            options.add_argument("--enable-notifications")
            return super().get_new_driver(options=options, *args, **kwargs)
`

2. Tried passing the chrome-args in pytest via command line:

`pytest -m debug --chrome-args=--enable-notifications
`
and it throws the below error as in the attachment : 

![image](https://github.com/user-attachments/assets/16635018-1028-4fb2-953a-249742dafdc4)

Any assistance would be appreciable on this thing.

**Comment by mdmintz** [comment]
To pass in additional args via the command-line, use `--chromium-arg`:

https://github.com/seleniumbase/SeleniumBase/blob/af3d9545473e55b2a25cdbab8be0b1ed5e1f6afa/seleniumbase/plugins/pytest_plugin.py#L53

With `get_new_driver`, use `chromium_arg`:

https://github.com/seleniumbase/SeleniumBase/blob/af3d9545473e55b2a25cdbab8be0b1ed5e1f6afa/help_docs/method_summary.md?plain=1#L312

First check to see that there isn't already an existing arg for that.

----

For more advanced customization, see [Syntax Format 9: Overriding the driver via BaseCase](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_09).
There's an example of that here: [SeleniumBase/examples/test_override_driver.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_override_driver.py).

**Comment by christinajoice** [comment]
Hi @mdmintz, I tried with prefs and overriding the get_new_driver() and it is working in my local now, but still, when I try the same in docker, it has default browser settings for notification (which is not allowed). I tried upgrading my Chrome, selenium and selenium base versions but the notification is still disabled. Below is the code snippet that worked in my local but not in docker, FYR.

`options = Options()
        prefs = {
            "profile.default_content_setting_values.notifications": 1,  # 1 allows, 2 blocks
            "profile.default_content_settings.popups": 1,
            "profile.default_content_settings.cookies": 1,
            "profile.default_content_settings.javascript": 1,
            "profile.managed_default_content_settings.notifications": 1,
            "local_discovery.notifications_enabled": True
        }
        options.add_argument("--enable-features=WebRTC-HW-Decoding,WebRTC-HW-Encoding")
        options.add_argument("--allow-insecure-localhost")
        options.add_argument("--enable-notifications")
        options.add_experimental_option("prefs", prefs)
        self.driver = self.get_new_driver(options=options)`

 Is there anything needs to be done additionally for it to work in docker?

**Comment by mdmintz** [comment]
For Docker, you'll also need to use headless mode unless you're running a virtual display. To activate Chrome's new headless mode, use: `options.add_argument("--headless=new")`. If you want the virtual display, see https://github.com/mdmintz/sbVirtualDisplay.

**Comment by christinajoice** [comment]
Hi @mdmintz sorry to bother again, after upgrading to seleniumbase 4.30.1 version, notification is not being enabled in any of the ways.

Below is the overridden method of get_new_driver().

    ```
def get_new_driver(self, *args, **kwargs):
        options = ChromeOptions()
        options.add_argument("--enable-notifications")
        super().get_new_driver(chromium_arg=options, *args, **kwargs)
```
 but looks like the above method is not getting overridden. Another way I tried is as below:

```
def test_enable_notifications(self):
         chrome_options = {
            "profile.default_content_setting_values.notifications": 1
         }
         self.driver = self.get_new_driver(browser='chrome', chromium_arg=chrome_options)
         self.open(BASE_URL)
```
Tried overriding setUp() method as below:
    ```
def setUp(self,masterqa_mode=False):
        chrome_options = Options()
        chrome_options.add_experimental_option(
            "prefs", {"profile.default_content_setting_values.notifications": 1}
        )
        self.driver = self.get_new_driver(browser='chrome', chromium_arg=chrome_options)
        super().setUp(masterqa_mode=masterqa_mode)
```
With commandline arguments using pytest as below:

`pytest -m notificationfeature --chromium-arg="--enable-notifications"
`

None of the above is working. I am new to seleniumbase and pytest. So your help would be much appreciated on this matter.

**Comment by mdmintz** [comment]
Follow the model here: [SeleniumBase/examples/test_override_driver.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_override_driver.py)
(Don't put `super()` in your method: That could override your settings.)

**Comment by christinajoice** [comment]
Yes tried that too, still get_new_driver() is not getting overriden i think, notification is still disabled.

**Comment by mdmintz** [comment]
This worked for me:

```python
from selenium import webdriver
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)


class OverrideDriverTest(BaseCase):
    def get_new_driver(self, *args, **kwargs):
        """This method overrides get_new_driver() from BaseCase."""
        options = webdriver.ChromeOptions()
        options.add_argument("--enable-notifications")
        if self.headless:
            options.add_argument("--headless=new")
            options.add_argument("--disable-gpu")
        options.add_experimental_option(
            "excludeSwitches", ["enable-automation", "enable-logging"],
        )
        prefs = {
            "credentials_enable_service": False,
            "profile.password_manager_enabled": False,
        }
        options.add_experimental_option("prefs", prefs)
        return webdriver.Chrome(options=options)

    def test_driver_override(self):
        self.open("https://dev.kabam.ai/login")
        breakpoint()
```

<img width="996" alt="Screenshot 2024-09-05 at 1 07 40 PM" src="https://github.com/user-attachments/assets/16a5a48f-1318-41db-8318-9c4277417a29">

**Comment by christinajoice** [comment]
Thank you so much for the quick reply @mdmintz, I just replaced the code in a different class and the tests started working as expected.
