### ISSUE TITLE
Unable to bypass cloudflare protected website that appears to block Linux

### ISSUE THREAD

**Issue by packfile** [seleniumbase/SeleniumBase#3058]
Hey, it appears the following website has rules/protections in place to prevent accessing via Linux. The code below runs successfully on Windows, however running on Ubuntu Desktop fails. In both cases the latest Chrome browser was used

```python
from seleniumbase import SB

with SB(uc=True) as sb:
    sb.uc_open_with_reconnect("https://keymaster.fivem.net/", 4)
    sb.uc_gui_click_captcha()
    sb.assert_element("//a[normalize-space()=\"Sign in\"]")
```

Initially a 404 page is returned on the Linux machine, however changing `SB(uc=True)` to `SB(uc=True, agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36")` then shows the cloudflare turnstile page as expected, though the turnstile will roll around indefinitely then page refresh (again, and again).

I've tested using https://gitlab.com/users/sign_in instead and this works on both machines as expected

Is getting around such block in the scope of this project, and if so what would be the way to approach it? Thanks

**Comment by mdmintz** [comment]
Try it with this script: (Added `incognito=True`)

```python
from seleniumbase import SB

with SB(uc=True, incognito=True) as sb:
    sb.uc_open_with_reconnect("https://keymaster.fivem.net/", 4)
    sb.uc_gui_click_captcha()
    sb.assert_element('a:contains("Sign in")')
```

If they're blocking ALL Linux users (not just bots, but humans too), then probably there's no way around it.

(See [SeleniumBase/help_docs/uc_mode.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md) for more ideas.)
