### ISSUE TITLE
Function "get_desired_capabilities" don't parse bool values

### ISSUE THREAD

**Issue by XenoAura** [seleniumbase/SeleniumBase#306]
I tried use bool values in my cap file, but [**get_desired_capabilities** ](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/capabilities_parser.py#L4)parse only string variables.

How i can add bool values in **desired_capabilities**?

**Comment by mdmintz** [comment]
Hi @XenoAura , As seen from the example at https://www.browserstack.com/automate/capabilities , you can use ``"true"`` or ``"false"`` to set a boolean value in your desired capabilities file.
Example:
```
desired_cap = {
'os_version' : '11',
'device' : 'iPhone 8 Plus',
'real_mobile' : 'true',
'browserstack.local' : 'false',
'browserstack.debug' : 'true'
} 
```
That works for any Selenium Grid, such as Sauce Labs, CrossBrowserTesting, TestingBot, etc.
Try something like that for your cap_file and see if that works for you.

**Comment by XenoAura** [comment]
This is don't work for aerokube selenoid:

**cap file**
```json
desired_cap = {
    "browserName": "chrome",
    "version": "73.0",
    "enableVNC": "true"
}
```

**pytest output:**
`selenium.common.exceptions.WebDriverException: Message: Failed to parse request: json: cannot unmarshal string into Go struct field caps.enableVNC of type bool`


I just overridden **get_desired_capabilities** method. It works for me.

```python
from seleniumbase.core import capabilities_parser
import seleniumbase
def capabilities_parser_patch(cap_file=None):
    from capabilities import desired_cap
    return desired_cap
seleniumbase.core.capabilities_parser.get_desired_capabilities = capabilities_parser_patch
```

**Comment by mdmintz** [comment]
@XenoAura,
See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.22.5
And https://github.com/seleniumbase/SeleniumBase/pull/308/files

You can now do the following in selenium v1.22.5:
``'KEY': 'VALUE'``
``'KEY': True``
``'KEY': False``
``caps['KEY'] = "VALUE"``
``caps['KEY'] = True``
``caps['KEY'] = False``

**Comment by XenoAura** [comment]
Thank you! This solved my problem.
