### ISSUE TITLE
Getting : start error  X11 display failed! Will use regular xvfb!

### ISSUE THREAD

**Issue by Orbiszeus** [seleniumbase/SeleniumBase#3060]
I have currently built an application that runs on Linux Ubuntu that does not have a GUI and regarding this situation for full protection I am not using Headless Mode and adding **incognito=True** and also for X11 display for Linux machines I added : **xvfb=True**. However, when I run the program I get this --> **start error  X11 display failed! Will use regular xvfb!**

My code:
```
menu_items = []
    with SB(uc=True, xvfb=True, incognito=True) as sb:
        sb.driver.uc_open_with_reconnect(url, 20)       
        try:
            print("Locale Code: " +str(sb.get_locale_code()))
            # print(sb.save_screenshot_to_logs(name=None, selector=None, by="css selector"))
            print("Page title: " + str(sb.get_title()))
            sb.sleep(5)
            sb.uc_gui_handle_cf()
            sb.sleep(5)
```

**Comment by mdmintz** [comment]
Duplicate of https://github.com/seleniumbase/SeleniumBase/issues/2982.

Also see the following if your Linux distribution is missing `X11` display dependencies:
* https://askubuntu.com/questions/1006753/how-to-check-if-the-x11-display-manager-is-installed
* https://stackoverflow.com/a/30120178/7058266
* https://askubuntu.com/questions/213678/how-to-install-x11-xorg

**Comment by TyronMYoung11** [comment]
Fixed by:
```
sudo apt install -y xvfb
```
