### ISSUE TITLE
Firefox Extensions

### ISSUE THREAD

**Issue by JasonCrowe** [seleniumbase/SeleniumBase#3063]
I don't see anything in the docs about using firefox extensions. Is that possible, or is it a chrome only feature?

**Comment by mdmintz** [comment]
See https://github.com/seleniumbase/SeleniumBase/issues/803#issuecomment-774402081

Firefox calls them "add-ons". Chrome calls them "extensions". (That's probably why you didn't find it via search.)

Use this method for loading a ``.xpi`` file:

```python
sb.install_addon(xpi_file)
```

For some reason, it must be done at run-time after the browser has already spun up, unlike Chrome extensions, which must be initialized before the web browser is launched. So, load your Chrome extensions from the command-line (or when launching your browser), and load your Firefox add-ons inside the scripts themselves after the browser has already been launched.

**Comment by JasonCrowe** [comment]
Awesome, thanks!
