### ISSUE TITLE
UC Mode does not work

### ISSUE THREAD

**Issue by robalmeister** [seleniumbase/SeleniumBase#3074]
When creating a Driver construct with the flags uc=True, Driver does not allow opening the page, etc

**Comment by mdmintz** [comment]
Works fine for me:

```python
from seleniumbase import Driver

driver = Driver(uc=True)
url = "https://gitlab.com/users/sign_in"
driver.uc_open_with_reconnect(url, 4)
driver.uc_gui_click_captcha()
driver.quit()
```

Read the [UC Mode documentation](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md) before opening UC Mode tickets.
