### ISSUE TITLE
The CF CAPTCHAs have changed again

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#3077]
## The CF CAPTCHAs have changed again

If you've seen my latest video (https://www.youtube.com/watch?v=-EpZlhGWo9k) you'll know that Cloudflare frequently changes their CAPTCHAs to prevent UC Mode from working. Looks like they just changed them again.

I'll need to update UC Mode again to make existing UC Mode methods work again, such as `uc_gui_click_captcha()`.

Stay tuned for updates!

**Comment by mdmintz** [comment]
This was resolved in `4.30.1` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.1

Note that **all UC Mode users** who are using UC Mode for CF CAPTCHAs will need to upgrade to `4.30.1` if you want your Linux scripts to keep working. (Or if you need to click the CAPTCHA to bypass it.)

**Comment by vmolostvov** [comment]
Really appreciate your work! Do you have any donation addresses?
