### ISSUE TITLE
UC Mode users should upgrade to `4.30.1` (or newer if available)

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#3080]
## UC Mode users should upgrade to `4.30.1` (or newer if available)

In case you missed https://github.com/seleniumbase/SeleniumBase/issues/3077, CF made changes to their CAPTCHAs, and a new UC Mode update was needed to continue clicking them successfully on Linux (and other environments where they force you to click the CAPTCHA to bypass it).

These CAPTCHA changes shouldn't be surprising to anyone who's already watched:
https://www.youtube.com/watch?v=-EpZlhGWo9k (my latest UC Mode video tutorial: "Revenge of the CAPTCHAs").

Upgrade to SeleniumBase `4.30.1` (or newer if available) to continue bypassing CAPTCHAs as usual.
https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.1

----

In addition to that, there's also a new tool for generating UC Mode scripts for you. (See https://github.com/seleniumbase/SeleniumBase/issues/3078 for details.)

**Comment by mdmintz** [comment]
Also, if you haven't heard of `sb.uc_gui_click_captcha()`, then you probably haven't read the [UC Mode Docs](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md) in over a month. (If that's the case, then check out the latest updates, and watch the [3rd UC Mode video tutorial on YouTube](https://www.youtube.com/watch?v=-EpZlhGWo9k).)

**Comment by ProtocolNebula** [comment]
Hi,
Is required any additional change?

Since the upgrade, instead of failing the 10% resolution, is failing the 75%.
It just let the screen white after resolution, because cloudflare detected it as a bot.

It might be an error of the proxy I'm using, but I'm worried that the wait time or someting is involved (I've tried with 7 seconds and 10 seconds).

**Comment by mdmintz** [comment]
Everyone should upgrade to `4.30.2` (or newer if available) - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.2
This will account for some CF changes that are coming soon (and in some cases, already here).

**Comment by mdmintz** [comment]
Version `4.30.3` is now available: https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.3
(More UC Mode updates)
