### ISSUE TITLE
你好,高手,我在使用您开发的seleniumbase遇到了无法使用@pytest.mark.parametrize进行数据驱动的问题

### ISSUE THREAD

**Issue by chiangbar** [seleniumbase/SeleniumBase#3089]
这是我的代码
![1725441702025](https://github.com/user-attachments/assets/b6457545-17f5-4eec-bbcd-497cac60211f)
执行我代码后报错内容为:TypeError: test_login() missing 2 required positional arguments: 'username' and 'password'

**Comment by mdmintz** [comment]
See [SeleniumBase/examples/parameterized_test.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py).

Use https://pypi.org/project/parameterized/ for test-parameterization when using `BaseCase` classes.

Example:

```python
from parameterized import parameterized
from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)

class SearchTests(BaseCase):
    @parameterized.expand(
        [
            ["SeleniumBase Commander", "Commander", "GUI / Commander"],
            ["SeleniumBase Recorder", "Recorder", "Recorder Mode"],
            ["SeleniumBase Syntax", "Syntax", "Syntax Formats"],
        ]
    )
    def test_parameterized_search(self, search_term, keyword, title_text):
        self.open("https://seleniumbase.io/help_docs/how_it_works/")
        self.assert_title_contains("SeleniumBase Docs")
        self.type('input[aria-label="Search"]', search_term)
        self.click('mark:contains("%s")' % keyword)
        self.assert_title_contains(title_text)
```

**Comment by chiangbar** [comment]
Thank you very much for your reply. I have just started learning and am not very proficient
