### ISSUE TITLE
When I use @ parameterized. expand() for parametric testing, I get an error: TypeError: unsupported callable

### ISSUE THREAD

**Issue by chiangbar** [seleniumbase/SeleniumBase#3092]
一下是我的源码:

```python
import allure
import pytest
from seleniumbase import BaseCase
from parameterized import parameterized

from config.VAR import *
from elements.page_elements import *

BaseCase.main(__name__, __file__)


class TestFlow(BaseCase):
    @allure.step('登录')
    @parameterized.expand([
        ['13344440099', '123456'],
        ['18598938172', 'a13217408311']
    ])
    def test_login(self, username, password):
        with allure.step('打开读书屋登录页面'):
            self.open(BOOK_HOME_LOGIN)
        with allure.step('输入用户名'):
            self.type(bookhome_login_username, username)
        with allure.step('输入密码'):
            self.type(bookhome_login_password, password)
        with allure.step('点击登录'):
            self.click(bookhome_login_button)
        with allure.step('校验登录成功'):
            self.assert_text(username, index_username)
```

I only have two sets of data, why are there three test cases

**Comment by mdmintz** [comment]
Your issue is coming from `allure`, or one of your other variables. I removed the `allure` part, but kept the rest, and it worked: (I had to fill in missing variables and use a known website)

```python
from seleniumbase import BaseCase
from parameterized import parameterized
BaseCase.main(__name__, __file__)


class TestFlow(BaseCase):
    @parameterized.expand([
        ['standard_user', 'secret_sauce'],
        ['visual_user', 'secret_sauce']
    ])
    def test_login(self, username, password):
        self.open("https://www.saucedemo.com/")
        self.type("#user-name", username)
        self.type("#password", password)
        self.click("#login-button")
        self.assert_text("Swag Labs", ".header_label")
```

**Comment by chiangbar** [comment]
`class TestFlow(BaseCase):
    @allure.step('1')
    @parameterized.expand([
        ['standard_user', 'secret_sauce'],
        ['visual_user', 'secret_sauce']
    ])
    def test_login(self, username, password):
        self.open("https://www.saucedemo.com/")
        self.type("#user-name", username)
        self.type("#password", password)
        self.click("#login-button")
        self.assert_text("Swag Labs", ".header_label")`

77/1000
实时翻译
划译
When I only added the @ allure. step ('1 ') code, this error occurs. Why is this? Why isn't selenium base compatible with allure, such an excellent library
![image](https://github.com/user-attachments/assets/5fe21344-5964-44c8-8652-11fc61d0c140)

**Comment by chiangbar** [comment]
> Your issue is coming from `allure`, or one of your other variables. I removed the `allure` part, but kept the rest, and it worked: (I had to fill in missing variables and use a known website)
> 
> ```python
> from seleniumbase import BaseCase
> from parameterized import parameterized
> BaseCase.main(__name__, __file__)
> 
> 
> class TestFlow(BaseCase):
>     @parameterized.expand([
>         ['standard_user', 'secret_sauce'],
>         ['visual_user', 'secret_sauce']
>     ])
>     def test_login(self, username, password):
>         self.open("https://www.saucedemo.com/")
>         self.type("#user-name", username)
>         self.type("#password", password)
>         self.click("#login-button")
>         self.assert_text("Swag Labs", ".header_label")
> ```



I hope seleniumbase can be better compatible with allure reports, because your reports are too difficult to use. Please follow the trend of the times

**Comment by mdmintz** [comment]
The same thing happens when using `unittest` instead:

```python
from unittest import TestCase
from parameterized import parameterized
import allure

class TestFlow(TestCase):
    @allure.step('1')
    @parameterized.expand([
        ['standard_user', 'secret_sauce'],
        ['visual_user', 'secret_sauce']
    ])
    def test_login(self, username, password):
        pass
```

`TypeError: unsupported callable`

----

However, if you change the order of the Python decorators, it works, even when using SeleniumBase:

```python
import allure
from seleniumbase import BaseCase
from parameterized import parameterized
BaseCase.main(__name__, __file__)

class TestFlow(BaseCase):
    @parameterized.expand([
        ['standard_user', 'secret_sauce'],
        ['visual_user', 'secret_sauce']
    ])
    @allure.step('1')
    def test_login(self, username, password):
        self.open("https://www.saucedemo.com/")
        self.type("#user-name", username)
        self.type("#password", password)
        self.click("#login-button")
        self.assert_text("Swag Labs", ".header_label")
```

(It works when `@allure.step` comes **after** `@parameterized.expand`.)

**Comment by chiangbar** [comment]
Salute to the expert, thank you very much
