### ISSUE TITLE
pip requests version upgrade

### ISSUE THREAD

**Issue by dmytrokoren** [seleniumbase/SeleniumBase#3097]
Hey @mdmintz 

Would it be possible to upgrade seleniumbase to support latest request 2.32.3 ?

ERROR: Cannot install -r requirements.txt (line 1), requests==2.32.3 and seleniumbase==4.30.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.32.3
    seleniumbase 4.30.3 depends on requests==2.31.0

https://github.com/seleniumbase/SeleniumBase/blob/4c455c46752e36ab6d469f6f293e09257178206a/setup.py#L176

I have force install requests==2.32.3 and seleniumbase worked just fine. Maybe there is something I don't know that won't work? Thanks in advance.

**Comment by mdmintz** [comment]
There's an issue with `requests` `2.32.3` leading to "widespread breakage", as mentioned in: https://github.com/psf/requests/issues/6730#issuecomment-2212573284, and I already talked about this specific one here: https://github.com/seleniumbase/SeleniumBase/issues/2951#issuecomment-2243105225.

There's already a PR in place to fix that major issue with `requests`: https://github.com/psf/requests/pull/6731. Until that fix is in, I'll need to keep `requests` pinned to `2.31.0`. (The versions between `2.31.0` and `2.32.3` had other issues.)

If you absolutely need `requests` `2.32.3` now (even with that issue), then feel free to force install it.
