### ISSUE TITLE
Blank page on using user_data_dir with headless mode

### ISSUE THREAD

**Issue by anastasiam** [seleniumbase/SeleniumBase#3100]
Hello,

Really appreciate the work that you've done, it's amazing.

I'm getting a blank white page when I'm `user_data_dir` with `headless` mode. This issue appeared afer updating Google Chrome from v.127 to v.128. The code still runs as expected though.
The code that I'm using:
```
from time import sleep
from seleniumbase import Driver

with Driver(browser="chrome",
            user_data_dir="path_to_user_data_dir",
            headless2=True) as detectableDriver:
    cookiesAll = detectableDriver.execute_cdp_cmd('Storage.getCookies', {})
    sleep(10) # Added sleep to see blank page, otherwise it quickly appears and disappears
    print('Done getting cookies.')

with Driver(uc=True, headless2=True, no_sandbox=True) as driver:
    print('Setting cookies...')
    res = driver.execute_cdp_cmd('Network.setCookies', cookiesAll)
```

I want to omit logging in using uc mode. For that I'm reading cookies from the Default Chrome profile and setting them in uc mode.

The blank page looks like this:
<img width="957" alt="image" src="https://github.com/user-attachments/assets/923d0429-dc83-4523-9d97-dfb9177bd7c3">

I would appreciate any help, thank you!

**Comment by anastasia-education** [comment]
Thank you so much for your responce!

The reason I was getting all cookies and not going to the website to get them is because I would need to open the website in `uc=False` mode with `user_data_dir` and I can be delected.

Is there something wrong with using `Storage.getCookies` and `Network.setCookies`? I'm planning to filter all received cookies to get only ones for the specific domain.

**Comment by anastasiam** [comment]
Thank you so much for your response!

The reason I was getting all cookies and not opening website is that by using `user_data_dir` in `uc=False` mode I can be detected. My code was working and I was able to get and set all cookies. I was planning to filter them by specific domain before setting.

**Comment by anastasiam** [comment]
Even though I won't be using headless mode and it's not relevant for me anymore, the problem with blank page still exists. Thought maybe it's something you should know.
`SB(user_data_dir='user_data_dir',headless2=True)`

**Comment by mdmintz** [comment]
If the blank page was the result of being detected, then you need to use UC Mode.
(uc=True)

**Comment by anastasiam** [comment]
I wasn't opening any website. It happens on driver initialization and the whole browser is white, just blank screen, not page. Maybe I said it wrong

**Comment by mdmintz** [comment]
If you mixed a UC Mode user-data-dir with a non UC Mode user-data-dir, (or the opposite), then unexpected things could happen. The two formats aren’t compatible.

**Comment by anastasiam** [comment]
I wasn't using user-data-dir with a UC Mode.

**Comment by anastasiam** [comment]
I was copying the whole directory from Chrome User Data directory location right before launching

**Comment by mdmintz** [comment]
That would be the problem. You mixed user-data-dir formats.
For SeleniumBase tests, let SeleniumBase create a new one for you when you specify the dir, and then don't mix the formats. Eg. Non UC Mode tests can use one dir.
UC Mode tests have to use another dir.
Can't be mixed.

**Comment by anastasiam** [comment]
So I can't use user-data-dir created by browser even with Non UC Mode?

**Comment by anastasiam** [comment]
Got it. Thank you for the explanation!
