### ISSUE TITLE
Question regarding sb.uc_gui_click_captcha()

### ISSUE THREAD

**Issue by sleepyzardo** [seleniumbase/SeleniumBase#3107]
what is the purpose? I have to solve a turnstile captcha on https://chess.com would this help?

**Comment by sleepyzardo** [comment]
import time
import logging
from seleniumbase import SB

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
logger = logging.getLogger()

# Define a function to get hidden input value by name
def get_hidden_input_value(driver, name):
    script = '''
    function getHiddenInputValueByName(name) {
        var inputElement = document.querySelector(`input[name="${name}"]`);
        if (inputElement) {
            return inputElement.value;
        } else {
            console.error('Input element with the specified name not found.');
            return null;
        }
    }
    return getHiddenInputValueByName(arguments[0]);
    '''
    value = driver.execute_script(script, name)
    return value

def func():
    with SB(uc=True) as sb:
        # Open the page with reconnect enabled
        sb.uc_open_with_reconnect(
            "http://chess.com/register",
            reconnect_time=2
        )
        sb.uc_click('.cc-button-component.cc-button-primary.cc-button-xx-large.cc-button-full.main-screen-button')
        sb.uc_click('.cc-button-component.cc-button-primary.cc-button-xx-large.cc-button-full.skill-level-button')
        
        time.sleep(3)

        sb.uc_gui_handle_captcha()
        sb.uc_gui_click_captcha()

        cookies = sb.get_cookies()
        cf_clearance = None
        for cookie in cookies:
            if cookie['name'] == 'cf_clearance':
                cf_clearance = cookie['value']
                logger.info(f"cf_clearance cookie found: {cf_clearance}")
                break
        if cf_clearance is None:
            logger.warning("cf_clearance cookie not found.")

        hidden_value = get_hidden_input_value(sb.driver, 'registration[turnstile_token]')
        if hidden_value:
            logger.info(f"Hidden input value: {hidden_value}")
        
        return cf_clearance, hidden_value



this doesnt seem to work the way i intend it to

**Comment by mdmintz** [comment]
See the **[UC Mode Docs](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md)**. There are lots of examples of how to use `sb.uc_gui_click_captcha()`.

----

<p>(<b><a href="https://www.youtube.com/watch?v=-EpZlhGWo9k">It's also covered in the 3rd UC Mode video tutorial on YouTube ▶️</a></b>)</p>
<a href="https://www.youtube.com/watch?v=-EpZlhGWo9k"><img src="http://img.youtube.com/vi/-EpZlhGWo9k/0.jpg" title="SeleniumBase on YouTube" width="342" /></a>
