### ISSUE TITLE
How to scroll on a tablebody that dymanically loads rows as it is scrolled through.

### ISSUE THREAD

**Issue by purpleZeahorze** [seleniumbase/SeleniumBase#3108]
There is a tag <tbody> that im trying to get. 

Currently it loads 6 rows, and to load more, the table needs to be clicked on and scrolled to the bottom, OR press "End" to get to the bottom. If possible, would like to loop this to load more data. The rows in the table are also indexed by CSS 

<tr data-index="5" data-item-index="5">

This is the code i am working with, when I run with headless=False to view the scraping, nothing happens.

with SB(uc=True, headless2=False ) as sb:
        sb.uc_open_with_reconnect(rot, 10)
        sb.wait_for_element_visible('tbody', timeout=5)
        sb.click('div.custom-8q3l37')   #Div containing tbody
        print('clicked')
        sb.scroll_to_bottom()
        sb.wait(5)

Expecting to see more rows loaded but nothing happens.

How can i simulate a click on the page on the table + press "End" on the keyboard or Scroll down alot to dynamically load the data?

**Comment by mdmintz** [comment]
You may need to use `pyautogui.hotkey("end")` to do it.
(See https://pyautogui.readthedocs.io/en/latest/keyboard.html#the-hotkey-function)
