### ISSUE TITLE
Better Chinese support

### ISSUE THREAD

**Issue by chiangbar** [seleniumbase/SeleniumBase#3115]
Dear seleniumbase author, could you please provide me with [https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md](url) Adding Chinese annotations to the API in is too powerful and powerful, sometimes it's hard to find,We are not accustomed to or fond of writing code in Chinese

**Comment by mdmintz** [comment]
It sounds like you're looking for [SeleniumBase/seleniumbase/translate/chinese.py](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/translate/chinese.py), which provides translations for the SeleniumBase methods in Chinese.

Example test: [SeleniumBase/examples/translations/chinese_test_1.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/translations/chinese_test_1.py).

```python
from seleniumbase.translate.chinese import 硒测试用例
硒测试用例.main(__name__, __file__)


class 我的测试类(硒测试用例):
    def test_例子1(self):
        self.开启("https://zh.wikipedia.org/wiki/")
        self.断言标题("维基百科，自由的百科全书")
        self.断言元素('a[title="Wikipedia:关于"]')
        self.如果可见请单击('button[aria-label="关闭"]')
        self.如果可见请单击('button[aria-label="關閉"]')
        self.断言元素('span:contains("创建账号")')
        self.断言元素('span:contains("登录")')
        self.输入文本('input[name="search"]', "舞龍")
        self.单击('button:contains("搜索")')
        self.断言文本("舞龍", "#firstHeading")
        self.断言元素('img[src*="Chinese_draak.jpg"]')
        self.回去()
        self.输入文本('input[name="search"]', "麻婆豆腐")
        self.单击('button:contains("搜索")')
        self.断言文本("麻婆豆腐", "#firstHeading")
        self.断言元素('figure:contains("一家中餐館的麻婆豆腐")')
        self.回去()
        self.输入文本('input[name="search"]', "精武英雄")
        self.单击('button:contains("搜索")')
        self.断言元素('img[src*="Fist_of_legend.jpg"]')
        self.断言文本("李连杰", 'li a[title="李连杰"]')
```

You can also use the SeleniumBase universal translator to translate any test from one language to another: [SeleniumBase/help_docs/translations.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/translations.md). Eg.

```bash
sbase translate basic_test.py --zh -p
```

Also see the [SeleniumBase Chinese Documentation](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/chinese.md).

**Comment by chiangbar** [comment]
No, I mean we Chinese people are not used to writing code in Chinese. I hope the author can improve it https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md Chinese annotation of encapsulation method

**Comment by mdmintz** [comment]
I'm not sure what you mean by that, but [SeleniumBase/seleniumbase/translate/chinese.py](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/translate/chinese.py) has the methods with Chinese descriptions.
