### ISSUE TITLE
Add an auto-retry for `uc_gui_click_captcha()` and `uc_gui_handle_captcha()`

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#3120]
### Add an auto-retry for `uc_gui_click_captcha()` and `uc_gui_handle_captcha()`

----

If you click the CAPTCHA with one of the special methods and you're still on the Turnstile page, then let's have UC Mode do one automatic retry, even if the `retry` or `blind` args are not set. This gives you another shot at getting through the CAPTCHA, even if you didn't on your first try.

There was some discussion on Discord (https://discord.com/invite/HDk5wYvzEZ) that calling `driver` methods between the `uc_open_with_reconnect()` and `uc_gui_click_captcha()` methods could cause CF to detect you, and then fail the CAPTCHA click after that. During the retry, it will call `uc_open_with_reconnect()` and `uc_gui_click_captcha()` together so that the user isn't given a chance to add a bad call in between there. (Or in the case of `uc_gui_handle_captcha()`, it will call `uc_open_with_reconnect()` and `uc_gui_handle_captcha()` together.)

This feature is needed because CF recently made some changes, which may prevent some existing scripts from keeping backwards compatibility.

Ideally, it would be better to make `driver` calls not be detectable at all. (I'm working on that too.) This ticket buys me some time so that I can keep the gears turning until I release a more stealthy version.

**Comment by mdmintz** [comment]
As a bonus, the changes I'm planning for this may also improve stealthiness.

**Comment by mdmintz** [comment]
This was resolved in `4.30.5` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.30.5

**Comment by Igiwigi** [comment]
Thanks so much for this, and in general, for your speedy updating of sb! Fixed my problem :)
