### ISSUE TITLE
UC incorrectly assumes it has failed CF turnstile captcha

### ISSUE THREAD

**Issue by Jovvik** [seleniumbase/SeleniumBase#3125]
These two checks are not correct for cloudflare:

https://github.com/seleniumbase/SeleniumBase/blob/6a057913b4971591b2ffdce51331c3d447cf391f/seleniumbase/core/browser_launcher.py#L992

https://github.com/seleniumbase/SeleniumBase/blob/6a057913b4971591b2ffdce51331c3d447cf391f/seleniumbase/core/browser_launcher.py#L1212

If there is `#challenge-success-text` present, the captcha has not failed, and the page just hasn't loaded yet (or the browser is redirected to a url with an unsupported protocol, which gets opened in an external app).

Repro (gets stuck inside `uc_gui_handle_captcha`), same issue with `uc_gui_click_captcha`:
```python
from seleniumbase import SB

with SB(uc=True, headed=True) as sb:
    sb.uc_open_with_reconnect(
        "https://csstats.gg/match/204001348/watch/3f164c7658b19e847cc83b3096b225a192637563b50596f908aa0a104386d57c",
        reconnect_time=6
    )
    sb.uc_gui_handle_captcha()
```

**Comment by mdmintz** [comment]
OK, technically a bug, but it wouldn't happen in a real-world scenario. That Turnstile redirects to `about:blank` after bypassing it, which wouldn't happen for a real Turnstile protecting a site.

**Comment by mdmintz** [comment]
I'll have a new release ready with the fix in the next 60 minutes.

**Comment by Jovvik** [comment]
This works for my use case, thanks for the fast release!
