### ISSUE TITLE
Add docstrings to the SeleniumBase Driver() and SB() definitions

### ISSUE THREAD

**Issue by J-sephB-lt-n** [seleniumbase/SeleniumBase#3146]
The argument documentation of the Driver function is just a bunch of comments in the function definition.
Can I move these comments to a docstring so that running ..
```python
from seleniumbase import Driver
help(Driver) 
```
.. prints useful documentation to the user?

Code: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/driver_manager.py

**Comment by mdmintz** [comment]
I'll update that in the next release.

**Comment by mdmintz** [comment]
This was resolved in `4.31.0` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.31.0
