### ISSUE TITLE
Any option to silence logs about starting uc_driver?

### ISSUE THREAD

**Issue by ruperson** [seleniumbase/SeleniumBase#3147]
I recieve logs like this on every uc command.
`Started executable: `C:\Users\ruperson\AppData\Roaming\Python\Python311\site-packages\seleniumbase\drivers\uc_driver.exe` in a child process with pid: 20900 using 134217728 to output -1`

Is there an elegant approach to get rid of this kind of notifications?

**Comment by mdmintz** [comment]
I haven't encountered those logging messages.
I couldn't find anywhere in the SeleniumBase code where that would be coming from.
I tried various searches to try finding them, but no results:
* https://github.com/search?q=repo%3Aseleniumbase%2FSeleniumBase%20%22Started%20executable%22&type=code
* https://github.com/search?q=repo%3Aseleniumbase%2FSeleniumBase+%22in+a+child+process%22&type=code
* https://github.com/search?q=repo%3Aseleniumbase%2FSeleniumBase+%22process+with+pid%22&type=code

Is it possible you have an external tool running that is generating those logs?

If I knew where those logs were coming from, then maybe I could suggest an idea for that. (Eg. Changing the default logging level, or something else.)
