### ISSUE TITLE
How disable notifications ? (popups, cookies ...)

### ISSUE THREAD

**Issue by JonasZaoui2** [seleniumbase/SeleniumBase#3151]
Hello ! 
I want to disable notifications, 
I tried this command  

```
from seleniumbase import Driver

self.driver = Driver(
            browser = 'chrome',
            uc=True,
            headless=True,
            chromium_arg="--disable-extensions, --disable-gpu, --disable-dev-shm-usage, --disable-notifications, --hide-scrollbars, --disabled-new-style-notification, --allow-silent-push"
        )
```

But it's not working ...
I tried on this URL : https://www.nvidia.com/fr-fr/

**Comment by mdmintz** [comment]
Notifications are already disabled by default:

https://github.com/seleniumbase/SeleniumBase/blob/d4e52465d13960957f26c6c02d04944cea4a6987/seleniumbase/core/browser_launcher.py#L1961

On the website you showed me, the part at the bottom is not an official browser "notification":

<img width="410" alt="Screenshot" src="https://github.com/user-attachments/assets/4a6b9a87-abae-4c39-a916-0cbe62bf3945">

(The part on the bottom is part of the website.)

When notifications are disabled, that part will still show up.

You'll have to interact with it to remove it:

`driver.click("#onetrust-accept-btn-handler")`

**Comment by JonasZaoui2** [comment]
Thanks for your feedback! 
In fact, I'll need to remove cookies regardless of the url given (for all sites). 
Is there a solution? 

<img width="1701" alt="Capture d’écran 2024-09-20 à 14 46 42" src="https://github.com/user-attachments/assets/bd09e7de-f759-458f-afa7-a491dbc69d85">

**Comment by JonasZaoui2** [comment]
Thanks for your feedback!
In fact, I'll need to remove cookies regardless of the url given (for all sites).
Is there a solution?


<img width="1702" alt="Capture d’écran 2024-09-20 à 14 47 21" src="https://github.com/user-attachments/assets/fd6e740e-a4e8-469f-b8f4-91ce6aabba80">

**Comment by mdmintz** [comment]
To delete all cookies:

```python
driver.delete_all_cookies()
```

**Comment by JonasZaoui2** [comment]
> To delete all cookies:
> 
> ```python
> driver.delete_all_cookies()
> ```

Not working ...

**Comment by mdmintz** [comment]
`driver.delete_all_cookies()` comes directly from raw Selenium:
https://github.com/SeleniumHQ/selenium/blob/030fcf79186e5597269166bd8dfa888e1eda29d7/py/selenium/webdriver/remote/webdriver.py#L614

**Comment by JonasZaoui2** [comment]
Thanks ! 
I tried but it's not working. But i have just found a solution with Selenium,

```
  chrome_options.add_experimental_option("prefs", {
            "profile.default_content_setting_values.cookies": 2
        })
```

**Comment by mdmintz** [comment]
To disable cookies, upgrade to SeleniumBase `4.31.2` (or newer) and use `--disable-cookies` / `disable_cookies=True`

**Comment by JonasZaoui2** [comment]
Thanks ! But it can't deal with cookies at the bottom of the website right ? Like here : https://soundcloud.com/
