### ISSUE TITLE
Support Type Hints 

### ISSUE THREAD

**Issue by Ehsan-U** [seleniumbase/SeleniumBase#3167]
It would be great to see type hints added to SeleniumBase to improve IntelliSense support in editors, making development easier.

**Comment by mdmintz** [comment]
Type hints are in the docstrings for `SB()` and `Driver()`. For example, here's part of the current  `SB()` docstring:

https://github.com/seleniumbase/SeleniumBase/blob/36f229b82a9d27c63df5da82119b53d6db854c15/seleniumbase/plugins/sb_manager.py#L149-L250

**Comment by mdmintz** [comment]
Also try https://github.com/seleniumbase/SeleniumBase/discussions/3402#discussioncomment-12506544

**Comment by Ehsan-U** [comment]
By type hints, I mean explicitly specifying parameter and return types, which helps the IDE provide better IntelliSense and improves the overall developer experience. What you're referring to seems to be just a docstring.

Here’s an example of code with proper type hints:
```python
from scrapy.http import Request, Response 
from typing import Iterable, Dict


def start_requests(self) -> Iterable[Request]:
    url = "https://www.opensecrets.org/news/feed"
    yield scrapy.Request(url, callback=self.parse)


def parse(self, response: Response) -> Iterable[Dict[str, str]]:
    for news in response.xpath("//item"):
        item = {
            "headline": news.xpath("./title/text()").get(),
        }
        yield item

```
