### ISSUE TITLE
Add relevant operation steps in Excel to complete web automation operations

### ISSUE THREAD

**Issue by chiangbar** [seleniumbase/SeleniumBase#3183]
Dear seleniumbase author, can we do web automation testing by simply filling in the relevant steps in Excel like in RobotFramework,I think this can enable more people to complete automated tasks without writing code and improve their work efficiency

**Comment by mdmintz** [comment]
There are no current plans for Excel support like that.
People can use the [SeleniumBase Recorder](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/recorder_mode.md) for instantly generating SeleniumBase test scripts without writing code.
