### ISSUE TITLE
raw_uc_mode.py example doesn't work

### ISSUE THREAD

**Issue by tqdo** [seleniumbase/SeleniumBase#3184]
I am using the latest seleniumbase (4.31.6) but when I ran this [example](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_uc_mode.py) it doesn't work, the checkbox doesn't even have time to show before reconnection happens. I am on Chrome, MacOs

**Comment by mdmintz** [comment]
The example is working for me. For slow internet connections, you may need to adjust your `reconnect_time`:

https://github.com/seleniumbase/SeleniumBase/blob/e6e3c97db39132415d402f59c5bfd55036c116f7/help_docs/method_summary.md?plain=1#L1063

(Use a number of seconds that's greater than the time it takes for your page to fully load.)
