### ISSUE TITLE
urllib3 version conflict

### ISSUE THREAD

**Issue by himasimplisafe** [seleniumbase/SeleniumBase#319]
We are experiencing issues with urllib3 and error is 
pkg_resources.VersionConflict: (urllib3 1.25 (/usr/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25.0,>=1.24.2'))

In https://github.com/seleniumbase/SeleniumBase/blob/master/requirements.txt, need to change urllib3 version from 1.24.2 to 1.25.0. urllib3 has a latest release 1.25.0, please check here https://pypi.org/project/urllib3/#history

Thanks

**Comment by himasimplisafe** [comment]
Do we have access to modify seleniumbase requirements.txt? In a way, we can modify it and make sure the fix works on our own. We have our own requirements.txt, where we had the latest version of urllib3 and it worked. If we can modify seleniumbase requirements.txt, we are not blocked until you fix requirements.txt.

**Comment by mdmintz** [comment]
Hi @himasimplisafe , looks like they just released urllib3 1.25 . I will ship a SeleniumBase update in 9 hours when I get back to my computer. In the meantime, you can update your requirements.txt file to allow the version you need.

**Comment by himasimplisafe** [comment]
It is good to know that there is python requests library https://github.com/kennethreitz/requests/pull/5063 fix is also in progress. So if you update urllib3 to 1.25, it is not going to work until https://github.com/kennethreitz/requests/pull/5063 is merged.

**Comment by mdmintz** [comment]
That’s the main reason I lock down urllib3 and requests versions: They don’t always play nice with each other.

**Comment by himasimplisafe** [comment]
Since you are already locked down requests and urllib3 versions, seleniumbase should go ahead with the versions you had in requirements.txt right, not sure why pkg version conflict with urllib3? Can you please explain?

**Comment by mdmintz** [comment]
Does the same situation happen for you in a python virtual environment?

**Comment by himasimplisafe** [comment]
For my local python virtual environment, I am not seeing issue using latest urllib3 version. But on CI(we use bees) only, I am seeing issue.

**Comment by mdmintz** [comment]
A more permanent solution would be for me to remove urllib3 from the requirements and to try using requests for everything instead. I think I only use urllib3 for chomedriver and other driver installation.

**Comment by himasimplisafe** [comment]
Once you remove urllib3, we could run our tests again. Thanks

**Comment by mdmintz** [comment]
Due to: ``requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25 which is incompatible.`` I can't remove urllib3 unless requests removes their requirement of urllib3.
I'm finding a workaround right now.

**Comment by himasimplisafe** [comment]
I am still confused that why seleniumbase has issues with urllib3 version 1.25, since you have hardcoded requests 2.21.0  and urllib3 1.24 versions.

**Comment by mdmintz** [comment]
@himasimplisafe Try with seleniumbase-1.23.4  . I think there's a bug with pip installs that use a range.

**Comment by mdmintz** [comment]
Once ``requests`` updates their requirements to allow the latest ``urllib3``, I'll update again.

**Comment by mdmintz** [comment]
urllib3 recently released https://github.com/urllib3/urllib3/releases/tag/1.24.3 , which patches a major issue. (Their newest versions have been 1.25.x up until now). Since ``requests`` is now in maintenance mode (according to https://github.com/kennethreitz/requests/blob/master/docs/index.rst , it is unlikely that they'll support the urllib3 1.25.x series any time soon. Therefore SeleniumBase will hardcode urllib3 version 1.24.3 for now. No issues detected with SeleniumBase so far, and now there are no more urllib3 conflicts. Closing this ticket.
