### ISSUE TITLE
Detected by Nike

### ISSUE THREAD

**Issue by pikulec777** [seleniumbase/SeleniumBase#3194]
Nike detects that I am using SeleniumBase. When I try to log in, I enter my email address and click the button to proceed, an error appears: Error while processing response from server

How to bypass this?

**Comment by mdmintz** [comment]
Here's an example of bypassing bot-detection on a site that uses real-time bot-scanning: [SeleniumBase/examples/raw_antibot_login.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_antibot_login.py).
