### ISSUE TITLE
Weirdly found a specific page on a specific site that detects seleniumbase every time

### ISSUE THREAD

**Issue by johnpjust** [seleniumbase/SeleniumBase#3199]
Was trying SB and it works great (typical examples from SB work really well in most places).  Why doesn't it work for this very specific page on this website below??  

url = "https://www.glassdoor.com/Reviews/index.htm"?
from seleniumbase import Driver
driver = Driver(uc=True)
driver.get(url) #detected as bot

**Comment by johnpjust** [comment]
just saw discussion section...I'll look there before posting this.

**Comment by mdmintz** [comment]
You may need to use the `SB()` format with `sb.uc_gui_click_captcha()`:

```python
from seleniumbase import SB

with SB(uc=True, incognito=True) as sb:
    url = "https://www.glassdoor.com/Reviews/index.htm"
    sb.uc_open_with_reconnect(url, 4)
    sb.uc_gui_click_captcha()
```
