### ISSUE TITLE
Usage of deprecated `desired_capabilities` in Selenium Wire

### ISSUE THREAD

**Issue by fgibertoni** [seleniumbase/SeleniumBase#3202]
Hello everyone!
I am getting a `TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'` using latest SeleniumBase version (v4.31.6) when instancing a `seleniumbase.Driver` object using Selenium Grid and Selenium Wire.

### How to reproduce
I am using Python 3.12.3, Selenium Base 4.31.6 and Google Chrome 130.0.6723.58.

Selenium Grid has been successfully started (following [docs](https://seleniumbase.io/seleniumbase/utilities/selenium_grid/ReadMe/)) with:
```
seleniumbase download server
seleniumbase grid-hub start
seleniumbase grid-node start
```

I am connecting to the grid running at `http://localhost:4444` with:
```
driver = Driver(
    headless=True,
    headless2=True,
    use_wire=True,
    no_sandbox=True,
    proxy=proxy_address or None,
    proxy_bypass_list=proxy_address or None,
    browser="chrome",
    servername="127.0.0.1",
    port=4444,
)
```
I expected to connect to my local instance of Selenium Grid to run some tests and analyze HTTP requests and responses.

### Error message
```
Traceback (most recent call last):
  File "/opt/deploy/analyzers/extract_site.py", line 62, in <module>
    analyze_target(target_url=arguments.target, proxy_address=arguments.proxy_address)
  File "/opt/deploy/analyzers/extract_site.py", line 46, in analyze_target
    driver_wrapper = DriverWrapper(proxy_address=proxy_address)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/deploy/analyzers/driver_wrapper.py", line 38, in __init__
    self.driver: Chrome = self._init_driver()
                          ^^^^^^^^^^^^^^^^^^^
  File "/opt/deploy/analyzers/driver_wrapper.py", line 47, in _init_driver
    driver = Driver(
             ^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/seleniumbase/plugins/driver_manager.py", line 782, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/seleniumbase/core/browser_launcher.py", line 2402, in get_driver
    return get_remote_driver(
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/seleniumbase/core/browser_launcher.py", line 2759, in get_remote_driver
    driver = webdriver.Remote(
             ^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/seleniumwire/webdriver.py", line 308, in __init__
    super().__init__(*args, **kwargs)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'
```

### Analysis
Selenium [removed](https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e) `desired_capabilities` from version 4.10.0 but Selenium Wire is still using it. Unluckily I don't think they will ever fix the issue as the project is no longer maintained.

During investigations I noticed that in [`browser_launcher.py`](https://github.com/seleniumbase/SeleniumBase/blob/e6e3c97db39132415d402f59c5bfd55036c116f7/seleniumbase/core/browser_launcher.py#L2953) there is no way to pass the optional parameter `auto_config=False` in `seleniumwire_options` that would prevent the [old code](https://github.com/wkeeling/selenium-wire/blob/da1b675fe2cc6dae2e3bb959c1ce95eb1c41830b/seleniumwire/webdriver.py#L306) from being executed.
Passing this parameter could be a workaround waiting for a more structured solution.

---

Is there another way to avoid this error or am I missing something here ?
Thank you for your help.

**Comment by mdmintz** [comment]
Wire Mode isn't compatible with Grid Mode anymore because [selenium-wire](https://github.com/wkeeling/selenium-wire) is unmaintained and archived.

The issues are coming directly from `selenium-wire`:
* https://github.com/wkeeling/selenium-wire/issues/697
* https://github.com/wkeeling/selenium-wire/issues/717

You have two options:
* Use Wire Mode without Grid Mode.
* Use Grid Mode without Wire Mode.

**Comment by fgibertoni** [comment]
Thank you for your answer.
I think this issue should be reported somewhere in the documentation (I was not able to find it).

Also, it should be enough to adapt the old code to avoid usage of the deprecated argument and passing the desired capabilities to the constructor together with `auto_config=False` to avoid the execution of the deprecated branch of code.
I understand this could be considered a bit messy, but I think that it would be useful to have an official workaround/patch for this issue.
What's your opinion on this proposal? We can also evaluate some other alternatives to have both Grid Mode and Wire Mode working together.

**Comment by mdmintz** [comment]
This can be the documentation if it wasn't clear:
* Can't mix Wire Mode with Grid Mode
* Can't mix UC Mode with Wire Mode
* Can't mix Grid Mode with UC Mode

If that doesn't work for you, try another repo.

**Comment by fgibertoni** [comment]
I apologize if I came across as disrespectful; that was not my intention, I really like this project.

I was just offering to help with this issue and looking to gather your feedback on whether you believe this would be beneficial for the community before I begin working on it :smile:

**Comment by mdmintz** [comment]
@fgibertoni You're welcome to look into it. Given that `selenium-wire` works by spinning up a local proxy server to collect the additional data, I don't think it would even work via a remote Grid machine. If you were just planning on running a local Grid for the multithreading, then that is unnecessary with the `pytest-xdist` multithreading system that's already built-in.
