### ISSUE TITLE
How to run on Remote Desktop Connection

### ISSUE THREAD

**Issue by zing75blog** [seleniumbase/SeleniumBase#3213]
I have a script that requires bypassing CF captcha but currently I am using Windows RDP, when I close my RDP then pyAutoGUI will stop working. is there a solution? should I use another OS?

**Comment by mdmintz** [comment]
UC Mode (and `PyAutoGUI`) won't work on remote servers. Only the local machine.

**Comment by zing75blog** [comment]
what if using a Linux VPS will it work?

**Comment by mdmintz** [comment]
Linux VPS is fine. It works in GitHub Actions.
