### ISSUE TITLE
When I updated to the latest version, it seemed like Chrome opened quite slowly so I just wanted to let you know

### ISSUE THREAD

**Issue by nhatxx** [seleniumbase/SeleniumBase#3221]

**Comment by mdmintz** [comment]
Bug tickets should include all relevant details, such as code used, stack traces, versions, OS, etc.
Also, make sure you're using the latest version of SeleniumBase (which is currently  `4.32.3` today).

**Comment by mdmintz** [comment]
Still not enough details in your description. I assume you are referring to UC Mode? It currently has to spin up an extra browser in advance to create the `user-data-dir` before using the actual browser. Takes a few extra seconds. Hopefully there's a better workaround soon.
