### ISSUE TITLE
I have problem when using chrome extension launched on extension home page my script commands are not working Someone please help me

### ISSUE THREAD

**Issue by nhatxx** [seleniumbase/SeleniumBase#3222]
from seleniumbase import Driver

driver = Driver(uc=True, extension_dir="Extension")
try:
    driver.open("https://pypi.org/project/seleniumbase/4.30.6a1/")
    import pdb; pdb.set_trace()
finally:
    driver.quit()

**Comment by nhatxx** [comment]
I just want to inform you that Uc mode is having an error with the extension. I have tested many different extensions and all have the same results.

**Comment by mdmintz** [comment]
Make sure your extension is a directory when using UC Mode. Regular `.crx` extensions aren't supported by UC Mode.
