### ISSUE TITLE
SeleniumBase Freezing when initializing in debugger

### ISSUE THREAD

**Issue by TheHolsback** [seleniumbase/SeleniumBase#3226]
I'm having a problem when initializing the Driver. When I run it through the vscode debugger, when I install the SeleniumBase library, it runs normally once. However, when I run it again through the debugger, it freezes when declaring the Driver (uc = True). Without the parameter, it runs normally.
disclaimer: it runs normally if I run it without the debugger.

**Comment by mdmintz** [comment]
Could be an issue with the VSCode Debugger. Use SeleniumBase's built-in debugger instead.
Lots of ways to activate it:
* pytest/pytest `--trace` (Debug Mode on start)
* pytest/pytest `--ftrace` (Debug Mode at end)
* pytest/pytest `--pdb` (Debug Mode on failures)
* `breakpoint()` (Debug Mode when reaching the breakpoint)
