### ISSUE TITLE
Issue with Chrome webdriver on ChromeOS

### ISSUE THREAD

**Issue by smf723** [seleniumbase/SeleniumBase#323]
Hi Michael,

Hopefully you are recovered from Saturday's bootcamp. For the second time I really enjoyed your session. So I'm the strange guy that's trying to run SeleniumBase on a ChromeBook via Crostini (terminal). Everything seems to install fine but I've hit an issue with the chrome webdriver. This is what I get when I try to test the webdriver:

mf723@penguin:~/SeleniumBase/examples$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> browser = webdriver.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.19.16-02893-g2cf2c17c8a43 x86_64)

The version of Chrome that I am using is Version 73.0.3683.114 (Official Build) (64-bit)

Any help would be greatly appreciated.
Thanks,
Sean

**Comment by mdmintz** [comment]
Hi Sean, you need Chromedriver on your system PATH. Or if you’re running a test that imports SeleniumBase’s BaseCase, you can call “seleniumbase install chromedriver” before that to download chromedriver to the SeleniumBase drivers folder. Try that and let me know how it goes.

**Comment by smf723** [comment]
smf723@penguin:~/SeleniumBase/seleniumbase/drivers$ seleniumbase install chromedriver 
Downloading chromedriver_linux64.zip from:
http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver_linux64.zip ...
Unzip Complete!

/home/smf723/SeleniumBase/seleniumbase/drivers/chromedriver saved!

Making /home/smf723/SeleniumBase/seleniumbase/drivers/chromedriver executable ...
/home/smf723/SeleniumBase/seleniumbase/drivers/chromedriver is now ready for use!

smf723@penguin:~/SeleniumBase/seleniumbase/drivers$ ls -l
total 16480
-rwxr-xr-x 1 smf723 smf723 8136192 Apr 30 00:20 chromedriver
-rwxrwxr-x 1 smf723 smf723 8724590 Jan 28 22:49 geckodriver
-rwxr-xr-x 1 smf723 smf723       0 Apr 27 19:22 __init__.py
-rw-r--r-- 1 smf723 smf723     145 Apr 27 19:25 __init__.pyc
-rwxr-xr-x 1 smf723 smf723    1054 Apr 27 19:22 ReadMe.md

Here is my path:
smf723@penguin:~/SeleniumBase/examples$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin

smf723@penguin:~/SeleniumBase/examples$ pytest my_first_test.py --browser=chrome
================================ test session starts ================================
platform linux2 -- Python 2.7.13, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/smf723/SeleniumBase, inifile: pytest.ini
plugins: xdist-1.28.0, rerunfailures-7.0, ordering-0.6, metadata-1.8.0, html-1.20.0, forked-1.0.2, cov-2.6.1, seleniumbase-1.23.6
collected 1 item                                                                    

my_first_test.py F

===================================== FAILURES ======================================
______________________________ MyTestClass.test_basic _______________________________
../seleniumbase/fixtures/base_case.py:3199: in setUp
    disable_csp=self.disable_csp)
../seleniumbase/fixtures/base_case.py:2753: in get_new_driver
    disable_csp=disable_csp)
../seleniumbase/core/browser_launcher.py:267: in get_driver
    proxy_user, proxy_pass, user_agent, disable_csp)
../seleniumbase/core/browser_launcher.py:515: in get_local_driver
    return webdriver.Chrome(executable_path=LOCAL_CHROMEDRIVER)
/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py:81: in __init__
    desired_capabilities=desired_capabilities)
/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py:157: in __init__
    self.start_session(capabilities, browser_profile)
/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py:252: in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f9731cc56d0>
response = {'sessionId': 'a52d3e07d68b7edc1fb60b2a16991d9a', 'status': 13, 'value': {'message': 'unknown error: cannot find Chrom...romedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.19.16-02893-g2cf2c17c8a43 x86_64)'}}

    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
      exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
       elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: unknown error: cannot find Chrome binary
E         (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.19.16-02893-g2cf2c17c8a43 x86_64)

/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
============================= 1 failed in 9.03 seconds ==============================

Could it be an issue with the Chromedriver version? I noticed it's looking for version 2.40.565383 yet when I look at this site (http://chromedriver.chromium.org/downloads) I think it should be using ChromeDriver 73.0.3683.68. Is the Chromedriver version dependent on the version of Chrome you have installed on your system?

**Comment by mdmintz** [comment]
Based on https://stackoverflow.com/a/24391989 It looks like it found ChromeDriver just fine. It cannot find the Chrome browser executable, which is unusual because you're using a Chromebook. Is there a Chrome executable that you can place on your system PATH in the Chrome? Also, looking at https://www.seleniumhq.org/about/platforms.jsp it seems that Chromebooks/ChromeOS are not on the list of supported operating systems. I don't have a Chromebook to help figure this out, but if you're able to find a solution to getting it working, please share. :)

**Comment by smf723** [comment]
Well this is embarrassing. I'm running on a Chromebook so I naturally assumed the chromium was installed. Well it is in the host but it's not installed in Crostini shell. Executed sudo apt-get install chromium and voila it works!

You know I just wanted to be one of the cool kids whipping out my chromebook and running crostini shell. In the end I realize I'm just an old fart faking it.
