### ISSUE TITLE
Not passing cloudflare turnstile

### ISSUE THREAD

**Issue by TheHolsback** [seleniumbase/SeleniumBase#3237]
When I enter the site it doesn't ask for any captcha, so I try to log in, when I log in it doesn't go through so I checked the console, I get the following errors:
Turnstile error: 600010
[Cloudflare Turnstile] Error: 600010.

I'm using the latest version of seleniumbase and the following command for the browser:
Driver(uc=True)

**Comment by mdmintz** [comment]
According to https://community.cloudflare.com/t/repeated-cloudflare-turnstile-error-600010/644578, that means there's an error with that site's configuration. There's not enough information in your ticket to provide an actionable response. See the UC Mode examples in the `examples/` folder for assistance. (The examples are working correctly at this time.)
