### ISSUE TITLE
Uc mode turnstile cloudflare captcha issue

### ISSUE THREAD

**Issue by BelugaWhale** [seleniumbase/SeleniumBase#3243]
I am running this code:

from seleniumbase import Driver
import time

driver = Driver(uc=True)
try:
    driver.uc_open_with_reconnect("...", 4)
    time.sleep(20)
finally:
    driver.quit()

I am getting successful check on https://seleniumbase.io/apps/brotector

The url of the website I would prefer to share in a private message, please tell me where I can provide that. (not a secret, but dont want to post it publicly anyway)

**Comment by mdmintz** [comment]
For bypassing the Brotector CAPTCHA with regular UC Mode, you would need something like this:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://seleniumbase.io/apps/brotector"
    sb.uc_open_with_disconnect(url, 2.2)
    sb.uc_gui_press_key("\t")
    sb.uc_gui_press_key(" ")
    sb.reconnect(2.2)
```

You can also use CDP Mode. Here's an example for a more complex site that uses the Brotector CAPTCHA:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://seleniumbase.io/antibot/login"
    sb.activate_cdp_mode(url)
    sb.press_keys("input#username", "demo_user")
    sb.press_keys("input#password", "secret_pass")
    x, y = sb.cdp.get_gui_element_center("button#myButton")
    sb.uc_gui_click_x_y(x, y)
    sb.sleep(1.5)
    x, y = sb.cdp.get_gui_element_center("a#log-in")
    sb.uc_gui_click_x_y(x, y)
    sb.assert_text("Welcome!", "h1")
    sb.set_messenger_theme(location="bottom_center")
    sb.post_message("SeleniumBase wasn't detected!")
    sb.sleep(1.5)
```

**Comment by mdmintz** [comment]
You would need to share the script you used. (You can remove the URL if that's private.)

**Comment by mdmintz** [comment]
The latest version is `4.32.7` right now.

Use a script like this:

```python
from seleniumbase import SB

with SB(uc=True, test=True, locale_code="en") as sb:
    url = "https://gitlab.com/users/sign_in"
    sb.activate_cdp_mode(url)
    sb.sleep(2)
    sb.uc_gui_click_captcha()
    breakpoint()
```

Swap in your URL.
