### ISSUE TITLE
Add browser arguments

### ISSUE THREAD

**Issue by schamen** [seleniumbase/SeleniumBase#3248]
why this method don't work?
    sb.driver.options.add_argument("--disable-crash-reporter")
    sb.driver.options.add_argument("--noerrdialogs")
    sb.driver.options.add_argument("--log-level=3")

**Comment by mdmintz** [comment]
Driver args are set when launching the driver. Eg:

https://github.com/seleniumbase/SeleniumBase/blob/7fadabdfd59588f734a68d4c66b3aa6fa6c24363/seleniumbase/plugins/sb_manager.py#L30-L38

They can also be set via the command-line. (See [customizing_test_runs](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/customizing_test_runs.md) for `pytest` options.)

Example of setting options within a script:

```python
from seleniumbase import SB

with SB(enable_3d_apis=True, test=True) as sb:
    sb.open("threejs.org/examples/#webgl_animation_skinning_morph")
    sb.sleep(3)
```
