### ISSUE TITLE
Linux -  uc_gui_click_captcha() and uc_gui_click_cf() do not even tick the box whilst uc_gui_handle_captcha() does

### ISSUE THREAD

**Issue by Jelly-Pudding** [seleniumbase/SeleniumBase#3249]
I'm on Linux and trying to handle a Cloudflare Turnstile CAPTCHA on https://www.planetminecraft.com/account/sign_in/

This can click the captcha (which does actually fail - but the captcha is nevertheless clicked):

```python
from seleniumbase import SB
with SB(uc=True) as sb:
    sb.uc_open_with_reconnect('https://www.planetminecraft.com/account/sign_in/', reconnect_time=2)
    sb.uc_gui_handle_captcha()  # Successfully clicks the CAPTCHA
```

So although that clicks it, the captcha does actually fail. I did see this in the documentation:

"If running on a Linux server, uc_gui_handle_captcha() might not be good enough. Switch to uc_gui_click_captcha() to be more stealthy."

However, these do NOT work (CAPTCHA is never even clicked):

```python
sb.uc_gui_click_captcha()
sb.uc_gui_click_cf()
```

May be doing this wrong, but I even tried various parent selectors with uc_gui_click_cf():

```python
sb.uc_gui_click_cf(frame=".turnstile")
sb.uc_gui_click_cf(frame="#turnstile-widget") 
sb.uc_gui_click_cf(frame="#full_screen")
```

Expected: uc_gui_click_cf() should work as a more stealthy alternative to uc_gui_handle_captcha()
Actual: Only uc_gui_handle_captcha() successfully clicks the CAPTCHA

System info:
Python: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
OS: Linux-6.1.0-25-amd64-x86_64-with-glibc2.36  (using debian bookworm)

Python versions:
SeleniumBase: 4.32.7
Selenium: 4.26.1
PyAutoGUI: 0.9.54
undetected-chromedriver: 3.5.5

Chrome Browser: 130.0.6723.116

**Comment by mdmintz** [comment]
Looks like you're using older examples. Try the new [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md):

```python
from seleniumbase import SB

with SB(uc=True, test=True, locale_code="en") as sb:
    url = "www.planetminecraft.com/account/sign_in/"
    sb.activate_cdp_mode(url)
    sb.sleep(1)
    sb.cdp.gui_click_element("#turnstile-widget")
    sb.sleep(2)
```

Unlike regular UC Mode, CDP Mode is more stealthy, and lets you perform browser actions while the WebDriver is disconnected from the browser. CDP Mode is a subset of UC Mode. To activate, use: `sb.activate_cdp_mode(url)`.
Then use the new `sb.cdp` methods, or switch back to regular SB methods by calling `sb.reconnect()`.
The `sb.cdp` methods can be found in [examples/cdp_mode/ReadMe.md](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md#-cdp-mode-api--methods).
