### ISSUE TITLE
hcaptcha solver

### ISSUE THREAD

**Issue by plscomeback** [seleniumbase/SeleniumBase#3255]
Does the UC solve this captcha, I mean a simple click, or am I doing something wrong?:

**Comment by mdmintz** [comment]
UC Mode makes bots appear human, however, hCaptcha throws CAPTCHAs at **both** bots and humans alike.
Therefore, UC Mode won't bypass hCaptcha unless hCaptcha allows regular humans to pass without solving a CAPTCHA.

**Comment by mdmintz** [comment]
Times have changed. This example: [SeleniumBase/examples/cdp_mode/raw_nevada_search.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/raw_nevada_search.py) bypasses hCaptcha now.

**Comment by pawlek** [comment]
> Times have changed. This example: [SeleniumBase/examples/cdp_mode/raw_nevada_search.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/raw_nevada_search.py) bypasses hCaptcha now.

Is it still works ?

**Comment by mdmintz** [comment]
[SeleniumBase/examples/cdp_mode/raw_nevada_search.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/raw_nevada_search.py) still works. 
Bypasses an hCaptcha that only makes you solve a puzzle if it detects a bot.

**Comment by mdmintz** [comment]
Watch the video about it: <b>https://www.youtube.com/watch?v=zTxITHhAqP0</b>

<a href="https://www.youtube.com/watch?v=zTxITHhAqP0"><img src="https://github.com/user-attachments/assets/8ab2369e-73dc-4482-b710-5ae5187a1111" title="Bypassing hCaptcha with CDP and Python" width="500" /></a>

SeleniumBase's `solve_captcha()` can click Imperva's hCaptcha successfully.
