### ISSUE TITLE
Need Help Handling Conditional CAPTCHA Challenges with uc_gui_click_captcha()

### ISSUE THREAD

**Issue by officicalalkhaldi** [seleniumbase/SeleniumBase#3276]
Hi, I’m using SeleniumBase on **Windows**, and I’m having trouble figuring out how to handle websites that sometimes throw a CAPTCHA challenge (like **Cloudflare Turnstile**). 

Here’s what I’m trying to do:

I’ve written a script to open a website and click the CAPTCHA using uc_gui_click_captcha() method. But the problem is that I don’t know how to detect if the CAPTCHA is actually present before calling that method. Sometimes the challenge doesn’t show up, and I don’t want the script to break or waste time trying to click a CAPTCHA that’s not there.

Here’s the script I’m using:

```
import time
from seleniumbase import Driver

with Driver(
    uc=True,
    binary_location=r"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe",
    agent=r"Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    undetectable=True,
) as driver:
    driver.uc_open_with_reconnect(
        "https://2captcha.com/demo/cloudflare-turnstile-challenge", 4
    )
    driver.uc_gui_click_captcha()
    time.sleep(60)
    driver.quit()
```

f there’s a better way to handle this scenario, maybe an if statement It’d valuable to me and maybe to others, I really appreciate any guidance.

Thanks in advance!

**Comment by mdmintz** [comment]
The `uc_gui_click_captcha()` method automatically checks to see if there's a CAPTCHA before trying to click one.
If there's no CAPTCHA on the page, then nothing happens when that method is called.

**Comment by darobles** [comment]
> The `uc_gui_click_captcha()` method automatically checks to see if there's a CAPTCHA before trying to click one. If there's no CAPTCHA on the page, then nothing happens when that method is called.

Is this working? I am facing same problem here. basically this is my code that works well when captcha is present but when it is not then mouse moves by it self and clicks on the corner which makes the page navigate to another place

driver = Driver(uc=True, incognito=True, headless=False)
   url = https://partsouq.com/en/search/all?q=JTDKBAB3X01016698
  driver.uc_open_with_reconnect(url, 5)
  driver.sleep(2)
  driver.uc_gui_click_captcha()
  content_results = WebDriverWait(driver, 15).until(
      EC.presence_of_element_located((By.CLASS_NAME, 'search-result-container'))
  )
  elements = driver.find_element(By.CLASS_NAME, 'search-result-container')
  table = elements.find_element(By.CLASS_NAME, 'table')

**Comment by SSujitX** [comment]
> > The `uc_gui_click_captcha()` method automatically checks to see if there's a CAPTCHA before trying to click one. If there's no CAPTCHA on the page, then nothing happens when that method is called.

try using CDP and updated version

`pip3 install seleniumbase -U`


```
from seleniumbase import SB

with SB(uc=True, test=True, locale="en") as sb:
    url = "https://partsouq.com/en/search/all?q=JTDKBAB3X01016698"
    sb.activate_cdp_mode(url)
    sb.uc_gui_click_captcha()
    sb.sleep(2)
```
