### ISSUE TITLE
dublicate url when using sb.open in cycle

### ISSUE THREAD

**Issue by SenseiSol** [seleniumbase/SeleniumBase#3284]
https://www.sofascore.comhttps//www.sofascore.com/ru/football/match/pharco-fc-enppi/owrsdJWb#id:13015449 getting like this when using
    def get_games_info(self, links):
        games_info = []
        for link in links:
            self.sb.open(link)
            time.sleep(1)

**Comment by mdmintz** [comment]
Please format code properly using [Markdown Syntax](https://www.markdownguide.org/).
Use a clear [Syntax Format](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) when creating your example.
It looks like you have incorrectly created your list of links.
