### ISSUE TITLE
Long Press or Long Click for the element using cdp method!

### ISSUE THREAD

**Issue by mynguyen95dn** [seleniumbase/SeleniumBase#3285]
Hi , I tried to use cdp mode to click and hold button by selector. Any idea for that case?

Thank you!

**Comment by mdmintz** [comment]
Press-and-hold in [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md) is just `sb.cdp.gui_drag_and_drop(drag_selector, drop_selector, timeframe)`, where the `drag_selector` is the same as the `drop_selector`.

https://github.com/seleniumbase/SeleniumBase/blob/d8d02cd4740e700ef6ea3b133bbdc9830e728cf4/seleniumbase/core/sb_cdp.py#L1304
