### ISSUE TITLE
UC-Mode not working with Captcha?

### ISSUE THREAD

**Issue by Rapid1898-code** [seleniumbase/SeleniumBase#3305]
Hello - i try to use SeleniumBase with UC-mode for the following url -

```
from seleniumbase import SB
agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0"
with SB(uc=True, test=True, rtf=True, agent=agent) as sb:
  url = "https://www.indeed.com/jobs?q=Executive+chef&l=USA&radius=100&start=0"
  sb.uc_open_with_reconnect(url, 4)
  sb.uc_gui_click_captcha()
  input("Press!")
```

But the captcha is not clicked at all?
Why is this not working?

Isn´t this the same like the example form here
https://gitlab.com/users/sign_in
where its working without problems?

**Comment by Pedro0152** [comment]
This worked for me

```
from seleniumbase import SB
with SB(uc=True,test=True) as sb:
    url = "https://www.indeed.com/jobs?q=Executive+chef&l=USA&radius=100&start=0"
    sb.activate_cdp_mode(url)
    sb.sleep(3)
    sb.uc_gui_click_captcha()
    input("Press!")
    
```

**Comment by Rapid1898-code** [comment]
Thanks a lot for the response - but its not working on my site:

![image](https://github.com/user-attachments/assets/59d93bc4-ae1f-4328-9091-9ed98b591453)

**Comment by mdmintz** [comment]
This is working:

```python
from seleniumbase import SB

with SB(uc=True, test=True, locale_code="en") as sb:
    url = "https://www.indeed.com/jobs?q=Executive+chef&l=USA&radius=100&start=0"
    sb.activate_cdp_mode(url)
    sb.sleep(1)
    selector = "form#challenge-form div div"
    if sb.cdp.is_element_visible(selector):
        sb.cdp.gui_click_element(selector)
    sb.sleep(5)
```

**Comment by Rapid1898-code** [comment]
Hello - thanks again -
I also tried this code - but again it is not working on my site -

![image](https://github.com/user-attachments/assets/58a97790-b4c9-4534-a62b-a637cc1da245)

**Comment by Rapid1898-code** [comment]
I saw that its working on one of my computer but not the other computer i have (both are Windows)
