### ISSUE TITLE
iframe error using sb.activate_cdp_mode()

### ISSUE THREAD

**Issue by FrostUNK** [seleniumbase/SeleniumBase#3313]
Hello,I am using the sb.activate_cdp_mode() method to bypass automation detection when solving a custom captcha. However, when I activate this mode, the sb.switch_to.frame(iframe) method stops working, I get an error: Element {iframe} was not present after 10 seconds!
If I use the sb.get(url) method, then switching to iframe using sb.switch_to.frame(iframe) works without problems.
What could be causing this problem and how can I fix it so that switching to iframe continues to work when using sb.activate_cdp_mode()? Thanks.

**Comment by mdmintz** [comment]
While the driver is disconnected from the browser, use the `nested` methods to get inside iframes.
Eg. `sb.cdp.nested_click("iframe#myFrame3", ".fBox")`

https://github.com/seleniumbase/SeleniumBase/blob/c909b1aae04172be680d75543ea9acfa2521af54/examples/cdp_mode/raw_demo_site.py#L70

Nested methods:

```python
sb.cdp.nested_click(parent_selector, selector)
sb.cdp.get_nested_element(parent_selector, selector)
```

Or call `sb.reconnect()`, and then use the usual `iframe` methods like `switch_to_frame(iframe)`. (Note that this could make the bot detectable.)

**Comment by FrostUNK** [comment]
Can you tell me how to solve captchas that require a slider (without images)? just they are inside an iframe and I ran into a problem in it. sb.uc_gui_click_captcha() doesn't help either

**Comment by FrostUNK** [comment]
maybe the iframe is blocking access?
