### ISSUE TITLE
Freezing / hang issue

### ISSUE THREAD

**Issue by scrapenetwork** [seleniumbase/SeleniumBase#3315]
On macOs 

im having this issue with using uc_gui_click()

inside a function 
( def function1 (): with SB…. )
for some reason does not work , the browser gets caught in a “hung” state , as the mouse does in fact move, the page is in a frozen state.

Same snippet without function (def etc) 
With SB ….

the snippet runs fine , no hanging

**Comment by mdmintz** [comment]
This is working for me:

```python
from seleniumbase import SB

def my_function():
    with SB(uc=True, test=True, locale_code="en", incognito=True) as sb:
        url = "https://wsform.com/demo/"
        sb.activate_cdp_mode(url)
        sb.scroll_into_view("div.grid")
        sb.uc_gui_click_captcha()
        sb.sleep(1)

if __name__ == "__main__":
    my_function()
```

**Comment by scrapenetwork** [comment]
Try adding an import 

same script on my end works
Adding import httpx hangs and stays frozen 
Using uc_gui_click_x_y not captcha 

let me know I can take a video as well
Tried to debug the issue but seems it was imports
