### ISSUE TITLE
Integrating selenium base with dotnet

### ISSUE THREAD

**Issue by Anurag130899** [seleniumbase/SeleniumBase#3326]
Actually, I am writing code in C# programming language using dotnet framework.
I am using undetected chrome-driver but its not enough to bypass detection.
Is there any possibility to integrate selenium base uc mode specifically for C#.
It would be more feasible rather than using sb from python and handle it in enterprise level.

**Comment by mdmintz** [comment]
SeleniumBase is for Python, only.
