### ISSUE TITLE
Should --disable-component-update be removed?

### ISSUE THREAD

**Issue by tkozybski** [seleniumbase/SeleniumBase#3329]
https://github.com/puppeteer/puppeteer/issues/13010

```
Summarizing the “why” here:

The --disable-component-update command-line flag does two things: it disables component updates (desired) but it also prevents any bundled components from being initialized (undesired).

Since CfT bundles a few components (hyphenation data, MEIPreload, WidevineCdm) the latter effect is problematic.

The above-mentioned CL changes CfT to disable component updates by default (without the need for any command-line flags) while still allowing bundled components to be initialized.
```

--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT" already disables update checks, and with --disable-component-update https://demo.fingerprint.com/playground detects Chrome as nodriver, even if you didn't run it with Selenium, just this flag alone..

**Comment by mdmintz** [comment]
Good catch. It probably should be removed. I can do that for the next release.
