### ISSUE TITLE
Firefox Addons Not Working

### ISSUE THREAD

**Issue by BelugaByte** [seleniumbase/SeleniumBase#3341]
Hello,

when I add a Firefox addon with `sb.install_addon(“./ublock_origin-1.61.2.xpi”)`, the addon is displayed in Firefox, but does not work. But if I manually change “Run in Private Windows” to allow, it works.

I read online that “extensions.allowPrivateBrowsingByDefault” has been removed from Firefox. Is there another solution that I have overlooked?

thanks in advance.

```
from seleniumbase import SB

with SB(browser="firefox") as sb:
    sb.open("about:blank")
    sb.install_addon("./ublock_origin-1.61.2.xpi")

    sb.open("https://www.finanzen.net/")
```

**Comment by mdmintz** [comment]
Hello,

1. I tested on `4.33.11` with [seleniumbase/extensions/firefox_addon.xpi](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/extensions/firefox_addon.xpi), and the add-on was loaded successfully. Check on that version (or newer if available). It could be an issue with your extension if it didn't work.
2. SeleniumBase has a built-in `ab_block` option for Chromium.
3. SeleniumBase just redirects the `install_addon()` call to ` self.driver.install_addon(xpi_path)` - https://github.com/seleniumbase/SeleniumBase/blob/v4.33.11/seleniumbase/fixtures/base_case.py#L4768 (which means if there was an actual bug there, you'd have to check directly with https://github.com/SeleniumHQ/selenium).
