### ISSUE TITLE
why when i press enter it make for me a new line 

### ISSUE THREAD

**Issue by pythondeveloperz** [seleniumbase/SeleniumBase#3343]
for i in "seleniumbase2025\n": sb.sleep(0.5) ,sb.cdp.press_keys('[name="q"]', i)
  i use this line to press Enter after write the keyword but it make a new line can i know how to press Enter ?

**Comment by mdmintz** [comment]
`\n` is working correctly for me with `press_keys()`:

https://github.com/seleniumbase/SeleniumBase/blob/907a9842bb0238b9a22ccc21651bb5c6e64ff695/examples/cdp_mode/raw_walmart.py#L11

For your specific site, you may want to try calling some of the built-in `PyAutoGUI` methods if you need a different result.
Eg. `self.uc_gui_press_keys(keys)`
https://github.com/seleniumbase/SeleniumBase/blob/907a9842bb0238b9a22ccc21651bb5c6e64ff695/help_docs/method_summary.md?plain=1#L1001
