### ISSUE TITLE
Headless=False

### ISSUE THREAD

**Issue by scrapenetwork** [seleniumbase/SeleniumBase#3349]
from seleniumbase import SB

with SB(uc=True, test=True, locale_code="en", ad_block=True) as sb:
    url = "https://www.pokemon.com/us"
    sb.activate_cdp_mode(url)
    sb.sleep(3.2)
    sb.cdp.click("button#onetrust-accept-btn-handler")
    sb.sleep(1.2)
    sb.cdp.click("a span.icon_pokeball")
    sb.sleep(2.5)
    sb.cdp.click('b:contains("Show Advanced Search")')
    sb.sleep(2.5)
    sb.cdp.click('span[data-type="type"][data-value="electric"]')
    sb.sleep(0.5)
    sb.scroll_into_view("a#advSearch")
    sb.sleep(0.5)
    sb.cdp.mouse_click("a#advSearch")
    sb.sleep(1.2)
    sb.cdp.click('img[src*="img/pokedex/detail/025.png"]')
    sb.cdp.assert_text("Pikachu", 'div[class*="title"]')
    sb.cdp.assert_element('img[alt="Pikachu"]')
    sb.cdp.scroll_into_view("div.pokemon-ability-info")
    sb.sleep(1.2)
    sb.cdp.flash('div[class*="title"]')
    sb.cdp.flash('img[alt="Pikachu"]')
    sb.cdp.flash("div.pokemon-ability-info")
    name = sb.cdp.get_text("label.styled-select")
    info = sb.cdp.get_text("div.version-descriptions p.active")
    print("*** %s: ***\n* %s" % (name, info))
    sb.sleep(2)
    sb.cdp.highlight_overlay("div.pokemon-ability-info")
    sb.sleep(2)
    sb.cdp.click('a[href="https://www.pokemon.com/us/play-pokemon/"]')
    sb.sleep(0.6)
    sb.cdp.click('h3:contains("Find an Event")')
    location = "Concord, MA, USA"
    sb.cdp.type('input[data-testid="location-search"]', location)
    sb.sleep(1.5)
    sb.cdp.click("div.autocomplete-dropdown-container div.suggestion-item")
    sb.sleep(0.6)
    sb.cdp.click('img[alt="search-icon"]')
    sb.sleep(2)
    events = sb.cdp.select_all('div[data-testid="event-name"]')
    print("*** Pokemon events near %s: ***" % location)
    for event in events:
        print("* " + event.text)
    sb.sleep(2)
    
    
    
    
    How do I turn Headless Off here? I want to see the browser

**Comment by SSujitX** [comment]
Headless mode is not enabled in the arguments. (headeless=True) means you can not see the browser. Therefore, the browser will be visible during the session. Please create a virtual environment and update SeleniumBase to the latest version to see the changes.

**Comment by mdmintz** [comment]
On Linux, headless/Xvfb is the default option. Use `headed=True` to see the browser if running on Linux.

**Comment by scrapenetwork** [comment]
> On Linux, headless/Xvfb is the default option. Use `headed=True` to see the browser if running on Linux with a GUI.


Yup on Mac headful
Ub server defaults to headless

When running test.py —headed only the first request is respected , following pages / new pages are all headless 

I’ll try setting headed=True

Also what I noticed on server the mouse movements don’t work , but using pyautogui without seleniumbase works fine .

**Comment by mdmintz** [comment]
With SeleniumBase, you can use the `PyAutoGUI` methods indirectly from `sb.uc_gui_*`, or you can just call the `PyAutoGUI` methods directly from that library from within CDP Mode.
