### ISSUE TITLE
Switch a Tab to Mobile Mode

### ISSUE THREAD

**Issue by oniononion36** [seleniumbase/SeleniumBase#3353]
In my use case, I need the website to be loaded on a desktop window but then get switched into mobile mode. In normal Chrome I can just open devtools and toggle to device mode. Is there a way to do this with selenium-base? Thanks!

**Comment by mdmintz** [comment]
The mobile emulator is set at start-up only. `mobile=True` for `SB()` and `Driver()` formats. Or `--mobile` for the `pytest` formats. For documentation, see [SeleniumBase/help_docs/mobile_testing.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/mobile_testing.md).
