### ISSUE TITLE
Use SeleniumBase with already opened Chrome by remote debugging address

### ISSUE THREAD

**Issue by vannguyen799** [seleniumbase/SeleniumBase#3354]
any solution to connect SeleniumBase with already opened Chrome by remote debugging address

Example in selenium:

```
chrome_service = ChromeService(driver_path)
chrome_options = Options()

chrome_options.debugger_address = f'{remote_debugging_address}'
driver = webdriver.Chrome(service=chrome_service, options=chrome_options)
```

**Comment by tomyo** [comment]
I was about to ask a similar question, would like this to run on a browser session with WhatsApp logged in, so I can read a public group messages...  That would be awesome.

**Comment by mdmintz** [comment]
That's doable if you already know the `host` (should be `"127.0.0.1"`) and the remote-debugging `port`.

Here's an `async` example:
(**assuming there's already an active Chrome instance using `9222` as the remote debugging port**)

```python
import asyncio
from seleniumbase.undetected.cdp_driver import cdp_util

async def main():
    host = "127.0.0.1"
    port = 9222
    driver = await cdp_util.start_async(host=host, port=port)
    page = await driver.get("https://seleniumbase.io/")
    await asyncio.sleep(2)
    print(await page.evaluate("document.title"))
    element = await page.find("CDP Mode")
    await element.click_async()
    await asyncio.sleep(2)
    print(await page.evaluate("document.title"))

if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    asyncio.run(main())
```

If you're unfamiliar with `async` / `await` syntax, here's the same example converted into `sync` format:

```python
import asyncio
import time
from seleniumbase.undetected.cdp_driver import cdp_util

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
host = "127.0.0.1"
port = 9222
driver = loop.run_until_complete(cdp_util.start(host=host, port=port))
page = loop.run_until_complete(driver.get("https://seleniumbase.io/"))
time.sleep(2)
print(loop.run_until_complete(page.evaluate("document.title")))
element = loop.run_until_complete(page.find("CDP Mode"))
loop.run_until_complete(element.click_async())
time.sleep(2)
print(loop.run_until_complete(page.evaluate("document.title")))
```

Those examples use pure CDP:
* **[24. CDP driver (async/await API. No Selenium)](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_24)**
* **[25. CDP driver (SB-CDP sync API. No Selenium)](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_25)**

Note that you'll get errors running those examples if there's no active Chrome instance with the debug `port` you selected.
For regular SB CDP Mode, new Chrome instances will first attempt to use debug port `9222` if not already taken.

**Comment by zbximo** [comment]
if i use remote-debugging, how can i using uc_gui_click_captcha ?

**Comment by mdmintz** [comment]
@zbximo, from the simplified sb_cdp format, you would have to use `sb.gui_click_element(selector)` to click the CAPTCHA, where the `selector` is the element directly above the `Shadow-root`.

**Comment by zbximo** [comment]
Thank you. 
Is there any way to encapsulate the above driver、page into a SeleniumBase object and directly use it's functions in base_case.py , such as uc_gui_click_captcha, accept_alert and so on?

**Comment by mdmintz** [comment]
@zbximo They are two different types of objects: There's a CDP Driver object, and there's a WebDriver object. If you want the SeleniumBase BaseCase functionality, you'll need to spin up the browser directly.
