### ISSUE TITLE
does SeleniumBase provide a method similar to getTargets()?

### ISSUE THREAD

**Issue by quyunet** [seleniumbase/SeleniumBase#3356]
does SeleniumBase provide a method similar to getTargets()?
https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/devtools/idealized/target/Target.html#getTargets()

**Comment by mdmintz** [comment]
It does. There's an internal method used by "CDP Mode":
https://github.com/seleniumbase/SeleniumBase/blob/ffeee7f34e99236bad0b83da3c89ae2c3ea9ec0e/seleniumbase/undetected/cdp_driver/browser.py#L504

That method indirectly calls `get_targets()` from `MyCDP`:
https://github.com/mdmintz/MyCDP/blob/e379a7f29ffc414c6966194719d83e787cac0724/mycdp/target.py#L459

Regular Python Selenium also uses it for some things:
https://github.com/SeleniumHQ/selenium/blob/c0b45ad714fb954a529aa10c0a83908b68fcf4b4/py/selenium/webdriver/remote/webdriver.py#L1108

It's `async`-only, so unless you're using [SeleniumBase's async API](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_24), you probably won't be calling it directly.
