### ISSUE TITLE
self.get_cookies() error

### ISSUE THREAD

**Issue by zxczxcdev** [seleniumbase/SeleniumBase#3358]
cookies = self.get_cookies()
              ^^^^^^^^^^^^^^^^
Exception: 'MyTestClass' object has no attribute 'get_cookies'

i want to get cookie from request header

**Comment by zxczxcdev** [comment]
like this 
![image](https://github.com/user-attachments/assets/5c280bb0-65a4-4f06-97c1-764f95538371)

**Comment by zxczxcdev** [comment]
like this 
![image](https://github.com/user-attachments/assets/0d546e74-998c-427a-8bf4-a946e29ab30e)

**Comment by SSujitX** [comment]
> ```
> cookies = self.get_cookies()
>           ^^^^^^^^^^^^^^^^
> ```
> 
> Exception: 'MyTestClass' object has no attribute 'get_cookies'
> 
> i want to get cookie from request header

Share code?

**Comment by zxczxcdev** [comment]
class MyTestClass(BaseCase):
 def test_swag_labs(self):
   self.open("https://www.google.com")
   self.get_cookies()

**Comment by zxczxcdev** [comment]
> > ```
> > cookies = self.get_cookies()
> >           ^^^^^^^^^^^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Exception: 'MyTestClass' object has no attribute 'get_cookies'
> > i want to get cookie from request header
> 
> Share code?

```
class MyTestClass(BaseCase):
 def test_swag_labs(self):
   self.open("https://www.google.com")
   self.get_cookies()
```

**Comment by zxczxcdev** [comment]
solved
