### ISSUE TITLE
Is there any way to interfere with global variables from Class BaseCase?

### ISSUE THREAD

**Issue by zxczxcdev** [seleniumbase/SeleniumBase#3360]
Like title , My code : 
```
good_count = 0
bad_count = 0


class MyTestClass(BaseCase):        
    def test_swag_labs(self):
        global good_count, bad_count
        try:
            #something here
            
            while True:
                if True:
                    good_count += 1
                    break
                elif False:
                    bad_count += 1
                    break
        finally:
            pass
        

if __name__ == "__main__":
    while True:
        BaseCase.main(__name__, __file__)
        print(good_count, bad_count)

```
 print(good_count, bad_count) >>> good = 0 bad = 0 
Please help me. Thank you!

**Comment by mdmintz** [comment]
That's more of a general Python question about `global` variables:
https://stackoverflow.com/a/423596/7058266
(Add `global` before the variable when using it inside functions.)

**Comment by zxczxcdev** [comment]
> class MyTestClass(BaseCase):        
>     def test_swag_labs(self):
>         global good_count, bad_count

i used 
```
class MyTestClass(BaseCase):        
    def test_swag_labs(self):
        global good_count, bad_count
```
 so is that true ?

**Comment by mdmintz** [comment]
According to [the StackOverflow post](https://stackoverflow.com/a/423596/7058266), the global variable was first set before the function, and then set with the `global` keyword in the function:

```python
globvar = 0

def set_globvar_to_one():
    global globvar    # Needed to modify global copy of globvar
    globvar = 1

def print_globvar():
    print(globvar)     # No need for global declaration to read value of globvar

set_globvar_to_one()
print_globvar()       # Prints 1
```

**Comment by zxczxcdev** [comment]
> al variable was first set bef



> According to [the StackOverflow post](https://stackoverflow.com/a/423596/7058266), the global variable was first set before the function, and then set with the `global` keyword in the function:
> 
> ```python
> globvar = 0
> 
> def set_globvar_to_one():
>     global globvar    # Needed to modify global copy of globvar
>     globvar = 1
> 
> def print_globvar():
>     print(globvar)     # No need for global declaration to read value of globvar
> 
> set_globvar_to_one()
> print_globvar()       # Prints 1
> ```

I think I actually did that. Please review my code in #1

```
**good_count = 0 <<< the global variable was first set before the function,
bad_count = 0 <<< the global variable was first set before the function,**


class MyTestClass(BaseCase):        
    def test_swag_labs(self):
        **global good_count, bad_count**
        try:
            #something here
            
            while True:
                if True:
                    good_count += 1
                    break
                elif False:
                    bad_count += 1
                    break
        finally:
            pass
```

**Comment by mdmintz** [comment]
Check the [Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md). You're using a `pytest` structure. `pytest` handles global variables differently. If you're going to be using a `pytest` structure, see https://github.com/pytest-dev/pytest/issues/3403#issuecomment-526554447 for handling global variables passed between tests.

You can avoid that by using [Syntax Format 23: SeleniumBase SB (Python context manager)](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_21) so that you're using pure Python format, rather than `pytest`.
