### ISSUE TITLE
Download file in UC mode, don't use requests module

### ISSUE THREAD

**Issue by quickdraw6906** [seleniumbase/SeleniumBase#3366]
I can load a page served by Akamai in UC mode, grab a link to a PDF (external_pdf=None, but tried both ways) and then call sb.save_file_as() but that merely uses requests which then gets blocked by Akamai.

**Comment by quickdraw6906** [comment]
Also tried opening the PDF (in a tab) and getting page source, but that just gets the HTML including the embed tag.

**Comment by SSujitX** [comment]
> I can load a page served by Akamai in UC mode, grab a link to a PDF (external_pdf=None, but tried both ways) and then call sb.save_file_as() but that merely uses requests which then gets blocked by Akamai.

Can you share the website or code? Without trying, we can not solve your issue.

**Comment by quickdraw6906** [comment]
Crawling this:
https://www.sedonaaz.gov/your-government/departments/city-clerk/council-commissions-committees-boards/city-council/meetings-agendas-packets-minutes/-folder-5854
to get PDF links. Here is the first link:
https://www.sedonaaz.gov/home/showpublisheddocument/53201/638699521242170000

Here is the full code:
`
from urllib.parse import urlsplit

from bs4 import BeautifulSoup
from seleniumbase import SB

def scrape_pdfs(url, download_dir):
    with SB(uc=True, headless=False, external_pdf=None, block_images=True) as sb:
        pdf_objects = []

        sb.open(url)
        soup = BeautifulSoup(sb.get_page_source(), "html.parser")

        for link in soup.find_all("a", href=True):
            if link["href"].endswith(".pdf") or "publisheddocument" in link["href"]: # Granicus creates URL"s with "publisheddocument" not pdf
                file_name = link.text.replace(" - ", "-")
                file_name = file_name.replace(" ", "~") + link["href"].split("/")[-1]
                if not file_name.endswith(".pdf"):
                    file_name = file_name + ".pdf"
                split_url = urlsplit(url)
                target_url = link["href"]
                if link["href"].startswith("/"):
                    target_url = split_url.scheme + "://" + split_url.netloc + link["href"]  
                    
                pdf_object = {
                    "protocol": split_url.scheme,
                    "domain": split_url.netloc,
                    "href": target_url,
                    "text": link.text,
                    "file_name": file_name
                }
                pdf_objects.append(pdf_object)

        for pdf_object in pdf_objects:
            sb.save_file_as(pdf_object["href"], pdf_object["file_name"], download_dir)
            download_filepath = f"{download_dir}/{pdf_object["file_name"]}"
            sb.assert_downloaded_file(download_filepath)        
            print(f"Downloaded {pdf_object["file_name"]}")

if __name__ == "__main__":
    url = "https://www.sedonaaz.gov/your-government/meetings-documents/-folder-5854"
    scrape_pdfs(url, "/Users/sean/Downloads/pdf_scraper")  
`

**Comment by SSujitX** [comment]
> Crawling this: https://www.sedonaaz.gov/your-government/departments/city-clerk/council-commissions-committees-boards/city-council/meetings-agendas-packets-minutes/-folder-5854 to get PDF links. Here is the first link: https://www.sedonaaz.gov/home/showpublisheddocument/53201/638699521242170000
> 
> Here is the full code:
> 
> ```
> from urllib.parse import urlsplit
> 
> from bs4 import BeautifulSoup
> from seleniumbase import SB
> 
> def scrape_pdfs(url, download_dir):
>     with SB(uc=True, headless=False, external_pdf=None, block_images=True) as sb:
>         pdf_objects = []
> 
>         sb.open(url)
>         soup = BeautifulSoup(sb.get_page_source(), "html.parser")
> 
>         for link in soup.find_all("a", href=True):
>             if link["href"].endswith(".pdf") or "publisheddocument" in link["href"]: # Granicus creates URL"s with "publisheddocument" not pdf
>                 file_name = link.text.replace(" - ", "-")
>                 file_name = file_name.replace(" ", "~") + link["href"].split("/")[-1]
>                 if not file_name.endswith(".pdf"):
>                     file_name = file_name + ".pdf"
>                 split_url = urlsplit(url)
>                 target_url = link["href"]
>                 if link["href"].startswith("/"):
>                     target_url = split_url.scheme + "://" + split_url.netloc + link["href"]  
>                     
>                 pdf_object = {
>                     "protocol": split_url.scheme,
>                     "domain": split_url.netloc,
>                     "href": target_url,
>                     "text": link.text,
>                     "file_name": file_name
>                 }
>                 pdf_objects.append(pdf_object)
> 
>         for pdf_object in pdf_objects:
>             sb.save_file_as(pdf_object["href"], pdf_object["file_name"], download_dir)
>             download_filepath = f"{download_dir}/{pdf_object["file_name"]}"
>             sb.assert_downloaded_file(download_filepath)        
>             print(f"Downloaded {pdf_object["file_name"]}")
> 
> if __name__ == "__main__":
>     url = "https://www.sedonaaz.gov/your-government/meetings-documents/-folder-5854"
>     scrape_pdfs(url, "/Users/sean/Downloads/pdf_scraper")  
> ```

`pip install curl_cffi`

```from curl_cffi import requests
from seleniumbase import SB
import os


def download_pdf_file(
    url,
    filename,
    download_dir,
    user_agent,
    cookies=None,
):
    headers = {
        "user-agent": user_agent
        or "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    }

    cookies_dict = (
        {cookie["name"]: cookie["value"] for cookie in cookies} if cookies else None
    )

    response = requests.get(url, headers=headers, cookies=cookies_dict)
    filename_ext = os.path.join(download_dir, filename)
    if response.status_code == 200:
        os.makedirs(download_dir, exist_ok=True)  # Ensure the directory exists
        with open(filename_ext, "wb") as f:
            f.write(response.content)
        print(f">= PDF {filename_ext} downloaded successfully!")
    else:
        print(f">= Failed to download {filename_ext} from {url}.")


def scrape_pdfs(url, download_dir):
    with SB(uc=True, block_images=True) as sb:
        sb.activate_cdp_mode(url)
        sb.wait_for_ready_state_complete(timeout=120)
        sb.sleep(5)

        elements = sb.find_elements('li > a[class="content_link"]')
        if not elements:
            print(">= No PDF links found")
            return

        for element in elements:
            headers = sb.get_user_agent()
            cookies = sb.get_cookies()

            target_url = element.get_attribute("href")
            file_name = element.text.replace(" - ", "-").replace(" ", "~") + ".pdf"

            print(f">= Downloading {file_name}")
            download_pdf_file(target_url, file_name, download_dir, headers, cookies)


if __name__ == "__main__":
    url = "https://www.sedonaaz.gov/your-government/meetings-documents/-folder-5854"
    import sys

    root_path = os.path.dirname(os.path.abspath(sys.argv[0]))
    os.chdir(root_path)

    download_folder = os.path.join(root_path, "downloads")
    os.makedirs(download_folder, exist_ok=True)

    scrape_pdfs(url, download_folder)```

**Comment by SSujitX** [comment]
> Crawling this: https://www.sedonaaz.gov/your-government/departments/city-clerk/council-commissions-committees-boards/city-council/meetings-agendas-packets-minutes/-folder-5854 to get PDF links. Here is the first link: https://www.sedonaaz.gov/home/showpublisheddocument/53201/638699521242170000

As a professional automation expert/scraper. Here is the solution.

Always use updated libraries.

```sh
pip install curl_cffi -U
```
```sh
pip install seleniumbase -U
```

```python
from curl_cffi import requests
from seleniumbase import SB
import os


def download_pdf_file(
    url,
    filename,
    download_dir,
    user_agent,
    cookies=None,
):
    headers = {
        "user-agent": user_agent
        or "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    }

    cookies_dict = (
        {cookie["name"]: cookie["value"] for cookie in cookies} if cookies else None
    )

    response = requests.get(url, headers=headers, cookies=cookies_dict)
    filename_ext = os.path.join(download_dir, filename)
    if response.status_code == 200:
        with open(filename_ext, "wb") as f:
            f.write(response.content)
        print(f">= PDF {filename_ext} downloaded successfully!")
    else:
        print(f">= Failed to download {filename_ext} from {url}.")


def scrape_pdfs(url, download_dir):
    with SB(uc=True, block_images=True) as sb:
        sb.activate_cdp_mode(url)
        sb.wait_for_ready_state_complete(timeout=120)
        sb.sleep(5)

        elements = sb.find_elements('li > a[class="content_link"]')
        if not elements:
            print(">= No PDF links found")
            return

        for element in elements:
            headers = sb.get_user_agent()
            cookies = sb.get_cookies()

            target_url = element.get_attribute("href")
            file_name = element.text.replace(" - ", "-").replace(" ", "~") + ".pdf"

            print(f">= Downloading {file_name}")
            download_pdf_file(target_url, file_name, download_dir, headers, cookies)


if __name__ == "__main__":
    url = "https://www.sedonaaz.gov/your-government/meetings-documents/-folder-5854"
    import sys

    root_path = os.path.dirname(os.path.abspath(sys.argv[0]))
    os.chdir(root_path)

    download_folder = os.path.join(root_path, "downloads")
    os.makedirs(download_folder, exist_ok=True)

    scrape_pdfs(url, download_folder)
```

**Comment by mdmintz** [comment]
Here's the correct setup: (Using [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md))

```python
from seleniumbase import SB

with SB(uc=True, test=True, external_pdf=True) as sb:
    url = "https://www.sedonaaz.gov/your-government/departments/city-clerk/council-commissions-committees-boards/city-council/meetings-agendas-packets-minutes/-folder-5854"
    sb.activate_cdp_mode(url)
    breakpoint()
```

From there, use SeleniumBase to click on the PDF links that you want so that the PDF downloads appear in the `./downloaded_files/` folder.

**Comment by quickdraw6906** [comment]
Thanks much @SSujitX ! Should there be a commit that switches from baked in requests to curl_cffi? @mdmintz I feel the docs should at least mention that UC mode alone doesn't do the trick for downloading files.

**Comment by mdmintz** [comment]
There are Docs: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md
CDP Mode replaces regular UC Mode.

**Comment by quickdraw6906** [comment]
Thanks much @mdmintz. Didn't see any CDP methods for downloading/saving. I didn't make the leap that being in CDP mode for a url then clicking it would initiate a download. From your example code above here I presume external_pdf=True is required to make that work. 

I had tried activate_cdp_mode() then save_file_as() but  `requests` module baked into Python doesn't do http2, etc....

I feel the deficiencies of the `requests` module baked into Python (doesn't do http2, etc.) should be mentioned in the docs for download_file() and save_file_as(). Or, switch to using curl-cffi as the http client. There's a nice table here that shows the deficiencies of using built-in `requests` http client: https://pypi.org/project/curl-cffi/

Thanks again to you and @SSujitX. Happy New Year!

**Comment by mdmintz** [comment]
Yes, external_pdf=True is what you need for clicks on PDF links to automatically download them.
