### ISSUE TITLE
Find shadow element issue

### ISSUE THREAD

**Issue by thienha1** [seleniumbase/SeleniumBase#3368]
I write this script:
```
from seleniumbase import Driver
import time


driver = Driver(uc=True, dark_mode=True)
url = "https://seleniumbase.io/other/shadow_dom"
driver.uc_open_with_reconnect(url, 4)
driver.assert_element("fancy-tabs::shadow #panels")
print("Found")
time.sleep(100)
driver.quit()
```
And I tried a whole interact element like those:
![Opera Snapshot_2024-12-25_200808_seleniumbase io](https://github.com/user-attachments/assets/811a58ca-55b3-451e-aff7-56302ccbed99)
Then none of these can't recognize element inside shadow, dunno why?

**Comment by mdmintz** [comment]
The `Driver()` format is mainly using the raw `Selenium` API (not the `SeleniumBase` one).
If you need the special shadow selectors, switch to the `SB()` format:

```python
from seleniumbase import SB

with SB(uc=True, dark_mode=True) as sb:
    url = "https://seleniumbase.io/other/shadow_dom"
    sb.uc_open_with_reconnect(url, 3)
    sb.assert_element("fancy-tabs::shadow #panels")
    print("Found")
    print(sb.get_text("fancy-tabs::shadow #panels"))
    breakpoint()
```

And when you want to pause the script, use a `breakpoint()`, which you can leave at any time by typing `c` in the console and pressing `Enter` to continue.

**Comment by thienha1** [comment]
> The `Driver()` format is mainly using the raw `Selenium` API (not the `SeleniumBase` one). If you need the special shadow selectors, switch to the `SB()` format:
> 
> ```python
> from seleniumbase import SB
> 
> with SB(uc=True, dark_mode=True) as sb:
>     url = "https://seleniumbase.io/other/shadow_dom"
>     sb.uc_open_with_reconnect(url, 3)
>     sb.assert_element("fancy-tabs::shadow #panels")
>     print("Found")
>     print(sb.get_text("fancy-tabs::shadow #panels"))
>     breakpoint()
> ```
> 
> And when you want to pause the script, use a `breakpoint()`, which you can leave at any time by typing `c` in the console and pressing `Enter` to continue.

I tried get inside iframe from shadow element
```
 with sb.frame_switch("#adsOnPage > div::shadow iframe"):
        sb.assert_element("body::shadow .main-wrapper")
        print("Found")
```
But almost case i tried, all have i got
```
Exception: Frame {#adsOnPage > div::shadow iframe} was not visible after 10 seconds!
```
It seem some function found some function not found!!

**Comment by mdmintz** [comment]
> "I tried get inside iframe from shadow element"

There are no `iframe` elements on https://seleniumbase.io/other/shadow_dom

**Comment by thienha1** [comment]
> > "I tried get inside iframe from shadow element"
> 
> There are no `iframe` elements on https://seleniumbase.io/other/shadow_dom

No, not this site, i tried this example html:
```
<body>
    <macroponent>
        <div>
            <sn-canvas-appshell-root>
                <sn-canvas-appshell-layout id='adsOnPage'>
                    <div>
                         #shadow-root (open) 
                            <iframe id="myIframe"> <!-- to access button I need to find the iframe 1st -->
                                <button id="myButton">TAKE</button> <!-- I need to get that click event -->
                            </iframe>
                    </div>
            </sn-canvas-appshell-root>
            </sn-canvas-appshell-root>
        </div>
    </macroponent> 
</body>
```

**Comment by mdmintz** [comment]
Use `sb.cdp.gui_click_element(selector)` to click inside there, such as with:
https://github.com/seleniumbase/SeleniumBase/blob/35dcd8214325a9b54c1d8ab67eb6f26544c2266c/examples/cdp_mode/raw_planetmc.py#L7

In your case, you would use `sb.cdp.gui_click_element("#adsOnPage div")` from [CDP Mode](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md)
