### ISSUE TITLE
move mouse to the element as mimic human 

### ISSUE THREAD

**Issue by pythondeveloperz** [seleniumbase/SeleniumBase#3376]
hello please i am using this to move mouse by selenium base sb.cdp.gui_hover_x_y(x, y)    but i need to make to the movement to element as human mimic 100% not be detected by google and any other website i am focusing on the behaviour to be the same as human ?

**Comment by SSujitX** [comment]
> hello please i am using this to move mouse by selenium base sb.cdp.gui_hover_x_y(x, y) but i need to make to the movement to element as human mimic 100% not be detected by google and any other website i am focusing on the behaviour to be the same as human ?

Using random library you can add value (x,y) based on coordinates. That will help you to act mouse as human.

**Comment by mdmintz** [comment]
Use https://github.com/asweigart/pyautogui directly to programmatically control the mouse in a specific way.
