### ISSUE TITLE
Make adjustments to better support Zalenium (dockerised selenium scalable grid)

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#339]
A very popular open source grid for scaling distributed interface system tests is, Zalenium:

https://github.com/zalando/zalenium

**The issue:**
When running pytest tests on zalenium, it relies on having particular cookie(s) set on the browser to allow zalenium to know which test passed or failed, you can read about it here:

https://opensource.zalando.com/zalenium/

```
By default, tests in Zalenium are marked in the dashboard either as COMPLETED (session finishes normally) or TIMEOUT (session was ended due to inactivity). You can mark the test as passed or failed based on the assertions you do on your side with your test framework, add a cookie from with the name zaleniumTestPassed with a value of true (if the test passes) or false (if the test fails). This could be done in the after method where you already know if the test passed or failed. Here is an example in Java:
    Cookie cookie = new Cookie("zaleniumTestPassed", "true");
    webDriver.manage().addCookie(cookie);

```

By the time we can determine the pytest success or failure, seleniumbase tearDown() (I think) has destroyed the drivers, hence making it incompatible fully with Zalenium grid.  

This is quite a big feature that SeleniumBase should support, in general having the driver after the test has failed in pytest would be a big win and provide a ton of improved use cases.

**Comment by mdmintz** [comment]
@symonk   There is a way to do it. It requires a few things. One is creating a custom tearDown() method in your test suite that runs before the SeleniumBase one. See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py   . Next, you’ll need to use self.driver.add_cookie() to add the cookie you want in your custom tearDown() method. You’ll also need to know if your test already passed or failed in that tearDown, so you can set a global variable on the last line of your test, which will only be reached if the test has passed. Your custom tearDown will look at that variable to know what to set your cookie to. I’ve used sb_config to pass variables from the pytest_plugin to base_case.

**Comment by mdmintz** [comment]
And as mentioned in Gitter chat, you can detect test failures in tearDown() with:

    has_exception = False
    if sys.version.startswith('3') and hasattr(self, '_outcome'):
        if hasattr(self._outcome, 'errors') and self._outcome.errors:
            has_exception = True
    else:
        has_exception = sys.exc_info()[1] is not None

**Comment by tcw0nw** [comment]
Hope to support zalenium。
