### ISSUE TITLE
Seleniumbase wait_for_alert functions no longer work with chromedriver 76+

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#362]
Recent W3C spec compliance change(s) to chromedriver as of 76+ result in breakages with alerts being instantly dismissed.  Seleniumbase default behaviour should account for these changes.

Recreation is simple:

```
    def test_fix_alerts(self):
        self.open('https://www.seleniumeasy.com/test/javascript-alert-box-demo.html')
        self.click_xpath("//button[@class='btn btn-default'][1]")
        self.wait_for_and_accept_alert()
```

I think this is because as of chromedriver76+ we are now seeing IGNORE AND DISMISS on these alert(s) by default.  No time to investigate for a PR as I am away this weekend, but logging for visibility @mdmintz 

```
selenium==3.141.0
seleniumbase==1.23.9
pytest==4.4.2
```

**Comment by mdmintz** [comment]
In the latest version of SeleniumBase, which is 1.30.0, “seleniumbase install chromedriver” installs chromedriver 2.44, which works fine with the latest version of chrome with no issues. Also, I’m in Europe right now for my honeymoon (currently getting WiFi at Hard Rock Cafe Mallorca), so I won’t be able to ship changes until August 30th. Try the latest SeleniumBase with “seleniumbase install chromedriver”.

**Comment by symonk** [comment]
note: chromedriver 2.44 won't work with chrome 76+ correctly

**Comment by mdmintz** [comment]
What issues did you experience with chromedriver 2.44 on Chrome 76? (I’m traveling through Italy now. Responses will be very delayed.)

**Comment by symonk** [comment]
I guess its not just ideal to be out of date, that said it seems to hold up ok :) 

ChromeDriver 2.46
Supports Chrome v71-73

**Comment by mdmintz** [comment]
If the Chrome team ships a faulty chromedriver, that’s out of my control. I made it work by using an earlier one with the latest Chrome. Auto-accepting alerts leads to unexpected behavior. If a test needs to check that the alert appeared, the alert shouldn’t be auto-accepted or auto-dismissed.

**Comment by symonk** [comment]
I don't think its necessarily faulty; just W3C more-so compliant which will be the case going forward

**Comment by mdmintz** [comment]
@symonk Try seleniumbase 1.31.0 . I made fixes that should have fixed your issue. https://github.com/seleniumbase/SeleniumBase/pull/364

**Comment by mdmintz** [comment]
And SeleniumBase v1.31.1 fixes another big issue with maximizing windows. Upgrade to that.

**Comment by mdmintz** [comment]
I'm closing this issue as resolved. Please upgrade to the latest version of SeleniumBase (which is currently 1.31.2). Then make sure you have the latest version of chromedriver: ``seleniumbase install chromedriver latest``.

**Comment by mdmintz** [comment]
Everything should be all good by now if you upgrade to the latest version.
