### ISSUE TITLE
AttributeError: 'BaseTest' object has no attribute 'assert_no_404_errors'

### ISSUE THREAD

**Issue by frafra** [seleniumbase/SeleniumBase#386]
I wrote a very simple test today and I got this error:

`AttributeError: 'BaseTest' object has no attribute 'assert_no_404_errors'`

Here is the script:

```python
from seleniumbase import BaseCase
class BaseTest(BaseCase):
    def test_http_errors(self):
        self.open("http://localhost:8000")
        self.assert_no_404_errors()
```

```
selenium==3.141.0
seleniumbase==1.19.6
```

Other functions, like `self.assert_no_js_errors` work as usual.

**Comment by mdmintz** [comment]
@frafra That functionality was added in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.22.0 (Automated Visual Testing - 1.22.0) You are using 1.19.6

**Comment by frafra** [comment]
Thank you very much :)
