### ISSUE TITLE
怎么分布式执行

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#391]
大神，您好，打算在项目中投入使用，请问下这个是否有分布式执行的方案呢？

**Comment by mdmintz** [comment]
Hello @meilisong1 , you can install seleniumbase with pip for easier distribution from your projects. Place seleniumbase in a requirements file or in a setup.py file.

**Comment by meilisong1** [comment]
> Hello @meilisong1 , you can install seleniumbase with pip for easier distribution from your projects. Place seleniumbase in a requirements file or in a setup.py file.

thank you
