### ISSUE TITLE
js = '$(".bdpfmenu")[0].style.display="block"' 		self.execute_async_script(js)

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#393]
E       selenium.common.exceptions.JavascriptException: Message: Cannot r
perty 'style' of undefined
E       JavaScript stack:
E       TypeError: Cannot read property 'style' of undefined

**Comment by mdmintz** [comment]
Since the result is the same when using ``self.driver.execute_async_script(js)``, which calls the WebDriver method directly, I would double check your usage of that.
