### ISSUE TITLE
Hello, I would like to ask if there is any way to get the full path of screenshot？

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#403]
I would like to combine with the screenshots of allure report, is there any way to get the full path of screenshots, as follows:

D: \ workspace \ wpsjweb\ latest_logs\ test_plus_allure TestCaseClass. Test_login \ screenshot PNG

**Comment by mdmintz** [comment]
You can probably use os.getcwd() to get the current working directory. Then the latest_logs/ folder will be in there. To get the full path to the screenshot, you’ll need to use Python to extract the names of the test file, the test class, and the test method, per test.

**Comment by meilisong1** [comment]
screen_out_path = os.path.abspath(os.path.join(os.path.dirname(__file__))) + os.sep + 'latest_logs\\'
		file_name = rep.nodeid.split("/")[-1].replace(".py", "").replace("::", ".") + "\screenshot.png"
		if os.path.exists(screen_out_path + file_name):
			with open(screen_out_path + file_name, mode='rb') as f:
				file = f.read()
				allure.MASTER_HELPER.step("失败截图")
				allure.MASTER_HELPER.attach('screenshot.png', file, allure.MASTER_HELPER.attach_type.PNG)


I combined with allure report has been achieved, thank you for your answer
It's a great frame to use
