### ISSUE TITLE
Executing scripts doesn't work. The console does. Weird

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#405]
self.open('https://www.baidu.com/')
		# 输入
		self.update_text("#kw", "apple\n")
		# 断言有出现文本
		self.assert_text_visible("(中国) - 官方网站")
		self.add_text("#kw", "234")
	
		scripts = "document.getElementsByClassName('bdpfmenu')[0].style.display='block'"
		# scripts = "document.getElementById('su').click();"
		self.execute_script(scripts)

**Comment by mdmintz** [comment]
It looks like you may be using incorrect syntax for what you’re trying to do. See the ReadMe, where you’ll find multiple examples with “execute_script” if you search for it. You’ll be able to perform actions on elements with jQuery. In most cases, you’ll be able to use built-in SeleniumBase methods.

**Comment by meilisong1** [comment]
> It looks like you may be using incorrect syntax for what you’re trying to do. See the ReadMe, where you’ll find multiple examples with “execute_script” if you search for it. You’ll be able to perform actions on elements with jQuery. In most cases, you’ll be able to use built-in SeleniumBase methods.

Ok, I'll try
