### ISSUE TITLE
The API for moving elements doesn't seem to exist. This is the most basic operation

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#406]
example:
Actions action =new Actions(driver);
WebElement gaikuang=driver.findElement(by(bytype, object));
action.moveToElement(gaikuang).click().perform();

**Comment by mdmintz** [comment]
Use the SeleniumBase scroll_to(Selector) method for scrolling to elements. It’s already included when using the SeleniumBase click(Selector) method. If you’re using “driver” in your code, it means you’re not using SeleniumBase methods because your jumping directly to the raw webdriver library.
