### ISSUE TITLE
recommended to add the get_elements function to get all the element sets

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#408]
Hello, sometimes when examining UI elements, you need to get a collection of multiple elements to make assertions. It is recommended to add the get_elements function to get all the element sets

**Comment by mdmintz** [comment]
``self.find_elements(SELECTOR)``
``self.find_visible_elements(SELECTOR)``
See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md for all methods.

**Comment by meilisong1** [comment]
> `self.find_elements(SELECTOR)`
> `self.find_visible_elements(SELECTOR)`
> See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/method_summary.md for all methods.

thx

**Comment by PankajSavaliya** [comment]
@mdmintz I have used this `self.find_elements(SELECTOR)` method and then i want to`uc_click()` one of them element. so how to click without detecting a bot?
