### ISSUE TITLE
Switch_to_frame_of_element switch encountered problems?

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#414]
<div data-v-70f44a90="" class="todo-iframe">
    <iframe data-v-70f44a90="" src="https://xxx/app/334837844" width="100%" height="100%" 
    frameborder="0">
    </iframe>
</div>

Unable to switch:
self.switch_to_frame_of_element("//iframe[contains(@src,'334837844')]", by=By.XPATH)

I can use the native API:
e = self.find_element("//iframe[contains(@src,'334837844')]")
self.driver.switch_to_frame(e)    --ok

self.switch_to_frame(0)   --ok
self.switch_to_default_content()

**Comment by mdmintz** [comment]
Hi @meilisong1, your call to self.switch_to_frame_of_element() is incorrect. The argument should be the selector of an element inside the iframe that you're trying to switch into, not the iframe itself. For what you're passing, you should use self.switch_to_frame(), as you did in your later examples.
