### ISSUE TITLE
how to get the element value

### ISSUE THREAD

**Issue by cx4** [seleniumbase/SeleniumBase#417]
If I use it as a crawler, how to get the text or value of an element
`
a = self.get_text('css selector')
`
`print(a)`

But it doesn't work

**Comment by mdmintz** [comment]
@cx4 What do you see when you run that? Is it finding the selector? Are you running without a pytest.ini file at the base of your repo? The pytest.ini file includes “--capture=no”, which prints console output to the screen. Without that, you may need need to add “-s” as an arg when running with pytest.

**Comment by mdmintz** [comment]
It’s been 2 days without a response to my response, so I’m going to assume that my above answer was sufficient for you.
