### ISSUE TITLE
Strangely enough, one click works, double click fails

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#419]
self.double_click(self.TeamPage.folder_first_btn)  --failed

self.click(self.TeamPage.folder_first_btn) --ok

To quote the following wrong:

Message: (Session info: chrome=77.0.3865.120)

**Comment by mdmintz** [comment]
If you're using the latest version of chrome, upgrade your chromedriver.
```bash
seleniumbase install chromedriver latest
```

I tried the following example and it worked for me:
```python
from seleniumbase import BaseCase

class MyTestClass(BaseCase):
    def test_double_click(self):
        self.open("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_ondblclick")
        self.click('[onclick="submitTryit(1);"]')
        self.switch_to_frame('iframeResult')                                        
        self.double_click('[ondblclick="myFunction()"]')
        self.assert_text('Hello World', '#demo')
```

**Comment by meilisong1** [comment]
> ```shell
> seleniumbase install chromedriver latest
> ```
The browser won't work after the upgrade

**Comment by mdmintz** [comment]
See which version of Chrome you have installed. Then swap in the version in place of “latest”. Unless you upgrade your version of Chrome to the latest to match your webdriver.

**Comment by mdmintz** [comment]
Here's the double_click test that works for me: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_double_click.py

**Comment by meilisong1** [comment]
> Here's the double_click test that works for me: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_double_click.py
I'm trying. Thank you
