### ISSUE TITLE
How can I get the log output from the console

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#422]
Sometimes, some functions need to be coordinated with the development to realize the verification of functions. At this time, it is necessary to develop and print some logs in the console, and then I will get them

self.open("file:///C:/Users/Administrator/Desktop/test.html")
			self.click("#copy")
			print(self.driver.get_log("browser")) 

The console output log is not available in this manner

test.html:

<script>

console.log("start,..");

function copyText()
{
document.getElementById("field2").value=document.getElementById("field1").value;
console.log("hello world");
console.log("hello world2");
console.log("hello world3");
}
</script>
</head>
<body>

Field1: <input type="text" id="field1" value="Hello World!"><br>
Field2: <input type="text" id="field2"><br><br>

<button onclick="copyText()" id="copy">复制文本</button>

**Comment by mdmintz** [comment]
Two things:
1) You may need Chrome or a Chromium-based browser for ``self.driver.get_log('browser')`` to give you output.
2) You may need to add ``-s`` when running tests with pytest for the console output to be seen, unless you're using the pytest.ini file that comes with SeleniumBase.

**Comment by meilisong1** [comment]
> 1. self.driver.get_log('browser')

self.driver.get_log('browser')   Can't get, also don't know is why

**Comment by mdmintz** [comment]
Did you try printing it?
``print(self.driver.get_log('browser'))``
Are you using Chrome or a different browser?
Did you add ``-s`` to your pytest command args?

**Comment by meilisong1** [comment]
> Did you try printing it?
> `print(self.driver.get_log('browser'))`
> Are you using Chrome or a different browser?
> Did you add `-s` to your pytest command args?

I've now switched to a method that requires the front end to inject a function, and then I call the function, and that's it. Thank you

**Comment by devnowcommit** [comment]
I've googled it and in pure Selenium they say to do this: 
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# enable browser logging
d = DesiredCapabilities.CHROME
d['loggingPrefs'] = { 'browser':'ALL' }
driver = webdriver.Chrome(desired_capabilities=d)

# load the desired webpage
driver.get('http://foo.com')

# print messages
for entry in driver.get_log('browser'):
    print(entry)

What do you think? Is there any chance we can do the same in SBase? 

Thank you very much, I love the layers of abstraction of this project! Keep it up!

**Comment by mdmintz** [comment]
Here's an example test for getting the output of console logs: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_console_logging.py
