### ISSUE TITLE
关于，BaseCase类，所有方法增加，element参数。

### ISSUE THREAD

**Issue by Likangkang08** [seleniumbase/SeleniumBase#428]
您好，我是一个测试工程师，一直在使用您的框架，目前测试的项目，ui使用的是iView，所有会遇到这些问题：
![image](https://user-images.githubusercontent.com/22090651/69497248-c27e2c00-0f15-11ea-9c30-35b4b4d2d4bb.png)
一个class,对应很多元素，如果使用 self.find_elements(".ivu-btn.ivu-btn-primary")，然后从列表取出元素的时候，将不能使用。self.update_text()之类的方法，因为这些方法只支持，selector、by=By.CSS_SELECTOR，请问，self.update_text(),等方法，可以加上，element这个参数吗？

**Comment by Likangkang08** [comment]
![image](https://user-images.githubusercontent.com/22090651/69497418-ca3ed000-0f17-11ea-9927-fe07f2e70ae6.png)

例如这样，使用self.find_elements()，寻找到element之后，直接传入给方法调用。

**Comment by mdmintz** [comment]
Hi @Likangkang08, the ``self.submit()`` method performs the same action as adding ``\n`` to the end of text after calling ``self.update_text(SELECTOR, TEXT)``. If you're already using that, you probably won't need the "submit()". For the SELECTOR, you can use either CSS or XPath. And make sure to use a unique selector if elements share a similar selector.
Also, please ask in English next time. (Translation software isn't perfect, and I had difficulty understanding your specific question.)

**Comment by Likangkang08** [comment]
dear @mdmintz 
my question：
![ManyElements](https://user-images.githubusercontent.com/22090651/69543516-bf904380-0fc8-11ea-91ea-7bbb9a8c7c88.png)
When a 'css' has a lot of tags to use, I just want to click on the third, or the first one. The method in the 'Base Case' class can only select the first element,You can add this judgment to the method in 'BaseCase'. When there are multiple elements.
for example：
    def click(self, selector,number,by=By.CSS_SELECTOR, timeout=None, delay=0):
        elements = self.find_elements("mjs-card-header")
	elements[number].click()
I don’t know what’s wrong with translation，I hope you can understand, thank you.

**Comment by mdmintz** [comment]
Hi @Likangkang08 You can use the ``:nth-child(3)`` CSS to specify the 3rd element, so in your case, you can use ``div.mjs-card-header:nth-child(3)``.
In the example you had with ``find_elements()``, you were missing the ``.``:
You said ``mjs-card-header``,
but you needed ``.mjs-card-header`` because it's a classname.

**Comment by Likangkang08** [comment]
dear @mdmintz，

In fact, these elements are not parent relationships, as shown in the figure: these classes have different ‘div’’s.
![WebPage Structure](https://user-images.githubusercontent.com/22090651/69552633-bfe50a80-0fd9-11ea-8440-b689b8e6c30f.png)
![classname](https://user-images.githubusercontent.com/22090651/69552642-c4a9be80-0fd9-11ea-85ac-a474321f6a4b.png)
If you use class positioning, There are no id, name, and other attributes in the tag, and almost all tags are exactly the same.you can only use absolute positioning, but the absolute positioning is too long, for example: ‘#tableContent > div:nth-child(1) > div:nth-child(2) > div > div > div.mjs-card-header‘ ，“#tableContent > div:nth-child(1) > div:nth-child(2) > div > div > div.mjs-card-header”
So, I can only find all the elements first, then click.
![image](https://user-images.githubusercontent.com/22090651/69554008-12bfc180-0fdc-11ea-8e3e-ab2bcb18ceb1.png)

**Comment by Likangkang08** [comment]
Modify the method in ‘BaseCase’ to this：
<img width="793" alt="LikeThis" src="https://user-images.githubusercontent.com/22090651/69558710-a6e15700-0fe3-11ea-8a09-3464f0a0691d.png">

**Comment by mdmintz** [comment]
@Likangkang08 See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.33.6 (Just released)

``click_nth_visible_element(selector, number, by=By.CSS_SELECTOR)``
```
Finds all matching page elements and clicks the nth visible one.
Example:
self.click_nth_visible_element('[type="checkbox"]', 5)
(Clicks the 5th visible checkbox on the page.)
```

**Comment by Likangkang08** [comment]
thank you for your help！

**Comment by mdmintz** [comment]
@Likangkang08 If you haven't seen it yet, there's now a Chinese translation for SeleniumBase: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/translations/chinese_test_1.py
```python
from seleniumbase.translate.chinese import 硒测试用例  # noqa

class 我的测试类(硒测试用例):

    def test_例子1(self):
        self.开启网址("https://xkcd.in/comic?lg=cn&id=353")
        self.断言标题("Python - XKCD中文站")
        self.断言元素("#content div.comic-body")
        self.断言文本("上漫画")
        self.单击("div.nextLink")
        self.断言文本("老妈的逆袭", "#content h1")
        self.单击链接文本("下一篇")
        self.断言文本("敲桌子", "#content h1")
        self.断言文本("有时候无聊就是最棒的乐趣")
        self.回去()
        self.单击链接文本("兰德尔·门罗")
        self.断言文本("兰德尔·门罗", "#firstHeading")
        self.更新文本("#searchInput", "程式设计")
        self.单击("#searchButton")
        self.断言文本("程序设计", "#firstHeading")
```
(It's in the latest version of SeleniumBase)
