### ISSUE TITLE
Multiple --data command line arguments

### ISSUE THREAD

**Issue by molinacarlos** [seleniumbase/SeleniumBase#448]
Greetings !

Is there a way to "pass" 3 custom command line arguments to a test case?
Right now, I'm building a complex test case, and sometimes I need to pass multiple custom command line arguments. I know that --data=DATA exists, but I need to pass --data multiple times on same invocations

Thanks a lot for this great framework :-)

**Comment by mdmintz** [comment]
Hi @molinacarlos , when passing data with ``--data``, you can pass a comma-separated string, then use Python String parsing to get the data you want from each component you want.
Example:
On command line: ``... --data="string1,string2,string3"``
In tests:
``params = self.data.split(“,”)``
Then you get ``params[0]`` , ``params[1]`` , etc.

**Comment by molinacarlos** [comment]
Thanks a lot mdmintz :-)

**Comment by mdmintz** [comment]
@molinacarlos I decided to add more anyway. Here are the additions in the latest SeleniumBase:
```bash
    --data=DATA  (Extra data to pass to tests. Use "self.data" in tests.)
    --var1=DATA  (Extra data to pass to tests. Use "self.var1" in tests.)
    --var2=DATA  (Extra data to pass to tests. Use "self.var2" in tests.)
    --var3=DATA  (Extra data to pass to tests. Use "self.var3" in tests.)
```
