### ISSUE TITLE
May I use it together with selniumgrid

### ISSUE THREAD

**Issue by meilisong1** [seleniumbase/SeleniumBase#456]
With the increase of cases, a single machine can't meet the daily version iteration speed, so it needs to be executed in parallel by multiple machines. There is no good method at present, so I don't know whether seleniumgrid can be used

**Comment by piotrkochan** [comment]
It can be used with selenium grid, You need to use SeleniumBase this way:

```
pytest examples/my_first_test.py --server=your_seleniumgrid_server.com --port=4444 --cap-file=cap_selenoid.py

**Comment by meilisong1** [comment]
> It can be used with selenium grid, You need to use SeleniumBase this way:
> 
> ```
> pytest examples/my_first_test.py --server=your_seleniumgrid_server.com --port=4444 --cap-file=cap_selenoid.py 
> ```
In this case, I can only execute on one node at a time. If I want to allocate all cases to different nodes at the same time to improve efficiency, what should I do?

For example, if I have 500 cases, I want 250 per node to execute concurrently

**Comment by piotrkochan** [comment]
You should read documentation
```
-n=NUM  # Multithread the tests using that many threads. (Speed up test runs!)

**Comment by meilisong1** [comment]
> You should read documentation
> 
> ```
> -n=NUM  # Multithread the tests using that many threads. (Speed up test runs!)
> ```
Thank you. Could you give me a practical example? My foundation is not very good

**Comment by mdmintz** [comment]
@meilisong1 Add ``-n=NUM`` to the code where you run pytest with SeleniumBase against your Selenium Grid Server.
Example:
```
pytest TEST_SUITE --server=IP_OR_URL_OF_GRID_SERVER --port=PORT -n=NUM
```
@piotrkochan Already mentioned this.

**Comment by piotrkochan** [comment]
> -n I know, I'm using the pytest framework but this is multiple threads on the same node, and I want to run on different nodes at the same time

If you define selenium grid by `--server` then tests will run on the grid. You just should try and see how it works.

**Comment by mdmintz** [comment]
I'll call this one done. See the ReadMe files for more information. Everything is covered there.

**Comment by meilisong1** [comment]
> I'll call this one done. See the ReadMe files for more information. Everything is covered there.

It's done. Thank you
