### ISSUE TITLE
pytest: error: unrecognized arguments: --mobile

### ISSUE THREAD

**Issue by lgrytdwtla** [seleniumbase/SeleniumBase#457]
I am studying the examples, when i tried to run the command "pytest test_swag_labs.py --mobile" on command line,i got an error:
![image](https://user-images.githubusercontent.com/15101455/71576222-db888700-2b2a-11ea-9267-d4406990cc30.png)
but i run this file with "--mobile" parameter in pycharm,it can run normally.why is this?please help me.
![image](https://user-images.githubusercontent.com/15101455/71576307-2aceb780-2b2b-11ea-8985-ba4accbda2e6.png)

**Comment by mdmintz** [comment]
@lgrytdwtla What version of SeleniumBase are you using? That functionality was added in v1.34.0 https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.34.0

**Comment by lgrytdwtla** [comment]
My seleniumbase is v1.32.21,it works fine in v1.34.0,thank you very much.
