### ISSUE TITLE
Nested cap_file options don't work

### ISSUE THREAD

**Issue by piotrkochan** [seleniumbase/SeleniumBase#458]
my_cap.py:
```
desired_cap = {
    "browserName": "opera",
    "version": "46.0",
    "enableVNC": True,
    "enableVideo": False,
    "operaOptions": {"binary": "/usr/bin/opera"}
}
```
`capabilities_parser.py` produces:

```
{'browserName': 'opera', 'version': '46.0', 'enableVNC': True, 'enableVideo': False, 'operaOptions": {"binary': '/usr/bin/opera'} <- note missing } at the end
```
Other way:
```
desired_cap = {
    "browserName": "opera",
    "version": "46.0",
    "enableVNC": True,
    "enableVideo": False,
    "operaOptions": {
        "binary": "/usr/bin/opera"
    }
}
```
result:
```{'browserName': 'opera', 'version': '46.0', 'enableVNC': True, 'enableVideo': False, 'binary': '/usr/bin/opera'} <- operaOptions are completely ignored```

**Comment by piotrkochan** [comment]
https://github.com/seleniumbase/SeleniumBase/pull/459

**Comment by mdmintz** [comment]
@piotrkochan The new release is ready for the merged pull request: https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.34.10  It's also on pypi: https://pypi.org/project/seleniumbase/1.34.10/
