### ISSUE TITLE
Prevent unused log folders from being created

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#466]
There are log folders getting created in the ``latest_logs`` folder that aren't always used. Log folders should only be created if log files are going to be put in there. This will prevent logs from getting too messy. Logs are expected when a test fails, when a run command adds ``--save-screenshot``, and when a test calls a method that puts files into the log folder. If ``--archive-logs`` is set, the log files from ``latest_logs`` will be moved to the ``archived_logs`` folder at the start of the next test run (otherwise they will be deleted to save space).

**Comment by mdmintz** [comment]
This issue has been resolved.

**Comment by SzilvasiPeter** [comment]
Empty log folders (the `latest_logs` and the `archived_logs`) are still created by SeleniumBase. I am using the following version:
```
seleniumbase 4.17.7
pytest 7.4.0
```

**Comment by mdmintz** [comment]
The `latest_logs/` and `archived_logs/` folders are OK. It's the **subfolders** that shouldn't be created if a test doesn't generate any logs.

Below is an example of the subfolders generated after running all tests in the `SeleniumBase/examples/` folder. None of these folders should be empty if they are created.

<img width="645" alt="Screenshot 2023-08-17 at 1 22 28 PM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/e8885886-9373-44b6-baa5-c3fd21ab65cc">
