### ISSUE TITLE
How to customize nosetests generated html report

### ISSUE THREAD

**Issue by tcwaily** [seleniumbase/SeleniumBase#469]
How to customize nosetests generated html report？

**Comment by mdmintz** [comment]
The Nosetest report isn't customizable. The developers of Nosetests have stopped all work on it. Pytest is the future. What you see is what you get, but if you'd like to change the layout of it, the code for that is here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/report_helper.py and you'd have to apply it to your local clone or fork of SeleniumBase.

[<img src="https://camo.githubusercontent.com/f4af5dce0b8cf01f0e5fd4587b0e673ae274eabe/68747470733a2f2f63646e322e68756273706f742e6e65742f68756266732f3130303030362f696d616765732f546573745f5265706f72745f322e706e67">]()

**Comment by mdmintz** [comment]
And the CSS for that is here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/style_sheet.py

**Comment by tcwaily** [comment]
> Nosetest报告不可自定义。Nosetests的开发人员已经停止了所有工作。Pytest是未来。所见即所得，但是如果您想更改其布局，则此处的代码为：[https](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/report_helper.py) : [//github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/report_helper。 py](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/report_helper.py)，则必须将其应用于本地克隆或SeleniumBase的fork。
> 
> ![](https://camo.githubusercontent.com/f4af5dce0b8cf01f0e5fd4587b0e673ae274eabe/68747470733a2f2f63646e322e68756273706f742e6e65742f68756266732f3130303030362f696d616765732f546573745f5265706f72745f322e706e67)

pytest report how to customize html？

**Comment by mdmintz** [comment]
@tcwaily If you're just looking for a translation of text in there (into Chinese for example), I could parse that out into a settings file. Is that what you're looking for?

**Comment by mdmintz** [comment]
@tcwaily, I could create a setting where the user selects a language before starting tests on the command line, and then have all messages and reports print in that language. It would be a large undertaking, but it's a possibility if there's interest in having SeleniumBase get translated into multiple languages. Something for 2020.
