### ISSUE TITLE
Need help in implementing in POM

### ISSUE THREAD

**Issue by dineshKumar777** [seleniumbase/SeleniumBase#476]
I am trying to use SeleniumBase as base framework and extend test solution for our project as per need. 
Facing few issues in achieving that goal, mostly because I am new to python and trouble implementing whatever we did so far in Java and c#

Main requirement is Page Object Model.
I saw your example on POM in seleniumbase (examples/boilerplatest/Page_objects.py) which is in following structure

 - Project 	
	 - Locators for all pages
	 - Test 

What I am trying to achieve is in following structure

 - Project
	 - Pages (contains locators and common functionalities)
		 - HomePage
		 - LoginPage
	- Tests
		- HomepageTest
		- LoginpageTest

**Code I tried
Pages/Homepage.py**
``` python

import time  
  
from seleniumbase import BaseCase  
  
  
class DuckDuckGoSearchPage(BaseCase):  
  
    URL = "https://www.duckduckgo.com"  
  
  # LOCATORS (default css locators)  
  SEARCH_INPUT = "input[name='q']"  
  
  def load(self):  
        self.open(self.URL)  
  
  def search(self, phrase):  
        self.update_text('input[name="q"]', phrase + '\n')  
        time.sleep(4)
```
**Tests/Homepage_test.py**
```python
from seleniumbase import BaseCase  
from Pages.searchPage import DuckDuckGoSearchPage  
  
  
class HomepageTest(BaseCase):  
    def test_simple_search(self):  
        PHRASE = 'seleniumbase'  
	searchengine = DuckDuckGoSearchPage(BaseCase)  
        searchengine.load()  
        searchengine.search(PHRASE)
```

**Comment by mdmintz** [comment]
@dineshKumar777 Have you looked at https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py ?

**Comment by dineshKumar777** [comment]
@mdmintz Thanks for the link. Implementing as you referenced worked good.

Is this the correct way to write test using seleniumbase pageobject or is there any other better way to do this?

```python
from Pages.searchPage import DuckDuckGoSearchPage
from Pages.resultPage import DuckDuckGoResultPage


class HomepageTest(DuckDuckGoSearchPage, DuckDuckGoResultPage):
    def test_simple_search(self):
        PHRASE = 'seleniumbase'
        self.load()
        self.search(PHRASE)

        self.assert_link_div_count()
        self.assert_search_input_value(PHRASE)

```

**Comment by mdmintz** [comment]
See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/boilerplate_test.py
Single inheritance for a subclass of BaseCase. Page objects get imported, not inherited.

**Comment by dineshKumar777** [comment]
> See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/boilerplate_test.py
> Single inheritance for a subclass of BaseCase. Page objects get imported, not inherited.

Sorry for dragging this out. I gone through all your examples but unable to make it work without inheriting!

Closest implementation in your example of what i want, is showed in [PageObjects.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/page_objects.py). But you used it to declare locators only and in calling test case you imported and called locators directly.

I need common methods to be implemented in page wise similarly. Not in single class like you mentioned in baseclass. Trying to attain pagestructure as following sample image

![sample](https://user-images.githubusercontent.com/21097695/72407235-da8b6280-3784-11ea-8f6c-3180194ca9f2.jpg)

Taking your  [PageObjects.py](https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/page_objects.py) example. I modified it as follows which contains locators and common functionalities.
Please correct the code to guide me attaining this behavior. 



``` python
class HomePage(object):
    see_items_button = "button.items"
    menu_bar = "menu.items"

    def is_menubar_displayed(self):
        return menubar_display_status

class ShoppingPage(object):
    buyable_item = 'img[alt="Item"]'
    add_to_cart = "button.add"
    go_to_checkout = "#checkout"

    def checkout_products(self):
          pass
        

```
so how do i access these methods in test class?

``` python
from .base_test_case import BaseTestCase
from .page_objects import HomePage, ShoppingPage

class MyTests(BaseTestCase):
    def test_example(self):
        self.login()
        # how to call Homepage.is_menubar_displayed() & Shoppingpage.Checkout_products() without inheriting as you mentioned before?

```

**Comment by allandsouza** [comment]
@dineshKumar777 - What you are trying is not something currently supported in this framework. See my last comment in https://github.com/seleniumbase/SeleniumBase/issues/392. Its exactly the same thing I was looking for in the beginning.

**Comment by mdmintz** [comment]
@dineshKumar777 In the case of https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/boilerplate_test.py , it calls the login() method from BaseTestCase, its parent class.
```python
from .base_test_case import BaseTestCase
from .page_objects import Page

class MyTestClass(BaseTestCase):

    def test_boilerplate(self):
        self.login()
        self.example_method()
        self.assert_element(Page.html)
```

**Comment by dineshKumar777** [comment]
> @mdmintz Thanks for the link. Implementing as you referenced worked good.
> 
> Is this the correct way to write test using seleniumbase pageobject or is there any other better way to do this?
> 
> ```python
> from Pages.searchPage import DuckDuckGoSearchPage
> from Pages.resultPage import DuckDuckGoResultPage
> 
> 
> class HomepageTest(DuckDuckGoSearchPage, DuckDuckGoResultPage):
>     def test_simple_search(self):
>         PHRASE = 'seleniumbase'
>         self.load()
>         self.search(PHRASE)
> 
>         self.assert_link_div_count()
>         self.assert_search_input_value(PHRASE)
> ```

@mdmintz as said before this is the closest implementation I can do with current framework structure with multiple inheritance. Thanks for the support and awesome framework in python community.

@allandsouza Thanks for the reference. Yep I am trying to achieve what you were asked and seems its not possible at the moment.
