### ISSUE TITLE
headless issue

### ISSUE THREAD

**Issue by wangrocky** [seleniumbase/SeleniumBase#478]
seleniumbase testcases ran perfectly in normal way but error raised in the headless mode, 
the command is : 
`pytest --headless --browser=chrome（or firefox）`
the error as below:
```
 File "c:\python37\lib\traceback.py", line 285, in line
INTERNALERROR>     self._line = linecache.getline(self.filename, self.lineno).strip()
INTERNALERROR>   File "c:\python37\lib\linecache.py", line 18, in getline
INTERNALERROR>     lines = getlines(filename, module_globals)
INTERNALERROR>   File "c:\python37\lib\linecache.py", line 49, in getlines
INTERNALERROR>     return updatecache(filename, module_globals)
INTERNALERROR>   File "c:\python37\lib\linecache.py", line 141, in updatecache
INTERNALERROR>     lines = fp.readlines()
INTERNALERROR>   File "c:\python37\lib\codecs.py", line 322, in decode
INTERNALERROR>     (result, consumed) = self._buffer_decode(data, self.errors, final)
INTERNALERROR> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 1472: invalid continuation byte
```
i tried the google and used some encoding&decoding way but it did not work, could u please check this issue which blocked me such a long time.. thanks a lot~~

**Comment by mdmintz** [comment]
Hi @wangrocky This might be specific to the test you're running, as I'm not encountering this issue. Can you attach the test script you're running?
Also, this StackOverflow article may help you: https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

**Comment by mdmintz** [comment]
Closing this, as I haven't heard back in a week. If the issue persists for you, please reopen with an example that I can use to reproduce this issue.
