### ISSUE TITLE
select_option_by_text & Index() throws elementnotvisibleexception always

### ISSUE THREAD

**Issue by dineshKumar777** [seleniumbase/SeleniumBase#481]
Always getting error as following for optionbytext as well as index call.

`selenium.common.exceptions.ElementNotVisibleException: Message: Element {#id_contact} was not visible after 6 seconds!`

I tried with different selector types but getting the same error. Am I missing something here?

Target page http://automationpractice.com/index.php?controller=contact

``` HTML
<div class="selector" id="uniform-id_contact" style="width: 266px;">
	<span style="width: 256px; user-select: none;">-- Choose --</span>
		<select id="id_contact" class="form-control" name="id_contact">
                        <option value="0">-- Choose --</option>
                        <option value="2">Customer service</option>
                        <option value="1">Webmaster</option>
        </select>
</div>
```

``` python
def select_dropdown(self):
	self.click("#uniform-id_contact") #opens dropdown menu. tried with and without this line
	self.select_option_by_text("#id_contact", "Webmaster")
```

**Update**
This is happening for this particular website it seems. I tried the same method in https://materializecss.com/select.html. 
It working there correctly by calling `self.select_option_by_text("select[class='browser-default']", "Option 1")`
Not sure why its not working in first site?

**Comment by allandsouza** [comment]
Can to try adding an explicit timeout like below? 
`self.select_option_by_text("#id_contact", "Webmaster" , timeout=20)`

**Comment by dineshKumar777** [comment]
@allandsouza Actually its not related to timeout issue(page is fully loaded) because I tried with both ipdb and pycharm evaluate expression at the particular instance once the page loaded. Still getting the same error.
This is happening only in this site though!

**Comment by mdmintz** [comment]
@dineshKumar777 
Use:
```python
self.hover_and_click('#uniform-id_contact', '#id_contact [value="1"]')
```
The page has a strange design in that the visible property won't be active unless hovering over the ``#uniform-id_contact`` element first.
And since hovering is involved, you'll need the latest chromedriver for it to work:
```bash
seleniumbase install chromedriver latest
```

**Comment by dineshKumar777** [comment]
@mdmintz Thanks for looking into it. still hoverandclick also didnt work for me even with latest chromedriver. still getting the same timeout error.

**ChromeDriver** 2.40.565498
**Chrome browser version:** 79.0.3945.130(32 bit)

But this dropdown is working with default selenium commands and implemented as follows.
``` python
select = Select(self.driver.find_element_by_id('id_contact'))
select.select_by_index(1)
select.select_by_index(2)
select.select_by_visible_text("Webmaster")
select.select_by_value("Customer Service") #not working
```

**Comment by mdmintz** [comment]
@dineshKumar777 Your version of Chromedriver looks old. See https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by dineshKumar777** [comment]
Oh will check this tomorrow and update here the results of it

**Comment by mdmintz** [comment]
@dineshKumar777 The issue is fixed in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.34.22 (Basically, even though Selenium said the element wasn't visible, Select() would still work as long as you don't check for element visibility first. I switched ``wait_for_element_visible()`` to ``wait_for_element_present()`` before doing the ``Select()``, and that did the trick.

**Comment by dineshKumar777** [comment]
@mdmintz thanks for the fix. Verified  and Its working now perfectly with option_by_text, value and index.
