### ISSUE TITLE
How do I use setup and teardown?

### ISSUE THREAD

**Issue by tcwaily** [seleniumbase/SeleniumBase#484]
I want to use this framework. How do I use setup and teardown? Because I want to do something before the test starts.

**Comment by mdmintz** [comment]
@tcwaily See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py

**Comment by tcwaily** [comment]
> @tcwaily See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py

I have read here, only method-level setup can be implemented here. I want to use module-level and perform some operations before all tests start.

**Comment by mdmintz** [comment]
@tcwaily See ``def pytest_configure`` and ``def pytest_unconfigure`` in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/pytest_plugin.py , which allow you to do a special setup once before all tests, and a special teardown after all tests have completed. This would require you to fork a copy of SeleniumBase and install it from your local clone of it.

**Comment by tcwaily** [comment]
> @tcwaily See `def pytest_configure` and `def pytest_unconfigure` in https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/pytest_plugin.py , which allow you to do a special setup once before all tests, and a special teardown after all tests have completed. This would require you to fork a copy of SeleniumBase and install it from your local clone of it.

Are there any examples？

**Comment by mdmintz** [comment]
The example is built-in (the pytest plugin) which parses out command line options before any test runs, and then archives the logs after all the tests complete. That's the only example, but there's a lot of documentation online about it here: https://pytest.readthedocs.io/en/2.7.3/plugins.html

Here's a snippet from it:
```
pytest_configure(config)[source]
    called after command line options have been parsed and all plugins and initial conftest files been loaded.
pytest_unconfigure(config)[source]
    called before test process is exited.
```

**Comment by tcwaily** [comment]
> The example is built-in (the pytest plugin) which parses out command line options before any test runs, and then archives the logs after all the tests complete. That's the only example, but there's a lot of documentation online about it here: https://pytest.readthedocs.io/en/2.7.3/plugins.html
> 
> Here's a snippet from it:
> 
> ```
> pytest_configure(config)[source]
>     called after command line options have been parsed and all plugins and initial conftest files been loaded.
> pytest_unconfigure(config)[source]
>     called before test process is exited.
> ```
 thanks.
