### ISSUE TITLE
pytest plugin --port option conflicts with pytest-selenium plugin

### ISSUE THREAD

**Issue by nfk** [seleniumbase/SeleniumBase#492]
In order to update a test base and to be able to run pytest without a virtual environment it should be great to have the ability to use both `seleniumbase` and `pytest-selenium` in same time.

After installing seleniumbase I cannot use `pytest` due to the following error.
```
argparse.ArgumentError: argument --port: conflicting option string: --port
```
 Can you rename some options? Or prefix it with sb?

**Comment by mdmintz** [comment]
Hi @nfk , SeleniumBase can’t be used together with pytest-selenium. It replaces pytest-selenium. Conflicting arguments. Although that’s why a virtual environment is recommended.
