### ISSUE TITLE
Cannot run my_first_test.py - ImportError while importing test module ('Requests' ?)

### ISSUE THREAD

**Issue by MaksimZinovev** [seleniumbase/SeleniumBase#498]
Hi, I am new to Python and test automation. I learn how to use pytest for web ui testin. Recently  found SeleniumBase  framework and wanted to give it a try. I followed your installation instructions but  keep getting this error:

`====================================== ERRORS ======================================
____________________ ERROR collecting examples/my_first_test.py ____________________
ImportError while importing test module '/Users/maksim/repos/seleniumbase/SeleniumBase/examples/my_first_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
my_first_test.py:1: in <module>
    from seleniumbase import BaseCase
../seleniumbase/__init__.py:1: in <module>
    from seleniumbase.fixtures.base_case import BaseCase  # noqa
../seleniumbase/fixtures/base_case.py:52: in <module>
    from seleniumbase.core import tour_helper
../seleniumbase/core/tour_helper.py:12: in <module>
    from seleniumbase.fixtures import js_utils
../seleniumbase/fixtures/js_utils.py:6: in <module>
    import requests
E   ModuleNotFoundError: No module named 'requests'
!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!
============================= 1 error in 0.66 seconds ==============================` 

I would really appreciate if you could help me to fix the problem 
Thank you!
Max

Please see terminal output (sorry, only 1000 lines available) attached and command history
[history.txt](https://github.com/seleniumbase/SeleniumBase/files/4197266/history.txt)
[iTerm2 Session 13 Feb 2020 at 7:18:33 pm.txt](https://github.com/seleniumbase/SeleniumBase/files/4197267/iTerm2.Session.13.Feb.2020.at.7.18.33.pm.txt)

**Comment by MaksimZinovev** [comment]
looks like it cannot  import 'requests' module, but why?

```
▶ pip install requests
Requirement already satisfied: requests in /Users/maksim/repos/seleniumbase/seleniumbase_ven/lib/python3.8/site-packages (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/maksim/repos/seleniumbase/seleniumbase_ven/lib/python3.8/site-packages (from requests) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/maksim/repos/seleniumbase/seleniumbase_ven/lib/python3.8/site-packages (from requests) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/maksim/repos/seleniumbase/seleniumbase_ven/lib/python3.8/site-packages (from requests) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/maksim/repos/seleniumbase/seleniumbase_ven/lib/python3.8/site-packages (from requests) (3.0.4)
(seleniumbase_ven)
seleniumbase/SeleniumBase/examples  master ✗
```

**Comment by mdmintz** [comment]
Hi @MaksimZinovev, There may be an issue with the way you created your virtual environment. I can't see why ``pip install requests`` wouldn't work for you, but here's a set of instructions to help: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/virtualenv_instructions.md (I used ``mkvirtualenv``, which is part of ``virtualenvwrapper``)

**Comment by MaksimZinovev** [comment]
Thank you for reply.
I got it working. Here is what helped me, in case someone else will have same issues. 

Turns out it was Pytest issue. This trick from[ Dirk Avery](https://medium.com/@dirk.avery/pytest-modulenotfounderror-no-module-named-requests-a770e6926ac5l) cured it.

**Comment by MaksimZinovev** [comment]
However , the story continued when I tried to run my_second_test.py from PyCharm

```
Testing started at 7:43 pm ...
/Users/maksim/repos/p08-aerofiler-selenium-base/venv/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_unittest_runner.py" --target my_first_test.MyTestClass.test_basic
Launching unittests with arguments python -m unittest my_first_test.MyTestClass.test_basic in /Users/maksim/repos/p08-aerofiler-selenium-base/examples



Ran 1 test in 0.007s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 672, in run
    self._callSetUp()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 630, in _callSetUp
    self.setUp()
  File "/Users/maksim/repos/p08-aerofiler-selenium-base/venv/lib/python3.8/site-packages/seleniumbase-1.35.3-py3.8.egg/seleniumbase/fixtures/base_case.py", line 4341, in setUp
    raise Exception("""SeleniumBase plugins DID NOT load!\n\n"""
Exception: SeleniumBase plugins DID NOT load!

*** Please REINSTALL SeleniumBase using: >
    >>> "pip install -r requirements.txt"
    >>> "python setup.py install" 


Assertion failed

Process finished with exit code 1

Assertion failed

Assertion failed
```
So what I did, simply  uninstalled SeleniumBase package from PyCharm and installed it again and ... got the same error.

It finally worked when I copied same code from the test into new file. 

my_second_test.py::MyTestClass::test_basic 

```
============================== 1 passed in 14.62s ==============================

Process finished with exit code 0
PASSED                        [100%]
```

Magic :)
