### ISSUE TITLE
where is testcaserepository.sql file，the page is 404

### ISSUE THREAD

**Issue by tkspeking** [seleniumbase/SeleniumBase#500]

**Comment by mdmintz** [comment]
Looks like it was renamed to this: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/create_db_tables.sql (I’ll update the ReadMe)

**Comment by tkspeking** [comment]
ok，thx

**Comment by mdmintz** [comment]
The ReadMe was updated in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.35.4
