### ISSUE TITLE
when the tested page has Chinese words, convert seleniumbase script has an error

### ISSUE THREAD

**Issue by tkspeking** [seleniumbase/SeleniumBase#501]
take look:
![image](https://user-images.githubusercontent.com/47775353/74640762-0e560f80-51ab-11ea-910a-c9ca1b27f2d3.png)

error info:UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1413: illegal multibyte sequence

when I edit the code 53 line in convert_ide.py like
f = open(webdriver_python_file, 'r') ->     f = open(webdriver_python_file, 'r', encoding='utf-8'), convert succefully, but Chinese word is garbage characters

**Comment by mdmintz** [comment]
@tkspeking Can you send me an example that I can use to help me debug this?

**Comment by tkspeking** [comment]
> @tkspeking Can you send me an example that I can use to help me debug this?
ok，you can edit test_baidu.txt to test_baidu.py, and then convert it

[test_baidu.txt](https://github.com/seleniumbase/SeleniumBase/files/4216964/test_baidu.txt)

**Comment by mdmintz** [comment]
This is what I got when renaming test_baidu.txt to test_baidu.py and running: ``seleniumbase convert test_baidu.py``:
```python
# -*- coding: utf-8 -*-
from seleniumbase import BaseCase


class UntitledTestCase(BaseCase):

    def test_untitled_test_case(self):
        self.open('https://www.baidu.com/')
        self.click('#kw')
        self.driver.find_element_by_id("kw").send_keys(u"中国")
        self.click('#su')
        try: self.assertEqual(u"中国卫生人才网", self.driver.find_element_by_link_text(u"中国卫生人才网").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
```
(On my system, the characters converted successfully.)

**Comment by tkspeking** [comment]
so strange

**Comment by mdmintz** [comment]
I can try putting ``# -*- coding: utf-8 -*-`` at the top of ``convert_ide.py`` in case your system needs that. I'll put that in the next release.

**Comment by tkspeking** [comment]
I edit

**Comment by mdmintz** [comment]
I'll add in the ``encoding='utf-8'`` to lines 53 and 725, since that helped. That'll prevent errors at least.

**Comment by tkspeking** [comment]
ok

**Comment by mdmintz** [comment]
https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.35.4 is ready.
