### ISSUE TITLE
Timeout in switch_to_window method doesn't do anything when the window page doesn't load

### ISSUE THREAD

**Issue by createNull** [seleniumbase/SeleniumBase#508]
I press a button which will open a new tab in my browser. That new tab will have a long page load time and even if I set timeout=0 to switch_to_window method and try to execute a script in order to stop loading that page, my automated script will still wait for the new page to load.

Is there any other way I could stop that page from loading? 
Worth mentioning that I also need to check for some elements in the new page, so the switch is necessary

**Comment by mdmintz** [comment]
@createNull First, timeout should always be greater than zero. That's how long the test waits to try to switch to a tab you just opened when using ``switch_to_window()``. Also, if you switch to a tab that's loading a page, the test needs to wait for the page to finish loading before it can perform any actions on the page.

**Comment by createNull** [comment]
Sorry, my bad with the timeout then. 
I actually tried it with numbers > 0 as well and I got the same result.

Waiting for the page to load is nice, but in case there is some huge loading time there should be a way to stop the loading page (for me the timeout should do this), but the timeout actually does nothing until the page loads (as you already mentioned).

In Selenium you can stop the page from loading, so maybe this might be a feature to add?

**Comment by mdmintz** [comment]
It seems that you probably want the page to finish loading before checking for elements on it, because otherwise the elements you’re looking for might not have loaded yet. SeleniumBase will wait for the page to finish loading because otherwise you’ll get errors interacting with the page. Not sure there’s an easy way around it, but you’re going to want the page to finish loading to avoid page interaction errors.

**Comment by createNull** [comment]
In my particular case I don't want to wait since the DOM is fully loading, so I can check any element on page without any errors. 
I thought it might be an interesting feature to add in order to get better control over the pages, but you're probably right and it won't add too much value to the framework since it's just a corner case.

Thank you for your fast answers!
