### ISSUE TITLE
Allow user to specify `--no-sandbox` and `--disable-gpu` for Chrome drivers ran inside Docker containers

### ISSUE THREAD

**Issue by zhangxiubo** [seleniumbase/SeleniumBase#511]
When running tests written with SeleniumBase inside a Docker container, the user may want to load extensions when launching the Chrome driver. The logic for determining which options to be supplied to the Chrome driver when launching the browser is controlled by `core/browser_launcher.py`; for Linux, the segment relevant to this issue is:
```
    if headless:
        if not proxy_auth:
            # Headless Chrome doesn't support extensions, which are
            # required when using a proxy server that has authentication.
            # Instead, base_case.py will use PyVirtualDisplay when not
            # using Chrome's built-in headless mode. See link for details:
            # https://bugs.chromium.org/p/chromium/issues/detail?id=706008
            chrome_options.add_argument("--headless")
        chrome_options.add_argument("--disable-gpu")
        if "linux" in PLATFORM:
            chrome_options.add_argument("--no-sandbox")
    if "linux" in PLATFORM:
        chrome_options.add_argument("--disable-dev-shm-usage")
```

Since `headless` mode does not support extensions, one has to enable `--gui` to turn off headless mode; however, it seems Chrome inside a docker container will not launch its GUI without specifying the `--no-sandbox` (and sometimes the `--disable-gpu`) option, which is only supplied to the driver when headless mode is turned on.

This means that SeleniumBase tests launched inside a Docker container cannot benefit from extensions.

Perhaps additional options can be added to allow the user to manipulate these settings?

**Comment by mdmintz** [comment]
@zhangxiubo The work for this is done in SeleniumBase 1.36.0, just released.
See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.36.0

**Comment by zhangxiubo** [comment]
@mdmintz Wow, that's really fast! Thanks for the update!
