### ISSUE TITLE
 self.hover_and_click() does not support xpath

### ISSUE THREAD

**Issue by alex-pancho** [seleniumbase/SeleniumBase#513]
Look like  self.hover_and_click() does not support xpath any way.
I try to use just
```! python
def test_sub_menu(self):
        self.get("https://www.babyshop.com")
        self.hover_and_click('//a[@data-class="babyshoes"]', '//div[@class="babyshoes mid-navigation-container"]//a')
```
and try
```! python
from selenium.webdriver.common.by import By
def test_sub_menu(self):
        self.get("https://www.babyshop.com")
        self.hover_and_click('//a[@data-class="babyshoes"]', '//div[@class="babyshoes mid-navigation-container"]//a',By.XPATH,By.XPATH)
```
but its function work only with css-selector

**Comment by mdmintz** [comment]
@alex-pancho Fixed in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.36.1

**Comment by alex-pancho** [comment]
```driver = <selenium.webdriver.chrome.webdriver.WebDriver (session="ac45a1f4538832c7a9e0d94292390a9e")>
hover_selector = 'a[data-class="babyshoes"]'
click_selector = '//div[@class="babyshoes mid-navigation-container"]/div[@class="content c-16"]/div[@class="c-8"]/ul[2]/li[1]/a'
hover_by = 'css selector', click_by = 'xpath', timeout = 6
(....)
E       selenium.common.exceptions.NoSuchElementException: Message: Element {//div[@class="babyshoes mid-navigation-container"]/div[@class="content c-16"]/div[@class="c-8"]/ul[2]/li[1]/a} was not present after 6 seconds!

lib\site-packages\seleniumbase\fixtures\page_actions.py:147: NoSuchElementException
```

**Comment by alex-pancho** [comment]
first part automatically transfer (converted?) to css-selector but  second - not yet

**Comment by alex-pancho** [comment]
![pic](https://i.imgur.com/tK70EhH.png)
May be you can try to use in code just:
driver.find_element(by, selector)

**Comment by mdmintz** [comment]
@alex-pancho I’ll do another release in the next 12 hours to fix this.

**Comment by alex-pancho** [comment]
well, look like problem with long x-path. I try use shorten xpath and all work fine:
self.hover_and_click('//a[@data-class="babyshoes"]', '//a[@href="/boots-and-winter-shoes/s/673"]')

**Comment by mdmintz** [comment]
@alex-pancho If short XPath is working, perhaps the long XPath is incorrect?

**Comment by alex-pancho** [comment]
no, I always check xpath before use. Now i'll write three different xpath for this element, and all contain one text
'//a[@href="/boots-and-winter-shoes/s/673"]'
'//*[@id="mid-navigation"]/div[9]/div/div[1]/ul[2]/li[1]/a'
'//*[@id="mid-navigation"]/div[@class="babyshoes mid-navigation-container"]//div[@class="c-8"]/ul[2]/li[1]/a'
'//div[@class="babyshoes mid-navigation-container"]/div[@class="content c-16"]/div[@class="c-8"]/ul[2]/li[1]/a'
and check result into site and Google-chome console:
![Imgur](https://imgur.com/USykftM)
![Imgur2](https://imgur.com/lraSp1P)
![Imgur3](https://imgur.com/Ca3dui0)
![Imgur4](https://imgur.com/temFYKq)

**Comment by alex-pancho** [comment]
first two work , 3 and 4 - does not. May be its because xpath contain sub-attributes inside (its first what i can find)

**Comment by mdmintz** [comment]
The hover selectors that are XPath get converted to CSS Selector first, but the click selectors stay as XPath for the Selenium click operation. Maybe it is due to the sub-attributes of the XPath. I'm still looking into it. It'll be easier to debug from a full example, such as the one you gave when you opened the issue. If the shorter XPath works for you, is that enough of a solution?

**Comment by alex-pancho** [comment]
if sub-attributes was supported - it was better

**Comment by allandsouza** [comment]
So, its not necessarily hover_and_click() that's impacted. For me, slow_click() stopped working on updating to 1.36.1. In general, I feel all methods using xpath selector would be impacted

`self.slow_click("//span[@title='Close popup']", by=By.XPATH)`

Its definitely some change in the newer seleniumbase version that broke this, since going back to 1.34.18, the above code works fine.

I haven't gotten to determining the exact change causing this, but for now, will workaround by changing the selector.

**Comment by mdmintz** [comment]
@alex-pancho @allandsouza Hopefully fixed now in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.36.2

**Comment by allandsouza** [comment]
Worked for me. Thank you @mdmintz

**Comment by mdmintz** [comment]
@alex-pancho Did you get a chance to try the latest version of SeleniumBase? Others have tried it and it resolved their XPath issue.
