### ISSUE TITLE
No screenshot in html report after test failure

### ISSUE THREAD

**Issue by createNull** [seleniumbase/SeleniumBase#516]
Hi, 

Maybe I am doing something wrong, but I can't get any screenshot when my tests fail.
I've tried with and without `--headless` arg, running them one by one or in parallel, adding `--save-screenshot` arg and I would only get screenshots for passed tests.

I did follow your boilerplate model and I have a `base_test_case.py` file and `test_suite.py` file.
In `base_test_case.py` I have this:
```
class BaseTestCase(BaseCase):

    def setUp(self):
        super(BaseTestCase, self).setUp()
        self.maximize_window()
        self.open(URL)

    def tearDown(self):
        self.save_teardown_screenshot()
        super(BaseTestCase, self).tearDown()
```

In `test_suite.py` I have this:
```
class TestSuite(BaseTestCase):
    def test_basic(self):
        assert False
```

My config from the test report:
```
Packages | {'pytest': '5.4.0', 'py': '1.8.1', 'pluggy': '0.13.1'}
-- | --
Platform | macOS-10.15.3-x86_64-i386-64bit
Plugins | {'seleniumbase': '1.35.8', 'html': '2.0.1', 'rerunfailures': '8.0', 'xdist': '1.31.0', 'ordering': '0.6', 'forked': '1.1.3', 'metadata': '1.8.0', 'cov': '2.8.1'}
Python | 3.8.2

```
Attached image of the test report:
![image](https://user-images.githubusercontent.com/23474238/76962387-0a86eb80-6917-11ea-869d-f778acd3342b.png)

Thanks in advance

**Comment by mdmintz** [comment]
Hi @createNull , try again in the latest version of SeleniumBase, which is https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.36.2 . It looks like pytest-html and pytest introduced bugs in their latest versions, so I set the versions to earlier ones, and that fixed the issue:

```
pytest==5.3.5;python_version>="3.5"
pytest-html==2.0.1;python_version>="3.6"
```

**Comment by createNull** [comment]
Many thanks!
