### ISSUE TITLE
@pytest.mark.repeat() can not use in seleniumbase.

### ISSUE THREAD

**Issue by arantir53** [seleniumbase/SeleniumBase#518]
Hi,
     I wanted to execute a test case many times, so I used decorator @pytest.mark.repeat(3), but it didn't work.  If I use raw pytest-repeat alone, there is no problem, but not in seleniumbase. Why? I have import pytest and also installed the pytest-repeat library.
     The raw pytest code works.  The code is as follows:
```python
import pytest
@pytest.mark.repeat(3)
def test_1():
   print("message")
```

   The seleniumBase code didn't works.  The code is as follows:
```python
from seleniumbase import BaseCase

class test_case(BaseCase):
    @pytest.mark.repeat(3)
    def test_1(self):
        print("message")
```

    My purpose is to generate a user, this user has a lot of attributes, so I want to randomly generate for each, this is why I need to execute a use case multiple times.  The only way I know is @ pytest.mark.repeat ().  Please tell me if there is any similar scheme in seleniumbase.

Best Regards.

**Comment by mdmintz** [comment]
@arantir53 There's a workaround for SeleniumBase due to compatibility issues with ``pytest.mark.repeat()`` -> You can create a parameterized test (without passing in parameters). The following will have the test run 3 times (one for each ``[],`` in the ``@parameterized.expand``):
```python
from seleniumbase import BaseCase
from parameterized import parameterized

class TestCase(BaseCase):
    @parameterized.expand([
        [], [], [],
    ])
    def test_1(self):
        print("message")
```
That assumes you can't just use a ``for`` loop in your tests, which makes things simpler if you can use it for what you're doing:
```python
from seleniumbase import BaseCase

class TestCase2(BaseCase):
    def test_2(self):
        for i in range(3):
            print("message")
```
On an unrelated note, I recently created a Chinese translation of SeleniumBase in a recent version (Example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/translations/chinese_test_1.py) and I'm wondering if you think it's useful.

**Comment by arantir53** [comment]
Thanks, this works perfectly.  
But 3 is just an approximation, what if I want to execute it 50 times? Can I use code like this?
in `baseFunction.py`:
```python
def create_empty_list(num=50):
    list = []
    for i in range(num):
       list.append([])
    return list
```
in `test_case.py`:
```python
import baseFunction
from parameterized import parameterized

class test_case(BaseTestCase):
    @parameterized.expand([
        create_empty_list()
    ])
    def test_1(self):
        print("message")
```


I have seen another issues. I coudn't use a function from another file by using @parameterized.expand(). Right? Or is there any other way?

**Comment by mdmintz** [comment]
@arantir53 I have a working solution.
This will repeat the test as many times as you specify:
```python
from seleniumbase import BaseCase
from parameterized import parameterized

def create_empty_list(num=5):
    my_list = []
    for i in range(num):
       my_list.append([])
    return my_list

class TestCase(BaseCase):
    @parameterized.expand(create_empty_list())
    def test_1(self):
        print("message")
```

**Comment by arantir53** [comment]
Thanks, it works perfectly now. Another problem is that our products use a lot of canvas tags to describe objects such as places and buildings. I rummaged through the selenium native library and the seleniumbase library, and I couldn't find a way to operate the canvas tag.  I know that canvas is just like a wall to DOM objects, maybe selenium can't do this. Is there any simpler way for me to operate the objects in the canvas?  Do I have to learn opencv to learn image processing?

**Comment by mdmintz** [comment]
@arantir53 SeleniumBase doesn't do image processing. You'll probably want opencv for that as you mentioned. Also, since the original issue has been resolved, would you say it's safe to close this issue?
