### ISSUE TITLE
[Question]: Invalid or unsupported Xpath

### ISSUE THREAD

**Issue by allandsouza** [seleniumbase/SeleniumBase#521]
PS: This is likely not a seleniumbase thing but wanted to confirm.

A xpath expression like below returns back as unsupported.
`//span[text()='Add Products']/ancestor::button`

seems to be a valid xpath expression. Is this a seleniumbase thing? If yes, can it be fixed?

**Comment by allandsouza** [comment]
Below is the code snipped that fails for reference:

xpath = "//span[text()='Add Products']/ancestor::button"

    def _get_raw_css_from_xpath(xpath):
        css = ""
        position = 0
    
        while position < len(xpath):
            node = prog.match(xpath[position:])
            if node is None:
>               raise XpathException("Invalid or unsupported Xpath: %s" % xpath)
E               seleniumbase.fixtures.xpath_to_css.XpathException: Invalid or unsupported Xpath: //span[text()='Add Products By SKU']/ancestor::button

venv/lib/python3.7/site-packages/seleniumbase/fixtures/xpath_to_css.py:84: XpathException

**Comment by mdmintz** [comment]
@allandsouza I don't think the ``()`` in ``text()`` is valid for XPath selectors. Show me the html where you're finding that.

**Comment by allandsouza** [comment]
The same xpath expression works fine for a slow_click.

See HTML in the attached snapshot alongside how chrome detects the right element with this xpath expression.

That said, this xpath and/or element may not be valid for a hover may be? The error showed up when I used this xpath in the hover_and_click method.

<img width="625" alt="Screen Shot 2020-03-20 at 1 10 17 PM" src="https://user-images.githubusercontent.com/17289362/77203012-b01f9380-6aac-11ea-8128-e594383cd28a.png">

**Comment by mdmintz** [comment]
@allandsouza Use CSS Selectors for hover elements to be safe.

**Comment by allandsouza** [comment]
Ok, thanks!

One last question - Do you have any reliable strategy for handling the below error? Its a classic problem where page element are temporarily disable by a spinning wheel or some other element/method. this is not really a seleniumbase issue per se, but was wondering if seleniumbase has any trick up its sleeve to handle this. ;)

`E       selenium.common.exceptions.WebDriverException: Message: Element <button class="action-secondary action-add" type="button">...</button> is not clickable at point (978, 146). Other element would receive the click: <div class="loading-mask" data-role="loader" style="display: block;">...</div>
E         (Session info: chrome=80.0.3987.149)`

**Comment by mdmintz** [comment]
@allandsouza You can use ``self.wait_for_element_not_visible('div[data-role="loader"]')`` to wait for the spinner to complete. You may have to change the default timeout length if it lasts longer than 10 seconds.

**Comment by allandsouza** [comment]
Thank you @mdmintz
