### ISSUE TITLE
custom --with-db_reporting storage field？

### ISSUE THREAD

**Issue by tcw0nw** [seleniumbase/SeleniumBase#527]
pytest.ini --with-db_reporting 
Can this parameter define the fields stored in the database, because I need to read the results of these use cases and display them on the page, but the current fields do not meet my needs

**Comment by mdmintz** [comment]
@tcw0nw You may add the ``--with-db_reporting`` to ``pytest.ini``, but the DB columns are fixed, and cannot be changed now without breaking backwards compatibility for all other SeleniumBase users. However, there are more columns available than what you see in the example from: https://travis-ci.org/github/seleniumbase/SeleniumBase/jobs/667564309 (shown below), if that's what you're looking at. All available columns can be found here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/create_db_tables.sql
```
sudo mysql --password=test -e 'select test_address,browser,state,start_time,runtime from test_db.test_run_data'

+------------------------------------------------------------+---------+-------+---------------+---------+
| test_address                                               | browser | state | start_time    | runtime |
+------------------------------------------------------------+---------+-------+---------------+---------+
| boilerplates.boilerplate_test.MyTestClass.test_boilerplate | chrome  | Pass  | 1585286674181 |    1634 |
| examples.my_first_test.MyTestClass.test_basic              | firefox | Pass  | 1585286684886 |    7473 |
| examples.my_first_test.MyTestClass.test_basic              | chrome  | Pass  | 1585286693108 |   23698 |
| examples.my_first_test.MyTestClass.test_basic              | chrome  | Pass  | 1585286676580 |    4241 |
| google_tour.MyTourClass.test_google_tour                   | chrome  | Pass  | 1585286720328 |    7354 |
| examples.test_inspect_html.MyTestClass.test_html_inspector | chrome  | Pass  | 1585286717566 |    2027 |
+------------------------------------------------------------+---------+-------+---------------+---------+
```
(Times listed are in milliseconds.)

**Comment by mdmintz** [comment]
I'm going to assume that answered the question and close this ticket.
