### ISSUE TITLE
seleniumBase convert id to css_selector don't find the element

### ISSUE THREAD

**Issue by acpn** [seleniumbase/SeleniumBase#531]
Hello guys,

I'm in an automation project of a system developed in ADF (i know, why someone use that, right?), it's a proprietary software and i've to do a lot of automation here.

I've a background with selenium + python and recently i hear in the testGuilde podcast about seleniumBase, and i think why not?

Now i'm facing an issue when i have the id of an element, but with selenium base update_text method, doesn't work. So i go through documentation (excellent by the way), and noted which i can pass by=By.SELECTOR, but also doesn't work. Someone have a clue?

I know seleniumBase convert id or whatever to css_selector, but maybe because of something doesn't working.

Thanks,
Antonio

**Comment by acpn** [comment]
Hi,

I found the problem, was just a '#' character in the init part of the id hahaha.

Sorry, i'll close the issue.

Thanks,

**Comment by mdmintz** [comment]
@acpn Unrelated, there's now a Portuguese translation of SeleniumBase: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/translations/portuguese_test_1.py
Here's an example test:
```python
from seleniumbase.translate.portuguese import CasoDeTeste

class MinhaClasseDeTeste(CasoDeTeste):

    def test_exemplo_1(self):
        self.abrir_url("https://pt.wikipedia.org/wiki/")
        self.verificar_texto("Wikipédia")
        self.verificar_elemento('[title="Língua portuguesa"]')
        self.atualizar_texto("#searchInput", "Rio de Janeiro")
        self.clique("#searchButton")
        self.verificar_texto("Rio de Janeiro", "#firstHeading")
        self.verificar_elemento('img[alt*="edifícios"]')
        self.atualizar_texto("#searchInput", "São Paulo")
        self.clique("#searchButton")
        self.verificar_texto("São Paulo", "h1#firstHeading")
        self.verificar_elemento('img[src*="Monumento"]')
        self.voltar()
        self.verificar_verdade("Rio" in self.obter_url_atual())
        self.atualizar_texto("#searchInput", "Florianópolis\n")
        self.verificar_texto("Florianópolis", "h1#firstHeading")
        self.verificar_elemento('img[alt*="Avenida Beira Mar"]')
```

**Comment by acpn** [comment]
Nice @mdmintz, I'll check it out!

Thanks!
