### ISSUE TITLE
Unable to get current url of new window pdf in headless mode

### ISSUE THREAD

**Issue by createNull** [seleniumbase/SeleniumBase#532]
There is an issue when trying to click a button that opens a pdf file in a new browser tab.
I'm doing a basic verification of the new tab url and it appears that I can't get the new tab url in headless mode.

Worth mentioning that the test has no issues when the browser window is opened in normal mode.

Might be related to this issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3120
But there it seems the current url is accessible on their side, so maybe there is a seleniumbase issue.

My test looks something like this:
```python
self.open(URL)
self.click(element)
self.switch_to_window(1)
self.assert_true(element.get('url') in self.get_current_url().strip(),
                             f'URL {element.get("url")} could not be found inside URL! '
                             f'Got {self.get_current_url()} instead.')
```
Command: 
`pytest my_test.py -vs --headless`
(tested in Chrome only)

Error:
`  AssertionError: False is not true : URL Flavored-Tobacco-Bans-and-Menthol-Exemptions-List could not be found inside URL! Got about:blank instead.
` is what I get after 7:30 mins

Config:  {'Python': '3.8.2', 'Platform': 'macOS-10.15.4-x86_64-i386-64bit', 'Packages': {'pytest': '5.3.5', 'py': '1.8.1', 'pluggy': '0.13.1'}, 'Plugins': {'html': '2.0.1', 'rerunfailures': '9.0', 'seleniumbase': '1.36.9', 'xdist': '1.31.0', 'ordering': '0.6', 'forked': '1.1.3', 'metadata': '1.8.0', 'cov': '2.8.1'}}

**Comment by createNull** [comment]
Try this one:
https://tobaccofreeca.com/we-are-not-profit/#fight-back and scroll just a little bit up to a button "SEE FULL LIST"

**Comment by mdmintz** [comment]
@createNull I'm running into the issue in headless mode, and that chromedriver bug may be the cause, but I do have a workaround. Try running with ``--headed`` when running on a machine with a headless display. SeleniumBase will use a virtual display (using xvfb) that allows you to bypass running in headless mode.

**Comment by createNull** [comment]
The chromedriver bug seems to be related strictly to downloading PDFs while getting the current URL works as intended. This issue should be further investigated, I might also try to do it only with pytest and selenium and see the results.

I don't have a headless machine at the moment and I want to run my tests in `--headless` mode to get a better runtime, so I can't test it right now. 
Maybe it could work if I run the tests inside a Docker container with `--headed` argument.

**Comment by mdmintz** [comment]
@createNull  You could try adding the following to the beginning of the specific test that you don't want to run in headless mode:
```python
if self.headless:
    self.get_new_driver(headless=False)
```
Here's a full example of that:
```python
from seleniumbase import BaseCase

class MyTestClass(BaseCase):

    def test_basic(self):
        if self.headless:
            self.get_new_driver(headless=False)
        self.open("https://xkcd.com/353/")
        self.click('a[rel="license"]')
```
Now, even if your use ``--headless`` on the run command, the part after that will still be run without headless mode.

**Comment by createNull** [comment]
@mdmintz thanks, this works. 
Do you have any idea how could I call my `setUp()` func here?
Just for the record, I do have a setUp defined inside the test class.

Also, should I leave this issue open until it gets fixed?

**Comment by mdmintz** [comment]
@createNull Here's an example that calls setUp() again for your situation:
```python
from seleniumbase import BaseCase

class MyTestClass(BaseCase):

    def setUp(self):
        super(MyTestClass, self).setUp()
        self.open("https://xkcd.com/353/")

    def test_basic(self):
        if self.headless:
            self.get_new_driver(headless=False)
            self.setUp()
        self.click('a[rel="license"]')
```
Hopefully this now resolves your situation so that this issue can be closed.

**Comment by createNull** [comment]
@mdmintz I tried this and it doesn't work on my machine. 
Browser window opens and it just gets stuck there.

I have a `base_test_case.py` file that looks like this:
```python
class BaseTestCase(BaseCase):

    def setUp(self):
        super(BaseTestCase, self).setUp()
        self.maximize_window()
```

and `my_test.py` file:
```python
class MyTestClass(BaseTestCase):
    def setUp(self):
        super(TestWANP, self).setUp()
        self.open(URL)

    def test_basic(self):
        if self.headless:
            self.get_new_driver(headless=False)
            self.setUp()
        self.click('a[rel="license"]')
```

`pytest test_basic.py --headless` will hang both the browser and the terminal.
Note: after closing the browser window, the process doesn't exit. It just hangs

**Comment by mdmintz** [comment]
@createNull ``URL`` wasn't defined, but the following works for me (one file):
```python
from seleniumbase import BaseCase

class BaseTestCase(BaseCase):

    def setUp(self):
        super(BaseTestCase, self).setUp()
        self.maximize_window()

class MyTestClass(BaseTestCase):
    def setUp(self):
        super(MyTestClass, self).setUp()
        self.open("https://xkcd.com/353/")

    def test_basic(self):
        if self.headless:
            self.get_new_driver(headless=False)
            self.setUp()
        self.click('a[rel="license"]')
```

**Comment by createNull** [comment]
Yes, the URL is a class variable imported from another file. 
Ok, then it must have something to do with my configuration, many thanks for helping me solve this issue.

Cheers!
