### ISSUE TITLE
Element Id saved in html folder latest logs doen't match with real webpage

### ISSUE THREAD

**Issue by acpn** [seleniumbase/SeleniumBase#533]
Hello guys, 

I've doubt here and maybe a possible bug, i'm in the middle of an automation project from a website write in ADF, the HTML file it's very 'dirty' per say, and  i've facing an issue when a try to find and input element by ID, i just get the id from page HTML and seleniumbase tells me which the element isn't present. I start to  digging and compare the element and it is present in the webpage. 

Then i saw the log files and found an html from the page stored in the latest_logs folder, that's ok but when I search for my element i can't find it in the stored html file. So I start to digging more and find my element with other id:

real element id from page source: `pt1:contentAreaReg:0:tabrg3:2:pt1:mR:it4::content`
stored element id from the html file stored in latest_logs: `pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4::content`

The only difference it's in tabrg part, in the real page its **tabrg3:2** and in the stored file it's **tabrg2:2**.

When i change the element id for the stored one, my code works, so, i supose the locators are running in the stored file, that is correct?

And if it's correct I think there is a bug or something wrong when the html file it's stored.

Thanks,
Antonio

**Comment by mdmintz** [comment]
Hi @acpn , If SeleniumBase says the element isn't present, then you probably won't find that element in the page source html that's saved in the latest_logs folder. You may need to use a different CSS Selector.
Also, if I had a bit more information I could try debugging for you. What version of SeleniumBase are you using? And if it's a public-facing web page, what is the URL (and the Selector that you used)?

**Comment by acpn** [comment]
Hi @mdmintz , I think should be something with chrome, because I tried in firefox right now and match, the same ID i extract from firefox it's the same present in saved file in latest_logs folder.

I'm using seleniumbase 1.36.9 version.

The website I'ts not publicly available, sorry, but I will paste the peace of html from stored and original.

**Original (copied from html source page):**

`<span id="pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4" class="x24e x1u">
    <input id="**pt1:contentAreaReg:0:tabrg3:2:pt1:mR:it4::content**" 
       name="pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4" style="text-align: right;text- 
      align:left;width:auto;" class="x25" size="20" maxlength="20" type="text"><label 
       for="pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4::content" class="x9w">Varejo Sugerido</label></span>` 

**Saved in latest_logs folder:**

`<span id="pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4" class="p_AFFocusTarget x24e x1u"><input 
    id="**pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4::content**" 
   name="pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4" style="text-align: right;text- 
   align:left;width:auto;" class="x25" size="20" maxlength="20" type="text" /><label 
   for="pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4::content" class="x9w">Suggested Retail</label></span>`

And this is my code to find that element:

` self.update_text('pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4::content', '1000\n', by=By.ID)`

My problem happens when I use the element id extracted directly from the page source, in this case the page source is: **pt1:contentAreaReg:0:tabrg3:2:pt1:mR:it4::content**. However, when i use the id from stored folder: **pt1:contentAreaReg:0:tabrg2:2:pt1:mR:it4::content** works perfectly.

And a curious thing as I wrote before  is if I get the same peace of html in firefox browser match exactly with the stored file in latest_logs folder.

So, I think it's not a bug, I check with my team and they said which doesn't have deploy today to change any of the element id's. Anyway, doesn't waste your time trying to debug this, because I think was something on my side ehehhe.

Thank you very much for the support, and i'm enjoying very much seleniumbase so far, especially the way SB handle with waits.

Cheers,

**Comment by mdmintz** [comment]
@acpn The web page is interesting because it looks like there's dynamically-generated content. One version has "Suggested Retail" shown where in the other version it's in Portuguese: "Varejo Sugerido". There's probably some Javascript changing the HTML, as it's clearly the same page with some dynamic content.
You may want to use a more adaptable selector, such as:
``'[id*="pt1:contentAreaReg:0:tabrg2:2"]'`` , where the ID doesn't need to be an exact match, but it will still locate the selector. (Now it's in CSS Selector format, which is the default Selector)

Glad to hear you're enjoying SeleniumBase!

**Comment by acpn** [comment]
Thank you @mdmintz ,
I'll try your suggestion.

Thanks!
