### ISSUE TITLE
`--cap-file=CAP_FILE` only works with tests that run on Selenium Grid

### ISSUE THREAD

**Issue by aklajnert** [seleniumbase/SeleniumBase#535]
Currently, SeleniumBase has `cap_file` option, that doesn't seem to work.

What I want to achieve is to add `{'goog:loggingPrefs': {'browser': 'ALL'}}`. Unfortunately, the only way I achieved that is by ugly monkey-patching around the `webdriver`.

I've tried to set `cap_file` to file with something like below, but it didn't work. Actually nothing happened. There was no difference in capabilities with or without the file.

My example `cap_file`:
```python
capabilities  = desired_cap = desired_capabilities = {'goog:loggingPrefs': {'browser': 'ALL'}}
```

I've debugged the sources and it seems that the `get_local_driver()` method doesn't use the file at all.

**Comment by tcw0nw** [comment]
same question
`capabilities = {
                'browserName': 'chrome',
                'tz': 'Asia/Harbin',
                'build': "build_%s" % time.strftime("%Y-%m-%d_%H-%M-%S", time.gmtime()),
                'name': "build_%s" % time.strftime("%Y-%m-%d_%H-%M-%S", time.gmtime()),
                'idleTimeout': 90,
                }`

`node = <_ast.BinOp object at 0x10719c890>

    def _convert_num(node):
        if isinstance(node, Constant):
            if isinstance(node.value, (int, float, complex)):
                return node.value
        elif isinstance(node, Num):
            return node.n
>       raise ValueError('malformed node or string: ' + repr(node))
E       ValueError: malformed node or string: <_ast.BinOp object at 0x10719c890>`

**Comment by mdmintz** [comment]
@aklajnert @tcw0nw What run commands are you using? If running locally, you must use a Selenium Grid, and you can start one up with two lines on the command line:
```bash
seleniumbase grid-hub start
seleniumbase grid-node start
```
Now you can run something like this from the ``examples/`` folder:
```bash
pytest basic_test.py --server=127.0.0.1 --cap-file=capabilities/sample_cap_file_BS.py
=============================================== test session starts ================================================
platform darwin -- Python 3.7.0, pytest-5.3.5, py-1.8.0, pluggy-0.13.1
rootdir: /Users/michael/github/SeleniumBase, inifile: pytest.ini
plugins: timeout-1.3.4, html-2.0.1, rerunfailures-9.0, xdist-1.31.0, ordering-0.6, forked-1.1.3, metadata-1.8.0, cov-2.8.1, seleniumbase-1.36.9
collected 1 item                                                                                                   

basic_test.py Starting ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5) on port 44953
Only local connections are allowed.
.

================================================ 1 passed in 5.20s
```

**Comment by aklajnert** [comment]
@mdmintz why the selenium grid is required here? The local driver should also have the ability to override the capabilities (which I did with an ugly hack).  
Maybe allowing to specify a JSON file with capability overrides would be a good idea?  

Here's my hack in case someone needs it:  
```python
from selenium.webdriver.chrome.options import Options


to_capabilities = Options.to_capabilities


def new_to_capabilities(self):
    capabilities = to_capabilities(self)
    capabilities["goog:loggingPrefs"] = {"browser": "ALL"}
    return capabilities


Options.to_capabilities = new_to_capabilities
```

**Comment by tcw0nw** [comment]
> @mdmintz why the selenium grid is required here? The local driver should also have the ability to override the capabilities (which I did with an ugly hack).
> Maybe allowing to specify a JSON file with capability overrides would be a good idea?
> 
> Here's my hack in case someone needs it:
> 
> ```python
> from selenium.webdriver.chrome.options import Options
> 
> 
> to_capabilities = Options.to_capabilities
> 
> 
> def new_to_capabilities(self):
>     capabilities = to_capabilities(self)
>     capabilities["goog:loggingPrefs"] = {"browser": "ALL"}
>     return capabilities
> 
> 
> Options.to_capabilities = new_to_capabilities
> ```
> 
> I would expect `SeleniumBase` to just pass `desired_capabilities` to the `WebDriver` constructor, which does the `update()` on capabilities.

Can you see the complete code？

**Comment by aklajnert** [comment]
@tcw0nw what do you mean?

**Comment by mdmintz** [comment]
@aklajnert 
desired_capabilities is natively built into ``webdriver.Remote()``, example:
```python
webdriver.Remote(command_executor, desired_capabilities, browser_profile)
```
But it is not built natively into ``webdriver.Chrome()``, ``webdriver.Firefox()``, etc...
And if you try adding it, you may override important SeleniumBase options, which you can already set from the command line. But there are no issues with using ``webdriver.Remote()``, and that's where the capabilities come in. But Remote does require a Selenium Grid, and that's not an issue with SeleniumBase's built-in Grid management tools, such as ``seleniumbase grid-hub start`` and ``seleniumbase grid-node start``.

**Comment by aklajnert** [comment]
@mdmintz are you sure that didn't change? Here's a fragment of my `site-packages\selenium\webdriver\chrome\webdriver.py` file:  
```python
class WebDriver(RemoteWebDriver):
    """
    Controls the ChromeDriver and allows you to drive the browser.

    You will need to download the ChromeDriver executable from
    http://chromedriver.storage.googleapis.com/index.html
    """

    def __init__(self, executable_path="chromedriver", port=0,
                 options=None, service_args=None,
                 desired_capabilities=None, service_log_path=None,
                 chrome_options=None, keep_alive=True):
        ...
```

As you see, the `__init__()` method has `desired_capabilities` option. I'm able to modify it (using the hack I shown above), the capabilities are set properly. And I'm running my tests with simple `pytest` command.

**Comment by mdmintz** [comment]
@aklajnert Thank you. I'll look into it more and see what I can do. That does appear to be using RemoteWebDriver, and if you've explored Selenium 4 at all (beta is available), you'll see that ``DeprecationWarning: executable_path has been deprecated, please pass in a Service object`` would result from using that, and I'm already looking ahead to the future for a seamless transition when it arrives. Given that I'm probably going to be changing this code (from browser_launcher.py) when Selenium 4 arrives, and given that they are still finalizing changes, I'm better off waiting until that's out (hopefully soon) so that I don't need to be making all these changes twice.

**Comment by aklajnert** [comment]
@mdmintz got it, that's reasonable. For now, I'm good with the ugly monkey-patching.

**Comment by mdmintz** [comment]
I changed the title since this works correctly when using a remote Selenium Grid such as Sauce Labs or Browserstack.
It'll also work if you use a local Selenium grid:
```bash
seleniumbase grid-hub start
seleniumbase grid-node start
pytest MY_TEST.py --server="127.0.0.1" --browser=remote --cap-file=CAP_FILE
```

**Comment by q30** [comment]
Can self.get_new_driver be used for this purpose? It seems to allow you to provide cap_file in its params. However I wasn't able to get it to work correctly myself. It opens a new browser for me but my test doesn't make use of it and continue to open another browser instance for running tests.

**Comment by mdmintz** [comment]
@q30 The cap_file still needs a Selenium Grid to process the desired capabilities right now. Changing this is on hold until Selenium 4 is officially released because that's going to simplify a lot of things related to this. Right now, SeleniumBase includes multiple command-line options that will let you set things without the cap file. But if you need the cap_file (which was orginally made to make it easier to use remote Selenium Grids like BrowserStack and Sauce Labs) then you can still easily spin up your own Selenium Grid with: ``seleniumbase grid-hub start`` and ``seleniumbase grid-node start``.

**Comment by q30** [comment]
Thank you @mdmintz! This helps.

**Comment by mdmintz** [comment]
Given that Selenium 4 is making changes to the Grid, and given that ``--cap-file=CAP_FILE`` was only meant to be used with the Selenium Grid since SeleniumBase sets its own custom options from the command line, I'm going to mark this ticket as closed.
