### ISSUE TITLE
Using --cap_file threw an exception

### ISSUE THREAD

**Issue by tcw0nw** [seleniumbase/SeleniumBase#538]
code:

`s = "abc"`
capabilities = {
                'browserName': 'chrome',
                'tz': 'Asia/Harbin',
                'build': s,
                'name': "build_" ,
                'idleTimeout': 90,         }

error：
`_____________________________________________________________________________________________________ MyTestClass.test_open_baidu _____________________________________________________________________________________________________
venv/lib/python3.7/site-packages/seleniumbase/fixtures/base_case.py:4518: in setUp
    d_p_r=self.__device_pixel_ratio)
venv/lib/python3.7/site-packages/seleniumbase/fixtures/base_case.py:1564: in get_new_driver
    device_pixel_ratio=d_p_r)
venv/lib/python3.7/site-packages/seleniumbase/core/browser_launcher.py:378: in get_driver
    mobile_emulator, device_width, device_height, device_pixel_ratio)
venv/lib/python3.7/site-packages/seleniumbase/core/browser_launcher.py:399: in get_remote_driver
    desired_caps = capabilities_parser.get_desired_capabilities(cap_file)
venv/lib/python3.7/site-packages/seleniumbase/core/capabilities_parser.py:206: in get_desired_capabilities
    capabilities = _parse_py_file(cap_file)
venv/lib/python3.7/site-packages/seleniumbase/core/capabilities_parser.py:190: in _parse_py_file
    capabilities = _analyze_ast(all_code)
venv/lib/python3.7/site-packages/seleniumbase/core/capabilities_parser.py:22: in _analyze_ast
    return ast.literal_eval(contents)
/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py:91: in literal_eval
    return _convert(node_or_string)
/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py:79: in _convert
    map(_convert, node.values)))
/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py:90: in _convert
    return _convert_signed_num(node)
/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py:63: in _convert_signed_num
    return _convert_num(node)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

node = <_ast.Call object at 0x107bfd950>

    def _convert_num(node):
        if isinstance(node, Constant):
            if isinstance(node.value, (int, float, complex)):
                return node.value
        elif isinstance(node, Num):
            return node.n
>       raise ValueError('malformed node or string: ' + repr(node))
E       ValueError: malformed node or string: <_ast.Call object at 0x107bfd950>
----------------

**Comment by symonk** [comment]
@tcw0nw the format of your capabilities looks incorrect?

**Comment by tcw0nw** [comment]
@mdmintz Hope to get help。

**Comment by tcw0nw** [comment]
> @tcw0nw the format of your capabilities looks incorrect?

What is wrong?

**Comment by mdmintz** [comment]
@tcw0nw Use the following:
```python
capabilities = {
'browserName': 'chrome',
'tz': 'Asia/Harbin',
'build': "abc",
'name': "build_" ,
'idleTimeout': 90,
}
```
It only parses what's inside the ``capabilities = {*}``. Everything else is ignored. It's not using regular Python expression evaluation.

**Comment by tcw0nw** [comment]
> @tcw0nw Use the following:
> 
> ```python
> capabilities = {
> 'browserName': 'chrome',
> 'tz': 'Asia/Harbin',
> 'build': "abc",
> 'name': "build_" ,
> 'idleTimeout': 90,
> }
> ```
> 
> It only parses what's inside the `capabilities = {*}`. Everything else is ignored. It's not using regular Python expression evaluation.

I want the value of 'name' in capabilities to be generated based on the test case name rather than a fixed value. How to modify?

**Comment by mdmintz** [comment]
@tcw0nw Here's the parse file: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/capabilities_parser.py
Not sure how to do it without using Python's ``eval()``, which isn't safe depending on the input. It's using the ``ast.literal_eval()`` for parsing, but if that fails, there are regular expressions.

**Comment by tcw0nw** [comment]
> @tcw0nw Here's the parse file: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/capabilities_parser.py
> Not sure how to do it without using Python's `eval()`, which isn't safe depending on the input. It's using the `ast.literal_eval()` for parsing, but if that fails, there are regular expressions.

I want the value of 'name' and 'build' in capabilities to be generated based on the test case name rather than a fixed value。

**Comment by mdmintz** [comment]
@tcw0nw That would be a feature request. I'd have to build in the functionality. Would the name be the full test name, such as ``my_first_test.py::MyTestClass::test_basic`` or just the short version ``test_basic``? I'll need specifics. You won't be able to set that from the cap-file, but I can add a command-line option that appends to the capabilities set there based on the test being run. Also, is the build name something that you want to specify manually on the command line?

**Comment by tcw0nw** [comment]
> @tcw0nw That would be a feature request. I'd have to build in the functionality. Would the name be the full test name, such as `my_first_test.py::MyTestClass::test_basic` or just the short version `test_basic`? I'll need specifics. You won't be able to set that from the cap-file, but I can add a command-line option that appends to the capabilities set there based on the test being run. Also, is the build name something that you want to specify manually on the command line?

get testcase __name__ or __doc__。need 'name' and 'build' on the command line。thanks。

**Comment by tcw0nw** [comment]
> > @tcw0nw That would be a feature request. I'd have to build in the functionality. Would the name be the full test name, such as `my_first_test.py::MyTestClass::test_basic` or just the short version `test_basic`? I'll need specifics. You won't be able to set that from the cap-file, but I can add a command-line option that appends to the capabilities set there based on the test being run. Also, is the build name something that you want to specify manually on the command line?
> 
> get testcase `__name__` or `__doc__`。need 'name' and 'build' on the command line。thanks

**Comment by mdmintz** [comment]
@tcw0nw See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.37.5

**Comment by tcw0nw** [comment]
> @tcw0nw See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.37.5
@mdmintz {"browserName": "chrome", "name": "test1"} --I want 'name' to be a variable instead of fixed.

**Comment by tcw0nw** [comment]
@mdmintz ` {"browserName": "chrome", "name": "test1"}` I want 'name' to be a variable instead of fixed.

**Comment by mdmintz** [comment]
@tcw0nw Fixed as part of https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.37.8

If you pass ``"*"`` into the ``"name"`` field of ``--cap-string``, the name will become the test identifier. Example:
```bash
pytest test_swag_labs.py --cap-string='{"browserName":"chrome","name":"*"}' --server="127.0.0.1" --browser=chrome
```
Example name: ``"my_first_test.MyTestClass.test_basic"``
(You can also pass it into a cap file)

See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/capabilities/ReadMe.md for complete details.

**Comment by tcw0nw** [comment]
> @tcw0nw Fixed as part of https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.37.8
> 
> If you pass `"*"` into the `"name"` field of `--cap-string`, the name will become the test identifier. Example:
> 
> ```shell
> pytest test_swag_labs.py --cap-string='{"browserName":"chrome","name":"*"}' --server="127.0.0.1" --browser=chrome
> ```
> 
> Example name: `"my_first_test.MyTestClass.test_basic"`
> (You can also pass it into a cap file)
> 
> See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/capabilities/ReadMe.md for complete details.

Thank you. Solved my problem。
