### ISSUE TITLE
get_attribute method cannot get the value,but when I use selenium,it works.

### ISSUE THREAD

**Issue by Melissa-mao** [seleniumbase/SeleniumBase#551]
Hi, i need to get an input value,just like this:
![image](https://user-images.githubusercontent.com/39981474/80200981-03f63d00-8656-11ea-9434-6c104c01d6f7.png)
When i use selenium, it works. I can use
![image](https://user-images.githubusercontent.com/39981474/80201286-7b2bd100-8656-11ea-810c-d32e81c14ee3.png)
I can get value=adminnd20200424180307;
But when I use seleniumBase to get this value, it dosen't work.
![image](https://user-images.githubusercontent.com/39981474/80202862-d65ec300-8658-11ea-8c3d-8a98e8d957cd.png)
![image](https://user-images.githubusercontent.com/39981474/80202887-deb6fe00-8658-11ea-9aee-e8438a13f081.png)
I consider that it's the problem of driver, it also send request to brower, and the response also has value, but it's an empty string.

**Comment by mdmintz** [comment]
The ``value`` attribute is not that same as the text that appears in a text field. It would be something like ``value="VALUE"`` in the html, and I don't see that from your screenshot. Is this on a public-facing URL? I need more info to debug. The selectors that you used in your examples are different.

**Comment by Melissa-mao** [comment]
Sorry, It's not a public-facing URL. Actually this value attribute cannot be seen on the elements, but when I use selenium library, I can get value attribute by the get_attribute method. So it is a really hard problem. 
PS: The web language is vue.

**Comment by mdmintz** [comment]
SeleniumBase is mainly Selenium under-the-hood, so if you have it working with raw Selenium successfully, then is sounds like your issue is resolved. Let me know if you have any more issues with this; otherwise I'll close this issue.

**Comment by Melissa-mao** [comment]
OK, I don't have any more question.
