### ISSUE TITLE
 Can you add a method to compare the pictures?

### ISSUE THREAD

**Issue by Likangkang08** [seleniumbase/SeleniumBase#557]
I think we can try to use python's opencv to compare the pictures. Selenium is only responsible for screenshots.

![image](https://user-images.githubusercontent.com/22090651/80693751-1238d300-8b06-11ea-956b-338c98bf53fe.png)

For example, before you start, put the original picture in the base file, take a screenshot at runtime, and then use python to write a method for comparison. If the same returns true, it returns false. Then mark the different places.
![image](https://user-images.githubusercontent.com/22090651/80693791-1e249500-8b06-11ea-8c78-bd04f0f813bd.png)

**Comment by Likangkang08** [comment]
![image](https://user-images.githubusercontent.com/22090651/80693902-4f9d6080-8b06-11ea-8091-a3cbb432d2a8.png)

**Comment by mdmintz** [comment]
@Likangkang08 I'd take a look at the ReadMe here: https://github.com/seleniumbase/SeleniumBase/tree/master/examples/visual_testing
Layout comparison is more effective than the direct image comparison for catching regressions. But even if you still want to compare images, it's easy to do that with Python library calls from within tests by importing any additional libraries that you need.
