### ISSUE TITLE
How can I reuse a code

### ISSUE THREAD

**Issue by filipe-guerra** [seleniumbase/SeleniumBase#559]
I have an login step, and I want to reuse that code in many tests. I like use "self.open" and "self.click" in a file that not are a test function, is that possible? Thanks.

**Comment by mdmintz** [comment]
@filipe-guerra Have you seen https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_swag_labs.py ?
There's also a boilerplate for adding login and other useful class methods: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py
And unrelated, here's an example of a SeleniumBase translation in Portuguese if that helps: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/translations/portuguese_test_1.py

**Comment by mdmintz** [comment]
@filipe-guerra As for using SeleniumBase methods outside of a test function: Due to pytest auto-discovery requirements, test methods must start with ``test_``, so methods will need to get called from that.

**Comment by filipe-guerra** [comment]
Cool! Thanks. I have a project using pytest and pytest-bdd. Your project is very nice. I'am trying to adapt my project using your framework.

**Comment by mdmintz** [comment]
@filipe-guerra Great! If you ever want to present SeleniumBase at a Belo Horizonte Python Meetup, let me know and I can try to help. https://www.meetup.com/PythonMG/ Since all Meetups are remote-only right now, it would be easy for me to assist (except for the part with speaking Portuguese).

**Comment by filipe-guerra** [comment]
Oh, thanks. That's nice. Hope I can help you to improve the project in the future. You have a group to discuss the future of project? Or you work alone? Is there any way to use BDD with SeleniumBase? I started a project to see print images tests diff , but I think using deep learning is a better way to do that and I have to study more to improve it.

**Comment by mdmintz** [comment]
@filipe-guerra There's the Gitter room for chat: https://gitter.im/seleniumbase/SeleniumBase , which can be used for both group messages and private messages. SeleniumBase is just me right now, but sometimes other people submit pull requests.
I'm not sure about BDD for Web UI tests. Normally Web UI tests are best suited for regression testing
