### ISSUE TITLE
Time limit will not end the test if the page didn't load

### ISSUE THREAD

**Issue by createNull** [seleniumbase/SeleniumBase#560]
Hi @mdmintz,

I reported an issue before with a webpage having a big load time and the conclusion was that it there was nothing to do from a seleniumbase perspective since any action on the page starts after the page is loaded.

Fair enough.

But, I see there is an argument that you can pass `time_limit`, so your tests can end if it takes longer than the given value. 
Isn't this supposed to fail my test in this case? 
Apparently, it doesn't.

The issue is that the test will fail with the time limit error after the page is loaded.

**Comment by mdmintz** [comment]
@createNull The ``--time-limit=SECONDS`` was meant to be a thead-safe alternate to ``pytest-timeout``, which would end a test run without closing WebDriver browser windows that were still open. To make ``time-limit`` work, it would be called from methods such as ``self.wait_for_element()``, ``self.click()``, etc, and if the time limit was exceeded while waiting for the element to be visible, then the test would end and fail (and properly close out WebDriver browser windows). Most SeleniumBase methods that wait for something to happen now check if the test time-limit has been exceeded during the method call. If the web page itself is taking too long to load, then WebDriver hasn't yet handed over control of the web browser to SeleniumBase yet, and so the framework can't check if the time-limit has been exceeded yet.

**Comment by createNull** [comment]
Ok, so my use case is pretty basic: I just want to check that the status code of the page is not 404, that's it.
You're telling me that basically there is no way I can do that fast, when the loading time of the page is larger than a couple of seconds, right?
I do believe implementing a method for stopping tests that run after a certain amount of time could be very useful for this framework since there is absolutely no guarantee you won't end up in a scenario with hanging processes.

**Comment by mdmintz** [comment]
@createNull There are already SeleniumBase methods available for checking for broken links before attempting to navigate to them directly:
```python
self.get_link_status_code(URL_LINK, allow_redirects=False, timeout=5)
self.assert_link_status_code_is_not_404(URL_LINK)
self.assert_no_404_errors()
```
Don't check if a page is broken by navigating to it directly, as WebDriver will try really hard to load the page first, which can take time. Instead, use one of the the above methods to check the page from a different page.

**Comment by createNull** [comment]
@mdmintz I'm already aware of these methods, but I can't use them since in my tests I don't know the URL.
Basically, I'm clicking on a link and I just want to make sure that everything that it's behind that link is not a 404 without caring about the URL.
It's not only this issue and I still consider that a safe mechanism like a global timeout to exit from the WebDriver is necessary.
I'll checkout to see if pytest has something like this and maybe implement it myself.
Thanks for the help!

**Comment by mdmintz** [comment]
@createNull Sounds good. Just note that you can always get the URL Link of an element before you click on it. The ``get_attribute()`` method with the ``href`` attribute will do that for you. Example:
```python
self.get_attribute('a[rel="next"]', "href")
```
