### ISSUE TITLE
self.double_click('select'),will close chrome

### ISSUE THREAD

**Issue by zhonghai9967** [seleniumbase/SeleniumBase#568]
self.click is True.
self.hover_and_double_click is none.
self.double_click,chrome is close.
====
windows 10
python 3.7.5
pytest 3.7.5
seleniumbase 1.37.14
chrome 68.0.3440.75

**Comment by zhonghai9967** [comment]
click 正常；self.hover_and_double_click 无效（没任何反应）；
如果 使用self.double_click，chrome浏览器会关闭。
 selenium.common.exceptions.WebDriverException: Message: (Session infochrome=81.0.4044.129)
c:\python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py:242: WebDriverException

**Comment by zhonghai9967** [comment]
I install chrome --=81.0.4044.138,the Error still present。
 self.double_click('table>tbody>tr>td:nth-child(1)>div')#双击选中,会退出,

test_qianyue.py:102:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\python37\lib\site-packages\seleniumbase\fixtures\base_case.py:215: in double_click
    actions.perform()
c:\python37\lib\site-packages\selenium\webdriver\common\action_chains.py:80: in perform
    self.w3c_actions.perform()
c:\python37\lib\site-packages\selenium\webdriver\common\actions\action_builder.py:76: in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
c:\python37\lib\site-packages\selenium\webdriver\remote\webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001F66FCD2508>
response = {'status': 404, 'value': '{"value":{"error":"unknown command","message":"(Session infochrome=81.0.4044.138)","stacktra...\n\\tRtlGetAppContainerNamedObjectPath [0x76F07C24+228]\\n\\tRtlGetAppContainerNamedObjectPath [0x76F07BF4+180]\\n"}}'}

selenium.common.exceptions.WebDriverException: Message: (Session infochrome=81.0.4044.138)

**Comment by zhonghai9967** [comment]
thank you for helping me.

**Comment by mdmintz** [comment]
@zhonghai9967 when I run https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_demo_site.py and swap out ``self.hover_and_click()`` with ``self.hover_and_double_click()``, it still works with no errors. Can you share the test that you're running so that I can try to reproduce your issue?

**Comment by mdmintz** [comment]
@zhonghai9967 Try https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_double_click.py It has double_click in it. Does it give you an error when you run it?

**Comment by zhonghai9967** [comment]
I operate in the company's intranet, and you cannot reproduce my problem.

"self.hover_and_double_click ()", in demo mode, you can see the double-clicked element, but it has no effect.

"self.double_click ()", run to this command, chrome closes and gives an error message.

This is my command:

self.double_click ('table> tbody> tr> td: nth-child (1)> div') # Confirm that the element is visible

This is the error message:
>           self.double_click('table>tbody>tr>td:nth-child(1)>div')#double_click
test_qianyue.py:102:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\python37\lib\site-packages\seleniumbase\fixtures\base_case.py:215: in double_click
    actions.perform()
c:\python37\lib\site-packages\selenium\webdriver\common\action_chains.py:80: in perform
    self.w3c_actions.perform()
c:\python37\lib\site-packages\selenium\webdriver\common\actions\action_builder.py:76: in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
c:\python37\lib\site-packages\selenium\webdriver\remote\webdriver.py:321: in execute
    self.error_handler.check_response(response)

**Comment by mdmintz** [comment]
That isn't enough information for me to reproduce and solve your problem. The Selector isn't enough - I'd need a public-facing website to test it on. Do you get errors when you run https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_double_click.py  , which uses double-click? This issue could be related to the specific website that you're using.

**Comment by zhonghai9967** [comment]
I changed to firefox, and there is a problem of closing the browsing when double-clicking。
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_double_click.py，
It is normal to run this test.

**Comment by zhonghai9967** [comment]
Is there any way to solve it? I will try IE after a while。

**Comment by mdmintz** [comment]
@zhonghai9967 This is what I get after I run it on firefox:
```bash
pytest test_double_click.py --browser=firefox
================================================ test session starts =================================================
platform darwin -- Python 3.7.0, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/michael/github/SeleniumBase, inifile: pytest.ini
plugins: html-2.0.1, rerunfailures-9.0, metadata-1.9.0, ordering-0.6, forked-1.1.3, xdist-1.32.0, cov-2.8.1, seleniumbase-1.38.0
collected 2 items                                                                                                    

test_double_click.py ..

================================================= 2 passed in 28.58s =================================================
```

**Comment by mdmintz** [comment]
I'm using geckodriver v0.26.0

**Comment by mdmintz** [comment]
I ran it again successfully on firefox
```bash
pytest test_double_click.py --browser=firefox
================================================ test session starts =================================================
platform darwin -- Python 3.7.0, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/michael/github/SeleniumBase, inifile: pytest.ini
plugins: html-2.0.1, rerunfailures-9.0, metadata-1.9.0, ordering-0.6, forked-1.1.3, xdist-1.32.0, cov-2.8.1, seleniumbase-1.38.0
collected 2 items                                                                                                    

test_double_click.py ..

================================================= 2 passed in 19.58s =================================================
```

**Comment by mdmintz** [comment]
I'm using a Mac. This might be an issue on Windows. I don't have a Windows machine with me at this moment, but I can get it later and check there.

**Comment by zhonghai9967** [comment]
I use IE instead and double-clicked successfully. (Double-click an element to automatically select a function and exit this frame)
Thank you!
IE version: 11.836.18362.0
IEDriverServer.exe version: IEDriverServer_Win32_3.9.0
Still want to find out why the chrome firefox double-click caused the browser to be closed.

**Comment by zhonghai9967** [comment]
Edge version 79 can also double-click normally.

**Comment by zhonghai9967** [comment]
Sorry, wrongly answered a question:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_double_click.py
I can't access the website in this example, so I'm not sure if there will be an error at runtime.
This is China, there is a wall
It is strongly recommended that you check Seleniumbase's “Double-click“ method again, and consider some possible problems.

**Comment by mdmintz** [comment]
@zhonghai9967 Fixed in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.38.2

**Comment by zhonghai9967** [comment]
thanks
thanks
thanks!👍



---Original---
