### ISSUE TITLE
Feature Suggetion for rest api automation

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#570]
Hello.
i am intrested to used this framework with rest api based test automation.

so if you have something related that or need to develop for that ?

Thanks

**Comment by mdmintz** [comment]
Our focus right now is Web/Mobile UI testing and automation. There are lots of frameworks out there that already exist for rest api testing, such as Postman, which is very popular.

**Comment by teamdts** [comment]
yes thanks.
