### ISSUE TITLE
not able to pass --mobile="mobile device name"

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#575]
hello
here i have attached device list screenshot.
so how i can give perticular  device selection using pytest with saleniumbase.
i am trying to do someting like below command
`
pipenv run pytest my_testcases.py --headed --browser=chrome --mobile="iPhone X"
`

getting below error while executing above command
```
pytest: error: argument --mobile/--mobile-emulator/--mobile_emulator: ignored explicit argument 'iPhone X'
```

Here some one did using programatically but it is useful if something direct argument based
`
 https://gist.github.com/devinmancuso/ec8ae08fa73402e45bf1
`
![1](https://user-images.githubusercontent.com/63253499/82427023-2ee17e80-9aa6-11ea-83f0-993e0c4f09de.png)

**Comment by mdmintz** [comment]
@teamdts Please reread the docs on Mobile Device Testing: https://seleniumbase.io/help_docs/mobile_testing/
Once you enable mobile mode with ``--mobile``, you then set the device by specifying the user agent and the device metrics: Example:
```bash
--mobile --agent="Mozilla/5.0 (Linux; Android 9; Pixel 3 XL)" --metrics="411,731,3"``
```
The help doc shows you where to get the user agent string and device metrics from.

**Comment by teamdts** [comment]
@mdmintz  Ok. Thanks
