### ISSUE TITLE
firefox headless mode by argument not working

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#585]
hello
i want to test using all possible browser with headless mode.
but when i am trung to do with `--browser=firefox --headless` argument then it is not working in headless mode.

for that need to set environment variable like `export MOZ_HEADLESS=1` 

so is there any argument based option to do that ?

Thanks

**Comment by mdmintz** [comment]
Headless mode on Firefox is working for me on the latest version of SeleniumBase. Please paste a stack trace showing your run command and stack trace output.

**Comment by teamdts** [comment]
```
pipenv run pytest my_test.py --alluredir="reports1" --browser=firefox --headless
Loading .env environment variables…
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /data/Projects/giggso/Automation/Iotium, inifile: pytest.ini
plugins: ordering-0.6, rerunfailures-9.0, metadata-1.8.0, allure-pytest-2.8.13, xdist-1.31.0, forked-1.1.3, cov-2.8.1, parallel-0.1.0, seleniumbase-1.37.2, html-2.0.1
collected 19 items                                                                                                                                                                                          ```

**Comment by mdmintz** [comment]
@teamdts There's no stack trace there. You only have a print statement in there after you ran your tests. I need to see a stack trace / error message to determine issues (if any). Try headless Firefox with an existing SeleniumBase test from the ``examples/`` folder. And upgrade to the latest version of SeleniumBase. It might also be something with your pipenv environment.

**Comment by u-phoria** [comment]
`--firefox --headless` did not work for me on Debian, even after #767 / #768 (am on v1.64.1). The code doesn't set the `-headless` firefox arg for Linux (`seleniumbase/core/browser_launcher.py`).

Adding an explicit Firefox argument worked for me:
```
 --firefox --headless --firefox-arg="--headless"
```

**Comment by mdmintz** [comment]
@u-phoria It would work if you have xvfb installed on your Linux machine, as then it would use the virtual display. But I'll see what happens if I add ``--headless`` as the default for headless mode on Linux, and if there are no issues, it'll be added as part of the next release.

**Comment by u-phoria** [comment]
Fab, it's nice not to depend on xvfb.

Thanks for this Michael, and for all your work on the project 🙏

**Comment by mdmintz** [comment]
@u-phoria In https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.65.0, ``--headless`` will always use the browser's built-in headless mode by default now for Firefox (Chrome was already doing that). Additionally, there's now a ``--xvfb`` option that will use the Xvfb virtual display if available. And this is a special release... it comes with a video!

**Comment by mdmintz** [comment]
Well, that Firefox change broke things for me, so I reverted it back to the way it was with v1.64.1 in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.65.1

**Comment by u-phoria** [comment]
No worries, and thanks for trying it out. The firefox-args workaround is fine (for me at least).
