### ISSUE TITLE
Feature: detect locator type by the value

### ISSUE THREAD

**Issue by aklajnert** [seleniumbase/SeleniumBase#595]
In my use case, I need to mix the default `CSS_SELECTOR` locators with `XPATH`. Most of the locators are reused between test so I keep them as constants, mostly in different files.
This is a bit annoying when I need to use them, as I need to remember to set valid `by` for the `XPATH` locators. 

The types are easily distinguishable by looking at the value. I think it would make sense for the framework to figure it out automatically, and fallback to `CSS_SELECTOR` if the value is not recognized.

**Comment by mdmintz** [comment]
@aklajnert This feature has existed for 4 years already. XPath is used by default if the selector starts with ``/``, ``./``, or ``(``.

**Comment by aklajnert** [comment]
@mdmintz - now I see that you're right. I was testing that today and I had the impression that it requires `by` argument, but this was probably an error in my tests. The XPATH actually works without specifying `by`. My mistake.
