### ISSUE TITLE
proxy pass using hostname

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#602]
pytest in i am passing argument like
pipenv run pytest . -m 'basic' --browser=chrome --proxy=172.19.0.2:8090
so
--proxy=IP_ADDRESS:PORT
is only allowing to use ip address.

i using docker so in proxy we want to pass hostname instead of ip.
because we don't know ip address .
so my expectation is it will accept hostname also.
--proxy=HOSTNAME:PORT

Thanks

**Comment by mdmintz** [comment]
@teamdts You can also pass a hostname instead of an ip address to proxy. Both work, and I use that regularly.
