### ISSUE TITLE
How to prevent the browser from loading pictures？

### ISSUE THREAD

**Issue by guke1991** [seleniumbase/SeleniumBase#615]
i want improve test speed.

```
chrome_options = webdriver.ChromeOptions()
prefs = {"profile.managed_default_content_settings.images": 2}
chrome_options.add_experimental_option("prefs", prefs)
self.driver = webdriver.Chrome(chrome_options=chrome_options)
```

this code can do it,but will open a new chrome.
how to make it in only one chrome?

**Comment by mdmintz** [comment]
@guke1991 Feature added to v1.42.7
https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.42.7
Usage: ``--block-images``

**Comment by guke1991** [comment]
@mdmintz  Thank you very much. You are a great developer. I love you.😘
