### ISSUE TITLE
How do I add a custom Chrome command-line argument?

### ISSUE THREAD

**Issue by mildmojo** [seleniumbase/SeleniumBase#619]
I have a Python project using SeleniumBase 1.34.11 that's running inside a docker container, and I'm forwarding my pytest run to the X server on my Linux host. Unfortunately, Chrome has a bug that makes it render a blank window to my host X server (nothing, no UI at all).

In the [Chromium project bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1048186#c3), one commenter suggests starting Chrome with `--use-gl=swiftshader` to enable software rendering. This works for me; I can run `google-chrome --use-gl=swiftshader`, and I get a regular Chome window with full UI.

I'd like to send that argument to Chrome via SeleniumBase. I've looked through the documentation and the issues in this repo, but I don't see any mention or examples of custom Chrome options. In the codebase, I see where the browser launcher's [_set_chrome_options](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/browser_launcher.py#L131) gets a ChromeOptions object and sets arguments on it, but it seems like it only understands hardcoded arguments.

Is there a way to add a custom Chrome command-line argument?

**Comment by mdmintz** [comment]
@mildmojo I'll create a new release of SeleniumBase with that option enabled. I don't see why it would hurt to have it on all the time.

**Comment by mdmintz** [comment]
@mildmojo I added the Chrome option you wanted in version 1.42.9
https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.42.9
``--use-gl=swiftshader``

**Comment by mdmintz** [comment]
Chrome options are all set here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/browser_launcher.py
From the command line, you can alter some of them with pytest arguments, which are defined here: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/plugins/pytest_plugin.py

**Comment by mildmojo** [comment]
That's great! Thank you for the lightning-quick feature add! :tada:

I'll see about upgrading my project on Monday.

**Comment by mildmojo** [comment]
One note, in the bug report I linked above, the commenter saw a performance penalty in their case. It might adversely affect non-headless users who have GPUs available? It could be worth leaving off by default, with like a `--swiftshader` option to enable it?

**Comment by mdmintz** [comment]
@mildmojo Good idea. I'll create another release using ``--swiftshader`` to enable it so that it's not on by default.

**Comment by mildmojo** [comment]
Thank you!

**Comment by mdmintz** [comment]
@mildmojo See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.42.10
Now, ``swiftshader`` is only enabled when specified as a command-line option:
``--swiftshader``

**Comment by mildmojo** [comment]
💯💯💯

**Comment by mildmojo** [comment]
@mdmintz I had a chance to test this today, and it looks like Chrome treats the swiftshader software renderer as a GPU, which means the always-on `--disable-gpu` disables the swiftshader renderer, and I still see a blank window with the new `--swiftshader` option turned on.

I confirmed by capturing the full pytest/seleniumbase-composed Chrome command line in the `/opt/google/chrome/chrome.real` shell script, then whittling the CLI flags down to a minimal case that worked or didn't work. I'm seeing `--disable-gpu --use-gl=swiftshader` rendering a blank window, and `--use-gl=swiftshader` alone rendering a proper window. I can see swiftshader info in `about:gpu` when it's working, too.

Would you be willing to omit `--disable-gpu` when `--swiftshader` is specified?

**Comment by mdmintz** [comment]
@mildmojo Sounds good. I'll create a new release with the update.

**Comment by mdmintz** [comment]
@mildmojo OK, it's ready in SeleniumBase v1.42.12
https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.42.12

**Comment by mildmojo** [comment]
Thanks so much, again! I'll try it out tomorrow.

**Comment by mildmojo** [comment]
@mdmintz AFAICT, the `--swiftshader` option (and the way it now turns off `--disable-gpu`) is doing the right thing, and gets me a working Chrome v79 display when forwarded to my host X server.

I also tested with dockerized Xpra and Xvfb+x11vnc+VNC setups, and while they had their own issues, Chrome rendering is fixed.

Thanks again for the quick, solid help!
