### ISSUE TITLE
How to triple click a text field/area?

### ISSUE THREAD

**Issue by createNull** [seleniumbase/SeleniumBase#624]
Hi @mdmintz ,

Is there any way to perform triple clicks?

I need to select text from a field and I might have multiple whitespaces inside the text, so a double click won't suffice.

Many thanks!

**Comment by mdmintz** [comment]
@createNull Try https://stackoverflow.com/a/62132283

**Comment by createNull** [comment]
@mdmintz from what I know, this method is already implemented in `double_click()`.
It works just fine for double click, but not for triple.

Ok, I guess a new method would be necessary for a triple kill

**Comment by mdmintz** [comment]
@createNull If you're just trying to get the text from a text field, just use:
``self.get_text(SELECTOR)``

**Comment by createNull** [comment]
@mdmintz I'm actually trying to select the text from a text field/area and then delete it. 
Worth to mention I can't use `clear()` due to a selenium bug/functionality.

Is there any way I can create this function myself?
Never tried to manipulate the driver from my own framework.

**Comment by mdmintz** [comment]
@createNull There's an easier way. Use:
``self.set_text(SELECTOR, "")`` to clear the text field if you can't seem to clear it through regular WebDriver means. Is this on a public-facing website? I'd be curious to take a look, since I don't think ``clear()`` is necessarily broken.

**Comment by createNull** [comment]
@mdmintz `clear()` is not broken, but it doesn't fulfil my needs at this moment. Sadly, I can't share the website, but here is a very relevant comment with my kind of problem: https://github.com/w3c/webdriver/issues/445#issuecomment-273080792.

I need to clear the text from a field, do an assert, input text and do another assert again. I'm checking the enabled/disabled state of the submit button for a form and the problem is that when I clear the text, the state of the button keeps being enabled due to the input event listener which is being used into the dev source code.

As for clearing the text normally, I use `self.type(SELECTOR, "")` .

**Comment by mdmintz** [comment]
@createNull The article on https://stackoverflow.com/a/62132283 explains that you can turn a double_click into a triple click by adding ``.perform()`` onto your action chain.

If that doesn't cover it, there's ``self.set_text(SELECTOR, "")`` to clear a text field with JS.

**Comment by createNull** [comment]
@mdmintz Ok, then maybe I'm a little bit confused. 
In https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/fixtures/base_case.py on line 219 we have that exact function call. 
I am using this function in my tests and it triggers a double click, not a triple click.
`self.double_click(SELECTOR)`.

Am I missing something?

I can try with `self.set_text(SELECTOR, "")` as well, thank you for your suggestion.

**Comment by mdmintz** [comment]
@createNull Ah, yes. The StackOverflow solution is incorrect then. I read it, thinking it was working, and then assumed that it was a triple click, when really it was just the normal syntax for a double click. So if that's double click, I'm not sure about triple click, and therefore there's probably a workaround, such as with ``self.set_text(SELECTOR, "")``. Let me know if that works for you.

**Comment by createNull** [comment]
@mdmintz can't find any `self.set_text(SELECTOR)` at a first sight. 
Maybe I am missing something and I can do more research tomorrow.

**Comment by mdmintz** [comment]
@createNull I meant ``self.set_value(SELECTOR, "")``. Typo earlier.

**Comment by createNull** [comment]
@mdmintz Sadly, it doesn't work for me (the button remains enabled). 
However, weirdly enough `self.js_update_text(SELECTOR, "")` works. 

But, if I still need to implement a method like `triple_click()`, any idea how would I be able to do that since I need to manipulate the driver?

**Comment by mdmintz** [comment]
@createNull I couldn't find anything for a triple click. But there's probably a workaround for what you want to do using other methods.

**Comment by createNull** [comment]
@mdmintz Alright, thank you for the quick answers.

**Comment by MarcelWilson** [comment]
I was able to create my own triple click and backspace (i.e. clear text field like a user would) this way:
```python
        actions = ActionChains(driver)
        actions.move_to_element(element)
        actions.w3c_actions.pointer_action.click()
        actions.w3c_actions.pointer_action.click()
        actions.w3c_actions.pointer_action.click()
        for _ in range(4):
            actions.w3c_actions.key_action.pause()

        actions.send_keys(Keys.BACKSPACE)
        actions.perform()
```
I basically borrowed from the logic found in `double_click` and just added one more.
