### ISSUE TITLE
How to put password in?

### ISSUE THREAD

**Issue by SwannZhang412** [seleniumbase/SeleniumBase#625]
Hi，@mdmintz
I need to put password in, like this: 
![image](https://user-images.githubusercontent.com/43056867/87501510-d687c100-c691-11ea-99e1-11ca852d46c7.png)

then I use:
![image](https://user-images.githubusercontent.com/43056867/87501172-07b3c180-c691-11ea-8f08-987cb88beaf9.png)
it return:
![image](https://user-images.githubusercontent.com/43056867/87501195-169a7400-c691-11ea-8fe1-c5ce8c375f8b.png)

Many thanks!

**Comment by mdmintz** [comment]
Hi @SwannZhang412 ,
Since the element is not an ``<input>`` field, you'll now need to use send_keys per selector.
``self.get_element(SELECTOR).send_keys(KEY)``
For your case, it could look like:
```python
self.get_element("div.ui-focus li.ui-passwordItem span.ui-cursor").send_keys("1")
self.get_element("div.ui-focus li.ui-passwordItem span.ui-cursor").send_keys("1")
self.get_element("div.ui-focus li.ui-passwordItem span.ui-cursor").send_keys("1")
self.get_element("div.ui-focus li.ui-passwordItem span.ui-cursor").send_keys("1")
self.get_element("div.ui-focus li.ui-passwordItem span.ui-cursor").send_keys("1")
```

**Comment by mdmintz** [comment]
Hi @SwannZhang412 , did the answer above solve your issue?

**Comment by mdmintz** [comment]
Question answered above. Marking issue as closed.
