### ISSUE TITLE
how to change chrome from pc mode into mobile mode in one test?

### ISSUE THREAD

**Issue by guke1991** [seleniumbase/SeleniumBase#628]
mobileEmulation = {'deviceName': 'iPhone X'}
        options = webdriver.ChromeOptions()
        options.add_experimental_option('mobileEmulation', mobileEmulation)
        self.driver = webdriver.Chrome(chrome_options=options)

this code work in windows（open a new chrome） ,but rebort an error in linux.

or how to set different tests with different mode(pc/mobile)

**Comment by mdmintz** [comment]
@guke1991 ,
To switch to mobile-mode for a single test:
```python
self.get_new_driver(is_mobile=True)
```

For more advanced control (iPhone X example):
```python
self.get_new_driver(
    is_mobile=True,
    agent="""Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1""",
    d_width=375,
    d_height=812,
    d_p_r=3)
```

Only Chrome has the mobile device emulator, so make sure you're using that browser.
To have all tests use mobile-mode, see: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/mobile_testing.md

**Comment by mdmintz** [comment]
Question answered above. Marking issue as closed.
