### ISSUE TITLE
How to get the current selection of the drop-down box？

### ISSUE THREAD

**Issue by zhonghai9967** [seleniumbase/SeleniumBase#631]
self.select_option_by_text（）、index、value,These methods can be selected.
For the drop-down box that has been selected, how much does it mean selection or index or value?
Thank you

**Comment by zhonghai9967** [comment]
<select name="streetCensus" onchange="toHandleCensus(this.value,this.name)" style="width:80px" class="validate[required]" id="form-validation-field-0"> 
									 <option value="" selected="selected">请选择</option><option value="370102005">大明湖街道办事处</option><option value="370102009">甸柳街道办事处</option><option value="370102006">东关街道办事处</option><option value="370102008">建新街道办事处</option><option value="370102001">解放路街道办事处</option><option value="370102012">龙洞街道办事处</option><option value="370102002">千佛山街道办事处</option><option value="370102004">泉城路街道办事处</option><option value="370102014">舜华路街道办事处</option><option value="370102007">文东街道办事处</option><option value="370102010">燕山街道办事处</option><option value="370102011">姚家街道办事处</option><option value="370102013">智远街道办事处</option><option value="370102003">趵突泉街道办事处</option>
								</select>

I have selected the item with value="370102005", but I cannot tell from the script that it has been selected.

**Comment by zhonghai9967** [comment]
“<“ select name="streetCensus" onchange="toHandleCensus(this.value,this.name)" style="width:80px" class="validate[required]" id="form-validation-field-0"> 
									 <option value="" selected="selected">请选择</option><option value="370102005">大明湖街道办事处</option><option value="370102009">甸柳街道办事处</option><option value="370102006">东关街道办事处</option><option value="370102008">建新街道办事处</option><option value="370102001">解放路街道办事处</option><option value="370102012">龙洞街道办事处</option><option value="370102002">千佛山街道办事处</option><option value="370102004">泉城路街道办事处</option><option value="370102014">舜华路街道办事处</option><option value="370102007">文东街道办事处</option><option value="370102010">燕山街道办事处</option><option value="370102011">姚家街道办事处</option><option value="370102013">智远街道办事处</option><option value="370102003">趵突泉街道办事处</option>
								</select>

I have selected the item with value="370102005", but I cannot tell from the script that it has been selected.

**Comment by zhonghai9967** [comment]
'<select name="streetCensus" onchange="toHandleCensus(this.value,this.name)" style="width:80px" class="validate[required]" id="form-validation-field-0"> 
									 '<option value="" selected="selected">请选择</option><option 'value="370102005">大明湖街道办事处</option><option value="370102009">甸柳街道办事处</option><option 'value="370102006">东关街道办事处</option><option value="370102008">建新街道办事处</option><option 'value="370102001">解放路街道办事处</option><option value="370102012">龙洞街道办事处</option><option 'value="370102002">千佛山街道办事处</option><option value="370102004">泉城路街道办事处</option><option 'value="370102014">舜华路街道办事处</option><option value="370102007">文东街道办事处</option><option 'value="370102010">燕山街道办事处</option><option value="370102011">姚家街道办事处</option><option 'value="370102013">智远街道办事处</option><option value="370102003">趵突泉街道办事处</option>
								'</select>

I have selected the item with value="370102005", but I cannot tell from the script that it has been selected.

**Comment by zhonghai9967** [comment]
'<'select name="streetCensus" onchange="toHandleCensus(this.value,this.name)" style="width:80px" class="validate[required]" id="form-validation-field-0"   '>' 
									 '<'option value="" selected="selected">请选择</option><option 'value="370102005">大明湖街道办事处</option><option value="370102009">甸柳街道办事处</option><option 'value="370102006">东关街道办事处</option><option value="370102008">建新街道办事处</option><option 'value="370102001">解放路街道办事处</option><option value="370102012">龙洞街道办事处</option><option 'value="370102002">千佛山街道办事处</option><option value="370102004">泉城路街道办事处</option><option 'value="370102014">舜华路街道办事处</option><option value="370102007">文东街道办事处</option><option 'value="370102010">燕山街道办事处</option><option value="370102011">姚家街道办事处</option><option 'value="370102013">智远街道办事处</option><option value="370102003">趵突泉街道办事处</option>
								'<'/select'>'
I have selected the item with value="370102005", but I cannot tell from the script that it has been selected.

**Comment by mdmintz** [comment]
Hi @zhonghai9967 , If you've correctly selected the option, there should be a change in the HTML, such as ``selected="selected"`` for the option that you have selected. With SeleniumBase, you can detect the change in the HTML by using ``self.is_element_visible(SELECTOR)``.

**Comment by zhonghai9967** [comment]
Thanks, I found it.
streetCensus=self.get_text('#td_consus2>select[name="streetCensus"]>option[selected="selected"]')

**Comment by mdmintz** [comment]
Great! I'll close this ticket.
