### ISSUE TITLE
Pytests with BaseCase not run in order

### ISSUE THREAD

**Issue by jbnjohnathan** [seleniumbase/SeleniumBase#634]
Consider this simple pytest script

```
def test_one():
    assert True

def test_two():
    assert True

def test_three():
    assert True
```
We run it with: `$ env/bin/pytest -sv tests/test_order_simple.py`

The output will be
```
tests/test_order_simple.py::test_one PASSED
tests/test_order_simple.py::test_two PASSED
tests/test_order_simple.py::test_three PASSED
```

Now lets get it in a class and use BaseCase
```
from seleniumbase import BaseCase
from selenium.webdriver.common.by import By
import os
from selenium.common import exceptions


class MyTestClass(BaseCase):
    def test_one(self):
        assert True

    def test_two(self):
        assert True

    def test_three(self):
        assert True
```
Lets run it in the same way `$ env/bin/pytest -sv tests/test_order_simple.py`

```
tests/test_order.py::MyTestClass::test_one FAILED
tests/test_order.py::MyTestClass::test_three FAILED
tests/test_order.py::MyTestClass::test_two FAILED
```

Let's not focus on the fail, but rather the order in which it is run in. 1,3,2. Why is this not run in order from top to bottom?
When I run my more advanced SeleniumBase pytest I find that it seems to run from bottom to top, but I haven't checked the exact order of all the functions.

seleniumbase==1.42.5
pytest==5.4.3
Running in Ubuntu 18.04.2 (WSL 2)

**Comment by mdmintz** [comment]
Hi @jbnjohnathan , The default test ordering is alphabetical. First by file name, then class name, then test name. It's not based on the order that the tests appear in the class. Alphabetically, it would be "test_one", test_three", "test_two". But then you can do this: "test_1", "test_2", "test_3", which is alphabetical. You can change the ordering using the ``pytest-ordering`` plugin's marker/decorator (included with SeleniumBase).

Example (I created a sample file to demonstrate):
```python
import pytest
from seleniumbase import BaseCase

class MyTests(BaseCase):
    @pytest.mark.run(order=1)
    def test_xyz(self):
        pass

    @pytest.mark.run(order=2)
    def test_abc(self):
        pass
```

And the output of that:
```bash
pytest test_2.py -v
...
test_2.py::MyTests::test_xyz PASSED
test_2.py::MyTests::test_abc PASSED
```

(Here's another example that uses it: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/swag_labs_suite.py)

**Comment by jbnjohnathan** [comment]
Thanks for the reply. I was just wondering since using only pytest would run it in the order the functions come in the file, while using BaseCase from seleniumbase change this. I have to admit I am no expert to pytest but to me it would seem more logical to have the default order as the order the functions come in the class. But maybe this is outside of selenium and in pytest instead, if so then I think your proposed solution is good. Thanks! : )
