### ISSUE TITLE
Feature for Screen(video) recording of browser

### ISSUE THREAD

**Issue by teamdts** [seleniumbase/SeleniumBase#642]
hello,
Feature Enhancement request:
can you add something like to record video of each test case ? in headed mode and headless mode both ?

Thanks

**Comment by mdmintz** [comment]
@teamdts Use an existing tool with SeleniumBase such as Zalenium for recording videos:
https://opensource.zalando.com/zalenium/
It works like a Selenium Grid.
See https://seleniumbase.io/seleniumbase/utilities/selenium_grid/ReadMe/ for instructions on using SeleniumBase to connect to a Selenium Grid.
