### ISSUE TITLE
Using the SeleniumBase module in Python, how to get URL of link that changes with each query?

### ISSUE THREAD

**Issue by bsmith4133** [seleniumbase/SeleniumBase#650]
Here is the HTML from a website I'm working with:

```
<pre>
Unique sequence file: 
<a href="/cgi-bin/elimdupesv2/elimdupes.cgi?id=4ROEFYUD&amp;output=unique_default.Fasta">View</a> 
<a href="/cgi-bin/elimdupesv2/elimdupes.cgi?id=4ROEFYUD&amp;download=unique_default.Fasta">Download</a>
<pre>
```

What's displayed:

Unique sequence file: View Download

The download link changes every run because a different file is produced. How should I extract the URL and save it into a variable to download the file? I tried this but it didn't work:

```
class Example(BaseCase):

def test_(self):
    ...
    url = self.find_link_text('Download', timeout=None).get_link_attribute()
    self.download_file(file_url, destination_folder=None)
```

Thanks a bunch in advance.

**Comment by mdmintz** [comment]
@bsmith4133 Try:
```python
href = self.get_link_attribute("Download", "href")
if href.startswith('/'):
    url = self.driver.current_url
    domain_url = self.get_domain_url(url)
    link = domain_url + href
```

**Comment by bsmith4133** [comment]
@mdmintz Thanks for the great solution. Do you have any recommendations for how to download from something like this, which doesn't contain a URL but instead a function of some sort? It doesn't open a link but instead

`<input type="image" src="files/download.png" onclick="startDownload();">`

The interface looks like this:
![image](https://user-images.githubusercontent.com/69334328/90158036-79e4f800-dd5c-11ea-9fdf-e8d20b26de7e.png)

Or would I have to just ask the user for the path to the downloaded file for the next steps? (This is part of a pipeline.)

**Comment by mdmintz** [comment]
Hi @bsmith4133 ,
You might be able to see where ``startDownload();`` is defined by calling ``source = self.get_page_source()`` and then using regular Python string parsing to extract the URL from the method definition. If necessary, there are methods such as ``self.execute_script(JAVASCRIPT)`` that can help you with that. Based on that one line of html that you posted, this is the best advice that I can offer at this time.

**Comment by bsmith4133** [comment]
@mdmintz Thanks so much for the suggestion. Here is what I found for the method definition (from [](https://www.ncbi.nlm.nih.gov/Structure/bwrpsb/bwrpsb.cgi)) There doesn't seem to be a URL, but not sure if this makes anything more clear, as I'm not completely familiar with JavaScript:

```
function startDownload() {
    var e = jQuery.extend(!0, {}, ajaxObj);
    e.data[ridKey] = ctrlHandle,
    jTotalInputs.each(function(t) {
        !this.disabled && this.checked && (e.data[this.name] = this.value)
    }),
    ajaxStart(e, '<span style="text-decoration: blink;">Formatting data ...</span>')
}
```

Do you have any recommendations for this? I'd be happy to provide more code or anything else if needed.

**Comment by mdmintz** [comment]
I'm not exactly sure how to extract the URL you're looking for out of that. There's probably an easier way to accomplish what you're going for. I'm currently working on several projects at once.
