### ISSUE TITLE
How to get input variable while running pytest for SeleniumBase in Python?

### ISSUE THREAD

**Issue by bsmith4133** [seleniumbase/SeleniumBase#657]
The file I upload to a website changes with each run, and I'd like a way to change it in test method. Currently, I have it set up like this:
## functions.py
```
def get_file():
    ...
    file = file_ex1.doc
    return file

def run_test1():
    cmd = "pytest -v webtests.py::EF --browser=chrome"
    subprocess.run(split(cmd))  # run command line
...
```

## webtests.py
```
file_path = file  # changes with each run

class EF(BaseCase):
    def test_now(self):
        self.open('https://www...')
        self.find_element('input[name="Query"]').send_keys(file_path)`

```
I was wondering about the best way to change the `file_path` variable based on the output of certain functions in `functions.py`. For example, it could sometimes produce a file called file1 to upload, or another time filet2.txt. What's the best way to connect the two scripts and run `test_now()` with the updated file path each run?

Thanks so much in advance.

**Comment by mdmintz** [comment]
Hi @bsmith4133 , based on your current code where you run ``subprocess`` to run other scripts, you can use one of the following pytest args that come with SeleniumBase.

```bash
--data=DATA  # (Extra test data. Access with "self.data" in tests.)
--var1=DATA  # (Extra test data. Access with "self.var1" in tests.)
--var2=DATA  # (Extra test data. Access with "self.var2" in tests.)
--var3=DATA  # (Extra test data. Access with "self.var3" in tests.)
```

That will let you set an environment variable when starting a test, and then let you access that variable in the test.

**Comment by mdmintz** [comment]
If that solves your issue, you can close this ticket.
