### ISSUE TITLE
how to add my own function

### ISSUE THREAD

**Issue by SwannZhang412** [seleniumbase/SeleniumBase#663]
need your help
I add my function in seleniumbase/fixtures/base_case.py
then run and it returns "object has no attribute 'my_send_message'"

![image](https://user-images.githubusercontent.com/43056867/90760628-bf816200-e314-11ea-9ada-21a09678ba48.png)

thanks!

**Comment by mdmintz** [comment]
Hi @SwannZhang412 It looks like you're spelling "message" differently in different parts of your code. You might be calling it with the wrong spelling ("mesage" vs "message"). Also, if you make changes to your local copy of SeleniumBase, you need to rerun ``pip install .`` from the top-level folder, or you need to run once in develop mode: ``pip install -e .``. And if you make changes to your local copy of seleniumbase, you may have issues when upgrading to a newer version of SeleniumBase. For that, you may want to create your own base class that inherits BaseCase. Here's an example of that: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py

**Comment by mdmintz** [comment]
Assuming resolved. Closing this ticket.
