### ISSUE TITLE
Is there a possibility to perform visual testing on two different environments?

### ISSUE THREAD

**Issue by PyShaman** [seleniumbase/SeleniumBase#680]
Hello,

I have a case where I have two environments to test (client want visual tests for them), let's say www.x_env.com and www.y_env.com. How to create testing scenarios to check and compare level 3 differences between?

Kind regards,
Michal

**Comment by mdmintz** [comment]
Hi @PyShaman , assuming the 2 website URLs are meant to represent the same website, you can hack the visual testing system to allow the comparison. Inside the ``visual_baseline`` folder, which is created when creating a baseline, there will be a file called ``page_url.txt``. If you can change that to match the URL of the 2nd website that you'll be comparing, you'll be able to make the visual layout comparisons without getting an error for it. It does require a bit of data swapping for that, as the system was intended to be used for comparing changes made to the same website.

**Comment by PyShaman** [comment]
Great. I found workaround ;) Correct me if I am wrong. in seleniumbase/fixtures/base_case.py i commented lines 5523-5525. This prevented to throw page url's assertion error, but I am not sure if the rest of comparison will be affected. What do you think @mdmintz ?

**Comment by mdmintz** [comment]
@PyShaman That sounds like it could work.

**Comment by PyShaman** [comment]
@mdmintz Awesome! Thanks for advice. I can close this issue :) Thank for very fast reply! Have a nice day!
