### ISSUE TITLE
Improvement request for calling scripts directly with python

### ISSUE THREAD

**Issue by passerby-afk** [seleniumbase/SeleniumBase#696]
Hi. I'm currently using your framework, which I find extremely useful. Can you improve the calling of the script directly with python (like you did in raw_parameter_script.py) ?  I'm using something similar to what you wrote in order to run my set of tests, but unfortunately if you update the attributes my automation will fail, if I were to upgrade to the latest version and not have the new attributes in my script. Thank you

**Comment by mdmintz** [comment]
Hi @passerby-afk , the ``raw_parameter_script.py`` (https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py) is a hack for getting around the automatic variable instantiation that comes with pytest initialization. Those variables need to be defined somewhere for SeleniumBase to work. When tests are run with pytest, there are default values set for any variable that isn't defined from command line arguments. When calling the ``raw_parameter_script.py`` with pure Python, those variables get defined there. They are necessary, as those determine the web browser to use and other important variables.

Tests are intended to be run with pytest, but for special cases when people want to run SeleniumBase as a pure Python non-test script, they have that option.

**Comment by passerby-afk** [comment]
Hi. So... no improvement :)

**Comment by mdmintz** [comment]
@passerby-afk The ``raw_parameter_script.py`` was the improvement: The ability to run SeleniumBase scripts as pure Python without ``pytest`` or ``nosetests``.

Alternatively, you can run SeleniumBase without classes. (See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_sb_fixture.py) That uses pytest fixtures to avoid sub-classing BaseCase, if that's what you're looking for.

**Comment by passerby-afk** [comment]
raw_parameter_script.py is my target. I'm using it because I'm reading a parameter value from command line: "python mypy.py param_value" and also I'm setting the sb.browser, sb.slow_mode,.... in mypy.py

**Comment by mdmintz** [comment]
Sounds like you just need to create your own customized version of ``raw_parameter_script.py`` where you only change the variables that you want changed and combine that with your own script. The ``raw_parameter_script.py`` is just an example/boilerplate that you can use to create your own script that uses pure Python rather than calling pytest or nosetests. Quite possibly someone has already done something similar and made it work. You may be able to join the public SeleniumBase chat at https://gitter.im/seleniumbase/SeleniumBase and see if anyone there has done what you're looking for.

**Comment by passerby-afk** [comment]
Just logged in. I'm going to pop the question :)))) Hopefully somebody will reply. Thank you.

**Comment by mdmintz** [comment]
I'm going to close this because https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py takes care of providing an example of running tests with a direct Python call.

**Comment by mdmintz** [comment]
There are more ways to run with pure Python now. For example:

```python
"""Context Manager Test. Runs with "python". (pytest not needed)."""
from seleniumbase import SB

with SB() as sb:  # By default, browser="chrome" if not set.
    sb.open("https://seleniumbase.io/realworld/login")
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.enter_mfa_code("#totpcode", "GAXG2MTEOR3DMMDG")  # 6-digit
    sb.assert_text("Welcome!", "h1")
    sb.highlight("img#image1")  # A fancier assert_element() call
    sb.click('a:contains("This Page")')  # Use :contains() on any tag
    sb.click_link("Sign out")  # Link must be "a" tag. Not "button".
    sb.assert_element('a:contains("Sign in")')
    sb.assert_exact_text("You have been signed out!", "#top_message")
```

Or:

```python
"""Driver() test. Runs with "python". (pytest not needed)."""
from seleniumbase import Driver
from seleniumbase import js_utils
from seleniumbase import page_actions

# Example with options. (Also accepts command-line options.)
driver = Driver(browser="chrome", headless=False)
try:
    driver.get("https://seleniumbase.io/apps/calculator")
    page_actions.wait_for_element(driver, '[id="4"]').click()
    page_actions.wait_for_element(driver, '[id="2"]').click()
    page_actions.wait_for_text(driver, "42", "#output")
    js_utils.highlight_with_js(driver, "#output", loops=6)
finally:
    driver.quit()

# Example 2 using default args or command-line options
driver = Driver()
try:
    driver.get("https://seleniumbase.github.io/demo_page")
    js_utils.highlight_with_js(driver, "h2", loops=5)
    by_css = "css selector"
    driver.find_element(by_css, "#myTextInput").send_keys("Automation")
    driver.find_element(by_css, "#checkBox1").click()
    js_utils.highlight_with_js(driver, "img", loops=5)
finally:
    driver.quit()
```

And more, see https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md
