### ISSUE TITLE
怎样获得网页超过一屏的截图（截取长图）？

### ISSUE THREAD

**Issue by zhonghai9967** [seleniumbase/SeleniumBase#705]
网页超过屏幕高度。
截图时，只能得到一个屏幕大小的图。
谢谢

**Comment by mdmintz** [comment]
使用 ``--headless`` 时截取的屏幕截图将显示完整的网页。
您还可以在截图之前在测试中更改窗口大小：``self.set_window_size(width, height)``

Screenshots taken when using ``--headless`` will have the full web page shown.
You can also change the window size in your tests before taking a screenshot: ``self.set_window_size(width, height)``

**Comment by zhonghai9967** [comment]
谢谢。self.set_window_size(width, height)无效。
--headless OK！

**Comment by mdmintz** [comment]
例 / Example: ``self.set_window_size(1400, 1500)``
宽度 - width - x轴
高度 - height - y轴
