### ISSUE TITLE
CSS Selector Confusion.... 

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#716]
Please, any assistance you can help with, I'd appreciate it.  

1) The web site I'm trying to use for testing is horrible, and I have no way to change it.  So I any workarounds or suggestions are welcome.
2) I need to be able to click on the anchor, and the only distinguishing value is the one value in the <.i class>
   (Please note, I couldn't get this to render as preformatted text, so I've been forced to add periods to prevent the html from being eaten).

<.a>
<.i class="fa fa-file-text fa-lg text-primary curs-ptr" data-placement="left" data-toggle="tooltip" title="" data-path="unique? filepath" data-iid="35833748" onclick="javascript:PrintPDF(this, true, false);" data-original-title="pdf"><./i>
<./a>

I could either detect the line by the data-path or data-iid, those two values are unique per anchor.

But I can't puzzle my way through figuring out the css selector to be able to detect it..  Is there an HTML to css selector site?

The CSS in firefox is just giving me the class selector ("fa fa-file-text").  

Would 
def click_document(self, iid):
        self.click("[data-iid=iid]") work in this case (where iid is the numeric value)?

3) Sorry, but this was working... And now all of a sudden, it isn't.  

    <.a data-onclick="bindSplitCategoryModuleList('/XXXXXX/Clinical/Dashboard/LeftSubMenu','xMultimedia',this) , bindAllinOneModule('/XXXXX/Clinical/Multimedia','xMultimedia','','','','',0,this)" class="" onclick="bindSplitCategoryModuleList('/XXXXXX/Clinical/Dashboard/LeftSubMenu','xMultimedia',this) , bindAllinOneModule('/XXXXXX/Clinical/Multimedia','xMultimedia','','','','',0,this)">
                            <.label class="modulenamewrap" title="Images">Images</label>
                            .<span class="spanCount number" style="float: right;">4</span>
                        <./a>

This should be simple?  

            self.click_link_text("Images")

Had been working, but now it isn't.  
It's reporting back "NoSuchElementException"?_

**Comment by mdmintz** [comment]
Hi @bschollnick , there's a typo in one of your examples:
``self.click("[data-iid=iid]")``
should be
``self.click('[data-iid="%s"]' % iid)``
so that the part after the ``=`` is in quotes.

Also, to paste code, use "`` CODE  ``". (It's that weird quote on the left of the "1" on most keyboards.) For a code block, use "``` CODE BLOCK ```".

For the "Images" link, you can also try: ``a:contains(TEXT)`` as a selector (assuming you have SeleniumBase v1.49.2 or newer - latest is v1.49.26)

**Comment by bschollnick** [comment]
Thanks, both worked...  I need to tweak my workflow a bit, but your suggestions worked fantastic...
