### ISSUE TITLE
self.click("a:contains('Images')") not working in --headless mode

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#719]
Well, the same code works fine in normal mode, but using --headless causes it to fail.

```
test_documents.py:84:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\python3\ellkay\lib\site-packages\seleniumbase\fixtures\base_case.py:149: in click
    self.driver, selector, by, timeout=timeout)
..\..\..\python3\ellkay\lib\site-packages\seleniumbase\fixtures\page_actions.py:304: in wait_for_element_visible
    timeout_exception(ElementNotVisibleException, message)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

exception = <class 'selenium.common.exceptions.ElementNotVisibleException'>
message = "\n Element {//a[contains(., 'Images')]} was not visible after 6 seconds!"

    def timeout_exception(exception, message):
        exc, message = s_utils.format_exc(exception, message)
>       raise exc(message)
E       selenium.common.exceptions.ElementNotVisibleException: Message:
E        Element {//a[contains(., 'Images')]} was not visible after 6 seconds!

..\..\..\python3\ellkay\lib\site-packages\seleniumbase\fixtures\page_actions.py:117: ElementNotVisibleException
============================ short test summary info ============================
FAILED test_documents.py::test_patients::test_documents - selenium.common.excep...
============================== 1 failed in 32.91s ===============================
```

**Comment by mdmintz** [comment]
@bschollnick Have you looked at the screenshot of the failure? It could be possible that the website is rendering headless browsers differently. For example, some websites detect that the web browser is headless (through the User Agent) and then render the site differently. You might be able to get around the issue (if that's the case) by changing the User Agent. Here's an example test that does that: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_apple_site.py

**Comment by bschollnick** [comment]
Headless works fine with scraping the site when we are doing a different workflow, it's just the documents workflow that uses the a:contains('Images').  

I'll try to dig further today or tomorrow.

**Comment by bschollnick** [comment]
You were correct.  The site itself was changing the layout to reflect the virtual screen size. 

What confused me, is I have a self.maximize in the workflow, which in hindsight makes sense.  What is the maximized size of a virtual display.

Using self.set_window_size(1680, 1050) resolved the contains issue, since it's being properly rendered.  

I'm now dealing with debugging an issue where the test doesn't seem to be completing under --headless, it's just sitting there....  Seemingly either stuck at a timeout or ????
