### ISSUE TITLE
--headless issues (lockup, freeze, or endless loop?) & pdf viewing?

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#720]
Here's the easy one first?  

1)  When in headless mode, the web site is reporting that Chrome doesn't support PDF files.  Whereas in normal mode Chrome displays them fine, is there some reason that headless wouldn't support viewing PDFs?  (Maybe a configuration setting that needs to be updated for headless?)

2) This is the confusing one.  Headless mode seems to be locking up, it might complete a cycle or two, but just sits there, never completing.  And this lockup or endless loop, seems to be occuring around:

            self.switch_to_default_window()

Is there some reason that might not be kosher in  headless mode?

**Comment by bschollnick** [comment]
Sorry, I think I have a better idea of what might be happening.

1) The web site uses a javascript to open a document in a new tab.  It appears that Seleniumbase isn't catching the fact that a new tab is opened, and thus I use:

`
            self.click_document(iid=data[0]["File Path"])  # Open document
            self.sleep(3)
            self.driver.switch_to.window(window_name=self.driver.window_handles[-1])
                                           # Force the web browser to be viewing the last tab opened
            if self.is_text_visible("Records"):  # is "Records" is visible we are still on the record listing page
                print("Records still visible")
                self.click_document(iid=data[0]["File Path"])
                self.sleep(20)

            self._save_screen_shot_woverlay(filename="ellkay_doc1", overlay=text_overlay)
`

So if there is a better way to force focus to be the new page that has opened, that might also be a contributing factor?

So I'm uncertain  if it's the switch.to_window or self.switch_to_default_window that might be causing this, or if they are just red herrings....  Any suggestions on how to better isolate the issue, is welcome.

**Comment by mdmintz** [comment]
Hello, responding to:
> 1. The web site uses a javascript to open a document in a new tab.  It appears that Seleniumbase isn't catching the fact that a new tab is opened

SeleniumBase won't automatically switch tabs for you just because you clicked a button that opens a new tab/window. You need you switch to it with ``self.switch_to_window(WINDOW)``, where ``0`` is the initial window, ``1`` in the next one, etc. This is to prevent loss of control if an unwanted pop-up opens a new window.

You can use ``self.switch_to_default_window()`` to go back to the initial window at any time. It's up to your test to manage the windows during tests.
