### ISSUE TITLE
Feature Suggestion - ability to add overlay text to screenshots

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#721]
1) The ability to get a screenshot as a Pillow object...  eg:

```
def _return_screen_shotdata(self):
        """
        Save a raw screen shot without overlay or any other changes
        """
        png = self.driver.get_screenshot_as_png() # saves screenshot of entire page
        im = Image.open(BytesIO(png)) # uses PIL library to open image in memory
        return im
```

2) The ability to add a text overlay to a screen shot.  (This code works, except sometimes the last two lines overlay, usually when the final line is too long for the screen dimensions...)

The text overlays are perfect to adding a timedate stamp to a screen capture, or adding information for comparison later...

example overlay:

```

text_overlay = {"x":400, "y":700,
                "fontfamily":"Regular",
                "text": ["%s %s" % (person["first_name"], person["last_name"]),
                         "ID: %s" % person["ID"],
                         "DOB: %s" % person[dob"],
                         "Date: %s" % person["doc_date"],
                         "Desc: %s" % person["description"],
                         "Doc ID: %s" % doc_id
                         ],
                "textcolor":(255, 255, 255, 200) }

def _add_overlay(self, filename=None, overlay=None, imagedata=None):
        """
        https://moonbooks.org/Articles/
                How-to-add-text-on-an-image-using-pillow-in-python-/
        """
        if imagedata != None:
            im1 = imagedata
            im1 = self._image_resize(imagedata=imagedata)
        else:
            im1 = self._open_image_resize(filename)
        if overlay not in [None, {}]:
            draw = ImageDraw.Draw(im1)
            font = ImageFont.truetype("arial.ttf", 20)

            for cnt, line in enumerate(overlay["text"]):
                #print(line)
                text_width, text_height = font.getsize(line)
                text_height = text_height * 1.25
                if overlay["x"] < 1:
                    overlay["x"] = 1
                draw.rectangle((overlay["x"],
                                overlay["y"]+(cnt*text_height),
                                overlay["x"]+text_width+10,
                                overlay["y"]+(cnt*text_height)+text_height+5),
                                fill=(0,0,0,128))
                draw.text((overlay["x"],
                            overlay["y"]+(cnt*text_height)),
                          line, overlay["textcolor"],font=font)
        return im1
```

**Comment by mdmintz** [comment]
Hi @bschollnick, Thank you. I'll play around with this. Yesterday I launched https://seleniumbase.io/devices/?url=github.com , which can be used to see how a website will look on multiple devices.
I'll play around with code to see what I can add in. I may be able to blend the two in to get screenshots of websites on devices with text overlays.

**Comment by mdmintz** [comment]
Hi @bschollnick, Thank you. I'll play around with this.
Yesterday I launched https://seleniumbase.io/devices/?url=github.com , which can be used to see how a website will look on multiple devices.
I'll play around with code to see what I can add in. I may be able to blend the two in to get screenshots of websites on devices with text overlays.

**Comment by mdmintz** [comment]
@bschollnick I'm getting various errors trying to debug this. Can you paste a complete working code sample with all necessary imports?

**Comment by bschollnick** [comment]
I'll try to get that to you in the morning...

**Comment by bschollnick** [comment]
Okay, I'm included a modified FIRST_TEST.PY, which includes an example of both with and without overlay.  

I've probably included a bit more code then necessary.  But I refactored that code a bit back, and I just cut and pasted the new code in.


[overlay example.zip](https://github.com/seleniumbase/SeleniumBase/files/5596791/overlay.example.zip)

**Comment by mdmintz** [comment]
Thanks. I'm working on getting this into SeleniumBase.

**Comment by mdmintz** [comment]
It's done and shipped:
https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.50.14

A few things: Using the default system font for overlay text because not all systems have all fonts. No images are resized because that can distort the images depending on the resolution. I've created a simplified version where all you need to specify is the text to add to the image as an overlay. The location will be the top left. The colors are already set to a default scheme.

See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/image_test.py for examples that add an overlay to images. Make sure to upgrade to seleniumbase ``v1.50.14``.

**Comment by mdmintz** [comment]
Done, and closing.
