### ISSUE TITLE
How to perform low level operations like keyboard.

### ISSUE THREAD

**Issue by jeetjddas** [seleniumbase/SeleniumBase#737]
1. If i want to push a button in keyboard what i have to do? like key_down.CTRL or key_down.Backspace...............
how to use those things?
2. Also your self.clear() method is not working in my application. Is there any other method to clear text from a text field?

**Comment by mdmintz** [comment]
Here's an example of using keys:
```python
from selenium.webdriver.common.keys import Keys
...
self.send_keys(Keys.BACK_SPACE)
```

Similarly, you can also use backspaces to clear a text field. Example:
```python
from selenium.webdriver.common.keys import Keys
...
backspaces = Keys.BACK_SPACE * 42
self.send_keys(backspaces)
```

**Comment by chenqinggang001** [comment]
@mdmintz Does current version  seleniumbase support keyboard operation?

**Comment by chenqinggang001** [comment]
The `self.send_keys(Keys.BACK_SPACE)` takes two parameters
![image](https://user-images.githubusercontent.com/74290987/202639493-455acb31-b667-462f-b856-53be181e1e07.png)

**Comment by mdmintz** [comment]
@chenqinggang001 Try:

```python
from selenium.webdriver.common.keys import Keys

self.send_keys(selector, Keys.BACK_SPACE)
```

Eg:

```python
from selenium.webdriver.common.keys import Keys

self.send_keys("input", Keys.BACK_SPACE)
```

There always needs to be a selector for the target.
