### ISSUE TITLE
pytest fixture can't be used when testcase extends of BaseCase

### ISSUE THREAD

**Issue by cw1427** [seleniumbase/SeleniumBase#745]
SeleniumBase version=1.50.1
Python=3.6.8
OS=Windows

When I customized a fixture named tap_testcase_config, and write below two kinds of testcase, one extends of BaseCase, one is a pure testcase.  Only pure testcase could pass when use my customized fixture.  
The same as built-in sb fixture.  Please see below error

`from seleniumbase import BaseCase

class MyTestClass(BaseCase):

    def test_demo_site(self, tap_testcase_config):
        pass

class MyTestClass1():

    def test_demo_site1(self, tap_testcase_config):
        pass
`

`
$ pytest ./test.py
============================= test session starts =============================
platform win32 -- Python 3.6.4, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: E:\opt\tools\newgam\taptest_base, configfile: pytest.ini
plugins: allure-pytest-2.8.18, celery-4.3.0, cov-2.10.1, forked-1.3.0, html-2.0.1, metadata-1.10.0, ordering-0.6,                                                                                                                            rerunfailures-9.1.1, xdist-2.1.0, seleniumbase-1.50.1
collected 2 items

test.py F.

================================== FAILURES ===================================
_________________________ MyTestClass.test_demo_site __________________________

self = <unittest.case._Outcome object at 0x0000014A048DEEF0>
test_case = <taptest_base.test.MyTestClass testMethod=test_demo_site>
isTest = True

    @contextlib.contextmanager
    def testPartExecutor(self, test_case, isTest=False):
        old_success = self.success
        self.success = True
        try:
>           yield

c:\program files\python36\Lib\unittest\case.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <taptest_base.test.MyTestClass testMethod=test_demo_site>
result = <TestCaseFunction test_demo_site>

    def run(self, result=None):
        orig_result = result
        if result is None:
            result = self.defaultTestResult()
            startTestRun = getattr(result, 'startTestRun', None)
            if startTestRun is not None:
                startTestRun()

        result.startTest(self)

        testMethod = getattr(self, self._testMethodName)
        if (getattr(self.__class__, "__unittest_skip__", False) or
            getattr(testMethod, "__unittest_skip__", False)):
            # If the class or method was skipped.
            try:
                skip_why = (getattr(self.__class__, '__unittest_skip_why__', '')
                            or getattr(testMethod, '__unittest_skip_why__', ''))
                self._addSkip(result, self, skip_why)
            finally:
                result.stopTest(self)
            return
        expecting_failure_method = getattr(testMethod,
                                           "__unittest_expecting_failure__", False)
        expecting_failure_class = getattr(self,
                                          "__unittest_expecting_failure__", False)
        expecting_failure = expecting_failure_class or expecting_failure_method
        outcome = _Outcome(result)
        try:
            self._outcome = outcome

            with outcome.testPartExecutor(self):
                self.setUp()
            if outcome.success:
                outcome.expecting_failure = expecting_failure
                with outcome.testPartExecutor(self, isTest=True):
>                   testMethod()
E                   TypeError: test_demo_site() missing 1 required positional argument: 'tap_testcase_config'

c:\program files\python36\Lib\unittest\case.py:605: TypeError
=========================== short test summary info ===========================
FAILED test.py::MyTestClass::test_demo_site - TypeError: test_demo_site() mis...
========================= 1 failed, 1 passed in 6.58s =========================
(env36)

`

**Comment by mdmintz** [comment]
Hi @cw1427 , That's the main reason why the ``sb`` fixture was created. (Example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_sb_fixture.py )
Most pytest fixtures have an incompatibility with ``unittest.TestCase``, which SeleniumBase's BaseCase inherits. Therefore, an indirect inheritance was necessary, and that's how the ``sb`` fixture came to be. It allows you to use other pytest fixtures in your tests.

**Comment by cw1427** [comment]
Hi @mdmintz :

I figured it by refering doc:  https://docs.pytest.org/en/3.0.1/unittest.html

We could make a generic base class, and explictly mark it use pytest fixture like below, 

```python
@pytest.mark.usefixtures("tap_testcase_config")
class TapTestBase(BaseCase):
      pass
```

Below is my sample fixture in class scope
```
@pytest.fixture(scope="class")
def tap_testcase_config(request):
    """a fixture to load testcase config file by mode."""
    try:
        env = request.config.getoption("--env")
        config = importlib.import_module('taptest_base.config_{0}'.format(env))
    except Exception as e:
        print('missing testcase config file err={0}'.format(e))
        config = None
    request.cls.config = config

```

**Comment by mdmintz** [comment]
@cw1427 Great! Looks like you found a workaround. Did that resolve your issue?

**Comment by symonk** [comment]
@cw1427 the problem is you cannot access return value(s) or yield values using such a method, which will massively hinder you later on.  using the `sb` fixture is the way to go for sure

**Comment by cw1427** [comment]
@symonk : Not all the fixtures need a return or yield way to provide the obj to the target, instead here I use class scope fixture and request.cls as the referance could bring the 'value obj' back into the  Base testcase.  It is convinent to work with seleniumBase base testcase than directly use sb fixture.
