### ISSUE TITLE
About CSRF calibration

### ISSUE THREAD

**Issue by meilisong1989** [seleniumbase/SeleniumBase#752]
hi , 
Our business does CSRF verification, but when the browser is launched, there is no origin field in the header, so the verification fails. May I ask what is the reason?

**Comment by mdmintz** [comment]
Hi @meilisong1989, are you getting the same issues when opening a regular browser window without Selenium? It could be that the browser is out-of-date, or that WebDriver does this automatically, but SeleniumBase isn't changing any of those settings on its own. I'm not too familiar with CSRF verification, so I wouldn't know where to start.

**Comment by meilisong1989** [comment]
I guess it's not the Selenium base problem, because it's nice to be able to selenium the browser, it's not the seleniumbase problem, but I can use selenium to launch it, and I've tried a lot of different versions, some of them won't, some of the higher versions will come up, which is strange


I'll try a few more browser versions, thank you
