### ISSUE TITLE
docs: expand abbreviation "RPA"

### ISSUE THREAD

**Issue by tbm** [seleniumbase/SeleniumBase#762]
The docs start with:

> SeleniumBase: A fast and reliable web automation framework for end-to-end testing and RPA

It would be good to expand "RPA" for those not familiar with the term.

**Comment by mdmintz** [comment]
Hi @tbm, I just updated the ReadMe on GitHub and on [seleniumbase.io](https://seleniumbase.io/)

It now says:

<p><b>SeleniumBase</b>: A fast and reliable web automation framework for end-to-end testing and <a href="https://en.wikipedia.org/wiki/Robotic_process_automation">RPA</a> with <a href="https://www.python.org/">Python</a>, <a href="https://docs.pytest.org/en/latest/index.html">pytest</a> and <a href="https://www.w3.org/TR/webdriver2/#endpoints">WebDriver</a>. Includes tools for reports, charts, presentations, product tours, and visual testing.</p>
