### ISSUE TITLE
I want to change the fixture level to class, but an error is reported during runtime.

### ISSUE THREAD

**Issue by Likangkang08** [seleniumbase/SeleniumBase#783]
![微信截图_20210118154854](https://user-images.githubusercontent.com/22090651/104886772-40688680-59a5-11eb-913f-f2ad39f1a01d.png)
![微信截图_20210118154958](https://user-images.githubusercontent.com/22090651/104886790-49595800-59a5-11eb-88d9-613342df5ab0.png)

**Comment by mdmintz** [comment]
@Likangkang08 There's no need to change the fixture level. You can already use it within a class like this:

```python
# "sb" pytest fixture test in a method inside a class
class Test_SB_Fixture():
    def test_sb_fixture_inside_class(self, sb):
        sb.open("https://google.com/ncr")
        sb.type('input[title="Search"]', 'SeleniumBase\n')
        sb.click('a[href*="github.com/seleniumbase/SeleniumBase"]')
        sb.click('a[title="examples"]')
```

**Comment by Likangkang08** [comment]
![image](https://user-images.githubusercontent.com/22090651/104924276-2c8a4800-59d8-11eb-89f1-040f965befe2.png)
Thank you for your reply，When I only want to run setup once, I can’t do it

**Comment by mdmintz** [comment]
@Likangkang08 Create a special test that runs before all tests. You can use pytest-ordering for that: Then add ``@pytest.mark.run(order=1)`` before that test.

```python
import pytest
class Test_Class():
    @pytest.mark.run(order=1)
    def test_abc(self, sb):
        sb.open("https://google.com/ncr")
        ....
```

Then use ``--reuse-session`` / ``--rs`` if tests running after that need to reuse the browser session. Without ordering, tests are run alphabetically.

**Comment by Likangkang08** [comment]
Thank you for your reply, my problem was solved perfectly.

**Comment by Likangkang08** [comment]
By the way, what do you think of Microsoft's Playwright, which seems very popular

**Comment by mdmintz** [comment]
@Likangkang08 Glad to hear that solved your problem.
There are a lot of popular test frameworks out there. I'm focused on SeleniumBase.
