### ISSUE TITLE
Hi, how many ways do seleniumbase support parameterization, which way do you think is the best?

### ISSUE THREAD

**Issue by ItTestKing** [seleniumbase/SeleniumBase#794]
This is the parameterized method I use at present, but since TrunPage does not inherit Basecase directly, it cannot call BaseCe's methods by association when writing。
![image](https://user-images.githubusercontent.com/22090651/105936616-fa8b7c80-608e-11eb-973a-c8c7daaa7da3.png)
![image](https://user-images.githubusercontent.com/22090651/105936739-358db000-608f-11eb-9198-bee4c75a0b82.png)

**Comment by mdmintz** [comment]
Hi @ItTestKing There are a few different ways. If you're not using pytest fixtures, there's this example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py , which uses BaseCase inheritance with the parameterized library. If you are using pytest fixtures, then you'll need to follow the model from this example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_pytest_parametrize.py , which seems to be the case for you.

**Comment by ItTestKing** [comment]
Thank you for your reply, I prefer this way https://github.com/seleniumbase/SeleniumBase/blob/master/examples/parameterized_test.py, in addition, sbase convert supports converting the recorded and exported scripts into scripts supported by seleniumbase , This feature is great.

**Comment by mdmintz** [comment]
Excellent. Yes, that's a great feature. I'm guessing you learned it from this tutorial video: https://www.youtube.com/watch?v=Sjzq9kU5kOw&list=PLp9uKicxkBc5UIlGi2BuE3aWC7JyXpD3m
Let me know if you have any more questions.

**Comment by ItTestKing** [comment]
I'm sorry that I can't access YouTube and watch the video you gave me。

**Comment by mdmintz** [comment]
That video partly talked about the ``sbase convert`` command, which you already knew. All the content from those videos can be found in the SeleniumBase ReadMe files, which you already have access to, even if you can't see the video tutorials.

**Comment by ItTestKing** [comment]
Yes, your documentation is very detailed。

**Comment by mdmintz** [comment]
Thank you. I'll close this GitHub issue unless you have any more questions.

**Comment by ItTestKing** [comment]
Okay, thank you for your help.
