### ISSUE TITLE
pytest_plugin unconfigure hook should account that sb_config may not be fully initialised

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#802]
It is completely plausible that other pytest plugins exit the `configure` terminating the run, through raising an exception or calling `pytest.exit()` explicitly.  Under such circumstance seleniumbases plugin can still run, however the `sb_config` attr, will not have the `reuse_session` (as well as many others).  The plugin may be registered, but its configure is not guaranteed to run before other plugins, perhaps marking `configure` with `@pytest.hookimpl(tryfirst=True)` is a potential aid.

code: https://github.com/seleniumbase/SeleniumBase/blob/66a96d344e613686f0814c444f280381ff84e841/seleniumbase/plugins/pytest_plugin.py#L856

**Comment by mdmintz** [comment]
@symonk Sounds simple enough. Can you send me a code example of a situation where it breaks so that I can test and confirm that ``@pytest.hookimpl(tryfirst=True)`` is the best solution for this? I want to confirm that changing the order doesn't break anything else in that particular situation.

**Comment by mdmintz** [comment]
Even with scattering random ``import pytest; pytest.exit("Exit")`` throughout tests to test this, I see no issues when tests reach the ``def pytest_unconfigure():`` method because ``sb_config.reuse_session`` was already defined in ``def pytest_configure(config):``. This makes it seem like adding ``@pytest.hookimpl(tryfirst=True)`` is unnecessary. It could be an issue with another plugin that you're using, but I wouldn't know unless I see a full example.

**Comment by symonk** [comment]
@mdmintz  here is some recreatable examples (in a nutshell you cannot guarantee that your configure hook will always be run, and your unconfigure implementation assumes that.

# conftest.py
```python
pytest_plugins = ['some_plugin']
```

# some_plugin.py (an internally loaded pytest plugin - perfectly acceptible)
```python
import pytest


@pytest.hookimpl(tryfirst=True)
def pytest_configure(config):
    pytest.exit("Computer says no", returncode=2)
```

# test_something.py

```python
def test_something():
    assert True
```

```console
pytest

AttributeError: module 'seleniumbase.config' has no attribute 'reuse_session'
```

Why?

 - The unconfigure of selenium base has not executed prior to the other plugins; but seleniumbase is always assuming that when unconfigure comes around it has (unconfigure still runs under this scenario and all subsequent hooks are invoked by pluggy for each plugin registered and implementing a `pytest_unconfigure` hook.

**Comment by mdmintz** [comment]
Fixed in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.55.1
(I went with the ``hasattr`` solution)
