### ISSUE TITLE
Load firefox extension

### ISSUE THREAD

**Issue by sridharaiyer** [seleniumbase/SeleniumBase#803]
I want an ability to do something like this for firefox:

`
profile = webdriver.FirefoxProfile() 
profile.add_extension(extension='https_everywhere-2019.1.31-an+fx.xpi')
driver = webdriver.Firefox(firefox_profile=profile)
`
I see that we can use the CLI option `--extension-zip=XXX.crx` for Chrome, but unfortunuately this extension for my Chromedriver does not work. I have a similar extension for firefox but just Seleniumbase to load it.

**Comment by mdmintz** [comment]
See https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.55.1
There's a new method for loading a ``.xpi`` file:

```python
self.install_addon(xpi_file)
```

For some reason, it must be done at run-time after the browser has already spun up, unlike Chrome extensions, which must be initialized before the web browser is launched. So, load your Chrome extensions on the command-line, and load your Firefox add-ons inside the tests.

**Comment by sridharaiyer** [comment]
Thanks a ton! This is super helpful and really appreciate the quick turnaround 👍🏼😎
