### ISSUE TITLE
Error AttributeError: 'LoginPage' object has no attribute 'timeout_multiplier'

### ISSUE THREAD

**Issue by 7ranadheer** [seleniumbase/SeleniumBase#814]
I am trying to run the tests using the command as in below:
 pytest login_test.py --dashboard --html=report.html

The error I receive :
AttributeError: 'LoginPage' object has no attribute 'timeout_multiplier'. Could you help where it went wrong? The script fails at entering the email.

Note: I have not pasted  the exact URL here on purpose.

``` #login_page.py

from seleniumbase import BaseCase

class LoginPage(BaseCase):
    email_box = "name=email"
    password_box = "name=password"

    def enter_email(self, username):
        self.update_text(self.email_box, username) 



 login_test.py 

from seleniumbase import BaseCase
from login_page import LoginPage

class LoginTests(BaseCase):

    def test_login_to_app(self):
        self.open(URL)
        LoginPage().enter_email("random@gmail.com")

**Comment by mdmintz** [comment]
Hello @7ranadheer ,
The webdriver information was stored in the ``self`` of your LoginTests, but not in the ``self`` of your LoginPage class. In order to use those methods there, you would have to pass it along as well. Inheriting ``BaseCase`` in LoginPage won't help because it still needs the driver information that comes from the test. Here's a working example where I made some modifications to your code so that I could run it: (The ``self`` from the test is passed into the ``sb`` variable so that all the required information exists in the LoginPage method.

```python
from seleniumbase import BaseCase

class LoginPage():

    def enter_email(self, sb, username):
        sb.type("#user-name", username)
        sb.type("#password", "secret_sauce")

class LoginTests(BaseCase):

    def test_login_to_app(self):
        self.open("https://www.saucedemo.com/")
        LoginPage().enter_email(self, "standard_user")
        self.click('input[type="submit"]')
        self.assert_element("#inventory_container")
        self.sleep(2)
```

Alternatively, if you only need single class inheritance, you can have LoginPage inherit ``BaseCase``, and then inherit LoginPage in LoginTests instead of inheriting ``BaseCase`` there. Then you could call those methods using ``self`` because they are part of your class inheritance structure. Here's an example of that:

```python
from seleniumbase import BaseCase

class LoginPage(BaseCase):

    def enter_email(self, username):
        self.type("#user-name", username)
        self.type("#password", "secret_sauce")

class LoginTests(LoginPage):

    def test_login_to_app(self):
        self.open("https://www.saucedemo.com/")
        self.enter_email("standard_user")
        self.click('input[type="submit"]')
        self.assert_element("#inventory_container")
        self.sleep(2)
```

So pick which working format that you like best from the two versions above.

**Comment by 7ranadheer** [comment]
Thank you very much @mdmintz . Much appreciated. This really works. 
I chose the first method which is close to Page Objects model where actions on the page can be defined well within the class.

**Comment by mdmintz** [comment]
Great to hear! I'll close this.

**Comment by mdmintz** [comment]
@7ranadheer I improved the error output in seleniumbase 1.55.5 in case anyone else runs into that issue:

```
>           raise OutOfScopeException(message)
E           seleniumbase.common.exceptions.OutOfScopeException: 
E            It looks like you are trying to call a SeleniumBase method
E            from outside the scope of your test class's `self` object.
E            When using page objects, be sure to pass the `self` object
E            from your test class into your page object methods so that
E            they can call BaseCase class methods with all the required
E            variables, which are initialized during the setUp() method
E            that runs automatically before all tests called by pytest.
E            The `self` object is where all test variables are defined.

../seleniumbase/fixtures/base_case.py:6009: OutOfScopeException
```

**Comment by hungdao-testing** [comment]
@mdmintz : although this thread is closed, but I don't know where to ask the concerns. In case, I follow the approach #1 for PageObject model which means "passing 'sb' " to the method inside the functions of page object. But then typing some builtin methods, the editor could not give suggestion. How could I achieve it (for more detail, you could refer to the code in this thread)?

**Comment by mdmintz** [comment]
@hungdao-testing If you're looking for autocompletion in a code editor within page object methods, the editor has no way of knowing what actually gets passed to the ``sb`` variable within the page object methods, so it can't offer auto-completion of methods in that situation. For the methods, see https://seleniumbase.io/help_docs/method_summary/

**Comment by hungdao-testing** [comment]
from what I tried, if  my test inherit from class BaseTest(BaseCase), and page-object also inherit from BaseCase. We have to pass `sb` into the methods inside page-object (just follow the `examples/boilerplates`: `examples/boilerplates/base_test_case.py`
`examples/boilerplates/boilerplate_test.py`
`examples/boilerplates/classic_obj_test.py`
)

Is there any way to not pass `sb` into page-object's methods but still achieve the results (auto-suggestion, code run as normal)

**Comment by mdmintz** [comment]
@hungdao-testing I suggest first building out your tests using ``BaseCase`` inheritance, then once your tests are done, copy/paste/find/replace your code into the page objects and retest. That way you still get the initial auto-completion from the code editor, and then you also get to use page objects.

**Comment by ymlilgee** [comment]
All though this thread is closed I would be grateful for some help similar to the first issue mentioned
**contactsPage.py**
`from enum import Enum

from pages.contacts.contact_properties.contactPropertiesPage import ContactPropertiesPage
from pages.contacts.exports.exportPage import ExportsPage
from pages.contacts.imports.importsPage import ImportsPage
from pages.homescreen.sidenavbar.side_nav_bar import SideNavBar
from test.base_test_case import BaseTestCase


class ContactsPage(SideNavBar, BaseTestCase):
    name_txtbox = "#form-name-filter"
    phone_txtbox = "[name='phone_filter']"
    search_btn = "//button[@class='btn btn-primary']"
    new_contact_btn = "//a[contains(.,'New Contact')]"
    toggle_dropdown = "//button[@class='btn btn-primary dropdown-toggle']"
    import_contacts_lnk = "//a[contains(.,'Import Contacts')]"
    export_contacts_lnk = "//a[contains(.,'Export Contacts')]"
    contacts_properties_lnk = "//a[contains(.,'Contact Properties')]"

    def setName(self, name):
        self.type(self.name_txtbox, name)

    def setPhoneNumber(self, phone):
        self.type(self.phone_txtbox, phone)

    def search(self):
        self.click(self.search_btn)

    def gotoContactProperties(self):
        self.click(self.toggle_dropdown)
        self.click(self.contacts_properties_lnk)
        return ContactPropertiesPage

    def gotImportContact(self):
        self.click(self.toggle_dropdown)
        self.click(self.import_contacts_lnk)
        return ImportsPage

    def gotoExportContact(self):
        self.click(self.toggle_dropdown)
        self.click(self.export_contacts_lnk)
        return ExportsPage

    def newContact(self):
        self.click(self.new_contact_btn)


class PreferredLanguage(Enum):
    CREOLE_ENGLISH = 207571
    ENGLISH = ''
    FRENCH = ''


class PreferredChannel(Enum):
    VOICE = 1
    SMS = 2`

**addNewContactPage.py**
`from seleniumbase import BaseCase
from test.base_test_case import BaseTestCase
from pages.contacts.contacts.contactsPage import ContactsPage


class AddNewContactPage(ContactsPage, BaseTestCase):
    phone_number_txt = "#phone"
    contact_name_txt = "//label[contains(text(), 'Name')]/following-sibling::input"
    location_txt = "//label[contains(text(), 'Location')]/following-sibling::input"
    preferred_language_selector = "[name='preferred_language']"
    voice_chkbox = "[name='receive_voice']"
    sms_chkbox = "[name='receive_sms']"
    comment_txtbox = "//label[contains(text(), 'Comments')]/following-sibling::input"
    receive_outbound_campaigns_chkbox = "[title='Contact should receive Outbound Campaigns addressed to All Contacts, " \
                                        "or Groups containing this contact:'] "
    date_selector = "#block-date-input-1"  # todo add a method for this later(yet to implement)
    preferred_channel_selector = "[name='preferred_content_type']"
    groups_selector = "//input[@class='select2-search__field']"  # todo implement later
    add_contact_button = "(//button[contains(text(), 'Add Contacts')])"
    cancel_button = '(//a[contains(text(), "Cancel")])'

    def setComment(self, comment):
        self.type(self.comment_txtbox, comment)

    def set_contact_name(self, name):
        self.type(self.contact_name_txt, name)

    def set_contact_phone_number(self, phone):
        self.type(self.phone_number_txt, phone)

    def set_comment(self, comment):
        self.type(self.comment_txtbox, comment)

    def set_location(self, location):
        self.type(self.location_txt, location)

    def set_preferred_language(self, pref_language):
        return self.select_option_by_value(self.preferred_language_selector, pref_language)

    def set_preferred_channel(self, pref_channel):
        self.select_option_by_value(self.preferred_channel_selector, pref_channel)

    def set_voice_chkbox(self):
        self.click(self.voice_chkbox)

    def set_sms_chkbox(self):
        self.click(self.sms_chkbox)

    def set_receive_outbound_campaigns_chkbox(self):
        self.click(self.receive_outbound_campaigns_chkbox)

    def set_comment_text(self, comments):
        self.type(self.comment_txtbox, comments)

    def add_contact(self):
        self.click(self.add_contact_button)

    def cancel_contact(self):
        self.click(self.cancel_button)

    def add_contact_details(self, name, phone, comment):
        self.set_contact_name(name)
        self.set_contact_phone_number(phone)
        self.set_comment(comment)

    def select_enable_channels(self):
        pass
`
tc_test_contacts.py
`import pytest
from seleniumbase import BaseCase
from pages.contacts.contacts.addNewContactPage import AddNewContactPage
from pages.contacts.contacts.contactsPage import ContactsPage, PreferredLanguage, PreferredChannel
from test.base_test_case import BaseTestCase


class ContactsPageTest(ContactsPage, BaseTestCase):
    contact = AddNewContactPage()
    pref_language = PreferredLanguage
    pref_channel = PreferredChannel

    @pytest.mark.skip
    def test_search_contact_by_name(self):
        self.login()
        self.gotoContacts()
        self.setName("some name here")
        self.search()
        # todo add assertions to check if name was returned in the results

    @pytest.mark.skip
    def test_search_contact_by_number(self):
        self.login()
        self.gotoContacts()
        self.setPhoneNumber("23300000000")
        self.search()
        # todo add assertions to check if Phone Number was returned in the results

    def test_add_new_contact(self):
        self.login()
        self.gotoContacts()
        self.newContact()
        self.contact.add_contact_details("George Test", "05412345678", "This is  a Test comment")
        self.contact.select_enable_channels()
        self.contact.set_preferred_language(self.pref_language.CREOLE_ENGLISH.value)
        self.contact.set_preferred_channel(self.pref_channel.VOICE.value)
        self.contact.add_contact()
`
**base_test_case.py**
`import namegenerator
from seleniumbase import BaseCase
import dotenv
import os
import unittest

dotenv.load_dotenv()


class BaseTestCase(BaseCase, unittest.TestCase):

    url = os.getenv('URL')
    admin_url = os.getenv('ADMIN_URL')
    email = os.getenv('EMAIL')
    new_email = os.getenv('NEW_EMAIL')
    password = os.getenv('PASSWORD')
    contact_number = os.getenv('CONTACT_NUMBER')
    contact_name = os.getenv('CONTACT_NAME')
    language_id = os.getenv('LANGUAGE_ID')


    #web elements for login page
    select_email = "#email"
    select_password = "#password"
    click_on_login = "//input[@value='Submit']"

    #web elements for logging out
    account_tab = "//li[contains(@data-key,'account-settings')]"
    click_to_logout = "//a[contains(@href,'logout')]"

    #web elements for admin login page
    enter_email = '[name="email"]'
    enter_password = '[name="password"]'
    click_to_login = '//button[@type="submit"]'

    #web elements for popups
    alert_box_selector = ".alert-heading"


    def setUp(self):
        super(BaseTestCase, self).setUp()
        # <<< Add custom setUp code for tests AFTER the super().setUp() >>>

    def tearDown(self):
        self.save_teardown_screenshot()
        # <<< Add custom tearDown code BEFORE the super().tearDown() >>>
        super(BaseTestCase, self).tearDown()

    def admin_login(self):
        self.open(self.admin_url + 'auth/login')
        self.click(self.enter_email)
        self.update_text(self.enter_email, self.email)
        # self.click(self.select_password, self.password)
        self.update_text(self.enter_password, self.password)
        self.click(self.click_to_login)


    def login(self):
        # <<< Placeholder. Add your code here. >>>
        # Reduce duplicate code in tests by having reusable methods like this.
        # If the UI changes, the fix can be applied in one place.


        self.open(self.url)
        self.maximize_window()
        self.click(self.select_email)
        self.update_text(self.select_email, self.email)
        #self.click(self.select_password, self.password)
        self.update_text(self.select_password, self.password)
        self.click(self.click_on_login)

    #Logout from the viamo platform
    def logout(self):
        self.click(self.account_tab)
        self.click(self.click_to_logout)

    def example_method(self):
        # <<< Placeholder. Add your code here. >>>
        pass

    def email_generator(self):
        return namegenerator.gen()+"@gmail.com"

    def get_alert_box_text(self):
        return self.get_text(self.alert_box_selector)`

**Error**
`   AttributeError: 'AddNewContactPage' object has no attribute 'timeout_multiplier'
contacts_test/tc_contacts_test.py::ContactsPageTest::test_add_new_contact - AttributeError: 'AddNewContactPage' object has no attribute 'timeout_multiplier'
`

**Comment by mdmintz** [comment]
@ymlilgee Some of your class definitions are using double inheritance, so it's likely that you're overriding important objects due to variable conflicts. Try using single inheritance for your classes and see if that resolves your issue. ``BaseCase`` already inherits ``unittest.TestCase``, so you shouldn't be inheriting both of those at the same time, or else you might override the SeleniumBase setUp() method, where ``timeout_multiplier`` is defined.

**Comment by amitbidlan** [comment]
Hi @mdmintz The conversation is closed but I don't know where else should I post it.  I am web scraping the data and using flask to call it as an API but I get the error: 
**"raise OutOfScopeException(message)
seleniumbase.common.exceptions.OutOfScopeException: 
 It looks like you are trying to call a SeleniumBase method
 from outside the scope of your test class's `self` object,
 which is initialized by calling BaseCase's setUp() method.
 The `self` object is where all test variables are defined.
 If you created a custom setUp() method (that overrided the
 the default one), make sure to call super().setUp() in it.
 When using page objects, be sure to pass the `self` object
 from your test class into your page object methods so that
 they can call BaseCase class methods with all the required
 variables, which are initialized during the setUp() method
 that runs automatically before all tests called by pytest."**

Here is my code: 
```
from selenium import webdriver
from seleniumbase import BaseCase
from flask import Flask, jsonify

# Initialize Flask app
app = Flask(__name__)

class Job:
    def __init__(self, type_of_job, company_name, job_title, salary, traffic, working_hours, detailed_url, image_url):
        self.type_of_job = type_of_job
        self.job_title = job_title
        self.company_name = company_name
        self.salary = salary
        self.traffic = traffic
        self.working_hours = working_hours
        self.detailed_url = detailed_url
        self.image_url = image_url

class OverrideDriverTest(BaseCase):
    def get_new_driver(self, *args, **kwargs):
        """Override get_new_driver() to customize WebDriver options."""
        options = webdriver.ChromeOptions()
        # options.add_argument('--headless')  # Commented out for debugging
        options.add_argument("--disable-3d-apis")
        options.add_argument("--disable-notifications")
        options.add_argument("--lang=en")
        if self.headless:
            options.add_argument("--headless=new")
            options.add_argument("--enable-gpu")
        options.add_experimental_option(
            "excludeSwitches", ["enable-automation", "enable-logging"],
        )
        prefs = {
            "translate_whitelists": {"ja": "en"},
            "translate": {"enabled": "true"}
        }
        options.add_experimental_option("prefs", prefs)
        return webdriver.Chrome(options=options)
    
    def fetch_jobs(self):
        self.demo_mode = True
        self.open("Some URL")
        self.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        self.scroll_to_element(".TM-adnetJobCassette__inner")
        elements = self.find_elements(".TM-adnetJobCassette.js-recordJobSeenCassette")
        
        jobs = []
        for element in elements:
            type_of_job = element.find_element("css selector", ".TM-adnetJobCassette__tag").text
            company_name = element.find_element("css selector", ".TM-adnetJobCassette__company").text
            job_title = element.find_element("css selector", ".TM-adnetJobCassette__jobTtl").text
            
            try:
                miscellaneous = element.find_elements("css selector", ".TM-adnetJobCassette__recruitInfoTbl--txt")
                salary = miscellaneous[0].text
                traffic = miscellaneous[1].text
                working_hours = miscellaneous[2].text
            except IndexError:
                salary = ""
                traffic = ""
                working_hours = ""

            image_url = element.find_element("css selector", ".TM-adnetJobCassette__imgDetail--main").get_attribute("src")
            detailed_url = element.find_element("css selector", ".TM-adnetJobCassette__link").get_attribute('href')

            job = Job(type_of_job, company_name, job_title, salary, traffic, working_hours, detailed_url, image_url)
            jobs.append(job)

        return jobs

# Define route to fetch jobs and return JSON response
@app.route('/get_jobs', methods=['GET'])
def get_jobs():
    override_test = OverrideDriverTest()
    jobs_list = override_test.fetch_jobs()
    
    # Transform job objects into JSON serializable data
    jobs_data = [{'type_of_job': job.type_of_job,
                  'company_name': job.company_name,
                  'job_title': job.job_title,
                  'salary': job.salary,
                  'traffic': job.traffic,
                  'working_hours': job.working_hours,
                  'detailed_url': job.detailed_url,
                  'image_url': job.image_url} for job in jobs_list]
    
    # Return job data as JSON response
    return jsonify({'status': 'success', 'jobs': jobs_data})

# Run Flask app
if __name__ == '__main__':
    app.run(debug=True)
```
Please help me solving this issue. Thank you

**Comment by mdmintz** [comment]
@amitbidlan The `BaseCase` formats expect to be called from one of the included test runners (`pytest` or `pynose`). These tests must be "collected", and for that to happen, they must be named appropriately, eg: `def test_ABC(self):`, which starts with `test_`. You used `def fetch_jobs(self):`, which isn't of the correct format, and therefore wasn't initialized via the automatic `setUp()` method, and so you wouldn't be able to call the methods from `self`.

Try using [SeleniumBase Syntax Format 21](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_21) instead. (One of the [23 Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md))

**Comment by amitbidlan** [comment]
@mdmintz Thank you very much for your reply. It worked like a charm.
