### ISSUE TITLE
Real device native app or device browser automation or Appium integration

### ISSUE THREAD

**Issue by sridharaiyer** [seleniumbase/SeleniumBase#817]
Hello Team

Is there any plan for real device native app or device browser automation or Appium integration?

**Comment by mdmintz** [comment]
Hello @sridharaiyer See SeleniumBase mobile mode, which lets you simulate any mobile device in a web browser: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/mobile_testing.md

**Comment by mdmintz** [comment]
Hello @sridharaiyer See SeleniumBase mobile mode, which lets you simulate any mobile device in a web browser: https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/mobile_testing.md

**Comment by sridharaiyer** [comment]
Actually I want to be able to run SeleniumBase on a real mobile device native app or real mobile device browser - like Safari on iOS or Chrome on Android.

**Comment by mdmintz** [comment]
To quote the answer from https://saucelabs.com/blog/can-selenium-be-used-for-mobile-testing =>

“You cannot use Selenium for mobile app testing, but there are frameworks based on Selenium especially created for mobile automated testing. You can still use Selenium for mobile website testing.”

These frameworks are: Selendroid and Appium.

My answer is pretty much in agreement with them. It would require a major effort to add native mobile app testing to SeleniumBase. We're focused on website testing, which includes mobile website testing using Chromium's mobile device emulator.

**Comment by sridharaiyer** [comment]
I agree on the "major effort to add native mobile app testing to SeleniumBase". However, Chromium's mobile device emulator -is again not the same as iOS Safari/Chrome or Android Chrome. As these browsers reside on the real device themselves, they are in a way, native apps. So I guess, SeleniumBase currently doesn't support any form of native app testing. Which is a good answers I can start adopting Appium for this purpose. Nevertheless, please accept my heartiest appreciation for your entire team for they have done a tremendous job with the SeleniumBase library!!

**Comment by mdmintz** [comment]
Thank you! I'll close this by saying that SeleniumBase mobile mode is the best solution that we have right now.
