### ISSUE TITLE
Trying to click on a "fake" dropbox down box.

### ISSUE THREAD

**Issue by bschollnick** [seleniumbase/SeleniumBase#822]
Sorry, I'm lost here, and I'm hoping you can assist...

The web page in question has this code:

![image](https://user-images.githubusercontent.com/979558/108758562-40662400-7519-11eb-975d-71fdc3269936.png)

So it's using SPANs to simulate a pull-down input, and running the jQuery function to make the change.

But I've tried three different ways to interact with the pull-down with no luck:

- self.select_option_by_text("input#ddlActive", "All"), results in UnexpectedTagNameException
- self.click("span.k-input").type("All\n"), which results in a NoneType has no attribute Type, which makes sense...
- self.click("span.k-input")
   self.type("span.k-input", "All\n"), results in selenium.common.exceptions.InvalidElementStateE.. presumably because it's not a *true* input.

So I'm a bit uncertain on how to flip this pseudo  drop down...  Any suggestions you can give would be appreciated, especially since I can't change the web site, it's out of my control.

**Comment by mdmintz** [comment]
A few different issues with your code samples based on the html you displayed:

Issue 1: ``self.select_option_by_text("input#ddlActive", "All")`` requires a ``select`` tag for the first argument. (You had an ``input`` tag.)

Issue 2:   ``self.click("span.k-input").type("All\n")`` is invalid syntax because you can't chain commands like that. Those must be two separate SeleniumBase commands on different lines.

Issue 3:

```python
self.click("span.k-input")
self.type("span.k-input", "All\n")
```

is invalid because you're treating a ``span`` tag as an ``input`` tag. If you want to type text into a text field, you should have an ``input`` tag or a ``textarea`` tag.

Also the ``input`` field in the html you pasted has a ``style="display: none;"``, so you'll need to make it unhidden first (looks like you're already trying to do that).

**Comment by bschollnick** [comment]
@mdmintz I realize that my attempts didn't work, that's one reason I'm asking for some guidance.  
Please remember, I can't change the HTML.  It's out of my control.  Or at least I can't change the website, in theory, I could try to change the DOM values, but that's something I haven't done, especially not via Seleniumbase.

So with that in mind, what can I use in Seleniumbase to control that non-select pull-down.  I just simply don't see anything that I recognize as being able to work.  _I can use the self.click to select the span_ which pops up the pseudo-select, but then I don't have any way to select anything, since it's not really a select?  

I tried a variation of something I've done elsewhere in the web site:.  

self.click("span.k-input")
self.click("span:contains('All')")
That results in an ElementNotVisibleException... Even though the span that contains "All" is visible (because of the first click), it's not visible to SB.

So I'm really trying to figure out what can be done to kludge something that works...  
If it can't be done, then it can't be done.  

But even if there someway to manipulate it via javascript/jquery, it'll be a win.   I'm just at a loss on how to do that...

**Comment by bschollnick** [comment]
Heck, I'm about to check about getting cursor X, Y from selenium itself, and manually clicking X points lower.... >g<

**Comment by mdmintz** [comment]
Try using ``self.js_click()`` instead of ``self.click()``. And try using ``self.js_type()`` instead of ``self.type()`` in areas.
Also, you can force visibility by using ``self.show_elements(SELECTOR)``. That may or may not work. This would be much easier if it was on a public-facing website. Then I could just give you the exact code to make it work.

**Comment by bschollnick** [comment]
Okay, I'll give that a try, one thing I have been attempting is to use ActionChains...

```             self.click("span.k-input")
                from selenium.webdriver.common.action_chains import ActionChains
                #duhdropdown = self.driver.find_element_by_class_name("k-input")
                duhdropdown = self.driver.find_element_by_xpath("/html/body/section/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/div/div[3]/span/span/span[1]")
                action = ActionChains(self.driver)
                action.move_to_element(duhdropdown)
                action.move_by_offset(0,10).perform() # x, y
                action.click(None).perform()
```

Which seems to be not clicking?  Or clicking at the wrong spot.  I really wish there was someway to find out where the virtual cursor actually was >g<  Because I just can't tell if I'm off on my click positioning...

**Comment by bschollnick** [comment]
```
               from selenium.webdriver.common.action_chains import ActionChains
                #duhdropdown = self.driver.find_element_by_class_name("k-input")
                duhdropdown = self.driver.find_element_by_xpath("/html/body/section/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/div/div[3]/span/span/span[1]")
                action = ActionChains(self.driver)
                action.move_to_element(duhdropdown)
                action.move_by_offset(0,10).perform() # x, y
                action.click(None).perform()
```

Okay, got it to work.

                action.move_by_offset(0,**30**).perform() # x, y

I was too optimistic with my original 10 pt offset.  Of course, this could and probably will change with screen resolution...  But...   For now, it'll work...  

Thank you for your assistance, if I might suggest exposing an click_offset or click_at routine that does something to this effect?

**Comment by mdmintz** [comment]
Great to hear! I'd need to see a live example to add an example test for this. There might be an easier solution, but a working solution is still a working solution. :)
