### ISSUE TITLE
Seleniumbase broadly catches Exception, often hiding the true underlying issues for users to debug

### ISSUE THREAD

**Issue by symonk** [seleniumbase/SeleniumBase#823]
An example of this is outlined below, the reason I am writing this issue is I am investigating some connectivity issues between a selenium hub / grid nodes, however when connection issues arise selenium base indicates failure for another reason and only when trawling through tons of logs (project implementation specific) that I can see the real issue.  I put this down to broadly catching `Exception` far too much.

Example method:

```python
# page_utils, is_element_visible check -> catching base Exception..

def is_element_visible(driver, selector, by=By.CSS_SELECTOR):
    """
    Returns whether the specified element selector is visible on the page.
    @Params
    driver - the web driver object (required)
    selector - the locator for identifying the page element (required)
    by - the type of selector being used (Default: By.CSS_SELECTOR)
    @Returns
    Boolean (is element visible)
    """
    try:
        element = driver.find_element(by=by, value=selector)
        return element.is_displayed()
    except Exception:
        return False
```

I won't be able to show an example using a selenium grid, but the same small example highlights the problem and selenium base should not be hiding them errors from the user, it should be catching some higher level web driver exceptions, appropriate to the function it is attempting.

Example:

```python
def test_masked_debug_info(sb):
    sel = ("??", By.ID)
    sb.driver.quit()
    # This shouldn't (really) return False, it is hiding a genuine error/issue from the user.
    sb.is_element_visible(*sel)
```

In this particular instance, the user has absolutely no idea that this has occurred:

```
MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=50338): 
Max retries exceeded with url: /session/d548644966d1f69964e636131971fa98/element 
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1080f50d0>: 
Failed to establish a new connection: [Errno 61] Connection refused'))")
```

The problem here is, a test has hit connectivity related issues, but the test to any developer investigating their failures looks like a particular element was not visible, which is not true. (Time sink then occurs trying to figure out what the problem was on false pretenses)

I know this is a trivial example, but you get the idea, maybe you disagree but as a heavy user of seleniumbase this causes me a massive problem in classifying test failure/defect issues correctly

**Comment by mdmintz** [comment]
@symonk Error handling improved in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.55.7

**Comment by symonk** [comment]
I admire your response @mdmintz, very speedy! I will verify the changes tomorrow

**Comment by mdmintz** [comment]
Marking this issue as resolved. Latest version of SeleniumBase is https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.56.0
Let me know if you have any more issues.
