### ISSUE TITLE
Suggestions for SOPA/REST API automation?

### ISSUE THREAD

**Issue by sridharaiyer** [seleniumbase/SeleniumBase#825]
Hi
Can you recommend any awesome library just as yours for me to do API testing of either SOAP/RESTful Web Services? This is instead of me writing boilerplate on top of the requests package.

**Comment by mdmintz** [comment]
My specialty is web automation and testing of web apps through web interfaces. REST APIs are in a completely different world, so you'll probably find your answers elsewhere.
