### ISSUE TITLE
is button enabled

### ISSUE THREAD

**Issue by jfoxai** [seleniumbase/SeleniumBase#837]
Hello, how can i check that button is enabled?
in selenium is_enabled() method present, but didn't find equivalent in seleniumbase

**Comment by mdmintz** [comment]
@jfoxai Here's an example:

```
...
self.open("https://store.xkcd.com/search")
print(self.get_element("input#search-submit").is_enabled())
...
```

You can use ``self.get_element(selector)`` to first get the element; and then ``.is_enabled()`` to return whether that element is enabled.

**Comment by jfoxai** [comment]
@mdmintz cool, it works, thank you!
but didn't get it from documentation https://seleniumbase.io/help_docs/method_summary/  may be should update it

**Comment by mdmintz** [comment]
@jfoxai OK, great. The method summary lists SeleniumBase methods, but that is a WebElement method. I can probably add a SeleniumBase method for that in the next release.

**Comment by mdmintz** [comment]
I added ``self.is_element_enabled(selector)`` in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.57.1
