### ISSUE TITLE
Issue with select element from drop down

### ISSUE THREAD

**Issue by Manu-07** [seleniumbase/SeleniumBase#839]
I'm trying to perform select a country from dropdown using selenium base it's not working can you help me with that.

**Comment by mdmintz** [comment]
Hi @Manu-07 , there's an example of that here: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/test_demo_site.py

```python
self.select_option_by_text("#mySelect", "Set to 75%")
```

**Comment by Manu-07** [comment]
Thank You, Michael.
