### ISSUE TITLE
Prevent duplicate setUp() and tearDown() calls in the same test

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#884]
Prevent duplicate setUp() and tearDown() calls in the same test. (From incorrect usage)

As most SeleniumBase users know, ``setUp()`` is automatically called before the start of each test, and ``tearDown()`` is automatically called at the end of each test. (This is where the web browser is automatically spun up for tests in the beginning and spun down at the end.) That doesn't prevent people from accidentally calling ``self.setUp()`` and ``self.tearDown()`` on their own, which can lead to unexpected behavior. To improve this situation, let's change the behavior so that ``setUp()`` isn't called again if it was already called, and ``tearDown()`` isn't called again if it was already called. (Calling ``tearDown()`` should reset the state so that ``setUp()`` can be called again in the same test if necessary.)

**Comment by thanhvodad** [comment]
Can you elaborate on the syntax in a demo?

**Comment by mdmintz** [comment]
It's a preventative measure. Someone might accidentally call ``self.tearDown()`` on their own in a test. But that is already done automatically at the end of every test.
