### ISSUE TITLE
How to setup seleniumbase to github buildpipeline

### ISSUE THREAD

**Issue by Manu-07** [seleniumbase/SeleniumBase#885]
I have written some test cases using  seleniumbase want to integrate it to github build pipeline please provide any helpdocs if you have

**Comment by mdmintz** [comment]
@Manu-07 See: https://github.com/seleniumbase/SeleniumBase/blob/master/integrations/github/workflows/ReadMe.md

**Comment by Manu-07** [comment]
Thanks, I'll check it out.
