### ISSUE TITLE
How to take screenshot of full page?

### ISSUE THREAD

**Issue by abhishal76** [seleniumbase/SeleniumBase#897]
I want to take screenshot of full screen and compare whole page. In check_window(), how do i check?

**Comment by abhishal76** [comment]
Ohh ok @mdmintz , so you mean to say check_window() will check tags/attributes/values of whole page? not only of the screenshot ? in below sample case- 

class VisualLayoutTests(BaseCase):
    def test_applitools_layout_change(self):
        self.open("https://applitools.com/helloworld?diff1")
        print('\nCreating baseline in "visual_baseline" folder.')
        self.check_window(name="helloworld", baseline=True)
        # Click a button that changes the text of an element
        # (Text changes do not impact visual comparisons)
        self.click('a[href="?diff1"]')
        # Verify html tags match the baseline
        self.check_window(name="helloworld", level=1)
        # Verify html tags and attribute names match the baseline
        self.check_window(name="helloworld", level=2)
        # Verify html tags and attribute values match the baseline
        self.check_window(name="helloworld", level=3)
        # Click a button that makes a hidden element visible
        self.click("button")
        self.check_window(name="helloworld", level=1)
        self.check_window(name="helloworld", level=2)
        with self.assertRaises(Exception):
            self.check_window(name="helloworld", level=3)
        # Now that we know the Exception was raised as expected,
        # let's print out the comparison results by running a Level-0 check.
        # (NOTE: Running with level-0 will print but NOT raise an Exception.)
        self.check_window(name="helloworld", level=0)

**Comment by mdmintz** [comment]
@abhishal76 Yes, it will check tags/attributes/values of whole page, like in the example.

**Comment by abhishal76** [comment]
@mdmintz is there a method with draws out difference on Page when it detects difference in tags/attributes/values.

Thank You

**Comment by mdmintz** [comment]
@abhishal76  There's the baseline screenshot, and the screenshot that is taken for a test failing due to not matching the baseline, but other than seeing the differences in the tags/attributes/values by text, there is nothing that draws out those differences on the last screenshot.

**Comment by abhishal76** [comment]
@mdmintz is there a way to ignore some tags when comparing with level=3 ? e.g i don't want to compare tags and value of <script> html tag

**Comment by mdmintz** [comment]
@abhishal76 See if one of the following methods can remove the tags that you don't want before saving a baseline or doing a tag comparison:

```python
self.remove_element(selector)  # Remove the first matching selector

self.remove_elements(selector)  # Remove all matching selectors
```

**Comment by abhishal76** [comment]
Ohh wow, Thank you
