### ISSUE TITLE
How to use self.open('url') method to open URL with custom headers?

### ISSUE THREAD

**Issue by abhishal76** [seleniumbase/SeleniumBase#898]
I want to add headers to my URL. how can i add to self.open()?

**Comment by mdmintz** [comment]
@abhishal76 , The ``self.open('url')`` method will navigate to the URL of your choice in the web browser. It does not change the page, so I don't understand what you mean by opening the page with custom headers. You can open any URL.

**Comment by abhishal76** [comment]
@mdmintz  i want to navigate to URL with custom headers using self.open() method

**Comment by mdmintz** [comment]
@abhishal76 The one argument for ``self.open(url)`` is the URL. That's all you can set.

**Comment by mdmintz** [comment]
@abhishal76  Not sure if you mean "User Agent" when you say "Custom Headers", but if that's what you mean, you can add ``--agent="STRING"`` on the ``pytest`` run command to set your user agent before navigating to the URL.

**Comment by abhishal76** [comment]
@abhishal76  scenario is i need to compare screens in Production with screen in test environment.

self.open(Production)
self.check_window(name="python_home", baseline=True)
self.open(Test env)
self.check_window(name="python_home", level=3)

so to open Test env URL i need pass headers. Is there a way i can do that ?

**Comment by mdmintz** [comment]
@abhishal76 As seen in https://stackoverflow.com/a/44588777 , you may be able to use the format of "http://user:password@URL" in order to pass in authentication headers to the ``self.open()`` method.

**Comment by abhishal76** [comment]
`import requests

response = requests.get(
    'https://api.github.com/search/repositories',
    params={'q': 'requests+language:python'},
    headers={'Accept': 'application/vnd.github.v3.text-match+json'},
)

# View the new `text-matches` array which provides information
# about your search term within the results
json_response = response.json()
repository = json_response['items'][0]
print(f'Text matches: {repository["text_matches"]}')`

looking something like request library

**Comment by abhishal76** [comment]
ok thank you @mdmintz

**Comment by abhishal76** [comment]
@mdmintz  do you mind sharing an example of
 --cap-file=FILE  # (The web browser's desired capabilities to use.)
--cap-string=STRING  # (The web browser's desired capabilities to use.)

**Comment by mdmintz** [comment]
@abhishal76 There are a few examples here: https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities

**Comment by abhishal76** [comment]
@mdmintz  is there a workaround you can suggest to open a URL with headers? I really want this working to access Test environment URL :(

**Comment by mdmintz** [comment]
@abhishal76 You might have to use the ``requests`` library for that.

**Comment by abhishal76** [comment]
@mdmintz yea requests works, but need to use in self.open() to capture and compare with level=3

**Comment by abhishal76** [comment]
@mdmintz The allure report is not attaching the screenshot on failure, can you please provide workaround ?

**Comment by mdmintz** [comment]
@abhishal76 The pytest html reports includes the screenshots (not the allure reports).
Use ``--html=report.html`` to get an html report with your ``pytest`` run command. Additionally, you can use ``--dashboard`` to see the dashboard. If you combine ``--html=report.html`` with ``--dashboard``, then the html report will also include the pie chart from the dashboard.
