### ISSUE TITLE
Allow SeleniumBase to perform visual testing between two separate tests

### ISSUE THREAD

**Issue by PyShaman** [seleniumbase/SeleniumBase#903]
As a tester
I want to be able to perform baseline scan and level 1, 2, 3 scan with two different test scenarios
So that I will be able to compare changes in the application before and after new deployment of the application that I am testing

**Comment by mdmintz** [comment]
Released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.63.5

**Comment by mdmintz** [comment]
The fix above changes the naming of the baseline folder so that only the test name and baseline name need to match in order for a visual layout comparison to be made. (The file name and class name can be different)
