### ISSUE TITLE
[Query] Could you please add --protocol option for remote browser 

### ISSUE THREAD

**Issue by traxxzz** [seleniumbase/SeleniumBase#906]
Hi! 
I would like to suggest adding a new option into core/browser_launcher.py::get_remote_browser.
It is necessary for integration with those selenium grid services that require connection via https.
For example https://github.com/wrike/callisto

**Comment by mdmintz** [comment]
Hi @traxxzz There's the ``--chromium-arg=ARG`` option, which lets you add any Chromium arg for Chrome/Edge browsers, comma-separated. If an arg doesn't start with "--", that will be added to the beginning of the arg automatically.

**Comment by traxxzz** [comment]
Hi @mdmintz First of all, let me thank you for a great job. I have been using your framework for one month and it is really great.

As for the issue please take a look at how the address is formed:
`def get_remote_driver(
        browser_name, headless, locale_code, servername, port,
        proxy_string, proxy_auth, proxy_user, proxy_pass, user_agent,
        cap_file, cap_string, disable_csp, enable_ws, enable_sync,
        use_auto_ext, no_sandbox, disable_gpu, incognito, guest_mode,
        devtools, remote_debug, swiftshader, block_images, chromium_arg,
        user_data_dir, extension_zip, extension_dir, test_id,
        mobile_emulator, device_width, device_height, device_pixel_ratio):
    downloads_path = download_helper.get_downloads_folder()
    **address = "http://%s:%s/wd/hub" % (servername, port)**`

I had to patch the last line of code locally to get url like https://callisto.dev-01.localhost 
So my suggestion is adding one more option --protocol=[http|https] (default http)
Additionally I suggest to make --port optional.

**Comment by mdmintz** [comment]
@traxxzz Work completed in https://github.com/seleniumbase/SeleniumBase/pull/907 and released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.63.6
