### ISSUE TITLE
Need --firefox-arg=ARG feature

### ISSUE THREAD

**Issue by ivan-borisov** [seleniumbase/SeleniumBase#909]
For chrome, we have` --chromium-arg=ARG`
It will be good if we have similar feature for firefox.

Yes they support small number of features 
http://kb.mozillazine.org/Command_line_arguments

But some are useful like
`-profile "profile_path"`, for example it is possible to create Profile with blocked or allowed  camera and mic by default and after this use this profile in tests.

**Comment by mdmintz** [comment]
Released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.63.8

### Add options to set custom Firefox args and preferences

```
  --firefox-arg=FIREFOX_ARG,
        Add a Firefox argument for Firefox browser runs.
        Format: A comma-separated list of Firefox args.
        If an arg doesn't start with "--", that will be
        added to the beginning of the arg automatically.
  --firefox-pref=FIREFOX_PREF,
        Set a Firefox preference:value combination.
        Format: A comma-separated list of pref:value items.
        Example usage:
            --firefox-pref="browser.formfill.enable:True"
            --firefox-pref="pdfjs.disabled:False"
            --firefox-pref="abc.def.xyz:42,hello.world:text"
        Boolean and integer values to the right of the ":"
        will be automatically converted into proper format.
        If there's no ":" in the string, then True is used.
```
