### ISSUE TITLE
SelenimBase not have option for block, disable camera

### ISSUE THREAD

**Issue by ivan-borisov** [seleniumbase/SeleniumBase#910]
It will be good if is possible if selenium base have pretty way to handle this. Yes now it is possible but with usage of native selenium, in this way we lose simplification of SeleniumBase code usage

https://stackoverflow.com/questions/60829593/how-to-disable-camera-and-microphone-popup-alert-via-selenium-webdriver-tests
https://stackoverflow.com/questions/54002953/how-to-allow-or-deny-notification-of-microphone-and-camera-popup-in-firefox-usin/54003309

**Comment by mdmintz** [comment]
The ``--chromium-arg=ARG`` already exists for Chrome and Edge.

This feature was released in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.63.8 for Firefox.

### Add options to set custom Firefox args and preferences

```
  --firefox-arg=FIREFOX_ARG,
        Add a Firefox argument for Firefox browser runs.
        Format: A comma-separated list of Firefox args.
        If an arg doesn't start with "--", that will be
        added to the beginning of the arg automatically.
  --firefox-pref=FIREFOX_PREF,
        Set a Firefox preference:value combination.
        Format: A comma-separated list of pref:value items.
        Example usage:
            --firefox-pref="browser.formfill.enable:True"
            --firefox-pref="pdfjs.disabled:False"
            --firefox-pref="abc.def.xyz:42,hello.world:text"
        Boolean and integer values to the right of the ":"
        will be automatically converted into proper format.
        If there's no ":" in the string, then True is used.
```
