### ISSUE TITLE
"How to" questions

### ISSUE THREAD

**Issue by pjsgit** [seleniumbase/SeleniumBase#911]
Hi. I'm been experimenting with SB for a few weeks, setting up some testing before teaching it to a small team. I've hit a learning curve wall and have collected questions that I wish I could get answered via the doc. Here's my short list of "how to.." questions

Ask a question without being annoying

	Is filing an issue the right way to ask a question?
	Where do I look to see what has already been asked/answered?

Developing

	How to debug/print in a SB session?
	I've tried straight print() and self._print() but I get no output at the console
   
	Can I try SB commands in a repl environment so I can see what a command does?
	
Understanding the doc

	I keep coming back to https://seleniumbase.io/help_docs/method_summary/
	and wanting to see a link to example code showing the method being use.
	Is there something with example by method?

Iterate over repeating HTML

   Example: For every row in a table, know what row I am in, inspect values in different columns 
   and then click a link in a column of that table.
  
Automation
 
	Example of deploying PyTest/SB to run automatically, verifying a site
	Signal when a test fails (e.g., send an email, post a message to slack)

**Comment by mdmintz** [comment]
Hello @pjsgit ,
Opening issues is generally for things that require a code commit and/or a new release, such as a bug fix, a new feature request, a documentation request, etc. For questions, there are a few places for that:
* https://gitter.im/seleniumbase/SeleniumBase (this has been around for a few years)
* https://github.com/seleniumbase/SeleniumBase/discussions (relatively new)
* The SeleniumBase channel in the "Selenium" Slack Group - https://app.slack.com/client/T0ABCRTNX/C01SM888REZ - (I created this channel there last month to expand relations with the Selenium Slack community)

If console output from ``print()`` is not appearing, that means you either need to add ``-s`` to your ``pytest`` run command, or you need to add ``addopts = --capture=no`` to your ``pytest.ini`` file, which you should have at the root folder of your test directory. You can copy/paste the one from the SeleniumBase repo to speed things up (it also contains other useful lines). For general pytest debugging info, see: https://seleniumbase.com/the-ultimate-pytest-debugging-guide-2021/

The https://github.com/seleniumbase/SeleniumBase/tree/master/examples directory contains examples of most of the methods you'll find in method_summary. If you're looking for a specific method used in an example test, try a GitHub search of the SeleniumBase repo for the method you want.

For iterating over tables with rows, see this example: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/nth_child_test.py

GitHub Actions can be configured to run a test as soon as there's a code change or pull request. Here's what GitHub Actions looks like: https://github.com/seleniumbase/SeleniumBase/actions  And here's the config file for that: https://github.com/seleniumbase/SeleniumBase/blob/master/.github/workflows/python-package.yml

For posting a message to a Slack channel from a test running in GitHub Actions, see: https://github.com/seleniumbase/SeleniumBase/blob/master/integrations/github/workflows/extras.md (that tool was written by someone else).

If using Jenkins, there are plugins for email notifications, etc, that can be initiated from Jenkins jobs.

Most tests in the https://github.com/seleniumbase/SeleniumBase/tree/master/examples folder do some kind of website verification. The rest are tests for advanced tools such as Website Tour Maker, Chart Maker, Presentation Maker, and others.

Also extremely useful to know is how to use the SeleniumBase Dashboard: https://seleniumbase.io/examples/example_logs/ReadMe/ (if you haven't already learned about it).
