### ISSUE TITLE
How to open a new window with target=_blank keeping the same configuration ?

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#917]
How to open a new window with target=_blank keeping the same configuration ?
When I try setting the parameters UA, Screen, Mobile but when accessing the _blank link, it returns to the default parameters in windows instead of the necessary parameters --agent, --metrics. Is there any way to fix this problem?

**Comment by mdmintz** [comment]
@thanhvodad 
```python
self.get_new_driver(
    browser=None, headless=None, locale_code=None,
    servername=None, port=None, proxy=None, agent=None,
    switch_to=True, cap_file=None, cap_string=None,
    disable_csp=None, enable_ws=None, enable_sync=None,
    use_auto_ext=None, no_sandbox=None, disable_gpu=None,
    incognito=None, guest_mode=None,
    devtools=None, remote_debug=None,
    swiftshader=None, block_images=None, user_data_dir=None,
    extension_zip=None, extension_dir=None, is_mobile=None,
    d_width=None, d_height=None, d_p_r=None)
```

Specify ``is_mobile`` (use ``True``), ``agent``, ``d_width``, ``d_height``, and ``d_p_r`` (which is device-pixel-ratio). More details here: https://seleniumbase.io/help_docs/mobile_testing/

**Comment by mdmintz** [comment]
@thanhvodad 
You can also prevent the opening of a new window by using:
``self.set_attributes('[target="_blank"]', "target", "_self")`` before clicking on the link that opens a new window. (After calling that method, you'll now stay in the same window.)

**Comment by thanhvodad** [comment]
please give me an example self.get_new_driver , every time i click new tab cant get the parameters that i entered...

**Comment by mdmintz** [comment]
@thanhvodad Here's an example test that uses it: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/github_test.py
If you need to click on a target=_blank though, use:
``self.set_attributes('[target="_blank"]', "target", "_self")``
