### ISSUE TITLE
How can I set the browser timezone

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#918]
How can I set the browser timezone ?
Thanks SUpportr

**Comment by mdmintz** [comment]
@thanhvodad Try adding this to your script: (example)
```python
tz_params = {'timezoneId': 'America/New_York'}
self.driver.execute_cdp_cmd('Emulation.setTimezoneOverride', tz_params)
```
(From https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setTimezoneOverride)

**Comment by thanhvodad** [comment]
How can I pass parameters from run command pytest abc.py birthday=abcxyz
ex:
`def test_demo_site(self, birthday):`
self.open("https://whoer.net/" birthday)

**Comment by mdmintz** [comment]
@thanhvodad There are a few predefined variable names that you can use for passing data into tests:
```python
--data=DATA  # (Extra test data. Access with "self.data" in tests.)
--var1=DATA  # (Extra test data. Access with "self.var1" in tests.)
--var2=DATA  # (Extra test data. Access with "self.var2" in tests.)
--var3=DATA  # (Extra test data. Access with "self.var3" in tests.)
```
