### ISSUE TITLE
pip install fails on M1 arm64 Macs due to version pin cryptography==3.3.2

### ISSUE THREAD

**Issue by alexrudd2** [seleniumbase/SeleniumBase#920]
The dependency `cryptography==3.3.2` fails to install with `pip` on the new M1 macs (I'm on a MacBook Air).  The problem is documented on [StackExchange](https://stackoverflow.com/questions/66035003/installing-cryptography-on-an-apple-silicon-m1-mac).  Developer @reaperhulk posted [there](https://stackoverflow.com/a/66055389) 
`I've uploaded arm64 wheels for macOS so the below compilation is no longer required if your pip is up-to-date`. 

I'm not sure which version between `3.3.2` and `3.4.7` was the first to include these wheels, however `3.4.7` works for me using pip `21.1.2`  It doesn't appear to break anything in my SeleniumBase usage.

**Comment by mdmintz** [comment]
@alexrudd2 Merged and released in ``1.63.12``. Thanks for fixing!
