### ISSUE TITLE
how to check the displayed div visible

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#928]
I execute a piece of javascript, write html.
setTimeout(function(){
			`$('#info-contents').html("<div` id='hit_view_done'>hit_view_done</div>");`
		}, 50000);

How to wait when #hit_view_done visible and tearDown

**Comment by mdmintz** [comment]
@thanhvodad To wait for an element to be visible, you can use:
``self.wait_for_element(selector)``
(default ``timeout`` = ``10`` seconds, but that can be changed)

If you're asking about customizing the ``tearDown()`` method, see Syntax Format Number 2 here: https://seleniumbase.io/help_docs/syntax_formats/

**Comment by thanhvodad** [comment]
how to process JSON string into test
I enter --var1={...json...}
how to make tests, can handle json, i tried but it doesn't work,

**Comment by mdmintz** [comment]
@thanhvodad 
```bash
--data=DATA  # (Extra test data. Access with "self.data" in tests.)
--var1=DATA  # (Extra test data. Access with "self.var1" in tests.)
--var2=DATA  # (Extra test data. Access with "self.var2" in tests.)
--var3=DATA  # (Extra test data. Access with "self.var3" in tests.)
```
The optional command-line arguments above will get passed as a string. You can then process that string as you want using Python within your tests.
