### ISSUE TITLE
any solution to connect socks5 with auth

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#931]
How to connect socks5 with auth, I tried many ways but it doesn't work

**Comment by mdmintz** [comment]
@thanhvodad The available socks5 format is:
```bash
pytest --proxy="socks5://IP_ADDRESS:PORT"
```

**Comment by thanhvodad** [comment]
But I run with user and pass, how do I enter with socks 5

**Comment by mdmintz** [comment]
@thanhvodad The closest solution I've found is https://stackoverflow.com/a/55395796 , which uses https://github.com/qwj/python-proxy . There's no direct way to do it, as seen from https://stackoverflow.com/questions/43312573/how-to-set-socks5-proxy-with-auth-for-chrome-in-selenium-python
