### ISSUE TITLE
How to block some specific image formats

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#932]
I tried --block-images, but now it is blocking google analytics, how can I block images of some specific format, With below code how can I apply it to pytest , give me an example of ChromeOptions
`
option = webdriver.ChromeOptions()
chrome_prefs = {}
option.experimental_options["prefs"] = chrome_prefs
chrome_prefs["profile.default_content_settings"] = {"images": 2}
chrome_prefs["profile.managed_default_content_settings"] = {"images": 2}
browser = webdriver.Chrome(chrome_options=option)
`

**Comment by mdmintz** [comment]
@thanhvodad If you want to add custom Chromium args from pytest, there's:
``--chromium-arg="ARG,ARG"`` (Comma-separated list)
Additionally, you can set custom behavior by adding a Chrome extension that blocks things the way you want. To load a Chrome extension, there are two ways:
``--extension-zip=ZIP`` (Load a Chrome Extension .zip\|.crx, comma-separated.)
``--extension-dir=DIR`` (Load a Chrome Extension directory, comma-separated.)

**Comment by thanhvodad** [comment]
Is there any method for me, block images it blocks all images :(

**Comment by mdmintz** [comment]
After the page has loaded, you can use the following methods to hide or remove elements that you don't want on the page during automation:
```bash
self.hide_elements(selector)
self.remove_elements(selector)
```
