### ISSUE TITLE
Take a screenshot in the TearDown function

### ISSUE THREAD

**Issue by pengyouak** [seleniumbase/SeleniumBase#939]
def test_something(self):
        self.test_case_id='test_01'
        # some code
        self.assert_true(1>2)

    def tearDown(self):
        super().tearDown()
        if self.has_exception():
            self.save_screenshot(f'spd_core_tests/screen_shots/{self.test_case_id}')

always show this error.

`driver = None, timeout = 30

def wait_for_ready_state_complete(driver, timeout=settings.LARGE_TIMEOUT):
    """
    The DOM (Document Object Model) has a property called "readyState".
    When the value of this becomes "complete", page resources are considered
      fully loaded (although AJAX and other loads might still be happening).
    This method will wait until document.readyState == "complete".
    This may be redundant, as methods already wait for page elements to load.
    If the timeout is exceeded, the test will still continue
      because readyState == "interactive" may be good enough.
    (Previously, tests would fail immediately if exceeding the timeout.)
    """
    start_ms = time.time() * 1000.0
    stop_ms = start_ms + (timeout * 1000.0)
    for x in range(int(timeout * 10)):
        shared_utils.check_if_time_limit_exceeded()
        try:
->               ready_state = driver.execute_script("return document.readyState")
E               AttributeError: 'NoneType' object has no attribute 'execute_script'

.env\lib\site-packages\seleniumbase\fixtures\js_utils.py:33: AttributeError
`

**Comment by mdmintz** [comment]
@pengyouak The ``super().tearDown()`` must be the last line of your custom ``tearDown()`` method. In your example, it was the first line. That won't work because ``super().tearDown()`` closes the web browser, and therefore you would get an error calling ``self.save_screenshot()`` because you need the browser to still be open in order to take the screenshot.

**Comment by pengyouak** [comment]
Thanks, it worked.
