### ISSUE TITLE
How to assert dynamically displayed items

### ISSUE THREAD

**Issue by pengyouak** [seleniumbase/SeleniumBase#941]
There is an input box with association function. When the text of the input box changes, a drop-down list will pop up and the data in the new list will be dynamically updated according to the input content. How can I tell if the item I'm looking for is included in the list? Using self.assert_text too fast will result in the element not being found, because the data in the list keeps changing, and I don't know when it will really end.

Please forgive me for using Google Translate.

self.type('drop down input', 'some values')      
self.sleep(1) # if you don’t sleep here, an exception will occur that the element is not found.      
self.assert_text('item text', 'drop down item')    

[gif](https://z3.ax1x.com/2021/07/15/WmzC3n.gif)

Please tell me how to solve this problem, thank you.

**Comment by mdmintz** [comment]
Hi @pengyouak, the ``self.assert_text()`` method is the correct method to use in this case. There is a default ``timeout`` value of 6 seconds to wait for the expected text to appear, but you can change that if the search is slower than that. (From your GIF, it looks like the search results stop changing after you stop typing.)
Try ``self.assert_text("text", "selector", timeout=10)`` if you need to change how long it waits.
There are also other useful methods such as:
```python
self.is_text_visible("text", "selector")
```
Let me know if changing the ``timeout`` value in ``self.assert_text()`` works.
