### ISSUE TITLE
Is there any method in combination with selenium-stealth ?

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#942]
https://pypi.org/project/selenium-stealth/
It is a library that combines with selenium to stealth over google, is there any way to integrate it into seleniumbase, it's very good

**Comment by mdmintz** [comment]
By the looks of it, you can integrate it directly into the custom ``setUp()`` method of your tests like this after you pip install it:

```python
from seleniumbase import BaseCase
from selenium_stealth import stealth

class BaseTestCase(BaseCase):
    def setUp(self):
        super().setUp()
        stealth(self.driver,
            languages=["en-US", "en"],
            vendor="Google Inc.",
            platform="Win32",
            webgl_vendor="Intel Inc.",
            renderer="Intel Iris OpenGL Engine",
            fix_hairline=True,
        )
```

It's that simple. No extra code is required on the SeleniumBase side.

**Comment by thanhvodad** [comment]
> By the looks of it, you can integrate it directly into the custom `setUp()` method of your tests like this after you pip install it:
> 
> ```python
> from seleniumbase import BaseCase
> from selenium_stealth import stealth
> 
> class BaseTestCase(BaseCase):
>     def setUp(self):
>         super().setUp()
>         stealth(self.driver,
>             languages=["en-US", "en"],
>             vendor="Google Inc.",
>             platform="Win32",
>             webgl_vendor="Intel Inc.",
>             renderer="Intel Iris OpenGL Engine",
>             fix_hairline=True,
>         )
> ```
> 
> It's that simple. No extra code is required on the SeleniumBase side.

How can I choose my custom chromedriver file?.

**Comment by mdmintz** [comment]
@thanhvodad The chromedriver used is the one that's on your system path. So if you want to use a specific chromedriver, make sure that it's the only one on the path. SeleniumBase adds the ``seleniumbase/drivers`` folder to your path when you run tests, so any driver installed there via a command such as ``sbase install chromedriver latest`` would be used before any other one that's found elsewhere. Maybe do a search for ``chromedriver`` to see all occurrences of it on your computer in case you're not sure which ones exist.

**Comment by thanhvodad** [comment]
def setUp(self):
        if self.browser == "chrome":
            super().setUp()
            stealth(
                self.driver,
                languages=["en-US", "en"],
                vendor="Google Inc.",
                platform="Win32",
                webgl_vendor="Intel Inc.",
                renderer="Intel Iris OpenGL Engine",
                fix_hairline=True,
            )
object has no attribute 'browser'
self.browser not in setup ?

**Comment by mdmintz** [comment]
@thanhvodad You can call the ``self`` commands in you setUp() method only **after** you've run ``super().setUp()``, which is on the very next line in your example.

**Comment by thanhvodad** [comment]
what will be the correct command, when i want to check if it's browe.chorme, if yes i will use stealth

**Comment by mdmintz** [comment]
@thanhvodad 

```python
def setUp(self):
    super().setUp()
    if self.browser == "chrome":
        stealth(
            self.driver,
            languages=["en-US", "en"],
            vendor="Google Inc.",
            platform="Win32",
            webgl_vendor="Intel Inc.",
            renderer="Intel Iris OpenGL Engine",
            fix_hairline=True,
        )
```

**Comment by thanhvodad** [comment]
I tried, yes seleniumbase has been caught by google automatically, I login google it will say :(

**Comment by mdmintz** [comment]
@thanhvodad If you're looking to avoid Selenium detection, you should see https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver/52108199#52108199 and the solution for that here: https://stackoverflow.com/a/52108199
