### ISSUE TITLE
Do not close the browser automatically when an error occurs.

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#956]
I use raw_parameter_script.py method run directly from python, I get error when I run
Summary:
i pass missing data, it throws an error while browser is still open, and closes python itself, but browser doesn't close itself with python. Is there any method to solve it?

"""
sb = raw_parameter(func, settings) #return sb setting
        sb.setUp()
        try:
            getattr(sb, func)()
        except:
            sb.tearDown()
            del sb
        else:
            sb.tearDown()
            del sb

**Comment by mdmintz** [comment]
When using the raw_parameter_script way, you must pass in **all** parameters that would've been initialized by pytest. The default values would not get set otherwise. This is the advantage to using pytest, as it does all that for you. Here's an example of a complete script written in that way (as taken from https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py):

```python
pure_python = False
try:
    # Running with Pytest / (Finds test methods to run using autodiscovery)
    # Example run command:  "pytest raw_parameter_script.py"
    from .my_first_test import MyTestClass  # (relative imports work: ".~")

except (ImportError, ValueError):
    # Running with pure Python OR from a Python interactive interpreter
    # Example run command:  "python raw_parameter_script.py"
    from my_first_test import MyTestClass  # (relative imports do not work)

    pure_python = True

if pure_python:
    sb = MyTestClass("test_basics")
    sb.browser = "chrome"
    sb.headless = False
    sb.headed = False
    sb.start_page = None
    sb.locale_code = None
    sb.protocol = "http"
    sb.servername = "localhost"
    sb.port = 4444
    sb.data = None
    sb.environment = "test"
    sb.user_agent = None
    sb.incognito = False
    sb.guest_mode = False
    sb.devtools = False
    sb.mobile_emulator = False
    sb.device_metrics = None
    sb.extension_zip = None
    sb.extension_dir = None
    sb.database_env = "test"
    sb.log_path = "latest_logs/"
    sb.archive_logs = False
    sb.disable_csp = False
    sb.disable_ws = False
    sb.enable_ws = False
    sb.enable_sync = False
    sb.use_auto_ext = False
    sb.no_sandbox = False
    sb.disable_gpu = False
    sb._multithreaded = False
    sb._reuse_session = False
    sb._crumbs = False
    sb.visual_baseline = False
    sb.maximize_option = False
    sb.save_screenshot_after_test = False
    sb.timeout_multiplier = None
    sb.pytest_html_report = None
    sb.with_db_reporting = False
    sb.with_s3_logging = False
    sb.js_checking_on = False
    sb.report_on = False
    sb.is_pytest = False
    sb.slow_mode = False
    sb.demo_mode = False
    sb.time_limit = None
    sb.demo_sleep = 1
    sb.dashboard = False
    sb._dash_initialized = False
    sb.message_duration = 2
    sb.block_images = False
    sb.remote_debug = False
    sb.settings_file = None
    sb.user_data_dir = None
    sb.chromium_arg = None
    sb.firefox_arg = None
    sb.firefox_pref = None
    sb.proxy_string = None
    sb.swiftshader = False
    sb.ad_block_on = False
    sb.highlights = None
    sb.check_js = False
    sb.interval = None
    sb.cap_file = None
    sb.cap_string = None

    sb.setUp()
    try:
        sb.test_basics()
    finally:
        sb.tearDown()
        del sb
```

(Note that all args normally initialized by the pytest plugin must be initialized here.)
Also, (for future reference), paste code in a code block because otherwise I can't see the indentation.

**Comment by thanhvodad** [comment]
I know, I have this set up, complete, I mean during the run of the command, something happens, and it doesn't automatically .tearDown(), close the browser, I have to run pure_python on my app

**Comment by mdmintz** [comment]
Does it fail in the ``setUp()`` step, or in the ``try`` block? If anything goes wrong in the ``try`` block, the ``finally`` block is supposed to tear down the web browser.

**Comment by thanhvodad** [comment]
I've tried it sometimes it still happens, maybe it's too CPU, it can't execute the command, and it quits unexpectedly?

**Comment by mdmintz** [comment]
I'd need to see a stack trace. And my previous question still applies: Does it fail in the ``setUp()`` step, or in the ``try`` block? If anything goes wrong in the ``try`` block, the ``finally`` block is supposed to tear down the web browser.

**Comment by thanhvodad** [comment]
setup is successful, I noticed when my cpu is high, it turns on the browser and waits for a long time to load then an error occurs, sometimes timeout..., sometimes usb something, i while True: pytest
Do you have another communication channel, can you help me fix it, I will pay for your effort

**Comment by mdmintz** [comment]
If you're spinning up a lot of browsers at the same time and hitting high CPU usage, then that's more of a general Selenium issue than a SeleniumBase one. You can try the Selenium group on Slack to see if they can help you. I can be found there too sometimes.

**Comment by thanhvodad** [comment]
Thanks you, love proooo <3

**Comment by thanhvodad** [comment]
DevTools listening on ws://127.0.0.1:59039/devtools/browser/5f8a94a2-6cd1-4d0c-b49c-f61e2f08df3f
[15332:20888:0807/111846.528:ERROR:device_event_log_impl.cc(214)] [11:18:46.529] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.

**Comment by mdmintz** [comment]
https://stackoverflow.com/questions/61561112/how-to-solve-getting-default-adapter-failed-error-when-launching-chrome-and-tr for the question. https://stackoverflow.com/a/63270005 for the solution. It probably means your chromedriver is out-of-sync with your version of Chrome. Upgrade.
