### ISSUE TITLE
Support for BDD!

### ISSUE THREAD

**Issue by salunkhe-ravi** [seleniumbase/SeleniumBase#962]
Hello,

Do we have support for BDD(Gherkin) yet?

**Comment by mdmintz** [comment]
@salunkhe-ravi Yes, that already exists: https://github.com/pytest-dev/pytest-bdd
Given that SeleniumBase is technically just one giant plugin of the pytest ecosystem, it works with the other pytest plugins as well. Therefore, you can install all the pytest plugins that you need, and then run your tests as needed.

**Comment by mdmintz** [comment]
@salunkhe-ravi Support for ``behave`` BDD has been added! https://github.com/seleniumbase/SeleniumBase/tree/master/examples/behave_bdd

**Comment by salunkhe-ravi** [comment]
This is awesome @mdmintz ! Thanks for all the efforts baking this in...

Also, lately I came across a very efficient and much needed module for behave named as BehaveX. This is basically to support parallel execution in behave.

FYI.

https://github.com/hrcorval/behavex

**Comment by mdmintz** [comment]
@salunkhe-ravi For parallel execution, there's another option. The SeleniumBase Recorder can record and convert the ``behave`` scripts into ``pytest`` format, which can then be run multi-threaded easily.

To convert those scripts, you can use the ``behave`` GUI Desktop App:

``sbase behave-gui``  (Then add ``-D rec`` into the additional options section.)

<img width="400" alt="Screen Shot 2022-05-18 at 9 17 44 AM" src="https://user-images.githubusercontent.com/6788579/169092101-85832918-f6cf-4319-84be-03cd6089d124.png">

After clicking to "Run Selected Tests", they will be outputted as pytest scripts in the ``./recordings`` folder. For pytest auto-discovery/collection to work, make sure those tests start with ``test_``. Then you can run them multi-threaded like this:

``pytest -n=4``

You may need SeleniumBase ``3.1.1`` (just released) for the important Recorder upgrades to record everything properly, at least with the provided examples in https://github.com/seleniumbase/SeleniumBase/tree/master/examples/behave_bdd.
