### ISSUE TITLE
Cannot set timeout for assert_no_404_errors

### ISSUE THREAD

**Issue by frafra** [seleniumbase/SeleniumBase#965]
`assert_no_404_errors` uses a default timeout of 5 seconds, which cannot be changed.

**Comment by mdmintz** [comment]
I'll add the ability to change that timeout value in the next release.

**Comment by mdmintz** [comment]
@frafra Work completed as part of https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.64.0 (https://github.com/seleniumbase/SeleniumBase/pull/966)
