### ISSUE TITLE
How do I use seleniumbase without pytest?

### ISSUE THREAD

**Issue by alex4200** [seleniumbase/SeleniumBase#981]
I need to use `seleniumbase` without `py.test`, but only using python, i.e. I want to run some code using the following command:

`python mycode.py`

How can I do that with `seleniumbase`? How does my code need to look like?

**Comment by mdmintz** [comment]
Hi @alex4200, take a look at https://github.com/seleniumbase/SeleniumBase/blob/master/examples/raw_parameter_script.py
It's an example of a SeleniumBase script that you can run with pure ``python``. The key difference is that you must initialize all variables manually, and that you have to call ``setUp()`` and ``tearDown()`` manually too, as seen in the script.

**Comment by alex4200** [comment]
Thanks, that seems to work!
