### ISSUE TITLE
How to create a firefox profile?

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#987]
How to create a firefox profile?

**Comment by mdmintz** [comment]
@thanhvodad SeleniumBase automatically creates a Firefox Profile for you during tests. If you want all tests in the same test run to reuse that profile, just add: ``--reuse-session`` to your ``pytest`` run command, and then all tests will run through the same browser window session. If what you're trying to do is reuse a Firefox Profile from a previous test run, then that is blocked by open bugs on the Geckodriver / Firefox-WebDriver side: See https://github.com/mozilla/geckodriver/issues/1844 and https://github.com/mozilla/geckodriver/issues/1058
