### ISSUE TITLE
How to use classes after finding

### ISSUE THREAD

**Issue by thanhvodad** [seleniumbase/SeleniumBase#996]
Finds
find_elements = self.find_elements("ytd-rich-item-renderer")
And then use the found class to execute other api commands?

find_elements[1].show_elements()
find_elements[1].hover_on_element()

**Comment by mdmintz** [comment]
@thanhvodad Here's an example test that uses the similar ``self.find_visible_elements(selector)``:
https://github.com/seleniumbase/SeleniumBase/blob/master/examples/migration/protractor/example_test.py
